### ISSUE TITLE
Implement notify_push to deliver push notifications?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/talk-android#1008]
Hey, 

I wonder if you could implement [notify_push](https://github.com/nextcloud/notify_push#clients) to deliver push notifications?

Greetings, szaimen

**Comment by mahibi** [comment]
Hi @szaimen 
since I am not familiar with it yet, I cannot say much about it. But i guess @nickvergessen or @icewind1991 can?

**Comment by szaimen** [comment]
As @tobiasKaminsky pointed out, this will most likely not work on android due to background restrictions on android:
https://github.com/nextcloud/android/issues/7975#issuecomment-779070209
So I guess this issue can be closed then.

**Comment by nickvergessen** [comment]
This is not going to work. It requires an constantly open websocket. Byebye battery
