### ISSUE TITLE
"Start new conversation" action should not have intermediate step

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#101]
Currently you need to choose between starting a new conversation or joining via link. Starting a new conversation then opens another menu with "NEW PUBLIC CALL" (needs to be lowercased btw). This makes starting a call much too cumbersome.

Instead, the menu should be cut out. Tapping the + should directly lead to the select contacts screen, with "New public call" and "Join from link" as items above.

**Comment by mario** [comment]
Join via link is a completely separate thing and doesn't belong in the contacts screen.

When you select new conversation, you're lead to a contacts selection screen where you can invite people to your new conversation. If you don't tap on "NEW PUBLIC CALL" then it's a one-to-one OR a group call, whereas if you tap NEW PUBLIC CALL it's a public call.

This approach is well recognized and used in other similar apps, so I don't see what benefit we get from changing this well-known patterns?
