### ISSUE TITLE
Log is flooded with errors while offline

### ISSUE THREAD

**Issue by PVince81** [nextcloud/talk-android#1013]
### Steps

1. Install and configure Nextcloud Talk
2. Disable wifi and cell connection to go offline
3. Examine the logs (adb logcat)

### Actual result
Log is flooded with `MagicWebSocketInstance: Error : Unable to resolve host "$HOSTNAME": No address associated with hostname`.
This happens every few milliseconds.

### Expected result
The message should appear only once and then stop trying.
Maybe listen to the connection state to find out when it's ok to try again.

### Version
v8.2.0

@mahibi as discussed

**Comment by mahibi** [comment]
It's the second time now i failed to reproduce this behaviour..
@PVince81 can you still reproduce it?

**Comment by PVince81** [comment]
I just tried again with v12.0.0 alpha 13 and the error is still there, but two lines now:
```
05-19 14:41:51.259 27398 27456 D MagicWebSocketInstance: restartWebSocket: wss://xx.xx.com/standalone-signaling/spreed
05-19 14:41:51.260 27398 29980 D MagicWebSocketInstance: Error : Unable to resolve host "xx.xx.com": No address associated with hostname
```

It happens only if I open the app first.
Then if I switch apps and leave it in the background, the messages continue to flood.
They only stop if I stop the app by swiping it away from the task manager.

**Comment by PVince81** [comment]
This is a Nokia 6.1 with Android 10 (security update from 01.04.2021)

**Comment by PVince81** [comment]
yeah, this is against the company server
