### ISSUE TITLE
display error when using emojis

### ISSUE THREAD

**Issue by theoneandonly-vector** [nextcloud/talk-android#1029]
typing works correctly using the keyboard, but as soon as I select emojis it looks like this (you don't see what you type):
![Screenshot_20210224-101120](https://user-images.githubusercontent.com/10380051/108977713-1fbcdc00-7689-11eb-94ee-7f4a1b94c05e.jpg)

this doesn't happen in other apps I use.

it may happen because of this setting I use:
wm overscan 0,0,0,-70
(this removes the keyboard-gap on oneplus-devices)

**Comment by mahibi** [comment]
hi @theoneandonly-vector 
which version of the app are you using? was it also wrong with older versions of the app?

**Comment by theoneandonly-vector** [comment]
hi @mahibi 
I use the latest release-version (11.0.0), but the issue also appears on older verisons.

**Comment by jakobroehrl** [comment]
On my device I can't use the groups, nothing happens on click. It seams the android keyboard settings are overlaying them:
![image](https://user-images.githubusercontent.com/24530680/109287961-8d513f80-7824-11eb-93f8-2211468109ea.png)

**Comment by mahibi** [comment]
@jakobroehrl what's 
your device 
/android version
/app version?

**Comment by dorpauli** [comment]
@mahibi 
I got the same problem like @jakobroehrl but i can still navigate through emojis with switching. 

Device: OnePlus 7T
Android Version: 10 (Oxygen Os 10.0.16.HD65BA)
App Version: 11.0.0

**Comment by mahibi** [comment]
i will close this one as it is the same error as https://github.com/nextcloud/talk-android/issues/1900
didn't find any solution yet..
