### ISSUE TITLE
check results of Accessibility Scanner

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#1033]
https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor

some Notes from @jancborchardt :
- The background of the list view should be full white #ffffff, so the text contrast works
- The FAB needs a text label to be readable by screen readers. "New conversation" would be fitting
...

**Comment by AndyScherzinger** [comment]
background and FAB have been fixed on master lately: FAB (https://github.com/nextcloud/talk-android/commit/cf6b4c12e4cbc6fb9216945cb7bd2c79aec12b15) and list (https://github.com/nextcloud/talk-android/commit/adac29d756e2e02d82dc7366d219206cf58f2fec)
