### ISSUE TITLE
Ringback tone

### ISSUE THREAD

**Issue by markcs** [nextcloud/talk-android#104]
Hi!

When calling a person I don't hear any ringback tone, so it is hard for users to know that the call is actually connecting.

A ringback tone is standard when calling.  Can this be implemented?

**Comment by mario** [comment]
I'll consider it.

**Comment by jancborchardt** [comment]
This is super important for proper feedback. Are there standard Android sounds we can use?

**Comment by mario** [comment]
It's not a bug, however.

**Comment by mario** [comment]
To further comment on this, we can get ringtones but they are not in any way standard and you can't know which one is which. So I could put up a default ringtone, but it wouldn't be the same across platforms (it would be what you chose actually).

I'm unfortunately not aware of any open source/free sounds we could use? :(

**Comment by jancborchardt** [comment]
> So I could put up a default ringtone, but it wouldn't be the same across platforms

That's ok. It should be the default ringtone on each platform, like same as when you get a phone call on Android, or when you get a call on iOS etc.

**Comment by mario** [comment]
Sure, but the issue is about the sound when you are calling?

Because ringtone is already set for receiving call.

**Comment by markcs** [comment]
How does an open source app like Signal do it?  

Can't you get a file from somewhere like https://www.audioblocks.com/royalty-free-audio/computer-sound-effects, http://soundbible.com/suggest.php?q=tone&x=0&y=0 or https://freesound.org/ ?

**Comment by mario** [comment]
Or well, a public domain :)

**Comment by markcs** [comment]
Creative Commons Attribution 3.0 okay?

Creative Commons Attribution 3.0 is one of many CC Audio types. Creative Commons Attribution 3.0 put simply means you can use this audio but you must attribute your work to this person. If the audio is from Mike Koenig then you need to give him credit somewhere. That somewhere could be in the credits, the cd cover, or a link to the sounds page from your site.

**Comment by mario** [comment]
@markcs let me call in @schiessle as our resident legal expert :D

**Comment by jancborchardt** [comment]
@mario there is no standard sound for that? Like the one in the Android phone app

**Comment by mario** [comment]
@jancborchardt not as far as I know.

**Comment by schiessle** [comment]
@mario a sound file is just data used by our app, as such it doesn't have to be compatible with the GPLv3. Still we should make sure to pick a free license. CC-BY is completely fine. As said by @markcs we just have to mention the the author and the license

**Comment by mario** [comment]
@schiessle cool, thanks! @markcs feel free to find something that is CC-BY and is nice :D

**Comment by markcs** [comment]
http://soundbible.com/1869-Phone-Ringing-8x.html or http://soundbible.com/1868-Ringing-Phone.html ?

**Comment by mario** [comment]
Thanks @markcs

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/notifications/pull/117

Replace the audio file here when the license is valid ;)

**Comment by markcs** [comment]
HI Mario,

So you' decided not to implement this?  All calling apps I can think of have a tone that indicates that a call is being established. What is the difference to Nextcloud that makes this nor make sense?

Thanks
