### ISSUE TITLE
enable media playback within a conversation

### ISSUE THREAD

**Issue by sudwhiwdh** [nextcloud/talk-android#1043]
Use case for me would be to be able to play an audio or video file or embedded platform video in Nextcloud Talk in a conversation so that all participants can listen/view it in parallel.
This will be a welcome function, especially in the now mostly digital education work in schools and universities.

Related Issues for iOS & the Web Interface
https://github.com/nextcloud/talk-ios/issues/510
nextcloud/spreed#5280

**Comment by nickvergessen** [comment]
Closing until https://github.com/nextcloud/spreed/issues/5280 is solved
