### ISSUE TITLE
only works when being in the same wifi

### ISSUE THREAD

**Issue by DaCryptor** [nextcloud/talk-android#105]
Device 1: Samsung Galaxy A5 2017 (Android 7.0)
Device 2: BQ Aquaris X Pro (Android 7.1.1)

Nextcloud 13 including the talk-app is installed on my shared-hosting (all-inkl.com).

Works perfect when the two devices are in the same wifi, but when one of the two devices is connected via 4G/LTE, the phone rings, but I cannot hear or see the other person (black screen, no audio).

Any ideas?

**Comment by steffanson** [comment]
I experience the same issue with Nextcloud Talk **1.1.0 beta 1** on LineageOs 14.1 (Feb. 2018).

**Comment by mario** [comment]
Do you guys have TURN configured?

**Comment by steffanson** [comment]
> Do you guys have TURN configured?

I thought it was already setup as I use the standard config of the Nextcloud Talk addon, however as I see right now only the STUN server is configured (`stun.nextcloud.com:443`).

**Comment by DaCryptor** [comment]
@mario 
Can you please explain that to me?
I am just using the standard installation/configuration and have nothing changed.

**Comment by mario** [comment]
That is Stun which Nextcloud provides as a service if you dont want to host
your own. But in some cases you will also need to host and setup your own
TURN (I suggest coTurn)

**Comment by DaCryptor** [comment]
I do not think that I can install coTurn on my shared-hosting environment.
Any other options?

**Comment by mario** [comment]
@DaCryptor I guess you could either rent out a dedicated server (virtual or a real one) and install, or use a TURN service from one of the providers.

I'm happy to to answer all questions, but I do have to close this issue now because it's really not a problem with the app :)

**Comment by mario** [comment]
@DaCryptor it does not work because STUN cannot determine IP of one of your phones. TURN would solve this by relaying everything through it.

**Comment by steffanson** [comment]
@DaCryptor  @mario  Thanks for you hint. I now setup a `coTURN` server and calls over LTE now work as expected.

**Comment by sohamd99** [comment]
I have installed TURN but still WIFI to LTE Calls are not audible. @steffanson How it worked for you?

**Comment by sohamd99** [comment]
Please Help me @mario
