### ISSUE TITLE
Raise Hand (feature parity)

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/talk-android#1056]
The web version of Talk now supports to "raise hand" in calls (https://github.com/nextcloud/spreed/pull/4569)
The mobile client should support that too.

**Comment by mahibi** [comment]
in https://github.com/nextcloud/talk-android/pull/2715 the UI for raise hand and request assistance for breakout rooms was introduced.
However, the signaling messages for raise hands are not yet sent.
This still needs to be implemented, see:

https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/activities/CallActivity.java#L425

https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java#L193
