### ISSUE TITLE
Text block on sharing link

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#106]
When you share the link to a call, there’s a whole block of text being copied:

> Hello,
>
> I would like you to join a call with me.
> 
> You can join this call via https://…
> 
> Talk soon,
> Name

It feels a bit weird since it’s not written by yourself, and you would never send something like that to a friend or so cause it sounds like an advertisement.

Instead, let’s just go with copying only the link?

**Comment by mario** [comment]
And there was me being especially proud of this :P

It actually works really well with the people I've asked + it would also insert a password if the call you're sharing has a password :P

In addition, you're given a chance to modify this, are you not?

**Comment by jancborchardt** [comment]
Yeah I could modify it, but when I want to share something I want it to be quick. Needing to delete all the prewritten text is a bit strange. :\

If there’s a password, the text could simply be:

> https://…
> Password: ****

**Comment by mario** [comment]
Why don't you rather come up with a "friendlier" text that I'd be happy to include? One that would work for both friends and business associates?

**Comment by jancborchardt** [comment]
Simple and versatile would be:

> Join the call "<call name>" at https://…
> Password: ****

**Comment by Ivansss** [comment]
I will use that text for the iOS app then.
At the moment we are using:
"You can join to this call: https://..."

**Comment by mario** [comment]
OK, sure. I dislike it, but sure :P

**Comment by Ivansss** [comment]
@jancborchardt  What about the subject if user wants to share the call by email?

**Comment by jancborchardt** [comment]
@Ivansss let’s say »Nextcloud Talk invitation«?

**Comment by mario** [comment]
Done!
