### ISSUE TITLE
Change avatar on web, see inconsistent behaviour

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#1067]
- have no avatar
- log in on Android Talk, see default avatar (one character, colored background)
- change avatar on web
- open app, still see old avatar
- go to setting, see new one
- go back, still see old one

This happens on local test server (http://localhost/nc)

**Comment by nickvergessen** [comment]
btw the default avatar is 2 letters since I think Nextcloud 18/19

**Comment by tobiasKaminsky** [comment]
> btw the default avatar is 2 letters since I think Nextcloud 18/19

The app always uses /index.php/avatar/$name/$size, so this is already correct.
There is no fallback/manual computation.

**Comment by tobiasKaminsky** [comment]
This will be fixed with #1092

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky #1092 has been merged, so close?
