### ISSUE TITLE
Not possible to join via link

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#107]
When you have the dialog asking for the »Conversation link«, it’s impossible to paste a link cause the keyboard overlaps that dialog.

Instead let’s start by using standard Android dialogs? ;) We can experiment on top of that when the basics work.

**Comment by mario** [comment]
I will check this.

Bottom sheet is the standard dialog and using it across the app gives a consistent experience and nicer ability to animate things etc etc.

**Comment by mario** [comment]
Can't reproduce. What version of Android?

**Comment by mario** [comment]
Found it. Now have to find a way to fix it :P

**Comment by mario** [comment]
Found it! Thanks for reporting this.
