### ISSUE TITLE
Open attachement without using nextcloud app client

### ISSUE THREAD

**Issue by tigermick** [nextcloud/talk-android#1098]
Hi,
Thanks for this app and thanks so much for continuing to develop it with new features.
The ability to send a file without using nextcloud app client is so cool but ... when you have an attachment in conversation, if you try to download it, talk goes back to nextcloud app client. will it be possible to add the ability to download directly with direct link with a simple browser for example?
thank you

**Comment by Hanskes** [comment]
This happened to be something I also wanted to ask about. For images it would be nice if they could be displayed larger within the talk app, without being redirected to the nextcloud app. Just like in most other chat apps.

**Comment by mahibi** [comment]
completely agree! hope to find time for this..

**Comment by tigermick** [comment]
> completely agree! hope to find time for this..

Thank you very much for considering this request.

**Comment by starypatyk** [comment]
I have simplified the prototype code in the [image_preview_internal](/nextcloud/talk-android/tree/image_preview_internal) branch. I have removed most of the code auto-generated by Android Studio. It should be now much easier to understand - the code in the FullScreenImageActivity got reduced to just one method. :wink:

I have also changed the background color to black - seems to work best for previewing images - even in cases when the user uses light mode on the phone.

Would it make sense to start a PR with this branch?

I am aware of the following things that likely need to be done before this can be merged.

- Implement zooming and assess if the SimpleDraweeView is an appropriate component to display the image.
- Determine what image size to use (currently arbitrarily hard coded to be max 2048x2048).
- Clean-up communication between MagicPreviewMessageViewHolder and the FullScreenImageActivity - probably just the image ID should be passed and the FullScreenImageActivity would retrieve all other data by itself.
- Provide some additional UI elements - e.g file name and a menu allowing additional operations - like opening the image in the main Nextcloud app.

**Comment by starypatyk** [comment]
Regarding zooming - I have made a quick experiment based on this discussion on StackOverflow:
[How I can implement zoom in Fresco Library?](https://stackoverflow.com/questions/32223363/how-i-can-implement-zoom-in-fresco-library)

[PhotoDraweeView](https://github.com/ongakuer/PhotoDraweeView) seems to work OK, but I am not sure, if it is a good idea to introduce a dependency on a library that seems not to be maintained for over two years.

Using the "official" [zoomable](https://github.com/facebook/fresco/tree/master/samples/zoomable) sample should be more robust. But making an experiment with this sample requires a better understanding of gradle than I currently have. :wink:

**Comment by nickvergessen** [comment]
Current planned steps are taken from iOS Talk comparison:

* txt/md: no editing, only plain text, downloaded, with local share (to another apps)
* jpg: all normal
* png: no special handling of transparent background, just white background
* gif: preview is not animated, downloaded file is animated
* audio/video: download, play, local share

**Comment by mahibi** [comment]
@starypatyk thanks for simplifying the prototype code! 
because we have to meet even more requirements i created another branch and created the PR https://github.com/nextcloud/talk-android/pull/1138 which also contains your code.
As we also have to deal with large files there is the need to download the files beforehand and show progress.
And as we also have to provide support for videos and text files the use of fresco will not be be sufficient.
Thanks very much for your help and you are welcomed to contribute on the PR if you like. As @tobiasKaminsky and me will work on this branch this week, we just have to make sure there won't be any huge merge conflicts.
