### ISSUE TITLE
Screens overlap

### ISSUE THREAD

**Issue by fantasio31** [nextcloud/talk-android#111]
Hi,

I have an issue when navigating between scrren. screens are overlapped.
Here is the scenario:
 1) Open Nextcloud Talk android App
 2) go to Parameters view
 3) click on "private life" (i have it in french so it is "Vie privée") ==> a popup ask me to choose the application to open the link
 4) Click on "Cancel" (it's "Annuler" on my French Xiaomi phone) ==> the popup is closed
 5) click on "Contacts" to open the contact view ==> Parameters and Contacts screens are ovelapped.

My configuration:
 - phone: Xiaomi Redmi 3 Pro with MIUI 9 (8.2.8.1 Beta) / Android 5.1.1
 - NextCloud version : 1.0.14

**Comment by mario** [comment]
Hm? Can you show me the screenshot where this "private life" is?

**Comment by fantasio31** [comment]
Here are the screens:
 - One with "Vie Privée"
 - The other one showing the overlap
![screenshot_2018-03-02-11-03-35-665_com nextcloud talk2](https://user-images.githubusercontent.com/23166621/36893924-16b02a84-1e0a-11e8-95cc-5f9262d99fc0.png)
![screenshot_2018-03-02-11-03-46-140_com nextcloud talk2](https://user-images.githubusercontent.com/23166621/36893925-16e31142-1e0a-11e8-9166-3bc47e9ec894.png)

**Comment by mario** [comment]
Thanks, I'll investigate :)

**Comment by mario** [comment]
Could you try the beta please? I couldn't reproduce there: https://play.google.com/apps/testing/com.nextcloud.talk2

**Comment by fantasio31** [comment]
Same behavior. 

Le 3 mars 2018 19:19:00 GMT+01:00, "Mario Đanić" <notifications@github.com> a écrit :
>Could you try the beta please? I couldn't reproduce there:
>https://play.google.com/apps/testing/com.nextcloud.talk2
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/talk-android/issues/111#issuecomment-370168460

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by mario** [comment]
I'll need to test this on Android 5, since I can't reproduce at all :(

**Comment by mario** [comment]
@xXSTrikeXx can you reproduce this?

**Comment by xXSTrikeXx** [comment]
@mario No. I cant reproduce. When I click on privacy ("private life") it doesnt open a new layer. Talk redirects me to chrome and it will open the URL there. :wink:

**Comment by fantasio31** [comment]
I have some browsers (firefox, firefox klar ans chrome) but is none defined as default. My MIUI system always ask me which one i want to use to open a web link.

Le 6 mars 2018 00:14:14 GMT+01:00, xXSTrikeXx <notifications@github.com> a écrit :
>@mario No. I cant reproduce. When I click on privacy ("private life")
>it doesnt open a new layer. Talk redirects me to chrome and it will
>open the URL there. :wink:
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/talk-android/issues/111#issuecomment-370601791

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by mario** [comment]
I also get a choice of browsers, but no overlap @fantasio31  :-/

Did you maybe do some rotation or something?

**Comment by mario** [comment]
Can't reproduce even on Android 5.x :(

**Comment by xXSTrikeXx** [comment]
Maybe its only China's software:stuck_out_tongue_closed_eyes::grinning:

**Comment by fantasio31** [comment]
May be 😁.
Anyway opening the conversation view cleans corrently the screen and the display is ok.

Le 7 mars 2018 08:41:25 GMT+01:00, xXSTrikeXx <notifications@github.com> a écrit :
>Maybe its only China's software:stuck_out_tongue_closed_eyes::grinning:
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/talk-android/issues/111#issuecomment-371051206

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by mario** [comment]
@fantasio31 does the same happens with 1.1.0beta2?

**Comment by mario** [comment]
@fantasio31 what about newest beta? :D

**Comment by splitt3r** [comment]
![Version](https://user-images.githubusercontent.com/1869584/37731419-54268e20-2d42-11e8-9b9b-26aa132813aa.png)

Also the bottom bar overlaps the version number now.

**Comment by mario** [comment]
@splitt3r this one I know. :) Already fixed - https://github.com/nextcloud/talk-android/commit/fff270c36b9e0fd808c4692fa1470128b6d9d7c9

**Comment by fantasio31** [comment]
My issue is not fixed in the last beta version.
Also tried with the F-Droid version, same issue.

**Comment by mario** [comment]
@fantasio31 yea I don't know :( I still can't reproduce that one :(

**Comment by fantasio31** [comment]
anyway to activate logs or to set a debug mode in order to help you ?

**Comment by mario** [comment]
Uh, how good are you with development? Android Studio + Vysor + TeamViewer would help? :D

**Comment by fantasio31** [comment]
I work as developper, but not an Android one ;).

When I'll have time to invistigate (when my child will not be here), I could try to invistigate.

**Comment by mario** [comment]
Awesome! :D

So I'd need the above + git checkout of this repository :)

**Comment by mario** [comment]
@fantasio31 think I got it. Look for the next release soon ;)

**Comment by mario** [comment]
@fantasio31 better now? :)

**Comment by fantasio31** [comment]
Hi,

Yep, it's ok now. Thanks !

**Comment by mario** [comment]
:)
