### ISSUE TITLE
Add new talk, Layout is under the keyboard

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/talk-android#112]
Add new Talk and name the talk, the layout of the talk is under the keyboard. Pic says more then words.

![inkedscreenshot_2018-03-05-10-05-02_li](https://user-images.githubusercontent.com/1523741/36966507-44efa190-205d-11e8-9058-20649b5e7b84.jpg)
![inkedscreenshot_2018-03-05-10-05-08_li](https://user-images.githubusercontent.com/1523741/36966521-4e876698-205d-11e8-81a3-7e8a67dd5fd8.jpg)

The layout goes on top after entering some letters.

Another hint: When you choose which contacts you invite the "Done" Button at the end is very slim.

**Comment by mario** [comment]
@xXSTrikeXx what android version?

**Comment by xXSTrikeXx** [comment]
@mario Android 6.0

**Comment by xXSTrikeXx** [comment]
Works great, but please make the "Done" Button bigger :)

**Comment by mario** [comment]
@xXSTrikeXx I did already?

**Comment by mario** [comment]
It's 64dp instead of 32dp.

**Comment by mario** [comment]
Not enough @xXSTrikeXx ?

**Comment by mario** [comment]
Yup, let me know!

**Comment by xXSTrikeXx** [comment]
@mario yup 64dp is enough. 128dp is too much :D 

but for any reasons its not accepted while adding new talks. Tested it now on my device and AVD ;) It´s still the old  :D 

![unbenannt](https://user-images.githubusercontent.com/1523741/36993130-4904b0ae-20ad-11e8-979b-757a647a89e4.jpg)

**Comment by xXSTrikeXx** [comment]
Yep, your changes even to 128dp is not changing anything ;)

**Comment by mario** [comment]
Will investigate.
