### ISSUE TITLE
update to Java11

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#1125]
- [ ] blocked by https://github.com/nextcloud/talk-android/issues/1548
- [ ] blocked by https://github.com/nextcloud/talk-android/issues/1549

conflicts with Java 11 would arise here:
- [x] https://github.com/nextcloud/talk-android/issues/1035

Currently the java version in Android Studio must be set to java 8 to compile this project.

Feel free to comment any thought what has to be done to get this project to run with Java 11

after this is solved:
- [x] remove hint from readme.md that java8 is necessary

**Comment by mahibi** [comment]
conflicts with Java 11 would arise here:
https://github.com/nextcloud/talk-android/issues/1051
https://github.com/nextcloud/talk-android/issues/1035

**Comment by AndyScherzinger** [comment]
Issue I experienced trying to use Java 11 with Android Studio < 4.3 was the code generation libs mix of lombok and parceler (maybe + updating to latest kotlin/gradle versions for AS4.2+) So like with the files client we should get rid of lombok at some point.

**Comment by mahibi** [comment]
the newest Android Studio versions can be used like mentioned in https://github.com/nextcloud/talk-android/pull/1692

**Comment by mahibi** [comment]
finally done with https://github.com/nextcloud/talk-android/pull/2061
