### ISSUE TITLE
Optimize grey tones according to WCAG

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1129]
At the moment the participants list is "greying-out" items for participants who are offline. It basically sets alpha to ```0.38``` which matches Material Design's value for disabled text. Unfortunately the accessibility scanner doesn't white like that (contrast ratio to low 2.x ...) So the question is do we want to use "disabled text color" (like material) or do we rather use the "secondary / medium-emphasis test color which WCAG would be fine with.

So calling @jancborchardt to the rescue :)

|now|medium emphasis text colored|
|---|---|
|![device-2021-04-14-131825](https://user-images.githubusercontent.com/1315170/114714897-d6a51200-9d32-11eb-9581-da316d6ae64a.png)|![device-2021-04-14-150555](https://user-images.githubusercontent.com/1315170/114715019-f2101d00-9d32-11eb-9f2f-abd36aefad11.png)|

**Comment by jancborchardt** [comment]
I’d say the fixed version is much nicer for accessibility. Just one thing, it would still be nice to have a little bit of contrast between the name and subline, so we probably need to bump up the darkness of the name text color a bit?

**Comment by AndyScherzinger** [comment]
As discussed in the chat we implement the "medium emphasis text colored" version
