### ISSUE TITLE
Too small "done" button

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/talk-android#113]
yup 64dp is enough. 128dp is too much :D 

but for any reasons its not accepted while adding new talks. Tested it now on my device and AVD ;) It´s still the old  :D 

![unbenannt](https://user-images.githubusercontent.com/1523741/36993130-4904b0ae-20ad-11e8-979b-757a647a89e4.jpg)

Created this new error, to have a better log and not all in one issue :D 
ref: #112
commit 07313680caaaf87c1757993dbdc2a99e063b5123

**Comment by mario** [comment]
I've set it to 48dp. Looks really good that way. 64dp is too much.

**Comment by xXSTrikeXx** [comment]
You're right! :grinning:
