### ISSUE TITLE
low contrast text color on mention chip-views on dark theme

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1131]
see screenshots

|dark|light|
|---|---|
|![device-2021-04-14-185814](https://user-images.githubusercontent.com/1315170/114749812-9d30ce80-9d53-11eb-938c-d84448fdd2f1.png)|![device-2021-04-14-185856](https://user-images.githubusercontent.com/1315170/114749825-a15cec00-9d53-11eb-9bd3-2b170cf68e8a.png)|

**Comment by AndyScherzinger** [comment]
@jancborchardt @nextcloud/designers the question is: do we change the text color for dark on the chip view (mentioned thingy) or do we change its background color?

**Comment by jancborchardt** [comment]
Let’s definitely change the text color for dark on the mention chip, yep! :) Should just be the same as for the light mention chip.

We could additionally reduce the intensity of the mention chip background to not be full white but e.g. with a bit of transparency so it’s not so intense of a contrast?

**Comment by AndyScherzinger** [comment]
Both optimizations sound good 👍

Thanks for the feedback ❤️
