### ISSUE TITLE
Findbugs

### ISSUE THREAD

**Issue by valentine-sys** [nextcloud/talk-android#1134]
plugin with id 'findbugs' not found

what shoud I do
the findbug is deprecated

**Comment by mahibi** [comment]
which java version do you use? it might be related.

anyway it's time for this project to switch to spotbugs, i will try to find some time for this soon

**Comment by AndyScherzinger** [comment]
Hi @valentine-sys please update to latest master which moved from FindBugs to SpotBugs and works fine on our CI pipeline/builds.
If the issue still persists, please re-open.
