### ISSUE TITLE
Make sharing vcard files display better

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1135]
## Steps to reproduce
1. Create a contact in your contacts
2. Share the vcard (.vcf) to a talk conversation
3. Clicking the file should allow adding the contact to your phones address book app

### Expected behaviour
It looks appealing and clear that it is a contact, maybe some meta data is displayed (FN, photo?) Check https://github.com/nextcloud/spreed/issues/5498 for potential APIs

### Actual behaviour
![Screenshot_2021-04-19-11-13-22-765_com nextcloud talk2](https://user-images.githubusercontent.com/213943/115211950-58fd4f80-a100-11eb-826b-3f13bd9926df.jpg)

**Comment by AndyScherzinger** [comment]
I minor change already present on master: show the right icon (as in contacts mimetype icon).

**Comment by AndyScherzinger** [comment]
@nickvergessen please re-test. I did some changes a while ago so the mimetype is correctly mapped and thus the icon too which also meant we trigger the "open action" with a proper mimetype and my Android phone offers to open it with the contacts app which being chosen then does the import. So seems closed.... aaaaand your welcome ;)

**Comment by nickvergessen** [comment]
No, there are further improvements required, which might need API work in talk or somewhere else first, to avoid dav implementation in talk clients:
* Show the image of a contact
* Show the FN (full name) property of a contact
