### ISSUE TITLE
Share a location

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1136]
Server ref https://github.com/nextcloud/spreed/issues/1478

It should be possible to share a location from e.g. Google Maps to a Talk chat
Also locations shared by others should be displayed somehow and allow to open in a Map app

**Comment by mahibi** [comment]
documentation for the message containing the location:

https://github.com/nextcloud/spreed/issues/1478#issuecomment-827641948

https://nextcloud-talk.readthedocs.io/en/latest/chat/#share-a-rich-object-to-the-chat

https://github.com/nextcloud/server/blob/master/lib/public/RichObjectStrings/Definitions.php#L421-L451
