### ISSUE TITLE
Call is interrupted when switching to another app.

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/talk-android#1144]
How to reproduce:
1) join a call with audio;
2) Minimize talk or switch to another app;

Expected behavior:
The call is not interrupted and you can keep talking/listening

Actual behavior:
The call is interrupted (at least the call audio stops)

Phone: xiaomi redmi note 9s
Talk version: v11.2.0 RC1
Android version: 10

**Comment by nickvergessen** [comment]
Duplicate of #957
