### ISSUE TITLE
Own video preview gone

### ISSUE THREAD

**Issue by maulwuff** [nextcloud/talk-android#117]
Since the last 2 betas (currently beta4) the display of the own video picture in the top right corner is gone.

It only appears while switching apps. Either to or from to the talk app.

**Comment by mario** [comment]
Yes, because the video is disabled by default. Check the control buttons on the bottom of the call and enable it?

**Comment by maulwuff** [comment]
It is of course ;-)


Am 17. März 2018 11:36:39 MEZ schrieb "Mario Đanić" <notifications@github.com>:

**Comment by mario** [comment]
It is what? Enabled or disabled? :D

**Comment by maulwuff** [comment]
Sorry, enabled. Let me try a screen recording

Am 17. März 2018 11:43:46 MEZ schrieb "Mario Đanić" <notifications@github.com>:

**Comment by mario** [comment]
Sure. Also tell me what Android version and what phone.

**Comment by maulwuff** [comment]
Just tried to do a video call with a bq aquaris m5, using the same beta version. It turns out, that neither phone is receiving a video stream. It's all black.
behavior is the same refarding the preview video, like shown in the screen capture above.

The m5 has Android 6.0.1

Video works with the current stable Version from the play store.

**Comment by mario** [comment]
@maulwuff I'll build a special version for you to try. Can you please let go to "About" for both phones, and let me know what it says for "MODEL"?  Thanks!

**Comment by realbout** [comment]
Hello there,

i got exactly the same problem, but with different phone. We have two LG G5 h850 running on Android 7.0.
On the Tablet (Samsung Galaxy S2 t810 [Exynos]) it runs fine with own videopicture.

Havent testet beta4 right now, but with beta 1 to 3 it was fine.

**Comment by maulwuff** [comment]
Of course, am I just waiting for play store update to appear? 

Am 17. März 2018 15:56:35 MEZ schrieb "Mario Đanić" <notifications@github.com>:

**Comment by mario** [comment]
@realbout can you give me the same? Go to about phone and tell me what it says under the model? Then send me an email at: mario @ nextcloud.com.

**Comment by mario** [comment]
@maulwuff well you need to send me an email: mario@nextcloud.com so I can give the APK to you for installation. But you do need to give me models before that :P

**Comment by mario** [comment]
@realbout also not sure I understand, what version are you on of the Talk app? Because you say beta 1-3 work and you haven't tested 4 yet?

**Comment by maulwuff** [comment]
Done

Am 17. März 2018 17:26:48 MEZ schrieb "Mario Đanić" <notifications@github.com>:

**Comment by realbout** [comment]
@mario i'll send you a email soon and give you the phone data, i havent it here right now. To your other question. I'm currently on 1.1.0 - and i've tested 1.1.0beta4 a few minutes ago, there is the same problem, no video in the right upper corner and no video on the called persons screen. Yes, video was enabled.

**Comment by mario** [comment]
@realbout ok, send me the email and I'll send you the test APK to install.

**Comment by realbout** [comment]
@mario on my Phones, under "about phone" - "hardware information" - "model number": LG-H850
Android version: 7.0
Android security patch level: 1. october 2017
I hope this helps. Now i send you the email with the same information.

**Comment by realbout** [comment]
@mario you've got it.
Got some mails with Mario, he send me a version which works perfectly fine. Thanks again Mario!

**Comment by maulwuff** [comment]
For me too 👍

**Comment by mario** [comment]
👍 

Thanks for testing!

**Comment by mario** [comment]
Rolled this out to beta @realbout and @maulwuff in the Play Store - so you should be able to go back to official deployments soon. Thanks for the patience and testing!
