### ISSUE TITLE
Not displaying images

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#1190]
## Steps to reproduce

1. Receive the image in the conversation.
2. Tap on an image to view it in full size.

The image is not displayed. Only a black background with three dots appears (kebab menu).

I also noticed that after tapping on the image there is no reaction for a long time. This confuses the user. Doesn't know if the application worked properly. In my opinion, there should be a loading wheel or other information about the image loading.

## Device information

**Android version:** 10

**Talk version:** 12.0.0 Alpha 08

**Comment by mahibi** [comment]
> The image is not displayed. Only a black background with three dots appears (kebab menu).
does this happen always for the same file or was it random?
which image type was it?

> I also noticed that after tapping on the image there is no reaction for a long time.
how long is "long time"? a few seconds.
this sounds like a problem with the DownloadFileToCacheWorker which starts with a delay. I think are ways to accelerate the worker-starts but had no time to have a closer look yet.

**Comment by Valdnet** [comment]
> does this happen always for the same file or was it random?

Yes. This always happens for the same file.

> which image type was it?

It is JPG.

> how long is "long time"? a few seconds?

The transition time is 4 seconds.

I noticed that only for this file there is no progress in loading the image as is the case with other images.

**Comment by mahibi** [comment]
Is it a file that you would provide me via mail or rather not?

**Comment by Valdnet** [comment]
@mahibi I can send an image that doesn't work in Talk. To what email address?

**Comment by mahibi** [comment]
great thanks,
dev@mhibbe.de

**Comment by Valdnet** [comment]
@mahibi Image sent 😉.

**Comment by mahibi** [comment]
thanks @Valdnet 
may have a look at the weekend i guess

**Comment by mahibi** [comment]
@Valdnet this seems to be a problem with high resolution images.

I get the error
java.lang.RuntimeException: Canvas: trying to draw too large(192000000bytes) bitmap.

will have a closer look

**Comment by Valdnet** [comment]
@mahibi Thanks for checking the problem 😉.

**Comment by mahibi** [comment]
TODO copy solution from files app https://github.com/nextcloud/android/blob/f50d805e4a5e27c2ff30f53848c5ffaebcbf2c41/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java#L524

**Comment by mahibi** [comment]
@Valdnet if you want you are welcomed to test the PR https://github.com/nextcloud/talk-android/pull/1283 by scanning the QR code to install the apk..

**Comment by Valdnet** [comment]
@mahibi I tested the Talk QA app. Works properly now 👍.
