### ISSUE TITLE
Patched ChatKit Implementation missing

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1197]
see gradle file

```
implementation('com.github.mario:chatkit:c6a61767291ddb212a2f4f792a2b6aaf295e69a5', {
        exclude group: 'com.facebook.fresco'
})
```

@mario Any chance you have a backup somewhere which you could push so we can fork/transfer it? Or remember what you pathed? ❤️

**Comment by AndyScherzinger** [comment]
Same for the fresco patched actually xD

**Comment by mahibi** [comment]
i forked all repos..
https://github.com/mahibi

**Comment by nickvergessen** [comment]
Forks have been moved to the nextcloud Org.

Build adjustment in #1205
