### ISSUE TITLE
Allow text chat for clients without camera or microphone

### ISSUE THREAD

**Issue by ndom91** [nextcloud/talk-android#121]
Since Mario quickly and incorrectly closed my last issue - here it is again. I do specifically mean the webapp!

Currently users without a microphone or camera get enumerateDevices() fail and then the UI simply says "Error while accessing microphone & camera" and does not load the user list, room list, anything.

They shoudl still be allowed to text chat, right?

If there is a workaround currently available, please point me in the right direction. I've been playing around with ../spreed/js/webrtc.js to disable the requirement of camera and mic to load, but have not been fruitful.

**Comment by mario** [comment]
All good :P

**Comment by Joe7new** [comment]
@mario Is may problem a similiar one ?: When I try to connect from mobile app to desktop (without camera and micro)and vice versa  sometimes no connection is established (but somestimes it is !).  Connection to notebook with cam and micro is no problem!

regards, Joe

**Comment by tobiasKaminsky** [comment]
This is more than 2,5 years old, please open up a new issue.

**Comment by Joe7new** [comment]
I haven't noticed the date, sorry.  will open new issue.. 
regards, Joe
