### ISSUE TITLE
Always show the microphone button in a video chat when using "push to talk"

### ISSUE THREAD

**Issue by steffanson** [nextcloud/talk-android#122]
Right now the control buttons, including the microphone buttons, fade out after a few seconds. 

In order to talk again by "push to talk", you got to tab first on the screen to let the buttons fade in again before you can hold the microphone button. IMHO this is annoying and it could be implemented more comfortable.

For instance, you can add an option for "push to talk" in the settings to show the "push button" either "always" or let it "fade away" as it's currently implemented.

What do you think?

**Comment by mario** [comment]
No, sorry. More options are more annoying than a second it takes for the button to appear. I'm open to better options if you have them though :)

**Comment by steffanson** [comment]
> No, sorry.  More options are more annoying than a second it takes for the button to appear. 

That's too bad. There are very few options there; I would also vote for an expert settings section. ;-)


> I'm open to better options if you have them though :)

Suggestion which come to my mind:
* When buttons are fade out: indicate that push to talk is active, long press anywhere on the screen triggers a "push"
* When mute, don't hide the microphone button

**Comment by mario** [comment]
As someone who added Expert option in the vanilla Nextcloud app, people are more confused by the option than ever :)

I will consider your other suggestions.

**Comment by mario** [comment]
In 2.1 if you use a voice-only call the buttons don't fade out. Is that good enough for you @steffanson? :)

**Comment by mario** [comment]
Poking @steffanson again! :)

**Comment by mario** [comment]
Closing for now as I consider the gist of the issue resolved.
