### ISSUE TITLE
Can not rejoin a call without leaving the conversation

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1232]
## Steps to reproduce
1. With user A join the call in the web
2. With user B configured in the Android app join the call
3. B: tab the red button
4. B: click on audio call icon again

### Expected behaviour
User B is back in the call

### Actual behaviour
User B sees the call screen waiting for others
User A is alone in the call
There is no server connection done as User B

## Device information

**Device:** Emulator

**Android version:** 10

**Talk version:** master

## Server information

**Nextcloud version:** master

**Talk version:** master

**Custom Signaling server configured:** yes

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

**Comment by mahibi** [comment]
this is solved by https://github.com/nextcloud/talk-android/pull/1655
