### ISSUE TITLE
Align stable branch naming pattern with files app

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1238]
I added https://github.com/nextcloud/talk-android/pull/1237/commits/2d72c198aebf10dccede27c0c80a3fce4977d293 for the `v11.x` branch so all our Github actions also run on PRs targeting a stable branch. It didn't work before since (as you can see) the naming pattern on the Android talk repo is different from the files app.

I order to make it easier to re-use solutions we have in palce regarding automation to adapt the files app's naming schema.

So all stable branches should be renamed, e.g. `v11.x ` --> `stable-11`
You might spot the slight difference since the files app also adds the minor version number. This is due to the fact that the files app doesn't follow a version scheme that must match the server version. It also doesn't matter for our automation since `stable-*` will work just fin in both scenarios. 😄 

cc @mahibi @nickvergessen and (due to a possible impact on brander app) @tobiasKaminsky (just to be sure/save)

**Comment by tobiasKaminsky** [comment]
Fine with me :+1: 
Branding, if needed, I can/will take care of

**Comment by mahibi** [comment]
Also fine with me!

**Comment by AndyScherzinger** [comment]
Done and merged via #1240
