### ISSUE TITLE
Screen / Desktop sharing, Android Talk can't see

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/talk-android#124]
So I am testing a demo instance of nextCloud. Installed the Talk app on the demo server, and I have Talk-Android on my android 7.1 phone.

I open the demo instance in Firefox, go to talk, and start sharing something on my desktop. So far as I can tell in firefox, it's correctly sharing the desktop.

However, on my phone, all I see is a black screen. It seems that desktop / screen sharing to/from Android is not working.

**Comment by mario** [comment]
Well not a bug since we never supported this. But I'll work on this eventually :)

**Comment by BloodyIron** [comment]
Well, I wasn't sure if it was a bug or not. But I think others are going to want this kind of functionality, and I anticipate there are those that would get confused about it "not working". As there is no information saying "Screen/Desktop Sharing doesn't work with mobile users". A bit surprised it didn't work out of the box as I anticipated it would encode/send the video content in the same way as a camera source.

Is desktop/screen sharing Peer-to-Peer like the voice/camera content is?

**Comment by mario** [comment]
I know, I know. It is p2p, but the issue is mostly from the mobile perspective where screen estate is limited and I need to decide how to show this.

For 1.2 I'm working on re-working the call UI, so maybe I can do this too.

**Comment by BloodyIron** [comment]
Is desk/screen sharing P2P even when using a desktop/browser client?

Perhaps pinch to zoom or something on mobile/tablet might be a good idea?

**Comment by mario** [comment]
It should be, yes :)

**Comment by johnfelipe** [comment]
screensharing for android is featured?
if not when release a version with that feature?

**Comment by mario** [comment]
@johnfelipe as soon as I get the time or someone contributes this :)

**Comment by mario** [comment]
@danxuliu and @nickvergessen - would any of you be so kind to tell me what's the signaling difference when receiving a screen, apart from roomType being "screen"? Am I supposed to send different messages etc?

**Comment by Ivansss** [comment]
@mario There is no difference apart from setting `roomType="screen"` in the signaling messages.

**Comment by mario** [comment]
Basic implementation was done for 3.2.
