### ISSUE TITLE
Call view broken for large group calls

### ISSUE THREAD

**Issue by schiessle** [nextcloud/talk-android#1241]
Today I joined the company call with the latest Android app (v11.1.0).

This is how the call view looks like:

portrait:

![image](https://user-images.githubusercontent.com/1589737/117823942-51981480-b26e-11eb-9c52-01bd1a0512bf.png)

landscape:

![image](https://user-images.githubusercontent.com/1589737/117823853-388f6380-b26e-11eb-92c8-08dd8e5084ab.png)

I think we need to re-think how to display the participants. The way we do it now just don't scale. For a user this looks really broken, that's why I opened it as a bug report and not as an enhancement request

**Comment by mahibi** [comment]
this was already fixed by https://github.com/nextcloud/talk-android/pull/1119 and will be available in the next release
