### ISSUE TITLE
Attachments sorted by oldest first

### ISSUE THREAD

**Issue by markus2330** [nextcloud/talk-android#1244]
## Steps to reproduce
1. try to attach a file from Nextcloud files

### Expected behaviour

That I see the latest files/pictures first, like also described in #919

### Actual behaviour

The oldest pictures are first, so I nearly always need to scroll to the end until I find the picture I want to share.

## Device information

**Device:** Fairphone3

**Android version:** 10

**Talk version:** 11.0.0

**Comment by nickvergessen** [comment]
Duplicate by #919
