### ISSUE TITLE
Support standalone signaling server

### ISSUE THREAD

**Issue by fancycode** [nextcloud/talk-android#127]
The Android app should support using a standalone signaling server.

**Comment by mario** [comment]
We'll talk at hackweek :)

**Comment by mario** [comment]
@fancycode I hope I'll see you there?

**Comment by fancycode** [comment]
How is a call started? Joining a call will go through Nextcloud as usual (I assume this triggers the notification) and you get a message over the WebSocket connection to the signaling server that the user has changed / is now in the call (instead of having to poll for the change).

**Comment by mario** [comment]
Ah ok. So I'll join a room via Nextcloud, Nextcloud will send a notification to the other user which can then join the room and pull signaling settings. Once they see it's external signaling server, they'll initiate a Websockets connection. 

And that should be it if I understood this correctly @fancycode.

**Comment by fancycode** [comment]
Sounds good. You then get events/messages through the WebSocket connection where you otherwise have to poll for.

**Comment by mario** [comment]
- [] - reconnect at random intervals
- [] send nick every now and then

@fancycode @Ivansss why do we send nicks all the time? o.O

**Comment by Ivansss** [comment]
> why do we send nicks all the time? o.O

This is just when using the MCU, because there is no way to know when another peer subscribed to receive your audio&video streams. Am I right @fancycode ?

**Comment by fancycode** [comment]
Yes, there is https://github.com/nextcloud/spreed/issues/991 open to stop (ab)using the datachannel and use the name from the participant list instead.

**Comment by mario** [comment]
OK, three smaller things remain. Will do it early next week and then it's time for beta!
