### ISSUE TITLE
If TOTP is disable and used backup code it will load nextcloud website in webview

### ISSUE THREAD

**Issue by imrun** [nextcloud/talk-android#1271]
## Steps to reproduce
1.Disable the totp from security 
2.Open up nextcloud app and use the backup code to login.
3. It will load the webview of nextcloud

### Expected behaviour
It should redirect to the main nextcloud talk app but loads the webview.

### Actual behaviour
After login using backup code redirects to webview.

## Device information

**Device:**  One Plus 6T

**Android version:** 10

**Talk version:** 11.0.0

**Comment by timkrueger** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
