### ISSUE TITLE
Theme for message menus

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#1273]
## Steps to reproduce

1. Set the app's theme to dark.
2. Create a conversation.
3. Write a message.
4. Mark the body of the message.

The background color of the menu does not change to the set theme:

![obraz](https://user-images.githubusercontent.com/47037905/118965454-fef2e280-b968-11eb-85c6-10fd59ce3f3b.png)

## Device information

**Android version:** 10

**Talk version:** 12.0.0 Alpha 13

## Server information

**Nextcloud version:** 21.0.1

**Talk version:** 11.2.1

**Comment by AndyScherzinger** [comment]
@Valdnet When the application is turned off and on again is the color then correct? Just asking because it works just fine for me (on master though, haven't yet tried Alpha 13)

**Comment by Valdnet** [comment]
> When the application is turned off and on again is the color then correct?

@AndyScherzinger The background color is always the same.

**Comment by AndyScherzinger** [comment]
@nickvergessen @mahibi can you reproduce this? It works fine on my Android 11 device and also fine on a Android 11 emulator 0_0

**Comment by nickvergessen** [comment]
Works fine here on my xiaomi redmi note 8 with Android 10 and Miui 12

![Screenshot_2021-05-20-18-59-56-016_com.nextcloud.talk2.qa~2.jpg](https://user-images.githubusercontent.com/213943/119019658-adb11600-b99d-11eb-9279-756507f247c4.jpg)

**Comment by mahibi** [comment]
also works fine here.

Talk version: 12.0.0 Alpha 13
Android version: 9
Xiaomi Redmi Note 7, MIUI 10.3.6.0

**Comment by Valdnet** [comment]
> which device do you use?

HUAWEI P smart 2019
Android 10
EMUI  10.0.0

**Comment by nickvergessen** [comment]
Do you have the OS set to white and Talk set to dark?

**Comment by Valdnet** [comment]
@nickvergessen I have white mode set for OS. It doesn't matter what my set up is, it always does.

**Comment by mahibi** [comment]
I just reproduced this with:
OneplusOne
LineageOS 15.1 (Android8.1.0)

**Comment by AndyScherzinger** [comment]
@mahibi can you reproduce this in any emulator-image?

**Comment by AndyScherzinger** [comment]
If you can spare some time testing: https://github.com/nextcloud/talk-android/pull/1462#issuecomment-878424831 should fix the issue.

**Comment by Valdnet** [comment]
Works fine :+1:. Now the menu has the correct background. Thanks a lot for the fix.

**Comment by Valdnet** [comment]
Works fine :+1:. Now the menu has the correct background. Thanks a lot for the fix.

**Comment by AndyScherzinger** [comment]
Sweet, thanks a lot for testing @Valdnet 🙏
