### ISSUE TITLE
System menu and app menu for messages

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#1274]
## Steps to reproduce

1. Create a conversation.
2. Write a message.
3. Mark the body of the message.

Two menus appear: the system menu and the application menu. The system menu is not needed here. It covers the application menu:
![obraz](https://user-images.githubusercontent.com/47037905/118985408-b7775100-b97e-11eb-9c04-fc50a99e4f3b.png)

## Device information

**Android version:** 10

**Talk version:** 12.0.0 Alpha 13

## Server information

**Nextcloud version:** 21.0.1

**Talk version:** 11.2.1

**Comment by mahibi** [comment]
can reproduce this. so this happens when the text inside the message is selected. The android popup for text selection pops up and additionally our popup for message actions..
![grafik](https://user-images.githubusercontent.com/2932790/119107619-b21e1300-ba1f-11eb-9a96-421957405b18.png)

**Comment by AndyScherzinger** [comment]
PR is  #1303
