### ISSUE TITLE
Remember video on/off and mute/unmute state when rejoining

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#128]
Just like we do in the web interface:

1. Join a call and mute yourself
2. Exit that call
3. When you join that call again later, you should be muted

Same for Talk on iOS @Ivansss

**Comment by Ivansss** [comment]
> 3. When you join that call again later, you should be muted

That call or any call?
In the web app we remember last state, not last state per call.

**Comment by mario** [comment]
This all makes no sense to me. If I join a call I want to be at least heard
so voice is on by default, but camera is disabled. (Yet you always receive
remote video atm)

Absoluely 0 complaints on this behaviour so far.

**Comment by jancborchardt** [comment]
> Absoluely 0 complaints on this behaviour so far.

@mario This is literally the first complaint then. And it’s not by the design we use for the web interface. 

I am in a call, get disconnected, or disconnect and retry for whatever reason, and I have to mute myself again. That’s annoying. I shouldn’t be wondering if now the microphone is on when I specifically muted it.

We do need good feedback if you are actually speaking but muted – that’s the case anyway and separate from this.


> That call or any call?
> In the web app we remember last state, not last state per call.

@Ivansss when I brought it up, I meant that it should be last state per call by design.

**Comment by mario** [comment]
Let's discuss this today as it's one of the biggest gripes I have with your issues :P

**Comment by mario** [comment]
Discussed so closing.
