### ISSUE TITLE
Unable to delete images

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#1281]
## Steps to reproduce

1. Create a conversation.
2. Send a images from your device in a message.
3. Remove images via message menu.

You cannot delete a message with an image:

![obraz](https://user-images.githubusercontent.com/47037905/119123020-6f643700-ba2f-11eb-8e9b-00f3cda40ee9.png)

I also noticed that it was impossible to **select an image directly** on it to launch the message menu. You should tap and hold next to the image, which is confusing for the user.

## Device information

**Android version:** 10

**Talk version:** 12.0.0 Alpha 13

## Server information

**Nextcloud version:** 21.0.1

**Talk version:** 11.2.1

**Comment by mahibi** [comment]
infact the delete option should't appear because deleting attachment is not yet supported by server.
the linked PR hides the delete button for attachments when you long click next to the attachment
