### ISSUE TITLE
Position own video according to where the front camera is

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#129]
Currently the own video feed is always shown in the top right. That works when you hold the phone in portrait mode and the camera is on the top right.

When in landscape mode, the video could switch to the top left (when tilted to the left) or to the bottom right (when tilted to the right).

cc @Ivansss @mario, probably same for iOS @marinofaggiana

**Comment by mario** [comment]
Actually @Ivansss does the iOS Talk app. Let's discuss this at the hackweek.

**Comment by mario** [comment]
After discussing this with @Ivansss, don't think it makes much sense and camera location is not always the same on different phones.
