### ISSUE TITLE
Error reading user fields for profile editing

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1294]
#1092 added the user profile screen and editing capabilities if available. This broke recently since it seems the API URL has changed or something else is wrong (maybe with the authorization header?). Maybe @nickvergessen knows more about it.

URL ist build via:

```
baseUrl + ocsApiVersion + "/cloud/user/fields"
```

which leads to:
```
https://cloud.nextcloud.com/ocs/v2.php/cloud/user/fields
```

Which now crashes with:
```
HTTP 404
```

**Comment by tobiasKaminsky** [comment]
Just tested with curl/insomnia, this also does not work for a regular account on c.nc.c.
But it works on my private NC21 instance.

**Comment by nickvergessen** [comment]
Fix is in https://github.com/nextcloud/server/pull/27188
