### ISSUE TITLE
View password toggle to confirm password is correct

### ISSUE THREAD

**Issue by dikshu11** [nextcloud/talk-android#130]
Currently in call actions, while setting password(Set a password), there should be an option for Confirm Password field. Similarly, when user clicks on Change a password again, It should ask user to type current password, then type new password and confirm it. Also, when user clicks on Clear password, it should ask user to type password and then clear it.
![whatsapp image 2018-04-09 at 9 41 36 pm 1](https://user-images.githubusercontent.com/33371085/38509324-35023c72-3c3f-11e8-9bc7-de5920e47bb8.jpeg)

**Comment by jancborchardt** [comment]
As this is on mobile, we must make sure that people don’t need to type that much. To confirm the password, it’s better to have a »Show password« toggle on the right side of the field:
![screenshot from 2018-04-09 18-52-01](https://user-images.githubusercontent.com/925062/38511045-1e95b4fe-3c27-11e8-9869-fc815bd747ae.png)

A toggle icon is here: https://github.com/nextcloud/server/blob/master/core/img/actions/toggle.svg

**Comment by dikshu11** [comment]
@jancborchardt  Would you please review the issue regarding option "Change password". Clicking on this option should ask for current password first, verify it and then ask user to type new password.

Similarly option "Clear password" should ask for current password, verify it and then clear it.
