### ISSUE TITLE
Ringing forever when missing permissions

### ISSUE THREAD

**Issue by PVince81** [nextcloud/talk-android#1309]
## Steps to reproduce
1. Install app
2. Login
3. Make it so that someone else sets up a call that includes you
4. Deny the call
5. Go to the conversation from the call and see that other people joined
6. Tap the phone button to join the existing call with audio only

### Expected behaviour
Joined with audio, permissions asked on the fly.
If no permissions granted, it should not ring forever and stop directly, or show an error.

### Actual behaviour
An obscure popup appears telling me that I need to setup some permissions somewhere (which it took me a while later on).
I've hit the "edit permissions" but did not land in a place where I could edit it (I don't remember where).
At this point I've ignored it and waited for the call as it's still ringing.
Wait...
It rings forever. I thought it would eventually connect.

To fix it, I had to find where to grant permissions and granted permissions everywhere. After that, joining works.

## Device information

**Device:** Nokia 6.1

**Android version:** 10

**Talk version:** 11.1.0

## Server information

**Nextcloud version:** c.nc.com (company instance)

**Comment by PVince81** [comment]
Note: while the flow might make sense, to ask to manually set permissions, it doesn't work in a "pressing" situation like when an important call started, which can be a stressful situation for some and makes it harder to quickly find the place for permissions.

So I think it would be better to ask the permissions directly when joining the call, if technically possible.

**Comment by mahibi** [comment]
i just had the same situation after a fresh install!
Asking for permissions earlier totally makes sense i think, maybe even on app startup?
On the other hand if you really want to use the app just for chat and don't like to give permissions the dialog might be intrusive on app startup.
But i think nowadays there is always the option to "remember this decision" in android.
So if you really declined the permission and checked "remember this decision", you would get a warning that you have to enable the permissions manually..?

by the way: when improving the permissions for calls, i would like to get rid of https://github.com/zhanghai/EffortlessPermissions which is used and replace it with plain android..

**Comment by mahibi** [comment]
shouldn't be an issue anymore since https://github.com/nextcloud/talk-android/pull/3199 was merged.
