### ISSUE TITLE
Back button in call chat leaves the call

### ISSUE THREAD

**Issue by PVince81** [nextcloud/talk-android#1317]
## Steps to reproduce
1. Join a call
2. Open the chat window from the call by hitting the chat button in the call view
3. Be confused by not knowing how to get back to the call (and overlook the hovering phone icon on the top right)
4. Hit the back button in hope to return to the call

### Expected behaviour
Back to the call view.
Or if leaving the call, maybe show a warning popup ?
I'd even suggest always showing a warning popup when leaving the call with the back button as it might not always be what was intended by the user.

### Actual behaviour
Leaves the call unwarned, confusion and worries about missing out.

## Device information

**Device:** Nokia 6.1

**Android version:** 10

**Talk version:** 12.0.0 Alpha 15

## Server information

Server was c.nc.com with HPB

**Comment by mahibi** [comment]
resolved with https://github.com/nextcloud/talk-android/pull/1655
