### ISSUE TITLE
State token does not match

### ISSUE THREAD

**Issue by AMajor-C** [nextcloud/talk-android#1326]
## Steps to reproduce
1. Connect the app to account without 2fa
2. Remove the acoount
3. Try to connet another account with 2fa

### Expected behaviour
No problems with it

### Actual behaviour
Always getting "State token does not match"

## Device information

**Device:** Redmi4X

**Android version:** 7.1

**Talk version:** 11.1.0 /last release

## Server information

**Nextcloud version:** last release

**Talk version:**  last release

**Custom Signaling server configured:** no 

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

### Server log (data/nextcloud.log)
no errors

**Comment by timkrueger** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
