### ISSUE TITLE
Delete messages by swiping

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#1333]
I really liked the feature to quote messages by swiping it to the right 👍.

The function of deleting a message by swiping to the left is now missing as is the case with other apps. The information preceding the action would be the trash can icon.

**Comment by AndyScherzinger** [comment]
What do you think @mahibi @nickvergessen @nextcloud/designers ? 

None of the other messengers do this, neither, WhatsApp, nor  Telegram or Signal
To me this action would be to prominent since deleting isn't as frequently used as reply+quote and is also a destructive action.
So I'd decline.

**Comment by Valdnet** [comment]
@AndyScherzinger If an app allows you to delete messages from the menu, why not add this feature by swiping it sideways 😁.

> None of the other messengers do this, neither, WhatsApp, nor Telegram or Signal

This is why we will be the first :sunglasses:. Why do we always stick to some standards with other applications that are more popular. Or maybe the developers of these applications will like our solution and they will add this feature to their applications.

In my opinion, if it is possible to delete messages, nothing prevents you from adding this function. It will enrich the application with easy functionality and operation, which will surely appeal to Talk users.

**Comment by nickvergessen** [comment]
I think there will be people which way to often swipe to the wrong side.

**Comment by Valdnet** [comment]
> I think there will be people which way to often swipe to the wrong side.

Just like in other applications.

The Talk application has a well-resolved shift as it is also indicated by vibration. Each user not only sees what they want to do, but also feels it in their hand.

**Comment by szaimen** [comment]
I think a destructive action like this shouldn't be so easy to triger in a chat app.

**Comment by Valdnet** [comment]
> Why would you like to clean up your your chat history so easily?

@szaimen When typing a message quickly, people often make mistakes, typos, etc. The sentence then makes no sense. To correct them, you must either delete them and rewrite them, or explain them in the following messages.

If there is no point in deleting messages in the chat app so easily, then what's in it at all in this app. Then I suggest editing the message, not deleting. And then a swipe to the left edits the message 😁.

**Comment by Valdnet** [comment]
> I also don't "believe" the argument that there are many people who want to delete messages to type them again, they just send it again.

Believe me, there are people who want to improve their message because it is incompatible or, for example, they made a spelling mistake that should not be displayed.

> Don't think polluting the chat history with "message deleted" items is any better, quite the opposite.

How about littering with repeated messages because the previous message needs to be corrected?

But okay, I just suggested a feature that I think would help users delete the message quickly and correct it into a more compact one. A chat doesn't always have to be just a message list with frequent typos and spelling mistakes.

**Comment by nickvergessen** [comment]
I'm closing this for now. We will keep the other swipe free for now, so we can use it for potential editing or other things in the future.
