### ISSUE TITLE
No feedback when the server is in maintenance mode

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1338]
## Steps to reproduce
1. Have a nextcloud account
2. Put the instance in maintainence mode or update
3. While that is in maintenance mode open the Talk app

### Expected behaviour
A note that the server is in maintenance mode

### Actual behaviour
![Screenshot_2021-06-18-22-14-12-286_com nextcloud talk2](https://user-images.githubusercontent.com/213943/122612146-ed454d80-d082-11eb-85c6-12adde275c0d.jpg)

**Comment by jakobroehrl** [comment]
dup of: https://github.com/nextcloud/talk-android/issues/740
