### ISSUE TITLE
Resume call or notify after connection loss

### ISSUE THREAD

**Issue by steffanson** [nextcloud/talk-android#135]
Hi! Last time I tried NextCloud Talk I experienced the following:

When using NextCloud Talk with mobile data (LTE) it may happen, that a call starts to hang due to an unstable connection.

In that case, no video or audio will be broadcasted and the video screen stays black. There is no information to the user about what happened. In order to phone again, a new call has to be initiated.

Therefore, I would suggest:

* Notify the user that the connection broke up
* Automatically or manually try to resume the call

Regards

**Comment by nickvergessen** [comment]
Hello there,

we are currently cleaning up old/stray github issues. Can you please retry with the current version and report back if the problem still persists for you?

cheers
