### ISSUE TITLE
Catch 'View Chat' notification from Nextcloud Android

### ISSUE THREAD

**Issue by shinenelson** [nextcloud/talk-android#1350]
**Description**
Nextcloud Talk ( spreed ) has this unique feature of having a call-to-action ( **View Chat** ) in the notifications for the application. I _think_ this is a deep-link on the web ( I am not sure though ).

**Describe the solution you'd like**
It would be great for the Android ( and possibly iOS too ) application to catch this deep-link from the notification ( on the Nextcloud Android application ) and open the corresponding conversation in the Nextcloud Talk application.

**Describe alternatives you've considered**
Currently, there are no alternatives other than manually opening the corresponding conversation from the Talk app after seeing :eyes: the notification in the Nextcloud app.

**Additional context**
This might require implementing some sort of common deep-linking strategy across all the platforms - web and mobile ( both Android and iOS ).

**Comment by shinenelson** [comment]
the button on the web is literally a `<button>` with a `data-href` attribute.

```html
<div data-v-38932a7f="" class="notification-actions">
  <button
    data-v-38932a7f=""
    data-type="WEB"
    data-href="https://nextcloud.mydomain.tld/call/[REDACTED]"
    class="action-button pull-right">
      View chat
  </button>
</div>
```

I do not know how that is handled by the spreed app on the web. Maybe the `data-type="WEB"` has some significance in translating the click into the spreed app (?)

If that is the case, then maybe, implementing a deep-linking strategy globally would be the ideal way to go.

**Comment by mahibi** [comment]
Thank you @shinenelson , this definitely makes sense. 
It was already reported at https://github.com/nextcloud/talk-android/issues/847 so i will close this issue.
