### ISSUE TITLE
Handle space in password

### ISSUE THREAD

**Issue by p-bo** [nextcloud/talk-android#1351]
(talk v11.1.2)
When user password contains space (passphrase, generated by password manager), it is not possible to login (due wrong password, even if typed correctly). For web interface, this password (with spaces) is working fine.
When password for user account was changed to remove spaces, it worked (successful login) for Talk.
Would it be possible to handle passwords, which contains space character please?

**Comment by timkrueger** [comment]
Hi @p-bo.

Thanks for opening this issue. But I was not able to reproduce the error.

IIt's probably not a problem in the Android Talk app either. The username and password will be entered in a webform loaded from your Nextcloud server. 

So please:
- Try to repoduce that issue with version 12.1 of the Android Talk app
- Let me know the version of your Nextcloud server instance
