### ISSUE TITLE
🤝 Account chooser for "share to"

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#1353]
when selecting "share to Nextcloud Talk" there should be an account chooser as a first screen if user is logged in with multiple accounts

**Comment by jakobroehrl** [comment]
In the file app, the user can tip within the sharing screen on the 3 dot menu and choose there "change account" if needed:
![image](https://user-images.githubusercontent.com/24530680/123062191-933ee200-d40c-11eb-8a4b-f0a95f8b8648.png)

**Comment by mahibi** [comment]
> Could this maybe get a bit prioritized? It makes using the app really hard (when sharing pictures) with multiple accounts, imho. :/

moved to planning evaluation

**Comment by szaimen** [comment]
> moved to planning evaluation

Thanks!

**Comment by mahibi** [comment]
also trying to fix https://github.com/nextcloud/talk-android/issues/1981 if possible

**Comment by szaimen** [comment]
🎉🎉🎉
