### ISSUE TITLE
No way to switch profile while sharing photo to talk-android

### ISSUE THREAD

**Issue by szaimen** [nextcloud/talk-android#1357]
**Is your feature request related to a problem? Please describe.**
There is currently no way to switch profile while sharing photo to talk-android

**Describe the solution you'd like**
I would like to have an option to choose/switch the profile while sharing a photo to talk-android

**Describe alternatives you've considered**
hacing to switch to the profile before sharing the photo to talk-android

cc @mahibi @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Yes, makes sense and also would align the behavior with the files app which shows an account chooser when files are shared via Android's OS mechanism with/to the app.

**Comment by szaimen** [comment]
Funny that this was just reported :D
https://github.com/nextcloud/talk-android/issues/1353
