### ISSUE TITLE
Add loading spinner while joining call

### ISSUE THREAD

**Issue by steffanson** [nextcloud/talk-android#136]
As proposed here: https://github.com/nextcloud/spreed/issues/707

**Comment by jancborchardt** [comment]
This is quite important for feedback as currently it is just a black screen.

What should be there is exactly what the web app and iOS app do: Show an avatar of the other person (or icon of the call if it's a group call) and below that "Calling Ivan …" (or "Waiting for Ivan to join the call …", depending on the situation).

This is quite important and confusing in the current experience, so putting it as high. Also tagging as bug cause it's missing feedback.
