### ISSUE TITLE
Stop parsing messages for potential links or improve it

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1375]
## Steps to reproduce
1. Have a college how posts text `show_me_morpheus.gif`
2. Open the conversation

### Expected behaviour
See text `show_me_morpheus.gif`

### Actual behaviour
![256-555](https://user-images.githubusercontent.com/213943/123912075-dce37b80-d97c-11eb-9ad2-f2ce0a543fd5.jpg)

**Comment by AndyScherzinger** [comment]
@timkrueger I think you just fixed this :)

**Comment by nickvergessen** [comment]
Fixed by #1470
