### ISSUE TITLE
Unreliable Signaling - connection problems

### ISSUE THREAD

**Issue by HAVP** [nextcloud/talk-android#139]
Hello,

the signaling seems to be unreliable in Nextcloud 13.0.1 and Talk 3.1.0. Sometimes I don't even get the remote candidate. Sometimes I get an video connection but screen sharing fails. It's hard to reproduce.
It happens with Firefox and Chrome - did not test other browsers.

I use stun.nextcloud.com:443 and coturn  turnserver-4.5.0.7-CentOS7.4-x86_64 on CentOS with UDP and TCP.

Nextcloud is behind a Apache reverse Proxy
ProxyPass /nextcloud https://nextcloud.intern/nextcloud
ProxyPassReverse /nextcloud https://nextcloud.intern/nextcloud

Turn is also behind a NAT. But also tried a public IP.

I tried an old Nextcloud 12.0.2 with Video Calls 2.0.1 with the same configuration and I can't reproduce the problem. Apache Reverse Proxy and Coturn is still the same. So I don't see a problem there. Apache Reverse Proxy and Nextcloud running on OpenSuse 42.3.

This is my coturn configuration:
listening-port=3478
listening-ip=192.168.2.18
external-ip=129.X.X.X/192.168.2.18
fingerprint
use-auth-secret
static-auth-secret=XXXX
realm=turn.XXXXXX.de
total-quota=100
bps-capacity=0
cipher-list="DEFAULT"
no-stdout-log
log-file=/var/tmp/turn.log
no-loopback-peers
no-multicast-peers
pidfile="/var/run/turnserver/turnserver.pid"

Any suggestions? 

Thank you

**Comment by mario** [comment]
Hello, can you please file the issue under https://github.com/nextcloud/spreed since this repository is for the Android client? Thanks! :)
