### ISSUE TITLE
Share menu not showing in landscape mode?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1392]
## Steps to reproduce
1. Turn phone to landscape
2. Try to share something to the chat
3. You only see the header "Zur Unterhaltung hinzufügen"

### Expected behaviour
You see the options to share something to the chat

### Actual behaviour
You have to pull up the menu from the header

**Comment by AndyScherzinger** [comment]
thew bottom sheet is pull-able so I guess it is a setting for the bottom sheet @mahibi

**Comment by AndyScherzinger** [comment]
there is also an issue with bottom sheet via long click in the conversation list in landscape

**Comment by mahibi** [comment]
> there is also an issue with bottom sheet via long click in the conversation list in landscape

@AndyScherzinger  you mean there is the same issue for the conversation list? for me it's working there without any modifications.

**Comment by nickvergessen** [comment]
On the conversation list I see at least some action. But for sharing in the chat I don't
![Screenshot_2021-07-05-15-40-51-936_com nextcloud talk2](https://user-images.githubusercontent.com/213943/124480589-b4f27e80-dda7-11eb-8b07-cf9bd2b661f6.jpg)
