### ISSUE TITLE
Take server address & credentials from main Nextcloud app

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#14]
@nextcloud/android is it possible that we can transfer the server address & credentials over from the main Nextcloud app?

Ideal would be completely seamless log in, but it’s also ok if we just port the URL and the username like we do for DAVdroid.

**Comment by mario** [comment]
There is a way to import credentials from the Nextcloud app, and we're working on a way to share credentials (and other things) directly in the future.

However this improvement for the Talk app is in the future, as we first need to have a working app and multi-account support, which is not the case now :)

**Comment by mario** [comment]
Current TODO:

- [ ] Implement better alert dialog
- [ ] Handle API above 22 (Dangerous permissions)
- [ ] Investigate crashes on the "Add account" button sometimes
- [ ] Investigate double "Server selection" controller happening sometimes
- [ ] Add support for checking if imported account is HTTP or HTTPS

If luck serves me, this will be in the next release.

**Comment by mario** [comment]
You can now choose to import account(s) from the Nextcloud app - including username, password and the url.

**Comment by jancborchardt** [comment]
Is this part of the initial setup also? Like when the Nextcloud app is detected (if possible), you can import?

**Comment by mario** [comment]
If Nextcloud app is detected, once you start the Talk app and the server entry screen is shown you'll see "IMPORT ACCOUNT FROM THE NEXTCLOUD APP" or "IMPORT ACCOUNTS FROM THE NEXTCLOUD APP" if you have more than 1 account.

**Comment by jancborchardt** [comment]
Ah sure, sorry I was just confused there. Thanks!
