### ISSUE TITLE
Import accounts from the Nextcloud app

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#1410]
Only user names are displayed when selecting "Import accounts from the Nextcloud app". This causes a problem when selecting the appropriate account when you have several accounts with the same username. I think that the domain name information should also be included under the usernames. As is the case with the selection of already added accounts.

## Device information

**Android version:** 10

**Talk version:** 12.2.0 Alpha 03

**Comment by silmaril42** [comment]
It seems that the Talk app currently only lists the logins from the Nextcloud app and opens a connection to the same server, which requests a full login procedure. 
Other Nextcloud companion apps let me chose one of the existing accounts and the main app asks me if I want to grant access. If I acknowledge this, the connection is established without any need for additional authentification.
I guess implementing this should not be too hard - maybe some developer of one of the other apps could provide a link to the code snippet needed for this?

**Comment by Valdnet** [comment]
This has been added. I close.
