### ISSUE TITLE
background of "send" button wrong when capability for voice messages not available

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#1414]
![grafik](https://user-images.githubusercontent.com/2932790/124799638-1146d100-df55-11eb-8e98-5baea33426f0.png)

### Expected behaviour
background is transparent

### Actual behaviour
background is grey

## Device information

**Talk version:** 12.1.0

**Comment by AndyScherzinger** [comment]
Will push the solution after some rebases 👍
