### ISSUE TITLE
Menu bar overlays the last contact in the contacts list

### ISSUE THREAD

**Issue by j-ed** [nextcloud/talk-android#142]
### Actual behavior
After I’ve installed the latest app version (1.1.2) I opened the contacts list in which the last available entry is overlayed by the menu bar so that it cannot be seen nor selected.. Only the alphabetic header is shown.

![talk](https://user-images.githubusercontent.com/2572764/39043923-f91ca26c-448e-11e8-87ee-92818e1666ec.jpg)

### Expected behavior
All available contacts should be visible and selectable.
 
### Steps to reproduce
1. Open the contacts menu and scroll down to the last contact.

### Environment data
Android version: 7.0
Device model: Samsung Galaxy S7
Stock or customized system: Stock ROM
Nextcloud Talk-app version: 1.1.2
Nextcloud server version: 13.01

**Comment by mario** [comment]
Fixed in 1.1.3 :)
