### ISSUE TITLE
Add action buttons to the existing android notification anatomy

### ISSUE THREAD

**Issue by MRFU510N88** [nextcloud/talk-android#1428]
Amend the existing notification to add action buttons and enable user to reply to messages via the android notification panel. 

In addition, would benefit from an expandable notification action with user profile icon. 

See: https://developer.android.com/guide/topics/ui/notifiers/notifications

**Comment by AndyScherzinger** [comment]
Reply has been added with 14.1.0 and mark as read will come with 14.2.0

**Comment by MRFU510N88** [comment]
Looks great guys! The only think I would add is the ability to preview media such as images in those notifications which is also in the dev documentation.

https://developer.android.com/guide/topics/ui/notifiers/notifications.

**Comment by AndyScherzinger** [comment]
@MRFU510N88 yeah, nice idea! Since it is not an action on a notification, could you please create a follow-up issue for the preview part in notifications? That'd be highly appreciated 🙏

**Comment by MRFU510N88** [comment]
> @MRFU510N88 yeah, nice idea! Since it is not an action on a notification, could you please create a follow-up issue for the preview part in notifications? That'd be highly appreciated 🙏

No problem, please see #2300
