### ISSUE TITLE
may i please get the setup documentation 

### ISSUE THREAD

**Issue by adeseg** [nextcloud/talk-android#143]
link to setup

**Comment by mario** [comment]
Do you have Nextcloud server and Talk app installed inside Nextcloud?

In addition, you might need a TURN server like coTurn.

**Comment by mario** [comment]
@adeseg around? :)

**Comment by mario** [comment]
Basic TURN docs is available here: https://github.com/nextcloud/talk-android/blob/master/docs/TURN.md
