### ISSUE TITLE
Make image preview bigger

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/talk-android#1448]
**Is your feature request related to a problem? Please describe.**
Sent a picture in Talk Android App I got a small preview, max half of the width.

**Describe the solution you'd like**
It could use the whole width.

**Describe alternatives you've considered**
None.

Seems like the app is preventing me from doing a screenshot. Sry.

Talk Android: 12.1.0

**Comment by mahibi** [comment]
@Dubidubiduu does this always happen? even if you paste the picture into other chats?

this might be a problem with the recyclerview which mistakenly reuses dimensions of other items.

**Comment by Valdnet** [comment]
> Seems like the app is preventing me from doing a screenshot. Sry.

If you have "Screen security" enabled in the application settings, it is not possible to take a screenshot 😉.
