### ISSUE TITLE
Missing dependencies .. Code is not consistent 

### ISSUE THREAD

**Issue by Vaibhav1587** [nextcloud/talk-android#145]
Missing class 
`com.nextcloud.talk.models.database.UserEntity;`
`com.nextcloud.talk.utils.glide.GlideApp;
`
Imported code into the android studio 3.2. 

> App not building up from the source code at Main branch.

**Comment by mario** [comment]
It's all there. Try now :)

**Comment by Vaibhav1587** [comment]
Thanks for the quick reply. 
But seriously `UserEntity` class is not present in the package rather there is 'User'. Either I'm so stupid or something really missing here.. 
![missing_dependancy](https://user-images.githubusercontent.com/34318157/39267495-9c665332-48ea-11e8-9458-8ebaa49ac06b.png)

Is there any setup instructions. Because simply importing code into android studio not working ..

**Comment by Vaibhav1587** [comment]
Thanks for recognizing.

**Comment by mario** [comment]
This seems to be a problem with newer Android studio and Dagger. But oh well.

**Comment by mario** [comment]
https://github.com/nextcloud/talk-android/pull/148

**Comment by Vaibhav1587** [comment]
Does older version Android studio will work ?

**Comment by AndyScherzinger** [comment]
@Vaibhav1587 No, due to the Android/gradle dependencies you need to run Android Studio 3.1
