### ISSUE TITLE
Improve/Align group creation

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#1463]
2 of my android users asks this question. 
Maybe we could overwork the group creating process.

**Comment by AndyScherzinger** [comment]
The short answer:
1. Hit the "+" button
2. choose more than one participant
3. hit "Done" in the action bar
4. provide a conversation name

The longer answer:
Just checked web and iOS and the creation process differs on all platforms so there is definitely room for improvement and alignment.

**Comment by jakobroehrl** [comment]
We found it out of course, but if 2 users asks me, maybe there is room for improvement.

**Comment by Valdnet** [comment]
The process of creating a group conversation is simple and easy, but can actually be a little confusing for users.

**Comment by AndyScherzinger** [comment]
> We found it out of course, but if 2 users asks me, maybe there is room for improvement.

Which is what I just said ;)

> so there is definitely room for improvement and alignment

Since this is a matter that need to be addressed across platforms it might be worth raising it in Tuesday's design calls when Jan is back.

**Comment by jakobroehrl** [comment]
Tested it on ios, there it's easier. 
I would recommend to solve it like there

**Comment by mahibi** [comment]
I had a look on https://github.com/nextcloud/talk-android/issues/3713 and decided that the contacts invitation / group creation etc has to be replaced. So with new solution we should also improve the workflow...
Will most probably done after v19 though..

**Comment by mahibi** [comment]
also be aware that on iOS it was recently changed: https://github.com/nextcloud/talk-ios/pull/1572
