### ISSUE TITLE
Opening a message by notification

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#1473]
## Steps to reproduce

1. Lock your smartphone.
2. Get a notification.
3. Wake up the smartphone.
4. Tap the notification on the lock screen to read the message in Android Talk.

### Expected behaviour
Opening messages in Talk Android.

### Actual behaviour
First the conversation lists will open.
Later after selecting the conversation, the application closes.

## Device information

**Android version:** 10

**Talk version:** 12.2.0 Alpha 04

## Server information

**Nextcloud version:** 22.0.0

**Talk version:** 12.0.0

**Comment by Valdnet** [comment]
In version 12.2.0, instead of opening the conversation, the list of all conversations opens.

**Comment by AndyScherzinger** [comment]
> In version 12.2.0 instead of opening the conversation the list of all conversations opens.

So you're implying that this works correct in 12.1.x @Valdnet ?

**Comment by Valdnet** [comment]
> So you're implying that this works correct in 12.1.x

Yes. It works fine in these versions.

**Comment by Valdnet** [comment]
@AndyScherzinger @mahibi From version 13.1.0 Alpha 15, the application behaves as follows:

After tapping the received notification after waking the smartphone, Talk starts with a double window of the conversation list. Tapping on a conversation with a new message does not start it. The conversation can be displayed only after the list of conversations is moved back (the duplicated list is closed).

Proper operation should be as follows:
After tapping the notification, which is displayed on the locked screen, it should start Talk with the appropriate conversation.

Steps:

1. Lock your smartphone.
2. Get a notification.
3. Wake up the smartphone.
4. Tap the notification on the lock screen to read the message in Android Talk.

Apps:
Android 10
Talk Nextcloud: 13.1.0 Alpha 16

**Comment by timkrueger** [comment]
Thank you for reporting that @Valdnet . 

I don't get it with that _duplicated list_. At least I can't reproduce it.

Can your create a screencast?

**Comment by Valdnet** [comment]
> I don't get it with that duplicated list.

@timkrueger There are exactly two windows with a list of conversations superimposed on top of each other. After moving the phone's navigation arrow back, one window with the list of conversations (inactive on taps) is moved back (disappears) and a second window appears hidden under it.

![obraz](https://user-images.githubusercontent.com/47037905/158783589-7933e8fd-f6b6-4888-bcdf-62c5c6deddd9.png)

Window no. 1 (active) is located underneath window no. 2 (inactive - does not respond to a tap on a conversation).

Properly, the application should work as follows:
1. Receipt of message.
2. The appearance of a notification on the lock screen.
3. After tapping the notification, a specific conversation starts.

**Comment by Valdnet** [comment]
It has been fixed. I close.
