### ISSUE TITLE
Update Screenshots

### ISSUE THREAD

**Issue by schiessle** [nextcloud/talk-android#1474]
I'm always shocked how out-dated Talk looks like in the appstores:

https://play.google.com/store/apps/details?id=com.nextcloud.talk2
https://f-droid.org/en/packages/com.nextcloud.talk2/

The real app looks so much nicer these days! :smile:

Maybe update the screenshots with the next release?

**Comment by AndyScherzinger** [comment]
Pinged @mahibi about it and also had made it a todo in the release issue-template: #1346

**Comment by mahibi** [comment]
totally agree. i was asked to wait with that but will update them finally tomorrow

**Comment by AndyScherzinger** [comment]
@mahibi if you create a PR and put them here: https://github.com/nextcloud/screenshots/ I should be able to do this before the press release

**Comment by mahibi** [comment]
ah didn't know that repo, and wow that's outdated ;) is this still the way to go @jospoortvliet ?
