### ISSUE TITLE
share message text to other apps

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#1487]
**Is your feature request related to a problem? Please describe.**
If I need to create a task, deck card, calendar event, ... I have to copy the message text, open the task, deck, caledar app and create a new item. 

**Describe the solution you'd like**
It would be a nice integration If I could share a text message to all apps on my smartphone. 
Long press on a text message
contecxt menu popps up
choose share message
android sharing menu popps up
choose the app you want to share to message text with

**Comment by mahibi** [comment]
good idea :+1:

**Comment by AndyScherzinger** [comment]
Beware that this only works _if_ the mentioned apps also support this (inbound api for "text")
