### ISSUE TITLE
Push Notifications are unreliable

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#1496]
Some Notifications are not shown (about 1 out of 10), this is sporadically. 
Tested on different phones. 
Bug occurs with NC22.

Tested out, its no push problem. The notification is not generated by the server talk app. 
If the push notification on the phone is missing, there is no notification in the browser nor in the nextcloud app:

![image](https://user-images.githubusercontent.com/24530680/131627532-e9df0859-9519-4eab-9a6f-b817f35d4881.png)

---

![image](https://user-images.githubusercontent.com/24530680/131628034-8debb324-311a-439c-9c58-660e7dd49b0b.png)

**Comment by mahibi** [comment]
this issue might has to move to another repository @nickvergessen ?
but fyi @jakobroehrl : we are creating a notifications troubleshooting checklist at https://github.com/nextcloud/talk-android/blob/master/docs/notifications.md (more content will come in by https://github.com/nextcloud/talk-android/pull/1595).

**Comment by AndyScherzinger** [comment]
as per the description and screenshot, yes, server-side issue

**Comment by nickvergessen** [comment]
If there is no notification generated and the settings for the conversations are not "No notifications" the likeliest thing is that there was an active session in the conversation. We don't create notifications when the user has an active session at the moment.
Some thoughts and attempts are in https://github.com/nextcloud/spreed/pull/1970 and https://github.com/nextcloud/spreed/issues/1575 but it's not satisfying yet.

**Comment by jakobroehrl** [comment]
@nickvergessen
A lot of my users says the notifications are unreliable. About 10% of all notifications are not pushed. 
It's not a matter of battery optimization
And most of the users only use the smartphome, so it could not be a open browser windows/session

**Comment by nickvergessen** [comment]
> A lot of my users says the notifications are unreliable. About 10% of all notifications are not pushed.

By not pushed you mean don't show on the phone, right? Or you track the out going connections to the push server?

> And most of the users only use the smartphome, so it could not be a open browser windows/session

Then you just confirmed that it is not an issue of our code but Android not waking up the phone or Google not forwarding the push. Literally nothing we can do about

**Comment by jakobroehrl** [comment]
> By not pushed you mean don't show on the phone, right? Or you track the out going connections to the push server?
 
Right, 10% don't show on the phone.

> Then you just confirmed that it is not an issue of our code but Android not waking up the phone or Google not forwarding the push. Literally nothing we can do about

But before the latest nextcloud update it was working 100%

**Comment by jakobroehrl** [comment]
I just had the problem again. 
No notification on the phone and in the web app.
There is no notification created from the server: (same problem as I described in this Issue at the top)

![image](https://user-images.githubusercontent.com/24530680/140967272-4462e46b-f7a9-4b91-98a3-5733400110bc.png)

**Comment by nickvergessen** [comment]
Do you have this already applied:
https://github.com/nextcloud/spreed/pull/6336

**Comment by jakobroehrl** [comment]
Applied it now, will test it hard in the next days, thank you!

**Comment by jakobroehrl** [comment]
It's working very well, thanks!
