### ISSUE TITLE
Create graphics

### ISSUE THREAD

**Issue by mario** [nextcloud/talk-android#15]
https://material.io/guidelines/style/icons.html#icons-product-icons

Relevant files are in:
mipmap-*
ic_launcher_background.xml in drawable directory

I also need an svg that will be used on the logo screen.

**Comment by jancborchardt** [comment]
The Talk app icon is here:
https://github.com/nextcloud/promo/blob/master/Specific%20designs/icon-talk-android.svg

Also adjusted the regular app icon with dotted background and round circle:
https://github.com/nextcloud/promo/blob/master/Specific%20designs/icon-android.svg

Beta logo, if needed:
https://github.com/nextcloud/promo/blob/master/Specific%20designs/icon-android-beta.svg

Dotted background without the blue (also available as SVG in the same folder, if needed):
https://github.com/nextcloud/promo/blob/master/background-4k-transparent.png

And if you need only the talk icon, that’s here as said:
https://github.com/nextcloud/spreed/blob/master/img/app.svg

**Comment by mario** [comment]
Thanks!
