### ISSUE TITLE
Drop header in bottom menu

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#151]
see https://github.com/nextcloud/talk-android/pull/150#issuecomment-385339658

**Comment by AndyScherzinger** [comment]
To be discussed, @jancborchardt. Also looking through most Bottom sheets there is a header (usually grey) and menu items (usually black). So I'd say we can keep the header and paint it grey and make the menu items text black to have the focus on the menu items.

**Comment by mario** [comment]
Do that.

**Comment by AndyScherzinger** [comment]
PR is #152

**Comment by jancborchardt** [comment]
The comment about the header being unnecessary is still valid. :)

In the case of tapping the Plus-icon, the header could be removed completely because it says nothing with a bunch of text. »What would you like to do today?« is not really needed. It distracts from the actions. → Header can be removed.

And for the 3-dot-menu for calls, it also shows that, which is not relevant to the call. → Instead, show call name in header.

**Comment by mario** [comment]
@AndyScherzinger thoughts again on them matter, so we can finalize this?

**Comment by mario** [comment]
@Andy PR.

**Comment by AndyScherzinger** [comment]
@mario #203

**Comment by jancborchardt** [comment]
@AndyScherzinger is it not possible to have the actual call name in the header? That’s important for context, instead of a generic "Configure room".

**Comment by mario** [comment]
It is of course possible @jancborchardt, the question is what do we want.

**Comment by mario** [comment]
This will be done now, but I'd once again stress that by removing the header that used to be so far, we're removing a bit of user friendliness.

**Comment by jancborchardt** [comment]
From the very beginning I now asked for a relevant header. ;) Relevant for the conversation actions means to actually have the conversation name itself in the header. (Also, we call it »conversation« everywhere, not »room«.)

So the question of what we want has been answered already. ;) The actual room name in the menu header of the conversation options menu.

**Comment by jancborchardt** [comment]
@mario maybe there’s some confusion because the issue title is still "Drop header" – ignore the title and simply look at my last comment. ;)

**Comment by mario** [comment]
Of course, "Room" isn't mentioned anywhere.

**Comment by AndyScherzinger** [comment]
There you go: https://github.com/nextcloud/talk-android/pull/204

Fixed ;)
