### ISSUE TITLE
STUN / TURN server: No Audio / Video transmission (but using a mobile browser works!) - back

### ISSUE THREAD

**Issue by EricThi** [nextcloud/talk-android#1519]
## Steps to reproduce
1. Launch a call via apps (only audio or with video) on phone A
2. Answer to phone B via apps
3. The screen stays black and no sound are listening

### Expected behaviour
See/listen the other person

### Actual behaviour
no change, screen stays black after 5 min
see you only on little window

## Device information

**Devices:** Samsung Galaxy A3 2016 / Samsung Galaxy A3 2016 / Samsung Galaxy A51

**Android version:** Android 8 (by Samsung) / Android 9 (rom /E/) / Android 11 (by Samsung)

**Talk version:** 12.1.2

## Server information

**Nextcloud version:** 21.0.3

**Talk version:** 11.3.1

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes - community/coturn  4.5.2-2

**Custom STUN server configured:** yes - community/coturn  4.5.2-2

Server Coturn : 
uname -a
Linux 5.13.9-arch1-1 #1 SMP PREEMPT Sun, 08 Aug 2021 11:25:35 +0000 x86_64 GNU/Linux

Server Nextcloud : 
uname -a
Linux 5.11.15-arch1-2 #1 SMP PREEMPT Sat, 17 Apr 2021 00:22:30 +0000 x86_64 GNU/Linux

php -v
PHP 8.0.3 (cli) (built: Apr 15 2021 13:36:35) ( NTS )

classic config.php, just redis : 
'memcache.local' => '\\OC\\Memcache\\APCu',
'memcache.distributed' => '\\OC\\Memcache\\Redis',

### Server log (data/nextcloud.log)
no log on server and on coturn when blackscreen...

Warning : 
If use browser on desktop : work well
If use browser on mobile : work well

(only use firefox)
=> about:webrtc : 
if launch a call via app and another user answer via a browser : 
i see only activity for browser session, for mobile via app : no stream, no remote spd...

This case is very similar to this issue : [](https://github.com/nextcloud/talk-android/issues/934)

Thank you for your help;
Eric.

**Comment by andyxheli** [comment]
Might be similar to https://github.com/nextcloud/talk-android/issues/924 they closed the ticket but the issue is not fixed

**Comment by jasonjenssen** [comment]
Same issue here

**Comment by EricThi** [comment]
For me, it's fixed with last update (now, i'm on 12.2.1) 

I close it

**Comment by mvarchdev** [comment]
Same issue here! Please reopen
