### ISSUE TITLE
Background Call Support on non-Google Play Services Devices

### ISSUE THREAD

**Issue by Bryantdl7** [nextcloud/talk-android#1532]
## Steps to reproduce
1. Install lineage OS on a supported device (Motorola G7 Power for me)
2. Install talk and begin a call
3. Press the home screen 
4. The call will be "frozen" and end. 

### Expected behaviour
The call should continue whilst outside of the application, and have a notification in the notification bar to signify a call is in progress. 

### Actual behaviour
What actually happens is the call will end approximately one second after going to the home screen. If I go back into the application the call still exists but it will never reconnect unless I leave the call and rejoin. 

## Device information

**Device:** Moto G7 Power

**Android version:** 11 (Lineage OS 18.1 with no Google Services installed) 

**Talk version:** 12.2.20 (or the f-droid version, too.)

## Server information

**Nextcloud version:** 20.0.11

**Talk version:** 10.0.9

**Custom Signaling server configured:** No

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

### Server log (data/nextcloud.log)
Not applicable
```
Insert your server log here
Not applicable

</details>

**Comment by Bryantdl7** [comment]
Maybe this could be fixed by following how Telegram FOSS implements background calls, where a notification sits in the notification bar throughout the whole call?

**Comment by andyxheli** [comment]
Looks like it might be the same issue as i reported https://github.com/nextcloud/talk-android/issues/938

**Comment by Bryantdl7** [comment]
Yes, this is the same problem I am having. Doing a quick search didn't pull up your ticket so at the least mine will reference back to the  original.

Aug 17, 2021 8:03:44 PM Andrea Xheli ***@***.***>:

**Comment by AMajor-C** [comment]
Same on MIUI 11

**Comment by Bryantdl7** [comment]
Closing this as 13.0 fixes the issue partially. See #938 for the rest of the progress
