### ISSUE TITLE
Can this combine with nextcloud/android ?

### ISSUE THREAD

**Issue by gyjymb** [nextcloud/talk-android#1533]
**Can this combine with nextcloud/android ?
I have a need to make a project contains netdisk and chat function ,how can I combine these two functions,thank you

**Comment by mahibi** [comment]
Dear @gyjymb ,
the talk-android app and the android nextcloud files app will always be two seperate projects and won't be merged.
a merge would be technically too complex.

**Comment by gyjymb** [comment]
> Dear @gyjymb ,
> the talk-android app and the android nextcloud files app will always be two seperate projects and won't be merged.
> a merge would be technically too complex.

thank you
