### ISSUE TITLE
Setup test automation on CI

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1547]
As discussed setup test automation based on the work on the Android Files app for test automation:

- [ ] execution/reporting of unit tests (min 1 working, simple test)
- [ ] execution/reporting of integration tests (min 1 working, simple test)
- [ ] execution/reporting of screenshot tests (min 1 working, simple test)
- [ ] code coverage reporting integration

This is a foundation task so it is not about building up a large pool of tests but adding everything needed for execution/analyzing/reporting via CI for the different aspects so maintainers and contributors just need to add/write tests but don't have to first do the groundwork to have this integrated via CI automation

**Comment by tobiasKaminsky** [comment]
PR for test on server: https://github.com/nextcloud/talk-android/pull/1497
