### ISSUE TITLE
contacts online status

### ISSUE THREAD

**Issue by Glebelg2** [nextcloud/talk-android#155]
Is it any possibility to see if a contact is online before initiating a call?

**Comment by mario** [comment]
No. This is probably a request for https://github.com/nextcloud/spreed first - to support Availability status.

**Comment by Glebelg2** [comment]
Right, I posted an issue on spreed's github. Thanks.

**Comment by mario** [comment]
Let's discuss the idea further in https://github.com/nextcloud/spreed/issues/832.
