### ISSUE TITLE
new software pattern

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#1550]
In the long term the talk app should switch to a new pattern. We want to get rid of https://github.com/bluelinelabs/Conductor 

In this issue there can be discussions which pattern should be used.
There should be the same pattern for the talk app and the files app (https://github.com/nextcloud/android).

**Comment by timkrueger** [comment]
In #1903 we used a new architectural pattern for the implementation. It's based on the [Android Developer Guidelines}(https://developer.android.com/topic/architecture) and using a View Model and the Repository pattern.

**Comment by AndyScherzinger** [comment]
afaik this one can be closed since a decision has been made on the architecture pattern to be used @timkrueger @mahibi

**Comment by timkrueger** [comment]
> afaik this one can be closed since a decision has been made on the architecture pattern to be used @timkrueger @mahibi

You're right.
