### ISSUE TITLE
No "missed call" push notification on Android (iOS and Browser is working)

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#1563]
## Steps to reproduce
1. Call a android user and don't answer the call
2. There will be no missed call push message on the android device

In the browser the notification is shown:
![image](https://user-images.githubusercontent.com/24530680/131474422-47ca3813-9f7c-4f93-a090-1e3d30b79779.png)

And in the Nextcloud Android App the notification is shown in the notification area:
![image](https://user-images.githubusercontent.com/24530680/131475673-68dc6c69-beb0-4a7c-9572-70afc9516009.png)

Text chat push notifications are working. 

NC: 22
Talk: 12.0.1
Android:  12.1.2

**Comment by Minnietheandroid** [comment]
Yes, same here.
While calling the phone shows alert and notification dot, then once call is stopped from source both disappear, leaving no indication that I missed a call. It does show the missed call inside the app however.

Pixel 2xl
Android 11
Nextcloud Snap 22
Talk 12.2.1

**Comment by mahibi** [comment]
closing as this will be implemented with https://github.com/nextcloud/talk-android/issues/1724 (i increased the priority of that issue..)
