### ISSUE TITLE
Back Button behavior not in line with app design guidelines

### ISSUE THREAD

**Issue by Soundbytes** [nextcloud/talk-android#157]
The back button always returns the user to the android home screen. 
As a user I find this annoying because this is not the expected behaviour in Android.
The button should instead bring up the previous screen.
Example: Clicking the back button should never bring up the home screen. instead the user should be brought back to the previous which can only be either the calls or contacts screens.  
Currently the back button behaves like an up button thus impairing the android user experience.

This is the page from the design guide that describes the correct back button behavior:
https://developer.android.com/training/design-navigation/ancestral-temporal

**Comment by mario** [comment]
What version of the app and in which screen does that happen?

**Comment by Soundbytes** [comment]
The version is 1.1.3.  It happens in all screens.    
 I have to correct myself a bit. I wrote wrongly: 
> Clicking the back button should never bring up the home screen.
The android home screen should of course be brought up if the back button is pressed  before the user has navigated to any other screen within the app. 

NB: I had to retrieve the version info from the google app store since I could not find it in the about section of the sttings screen. It might be there but then it looks to me like the bottom of the sceen is hidden by the button bar. This might be another issue that has not been reported yet.

**Comment by mario** [comment]
I fixed the bottom of the screen issue in settings, so it'll be in the next release.

So I just tested the button (both the one in the menu top-left and the hw button) and it works as expected :/

**Comment by Soundbytes** [comment]
then it took me longer to report the issue than for you to fix it. 
I feel old!  :/

**Comment by mario** [comment]
Haha sorry about that! There's probably gonna be a beta release next week, so if you're part of the beta team, maybe you can report back once you test that? :)

**Comment by Soundbytes** [comment]
>  and it works as expected :/

this is strange. The behaviour ahould be consistent through all android versions. Anyway here are my phone specs:
Android 6.0.1
Model - Vodaphone VFD 600

To clarify here are steps to reroduce the issue:
1. Open talk app (Calls screen is now present).
2. Navigate to app settings screen.
3. Hit the HW back button.

Observed Result: The User is brought back to the android home screen
Expected: The app should navigate back to the calls screen.

**Comment by mario** [comment]
Ergh no? This is not what's expected. We misunderstood each other.

The whole screen with bottom navigation is a single screen - so if you're in settings, there's no way back other than the android home screen.

**Comment by Soundbytes** [comment]
And that is what I find annyoing (mildy in fact)
please read the guidlines that I have linked to in my previous post. I don't think these leave much room for interpretation.
Just to clarify: I am quite aware that this issue shouldn't necessarily have a high priority at all .

**Comment by mario** [comment]
I will read it :) In the meantime, do you have examples of applications that work the way you say?

**Comment by Soundbytes** [comment]
I'd say all google apps that have more than a single screen. (chrome, youtube, gmail, maps ...)
Youtube is a great example since it also uses the button bar at the bottom of the screen.
Try clicking a few buttons there then use the back button until you finally end up at the android home screen. 
I know fixing this does not contribute a bit to the functionality. Still users will feel much more at home with your app then and will be much more prepared to tolerate the inevitable quirks and perks that every piece of software comes with.

**Comment by mario** [comment]
Thanks for the report. This has been fixed and will be in v1.2.0beta2 once released.
