### ISSUE TITLE
Getting rid of the need to keep the record button pressed for voice messages

### ISSUE THREAD

**Issue by jacotec** [nextcloud/talk-android#1577]
**Is your feature request related to a problem? Please describe.**
Although users highly welcome the ability to record voice messages, they completely refuse to use it on the mobile apps and still use other platforms.

The reason is that you need to have the record button pressed all the time during recording. Not only that this is annoying, in a car with the phone in a holder and connected to the handsfree this is a security issue.

All other known apps (Element, RocketChat, Signal, WhatsApp) allow to "lock" the recording button during recording the message and finally let the user decide to send or discard it.

**Describe the solution you'd like**
Either the record button should be lockable (like Element, WhatsApp or Signal) or the recording should be done by starting the recording and then press "green" or "red" (like in the Web UI or like RocketChat does it - although RC is about to change this to the same way like Element, WhatsApp or Signal)

**Describe alternatives you've considered**
No alternative except using a different platform ;-)

**Comment by mahibi** [comment]
Dear @jacotec , we are aware of this and we will deliver the feature later.

**Comment by mahibi** [comment]
already implemented
