### ISSUE TITLE
camera usage: add image/video compression

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#1581]
It would be great if there is a image/video compression before uploading like in the deck android app

**Comment by AndyScherzinger** [comment]
Included in #1542 while in comparison to the deck app I use FHD instead of HD for limiting the size which leads to slightly bigger images (450Kb vs 750Kb give or take) but in my test cam shots the quality seemed too low with just HD.

**Comment by ASerbinski** [comment]
This could probably be expanded to a general option to reduce resolution upon upload, i.e. from device storage.
