### ISSUE TITLE
rewrite "toggle Chat" feature (fixes many bugs)

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#1582]
The "toggle chat" feature (https://github.com/nextcloud/talk-android/pull/912) obviously caused a lot of bugs.
The main problem is that multiple instances of the ChatController are created here:
https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/activities/MagicCallActivity.kt#L92

So inside the ChatController an intent is sent to start the MagicCallActivity
https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt#L2137

and in the MagicCallActivity another ChatController is created. As a result there is a mess with different controllers and sessions.

The known bugs that are caused by this feature should be at least:
- https://github.com/nextcloud/talk-android/issues/1232
- accept the call right after granting permissions doesn't work
   - might fix https://github.com/nextcloud/talk-android/issues/1309
- https://github.com/nextcloud/talk-android/issues/935
- https://github.com/nextcloud/talk-android/issues/938
- https://github.com/nextcloud/talk-android/issues/1584
- https://github.com/nextcloud/talk-android/issues/1583
- i guess that "one-way" connections where only one person could hear the other are caused by the code of the toggle chat feature

A clean solution might be only possible when conductor is replaced by native android solutions (see https://github.com/nextcloud/talk-android/issues/1551).

**Comment by mahibi** [comment]
idea by @AndyScherzinger :
modify the CallActivity so it can handle fragments like a "ChatFragment". This will be needed anyway if conductor is replaced..

**Comment by mahibi** [comment]
Another idea might be to have a closer look if picture-in-picture mode (https://developer.android.com/guide/topics/ui/picture-in-picture#kotlin) could be a better alternative for the current toggle-chat button. So you could see the (video-)call while you are using other apps, or you can have the chatView opened. So toggle-chat button might trigger the PIP-mode and open the ChatView at the same time.

**Comment by timkrueger** [comment]
I think also that this issue should be solved with high priority!

I would also prefer the solution proposed by @AndyScherzinger. Let's stabilise the current behaviour.

**Comment by andyxheli** [comment]
@mahibi got a question what will happen with a user stops using pip will the issues come back?

**Comment by andyxheli** [comment]
@mahibi I had an issue with the QA app. I was in a meeting with two users via web and they where on talk ios i left the call from my computer and joined via QA PIP App and they all lost the audio and everyone had to leave and rejoin i was also getting video flickering from one user

**Comment by andyxheli** [comment]
Also, the image is really blown up. the images are not displaced in high res on the ios platform if you double clock on the screen the image will zoom out and if double tab like below video. 


IOS Talk APP

https://user-images.githubusercontent.com/59488153/140657127-a5b3ea63-9907-44d2-bc71-23209f4cb020.mp4


Android Talk App

https://user-images.githubusercontent.com/59488153/140657223-29eff0d4-0711-4b0c-a7d1-6a260cf8c6c8.mp4
