### ISSUE TITLE
🎦 Direct video upload

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#1587]
https://github.com/nextcloud/talk-android/pull/1542#issuecomment-921627358

> Is it possibly to make videos directly, too?

**Comment by mahibi** [comment]
unless there is no reason against it from @AndyScherzinger or anyone else, we (@timkrueger @tobiasKaminsky @AlvaroBrey @mahibi ) would like to replace the own camera implementation by android build in solutions.
https://developer.android.com/training/camerax/choose-camera-library

**Comment by AndyScherzinger** [comment]
No strong feelings from my side but the referenced article is actually what we did, implement camera2 😉

**Comment by mahibi** [comment]
actually i didn't have a really close look at our own implementation (neither at the android docs), but at first sight it looks that we reinvent a wheel... 
will have a closer look whenever this task is due

**Comment by AlvaroBrey** [comment]
The point is to remove the camera implementation and use a system Intent instead (https://developer.android.com/training/camera/photobasics#TaskManifest)

**Comment by AndyScherzinger** [comment]
Again, no strong feelings. So if you all agreed on it, just go for it 😊👍
