### ISSUE TITLE
Change readme in coherence with ios app

### ISSUE THREAD

**Issue by Spartachetto** [nextcloud/talk-android#16]
A bit more "Brand" identity with talk-ios could be good.

A really simple proposal for the first part of the readme

-------------------------------------------

# Nextcloud Talk Android app

This is the Android app for the [Nextcloud Talk](https://github.com/nextcloud/spreed) app.

## Prerequisites

*    Nexcloud instance with Nextcloud Talk app installed (Latest [master](https://github.com/nextcloud/spreed/commits/master))
*    .....

-------------------------------------------

In addition it could be useful that each of the two apps cites the other. 
Something like: "We are working also on the [ios version](https://github.com/nextcloud/talk-ios) of this app!"

**Comment by mario** [comment]
Will talk with @Ivansss about this, but priority is to get the apps running. Thanks for the note! :)

**Comment by mario** [comment]
Changing this a bit as we speak.
