### ISSUE TITLE
Time setting for lobby does not work well

### ISSUE THREAD

**Issue by weinic** [nextcloud/talk-android#1610]
Time setting for lobby does not work well.
See in the video.
The time setting by wiping is almost impossible.

Nextcloud Talk for Android Version 12.2.1

https://user-images.githubusercontent.com/57099502/135388115-469c24f4-b259-4407-8a05-76a373dd60e6.mp4

**Comment by nickvergessen** [comment]
@sowjanyakch let me know if that is within your scope and okay effort wise

**Comment by sowjanyakch** [comment]
okay effort wise and can implement this
