### ISSUE TITLE
Poor audio quality of voice messages

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/talk-android#1613]
## Steps to reproduce
1. Record an audio message

### Expected behaviour
Audio message has similar quality as in Nextcloud Talk web version, whatsapp, telegram, signal etc.

### Actual behaviour
It is very tinny and not at pleasure to hear that voice message at all.

## Device information

**Talk version:** 12.2.1

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`) 22.1.1

**Talk version:** (see apps admin page: `/index.php/settings/apps`)  12.1.2

**Comment by timkrueger** [comment]
@Dubidubiduu Thanks for reporting this issue. I was able to reproduce it.

**Comment by DanielStandfest** [comment]
I can confirm it for the Xiaomi Mi 5T.

**Comment by StarSmasher44** [comment]
Any ehrm, any status on this? Half a year in, can I do anything to change the quality setting of any of my chats/calls? I need it

**Comment by mahibi** [comment]
@timkrueger how did you reproduce this?

**Comment by timkrueger** [comment]
> @timkrueger how did you reproduce this?

On my test devices I created a voice message in NC Talk for Android and made a voice memo. In comparison the audio quality for NC Talk for Android was much lower. But I didn't investigate any more.

**Comment by andyxheli** [comment]
Same with S21+ 5G SM-G996U1

**Comment by siriwliw98** [comment]
I have the same problem with my samsung note 9.
My nextcloud version is 24

**Comment by timkrueger** [comment]
We not working active on that issue. But it would be interesting to know if you used external micros (cable, bluetooth) or the integrated micro!

**Comment by dotmitsu** [comment]
> We not working active on that issue. But it would be interesting to know if you used external micros (cable, bluetooth) or the integrated micro!

I used integrated micro

**Comment by siriwliw98** [comment]
> We not working active on that issue. But it would be interesting to know if you used external micros (cable, bluetooth) or the integrated micro!

It's the same problem when I use integrated and external Mic.

**Comment by R7JANV1** [comment]
integrated micro

**Comment by dorpauli** [comment]
https://github.com/nextcloud/talk-android/issues/1835#issue-1150972885

Is this question not a clue to the problem? Has anyone done any research in this direction so far?

All the devices in my family (oneplus 7t, huawai p20, Samsung S22, Motorola G22) have this problem. So I don't think it's a problem with the devices.

**Comment by nssatlantis** [comment]
> https://github.com/nextcloud/talk-android/issues/1835
> 
> Is the referenced issue not a clue to the problem? Has anyone done any research in this direction so far?
> 
> All the devices in my family (oneplus 7t, huawai p20, Samsung S22, Motorola G22) have this problem. So I don't think it's a problem with the devices.

If they really use such awful bitrate and settings then yes, this is the whole problem. I can't believe these settings are not changeable on a self-hosted solution in all fairness...

**Comment by dorpauli** [comment]
> > https://github.com/nextcloud/talk-android/issues/1835
> > 
> > Is the referenced issue not a clue to the problem? Has anyone done any research in this direction so far?
> > 
> > All the devices in my family (oneplus 7t, huawai p20, Samsung S22, Motorola G22) have this problem. So I don't think it's a problem with the devices.
> 
> If they really use such awful bitrate and settings then yes, this is the whole problem. I can't believe these settings are not changeable on a self-hosted solution in all fairness...

But it's not about the self hostet nextcloud instance. It's about the client (android app in this case) because this records the audio. Audio in nc talk browser is way better.

**Comment by nssatlantis** [comment]
> > > https://github.com/nextcloud/talk-android/issues/1835
> > > 
> > > Is the referenced issue not a clue to the problem? Has anyone done any research in this direction so far?
> > > 
> > > All the devices in my family (oneplus 7t, huawai p20, Samsung S22, Motorola G22) have this problem. So I don't think it's a problem with the devices.
> > 
> > If they really use such awful bitrate and settings then yes, this is the whole problem. I can't believe these settings are not changeable on a self-hosted solution in all fairness...
> 
> @nssatlantis 
> But it's not about the self hostet nextcloud instance. It's about the client (android app in this case) because this records the audio. Audio in nc talk browser is way better.



Even so, If the quality is really set to the specified low bitrate, then that would likely be the same on the app, and again it makes me question why this isn't a configurable option either way. Since you process the data yourself from android to server to reciever.

**Comment by RepLicanT-UHD** [comment]
I can attest to the Samsung A52's awful recording quality for voicemails.
In one of the discussions on the Android client and the second one on the web browser, I specifically recorded two voice messages.
While the web version has an adequate quality, the quality on Android is simply unimaginably inferior.
The Talk client for Android presently only records audio messages at a quality of... 10 kbps. Could you kindly add the voice quality settings?

**Comment by mahibi** [comment]
please test this apk https://github.com/nextcloud/talk-android/pull/2714#issuecomment-1400252696 
and let me know if the quality is better for you.

if it's not, please let me know which device you used.

**Comment by RepLicanT-UHD** [comment]
> please test this apk [#2714 (comment)](https://github.com/nextcloud/talk-android/pull/2714#issuecomment-1400252696) and let me know if the quality is better for you.
> 
> if it's not, please let me know which device you used.

Just tested. Quality of voice message is great now. Absolutely clear sound. Thanks a lot for that fix. When can we see it in the stable version in GooglePlay store?

**Comment by RepLicanT-UHD** [comment]
> this will be in 15.1.2 which should be out beginning/mid of february

Thanks! Great job!

**Comment by mahibi** [comment]
we had to make changes because my solution from yesterday failed playback on safari (it's quite some fiddling to support all platforms!).

Please give it another try with this updated apk: https://github.com/nextcloud/talk-android/pull/2714#issuecomment-1401680591 (quality is slightly lower than the solution from yesterday but we have to find one than okay for all platforms)

It would be great to have feedback if the voice message playback works for different browsers.

**Comment by RepLicanT-UHD** [comment]
> 



> we had to make changes because my solution from yesterday failed playback on safari (it's quite some fiddling to support all platforms!).
> 
> Please give it another try with this updated apk: [#2714 (comment)](https://github.com/nextcloud/talk-android/pull/2714#issuecomment-1401680591) (quality is slightly lower than the solution from yesterday but we have to find one that's okay for all platforms/browsers)
> 
> It would be great to have feedback if the recorded voice message from android is able to be played on different platforms/browsers.

Tested:

Samsung Galaxy A52 (Android):

--- Talk Application (recorded in QA version, played in GooglePlay version): everything is OK
--- Mobile browser (Firefox Android): everything is OK

Linux Mint:

--- Firefox: everything is ok
--- Ungoogled Chromium 108: everything is ok

Sound is still good, but with a little bit more noise in the background and the voice itself is a bit more flat.
But overall quality is still very good, especially compared to the current stable version.

Thank you!
