### ISSUE TITLE
No way of viewing/writing chat when in a call

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#163]
Oftentimes people post links in the chat during the call. It's not possible to check it out without disconnecting.

There should be a function to go back to the chat without dropping the call (probably a back icon in the top left). Ideally that also has a red dot icon added to it when there are new messages.

**Comment by jancborchardt** [comment]
@mario what’s your take on this? It is quite disruptive to any call on mobile unfortunately. :\

**Comment by mario** [comment]
We discussed this I think @jancborchardt when we talked about the product vision. While this is something we all want, this cannot come soon as there are more pressing issues atm.

**Comment by jancborchardt** [comment]
@mario ok, sure :) I added the issue to a new proposed 2.2 milestone. :)

**Comment by mario** [comment]
I think it's further down the road @jancborchardt, but let's see :)

**Comment by jancborchardt** [comment]
@ma12-co here's the design spec with what we talked about, including the indicator for new messages. :)

Only change to make it a bit more obvious is to use a "chat" icon in the top left instead of just a "back" arrow.

It should then be possible to get back into the call by tapping either of the "Voice call" or "Video call" icons. And ideally there's some sticky indicator of an ongoing call also when you go into other conversations.

**Comment by nickvergessen** [comment]
This is done in the meantime
