### ISSUE TITLE
Message notification setting to look like a subline

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1631]
As discussed last week, the message notification setting looks like a subline.
Instead it should be on the right side of the view similar to other settings in stock android.

**Comment by AndyScherzinger** [comment]
@nickvergessen Do you have a screenshot since I am not sure I know what needs to be changed where? :)

**Comment by nickvergessen** [comment]
Current | Should be
---|---
![Screenshot_2021-11-11-12-58-17-041_com nextcloud talk2](https://user-images.githubusercontent.com/213943/141294737-a2d4a07a-2f27-4239-a40c-9792e7f8d5c9.jpg) | ![Screenshot_2021-11-11-12-58-36-280_com nextcloud talk2](https://user-images.githubusercontent.com/213943/141294766-72119ac9-0e9b-4e23-8ba0-7054a7881514.jpg)

It looks like a subline, while the material design way is to have it on the right like in the proxy setting?

**Comment by AndyScherzinger** [comment]
Actually it is the other way around... it should be a subline and not be on the right, on the right you only show toggles, chosen values are display as a subline, see OS settings or any of the other settings on that screen like dark/light theme etc.

**Comment by nickvergessen** [comment]
Exactly where I looked, but I don't have native Google UI
![Screenshot_2021-11-11-13-40-38-828_com miui home](https://user-images.githubusercontent.com/213943/141299856-de56eabb-4c98-4f05-9b50-3be15835bff5.jpg)

**Comment by AndyScherzinger** [comment]
Ah, that is custom OEM. This is material atm
https://material.io/archive/guidelines/patterns/settings.html#

But I need to check if this changes with upcoming Material 3 or material you.

Which OS version do you have?

**Comment by nickvergessen** [comment]
MIUI 12.5.3
Android 11 RP1A.200720.011
Redmi Note 8 Pro

**Comment by AndyScherzinger** [comment]
Interesting, my OP9Pro Oxygen 11 / Android 11 puts them in a subline :/

**Comment by AndyScherzinger** [comment]
Checked Android 12 with material 3 / you on the emulator -> subline it is...
![device-2021-11-11-225221](https://user-images.githubusercontent.com/1315170/141374253-56720889-5e02-458e-ac16-351ea85d8e2b.png)

**Comment by AndyScherzinger** [comment]
PR opened :)
