### ISSUE TITLE
Avatar "hovercard"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1644]
On click on each avatar open bottom sheet with
- profile: opens (public profile) page in web browser
- mail: mailto link handled by OS
- talk: ~~either native app if installed or opens in web browser~~ open one-to-one

Server API: in https://github.com/nextcloud/files-clients/issues/1

**Comment by timkrueger** [comment]
Currently the result will look like that.

![Screenshot_1636039300](https://user-images.githubusercontent.com/606665/140349775-a11c1e8c-0fd9-4859-848d-60888773fe48.png)

https://user-images.githubusercontent.com/606665/140353956-3065a4d0-7ab1-45dd-b91b-b468157827c7.mp4
