### ISSUE TITLE
In mention notification, show actual message in second line

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#165]
Currently the notification only says: "Tobias mentioned you in a gr…" (can't read more because it's phone width - but it should say the call name instead of what I assume to be "group call").

**And the point: We should show the actual message in the second row here.**

**Comment by mario** [comment]
Please file this issue against the spreed repository since the server generates notifications.

**Comment by jancborchardt** [comment]
Done https://github.com/nextcloud/spreed/issues/879
