### ISSUE TITLE
Own message text should be white to not look inactive

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#166]
Currently your own messages look like this
 ![](https://i.imgur.com/kZocYkf.jpg)

The text is a bit transparent it seems (or just colored) which makes it look inactive/disabled or as if it was not sent yet.

It should be proper #fff white to not confuse in this way.

**Comment by mario** [comment]
The reason why it's like that is simple - mentions are white for the outgoing messages.

Regular text for outgoing messages is: #99DBFF

**Comment by jancborchardt** [comment]
But mentions are also bold, so it's not necessary to also differentiate by text color. :)

**Comment by mario** [comment]
Fixed.

**Comment by jancborchardt** [comment]
Thank you! :)
