### ISSUE TITLE
Handle "End meeting for all" case

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1660]
With Talk 13 "End meeting for all" is coming. When the moderator does this, the app should terminate the call screen but currently the user stays on the empty call view.

Ref https://github.com/nextcloud/spreed/pull/5981

**Comment by nickvergessen** [comment]
Also make sure the system message `call_ended_everyone` renders correctly

**Comment by mahibi** [comment]
if anyone else is also wondering how to get the "end meeting for all" button: you have to set participants permissions to "restricted"..

![grafik](https://user-images.githubusercontent.com/2932790/146361861-8dbb7c1e-3c5d-48b8-9f34-e9511a9c3f4b.png)
