### ISSUE TITLE
hard to scroll a prefilled message

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#1672]
## Steps to reproduce
1. fill in 5-6 lines of words 
2. now change something in the 1st line. 
3. it's hard to come back to the last line

In signal this is a little bit easier solved. 

Edit: It seems to be phone depending: redmi is working, Oneplus and Samsung not.
I have noticed that if you "hold" the cursor you can scroll, without it it is almost impossible to get back to the first line.

https://user-images.githubusercontent.com/24530680/141931217-ce59c3cb-129c-4ec3-b81b-09f8f0de3d58.mp4

**Comment by mahibi** [comment]
i didn't get it yet..
why is it hard to come back to the last line? scrolling works fine..? or doesn't it work as expected?

**Comment by mahibi** [comment]
@jakobroehrl i remember you had some video for this?

**Comment by jakobroehrl** [comment]
Still a problem

**Comment by jakobroehrl** [comment]
This is solved, I think
