### ISSUE TITLE
Video Flickering when rotating screen from landscape to horizontal and when going into PIP 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-android#1679]
## Steps to reproduce
1. Join Group Chat
2. Rotate the screen landscape 
3. Back horizontal 

### Actual behaviour
One of the videos flaker

## Device information

**Device:** Fairphone2/…
Oneplus N200 5G
**Android version:** 10/…
Oxygen OS 11.0.3.0.DE17AA
**Talk version:** 11.0.0
v13.0.0 RC1
## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)
22.2.2
**Talk version:** (see apps admin page: `/index.php/settings/apps`)
12.1.2
**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
No
**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`)
Yes
**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`)
Yes

https://user-images.githubusercontent.com/59488153/141349078-534021bb-480e-4372-a9e9-16e7df32419c.mp4

**Comment by andyxheli** [comment]
This also started to happen when i went into PIP mode and back to full screen.

**Comment by andyxheli** [comment]
This is still an issue on NC 14.0.1 RC1 @AndyScherzinger I'm sorry to ping you. Do you think we can have some input on this ? I just did a test on NC 14.0.1 RC and same result. As soon as i go into PIP mode and back into full screen getting flickering & same results for rotating the screen.  Again I'm sorry to ping you. Please let me know
