### ISSUE TITLE
View "breaks" when @-mentioning empty string

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#168]
* Start typing: `Nice @admin`
* Before sending remove text until you have `Nice @`

### Expected

You can still type and do something

### Actually

Input breaks somehow, keyboard is visible, but the input field is missing:
![screenshot_20180509-142756](https://user-images.githubusercontent.com/213943/39814604-5076cbae-5395-11e8-9bc0-312174b9dd33.png)

**Comment by mario** [comment]
Will see if I can reproduce. What phone and Android version?

**Comment by nickvergessen** [comment]
Xiaomi Mi A1 - Android 8.0

**Comment by mario** [comment]
XIaomi :(

**Comment by mario** [comment]
Fixed, thanks for the report.
