### ISSUE TITLE
13.0.0 RC1: Upload from camera: HQ vs LQ

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#1694]
It's hard for me as user to understand if I do a photo in high oder low qualitiy.

As tested, if it shows LQ the photo is big, if it shows HQ it's big.

**Comment by AndyScherzinger** [comment]
@nextcloud/designers @ASerbinski as discussed in the cam upload PR, atm all buttons refer to the action triggered not the current state the UI/cam is in, but maybe we would want to switch that for _resolution_ and _aspect-ratio_
![device-2021-11-10-000645](https://user-images.githubusercontent.com/1315170/141020602-f5cb9dfb-610d-4e41-b810-85d8f54ed2c3.png)

**Comment by ASerbinski** [comment]
FWIW, I've just looked at both AOSP camera and GrapheneOS camera (https://github.com/GrapheneOS/Camera), and on both, all of the toggle buttons show the state it is currently in.

**Comment by nimishavijay** [comment]
Ideally all the buttons should follow the same logic, and since many apps show the current state (and not the action to be triggered) we can go ahead with that for ALL the buttons, what do you think?

**Comment by AndyScherzinger** [comment]
@nimishavijay yes, completely agree and done via #1694 👍  Thanks for the quick feedback 🙏

**Comment by dvergeylen** [comment]
> @nimishavijay yes, completely agree and done via #1694 +1 Thanks for the quick feedback pray

you probably meant #1706 🙂

**Comment by AndyScherzinger** [comment]
@dvergeylen yes, whoops 😄
