### ISSUE TITLE
13.0.0 RC1: Only PiP is shown, button bar is gone

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#1711]
1. start a video call with at least 2 users
2. use pip with one of this users (eg user X)
3. if all user left the call expect user X, the button bar is gone, no possibility to left the call with the red button, only the pip window is shown:
![image](https://user-images.githubusercontent.com/24530680/142368008-3baa7120-235a-4e40-95b6-9d996a6d7852.png)

**Comment by mahibi** [comment]
should be fixed with https://github.com/nextcloud/talk-android/pull/1696 and will be available with RC2

**Comment by mahibi** [comment]
can you confirm this is fixed @jakobroehrl ?
