### ISSUE TITLE
Push Notifications are not working

### ISSUE THREAD

**Issue by YasTouchedMySpaggett** [nextcloud/talk-android#1717]
1. Recieve message

### Expected behaviour
I should have received a notification on my android devide

### Actual behaviour
I do not receive any notifications

## Device information

**Device:** Pixel 6

**Android version:** 12

**Talk version:** 13.0.0

## Server information

**Nextcloud version:** 23.0.0

**Talk version:** 	13.0.0

**Comment by EdoardoVignati** [comment]
Same behavior with

- Talk version 12.2.1
- Nextcloud version 22.2.3

**Comment by lbdroid** [comment]
Where did you get Talk apk file from?
Does your phone have google services installed/working and linked with a google account?

**Comment by YasTouchedMySpaggett** [comment]
I got nextcloud talk from the playstore (on my pixep 6) and previously it was from F-Droid (oneplus 6). Yes i have Google services and they are linked to my google account(both devices)

**Comment by lbdroid** [comment]
Ok, so since your bug report says "Device: Oneplus 6", and you also say "it was from F-Droid (oneplus 6)", I'll say...

"Working as expected".

The f-droid builds do NOT support push notifications since those notifications depend on closed source components of goog.

Can you confirm that you are experiencing the same issues on the Pixel 6?

**Comment by YasTouchedMySpaggett** [comment]
>>Can you confirm that you are experiencing the same issues on the Pixel 6?<< Yes, and my girlfriend also experiences this on her P20Lite with Talk from the google play store.

**Comment by lbdroid** [comment]
First, try clearing out the contents of the {prefix}_notifications_pushhash table and reconnect.

Second, try applying this PR to the server side; https://github.com/nextcloud/spreed/pull/1970

**Comment by YasTouchedMySpaggett** [comment]
Thank you, , i will try thia and update the thread.

Your help is much appriciated

**Comment by YasTouchedMySpaggett** [comment]
> First, try clearing out the contents of the {prefix}_notifications_pushhash table and reconnect.

Sorry for asking just now ( i just found sometime to troubleshoot my instalation ) , how do i do that?

**Comment by EdoardoVignati** [comment]
> > First, try clearing out the contents of the {prefix}_notifications_pushhash table and reconnect.
> 
> Sorry for asking just now ( i just found sometime to troubleshoot my instalation ) , how do i do that?

@YasTouchedMySpaggett  the table is in the database (oc_notifications_pushhash in my case)

**Comment by YasTouchedMySpaggett** [comment]
I reinstalled nextcloud ( i broke my instance doing something else, i restored all my files no problem there ) and I am at the latest version of both nextcloud and talk ( nextcloud app and android app ). I had the same problem and I cleared the table you mentioned and reconnected. I experience the same problem sadly... at this point I have lost hope for push notifications lmao. JFYI I'm running webmin/virtualmin and I manage my installation from there if that helps. All the other features work normally.

**Comment by lbdroid** [comment]
I gave you two suggestions. One you've tried, and the other you have not. Try it.

**Comment by YasTouchedMySpaggett** [comment]
> I gave you two suggestions. One you've tried, and the other you have not. Try it.

I have tried the second suggestion as well. In my new installation i personally ( only on my account and device ) get notifications. I tried applying the patch again and clearing the table as well but other users do not get notifications. Is there anything else i can do?

**Comment by mahibi** [comment]
hi @YasTouchedMySpaggett sorry for the late answer. 
Did you check the items from this checklist?: https://github.com/nextcloud/talk-android/blob/master/docs/notifications.md

**Comment by lbdroid** [comment]
> > I gave you two suggestions. One you've tried, and the other you have not. Try it.
> 
> I have tried the second suggestion as well. In my new installation i personally ( only on my account and device ) get notifications. I tried applying the patch again and clearing the table as well but other users do not get notifications. Is there anything else i can do?

Anything in common between the users who work and the users who don't?
For example, all the non-working users have apple devices?
All the non-working users use the f-droid build?
Both of the above maybe?

**Comment by mahibi** [comment]
leave this issue open no-response bot!

**Comment by EdoardoVignati** [comment]
I fixed basically checking out  Security & setup warnings, then I found I had a problem with the caching system (APCu)
