### ISSUE TITLE
make application logo for statusbar black/white

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#1718]
currently the application logo for statusbar is colored. it should be black/white.
(also applies for branding)

**Comment by AndyScherzinger** [comment]
@mahibi do you have a screenshot about the issue, for me everything seems fine, color-wise, no?

**Comment by mahibi** [comment]
@AndyScherzinger see screenshots for https://github.com/nextcloud/talk-android/pull/1655 when pip is in action

**Comment by AndyScherzinger** [comment]
It seems you are using the launcher icon instead of the notification icon then, no?

**Comment by mahibi** [comment]
While being in PIP mode, the colored application logo in the statusbar doesn't come from the app itself.
It's a notification that seems to pop up by Android system on some Xiaomi devices:

![grafik](https://user-images.githubusercontent.com/2932790/146898437-866ae065-7ab5-47f0-b0e8-32f75a2c0323.png)

I won't invest time in this and close this issue. Other notifications are fine color-wise.


> It seems you are using the launcher icon instead of the notification icon then, no?

yes the launcher seems to be used instead of a notification icon. 
https://github.com/nextcloud/talk-android/blob/172d8da1cfef1a38d3ee20fb30adb8ac2d131d03/app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java#L278
might be changed but will require work on brander as well.
