### ISSUE TITLE
Blank Screen. No voice no video

### ISSUE THREAD

**Issue by Vaibhav1587** [nextcloud/talk-android#172]
Build the application using the current master build.. App not working tried following combinations. 

- WEB to Android app - didn't work
- iOS App to Android App - didn't work
- Android app to iOS app - didnt work

Whereas iOS app working fine. 

Tested on Moto X Play.

**Comment by mario** [comment]
Strange. What Android version and do you have TURN server?

**Comment by mario** [comment]
Also what commit did you compile? I did a lot of changes yesterday :)

**Comment by Vaibhav1587** [comment]
Android version 
    compileSdkVersion 27
    buildToolsVersion '27.0.3'

Do have the TURN server . Web to Web n iPhone to Web calls are working. 

Taken code on Tuesday.

**Comment by mario** [comment]
Take code today :)

**Comment by Vaibhav1587** [comment]
Build the application with latest code. 
After login nothing happens endless loading spinner. 
complete log in the IDE as follow,

> 05-15 00:06:04.491 8096-8096/? I/art: Late-enabling -Xcheck:jni
> 05-15 00:06:04.612 8096-8096/? I/MultiDex: VM with version 2.1.0 has multidex support
>     Installing application
>     VM has multidex support, MultiDex support library is disabled.
>     Installing application
>     VM has multidex support, MultiDex support library is disabled.
> 05-15 00:06:04.628 8096-8096/? I/art: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.app.JobIntentService$JobServiceEngineImpl>
> 05-15 00:06:04.629 8096-8096/? I/art: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.app.JobIntentService$JobServiceEngineImpl>
> 05-15 00:06:04.642 8096-8096/? I/org.webrtc.Logging: NativeLibrary: Loading native library.
>     NativeLibrary: Loading library: jingle_peerconnection_so
> 05-15 00:06:04.663 8096-8102/? E/art: Failed sending reply to debugger: Broken pipe
> 05-15 00:06:04.663 8096-8102/? I/art: Debugger is no longer active
> 05-15 00:06:04.925 8096-8121/? D/JobProxy21: Schedule periodic (flex support) jobInfo success, request{id=3, tag=CapabilitiesJob, transient=false}, start 23:00:00, end 00:00:00 (+1 day), flex 01:00:00
> 05-15 00:06:04.937 8096-8106/? I/art: Background sticky concurrent mark sweep GC freed 13508(791KB) AllocSpace objects, 4(80KB) LOS objects, 28% free, 8MB/11MB, paused 1.351ms total 108.506ms
> 05-15 00:06:05.040 8096-8096/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
> 05-15 00:06:05.194 8096-8096/? I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.sql.ManagedTransaction>
>     Rejecting re-init on previously-failed class java.lang.Class<io.requery.sql.ManagedTransaction>
> 05-15 00:06:06.125 8096-8096/com.nextcloud.talk2 I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.query.BaseScalar$1>
>     Rejecting re-init on previously-failed class java.lang.Class<io.requery.query.BaseScalar$1>
> 05-15 00:06:06.927 8096-8172/com.nextcloud.talk2 D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
> 05-15 00:06:06.968 8096-8174/com.nextcloud.talk2 D/PlatformAlarmService: Run job, request{id=4, tag=CapabilitiesJob, transient=false}, waited 00:00:02, delay 00:00:00
> 05-15 00:06:06.972 8096-8174/com.nextcloud.talk2 I/JobExecutor: Executing request{id=4, tag=CapabilitiesJob, transient=false}, context PlatformAlarmService
> 05-15 00:06:06.982 8096-8119/com.nextcloud.talk2 I/JobExecutor: Finished job{id=4, finished=true, result=SUCCESS, canceled=false, periodic=false, class=CapabilitiesJob, tag=CapabilitiesJob}
> 05-15 00:06:06.984 8096-8174/com.nextcloud.talk2 D/PlatformAlarmService: Finished job, request{id=4, tag=CapabilitiesJob, transient=false} SUCCESS
> 05-15 00:06:06.988 8096-8174/com.nextcloud.talk2 D/PlatformAlarmService: Run job, request{id=2, tag=AccountRemovalJob, transient=false}, waited 00:00:02, delay 00:00:00
> 05-15 00:06:06.990 8096-8174/com.nextcloud.talk2 I/JobExecutor: Executing request{id=2, tag=AccountRemovalJob, transient=false}, context PlatformAlarmService
> 05-15 00:06:06.995 8096-8119/com.nextcloud.talk2 I/JobExecutor: Finished job{id=2, finished=true, result=SUCCESS, canceled=false, periodic=false, class=AccountRemovalJob, tag=AccountRemovalJob}
> 05-15 00:06:07.001 8096-8174/com.nextcloud.talk2 D/PlatformAlarmService: Finished job, request{id=2, tag=AccountRemovalJob, transient=false} SUCCESS
> 05-15 00:06:07.007 8096-8174/com.nextcloud.talk2 D/PlatformAlarmService: Run job, request{id=1, tag=PushRegistrationJob, transient=false}, waited 00:00:02, delay 00:00:00
> 05-15 00:06:07.010 8096-8174/com.nextcloud.talk2 I/JobExecutor: Executing request{id=1, tag=PushRegistrationJob, transient=false}, context PlatformAlarmService
> 05-15 00:06:07.098 8096-8172/com.nextcloud.talk2 I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (Ifd751822f5)
>     OpenGL ES Shader Compiler Version: XE031.06.00.05
>     Build Date: 01/26/16 Tue
>     Local Branch: AU12_SBA
>     Remote Branch: 
>     Local Patches: 
>     Reconstruct Branch: 
> 05-15 00:06:07.104 8096-8172/com.nextcloud.talk2 I/OpenGLRenderer: Initialized EGL, version 1.4
> 05-15 00:06:11.214 8096-8119/com.nextcloud.talk2 I/JobExecutor: Finished job{id=1, finished=true, result=SUCCESS, canceled=false, periodic=false, class=PushRegistrationJob, tag=PushRegistrationJob}
> 05-15 00:06:11.216 8096-8174/com.nextcloud.talk2 D/PlatformAlarmService: Finished job, request{id=1, tag=PushRegistrationJob, transient=false} SUCCESS
> 05-15 00:07:05.383 8096-8096/com.nextcloud.talk2 E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
>     SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
> 05-15 00:07:05.821 8096-8096/com.nextcloud.talk2 E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
>     SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
> 05-15 00:07:06.344 8096-8096/com.nextcloud.talk2 E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
>     SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
> 05-15 00:07:10.739 8096-8577/com.nextcloud.talk2 D/OkHttp: --> GET https://xxx.xxxxxxxx.com/status.php
>     --> END GET
> 05-15 00:07:11.060 8096-8577/com.nextcloud.talk2 D/OkHttp: <-- 200 OK https://xxx.xxxxxxxx.com/status.php (319ms)
>     Date: Mon, 14 May 2018 18:36:55 GMT
>     Server: Apache
>     X-Powered-By: PHP/5.6.36
>     Expires: Thu, 19 Nov 1981 08:52:00 GMT
>     Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
>     Pragma: no-cache
>     Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval' 'nonce-aWd1a09pSnh1SVpqNEI0Q3JuVTJlSE80QXRldmdzWmRqK3hzSWdKV3dZbz06czBpWGExZ2QwL1JScEdndDZrRjhOVWY2UlpMQjRhaHE1NTBiUldkbXFxRT0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
>     X-Frame-Options: SAMEORIGIN
>     Access-Control-Allow-Origin: *
>     Set-Cookie: ochjaxalez7q=7ac2fibl12i51n9tn6vji0ngh3; path=/xxxxxxx; secure; HttpOnly
>     Set-Cookie: oc_sessionPassphrase=0GUuxQvH5PDsPUpc7uCOA6WI4I3f7WnAnHdk2L%2FjMLPP3WICIMe%2B0m1kGa7bPXAE2wfJGgIQREO79U2HEeW69Db2UQWMKkonoU%2BMw4quEvcB7ZwlQHWu6%2BhT0NORMTzK; path=/xxxxxxx; secure; httponly
>     Set-Cookie: nc_sameSiteCookielax=true; path=/xxxxxxx; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
>     Set-Cookie: nc_sameSiteCookiestrict=true; path=/xxxxxxx; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
>     X-Content-Type-Options: nosniff
>     X-XSS-Protection: 1; mode=block
>     X-Robots-Tag: none
>     X-Download-Options: noopen
>     X-Permitted-Cross-Domain-Policies: none
>     Keep-Alive: timeout=3, max=30
>     Connection: Keep-Alive
>     Transfer-Encoding: chunked
>     Content-Type: application/json
> 05-15 00:07:11.063 8096-8577/com.nextcloud.talk2 D/OkHttp: {"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"13.0.1.1","versionstring":"13.0.1","edition":"","productname":"8Cloud8"}
>     <-- END HTTP (144-byte body)
> 05-15 00:07:11.107 8096-8096/com.nextcloud.talk2 I/WebViewFactory: Loading com.google.android.webview version 66.0.3359.126 (code 335912600)
> 05-15 00:07:11.238 8096-8096/com.nextcloud.talk2 I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
>     Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
> 05-15 00:07:11.246 8096-8096/com.nextcloud.talk2 I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
>     Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
> 05-15 00:07:11.251 8096-8096/com.nextcloud.talk2 I/cr_LibraryLoader: Time to load native libraries: 1 ms (timestamps 621-622)
> 05-15 00:07:11.280 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
> 05-15 00:07:11.280 8096-8096/com.nextcloud.talk2 I/cr_LibraryLoader: Expected native library version number "66.0.3359.126", actual native library version number "66.0.3359.126"
> 05-15 00:07:11.319 8096-8096/com.nextcloud.talk2 I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
> 05-15 00:07:11.322 8096-8096/com.nextcloud.talk2 I/cr_base: Android Locale: en_GB requires .pak files: []
> 05-15 00:07:11.431 8096-8096/com.nextcloud.talk2 I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$7>
>     Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$7>
> 05-15 00:07:11.433 8096-8096/com.nextcloud.talk2 I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$3>
>     Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$3>
> 05-15 00:07:11.626 8096-8618/com.nextcloud.talk2 E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
> 05-15 00:07:11.758 8096-8618/com.nextcloud.talk2 W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
> 05-15 00:07:11.776 8096-8624/com.nextcloud.talk2 W/cr_CrashFileManager: /data/user/0/com.nextcloud.talk2/cache/WebView/Crash Reports does not exist or is not a directory
> 05-15 00:07:11.782 8096-8618/com.nextcloud.talk2 W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
> 05-15 00:07:11.825 8096-8618/com.nextcloud.talk2 I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
> 05-15 00:07:14.699 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(7)] "JQMIGRATE: Migrate is installed, version 1.4.0", source: https://xxx.xxxxxxxx.com/core/vendor/core.js?v=31c80262 (7)
> 05-15 00:07:29.301 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(7)] "JQMIGRATE: Migrate is installed, version 1.4.0", source: https://xxx.xxxxxxxx.com/core/vendor/core.js?v=31c80262 (7)
> 05-15 00:07:29.954 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(13)] "I turned out your storage and deleted 0 entries.", source: https://xxx.xxxxxxxx.com/apps/ojsxc/js/jsxc/jsxc.min.js?v=31c80262 (13)
> 05-15 00:07:29.955 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(13)] "State changed to INITIATING", source: https://xxx.xxxxxxxx.com/apps/ojsxc/js/jsxc/jsxc.min.js?v=31c80262 (13)
> 05-15 00:07:29.973 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(13)] "Try to relogin", source: https://xxx.xxxxxxxx.com/apps/ojsxc/js/jsxc/jsxc.min.js?v=31c80262 (13)
> 05-15 00:07:29.974 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(13)] "Logout was forced or I found no valid jid", source: https://xxx.xxxxxxxx.com/apps/ojsxc/js/jsxc/jsxc.min.js?v=31c80262 (13)
> 05-15 00:07:29.975 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(13)] "State changed to TRYTOINTERCEPT", source: https://xxx.xxxxxxxx.com/apps/ojsxc/js/jsxc/jsxc.min.js?v=31c80262 (13)
> 05-15 00:07:29.977 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(13)] "State changed to INTERCEPTED", source: https://xxx.xxxxxxxx.com/apps/ojsxc/js/jsxc/jsxc.min.js?v=31c80262 (13)
> 05-15 00:08:02.759 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(13)] "Variable adminSettings doesn't exist. It was created.", source: https://xxx.xxxxxxxx.com/apps/ojsxc/js/jsxc/jsxc.min.js?v=31c80262 (13)
> 05-15 00:08:02.761 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(13)] "Variable loginForm doesn't exist. It was created.", source: https://xxx.xxxxxxxx.com/apps/ojsxc/js/jsxc/jsxc.min.js?v=31c80262 (13)
> 05-15 00:08:02.764 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(13)] "[WARN] No settings provided", source: https://xxx.xxxxxxxx.com/apps/ojsxc/js/jsxc/jsxc.min.js?v=31c80262 (13)
> 05-15 00:08:04.553 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(7)] "JQMIGRATE: Migrate is installed, version 1.4.0", source: https://xxx.xxxxxxxx.com/core/vendor/core.js?v=31c80262 (7)
> 05-15 00:08:05.031 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(13)] "State changed to INITIATING", source: https://xxx.xxxxxxxx.com/apps/ojsxc/js/jsxc/jsxc.min.js?v=31c80262 (13)
> 05-15 00:08:05.047 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(13)] "Try to relogin", source: https://xxx.xxxxxxxx.com/apps/ojsxc/js/jsxc/jsxc.min.js?v=31c80262 (13)
> 05-15 00:08:05.048 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(13)] "Logout was forced or I found no valid jid", source: https://xxx.xxxxxxxx.com/apps/ojsxc/js/jsxc/jsxc.min.js?v=31c80262 (13)
>     [INFO:CONSOLE(13)] "State changed to SUSPEND", source: https://xxx.xxxxxxxx.com/apps/ojsxc/js/jsxc/jsxc.min.js?v=31c80262 (13)
> 05-15 00:08:05.049 8096-8096/com.nextcloud.talk2 I/chromium: [INFO:CONSOLE(13)] "[WARN] Unable to create user prefix", source: https://xxx.xxxxxxxx.com/apps/ojsxc/js/jsxc/jsxc.min.js?v=31c80262 (13)
> 05-15 00:08:05.814 8096-8577/com.nextcloud.talk2 D/OkHttp: --> GET https://xxx.xxxxxxxx.com/ocs/v2.php/apps/spreed/api/v1/room
>     Authorization: Basic Z3Jhc3NwYWw6cU02ekZuem5VcXR
>     --> END GET
> 05-15 00:08:06.183 8096-8172/com.nextcloud.talk2 E/chromium: [ERROR:gl_context_virtual.cc(39)] Trying to make virtual context current without decoder.
> 05-15 00:08:07.776 8096-8577/com.nextcloud.talk2 D/OkHttp: <-- 200 OK https://xxx.xxxxxxxx.com/ocs/v2.php/apps/spreed/api/v1/room (1962ms)
>     Date: Mon, 14 May 2018 18:37:51 GMT
>     Server: Apache
>     X-Powered-By: PHP/5.6.36
>     Expires: Thu, 19 Nov 1981 08:52:00 GMT
>     Pragma: no-cache
>     X-Frame-Options: SAMEORIGIN
>     Cache-Control: no-cache, no-store, must-revalidate
> 05-15 00:08:07.777 8096-8577/com.nextcloud.talk2 D/OkHttp: Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self'
>     Set-Cookie: oc_sessionPassphrase=lkv48FiFnCv1VDY4jgMB2I09NgE1nWX6gXW2avYbqQvyBU1sc1cHOvA8vnPzT2C7k6eCkMwYtpHbU6KEdCgGHF1J3m8Kt2AmS4U5oaa4n9tJPZZ4%2FPl7R2%2BABHyN28%2FW; path=/xxxxxxx; secure; httponly
>     Set-Cookie: nc_sameSiteCookielax=true; path=/xxxxxxx; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
>     Set-Cookie: nc_sameSiteCookiestrict=true; path=/xxxxxxx; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
>     Set-Cookie: ochjaxalez7q=ndjplq0jv7roj6o57b2dqa3k03; path=/xxxxxxx; secure; HttpOnly
>     Content-Length: 705
>     X-Content-Type-Options: nosniff
>     X-XSS-Protection: 1; mode=block
>     X-Robots-Tag: none
>     X-Download-Options: noopen
>     X-Permitted-Cross-Domain-Policies: none
>     Keep-Alive: timeout=3, max=30
>     Connection: Keep-Alive
>     Content-Type: application/json; charset=utf-8
> 05-15 00:08:07.779 8096-8577/com.nextcloud.talk2 D/OkHttp: {"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":[{"id":35,"token":"poxy3836","type":1,"name":"ganesh","displayName":"ganesh","participantType":1,"participantInCall":false,"count":0,"hasPassword":false,"hasCall":false,"unreadMessages":0,"lastPing":1526321779,"sessionId":"ejsBBOaXa9TeFQ8FCNTW7iBKfCm0xpwNFVZ9bn9fBfQpZY49bXitohOhU1o9PFjHkCUjAiIFLP0KLLAJ4DdUmACiYU\/gDy14fV1hyC9cmtpipSdk4TaGiKIZS9FN+Lh90","participants":{"xxxxxxxx":{"name":"xxxxxxxx","type":1,"call":false},"ganesh":{"name":"ganesh","type":1,"call":false}},"numGuests":0,"guestList":""}]}}
>     <-- END HTTP (705-byte body)
> 05-15 00:08:07.802 8096-8577/com.nextcloud.talk2 D/OkHttp: --> GET https://xxx.xxxxxxxx.com/ocs/v2.php/cloud/user
>     Authorization: Basic Z3Jhc3NwYWw6cU02ekZuem5VcXR
>     --> END GET
> 05-15 00:08:08.383 8096-8577/com.nextcloud.talk2 D/OkHttp: <-- 200 OK https://xxx.xxxxxxxx.com/ocs/v2.php/cloud/user (581ms)
>     Date: Mon, 14 May 2018 18:37:53 GMT
>     Server: Apache
>     X-Powered-By: PHP/5.6.36
>     Expires: Thu, 19 Nov 1981 08:52:00 GMT
> 05-15 00:08:08.384 8096-8577/com.nextcloud.talk2 D/OkHttp: Pragma: no-cache
>     X-Frame-Options: SAMEORIGIN
>     Cache-Control: no-cache, no-store, must-revalidate
>     Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self'
>     Content-Length: 319
>     X-Content-Type-Options: nosniff
>     X-XSS-Protection: 1; mode=block
>     X-Robots-Tag: none
>     X-Download-Options: noopen
>     X-Permitted-Cross-Domain-Policies: none
>     Keep-Alive: timeout=3, max=29
>     Connection: Keep-Alive
>     Content-Type: application/json; charset=utf-8
> 05-15 00:08:08.386 8096-8577/com.nextcloud.talk2 D/OkHttp: {"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"id":"xxxxxxxx","quota":{"free":4460231565312,"used":85734746,"total":4460317300058,"relative":0,"quota":-3},"email":"vaibhav@xxxxxxxxxx.com","phone":"","address":"","website":"","twitter":"","groups":[],"language":"en","display-name":"xxxxxxxx"}}}
>     <-- END HTTP (319-byte body)
> 05-15 00:08:08.708 8096-8831/com.nextcloud.talk2 D/PlatformAlarmService: Run job, request{id=5, tag=PushRegistrationJob, transient=false}, waited 00:00:00, delay 00:00:00
> 05-15 00:08:08.715 8096-8831/com.nextcloud.talk2 I/JobExecutor: Executing request{id=5, tag=PushRegistrationJob, transient=false}, context PlatformAlarmService
> 05-15 00:08:08.731 8096-8832/com.nextcloud.talk2 I/JobExecutor: Finished job{id=5, finished=true, result=SUCCESS, canceled=false, periodic=false, class=PushRegistrationJob, tag=PushRegistrationJob}
> 05-15 00:08:08.734 8096-8831/com.nextcloud.talk2 D/PlatformAlarmService: Finished job, request{id=5, tag=PushRegistrationJob, transient=false} SUCCESS
> 05-15 00:12:53.301 8096-8101/com.nextcloud.talk2 I/art: Thread[2,tid=8101,WaitingInMainSignalCatcherLoop,Thread*=0xb79dca58,peer=0x22c070a0,"Signal Catcher"]: reacting to signal 3
> 05-15 00:12:53.747 8096-8101/com.nextcloud.talk2 I/art: Wrote stack traces to '/data/anr/traces.txt'
> 05-15 00:13:27.547 8096-8107/com.nextcloud.talk2 I/art: Starting a blocking GC Explicit
> 05-15 00:13:27.620 8096-8107/com.nextcloud.talk2 I/art: Explicit concurrent mark sweep GC freed 66087(2MB) AllocSpace objects, 4(208KB) LOS objects, 40% free, 11MB/19MB, paused 999us total 71.918ms
> 05-15 00:13:27.650 8096-8107/com.nextcloud.talk2 I/art: Starting a blocking GC Explicit
> 05-15 00:13:27.683 8096-8107/com.nextcloud.talk2 I/art: Explicit concurrent mark sweep GC freed 2662(84KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 11MB/19MB, paused 1.243ms total 33.053ms
> 05-15 00:13:27.701 8096-8107/com.nextcloud.talk2 I/art: Starting a blocking GC Explicit
> 05-15 00:13:27.734 8096-8107/com.nextcloud.talk2 I/art: Explicit concurrent mark sweep GC freed 3352(104KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 11MB/19MB, paused 1.358ms total 32.802ms
> 05-15 00:13:27.750 8096-8107/com.nextcloud.talk2 I/art: Starting a blocking GC Explicit
> 05-15 00:13:27.780 8096-8107/com.nextcloud.talk2 I/art: Explicit concurrent mark sweep GC freed 9109(284KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 11MB/18MB, paused 820us total 29.299ms
> 05-15 00:13:27.795 8096-8107/com.nextcloud.talk2 I/art: Starting a blocking GC Explicit
> 05-15 00:13:27.825 8096-8107/com.nextcloud.talk2 I/art: Explicit concurrent mark sweep GC freed 10650(332KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 10MB/18MB, paused 847us total 29.582ms
> 05-15 00:13:48.493 8096-8108/com.nextcloud.talk2 I/art: Starting a blocking GC Explicit
> 05-15 00:13:48.519 8096-8108/com.nextcloud.talk2 I/art: Explicit concurrent mark sweep GC freed 17772(640KB) AllocSpace objects, 1(20KB) LOS objects, 40% free, 10MB/17MB, paused 869us total 26.342ms
> 05-15 00:13:48.533 8096-8108/com.nextcloud.talk2 I/art: Starting a blocking GC Explicit
> 05-15 00:13:48.555 8096-8108/com.nextcloud.talk2 I/art: Explicit concurrent mark sweep GC freed 3009(100KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 10MB/17MB, paused 712us total 21.560ms
> 05-15 00:13:48.568 8096-8108/com.nextcloud.talk2 I/art: Starting a blocking GC Explicit
> 05-15 00:13:48.589 8096-8108/com.nextcloud.talk2 I/art: Explicit concurrent mark sweep GC freed 13(480B) AllocSpace objects, 0(0B) LOS objects, 40% free, 10MB/17MB, paused 707us total 20.879ms
> 05-15 00:13:48.602 8096-8108/com.nextcloud.talk2 I/art: Starting a blocking GC Explicit
> 05-15 00:13:48.624 8096-8108/com.nextcloud.talk2 I/art: Explicit concurrent mark sweep GC freed 13(480B) AllocSpace objects, 0(0B) LOS objects, 40% free, 10MB/17MB, paused 720us total 20.952ms
> 05-15 00:13:48.637 8096-8108/com.nextcloud.talk2 I/art: Starting a blocking GC Explicit
> 05-15 00:13:48.658 8096-8108/com.nextcloud.talk2 I/art: Explicit concurrent mark sweep GC freed 13(480B) AllocSpace objects, 0(0B) LOS objects, 40% free, 10MB/17MB, paused 706us total 20.981ms
> 

Need to swap out application and open again to get it working. Still didn't able to receive any call not even a notification for the call. Where as on iOS able to get the notification as well as connect to the call with some delay from android app.
When I call from the iOS app, android shows "Dumping memory app will freeze. Brrrr." No notification nothing. Screenshot of the same is attached. 

![nextcloud_after_login](https://user-images.githubusercontent.com/34318157/40018862-2f346d80-57db-11e8-951d-b8fe19c4f7e4.png)
![nextcloud_memory_leaks](https://user-images.githubusercontent.com/34318157/40018863-2f6c92f0-57db-11e8-9c9d-4756e45380b6.png)
![nextcloud_toast_after_call](https://user-images.githubusercontent.com/34318157/40018864-2f9e4886-57db-11e8-8227-3f396ad9d5a1.png)

**Sorry for the long post..** :|

**Comment by Vaibhav1587** [comment]
Thanks for the reply.

Which version should I compile? n how? :-? 
Notification app is installed on the server and its enabled.

**Comment by mario** [comment]
It's all good, the debug version isn't bad. But I don't see why there's no push activity. 

I know the trouble with push notifications, it's fixed in the current master.

But no idea about the black screen - what phone you have? (vendor + android version)

**Comment by mario** [comment]
Ah you said Moto X Play, but not the Android version?
Can you send a test account to mario@nextcloud.com?

**Comment by mario** [comment]
Closing because I can't reproduce and it doesn't seem to be a problem with the app, but rather the setup.
