### ISSUE TITLE
show notifications for missed calls (+ improve duration for ringing)

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#1724]
https://github.com/nextcloud/talk-android/pull/1634 fixed that the phone rings only for 1 minute and not forever. Now there must be an info for the user when the phone stops to ring that a call was missed!

# for 1:1 calls 
there should be even no timeout but the phone should ring as long as the other participant tries to call. And after the other participant hung up the notification should switch to a lower importance and set the text "you missed a call in ....".

# for group calls:
if the group call is still ongoing after it was not joined for 1 minute, is suggest to switch to a lower notification importance. Means no sound, and only an icon visible in the status bar. 
But it should still check if it's ongoing from time to time (like a 2-5 minutes interval) to decide if the text says "ongoing call in group ...." or "you missed a call in ...."

the phone should only continue to ring if the user never joined on any device.
What should happen if he joined on an other device? No notification at all..?

**Comment by mahibi** [comment]
@Ivansss is the issue description like it works on iOS or are there differences?

**Comment by Ivansss** [comment]
On iOS the phone rings for 45 secs for any type of call.
During that time it checks if the user has joined the call from another device.
After the 45 secs it shows a "missed call" notification.
