### ISSUE TITLE
Recover from deleted push notification hash on NC server or push token on FCM

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1740]
On each start of the app and roughly once every 24h the app should try to "heal" the push registration to make sure it recovers when FCM lost the token or the Nextcloud server did.

Similar to https://github.com/nextcloud/talk-ios/issues/691

**Comment by szaimen** [comment]
@nickvergessen I wonder is that also already implemented in the nextcloud files android app? Maybe there could be some code borrowed then :)

**Comment by nickvergessen** [comment]
It might do that already. But the Talk apps register too. So it's just a matter of invoking it again on start up and ~every 24h

**Comment by szaimen** [comment]
cc @AlvaroBrey and @tobiasKaminsky on that 

>  I wonder is that also already implemented in the nextcloud files android app? Maybe there could be some code borrowed then :)

**Comment by tobiasKaminsky** [comment]
https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessagingService#public-void-onnewtoken-string-token

We listen on this and (re-)generate push connection.
If there is no token, app will also retry.

So above topic is not yet handled by us.
Push code is ~99% the same, so it will be easy to adopt it in Files.

@marcel @timkrueger If you need any help with this, just ping me here :)

**Comment by mahibi** [comment]
@tobiasKaminsky as far as i see this is already done in android talk on each start.
see https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt#L168

@nickvergessen it always registers at the pushproxy, no matter if nextcloud servers response is 200 or 201. but that's also fine, right?
see https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/utils/PushUtils.java#L287

so only to implement to register once every 24h i guess..

**Comment by nickvergessen** [comment]
> it always registers at the pushproxy, no matter if nextcloud servers response is 200 or 201. but that's also fine, right?

yes

**Comment by tobiasKaminsky** [comment]
In PushUtils:pushRegistrationToServer() it is checked if there is a push token.
If there is one, it will just do nothing.

So if situation is like this
- app install
- token registration
- token on server is removed (due to inactivity, other reason)
- app starts
- app checks if token is present --> does nothing

So there is no actual check if stored token is still valid.

**Comment by mahibi** [comment]
> In PushUtils:pushRegistrationToServer() it is checked if there is a push token. 
> If there is one, it will just do nothing.

no, if there is one, it will just do the registration:
https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/utils/PushUtils.java#L228

and whenever there is a new token received in onNewToken then it's saved in the appPreferences and registration is renewed:
https://github.com/nextcloud/talk-android/blob/master/app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt#L132

> So there is no actual check if stored token is still valid

well, it can't be checked? all we can do is updating the token on nextcloud&pushproxy whenever we receive a new one in onNewToken? and additionally register the existing one again when app starts (or maybe every 24h)? and this is what is already done...?

**Comment by tobiasKaminsky** [comment]
Right, I overlooked the "!".



> and additionally register the existing one again when app starts (or maybe every 24h)? and this is what is already done...?

What is if you have an invalid token and register it again? This then should be caught and a new toke requested, if this is possible.
Other than that you are right, it seems to be enough/already working as needed.

**Comment by mahibi** [comment]
nextcloud files app uses com.google.firebase:firebase-messaging:20.1.3
nextcloud talk app uses com.google.firebase:firebase-messaging:20.1.2

current version is com.google.firebase:firebase-messaging:23.0.0

So there are quite some todo's i guess..
first insight: we should make use of "getToken"
https://firebase.google.com/docs/cloud-messaging/manage-tokens?hl=en
https://firebase.google.com/docs/cloud-messaging/android/client#java

**Comment by nickvergessen** [comment]
@tobiasKaminsky files app also seems affected ref https://github.com/nextcloud/notifications/issues/1131
Maybe you can create issues for ios and android files too?

**Comment by mahibi** [comment]
@nickvergessen google recommends 1 month to check for push token. 
https://firebase.google.com/docs/cloud-messaging/manage-tokens?hl=en#update-tokens-on-a-regular-basis

you suggest every start and 24h. i can do that. but just wanted to let you know googles recommendation...

**Comment by nickvergessen** [comment]
I mean we should check it daily against the nextcloud and when the return code is 201 there we update at google?
Thats what we siad last time?

**Comment by mahibi** [comment]
well the situation is like this:

on app startup, the current known token is registered at NC server. No matter what the answer from NC server is, it's also registered at PROXY.
https://github.com/nextcloud/talk-android/issues/1740#issuecomment-1011437629

This was always the case.

Nowadays it's possible to get the current token from FCM also by "getToken" command (additionally to receive it by onNewToken). 
https://firebase.google.com/docs/cloud-messaging/android/client#retrieve-the-current-registration-token
In most cases it remains the same, but when done, we are really sure it's up to date and valid.
Google recommends to check the token every month.
After every token-check at FCM, it's updated at NC server and proxy.
I implemented a PeriodicWorkRequest to do that periodically. The question was if i set the interval to 1 month as google suggests or if we want to check it more often.

Additionally, i could create another PeriodicWorkRequest to register the local known token at NC server and proxy.
So for example there could be the PeriodicWorkRequest to check the token at google every month.
And there could be another PeriodicWorkRequest to register the current local known token every day.

so:
1) how often should i check at FCM for the current token?
2) should i create another PeriodicWorkRequest to register the local known token at NC server and proxy? If yes, i set it to every 24h?

**Comment by nickvergessen** [comment]
> how often should i check at FCM for the current token?

Their service their rules? So 1 a month is fine. The problems we have is not when google doesn't know the token anymore, but when a wrong error handling somewhere dropped it on out side, so:

> should i create another PeriodicWorkRequest to register the local known token at NC server and proxy? If yes, i set it to every 24h?

Yes I would do that and that is also what was meant all the time with this issue
