### ISSUE TITLE
error message during installation

### ISSUE THREAD

**Issue by fredjoz** [nextcloud/talk-android#1748]
## Steps to reproduce
1.connect to a store (f-droid for me)
2.download and install app (version 13)
3.during setiings when I have to give the server address ;

message :
"Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or....

Many thanks for your help!

## Device information

**Device:** Fairphone3 and others. I tried with 4 differents smartphones

**Android version:** 10

**Talk version (app):** 13.0.0

## Server information

**Nextcloud version:** 22.2.3

**Talk version (server):** 12.2.2

**Custom Signaling server configured:** no 

**Custom TURN server configured:** no 

**Custom STUN server configured:** no

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by AndyScherzinger** [comment]
This sounds a lot like a misconfigured server regarding the webservier itseld. since the "<" points to a HTML response from the server while the client expects a JSON payload.

**Comment by fredjoz** [comment]
Thank you for your answer.
Do you think it could come from the SSO authentification wich is provided by yunohost?
Thanks for your help,

**Comment by AndyScherzinger** [comment]
Hi @fredjoz,
hard to tell I/we don't know their setup but could be a possibility, yes. While then it would impact all of their users.

**Comment by fredjoz** [comment]
Hi @AndyScherzinger ,
Yes, it's exact. It impact all users.
Thank you for your help, I'm going to ask my question to Yunohost/Nextcloud devs.

have a merry Christmas and a happy New Year!

**Comment by AndyScherzinger** [comment]
Merry Christmas and a happy New Year to you too @fredjoz 🎄
