### ISSUE TITLE
sent message doesn't show up in new conversation/room

### ISSUE THREAD

**Issue by violoncelloch** [nextcloud/talk-android#175]
In a newly created conversation/room or a room without a message sent, after sending messages I have to go back to conversations and open the room again to make the message appear. After that messages show up immediately after sending.

talk-android: v1.2.0beta1
spreed: 3.2.1
nextcloud: 13.0.2

**Comment by mario** [comment]
Please try beta2

**Comment by violoncelloch** [comment]
waiting for it to be downloadable via f-droid...

**Comment by mario** [comment]
Yes, it should. Just poked responsible people for F-Droid :)

**Comment by mario** [comment]
I'll close the issue now, and let me know if it doesn't work in beta2! :)

**Comment by violoncelloch** [comment]
Thank you!

**Comment by violoncelloch** [comment]
Still waiting for beta2 while beta3 has already been released... is there a way to speed up f-droid publishing?

**Comment by mario** [comment]
Nop, patience is all you need :)
