### ISSUE TITLE
useless call tone when starting video call in empty room

### ISSUE THREAD

**Issue by himpierre** [nextcloud/talk-android#1750]
## Steps to reproduce
1. Enter a room with noone in it at this time 
2. Start Video / Audio Call
3. useless Ringtone sounds

### Expected behaviour
Silence in this case.

### Actual behaviour
Well, I just started the call and maybe I like to invite someone to it but for now I am the only person in this video call. There is no need to playback the german "freizeichen" to me as if I would call someone.

## Device information

**Android version:** 11

**Talk version:** 13

## Server information

**Nextcloud version:** 23

**Talk version:** 13

cheers, t.

**Comment by mahibi** [comment]
i understand the idea :+1: 
but because:
- this is quite an edge case
- spreed behaves the same way in web
- to keep things simple
i would like to close this issue as "won't develop". If more people have this requirement it might be reopened.
