### ISSUE TITLE
Translations not syncing anymore

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1754]
Regression from https://github.com/nextcloud/talk-android/pull/1728

Problem is the some keys have different values:

* stable-13.0 https://github.com/nextcloud/talk-android/blob/cb0f20d4593725f5352a7a4c8a644db64c1bd38b/app/src/main/res/values/strings.xml#L230
* master https://github.com/nextcloud/talk-android/blob/09879ff3470c3fa1daa2e2eb60d10999c9bd2825/app/src/main/res/values/strings.xml#L231

---

* stable-13.0 https://github.com/nextcloud/talk-android/blob/cb0f20d4593725f5352a7a4c8a644db64c1bd38b/app/src/main/res/values/strings.xml#L231
* master https://github.com/nextcloud/talk-android/blob/09879ff3470c3fa1daa2e2eb60d10999c9bd2825/app/src/main/res/values/strings.xml#L232

**Comment by nickvergessen** [comment]
Get bonus points to create a CI check for that

**Comment by starypatyk** [comment]
Ups... These are my changes :worried:

@nickvergessen A question for the future - in a scenario like this should I change the key of the string?

**Comment by nickvergessen** [comment]
Yeah makes sense when it's not only fixing a typo

**Comment by nickvergessen** [comment]
Now `nc_notification_channel_calls_description` is conflicting

**Comment by nickvergessen** [comment]
But locally it's not happening anymore. So not sure. Maybe the tool can not switch branches anymore or is stuck with the old code because of a merge conflict?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/talk-android/commit/69518cbe0f942fa1c1b49f26dc4e65395c4e2371 Working again.

https://github.com/nextcloud/talk-android/commit/8305823384c37850bd3bf74ef716eafa357b4543
https://github.com/nextcloud/talk-android/commit/d2da295783890a5c8ca2f4d2748246c898642836

Also we fixed the email setup so I will now get emails when syncing fails
