### ISSUE TITLE
joining via link only opens a call, should be possible to chat as well

### ISSUE THREAD

**Issue by violoncelloch** [nextcloud/talk-android#176]
talk-android: 1.2.0beta1

it could open the chat view as standard and allowing to join the call via the icon at the top right?

maybe a conversation joined via link could even be kept in conversations view? probably marked as such?

**Comment by mario** [comment]
This is fixed in beta2. As for conversations staying there - they'll stay if you join a public room on the same server, but not if you're a guest.

**Comment by violoncelloch** [comment]
sorry for reporting a duplicate then... wil wait for beta2
I think it would be nice if chats would stay inside talk-android for servers I'm a guest too... would this be possible?

**Comment by mario** [comment]
@violoncelloch try filling a bug here - https://github.com/nextcloud/spreed :)
