### ISSUE TITLE
Where is the chat?

### ISSUE THREAD

**Issue by alex9099** [nextcloud/talk-android#177]
Hi, where is the chat? 

if click on some contact it goes directly to the video call

**Comment by mario** [comment]
You need Talk 3.2.x installed on the server in order to have chat + Nextcloud Talk for Android v1.2.0beta(1,2,3).

**Comment by alex9099** [comment]
hmm, i was using the recomended from F-droid(1.1.3) :) the 1.2.0 version from F-droid seems to work fine, thanks ;)
