### ISSUE TITLE
fix "mark as unread"

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#1770]
follow up of https://github.com/nextcloud/talk-android/pull/1752 and https://github.com/nextcloud/talk-android/pull/1767

the "mark as unread" feature for messages is currently not ready for production, so it's only available in debug mode (see https://github.com/nextcloud/talk-android/pull/1767)

### Actual behaviour
https://github.com/nextcloud/talk-android/pull/1752#issuecomment-1004218030

**Comment by AndyScherzinger** [comment]
merged for 16.0.0 as-is
