### ISSUE TITLE
 Reactions to chat messages

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1772]
After being able to reply, replying with a reaction emoji is the next step.
An API is currently developed in https://github.com/nextcloud/spreed/issues/1920
Once done the mobile clients and web UI should show the summary on messages and allow reacting as well.

**Comment by mahibi** [comment]
can someone post some screenshots or mockups of what was finally decided for the mobile designs? @nickvergessen @AndyScherzinger @Ivansss

**Comment by AndyScherzinger** [comment]
design discussed in-person at the company week

**Comment by AndyScherzinger** [comment]
screenshots of competitors to show case some directions where are going for:

|Reactions on message (teams)|Reactions listing on bottom sheet (teams)|Reactions listing on bottom sheet (fb messenger)|Reactions listing on bottom sheet (signal)|React to message (Signal)|
|---|---|---|---|---|
|![device-2022-04-05-140950](https://user-images.githubusercontent.com/1315170/161752316-633a5e25-8e7d-43e7-86f2-945cb84853df.png)|![device-2022-04-05-140959](https://user-images.githubusercontent.com/1315170/161752364-a5f11532-3118-4e78-8bf6-ac27306d8824.png)|<img width="540" alt="device-2022-04-05-141027" src="https://user-images.githubusercontent.com/1315170/161752400-a51f4c93-0c61-4771-842b-5015158a96ec.png">|<img width="540" alt="device-2022-04-05-141045" src="https://user-images.githubusercontent.com/1315170/161752430-9a956ed7-c559-4dd3-8b5f-c8c98e591305.png">|<img width="540" alt="device-2022-04-05-141106" src="https://user-images.githubusercontent.com/1315170/161752452-235a9d86-c43b-4824-a95b-6a97d1708bfa.png">|

Some notes to this:
* Reactions listing
  *  Sort by emoji, display-name, timestamp, actor-id
  * reactions the user added to a message are highlighted (teams: underlined; signal: circular background): Needs to be discussed/aligned
  * add a filter all/per-used-emoji to the list (see messenger and signal): Design to be discussed (messenger: chip-style; signal: viewpager-tab style)
* Limit the amount of shown reaction on a message to 4 + ellipsising ("..." icon at the end)
