### ISSUE TITLE
 Disable Google Analytics introduced by Firebase

### ISSUE THREAD

**Issue by alexara** [nextcloud/talk-android#178]
Since you have introduced Firebase, you might need to explicitly disable Google Analytics:

> Google Analytics for Firebase helps you understand how people use your iOS or Android app. The SDK automatically captures a number of events and user properties (...)

Source: https://firebase.google.com/docs/analytics/

> **Permanently deactivate collection**
> 
> If you need to deactivate Analytics collection permanently in a version of your app, set firebase_analytics_collection_deactivated to true in your app's AndroidManifest.xml in the application tag. For example:
> 
> `<meta-data android:name="firebase_analytics_collection_deactivated" android:value="true" />`
> 
> **Disable Advertising ID collection**
> 
> If you wish to disable collection of the Advertising ID in your Android app, you can set the value of google_analytics_adid_collection_enabled to false in your app's AndroidManifest.xml in the application tag. For example:
> 
>` <meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />`
> 

Source: https://firebase.google.com/support/guides/disable-analytics

See also https://stackoverflow.com/questions/39327141/disable-the-analytics-service-for-firebase-cloud-messaging

**Comment by mario** [comment]
Only Firebase messaging is compiled with the app, not analytics :)

**Comment by mario** [comment]
Well, but like the line says, we don't include firebase-core, in fact, we even remove it from all dependencies if any of them ship it.

**Comment by mario** [comment]
I have checked our Firebase, and we indeed have absolutely 0 (zero!) information even on users who opened the app. I'll add the tag regardless.

**Comment by jospoortvliet** [comment]
Mentioning https://github.com/nextcloud/android/issues/2657 to connect the two issues. People regularly ask about this..

**Comment by alexara** [comment]
Just a note @mario : Currently https://reports.exodus-privacy.eu.org/en/reports/58849/ finds one tracker, by name Google Firebase Analytics, though it is disabled as we know.

However, if you like to remove the warning at Exodus and to go sure that the the library doesn't ignore the parameter from the manifest, you can also remove the appropriate classes, as Conversations has been doing it for quiet some time: 
https://github.com/siacs/Conversations/commit/c2067e3b56364317bc384b55e320b72326fb1de6

Regards

**Comment by mario** [comment]
Ah so they changed the way Firebase is bundled. Let me fix this - thanks @alexara :)

**Comment by mario** [comment]
https://github.com/nextcloud/talk-android/commit/24626ba2dda4f1f6e617aa2ae2ebbcf9ce5b7e6c cc @alexara :)
