### ISSUE TITLE
👥 Implement participant permissions

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1783]
Since Talk 13 permissions exist.
Ref https://nextcloud-talk.readthedocs.io/en/latest/participant/#set-permissions-for-an-attendee

When a user does not have a permission:
https://nextcloud-talk.readthedocs.io/en/latest/constants/#attendee-permissions
the respective action should not be offered or appear disabled.

**Comment by nickvergessen** [comment]
This is done right @mahibi ?
Or something still open?

**Comment by mahibi** [comment]
i guess some are still not done.. https://github.com/nextcloud/talk-android/issues/2020
