### ISSUE TITLE
FR: Url handler for public chats

### ISSUE THREAD

**Issue by gerroon** [nextcloud/talk-android#179]
Hi

It would be nice if the NC Talk app can become a url handler for public chat urls, without even needing a user account on the server.  For instance if you have some kind of Youtube app installed (like Newpipe), any youtube url can be opened with those apps either through shares, or through browser's url line, generally there would be an addiitonal icon to open the url directly in the corresponding app.

If this is implemented, then any user with the public url can download the Talk app and join the conversation without needing an account, like Newpipe does not need you yo enter any youtube account to watch videos from that site.

I know there is a "join via link " option but to get there one has to have an account on the server. What I am asking is some kind of anonymous mode for this app, some kind of guest mode maybe, so the mobile users can enjoy better performance through this app. I find public talks on the mobile via browser use is just plain painful in many ways. 

To wrap this up

- Handle public chat urls directly via app shares, and via browser integration like Newpipe does for Youtube

- Enable some kind of guest mode so that any non-user (without any  login needs) can use this app to join a public chat on Android.

thanks

**Comment by mario** [comment]
Not possible since url handlers need to be registered in advance and we don't have a single server.

Sorry.
