### ISSUE TITLE
could u make some change in talk app?

### ISSUE THREAD

**Issue by FlyingHarman** [nextcloud/talk-android#1793]
some advices for improving android app 

1. in group-room calling,more users maybe "join" and "leave" frequently,so u can not see "xxx strating a call"  and replaced by "join and leave" show on the screen,and phone icon in the toolbar no changed.but good expierence on webpage, because u can see  "start call" turn into "join call" ,it's more clear instead of guessing or confused.plz consider about this
2. could u make a floating tooltip on screen if u do not want to modify toolbar.I think text of tooltip like "4 users in calling" should be good.
3. could u put timer on the ongoing call screen,even for webpage

why no ringtone or notifycation on iphone/ipad when someone starting a call in group-room? could u fix this?

I'm so appreicate what u have done to Talk and take care what I said

**Comment by jld3103** [comment]
@nickvergessen could you close this one since we don't have any further information and it isn't even clear which client this is about?
