### ISSUE TITLE
Non-Google (GCM/FCM) notifications?

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/talk-android#180]
Hi,
Is there a plan to implement independent notifications that work without the Google framework?
It would be great to have some (worst case poll-based) notifications on the F-Droid version too.
For example Riot.IM has them as fallback in case Google push does not work and work really well and are also customizable (the time between polls).

**Comment by mario** [comment]
No plans. There's been a LOOOONG discussion about this in one of the previous F-Droid issues. Polling wouldn't work on newer Android versions, and even if it did, it would consume significant battery resources.

**Comment by gradinaruvasile** [comment]
In this case you should update the F Droid description to make sure people know this. Right now notifications are part of the feature list. Also it should be pointed out clearly that this version does not implement notifications at all which in a messenger app should be a requirement.

BTW on Android 8.1 Riot and other apps like Telegram and Conversations seem to work just fine with their own notification framework. I even set Riot polling to 20 seconds and does not seem to eat that much battery (the battery estimates are mostly the same and i dont have to charge the phone more frequently).

**Comment by mario** [comment]
I'll happily entertain reviewing & merging such functionality if you think you can do it properly. 

Remember it needs modification to the mobile apps, Nextcloud, and a separate push service binary.
