### ISSUE TITLE
No ringing sound after first call

### ISSUE THREAD

**Issue by miniskipper** [nextcloud/talk-android#182]
I have removed the fdroid-version and installed the play store version of the app (v 1.2.0b3) so that the phone rings on an incoming call.
But this only works for the first call. As soon as there is a successful connection, there is no ringing anymore.
When deleting the conversation from the list and starting a new call, the device rings again. But again only 1 time  :/

Doesnt matter if the clients are in LAN or WAN.

Also the sound is only played once - bad if you have a short ringtone.

**Comment by mario** [comment]
Yup, aware of this. I'll work on better ringtone support in one of the follow-up versions.
