### ISSUE TITLE
Improve audio quality in voice message.

### ISSUE THREAD

**Issue by Akrobs** [nextcloud/talk-android#1835]
Audio quality is very bad! Bitrate 12Kb/s is very low for voice!!! And Sample rate 8KHz low to!!!!

Please do a 32KHz sample rate and 48Kb/s bitrate. Then audio will be good.

Thanks.

**Comment by jakobroehrl** [comment]
duplicate? 
#1613

**Comment by Akrobs** [comment]
> duplicate? #1613

Yep. Sorry.
