### ISSUE TITLE
Clicking on notification (when mentioned) does not lead me to the correct room

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/talk-android#184]
When a user mentions me in a chat and I am in another room already, and I click the notification, the app does not redirect me to the correct chat room, but instead leaves me in the room/chat list.

This bug only happens if I am already somewhere in another room/chat.

The bug does not happen if I am either in the chat/group list or if the app is entirely closed.

v2.0.0

**Comment by mario** [comment]
Should be fixed in 2.0.1beta1.
