### ISSUE TITLE
Sticky notification after calls have already ended

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/talk-android#1842]
## Steps to reproduce
1. Have an incoming 1-on-1 call
2. Join the call on a different device

### Expected behaviour
The notification about the incoming call should be dismissed, or it should be possible to dismiss it manually.

### Actual behaviour
- The notification cannot be dismissed (swiped away)
- The notification opens a call screen on tapping, even though the call has already ended
- Only after ending the call that is no longer running anyways, the notification goes away.

## Device information

**Device:** Pixel 3A

**Android version:** 12

**Talk version:** 13.1.0 Alpha 14

## Server information

**Nextcloud version:** 23.0.2

**Talk version:** likely latest on c.nc.com

**Custom Signaling server configured:** yes
**Custom TURN server configured:** yes
**Custom STUN server configured:** yes

**Comment by juliushaertl** [comment]
Still an issue with the latest release ;)

**Comment by mahibi** [comment]
thanks julius.
i can not reproduce this for now.
the notification should be dismissed once an other device joins or the call ended, which works perfectly fine for me.

can you reproduce this, @timkrueger ?

**Comment by juliushaertl** [comment]
Maybe it helps for how I usually join the call. I tend to dismiss the call notification of the desktop client (since I use a different browser for calls than my default one). Then I join the call manually in the browser (without interacting with the notification in there).

**Comment by juliushaertl** [comment]
I can try next time if that makes a difference when joining directly without dismissing the desktop notification.

**Comment by juliushaertl** [comment]
Two scenarios where id didn't happen today:
- Let the phone ring, let the desktop client ring, join in the browser
- Let the phone ring, dismiss the desktop client ring, join in the browser

Will run some more tests with declining the call on the phone next.

**Comment by juliushaertl** [comment]
Seems to happen when I dismiss the phone ring with the power button, but only on some calls. 

Today there were two calls that kept a sticky notification. One I joined a few minutes later and another one I didn't join at all.

**Comment by mahibi** [comment]
is this still an issue @juliushaertl ?

**Comment by juliushaertl** [comment]
Can't tell since i switched to iOS, but if there is no further report, let's close this. In case this becomes an issue again I can reopen ;)
