### ISSUE TITLE
Autocompletion/mentioning not working properly because no space added after the name

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/talk-android#185]
Autocompletion/mentioning not working properly because no space added after the name: when I start typing a username and then click the suggested user when it comes up via autocompletion recommendation, the app seems to append a space behind the name when in fact it doesn't. Because once I type the next letter, it gets appended right after the name, no space in between. It seems as if typing the next letter would for some reason remove the space that seems to exist after the name.

So the autocompletion/mentioning only works if I manually type a space after tapping the user, which is not convenient.

See screencast: https://cloud.nextcloud.com/s/QszFtYfoDsP5gy5 
Hope it makes it clear what I mean.

Possible that it's only a specific behaviour of my phone. 

App version 2.0.0
Huawei Mate 8

**Comment by mario** [comment]
So I looked into the screencast. It looks like your PHONE autocompletion is misbehaving here. If you look closely, you'll see that "ivan" continues to be underlined as you type and autocorrected to what it thinks it should be.

Afaik, the only solution would be to disable autocompletion on a field which I don't think is a good idea.

Let me know your thoughts!
