### ISSUE TITLE
black screen or single videoframe for audicalls (instead of avatar)

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#1852]
## Steps to reproduce
1. start audiocall from web
2. accept call on phone

### Expected behaviour
avatar is shown

### Actual behaviour
audio connection is okay but
either there is a black frame or a single videoframe from calling participant!

![grafik](https://user-images.githubusercontent.com/2932790/156815602-7b1865e4-17d4-4896-a7a0-70642bb6e5d4.png)

this must be caused by the webRTC lib update https://github.com/nextcloud/talk-android/pull/1774 because:
it works with commit 3af4f368
it fails with commit 89f64b39

## Device information

**Device:** Redmi Note 9 Pro

**Android version:** 10

**Talk version:** test with commit 89f64b39

## Server information

**Nextcloud version:** 24.0.0.4 (Sermo)

**Comment by timkrueger** [comment]
I was able to narrow it a bit more.

Works: bad5b5f9
Works not: 86f20dcf

### Step 1 

The `MagicPeerConnectionWrapper` get passed the `remoteMediaStream` and it's containing a video and a audio stream. For both commits `remoteMediaStream#toString` is `[janus:A=1:V=1]`.

https://github.com/nextcloud/talk-android/blob/bad5b5f9bccae7f88eb533cf900094956487849f/app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java#L407

### Step 2

The code at this point didn't change between the two commits. The `remoteMediaStream` is neither accessed or wrote again. But the `remoteMediaStream#toString` is different for both commits:
- bad5b5f9 `[janus:A=1:V=0]`.
- 86f20dcf `[janus:A=1:V=1]`

https://github.com/nextcloud/talk-android/blob/bad5b5f9bccae7f88eb533cf900094956487849f/app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java#L359


The private variable `remoteMediaStream` is only accessed at this two points. I don't have any clue at which point the video stream is removed in the working commit bad5b5f9.

**Comment by timkrueger** [comment]
[Migrating your native/mobile application to Unified Plan/WebRTC 1](https://docs.google.com/document/d/1PPHWV6108znP1tk_rkCnyagH9FK205hHeE9k5mhUzOg/edit#)
