### ISSUE TITLE
phone keeps ringing while call connection is established, when hangup call notification screen is shown

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#1853]
## Steps to reproduce
1. start a call from web
2. accept call on phone
3. error1: while being in the call on phone, it keeps ringing while connection is established
4. hangup on phone
5. error2: call notification screen pops up 
6. accept call -> goto 3.

### Expected behaviour
accept call stops the ringtone
after hangup, call notification screen doesn't pop up

## Device information

**Device:** RedmiNote 9 pro
**Android version:** 10
**Talk version:** 24.0.0.4 (Sermo)

## Notes
this behaviour is introduced somewhere between commit 3f6ef9ae (works) and commit ffbe39bd (fails)
this kept me away from releasing 13.1.0 beta today. 

FYI @nickvergessen @AndyScherzinger @timkrueger :
i'm on vacation on monday & tuesday.
if you take over here @timkrueger ... happy git bisect ;)

**Comment by timkrueger** [comment]
I can reproduce the same behavior with both mentioned commits. But a different one then described.

`error1` does not occurs in my test. But `error2` happens on both commits. And it happens only when the call is joined via the lock screen or notification. If the call is joined directly in the conversation `error2` is also not happening.

@mahibi I think we should compare our results tomorrow when you're back.

**Comment by mahibi** [comment]
this was caused with commit [d453773a](https://github.com/nextcloud/talk-android/commit/d453773a1df31065ec38d5b7ae378e2776ab045e) 
It's not allowed to pass null for a query map

**Comment by andyxheli** [comment]
Hey @mahibi sorry to bother you. I got a call on talk and i did answer the phone keep rining even if the other user left the call so i had to open the android talk app and then it stopped. I didn't want to create a new ticket since I seen this issue and want to consult you.

**Comment by mahibi** [comment]
which version was this, @andyxheli ?
can you reproduce it?

**Comment by andyxheli** [comment]
@mahibi So far on v14.2.0 i have not been able to reproduce the issue.

**Comment by mahibi** [comment]
okay good to know, feel free to reopen if this occurs again
