### ISSUE TITLE
No text input in chat when in portrait mode

### ISSUE THREAD

**Issue by moonwolf-github** [nextcloud/talk-android#186]
On Galaxy S8+ there's no text input field when phone is in portrait mode and you can't post any message.

![screenshot_20180606-130424_nextcloud talk](https://user-images.githubusercontent.com/10871358/41035019-b11ee098-698b-11e8-952a-6605509dd94b.jpg)

In landscape mode all works as expected.

![screenshot_20180606-130440_nextcloud talk](https://user-images.githubusercontent.com/10871358/41035027-b5d7bbfa-698b-11e8-81a0-c9987265fd64.jpg)

**Comment by mario** [comment]
Thanks for the report. I'll investigate.

**Comment by mario** [comment]
Unfortunately I don't have the phone specified but I tried Android 8 + same resolution and it works.

However. I do have one idea, so once 2.0.1 beta is out I'll ask you to test!

**Comment by moonwolf-github** [comment]
Sure!

**Comment by mario** [comment]
@moonwolf-github one thing. Could you try writing bunch of messages when in landscape (enough to fill the screen) and then rotate the phone to see if input field appears?

**Comment by moonwolf-github** [comment]
Looks like it doesn't:

![screenshot_20180606-205446_nextcloud talk](https://user-images.githubusercontent.com/10871358/41059178-1dc377aa-69cc-11e8-8b5d-fc6e614ae417.jpg)

**Comment by mario** [comment]
Strange. But you can still scroll, right?

**Comment by moonwolf-github** [comment]
Yes, i can.

**Comment by mario** [comment]
Ok, thanks. Please take a look at 2.0.1beta1 once its released (aka in half an hour or so).

https://play.google.com/apps/testing/com.nextcloud.talk2

**Comment by moonwolf-github** [comment]
Unfortunately it doesn't work.

**Comment by moonwolf-github** [comment]
Layout looks OK in my Android Studio. Here's layout boundaries from phone, maybe this will help?
![screenshot_20180606-214840_nextcloud talk](https://user-images.githubusercontent.com/10871358/41061710-ce27fe70-69d3-11e8-99f5-8c0b9fe09f1e.jpg)

**Comment by mario** [comment]
Hm. Do you think we could do a TeamViewer (or something) session so I can test this out?

**Comment by mario** [comment]
I'm basically interested to see if messageInput in ChatController is null and why.

**Comment by mario** [comment]
If you could set ButterKnife.setDebug(true) and send me the logs, that would be awesome!

**Comment by mario** [comment]
(Also just released 2.0.1beta2 in a strange attempt to fix it)

**Comment by moonwolf-github** [comment]
Still no joy :(
I'll get my hands on another S8+ and S5 today so i'll give this a try. But unfortunately before weekend i won't have time to dig into it further.

**Comment by mario** [comment]
@moonwolf-github this is with full screen on, right?

**Comment by moonwolf-github** [comment]
Yes.

**Comment by moonwolf-github** [comment]
Oh. With navigation bar it works!

**Comment by mario** [comment]
:)

**Comment by mario** [comment]
I need to find a way to support full screen mode. But it's really hard with no phone :(

**Comment by tobiasKaminsky** [comment]
> @moonwolf-github one thing. Could you try writing bunch of messages when in landscape (enough to fill the screen) and then rotate the phone to see if input field appears?

This is working for me, if I enter at least 5 lines in landscape mode.


Adding "minHeight:100dp" to the input field leads to this
(with fullscreen):
![image](https://user-images.githubusercontent.com/5836855/41256621-72dda286-6dca-11e8-9148-9d2db82d9d97.png)


(without fullscreen):
![image](https://user-images.githubusercontent.com/5836855/41256683-a2406270-6dca-11e8-8fb9-25e145db881b.png)


--> So for some reason the chat input field is not recognized as "keep", but rather is collapsed.

A regular TextInputField is also affected.
Currently my only "fix" is to set a minHeight

**Comment by mario** [comment]
Thanks @tobiasKaminsky. Did you try to maybe set messagesListView height to wrap_content? Maybe for some strange reasons it pushes edit text down since it's         android:layout_alignParentBottom="true"?

**Comment by tobiasKaminsky** [comment]
> Did you try to maybe set messagesListView height to wrap_content? Maybe for some strange reasons it pushes edit text down since it's android:layout_alignParentBottom="true"?

Does not help.

I even tried to just use a simple LinearLayout, with fixed height for input field and messagesListView taking the rest of the screen, but even then the input field vanishes.
When having LinearLayout, immediately after entering a conversation I can see the InputField, but as soon as the chat content is loaded it disappears.

After playing a long time with it, only setting height to 100dp is working, but this is also not a real solution :/

**Comment by mario** [comment]
@tobiasKaminsky but even with 100dp, the field doesn't seem completely visible? Did you try hiding action bar maybe?

**Comment by tobiasKaminsky** [comment]
100dp was just a value to show that it is then showing the input field. 

> Did you try hiding action bar maybe?

As far as I know, we cannot know if an app is in fullscreen, or not.
So hiding the action bar then would be permanent.
I can try this, but showing no action bar is not wanted, I guess?

**Comment by tobiasKaminsky** [comment]
Just for recording what I tried without success:
- https://stackoverflow.com/questions/43694526/samsung-galaxy-s8-full-screen-mode
- hiding action bar

**Comment by mario** [comment]
Because we cannot fix this atm, unassigned milestone :(

**Comment by moonwolf-github** [comment]
I was struggling with layout for some time with no success but it really looks like a bug - i tried this:
```diff
--- a/app/src/main/java/com/nextcloud/talk/activities/MainActivity.java
+++ b/app/src/main/java/com/nextcloud/talk/activities/MainActivity.java
@@ -27,6 +27,7 @@ import android.support.annotation.Nullable;
 import android.support.v7.app.AppCompatActivity;
 import android.support.v7.widget.Toolbar;
 import android.util.Log;
+import android.view.View;
 import android.view.ViewGroup;
 import android.webkit.SslErrorHandler;
 
@@ -86,6 +87,12 @@ public final class MainActivity extends AppCompatActivity implements ActionBarPr
 
     private Router router;
 
+    private static int getSystemUiVisibility() {
+        int flags = View.SYSTEM_UI_FLAG_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_FULLSCREEN;
+        flags |= View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY;
+        return flags;
+    }
+
     @Override
     protected void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
@@ -97,6 +104,8 @@ public final class MainActivity extends AppCompatActivity implements ActionBarPr
 
         setSupportActionBar(toolbar);
 
+        getWindow().getDecorView().setSystemUiVisibility(getSystemUiVisibility());
+
         router = Conductor.attachRouter(this, container, savedInstanceState);
 
         boolean hasDb = true;
```

and this is result:

![screenshot_20180613-211621_nextcloud talk](https://user-images.githubusercontent.com/10871358/41373183-d98c0b7c-6f4f-11e8-8105-c8fcc5c7f416.jpg)

Notice message hides behind `separator` and `nc_message_input` is still missing. Looks like something hard to pinpoint and fix :(

**Comment by mario** [comment]
@moonwolf-github could you compile current master and tell me if it works?

**Comment by tobiasKaminsky** [comment]
@mario I tried it with todays master, but it is still the same…

**Comment by mario** [comment]
@tobiasKaminsky master from now. Please try :) same for @moonwolf-github

**Comment by moonwolf-github** [comment]
Sorry, but no joy :(

**Comment by mario** [comment]
Can you check @moonwolf-github ? The input view should now be visible though there are other issues now which I'm trying to resolve.

**Comment by moonwolf-github** [comment]
Sorry, but i checked yeasterday and there was no difference :(

**Comment by mario** [comment]
@moonwolf-github but I just pushed new code!

**Comment by moonwolf-github** [comment]
Oh :) Looks like i don't see it yet :)

**Comment by mario** [comment]
@moonwolf-github just pushed new code which should completely fix it. Please test both full screen and without full screen.

**Comment by moonwolf-github** [comment]
@mario I still don't see any updates in Google Play Stor :(

**Comment by mario** [comment]
@moonwolf-github you need to compile the app from the repository!

**Comment by mario** [comment]
@moonwolf-github beta4 is out, so let me know when you get it!

**Comment by tobiasKaminsky** [comment]
It is working :+1: :+1:

**Comment by mario** [comment]
Well, yay @tobiasKaminsky! Thanks for testing!

**Comment by moonwolf-github** [comment]
Confirm. I finally got update and it's working!
