### ISSUE TITLE
Responding audio-only calls opens up front cam video

### ISSUE THREAD

**Issue by godfuture** [nextcloud/talk-android#187]
When I get an audio call and respond to it, my front cam is opened automatically. I did not expect my video to start for audio calls.

NC server: 13.0.2
Talk server: 3.2.2
Talk Android: 2.0

**Comment by mario** [comment]
That's because we don't know what type of call is it before we answer it. In one of the future versions you'll be able to answer either audio-only or video (different buttons).

Sorry about the inconvenience.
