### ISSUE TITLE
Conversation loading hangs on message notification tapping while screen is locked 

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/talk-android#1871]
## Steps to reproduce
1. Open Nextcloud Talk.
2. Lock the screen.
3. When getting a new message notification, double tap on it to open the corresponding conversation.

### Expected behaviour
The conversation loads correctly. If before locking the screen Nextcloud Talk is closed, the issue doesn't happen.

### Actual behaviour
The conversation doesn't load correctly, the messages placeholders keep blinking.

## Device information

**Device:** Fairphone3 (/e/ OS, Android 10) and Huawei P8 Lite 2017 (Android 8.0.0)

**Talk version:** 13.0.0

## Server information

**Nextcloud version:** c.nc.com

**Talk version:** don't know

**Custom Signaling server configured:** don't know

**Custom TURN server configured:** don't know

**Custom STUN server configured:** don't know

**Comment by timkrueger** [comment]
Can you please check if this is still the case with the current version 15.0.1?

**Comment by pmarini-nc** [comment]
Just tested on the Huawei device mentioned above and cannot replicate the issue.

**Comment by mahibi** [comment]
was fixed with https://github.com/nextcloud/talk-android/pull/1766
