### ISSUE TITLE
Display does not turn off automatically when covered

### ISSUE THREAD

**Issue by godfuture** [nextcloud/talk-android#188]
When I have started an audio call and put my mobile to ear, the screen does not turn off automatically.

NC server: 13.0.2
Talk server: 3.2.2
Talk Android: 2.0

**Comment by mario** [comment]
It shouldn't really turn off. But the camera should stop being shown. Can you please clarify?

**Comment by godfuture** [comment]
I guess you speak about the video being stopped when the approximation sensor gets covered. I meant the display that should be turned off. This is the usual behaviour for many voice apps.

In the end it would make sense to turn off both display and camera when the approximation sensor is covered.

**Comment by jancborchardt** [comment]
Same here, the display should of course be turned off because otherwise you can accidentally touch the buttons with your face. Also it saves battery cause you don't need to look at the screen while it's on the side of your face.

**Comment by mario** [comment]
This is not a bug. A bug means that something is not working as it should. Since this feature does not exist, this is not a bug.

In addition, technically, you cannot AFAIK turn off the display. You can lower the brightness though which I might do in the future.

**Comment by godfuture** [comment]
Don't know if I should agree here. I guess as long as touch screen inputs are disabled with lower brightness, your point makes sense. But with my current Android phone I still can use the touch screen even brightness was reduced...

**Comment by mario** [comment]
I will investigate once I come to this. So far I'm only aware of PROXIMITY_SCREEN_OFF_WAKE_LOCK and I'm not sure how well that plays with running network calls in the background. But we'll see :)
