### ISSUE TITLE
Delete recorded voice message

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#1880]
## Steps to reproduce

1. Create a conversation with the user.
2. Record a voice message.
3. Tap and hang on the sent voice message.

### Expected behaviour
Ability to delete recorded and sent voice messages.

### Actual behaviour
The sent voice message cannot be deleted.
When you hold your finger on a sent voice message, the voice message editing menu does not appear.

![obraz](https://user-images.githubusercontent.com/47037905/159240617-244320db-184e-4b50-9269-a9a6ecff9e00.png)

**Android version:**
10

**Talk version:** 11.0.0
v13.1.0 Alpha 17

**Comment by mahibi** [comment]
with 14.0.1 the voice message editing menu does appear but still doesn't contain the option to delete. This should be fixed

**Comment by sowjanyakch** [comment]
Voice messages can be deleted using the content menu.
