### ISSUE TITLE
Lobby management is not working

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/talk-android#1887]
## Steps to reproduce
1. Select a Conversation
2. Open Conversation Info
3. Enable the lobby
4. Leave Conversation Info and check if the event is written in the conversation

Please note that the behaviour is similar when disabling the lobby, instead of enabling it.

### Expected behaviour
The lobby status should be updated

### Actual behaviour
The lobby status is not updated

## Device information

**Device:** Fairphone 3
**Android version:** 10
**Talk version:** 13.0.0

## Server information

c.nc.com

### Server log (data/nextcloud.log)

**Comment by mahibi** [comment]
reproduced this with version 14.0.1.

1. Open Conversation Info
2. Enable the lobby
3. got back to conversation
4. Open Conversation Info
5. --> state of lobby is still disabled

**Comment by R7JANV1** [comment]
This problem still exists.
