### ISSUE TITLE
Clicking on "open conversation" crashes

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#1893]
## Steps to reproduce
1. search for a conversation that is open
2. click on "open conversation"
3. (sidenote: in german it is currently called "Unterhaltung öffnen", but it should be "Offene Unterhaltungen"

### Expected behaviour
No crash

### Actual behaviour
Crash 

## Device information

**Device:** Fairphone2/…

**Android version:** 10/…

**Talk version:** 11.0.0

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)

**Talk version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`)

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by AndyScherzinger** [comment]
I fixed the translation just now, so bot fetches it tonight. As for the crash: Doesn't happen to me, just opens the room and loads all messages.
