### ISSUE TITLE
Add "Media tab" to show shared items and files

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1903]
API available since: https://github.com/nextcloud/spreed/pull/7077
Docs: https://nextcloud-talk.readthedocs.io/en/latest/chat/#list-overview-of-items-shared-into-a-chat
Server ticket: https://github.com/nextcloud/spreed/issues/1577

Server frontend as inspiration: https://github.com/nextcloud/spreed/pull/7076

**Comment by timkrueger** [comment]
Development happen here: https://github.com/nextcloud/talk-android/tree/feature/noid/media-overview
