### ISSUE TITLE
some emojis are not shown 

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#1913]
## Steps to reproduce
1. give reactions to chat messages

### Expected behaviour
all emojis are shown

### Actual behaviour
some emojis are shown as
![image](https://user-images.githubusercontent.com/2932790/162592086-d9e7750f-4ad0-49fb-938f-614923cfa873.png)

14.1.0 Alpha 1

**Comment by mahibi** [comment]
this is due to the android version, so nothing we can do.
tested this and can confirm it's these emojis that are not shown when using android <11:

https://blog.emojipedia.org/android-11-0-emoji-changelog/

**Comment by AndyScherzinger** [comment]
@mahibi can you check again, maybe this is fixed with my latest lib update regarding emojis

**Comment by mahibi** [comment]
now the new emojis work on android talk as reactions :+1: 

but they are not shown successfully as message content

**Comment by mahibi** [comment]
see "reactionsTest" conversation on sermo
