### ISSUE TITLE
"Import accounts from the Nextcloud app" is unclear if there are multiple accounts with same username

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#1919]
## Steps to reproduce
1. Create 2 or more accounts which have the same username (e.g. your name) in the Nextcloud Files app
2. Open the Talk app and pick "Import accounts from the Nextcloud app"
3. See your username twice, unable to distinguish which account is which

### Expected behaviour
It should be possible to distinguish the accounts. Ideal would of course be to show a nice list with avatar on the left, display name in main line, and `username at cloud.example.com` in the subline.
As a small step, just showing the server domain after the name would be good.

### Actual behaviour
I see:
> **Select an account**
> - jan
> - jan

## Device information

**Device:** Fairphone 2

**Talk version:** 13.0.0

## Server information

Not relevant

**Comment by AndyScherzinger** [comment]
I fixed this quite a while ago, please update to the alpha or beta channel.

I simply added the server on the second line, hope that is fine too.
