### ISSUE TITLE
Missing notifications completely

### ISSUE THREAD

**Issue by jurgenhaas** [nextcloud/talk-android#192]
Should there be any notification on the mobile app if a new conversation, message, mention or call comes in? I'm asking because I don't get any and I'm using 2 Android devices, one from Samsung and the other from Google.

I'm running Nextcloud 13.0.3 with my own STUN and TURN (coturn) server and chats are generally working, just no notifications.

**Comment by mario** [comment]
You get a notification when a new conversation is opened, you're mentioned or you get a call.

If not, something is wrong.

In general:
a) Do you have Google Play Services?
b) Do you have Notifications app installed on the server?
c) What version of Android?

Cheers,
Mario

**Comment by podkilla** [comment]
Same problem.

a) of course not
b) yes
c) Copperhead OS Android 8.1.0 June Security Patch

**Comment by mario** [comment]
@podkilla your "of course not" means that you will not have notifications, sorry.

**Comment by mario** [comment]
@podkilla btw. having MicroG instead would be a good alternative)

**Comment by jurgenhaas** [comment]
a) yes
b) yes
c) 8.1.0 with June sec update on a pixel 2 and on a Samsung Tab S3

**Comment by mario** [comment]
@jurgenhaas strange. fancy sending a test account to mario AT nextcloud.com and I can test on Monday?

**Comment by podkilla** [comment]
@mario, np, thanks for the clarification.

the notifications of other apps work just fine without any google services. so no need for compromising security and  being wasteful with data by installing not needed software.

**Comment by mario** [comment]
@podkilla what other apps?

**Comment by jurgenhaas** [comment]
@mario sure, let's catch up on Monday then

**Comment by mario** [comment]
@jurgenhaas things to try in the mean time: 

a) settings>battery>battery optimization -> Ignore
b) Find the app somewhere in settings and enable all Notification channels the app created

**Comment by podkilla** [comment]
@mario conversations & mastalab for example

**Comment by mario** [comment]
@podkilla Conversation says this: "You need to be running the Play Store version of Conversations and your server needs to support push notifications.¹ "

**Comment by mario** [comment]
That you need Google Play Services to get push even with Conversations :) Everything else is less reliable.

**Comment by podkilla** [comment]
@mario copperhead os does not have google play services and still i receive notifications.
but i understand that most developers take the "easy way" and just use services that are already there instead of thinking of a way not to rely and share unnecessary data with a third party.

**Comment by mario** [comment]
I had this discussion countless times. It's not the "easy way", it's the "only way" at the moment. There are alternatives like MicroG (but you still use Google in a way then) OR controlling your platform from the bottom up.

To summarize: there is no way to wake up 99,999% devices on the market out there without Google High priority messages.

**Comment by jurgenhaas** [comment]
@mario I have just created an account on a testplatform for you, an email should be sent to you from cloud.tc-gottmadingen.de

Over the weekend I have adjusted the settings on my Android devices (giving them all permissions and disabling power management for Android Talk), but that made no difference.

**Comment by marvicz** [comment]
With Google services installed, I get a notification when someone invites me for the chat. But no notification at new message income when being out of the app.

**Comment by mario** [comment]
@jurgenhaas thanks, will take a look.

@marvicz expected for now. You get call notifications and mention notifications (say "@marvics" inside chat). We'll refine that eventually.

**Comment by jurgenhaas** [comment]
@mario what's interesting though, I had notifications for Nextcloud (not Nextcloud Talk) disabled on my Pixel 2 and since I enabled them there, I do get notifications on the Pixel 2 for mentions and call invitations.

However, on the Samsung devices that still doesn't work. The settings are in different places but I pretty sure I've checked everything and still can't get it to work.

**Comment by mario** [comment]
@jurgenhaas super strange, they are different and Nextcloud app silently ignores Nextcloud Talk notifications. Hm.

I do have Samsung devices so I'll definitely try.

**Comment by mario** [comment]
@jurgenhaas you have a message in the chat!

**Comment by mario** [comment]
Closing at least temporarily since it seems to be a glitch of a particular phone after testing with @jurgenhaas. But we'll re-open if need arises.

**Comment by mjanssens** [comment]
Just my 2 cents. I had similar issue, no notifications in Nextcloud talk. Nextcloud app notifications were working.
After clear cache and clear data in android app settings for Nextcloud Talk and importing account settings again from Nextcloud app (first run) notifications are working again.

**Comment by deusama** [comment]
I do get notifications when I am invited into a video call, but still nothing if a new chat message comes in. Same for the notifications app in the browser. Is this a general limitation right now that comes from the talk app, or can I somehow configure the notification app to get this working?

Thanks,
Amadeus

**Comment by mario** [comment]
You get notifications if you're mentioned (e.g. if someone writes @deusama.) We'll work on general notifications in the future.

**Comment by deusama** [comment]
Ok thanks for clarification :-)

I would have thought that it makes sense to have notifications in group chats (> 2 people) only when I am mentioned, but I would expect to have instant notifications when talking to one person directly. Just my two cents.

**Comment by mario** [comment]
@deusama I know, but step-by-step - this needs changes in the Talk server app.

**Comment by mario** [comment]
@jurgenhaas this should help: https://github.com/nextcloud/notifications/pull/134

**Comment by bisherbas** [comment]
@florentfeougier Nope. Still the same. :(

**Comment by mario** [comment]
@bisherbas did you use 3.1 beta? Same for @florentfeougier :)

**Comment by bisherbas** [comment]
@mario I think you were asking for the Android app version not the server plugin. Android app I have is from the app store. It shows as 3.0.1. I haven't downloaded and installed the 3.1 apk.

**Comment by florentfeougier** [comment]
@mario , I registered to the beta program and installed the 3.1 beta on 2 android devices but it's still not working. I noticed that I do get the notifications from the OSX client in Activity -> Server Activity  however.

**Comment by mario** [comment]
@florentfeougier this is different than push notifications though. Can you send a two test accounts so I can test? mario AT nextcloud.com :)

**Comment by mario** [comment]
@bisherbas if you can do the link @florentfeougier gave you, that would be awesome :)

**Comment by bisherbas** [comment]
@mario Using the latest beta now. Still no notification. When I hold two phones, Android and iPhone, and keep the Talk app open on both phones, and I called the one from other, I see a message at the bottom saying that called initiated. But no system notification on either phone. Whether the Talk app is open or not.

**Comment by florentfeougier** [comment]
Hi @mario, I was going to create the accounts for you to test but I decided to setup a new test server as followed:

Server: Debian9 + latest Nextcloud 14.04 + coturn + Nextcloud app 4.0.1
Android client: updated from 3.0.1 to 3.1.1

it now works perfectly ! 

Thanks for you all your hard work on this great software :)

**Comment by mario** [comment]
@florentfeougier happy to hear this! :)

**Comment by vwbusguy** [comment]
For what it's worth. Notifications work fine on my galaxy s9+ but not my wife's s7. Same app and server version, but if she sends a call or message I get a notification, and no matter what she never gets on. I verified Talk isn't battery optimized and notifications are allowed on hers. Not sure the difference but based on this thread, it might be something with Samsung Galaxy s6 and s7 devices?

**Comment by kadarpik** [comment]
Same here, notificaitons only when chat room created, nothing when message has been added. Chat room notificaiotn level=1, i.e. always notify.
