### ISSUE TITLE
Handshake failed

### ISSUE THREAD

**Issue by FranciscoPombal** [nextcloud/talk-android#193]
When trying to connect to my server, I get this error:
`Handshake failed`

The main Nextcloud app connects and works just fine. Maybe support for the newer TLS cipher suites is lacking?

Here are the ones that my server is using:
ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-CHACHA20-POLY1305

**Comment by mario** [comment]
Hi,

what phone, what Android version, what protocol (SSL and what version or TLS and what version)?

Also F-Droid or Google Play?

Thanks!

**Comment by FranciscoPombal** [comment]
@mario 
Samsung Galaxy S6 (SM-G920F)
Android 7.0 (with latest updates for my phone)
TLS 1.2
Latest app version from F-Droid

**Comment by mario** [comment]
GPlay version automatically updates supported protocols for your phone, F-Droid one does not unfortunately which is an issue.

Keep in mind I disable all SSL protocols by default.

As for ciphers, I try to add these to supported ones (if supported by phone) along with others:

                                "TLS_RSA_WITH_AES_256_GCM_SHA384",
                                "TLS_RSA_WITH_AES_128_GCM_SHA256",
                                "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
                                "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
                                "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
                                "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
                                "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
                                // maximum interoperability
                                "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
                                "SSL_RSA_WITH_3DES_EDE_CBC_SHA",
                                "TLS_RSA_WITH_AES_128_CBC_SHA",
                                // additionally
                                "TLS_RSA_WITH_AES_256_CBC_SHA",
                                "TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA",
                                "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
                                "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA",
                                "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"

**Comment by FranciscoPombal** [comment]
@mario 
I just confirmed that the GPlay version works perfectly with my setup
Can the F-Droid version be fixed? What does it take to fix it?

**Comment by mario** [comment]
@FranciscoPombal sorry but no, since this is related to security provider/operating system updates and while this can be manually updated if you have Google Play Services (which I do on a GPlay variant) it's impossible to do on F-Droid :(
