### ISSUE TITLE
avatars too big

### ISSUE THREAD

**Issue by MariusQuabeck** [nextcloud/talk-android#1931]
see screenshot, I assume this is because of the new avatar resizing feature in 24? this started happening after our 24 RC1 update on c.nc.c 

![Screenshot_20220420-101149_Talk](https://user-images.githubusercontent.com/17063564/164194549-cdfbc3ab-2a3b-43c9-a65f-7d1b176db8d0.jpg)

**Comment by AndyScherzinger** [comment]
@MariusQuabeck you need to upgrade the Android app to the RC, see https://play.google.com/apps/testing/com.nextcloud.talk2 or even the Alphas see https://github.com/nextcloud/talk-android#via-google-play-1

**Comment by MariusQuabeck** [comment]
just tried it, fixed in the RC version, thanks Andy :)

**Comment by AndyScherzinger** [comment]
fixed via #1844 that is why I know
