### ISSUE TITLE
[v14rc2] multiple accounts with same name broken

### ISSUE THREAD

**Issue by XueSheng-GIT** [nextcloud/talk-android#1938]
## Steps to reproduce
1. Add account with username "max@cloud.domain.com"
2. Add a second account with username "max@another-cloud.domain.com"

### Expected behaviour
Second account should be added.

### Actual behaviour
Second account cannot be added. No error is shown... after login, the screen just jumps back to the main screen of nextcloud talk.
But when entering the account details of the existing first account the following message is shown:
![Adding second account with same name](https://user-images.githubusercontent.com/4077683/164526446-9f33e039-9854-4304-9dd0-b0173feec2ac.jpg)

Adding multiple accounts with different names seems to be no issue! Multiple accounts with the same username is also no issue for the nextcloud android app (not talk).

## Device information

**Device:** Huawei Mate 40 Pro (NOH-NX9)

**Android version:** 10

**Talk version:** 14.0.0 RC2

## Server information

**Nextcloud version:** 24.0.0 RC1

**Talk version:** 14.0.0-rc.2

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

**Comment by mahibi** [comment]
thanks for the report we will have a look.
@XueSheng-GIT did you have this issue also for previous versions or is this new in 14.0.0 RC1?

**Comment by XueSheng-GIT** [comment]
Didn't have this issue in the past with NC23 and talk-android 13.
My first impression was that it could also be related to the new server version (24rc1). But didn't double check yet.

**Comment by XueSheng-GIT** [comment]
I did some further testing and wasn't able to reproduce this issue with other user accounts (same username on different hosts). This seems to be an issue for only one specific account I'm using. Therefore I have deinstalled talk-android and re-installed 14rc2 again. Now I'm able to add the mentioned account!


@mahibi feel free to close this issue if you can't reproduce it. One improvement which could be considered is that talk-android should provide direct feedback to the user if adding an account fails.

**Comment by mahibi** [comment]
also can't reproduce this so i will close.
regarding the feedback when adding an account fails: As i can't reproduce it i don't know yet where something needs to be improved. 
Feel free to reopen if you can reproduce it again!
