### ISSUE TITLE
attempt to invoke virtual method java.lang.String com.nextcloud.talk.models.database.UserEntity.getClientCertificate() on a null object reference

### ISSUE THREAD

**Issue by ClCfe** [nextcloud/talk-android#195]
Hello

i just updated to 2.0.0 from play store
I ve got this error as soon as I enter the server address that has ssl client cert enabled

attempt to invoke virtual method java.lang.String com.nextcloud.talk.models.database.UserEntity.getClientCertificate() on a null object reference

I have android 8.1.0

I have no stack trace (nothing in logcat)

Maybe this is occuring here:

https://github.com/nextcloud/talk-android/blob/1b728a7c4d1928f808420b03745666b7583ee306/app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.java#L233

**Comment by ClCfe** [comment]
Yes cert  is imported in android and i can connect to my nextcloud with chrome
No i haven't configured any user in the app

**Comment by mario** [comment]
Thanks for the clarification.

**Comment by ClCfe** [comment]
Hello

Bug is still here, but is definitely related to not having any user configured

if I connect to a server without client certs, then I can add the 2nd account targetting my server with certs 

Maybe the bug is either in controllers/SettingsController.java
Or
utils/ssl/MagicKeyManager.java

**Comment by IMbiea** [comment]
I'm still seeing this issue as well.

Same error.  I have my CA installed, and client certs (same custom CA) which works with Android/chrome
But doesn't work with the latest client (3.1.1)

**Comment by intika** [comment]
still not solved...

**Comment by mario** [comment]
Should be fixed now :)
