### ISSUE TITLE
Room list not loaded anymore after upddate

### ISSUE THREAD

**Issue by socialize-IT** [nextcloud/talk-android#1963]
## Steps to reproduce
1. Update app to 14.0.0
2. Open App
3. List pretends to be loading, but ends in not being loaded/white area

### Expected behaviour
Load the room list

### Actual behaviour
List couldn't be loaded. Instead there is just white

## Device information

**Device:** Galaxy S21

**Android version:** 12

**Talk version:** 14.0.0

## Server information

**Nextcloud version:** 23.0.4 and 23.0.3

**Talk version:** 13.0.5

**Custom Signaling server configured:** yes and version 135df8c50d78e5b1869f7c8b50464d3e748eb712

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

### Server log (data/nextcloud.log)
<details>

```
nothing of today
```
</details>

**Comment by Akrobs** [comment]
Same problem, Samsung S10e, Android 10.

**Comment by AndyScherzinger** [comment]
looping in @mahibi and @timkrueger 

so neither a force close+open doesn't help nor a pull-down-to-refresh?

**Comment by socialize-IT** [comment]
Nothing helps, even rebooted the phone, deleted and readded the accounts and updated HPB to latest version.

It is possible to start new conversations via the + Button, but even new conversations do not show up in the list.

**Comment by Akrobs** [comment]
I'm clear cache & data of Talk app, but this doesn't help me.
Pull-down-to-refresh not help(

**Comment by mahibi** [comment]
thanks for the report @socialize-IT 
we will work on this with highest priority. 
would it be ok for you that you create a test account for us on your affected nextcloud instance so we can debug?

**Comment by socialize-IT** [comment]
You can have an account on one instance. But the problem is existing with different nextcloud instances. What mail should I use for the account?

**Comment by mahibi** [comment]
thank you! you can make an account for marcel.hibbe@nextcloud.com and send credentials to this mail address

**Comment by mahibi** [comment]
thanks. can reproduce it and will start debugging now...

**Comment by mahibi** [comment]
ok found it. this happens when the "user status" app is not enabled on server.
can you also confirm this is not enabled on your instance @Akrobs ?

fix will come soon.
so as a workaround you can enable the "user status" app for now

**Comment by Akrobs** [comment]
Yep, user status app is disabled. Try switch on it.

**Comment by socialize-IT** [comment]
Can confirm that. As soon as "user status" is activated the list appears in the app again.

**Comment by mahibi** [comment]
@socialize-IT you can delete the test account, thank you for your help :+1: 
a fix will come today i guess..
