### ISSUE TITLE
Always show reaction count (not only > 1)

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1983]
To be consistent with iOS and web.
I assume it is this here?
https://github.com/nextcloud/talk-android/blob/dc26a20278ad33a5d252bc35a626e300fede533c/app/src/main/java/com/nextcloud/talk/adapters/messages/Reaction.kt#L78-L84

**Comment by AndyScherzinger** [comment]
I added the hiding based on @jancborchardt's feedback

**Comment by jancborchardt** [comment]
So @nickvergessen mentioned in Talk that the count of 1 is also done e.g. on GitHub (and did you say Telegram?) and I also saw it on Discord.
So I’d say either is fine, as long as it’s consistent. Count of 1 is ok with me. :)
