### ISSUE TITLE
Voice memo quality

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/talk-android#1986]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when.... I have to listen to a voice memo recorded with the Talk Android app.😅

**Describe the solution you'd like**
Please an improvement in the audio quality of voice memos. (Voice memos via the browser have much better quality).

**Comment by dorpauli** [comment]
https://github.com/nextcloud/talk-android/issues/1613
https://github.com/nextcloud/talk-android/issues/1835

**Comment by R7JANV1** [comment]
Ouu unfortunately I have not found. Thank you!

**Comment by dorpauli** [comment]
No problem. I randomly saw your issue and remembered those two, because I'm also waiting for this to be improved. :)

Another hot feature for me is the caching of the chats, so that the client must not have a permanent internet connection to work. Usability would improve much and i could use the app as a daily chat app with my family and friends instead of other messenger. :)

**Comment by R7JANV1** [comment]
I see @dorpauli  we speak the same language. Nextcloud and Nextcloud Talk are great software. But there are many "little things" that are of little importance but still make a big difference and make the use of (non-privacy friendly alternatives) easier and more convenient for "non-techies". Also the caching is a great idea which I hope to see in an upcoming update.

**Comment by R7JANV1** [comment]
> @R7JANV1 No problem. I randomly saw your issue and remembered those two, because I'm also waiting for this to be improved. :)
> 
> Another hot feature for me is the caching of the chats, so that the client must not have a permanent internet connection to work. Usability would improve much and i could use the app as a daily chat app with my family and friends instead of other messenger. :)

I can't find an open issue for caching have you opened one for it?

**Comment by dorpauli** [comment]
There is one https://github.com/nextcloud/talk-android/issues/217 :)

But i thought there was more. I remember, that the old main developer left Nextcloud in about 2019. I believe he started to implement such function, but it seems that it could not be finished.

**Comment by mahibi** [comment]
> I remember, that the old main developer left Nextcloud in about 2019. I believe he started to implement such function, but it seems that it could not be finished.

Yes back then there was once an approach which failed. We are aware and have this in mind for the long term! There needs to be done quite some refactoring before are able to implement this, but that's definitly a main goal..

**Comment by dorpauli** [comment]
> > I remember, that the old main developer left Nextcloud in about 2019. I believe he started to implement such function, but it seems that it could not be finished.
> 
> Yes back then there was once an approach which failed. We are aware and have this in mind for the long term! There needs to be done quite some refactoring before are able to implement this, but that's definitly a main goal..

Thanks @mahibi for your time! You and the other developers are doing a really good job. The app improved a lot in my opinion.

**Comment by mahibi** [comment]
> Thanks @mahibi for your time! You and the other developers are doing a really good job. The app improved a lot in my opinion.

Thank you very much 😀

> 
> And I'm eagerly looking forward to this feature. wink

me too 😉
