### ISSUE TITLE
Profile pictures are extremely large in group chats

### ISSUE THREAD

**Issue by TtuxX** [nextcloud/talk-android#1990]
## Steps to reproduce
1. Open Nextcloud Talk for Android and have a nice conversation with some friends  
2. See that profile pictures are way larger than expected and that they take more space than messages 
3. Have a good laugh but still think about opening an issue on github 

### Expected behaviour
Have a normal chat with plenty of space for messages.
Profile pictures in group chats should not be so large as they appear to be wider than messages themselves haha

### Actual behaviour
Profile pictures heading each group chat message are larger than messages themselves 

## Device information

**Device:** Huawei Mate 10 Pro (on my friend's Samsung device it is the same)

**Android version:** 8.0.0

**Talk version:** 13.0.0

## Server information

**Nextcloud version:** 24.0.0

**Talk version:** 14.0.0

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes, on the server itself

**Custom STUN server configured:** yes, on the server itself

### Server log (data/nextcloud.log)
Not useful for this issue I think 

### Screenshot of the app
![Screenshot_20220505-230233](https://user-images.githubusercontent.com/6570830/167027839-609786f7-1ceb-469c-81a4-98237d1ab234.jpg)

**Comment by AndyScherzinger** [comment]
This has already been fixed with client version 14. Please upgrade the mobile app in order to resolve this.
