### ISSUE TITLE
Avoid SSL certificate check if possible

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/talk-android#20]
Not sure if it's possible on Android
https://gist.github.com/aembleton/889392
but if, the SSL cert check should be avoided. It's technical and cryptic for non-technical end-users. They wouldn't even know what exactly they should check and how.
![image](https://user-images.githubusercontent.com/295122/33933450-0c7b0040-dff6-11e7-9ffc-aa0d40975fdf.png)

**Comment by mario** [comment]
Well, if it's an untrusted cert, what would you like me to do? xD Just trusting every certificate out there is not acceptable.

**Comment by mathiasconradt** [comment]
Depends if untrusted or unknown. If it's untrusted, don't proceed. If it's unknown, proceed.

I mean, how can a user know if he should trust this certificate, when this dialog comes up? What is he supposed to do? It says "Please check out the certificate" but it doesn't tell how/what exactly he should check.
I assume that 99,99% of the user will click "yes" just because they want to proceed with the app, cause they don't even understand the meaning of it. (I'm not talking about NC community members, but business end-users).

I don't have any of these dialogs in other apps like Telegram, Signal, etc. Why would we have it?

**Comment by mario** [comment]
It's basically untrusted, because I cannot find it in any of the system trust managers. Maybe @MorrisJobke can check if we serve the intermediate certificate too, which should resolve the problem?

**Comment by mathiasconradt** [comment]
With "untrusted", I mean if a user has actively rejected a cert before by having pressed "No" anywhere else in the system (i.e. another app). While with "unknown" it would be like in the screen above.
Not sure if the cert validation state between "untrusted" and "unknown" can be differentiated in code.

**Comment by mario** [comment]
As far as I know, it can't - either you trust it or you don't trust it. (It's different with our own trust store, but yea...)

**Comment by MorrisJobke** [comment]
> It's basically untrusted, because I cannot find it in any of the system trust managers. Maybe @MorrisJobke can check if we serve the intermediate certificate too, which should resolve the problem?

We never have seen problems here and also the SSL test says, that it is okay: https://www.ssllabs.com/ssltest/analyze.html?d=cloud.nextcloud.com&hideResults=on The intermediate is properly served.

**Comment by rullzer** [comment]
Also Letsencrypt certs work just fine in the Nextcloud app

**Comment by mario** [comment]
Fixed, thanks!
