### ISSUE TITLE
Tapping notification should not join call with video by default

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#200]
Currently, tapping the notification for a call joins that call by default, with the video on.

In the case of a group call this is very unexpected, especially since we changed the app to show the chat instead of directly joining the call. It would be good if tapping the notification would reflect that, first opening the chat. (Which could show a more prominent »Join call« button below the chat when a call is active.)

**Comment by mario** [comment]
I'm currently refactoring and rewriting/rewiring the "incoming call" experience where you'll be able to select either voice or video response. Since it's an actual CALL (and not a chat message) people do expect to be able to join a call. 

Let's see how you feel about this once this is ready for testing.

**Comment by mario** [comment]
Edit: Yes, group calls are a bit special - but when I get a push notification, I don't know what type of a call it is, so that makes it a tricky. I'll explore how others do it and come back to you.

**Comment by mario** [comment]
@jancborchardt thoughts on the beta?

**Comment by jancborchardt** [comment]
Yup! :)

- Great stuff with full-screen thing!
- the avatar when you get a call from someone else should be even bigger – and when you accepted it and it’s a voice call, the avatar should be exactly the same size (bigger than now)
- When you accept the call, it shouldn’t animate to the right but just morph the view (cause the buttons are basically the same) and replace the avatar with the video (or keep avatar, when it’s a video call)

Here’s a mockup of an improved background without the controls:  **Improved design of avatars in calls** https://github.com/nextcloud/spreed/issues/1011

**Comment by mario** [comment]
Closing this since the actual issue is solved. If you'd like other things, open separate issues and we can discuss.

**Comment by jancborchardt** [comment]
Issue opened at https://github.com/nextcloud/talk-android/issues/223
