### ISSUE TITLE
Hide reactions option for deleted messages and commands

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#2004]
## Steps to reproduce
1. In a chat type `/help`
2. Long press on the resulting message (`messageType === 'command'`)
3. There should be no reaction option

## Steps to reproduce
1. Post a message `test`
2. Delete the message
3. Long press on the `Message deleted by you` (`messageType === 'comment_deleted'`)
4. There should be no reaction option

Server ref:
https://github.com/nextcloud/spreed/pull/7344/files#diff-5b376538abda3104135a2b8890732df2e72ba5533bae840015b0be25c5f33313R586-R587

**Comment by AndyScherzinger** [comment]
I'll take care of this! 👍
