### ISSUE TITLE
Support "📊 Simple polls"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#2024]
Server ref https://github.com/nextcloud/spreed/issues/7355

**Comment by AndyScherzinger** [comment]
@nickvergessen can you also post some screenshots for inspiration from other apps? I checked telegram and signal and couldn't find the option, else I would have posted some :(

**Comment by nickvergessen** [comment]
We talked a bit about it in the feature discussion this morning. It now goes into design process and Marco/Nimisha will follow up with mocks/screenshots
