### ISSUE TITLE
🗂️ More tabs in shared items view

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2029]
Media tab should show:
- Deck cards
- locations
- polls
- other shared objects

Future ideas for another follow up 
- Links https://github.com/nextcloud/spreed/issues/7660

follow up for #1946

**Comment by mahibi** [comment]
this is partly a follow up for the polls. please rate the importance @nickvergessen 
fyi @timkrueger

**Comment by nickvergessen** [comment]
yeah would be good to have

**Comment by timkrueger** [comment]
The nextcloud-android-bot merged my draft PR automatically. Some work is to do.
