### ISSUE TITLE
rounded corners for all bottom menu's

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2035]
When long press a participant in conversation info we use rounded corners for the bottom menu. 
in my opinion this looks much better than the other bottom menu's without rounded corners. 

![grafik](https://user-images.githubusercontent.com/2932790/168153525-4ebcfeee-7f29-4110-8dd2-e0d57c3a9aa3.png)

**Comment by AndyScherzinger** [comment]
Yes, I second that 👍

**Comment by AndyScherzinger** [comment]
Issue with the above is that that is a 3rd party library for dialogs but the dialog is mimicking a bottom sheet design-wise while the other are actual bottom sheets in the part I failed to get the design working in the styling :( Also not sure if that might be a material lib version issue and that it might need a newer version which is currently blocked by the sdk=31 issue...

**Comment by AndyScherzinger** [comment]
@mahibi I have a working solution on my laptop, will push this tomorrow
