### ISSUE TITLE
Update to 23.0.4 broke the link with Android app

### ISSUE THREAD

**Issue by empusaee** [nextcloud/talk-android#2044]
Hi,

After I updated Nextcloud on my server today to 23.0.4, the mobile app (Android 12 Samsung A71) didn't want to login anymore saying that the server version of Nextcloud was too old
I checked my Nextcloud for errors and couldn't see any, updated my mobile app, restarted everything after which i decided to re-install the app. 
Now instead of 'old version' it says that I don't have Nextcloud installed on the server then aborting. But it does recognize my user, so it does connect in some way to my server.

Can you please guide me on what to do or at least what info to pull which you might need in case this is hopefully fixable? 

Thank you

**Comment by empusaee** [comment]
Nevermind, 
For some reason after the last update Talk app got disabled in Nextcloud.

**Comment by AndyScherzinger** [comment]
Thanks for the update and happy to hear it is working again for you 👍
