### ISSUE TITLE
Feature-Request: disable or mute APP/disable calls

### ISSUE THREAD

**Issue by egeu5** [nextcloud/talk-android#205]
We are planning to use NC-Talk-App to get in contact with our students (about 1000+). It would be nice if any user could disable the call/text-feature simple in the app (or "mute" the whole app so that all calls and messages are rejected or not displayed).

On a computer I can just close the windows, on the phone you have to log out...

Thank you!

**Comment by mario** [comment]
I'm not very sure this will happen soon. We could potentially look into speeding it up if you have a Talk subscription and try to push it forward via a professional services contract.

**Comment by mario** [comment]
With 3.0 you'll be able to use system-wide Do-Not-Disturb to accomplish this.

**Comment by egeu5** [comment]
Does system-wide means you can set a DND in Nextcloud Web?
Thank you!

**Comment by mario** [comment]
No. It means your phone.
