### ISSUE TITLE
[14.1.0 Alpha 06] No application opening after tapping push notification

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#2059]
## Steps to reproduce

1. Receive a push notification.
2. Tap on the notification.

### Actual behaviour
When I tap the notification, the Talk application does not open.

## Device information

**Android version:** 10

**Talk version:** 14.1.0 Alpha 06

## Server information

**Nextcloud version:** 24.0.0

**Talk version:** 14.0.1

**Comment by AndyScherzinger** [comment]
Fixed on master by @mahibi so will ship with next week's alpha build
