### ISSUE TITLE
duplicated messages in chat after call

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2060]
## Steps to reproduce
1. start a call & hangup
2. BUG: system messages in chat are shown multiple times (3x?)
3. write a message
4. BUG: message shown twice
5. go back to conversation list & re enter chat
7. BUG: system messages in chat are shown multiple times (2x?), just like on server! (see screenshot)
8. written message is shown once

### Actual behaviour
the call system messages are shown multiple times.
after the call also the normal messages are shown twice

right after trying to call someone
![grafik](https://user-images.githubusercontent.com/2932790/168823787-c8c87c86-b832-4e7e-84e9-39b2174477ba.png)

after switching to conversation list and back to chat
![grafik](https://user-images.githubusercontent.com/2932790/168824248-ebbea71b-4676-455d-aeea-f3325e473ffe.png)

also on server the call system messages are shown twice:
![grafik](https://user-images.githubusercontent.com/2932790/168825565-ef36f482-872e-42f8-a84b-52811844f05d.png)

## Device information

**Device:** Xiaomi Redmi Note 7

**Talk version:** 14.1.0 alpha 06

## Server information
Sermo

**Comment by mahibi** [comment]
might be related:
https://github.com/nextcloud/talk-android/issues/684
https://github.com/nextcloud/talk-android/issues/453

**Comment by hboetes** [comment]
I've seen this as well. Or messages not being displayed until I reopen the window (select another chat and then come back)

**Comment by miaulalala** [comment]
Seeing this on the Android app.

**Comment by andyxheli** [comment]
I also get them without being on a call and sometimes new messages that i send are not visible i have to go out of the chat and back in
