### ISSUE TITLE
FR: Dark theme

### ISSUE THREAD

**Issue by gerroon** [nextcloud/talk-android#207]
I am hoping that we will have a dark theme for this app, this is useful especially for those of us with amoled screens, also darker themes are easier on eyes.

thanks

**Comment by asgardius** [comment]
i'm working in a darkj theme for this app, i'll upload modified files when i finish

**Comment by mario** [comment]
Dark theme will probably have to be calculated based on the existing colors
so when they are changed, dark colors change too

**Comment by asgardius** [comment]
[dark theme patch.zip](https://github.com/nextcloud/talk-android/files/2592392/dark.theme.patch.zip)
Here my dark theme for Nextcloud Talk, Archive includes modified files from current master branch with a list of them in an unix txt file

**Comment by mario** [comment]
Thanks @asgardius - I noticed you changed the colour files directly. Let me see if I can figure something out of this :)

**Comment by mario** [comment]
@dan0xii given your great contributions to the Android app, would you be willing to work on this + https://github.com/nextcloud/talk-android/issues/250 here as well? I am, of course, more than willing to assist.

It would need some refactoring I assume since I didn't get around to extracting all the colours yet.

I'm sure the users would be grateful as your contributions have really been great in this area.

**Comment by dan0xii** [comment]
Sure, I'll take a look. I might be able to port the dark theme from the main app.

**Comment by mario** [comment]
@dan0xii that would be awesome. Like I mentioned, might need a bit more work as colors are hardcoded at places, but you seem to be the expert in these things - so... :)

Remind me to get you a beer/wine/coffee/pancakes when we meet :)

**Comment by dan0xii** [comment]
I curse whenever I see hard-coded colours !

> Remind me to get you a beer/wine/coffee/pancakes when we meet :)

I won't forget. :)

**Comment by gerroon** [comment]
> I curse whenever I see hard-coded colours !

This is the spirit!
