### ISSUE TITLE
Creating public call with no participants should open the conversation

### ISSUE THREAD

**Issue by mario** [nextcloud/talk-android#208]

**Comment by jancborchardt** [comment]
What does "pop the screen" mean? Showing the share sheet directly? (If so then yeah, probably good)

**Comment by mario** [comment]
No, it means going back to the conversation list. If you want a share sheet opened in this case, open a separate issue for one of the future versions.

**Comment by mario** [comment]
Actually looking at the issue list, there's an issue for that @jancborchardt : https://github.com/nextcloud/talk-android/issues/197

**Comment by jancborchardt** [comment]
Creating any call should go into the conversation itself though, not the conversation list. Or not?

**Comment by mario** [comment]
@jancborchardt well, it could. But what's the point doing that when you create a public call with no participants? :)

**Comment by jancborchardt** [comment]
@mario because then you can directly send messages, or start the call already. Then when #197 is also implemented, you can share the link instantly too.

Also, this is how we do it in the web app as well.
