### ISSUE TITLE
Allow Reactions in Talk App

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/talk-android#2085]
Hi,

this is probably a duplicate, but i really can't find a ticket for this.

At the moment you can only add reactions to a message when you use talk in the browser.

In the (Android) Talk App you can remove your reactions by clicking on the reaction, but you can not add new reactions. A lot of our users use talk primarly on the smartphone and it would be great if they could add reactions too.

**Comment by AndyScherzinger** [comment]
Android app allows for reactions in case you run at least 14.0.0 for mobile app as well as server. You see the reactions on the long press of a message.

**Comment by xbluemonkx** [comment]
@AndyScherzinger that is very weird. it just started working. no update was done in the meantime, but someone with an iphone added reactions. from then on i was able to add them by myeself using android.
