### ISSUE TITLE
No visual or audio clues for incoming call

### ISSUE THREAD

**Issue by Grunthos** [nextcloud/talk-android#209]
I may misunderstand the way things should work, but I call one of my contacts who has nextcloud talk app and they get no indication of any kind that a call is requested. I have set us both up with ring & message sounds. Also, text messages arrive but no sound plays.

If we both call each other then the call is connected and we can speak.

A visual and audio signal would be great.

**Comment by mario** [comment]
What version od the app, what version od Talk app on the server, do you
have Notifications app installer on the server, Google Play on the phone?

**Comment by Grunthos** [comment]
Sorry, I should have posted these!

App: 2.1.0beta 2 (and was at most recent non-beta before that)
NC: 13.0.4
Notifications App: 2.1.2 (enabled)

**Comment by mario** [comment]
Google play services?

Also what phone & android version?

**Comment by Grunthos** [comment]
Play services 12.6.85 on both.

Phone 1: Android 5.0  (Zenfone 5)
Phone 2: Android: 7.0 (Galaxy S7)

**Comment by Grunthos** [comment]
Yes, on Asus, can't find on the Samsung. Still no joy.

**Comment by mario** [comment]
Send me two test accounts on mario@nextcloud.com and I can test later today.

**Comment by Grunthos** [comment]
OK...is there a recommended means of sending accounts to external users?

**Comment by Grunthos** [comment]
You*should* receive emails. Let me know.

**Comment by Grunthos** [comment]
Ahhh...could be firewall? What ports are used?

**Comment by mario** [comment]
Firewall on mobile phones?

**Comment by Grunthos** [comment]
NC server, since I assume phones speak via server

**Comment by mario** [comment]
Notifications are related to Google servers. Anyway I will test if it works
once near a computer

**Comment by jookk** [comment]
I have no problem with call notification, but text msg's are not notified.

**Comment by ArtJames** [comment]
NC 13.04, Notifications 2.1.2, Coturn, Play Services 12.6.85, Android 5.1 (2 devices)

Tested phone to phone, phone to website
Voicecall: Working, including notifications
Textchat: Working, but without notifications
Videochat: App on both phones crash immediatly

Older versions 1.x work well. (Voice/Video-calls)

**Comment by mario** [comment]
Text chat has notifications only if you're mentioned. Say "@jookk" or "@ArtJames".  cc @ArtJames and @jookk

**Comment by jookk** [comment]
So, no notification on receiving new msg?

**Comment by mario** [comment]
No @jook. See: https://github.com/nextcloud/spreed/issues/875

**Comment by mario** [comment]
@Grunthos so I had a quick look. It seems like app tokens that are created as part of the login flow are not stored properly/at all and that is why push registration fails. Feel free to delete my accounts now.

(cc @rullzer anyone else complained about this?)

This is possibly a setup or a server (https://github.com/nextcloud/server) bug so you might look into that direction.

**Comment by Grunthos** [comment]
@mario Thanks for investigating. There was nothing in the logs from nextcloud that indicated an issue, and nothing in the app that indicated that regisdtration failed. So what I did was kill the app on my phone to (I assume) force it to register again. What I see is this:

    <MY-ADDR> - <USER> [26/Jun/2018:10:10:32 +1000] "POST /ocs/v2.php/apps/notifications/api/v2/push?proxyServer=https://push-notifications.nextcloud.com&devicePublicKey=-----BEGIN<STUFF>END%20PUBLIC%20KEY-----%0A&pushTokenHash=<LONG HASH>&format=json HTTP/1.1" 400 112

The 400 response is probably the root of the problem. Also, using https://push-notifications.nextcloud.com (presumably a next cloud server) might be an issue since I assume I am not registered there.

Any suggestions?

**Comment by mario** [comment]
I answered via email @Grunthos since you mailed me.

**Comment by mario** [comment]
But to write it again here: The reason why you get 400 is what I mentioned earlier: your Nc server doesn't store app tokens for some reason.

**Comment by Pistos** [comment]
@mario (Honest question) Are you saying that Nextcloud Talk can't provide native notifications without going through Google-controlled servers?  If so: Is that just how Android is?

**Comment by makuser** [comment]
@mario you asked how @Grunthos installed it and he said Google Play store. I got it from F-Droid, so I assume and hope there are no Google services integrated in this version?

Notifications don't work there too, which is why I'm here. How does it work for those setups? And what about iOS or other platforms?

**Comment by n-e-y-s** [comment]
@mario Having the same problem. Using FDROID to install apps on my phone and neither google play nor google play services installed due to privacy concerns. 

Is there really no google-free solution for getting notifications? There are apps out there being able to give notifications, e.g. Conversations.

**Comment by mario** [comment]
Please stop spamming the issue :-/ There will be a partial solution for fdroid installs soon.

**Comment by makuser** [comment]
@mario Holy cow.

It was a normal question and/or note that @n-e-y-s had and there was NOTHING from you on this topic here for nine months, so I'd say it's valid to refresh it once more.

And now you immediately react like that?

Please chill the f*** down, noone is spamming after replying to an issue that's nine months old without any progress being made (at least not made visible in this issue).

Thank you.

So if there will be a partial solution in the close future, why didn't you say so anyway? I mean isn't this issue tracker precisely for things like that?

Man, some maintainers need to relax some more....

**Comment by mario** [comment]
@makuser spamming it is because this issue has NOTHING to do with F-Droid and it was closed as a setup issue.

If you want F-Droid related thing, please take a look into https://github.com/nextcloud/talk-android/issues/257. Also, look at the latest reply there where I said exactly what you wanted to hear.

In the mean time, please take a look at Code of Conduct or I will be forced to take further actions since your wording is not adequate.

**Comment by Pistos** [comment]
(for reference, here's the deleted comment: https://gist.github.com/Pistos/2420c65117ed9edc56df8c2ba3c53026 )

Personally, I think the aggression on both sides was unwarranted.
