### ISSUE TITLE
"Your SSL setup prevented us from connecting" message not making sense

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/talk-android#21]
The "Your SSL setup prevented us from connecting" message I get is confusing, it doesn't make much sense. It happened when on the NC i tried to connect, there was still NC12 without the Talk app (server-side) running.

So, of course the talk app wouldn't work without a server-side Talk app installed.

But SSL is fine, and should not be related, therefore the message does not make much sense here.

![image](https://user-images.githubusercontent.com/295122/33933562-68d0979c-dff6-11e7-8121-f39dab8494e7.png)

**Comment by mario** [comment]
Did you accept the SSL certificate?

**Comment by mathiasconradt** [comment]
Yes, I did. You can try it yourself. Choose https://nextcloud.com as URL (of course, there is no Talk or even NC running, but it's still a valid SSL cert), and you would get the same message.

**Comment by mario** [comment]
Fixed. You'd get 404 now :P
