### ISSUE TITLE
[14.1.0 Alpha 07] i18n: Translate "Search" for Emoji

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#2110]
## Steps to reproduce

1. Choose an Emoji.
2. Tap the "Search" magnifying glass.

The text string "Search" is not translated. My guess is that it comes from a ready-made Emoji module.

![obraz](https://user-images.githubusercontent.com/47037905/171399186-40fae22b-a1b2-46fa-b388-bc70423d0cca.png)

## Device information

**Android version:** 10

**Talk version:** 14.1.0 Alpha 07

**Comment by AndyScherzinger** [comment]
@Valdnet for me having a German locale it says "Suche" but yes, I expect this to be within the emoji lib, yes

**Comment by Valdnet** [comment]
And with me it is in English 😁.

**Comment by Valdnet** [comment]
Will it be possible to adapt the code to translate into other languages?

**Comment by AndyScherzinger** [comment]
well, see https://github.com/nextcloud/talk-android/issues/2110#issuecomment-1143573173 that's is what I need to check, because the library ships its own translations, so not sure

**Comment by AndyScherzinger** [comment]
@Valdnet Opened a PR, so when merged, the day after the strings will be translatable 👍
