### ISSUE TITLE
[14.1.0 Alpha 07] Opening a conversation from a notification

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#2111]
## Steps to reproduce

1. Receive notification.
2. Tap on the notification.

After tapping the notification, a conversation with another user with whom I wrote earlier opens. I don't know why it always selects the same user. Perhaps this was the last conversation with a user on a previous version or the first conversation on a new version. Or maybe it's the first user to add to the list.

## Device information

**Android version:** 10

**Talk version:** 14.1.0 Alpha 07

**Comment by AndyScherzinger** [comment]
I can reproduce this and it always opens the same one for me two. Didn't have the time to debug though.

**Comment by Valdnet** [comment]
> I can reproduce this and it always opens the same one for me two.

Cool 👍. Now just wait for the fix.

**Comment by mahibi** [comment]
can reproduce :+1: 
doesn't happen with 14.0.2

**Comment by Valdnet** [comment]
This also happens when you reverse the rotation of the smartphone on an open conversation. After the rotation, a conversation with another user opens.
