### ISSUE TITLE
Need an option to "ignore" calls in some rooms

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#212]
…

**Comment by mario** [comment]
I'd guess you'd want this mostly in group and public calls, right? Once I get the call type in a notification, those calls won't be as prominent as they are now - instead they'll get a simple notification + one-time sound.

**Comment by nickvergessen** [comment]
Yeah well the internal room jan created earlier had 4 calls already :D

**Comment by mario** [comment]
Get me call types :P

**Comment by jancborchardt** [comment]
The calls just happened because of a bug that @schiessle encountered (in the Android Talk app) where tapping the conversation started a call instead of a chat.

So that should be fixed rather than adding the requested setting.

**Comment by jancborchardt** [comment]
Also, this is a duplicate of #205
