### ISSUE TITLE
No overview of conversations

### ISSUE THREAD

**Issue by Tino-ko** [nextcloud/talk-android#2123]
Hello,
for a few weeks we have been having problems with the Nextcloud Talk app for Android (the IOS app works as usual).

## Steps to reproduce
1. open the app
2. login
3. -> overview of the previous chats is missing

### Expected behaviour
See a overview of last Chats/Messages

### Actual behaviour
If the app is opened, an empty window appears, the overview of the previous chats is missing (the only thing we see are grey bars.).
If a new conversation is started and a contact is selected via the app, the older chats are available and telephony and chat functions work without any problems.

For testing, I restored an older backup from 6.5. of the Nextcloud and the external signal server but could not detect any change in behavior. I'm assuming this is related to the latest update to the Android app.

It is strange that users who are members of the “admin” group are not affected by this problem. Talk group restrictions are not set.
The problem was first reported to me on 12 or 13.5.

## Device information

**Device:** different / Samsung S20

**Android version:** different, up to 12

**Talk version:** 14.0.1

## Server information

**Nextcloud version: [Nextcloud HanssonIT VM] (23.0.4)

**Talk version: 13.0.6

**Custom Signaling server configured: I can't find this one in https://domain.tld/settings/admin/talk#signaling_server

**Custom TURN server configured: yes

**Custom STUN server configured: yes 

### Server log (data/nextcloud.log)
No entries related to Talk

</details>

**Comment by Tino-ko** [comment]
> For testing, I restored an older backup from 6.5. of the Nextcloud and the external signal server 
I meant turn and stun servers

**Comment by mahibi** [comment]
Thanks for the report!

Does this also happen with Nextcloud Android Talk 14.0.2 ?

If yes, would you be willing to temporarily provide me a test account for your server? Just send the credentials to marcel@nextcloud.com

**Comment by mahibi** [comment]
my first guess was that it's https://github.com/nextcloud/talk-android/issues/1963 but this should be fixed already with 14.0.1, so maybe it's another error.

**Comment by mahibi** [comment]
Glad i could help @Tino-ko 
We will have to implement the check if status app if restricted to groups
