### ISSUE TITLE
Crash when calling on alpha 7 & 8

### ISSUE THREAD

**Issue by maxcco** [nextcloud/talk-android#2132]
First of all thank you all for this great app !! It so nice to see all the new features and development that you bringing lately
Since I upgraded to alpha 7, my calls stopped working. Crash when calling and answering 
Everything work back great if I downgrade to alpha 6

Tell me if you need more info

## Steps to reproduce
1.Start a call 

1.Receive a call 
2.Press answer (video or not same behavior) 

### Expected behaviour
Call is starting

### Actual behaviour
App crash

## Device information

**Device:** s10e

**Android version:** 12

**Talk version:** 14.1.0 alpha 7 and 8

## Server information

**Nextcloud version:** 24.0.1

**Talk version:** 14.0.2

**Custom Signaling server configured:** no 

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

**Comment by AndyScherzinger** [comment]
@mahibi @timkrueger any idea what might have changes from Alpha 6 to 7/8 ?

**Comment by AndyScherzinger** [comment]
The numebr of changes is (unfortunately) super-huge...

https://github.com/nextcloud/talk-android/compare/alpha-140010006...alpha-140010007

**Comment by mahibi** [comment]
thanks for the report!
can't reproduce yet..

Do you have more phones that you can try? So does this happen only on your galaxy s10e or also for other devices?

Would you be willing to create 2 temporary test accounts so we can log into the server and try to reproduce & see logs?

**Comment by maxcco** [comment]
Hej Mahibi

Tried it on an old xperia z5c with android 11 both versions are working fine there.

Completely removed the app from the s10e and did a system upgrade. Still the issue persist crash right when clicking on calling button.
Is there a way to extract log, that can be useful for you ?

**Comment by mahibi** [comment]
@tobiasKaminsky could you try to reproduce this with your S9+ ?

**Comment by tobiasKaminsky** [comment]
I cannot reproduce it, but I only have Android 10.

**Comment by timkrueger** [comment]
I can reproduce this on a Samsung Galaxy A32 with Android 12.

I take over this issue.
