### ISSUE TITLE
Handle "400 Bad Request" on set password

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#2143]
Password policy app support has been implemented with https://github.com/nextcloud/spreed/pull/7473
If the password does not match the password policy rules, a `400 Bad Request` will be returned as normal OCS response.
The data contains a `message` attribute which should be shown to the user (it's translated already).

**Comment by timkrueger** [comment]
Currently setting a password for a conversation is not supported and it's implementation is tracked in https://github.com/nextcloud/talk-android/issues/2133.

The password policy response will be respected during the implementation.
