### ISSUE TITLE
Remove dependency EffortlessPermission

### ISSUE THREAD

**Issue by timkrueger** [nextcloud/talk-android#2155]
Remove the [EffortlessPermission](https://github.com/zhanghai/EffortlessPermissions) library.

It looks like this dependency is the cause for multiple issues:
- https://github.com/nextcloud/talk-android/issues/1309#issuecomment-900283351
- https://github.com/nextcloud/talk-android/issues/2114

The library is exclusively used in the `CallActivity` and should be replaced by the in the [Android Developer documentation](https://developer.android.com/training/permissions/requesting) described way. In the following PR the `BLUETOOTH_CONNECT` permission is already requested by that way:
- https://github.com/nextcloud/talk-android/pull/2139

**Comment by AndyScherzinger** [comment]
@dependabot rebase
