### ISSUE TITLE
Development setup not described

### ISSUE THREAD

**Issue by Grunthos** [nextcloud/talk-android#216]
I'm using latest AS and have tried HEAD and 2.0.2; on a fresh install of the app both hang after the register step (blank screen with spinning progress item).

Are there any special setup instructions I should be aware of?

After the reg step, if I press back a few times until I get "Unfortunately, Nextcloud Task has stopped", after which I can restart the app and it seems to work, but without notifications which were precisely what I was hoping to debug.

**Comment by jancborchardt** [comment]
@mario can you add a "Development setup" section to the readme which includes this info? :)

**Comment by jancborchardt** [comment]
@mario can you add a "Development setup" section to the readme which includes this info? :)

**Comment by jancborchardt** [comment]
@mario can you add a "Development setup" section to the readme which includes this info? :)

**Comment by mario** [comment]
@jancborchardt why write this three times?

@Grunthos there are no special build steps. Git clone + run in AS. If the app itself crashes, look at the crash report and submit it if you think it's a bug in the app.

**Comment by jancborchardt** [comment]
@mario sorry, was apparently a bug.

@mario could you please add those steps, however simple they are, as a "Development setup" section in the readme? Also, this link in the readme is broken: https://github.com/nextcloud/talk-android/blob/master/CONTRIBUTING.md

**Comment by mario** [comment]
@jancborchardt absolutely.

**Comment by AndyScherzinger** [comment]
contribution guidelines as well as dev setup instructions have been written (adopted and adapted from files app) and merged to master
