### ISSUE TITLE
14.1.0 RC1: "Search within messages" -> show result message

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#2162]
I can search for conversations this still works but if I search for texts within a conversation no result is shown up
If I press the Enter key after tipping a search phrase the search is not working entirely

**Comment by AlvaroBrey** [comment]
@jakobroehrl the message search needs a new capability from server, which I think is still unreleased. The search option should not even appear in this case.  What nextcloud version / talk version do you have in your server?

**Comment by jakobroehrl** [comment]
the latest

**Comment by AlvaroBrey** [comment]
> the latest

Specific version please. Unless it's a version from a Git branch directly, there haven't been any Talk (server) releases with the new capability yet.

The real bug here is that you can see the Search option, it should not be possible without the capabilities.

**Comment by jakobroehrl** [comment]
I dont see any changes to 14.0.2 regarding the searchbox.
I only can search for conversations. I thought in the same box I now can serach for conversations and messages

**Comment by jakobroehrl** [comment]
Tested with the latest spreed server version.
Search is now working.
If I click on the search result it would be great if not only the conversation is shown up but scrolling to the result message.

**Comment by AlvaroBrey** [comment]
> Tested with the latest spreed server version. Search is now working. If I click on the search result it would be great if not only the conversation is shown up but scrolling to the result message.

It will scroll to the result message if it's in the already fetched messages (last 200 if I recall correctly), but not if it's earlier. We may have a way to improve this if/when we implement offline caching of messages

**Comment by jakobroehrl** [comment]
This is working, lets close it for now
