### ISSUE TITLE
14.1.0 RC1: "Quick reply via notification": Fehler beim senden der Nachricht

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#2163]
Reply field is shown up, if I write a text an tip send
"Fehler beim senden der Nachricht" is shown up and the message is not delivered
But very cool feature btw

**Comment by jakobroehrl** [comment]
Tested again now it works

**Comment by AndyScherzinger** [comment]
😁 happy to hear it works now, also not sure how to analyze with out a log :S
