### ISSUE TITLE
"Mark as read" via notification

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#2164]
@starypatyk implemented "Quick reply via notification" what works very well
Mark as read would be awesome, too.

**Comment by starypatyk** [comment]
@jakobroehrl I have not been able to contribute recently. I hope to have some time to spare in July. 😉

**Comment by nickvergessen** [comment]
https://nextcloud-talk.readthedocs.io/en/latest/chat/#mark-chat-as-read

**Comment by AndyScherzinger** [comment]
Currently not possible to be implemented since the push notification doesn't ship the message id which would be needed to mark it as read, see https://github.com/nextcloud/talk-android/pull/2199#issuecomment-1177984416

**Comment by nickvergessen** [comment]
> Currently not possible to be implemented since the push notification doesn't ship the message id which would be needed to mark it as read, see https://github.com/nextcloud/talk-android/pull/2199#issuecomment-1177984416

It does, the object id of the notification is `conversation-token/message-id` ?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blob/da0ec90ce550e71f81da47db50ba70c5a504b5e8/lib/Notification/Notifier.php#L388-L394

Okay, sorry. Only does so when NOT preparing push. So if you pull the notification from the server (which I think you do anyway?) you should be able to split the object id by `/`
