### ISSUE TITLE
[14.1.0 Alpha 11] Message visibility

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#2167]
## Steps to reproduce

1. Receive a message
2. Open a conversation.
3. Reply to the message.

The last message is not displayed in full. A window for typing a message covers it:

![obraz](https://user-images.githubusercontent.com/47037905/175907574-883366d3-b0ae-48e1-b50d-b9d48a254219.png)

## Device information

**Android version:** 10

**Talk version:** 14.1.0 Alpha 11

**Comment by mahibi** [comment]
just a guess without to have a closer look or reproduce: might be related to https://github.com/nextcloud/talk-android/pull/2131 ?

**Comment by mahibi** [comment]
this bug occurred quite often for me now while developing

**Comment by mahibi** [comment]
should be fixed since quite long. otherwise please reopen
