### ISSUE TITLE
Design : enable a more compact display of the text messages

### ISSUE THREAD

**Issue by GLLM** [nextcloud/talk-android#218]
Hi !
when using NC talk (text messages) on Android (8.0, latest released version), I find that the display of chats is not taking advantage of the screen estate : 
when the keyboard is visible NC talk displays only 7 lines of text (among 2 people's msg) while whatsapp displays 11, and signal 11 as well.

I findh that the font is too big and the spacing betwenn the bubbles is to large + the empty space within a bubble (between text and border) is too large as well.

Am I the only one to wish for a way more compact design ?
Thanks

**Comment by jancborchardt** [comment]
Good point. Our text is not even bigger than in Signal.

We can put the time into the bubble, and next to it display a sent confirmation as mentioned in #219. And the padding of the bubble can be reduced.

**Comment by mario** [comment]
Time was initially in the bubble. Then we moved it out of the bubble. Are we really moving it OUT of the bubble again?

**Comment by mario** [comment]
cc @skjnldsv

**Comment by jancborchardt** [comment]
@mario if that's a problem, focus on only the bubble padding first.

**Comment by mario** [comment]
I'm not sure this is a trivial change at this point.

**Comment by skjnldsv** [comment]
I would stack all the messages from the same user during a specific period of time. :)

**Comment by mario** [comment]
@skjnldsv that's planned and in a separate issue already - we agreed to do this already ;)

**Comment by skjnldsv** [comment]
So lower the bubble padding and stack up should be enough?
![screenshot_20180627-193204](https://user-images.githubusercontent.com/14975046/41990085-b732db94-7a41-11e8-82be-5b1e0482d9d6.png)

As a reference: my sms app which I really like
![screenshot_20180508-141548](https://user-images.githubusercontent.com/14975046/41990168-f38f8952-7a41-11e8-9144-17a820f23d42.png)

**Comment by mario** [comment]
This is exactly what I'll do. Eventually.

**Comment by skjnldsv** [comment]
You rocks!
@jancborchardt opinions? :)

**Comment by jancborchardt** [comment]
Cool! I mean, to be clear, only reducing the bubble padding is fine. The rest of the style, like the big bubble border-radius is great.

**Comment by GLLM** [comment]
The large radius is bit too large IMHO .... sooooo iphone3ish :-)

**Comment by mario** [comment]
4dp
![screen shot 2018-07-02 at 22 16 27](https://user-images.githubusercontent.com/5810/42184374-96931ebe-7e45-11e8-9a15-dba9c338f9c4.png)

vs 

8dp
![screen shot 2018-07-02 at 22 17 17](https://user-images.githubusercontent.com/5810/42184406-b2ba66ba-7e45-11e8-8fff-2c99df734c95.png)

@jancborchardt @skjnldsv ?

**Comment by mario** [comment]
Currently it's 8dp.

**Comment by skjnldsv** [comment]
Could you try 2dp?
Also I kind of agree that the radius is too big @jancborchardt .
Could we lower it to something like we have on the server? 3px?

**Comment by mario** [comment]
@skjnldsv can you clarify what radius are you referring to?

**Comment by skjnldsv** [comment]
The radius of the bubbles, it feels too big compared to what we're using on the server: https://github.com/nextcloud/server/blob/master/core/css/variables.scss#L50

2dp was for the padding :)

**Comment by mario** [comment]
@skjnldsv it is currently 15dp. And you want it 3dp?!

**Comment by skjnldsv** [comment]
@mario I need to see before :p 
I have no idea what 3dp looks like

**Comment by mario** [comment]
![screen shot 2018-07-03 at 10 04 19](https://user-images.githubusercontent.com/5810/42206803-7a004160-7ea8-11e8-84dd-819753af1cb2.png)

2dp padding between bubbles, 3dp border radius xD

**Comment by mario** [comment]
Very ugly!

**Comment by skjnldsv** [comment]
Aaah, far better :D 
Not sure @jancborchardt agree though. What are your thought @mario ?

**Comment by mario** [comment]
I think the padding between bubbles is fine, but the border radius is super super ugly.

Let me try 6dp.

**Comment by mario** [comment]
I can live with 8dp.
![screen shot 2018-07-03 at 10 09 10](https://user-images.githubusercontent.com/5810/42207038-2c14d8d4-7ea9-11e8-9430-bff0f02c4981.png)

**Comment by mario** [comment]
So ... 2dp, 8dp it is!

**Comment by skjnldsv** [comment]
Not a big fan :)
Signal, textra, whatsapp, all uses small radius. I guess 8dp is better that what we currently have though, but maybe an inbetween like 6 is better ;)

Also: your screenshots could benefit from more pixels :p 
Hard to see on low res, especially on the radius anti aliasing

**Comment by mario** [comment]
I can do 6 as a compromise.

**Comment by mario** [comment]
@jancborchardt @skjnldsv final:

![screenshot_20180703-103335_nextcloud talk](https://user-images.githubusercontent.com/5810/42208561-c65fbb18-7eac-11e8-9a9a-3fc75a51d0b5.jpg)

**Comment by GLLM** [comment]
hey all !
just wondering : why are we keeping that large of a space/padding between teh text within a bubble and the border of the bubble ?
It just looks sooo big (to me, at least) :

**Comment by mario** [comment]
@skjnldsv and @jancborchardt to the rescue.

**Comment by skjnldsv** [comment]
I kind of agree, @jancborchardt to the rescue then? :laughing:

**Comment by mario** [comment]
@GLLM @skjnldsv @jancborchardt 
![screenshot_20180703-135038_nextcloud talk](https://user-images.githubusercontent.com/5810/42218219-25e26a48-7ec8-11e8-8904-768f1e79aefc.jpg)

**Comment by mario** [comment]
Better?

**Comment by jancborchardt** [comment]
It still seems there is a lot of padding? As a baseline, could you simply use the _same_ measure as Signal uses?

Also, the text size is quite small. The date divider size is bigger than the text. Text size should be increased to be same size as date divider.

**Comment by mario** [comment]
It's 8dp vs 16dp.

**Comment by mario** [comment]
Sorry, 12dp vs 16dp. I'll set it to 8 and be done with it. Text increased from 16dp to 14dp.

**Comment by mario** [comment]
![screenshot_20180703-135849_nextcloud talk](https://user-images.githubusercontent.com/5810/42218521-2d740e64-7ec9-11e8-870b-f93ab6649bf3.jpg)

**Comment by skjnldsv** [comment]
Nice!

**Comment by mario** [comment]
I dislike the big text size heavily. The padding is fine, but I have to reduce the text size.

**Comment by mario** [comment]
Final design:

![screenshot_20180703-140315_nextcloud talk](https://user-images.githubusercontent.com/5810/42218720-c9406cde-7ec9-11e8-8c38-3cf613001b60.jpg)

**Comment by mario** [comment]
(Btw. date divider is bigger on purpose)

**Comment by mario** [comment]
After thinking about it, made is smaller.

![screenshot_20180703-141850_nextcloud talk](https://user-images.githubusercontent.com/5810/42219367-fdb06116-7ecb-11e8-80d2-cef6fceebf74.jpg)

**Comment by GLLM** [comment]
@mario : your last attempt looks really good :) I like it this way !
I wont bugger for more changes if it remains like this !

**Comment by mario** [comment]
I'd need another issue, but I'd close it right away, sorry :P 
One wish at a time :D

**Comment by GLLM** [comment]
No worries ... Be careful what you wish for :)

https://github.com/nextcloud/talk-android/issues/225

**Comment by jancborchardt** [comment]
Sorry, this is not about liking or disliking but about readability on mobile. The text size is too small. The one in your earlier screenshot was perfect: https://github.com/nextcloud/talk-android/issues/218#issuecomment-402129987

**Comment by GLLM** [comment]
@jancborchardt  : not sure who your last message was meant for !

But then, let's have a setting for the font size, like every 2018-ear messaging app .... 
On bigger screen smartphone (such as mine) , I feel like I'm visually deficient with such a big font ! (no offense meant to visually deficient people)

GLLM
