### ISSUE TITLE
Feature Request : add a Sent/Received/Read status for text messages

### ISSUE THREAD

**Issue by GLLM** [nextcloud/talk-android#219]
hi !

maybe there's a pre-requisite of the chat server itself, but I'd love to have : 
Sent
Received
Read
status indicators the same way Signal or Whatsapp do ...

The way signal or Whatapps do it is nice :
1 grey tick for Sent
2 grey tick for Received
2 blue (theme colored) ticks for Read

Anyone else ?

**Comment by mario** [comment]
This is a request for the server app first.

**Comment by GLLM** [comment]
@mario : thanks, do you need me to log an issue on the server repo ?

**Comment by mario** [comment]
Yes please

**Comment by GLLM** [comment]
Done > https://github.com/nextcloud/server/issues/10029

I let you add the link to this enabler.
Many thanks !!

**Comment by gradinaruvasile** [comment]
Also it would be nice to see WHO read the message in group chat. 
Something like in Hangouts and Riot.im, where they place small "pills" of user icons under the message. Very useful feature.

**Comment by scalderwood1** [comment]
@mario Looking at the prereq on server, according to the issue log 5.0 included this as of Dec '18. Is this something that can be prioritized for android-mobile now?

**Comment by mario** [comment]
@scalderwood1 this was never implemented on the server. Where have you seen this?

**Comment by scalderwood1** [comment]
@mario - Perhaps I am misreading the milstone adoption for the project. Looking at milestones 5.0.0 shows as being attached to that feature request and shows as 100% done. Release is shown as 5.0.2 currently.

**Comment by mario** [comment]
Link me up? :)

**Comment by scalderwood1** [comment]
Sure thing, @mario - [Spreed issue here] links to  [milestone 5.0.0 for spreed](https://github.com/nextcloud/spreed/milestone/15) which shows 100% completed. In latest releases they are on version 5.0.2

**Comment by mario** [comment]
This was changed to Backlog, so not done.

**Comment by scalderwood1** [comment]
Ah- so i was misreading it.  ;)

**Comment by nickvergessen** [comment]
Implemented with https://github.com/nextcloud/talk-android/pull/948
