### ISSUE TITLE
Feedback missing for copying message (long-press)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#220]
I tried to copy a message by long-press and it didn't work.

Should probably work, just like in Signal where you can copy the whole message. (In the future it can also have options to forward etc., but copying is essential.)

Also cc @ivansss – not sure if it's the same in the iOS app.

**Comment by mario** [comment]
Of course it works, I just tested this. Why do you think it didn't work?

**Comment by mario** [comment]
Let me know how you tested this, cause I just tried both copy AND pasting the text and it absolutely worked.

Also what Android version & phone.

**Comment by andrew-paglinawan** [comment]
Haven't tested it on android but in iOS it's not possible to copy text.

**Comment by jancborchardt** [comment]
Fairphone 2, Android 6.0.1

I tried just tapping a message, or long-pressing. Nothing happens. To be clear: I mean copying text from messages _already sent_, so in the message list. (Of course copying/pasting from the input field works.)

**Comment by mario** [comment]
@jancborchardt long-press on a message bubble should copy it. After doing that, try long press on the input field and click paste. If that doesn't work (which it should) I can look into Android 6 a bit more.

**Comment by jancborchardt** [comment]
Huh, it does indeed work, but there is no feedback _at all_. We need a toast/snackbar (whatever is proper) here which says "Message copied".

**Comment by jancborchardt** [comment]
Reading up on it again, I would say a snackbar is better here: https://material.io/design/components/snackbars.html

So it could read:

> Message copied    **Share**

With share being the action, and the way you can immediately share the content you just copied to other apps (bringing up the share sheet).

**Comment by mario** [comment]
The sharing part I'll ignore, but snack I can do :)

**Comment by mario** [comment]
So I talked with @nickvergessen and @giulianograssi and there will be a context menu in the future with various other options. Since copy will be there, is that enough for you so we don't really need the snackbar or anything @jancborchardt?

**Comment by mario** [comment]
@giulianograssi any chances you've had the time to work on this?

**Comment by jancborchardt** [comment]
@mario I’m fine with the context menu, but if that still is not started (and takes a lot of time), maybe it makes sense to have a quick fix in the form of a snackbar as mentioned above? Especially as others are filing issues too.

**Comment by mario** [comment]
Context menu is now there.
