### ISSUE TITLE
switching accounts fails / wrong username shown in account switcher

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2218]
## Steps to reproduce
there exist 2 users: userA and userB

1. login with userA
2. go to account switcher
3. BUG: avatars are shown correctly, but userA has the name of userB
4. keep userA selected. go to some conversation and send a message
5. BUG: message is sent as userB
6. go back to account switcher and select userB
7. go to the conversation and send a message
8. BUG: message is sent as userA

this doesn't always happen but sometimes.

### Expected behaviour
- names in account switcher match the avatars
- actions are not executed as another user

i guess this is caused by the room migration..

## Device information
**Talk version:** master (>= 14.2.0 Alpha 02)

## Server information
sermo

**Comment by AndyScherzinger** [comment]
@mahibi are both users on the same server or different ones? I tested with 3 users on 3 servers and don't have an issue there.

**Comment by mahibi** [comment]
both on the same server (sermo)

**Comment by mahibi** [comment]
just reproduced this with 14.1.0 RC2 !
this time the names in the account switch dialog were correct but the messages were still send as the wrong user!

**Comment by AndyScherzinger** [comment]
@mahibi but it works with 14.0.2 - no?

**Comment by mahibi** [comment]
same error with talk app 14.0.2 on sermo. so either i proved it's a bug present in the app or (which i assume as described) on sermo... now trying with older servers..

**Comment by AndyScherzinger** [comment]
same error with 14.0.0 with personal server on 24.0.2 while it works fine with 13.0.0 so it is not the DB technology switch but something else.

**Comment by AndyScherzinger** [comment]
--> issue must be client side

**Comment by mahibi** [comment]
as expected, and now approved:
this happens only for accounts that are on the same server. So this should not affect too many users, anyway it's a serious bug.

**Comment by AndyScherzinger** [comment]
Some thinking and digging broad me to testdriving cookie clearing, see #2229 which leads to the correct expected results whenever to clear all cookies _before_ the next server call, seems the server's response resets the cookie state to a "wrong" one, so without clearing all follow-up server calls are wrong again.

**Comment by mahibi** [comment]
@jld3103 was able to reproduce this once! 
So we tried again but now fail to reprduce it another time...

Talk app version 15.1.0 Alpha 03
tested with 2 accounts on the same localhost

**Comment by mahibi** [comment]
never experienced this again. closing..
