### ISSUE TITLE
Incoming call design enhancements

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#223]
- The avatar when you get a call from someone else should be even bigger – and when you accepted it and it’s a voice call, the avatar should be exactly the same size (bigger than now)
- When you accept the call, it shouldn’t animate to the right but just morph the view (cause the buttons are basically the same) and replace the avatar with the video (or keep avatar, when it’s a video call)

(Copied over from https://github.com/nextcloud/talk-android/issues/200#issuecomment-400663647 )

**Comment by mario** [comment]
Thanks. Now please copy the new screen designs you had in some other repo xD

**Comment by jancborchardt** [comment]
The mockup discussion is in https://github.com/nextcloud/spreed/issues/1011

We settled on the middle version: larger picture, and picture doubled in blurry in the background:
![](![call](https://user-images.githubusercontent.com/925062/41923083-db5290e0-7966-11e8-810a-f3cb187f3e23.jpg))
With some dark fade on the top so the white text can be read. (Like fading rgba(50,50,50,.5) on the top to transparency further down.)

**Comment by mario** [comment]
This looks quite ugly.

![screenshot_20180729-104657_nextcloud talk](https://user-images.githubusercontent.com/5810/43364837-a3f75704-9322-11e8-91ab-ffe01ce7b61e.jpg)

**Comment by jancborchardt** [comment]
Well, of course it should only be done if there’s actually an avatar set. ;) For placeholders it does not make sense and we can keep the black background. Or if there’s a way to do that, fill the background with the background color of the avatar placeholder.

Also, it looks like the M in the background is stretched in height. We should not stretch the faces, but make them fill the screen (it's fine if the sides or top/bottom is cut off, it's blurred anyway).

**Comment by mario** [comment]
@jancborchardt you know we AFAIK can't know if there's an avatar set or not. Poking @nickvergessen, maybe he knows more about this.

You will have to clarify what you mean by "fill the screen".

**Comment by nickvergessen** [comment]
Not sure how you are getting the avatars atm. But in the web UI we query the URL and when it' 404 we create the FirstChar thingy.

**Comment by mario** [comment]
The letter avatar is generated and returned by the server if no avatar is
set. There is no 404 involved.

**Comment by mario** [comment]
or @skjnldsv

**Comment by mario** [comment]
Considering that as far as I know it's not possible to know if avatar is set, what do you want to do? Suggestions welcome @nickvergessen @skjnldsv

**Comment by nickvergessen** [comment]
We could make the api return 201 whe. It generated the letter image?

**Comment by mario** [comment]
@nickvergessen that would not be a bad idea.

**Comment by skjnldsv** [comment]
I'm not sure this will change anything since once it's generated, it will use the same functions than any saved avatar, right?
Couldn't we just add a new endpoint to return if the user have a custom avatar set?

**Comment by mario** [comment]
@skjnldsv ah due to caching. @skjnldsv this will cause additional network and processing load on mobile app which basically just wants to show the avatar as soon as possible.

**Comment by skjnldsv** [comment]
You could do that php-side and add this data in the call request?
That would be one request less to do ?

**Comment by mario** [comment]
Dunno. Not the server magician here.

**Comment by nickvergessen** [comment]
The file name is generated instead of avatar then. I will have a look tomorrow

**Comment by jospoortvliet** [comment]
Just a thought - there was a PR to auto-generate avatars on the server. Not merged but would come for 15, I suppose. Also, if the auto-generated avatar looks so bad how do we know users won't have an avatar that looks similarly bad? Not everyone uses a picture of themselves...

**Comment by mario** [comment]
That was for guests. We already generate avatar if it's not set :)

**Comment by mario** [comment]
Ok, so @nickvergessen did this awesome PR which will allow me to show background only if it's a custom avatar.

But the point from @jospoortvliet still stands - it could be a really, really bad thing.

**Comment by nickvergessen** [comment]
> Just a thought - there was a PR to auto-generate avatars on the server. Not merged but would come for 15, I suppose.

That is something we can tackle once the problem exists.

> Also, if the auto-generated avatar looks so bad how do we know users won't have an avatar that looks similarly bad?

Well you can't but we have to do a trade of at some point.

**Comment by mario** [comment]
Partly done for 3.0, the rest will be in 3.1.

**Comment by mario** [comment]
Done a while ago.
