### ISSUE TITLE
14.1.0: open conversation from notification: new messages are missing

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#2230]
## Steps to reproduce
1. tip on a notification
2. the conversation opens 
3. sometimes the new messages are missing
4. go back to conversation overview
5. open conversation again
6. new messages shown up

Tested on 2 different phones with 14.1.0

**Comment by mahibi** [comment]
could not reproduce this yet. 
maybe this is also fixed with https://github.com/nextcloud/talk-android/issues/2290#issuecomment-1214827631 ?
So does it still happen with 14.1.1?

**Comment by jakobroehrl** [comment]
I will test it the next days

**Comment by jakobroehrl** [comment]
It's still there with 14.1.1 sometimes.

**Comment by mahibi** [comment]
i could not reproduce this yet.
but i remember that recently sometimes the chat was not scrolled down to the newest messages after opening.
are you sure the messages were not there or might it be the scrolling bug?

**Comment by mahibi** [comment]
does this still happen for you with 15.x @jakobroehrl ?

**Comment by jakobroehrl** [comment]
Not sure, I will comment if I stumble upon
