### ISSUE TITLE
Feature request : add thin lines next to the date separators in text messages

### ISSUE THREAD

**Issue by GLLM** [nextcloud/talk-android#225]
Hi @mario !

For readability prupose, I suggest to add a very thin grey line on each side of the date separator ...
It makes the reading easier and is a visual cue when you look in your messages :+1: 
Example :
![image](https://user-images.githubusercontent.com/3989573/42228413-2d034736-7ee4-11e8-9131-ed29e9fa182f.png)

Thanks :)

**Comment by mario** [comment]
@GLLM like I mentioned in the previous ticket where you suggested this, I really don't see a way this increases readability and just clutters the screen :(

Sorry! :(

**Comment by mario** [comment]
You got everything else though! :D

**Comment by mario** [comment]
You're welcome, and thanks for helping make the overall experience better!

**Comment by jancborchardt** [comment]
Much better than a line divider is to have proper whitespace. :) It’s less visual clutter and a better separation.
