### ISSUE TITLE
Escaping, e.g. newline and apostrophes preceded by backslash

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#226]
In a conversation I wrote `"Something"` and it is now displayed as `\"Something\"`, with the apostrophe being preceded by backslash.

Similarly, something the other person sent through their mobile app and pressed enter in the message is shown with a `\n` instead of an actual new line.

Happening with current cloud.nc @mario

**Comment by mario** [comment]
Discussed this via Talk. Probably an issue @jospoortvliet had if he used beta3 :)

Will let @jancborchardt close after confirmation.

**Comment by mario** [comment]
Closing as it really works :)

**Comment by Elfanar** [comment]
Got same issue, NC 15 and Talk 5.0.2
