### ISSUE TITLE
No back icon in title when clicking on mention notification

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#227]
When you click on a mention notification, there's no back button icon shown left of the converswtion name to go back to the conversation list. Should of course be there. :) 

v2.1.0beta4

**Comment by mario** [comment]
I tested this earlier and it worked, but I'll look into it again.

**Comment by mario** [comment]
@jancborchardt do you experience this with 3.0 still? I don't have an Android 6.x or lower with Play Services so I can't really test it atm.

**Comment by mario** [comment]
@jancborchardt  please respond :)

**Comment by jancborchardt** [comment]
@mario sorry – send me some messages on Talk and I will be able to test, have Talk 3.1.1 on Android 5.1

**Comment by jancborchardt** [comment]
Could still reproduce:
![talk app header without back from notification](https://user-images.githubusercontent.com/925062/49451827-4fe5df00-f7e0-11e8-895f-250c3a1bb018.png)

It shows the arrow when switching out of the app and back in.

**Comment by mario** [comment]
Will be fixed by #360
