### ISSUE TITLE
Push test notification don't show on app

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#2284]
## Steps to reproduce
1.send push test via sever occ
2.says successful 
3 never comes to android talk

### Expected behaviour
Should get a push test notification 

### Actual behaviour
Don't get push test notifications

Notifications via users do work just the push test that don't work calls and test via other users do 

## Device information

**Device:** Fairphone2/…
SM-G996U1 
**Android version:** 10/…
12
**Talk version:** 11.0.0
14.1.1 RC1
## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)
24.0.3
**Talk version:** (see apps admin page: `/index.php/settings/apps`)
14.0.3
**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
No
**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`)
Yes
**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`)
Yes
### Server log (data/nextcloud.log)
<details>

```
No Logs
```
</details>

**Comment by AlvaroBrey** [comment]
What is the command you're using? For Talk you need to be using `php occ notification:test-push --talk <userid>`. Note the `--talk`, it's needed.

**Comment by andyxheli** [comment]
Hi @AlvaroBrey here the command im using. 

root@nextcloud:~# sudo -u www-data php /var/www/nextcloud/occ notification:test-push --talk pushtest
Trying to push to 3 devices

Language is set to en
Private user key size: 1704
Public user key size: 451
Identified 1 Talk devices and 2 others.

Device token:1526
Device token is valid
Device public key size: 451
Data to encrypt is: {"nid":2925,"app":"admin_notification_talk","subject":"Testing push notifications","type":"admin_notifications","id":"62f39fe1"}
Signed encrypted push subject
Push notification sent successfully

**Comment by andyxheli** [comment]
Here a DB output that 1526 is the Android Talk.
1526 | axheli | axheli     |    1660128739 | 1660128739 | 93324438               | Samsung SM-G996U1 (Nextcloud Talk)

**Comment by andyxheli** [comment]
@mahibi wouos this be the same as #2112

**Comment by timkrueger** [comment]
It's working as intended. The test notification is not shown on your device. From our [notifications guide](https://github.com/nextcloud/talk-android/blob/master/docs/notifications.md#-check-server-settings):

>... Note that there won't be any notification on the phone as this is just a test-message which won't be handled (As a developer you could set a breakpoint in the "onMessageReceived"-method of the Firebase cloud messaging handling to check if the notification is received).
