### ISSUE TITLE
🤖1️⃣3️⃣ Migration to Android 13

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#2299]
this issue should collect all tasks that are needed to migrate to Android 13.

# docs
* https://developer.android.com/about/versions/13/migration
* https://developer.android.com/about/versions/13/behavior-changes-13

## especially
* https://developer.android.com/about/versions/13/behavior-changes-13#nearby-wifi-devices-permission
* https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

**Comment by mahibi** [comment]
Starting August 31, 2023: New apps and app updates must target API level 33 to be submitted to Google Play
https://support.google.com/googleplay/android-developer/answer/11926878

**Comment by AndyScherzinger** [comment]
@mahibi moved it to #2879 for tracking

**Comment by AndyScherzinger** [comment]
@mahibi how about just bumping it to 13 on master for the moment? I ran it here an there on my phone already. Didn't have any issues so far but that might depend on scenarios like fresh installations, etc.

**Comment by AndyScherzinger** [comment]
Well I actually just bumped the compileSDK not the targetSDK...
