### ISSUE TITLE
Quick reply via notification

### ISSUE THREAD

**Issue by GLLM** [nextcloud/talk-android#230]
Hi !

I'd be really happy if, from the notification itself, I'm could 
* reply to the last message
* mark the message as read
(i.e. without leaving the notification zone)

The usual suspect, Signal & Whatsapp, do this and this is a feature I use *_a lot_* !

Suprisingly, I could not find an existing issue for this !
Thanks
GLLM

**Comment by mario** [comment]
Reply could happen eventually, but mark as read is not possible since it works differently than general apps.

Messages are marked as read even if they're not really read when we pull for new messages. So again, a server issue.

**Comment by GLLM** [comment]
@mario  : OK no worries. 

Reply : cool ! I really like this feature when I get it !
Mark as read would have served as : remove the notif. BU ti understand your point

GLLM

**Comment by mario** [comment]
Moving to v3.3 (sorry @icewind1991) since I'll do a lot of notifications-related stuff in that version.
