### ISSUE TITLE
The ability to change the themes default colour.

### ISSUE THREAD

**Issue by MRFU510N88** [nextcloud/talk-android#2301]
The nextcloud app currently syncs the servers theme colour however talk does not do this and remains the default blue.

Currently we have the ability to to enable dark mode which is great. To change the default colour from say blue to purple would be a great addition for both the app and notifications.

A colour picker to change this would be useful for customisation.

**Comment by AndyScherzinger** [comment]
Talk will support the server side theme beginning with Android App 15.0.0 (October) for that reason we would not implement dynamic client side theming except material you which might come later, rather next year.

**Comment by MRFU510N88** [comment]
Thats good news, thankyou.
