### ISSUE TITLE
Blurry photos of Recipient on main screen

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#2302]
### Steps to reproduce

The pictures of the users looks blurry under the main screen. I opened talk on ios and user pictures are clear just seem too be an issue on Talk Android 

### Expected behaviour

Should be clear 

### Actual behaviour

Blurry images 

### Device brand and model

SM-G996U1 

### Android version

12

### Nextcloud Talk app version

14.1.1 RC1

### Nextcloud server version

24.0.4

### Talk version

14.1.4

### Custom Signaling server configured

No

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

### Additional information

Android App 

![Screenshot_20220814-112101_Talk](https://user-images.githubusercontent.com/59488153/184545991-8b911191-55b0-479f-8442-38ab0bbe890c.jpg)

IOS App![22-08-14 11-27-01 0020.png](https://user-images.githubusercontent.com/59488153/184546167-bdc39665-8a9f-4a90-adf1-2742093fc865.png)

**Comment by AndyScherzinger** [comment]
@Ivansss I guess you load the high-res version and @mahibi @timkrueger Android uses the low-res? (with v24 there are only 2 sizes available low/high).

**Comment by timkrueger** [comment]
> Android uses the low-res?

That's correct. Currently `64px` version will be loaded. I'll change that to the better resolution (`512px`).

**Comment by andyxheli** [comment]
Still an issue :( #2306 is not part of 14.2.0 i see #2305 on there but that pull request had issue from what I remember.
