### ISSUE TITLE
Problems with high frequent message exchange

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [nextcloud/talk-android#2309]
### Steps to reproduce

1. Activate Talk
2. Use Talk on Android and another person talk at web browser
3. Person from web browser and adroid app chat with each other and keep the apps open with breaks > 5 mins
4. Alot of messages sending between each other, sometimes also simultaniouse
5. Messages sometimes not displayed automatically in the talk app ==> Manual Reload nessesary

### Expected behaviour

As soon as message is sent, it should automatically pop up at the android app.

### Actual behaviour

Messages pops up sometimes sometimes not.
I suggest multiple messages over more then 1 h with high fequence.
Also sending of messages from both ends at the same time.
to reproduce.

### Device brand and model

Note 1ß Plus, Z Fold 2 

### Android version

12

### Nextcloud Talk app version

14.1.1

### Nextcloud server version

24.0.4

### Talk version

14.0.4

### Custom Signaling server configured

No

### Custom TURN server configured

No

### Custom STUN server configured

No

### Android logs

There is no error messages. 
Logs cannot be found on my android device.

### Server log

```bash
No error messages from the server side.
It works if all users use the web version.
```

### Additional information

Happens also sometimes at iphone app.
With a Debug Mode at the android app, things could get more easy ^^

**Comment by mahibi** [comment]
should be fixed since offline support.
