### ISSUE TITLE
Use avatar of person as notification icon

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#231]
Currently it's a generic speech bubble icon when someone mentions you or invited you to a conversation (or calls you).

Much nicer would be to use the person's avatar. Or when it's a group conversation, the group icon (as soon as we have that).

**Comment by mario** [comment]
Needs https://github.com/nextcloud/spreed/issues/1001 or a different way to fetch room by id ;)

**Comment by mario** [comment]
I wonder if we should bother with this part after all. I mean - First I need to fetch the room, then I need to fetch the image, and only after that I can show the notification :(

Not sure this is a very nice thing to do @jancborchardt .

**Comment by jancborchardt** [comment]
> I wonder if we should bother with this part after all. I mean - First I need to fetch the room, then I need to fetch the image, and only after that I can show the notification :(
> 
> Not sure this is a very nice thing to do 

Let’s separate UX and implementation detail. ;) Just because it’s a bit of work to make it happen does not mean it’s not a nice thing to add.

In fact, all other messengers do show the avatars of the person or group. So we should of course do that too.

**Comment by jancborchardt** [comment]
Ah ok. But then still I would ask _why_ it takes so much time. When we get a notification, it’s from a conversation which is most probably already in the app, so the avatars of the participants should already be cached.

And even then, it’s technical details. ;) People expect to get a notification immediately, with the avatar and the message.

**Comment by mario** [comment]
It's not about the avatars being cached (their network requests indeed are, via ETags). Conversations themselves are cached, but not in a way you'd expect (so I can't access them) at least not until we introduce a database. So yea..

Can you show me screenshots of notifications from "other" apps you mention?

**Comment by jancborchardt** [comment]
> Can you show me screenshots of notifications from "other" apps you mention?

You do use other apps like Signal and WhatsApp for testing and research too, no? ;)

Both WhatsApp and Signal always show name, message, and avatar directly. (Additionally they have a direct "Reply" function and Signal also has "Mark as read", but that’s a separate thing.)
![signal-attachment-2018-07-19-181233](https://user-images.githubusercontent.com/925062/42956260-d16a7d60-8b7f-11e8-85c3-e74c95cb7c60.png)
![screenshot_20180719-180650](https://user-images.githubusercontent.com/925062/42956263-d1ec6b5e-8b7f-11e8-9c92-11aba4e79486.png)

This is how a Nextcloud Talk notification looks like – it’s basically a notification about a notification, and can be much more informative (showing name, message, avatar and direct inline reply action like others):
![screenshot_20180719-181054](https://user-images.githubusercontent.com/925062/42956261-d198e13c-8b7f-11e8-900e-bb0f6375c529.png)

Also cc @Ivansss because the same issue exists with the iOS app.

**Comment by mario** [comment]
Mark as read is not possible at all. There's an issue for reply later on.

Missing messages and avatars are a matter of technical details and UX that we can provide right now.

Just for curiosity - what would you show for group/public chats UNTIL we even have a proper avatar endpoint for that?

**Comment by jancborchardt** [comment]
> Missing messages and avatars are a matter of technical details and UX that we can provide right now.

(I assume you meant to say "we _can’t_ provide right now"?) And this is exactly why this issue is open.

> Just for curiosity - what would you show for group/public chats UNTIL we even have a proper avatar endpoint for that?

The avatar and name of the person wo mentioned you in this group. Could be adjusted to intead of just the name in the first line to say:

> Morris in Company call
> Hey Jan blabla something

**Comment by mario** [comment]
File issues to the Spreed/Talk app if you haven't already please.

**Comment by jancborchardt** [comment]
@mario as apparently there’s a lot of technical stuff involved here, I don’t exactly know what I would need to write in there. It seems best if you just file it and have all the needed technical info in there already. Feel free to use the screenshots I took for illustration, and quote what I said.
