### ISSUE TITLE
14.1.1: Can't leave a call

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#2311]
I have to kill the app. tipping on the red button does not work:
![grafik](https://user-images.githubusercontent.com/24530680/185307853-7a570fd1-7437-45ea-8e40-f0cab60b21a3.png)

**Comment by AlvaroBrey** [comment]
I can't reproduce this; some more information is needed.

* Is this with a particular call or with any call?
* What is your Android version?

**Comment by jakobroehrl** [comment]
It's on every 10th Call maybe.
I had it on 2 smartphones with Android 12

**Comment by jakobroehrl** [comment]
Works good with the latest version.
