### ISSUE TITLE
salutation wrong

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/talk-android#2317]
### Steps to reproduce

1. Nextcloud Settings Language: German (Du)
2. Open the Android Talk app
3. See the bug in the chat overview

### Expected behaviour

Message should appear as follows:
Du: message I sent

### Actual behaviour

Messages I send are displayed as follows:
Sie: message I sent

### Device brand and model

Realme RMX3085

### Android version

12

### Nextcloud Talk app version

3.20.3

### Nextcloud server version

24.0.3

### Additional information

The display is correct in the browser.  Depending on the setting, Sie or Du will be displayed

**Comment by AndyScherzinger** [comment]
The clients only have formal German by design and the client language in general depends on the devices language.

**Comment by R7JANV1** [comment]
> The clients only have formal German by design and the client language in general depends on the devices language. 

Wouldn't it make sense to change this?  and unify in the apps and in the browser?

**Comment by AndyScherzinger** [comment]
It is a operating system restriction. Android doesn't distinguish between formal and informal German. So we have to decide which translated strings to copy into app and decided to use the formal language.

**Comment by R7JANV1** [comment]
Is there a possibility that the app queries the settings of the Nextcloud account on the server and accordingly decides which language is used formally or not?

**Comment by AndyScherzinger** [comment]
That is not possible, the language is chosen by your phone (its settings) and again we can only ship one German translation - the server and its settings has no impact at all on the language on your phone.
