### ISSUE TITLE
Notifications don't work with AD autorization

### ISSUE THREAD

**Issue by Mario116** [nextcloud/talk-android#232]
After enabling AD authorizations notifications have stopped working in talk-android. In chromium notifications works correctly. Even between created users (not imported from AD) notifications do not come

**Comment by mario** [comment]
What version of Nextcloud, what version of the server Talk app, what version of the mobile app?

**Comment by mario** [comment]
@Mario116 do you have a Talk subscription as a company? If so, open a support ticket in the portal and send me a test account there.

**Comment by Mario116** [comment]
No, we do not have a subscription yet. We are testing the product for now

**Comment by mario** [comment]
@Mario116 through an account manager? If so, get them a test account and tell them to forward it to me :)

**Comment by Mario116** [comment]
@mario we sent you a letter with a test account. You received it?

**Comment by Mario116** [comment]
If you do not have the opportunity to connect to us and check, tell us where you can see and understand the problem

**Comment by mario** [comment]
Hi, I just tested this and push registration works like a charm.

**Comment by Mario116** [comment]
Hello.
Notifications are still not working.

Install a clean NC.
Installing Notifications
Installing Nextcloud Talk
Notifications are still working

I add authorization through AD - notifications stop working.
Turning off authorization through AD - does not help, notifications still do not work. At the same time through the browser - everything works. Tried and turned on and off TURN and STUN - Notifications in Nextcloud Talk Android (on samsung, asus, ipad, iphone and over devices) do not work.

**Comment by mario** [comment]
Hi @Mario116,

I am sorry that this is not working for you. Since AD is not officially supported by the Talk Android app just yet, it might happen that something doesn't work.

If you'd like us to look into this, please contact sales@nextcloud.com and they'll arrange for something with you.

Thanks,
Mario
