### ISSUE TITLE
User status dialog is squeezed when typing status message

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#2325]
### Steps to reproduce

1. Open the user status menu
2. Tab into the input so you can type a message

### Expected behaviour

✨  and you can see what you type

### Actual behaviour

Predefined statuses disappear and the input is so small that it becomes scrollable and you can't see what you type

<img width="300" src="https://user-images.githubusercontent.com/213943/186093275-8be2728f-486e-4f7c-9dff-63684dbc5532.jpg" />

### Device brand and model

Redmi Note 8 Pro

### Android version

11

### Nextcloud Talk app version

15.0.0 Alpha 02

### Nextcloud server version

24.0.3

### Talk version

14.0.3

### Custom Signaling server configured

Yes (specify version in Additional Information)

### Custom TURN server configured

Yes

### Custom STUN server configured

No

**Comment by mahibi** [comment]
could not reproduce this yet.
does this happen also for the set-status dialog on android files app on this phone?

**Comment by nickvergessen** [comment]
No, the files app scrolls the the list of predefined statuses and has way less padding

Files | Talk
---|---
![Screenshot_2022-09-01-10-23-23-866_com nextcloud client](https://user-images.githubusercontent.com/213943/187868606-37f4df95-3b5c-48d8-833f-d206200deb73.jpg) | ![Screenshot_2022-09-01-10-23-39-152_com nextcloud talk2](https://user-images.githubusercontent.com/213943/187868604-b83cd242-222b-4ff5-83a0-b14300b75cc0.jpg)

**Comment by AndyScherzinger** [comment]
Funky, for me in the emulator and on the phone the keyboard always hovers on top and the dialog isn't shrinked, Google keyboard as well as swiftkey.

**Comment by mahibi** [comment]
As said, there were discussions in the design review to make this screen a normal screen instead a dialog. So this **could** also fix the issue for the devices where it happens.
