### ISSUE TITLE
save shared files

### ISSUE THREAD

**Issue by tigermick** [nextcloud/talk-android#2331]
Talk is a great app to talk with other users on nextcloud but i think one feature is missing when you share files.
You can show a picture for example but if you want to save its, this is hard ...
You just can share its ...

**Describe the solution you'd like**
Can you add an option below "share" in menu to save file ?

Maybe necessary to add a setting to have a default folder to save files in nextcloud setting too.

**Comment by timkrueger** [comment]
With the share sheet it is already possible to save files shared in a conversation. If you want to save them in your Nextcloud, NC Files for Android must be installed.

Beside that all with you shared files are accessible in the `/Talk` directory in the users directory.

**Comment by tigermick** [comment]
I know another solution is possible to save shared file like with nextcloud app in talk folder ... But it's just simplier et quicker to have "save" option when you preview file in talk, isn't it ?

**Comment by timkrueger** [comment]
Currently the workflow to save something into your Nextcloud is:

```
View file in full-screen -> select share -> select Nextcloud Files (or other target app) -> select target folder
```

With a specific `save` (to Nextcloud) it looks like that:
 
```
View file in full-screen -> select share  -> select target folder
```

One interaction will be removed with this change. But for that we must change the scope of the Talk app into the direction of file management. But in my view that is the domain of the Files app.

**Comment by mahibi** [comment]
i guess you want a save button next to the share button? @tigermick 
So in whatsapp there is this save button which saves the file to the public visible folder of the app so it also appears in the systems gallery app.

**Comment by tigermick** [comment]
@mahibi  You could have something like this : 
![Screenshot_20220904-233512_Talk](https://user-images.githubusercontent.com/15263539/188334626-8f5c7826-232a-4b0f-8ce1-298fc0b9e8ab.png)
With this choice, default file browser open to prompt user to choice a path to download a picture for example on his phone.
Currently, I use this application : https://f-droid.org/fr/packages/xyz.myachin.saveto/ to have possibility to save a file in my phone if i don't want go to look for in talk folder in nextcloud android app.

**Comment by mahibi** [comment]
i like this, but might needs to be discussed if we want this, especially privacy-wise. cc @AndyScherzinger 
The main purpose of people using this will be that other apps can access the files (see https://developer.android.com/training/data-storage/shared). However other users want to avoid that data is accessible to other apps and may not understand the impact of this feature. So at least there should be some hint with a privacy warning.

**Comment by gerbrent** [comment]
I was just searching for this function today without any luck.
My use case: save a file from a conversation for long-term archiving.

Rational for expecting it: Every other arguably privacy-conscious app in this space I've used has implemented a save feature (Signal, SimpleX, Element) despite some also having the above hesitation (i.e. Signal in it's infancy..)

> other users want to avoid that data is accessible to other apps and may not understand the impact of this feature

My thought process immediately upon not finding a save feature was "how can I game the share feature to accomplish what I want - that is save the file to local storage for backing up? The answer of this workaround then becomes: use the share function to share it with literally any other app installed on my phone that can handle this file type, whether privacy-conscious or not. Then save from there.

So, I'm not sure the lack of a save function is preventing privacy leaks. Arguably it may even be increasing privacy leaks..

So, there is my humble argument why a save feature would be a wonderful UX addition..

**Comment by gerbrent** [comment]
If implemented, should consider also adding the functionality to the long-click menu:

![image](https://github.com/nextcloud/talk-android/assets/7018928/b9b1a1c9-fe5e-4c47-b0ff-5e4ed56c9bfa)

**Comment by gerbrent** [comment]
An example of a privacy-conscious warning message in Signal when saving a photo to local storage:

![Screenshot_20230826-173843_Signal](https://github.com/nextcloud/talk-android/assets/7018928/819096b7-2eda-4772-9b46-6af7bf7bf3d0)

**Comment by gerbrent** [comment]
🎉
