### ISSUE TITLE
 @JsonField annotation can only be used on private fields if both getter and setter are present.

### ISSUE THREAD

**Issue by mhmttaa** [nextcloud/talk-android#2340]
### Steps to reproduce

It doesn't give any error while building the project, but when I run it, it's for many classes.
  @JsonField annotation can only be used on private fields if both getter and setter are present.
it gives this error.

### Expected behaviour

It should be able to run without error

### Actual behaviour

gives error in model classes

### Device brand and model

Android Emulator

### Android version

30

### Nextcloud Talk app version

14.2.0

**Comment by mahibi** [comment]
Not sure yet whats going wrong.
did you try to 
1. clean the project ("Build - Clean Project")
and
2. "Sync project with gradle files"
?

**Comment by mhmttaa** [comment]
I found the cause of the problem. Error occurs due to values such as "id", "icon" due to the language of the computer.
I changed the language to English, problem solved.
