### ISSUE TITLE
Make Reader check marks smaller

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#2362]
It would be nice to have the read check mark smaller. Something similar to  Whatsapp 

![image](https://user-images.githubusercontent.com/59488153/189702656-aae3fb52-85bd-4d04-af25-5acd65181afc.png)

**Comment by AndyScherzinger** [comment]
@nextcloud/designers @nickvergessen @mahibi what do you think? (sidenote original issue's screenshot is iOS)

|Before(24dp)|After(18dp)|
|---|---|
|<img width="540" alt="before" src="https://user-images.githubusercontent.com/1315170/189719331-4bbb3e53-ad62-42f2-b1e0-281e0516be71.png">|<img width="540" alt="after" src="https://user-images.githubusercontent.com/1315170/189719351-bf1d4f1d-96ab-4074-853d-5e42c8030e4c.png">|

**Sidenote**
`18dp` is the min-size for icons to be used in general

**Comment by mahibi** [comment]
i prefer 18dp :+1:

**Comment by andyxheli** [comment]
@AndyScherzinger first thank you so much for looking into this:) second what do you think about making the text box have less gap on the bottom and top like in the image?

**Comment by AndyScherzinger** [comment]
> second what do you think about making the text box have less gap on the bottom and top like in the image?

Not sure what you mean but I guess "maybe?" because it collides with the material 3 corner radius a bit, so some spacing might be able to be taken away but not that much since the WhatsApps UI is old-ish and not very material3-like.

**Comment by andyxheli** [comment]
Sorry for not giving an good example. 

Please see the below image how's there's less of a gap between the words and the edges  of the text box ![Screenshot_20220912-172407_Messages.jpg](https://user-images.githubusercontent.com/59488153/189773992-5e7c65bb-1e45-4251-bdcd-e01984fe250e.jpg)

**Comment by AndyScherzinger** [comment]
@andyxheli see #2364 for potential change based on the feedback
