### ISSUE TITLE
Notifications are on /loud even if phone is muted/vibration

### ISSUE THREAD

**Issue by Bolli84** [nextcloud/talk-android#238]
On my Phone, once I set up the notification, it is ringing even it the normal android notification is muted or on vibration

Android 8.0
Talk-Version Beta 5

**Comment by mario** [comment]
Currently expected behaviour. I'll work on it eventually to respect system sound settings.

**Comment by jancborchardt** [comment]
Marking as high because not honoring this is at best annoying and at worst quite embarassing in meetings or the cinema etc.

**Comment by mario** [comment]
I agree @jancborchardt and @Bolli84 - so this will be in the next big stable release.
