### ISSUE TITLE
Offline Mode for Talk-Android

### ISSUE THREAD

**Issue by DineshRefex** [nextcloud/talk-android#2385]
Hello there, Offline mode is available in Nextcloud-Files/Android but why it is not in Talk/Android. 

Talk/Android takes heavy load for refreshing only because there is no offline mode. But it does not happen in Files/Android app.
Even though I tried to modify it , some of the files being in Read-only format I could not modify it . 

Several times I have raised this issue but without giving any proper answer you are closing it as completed. If seriously this issue has been completed why I am going to raise this issue ? 

My feature request is simple , Offline mode is available in Files , Why not it can be in Talk/Android.

Again a kind request , please give a clear solution for this issue !

**Comment by mahibi** [comment]
Dear @DineshRefex,
we are aware that the missing offline support is a problem. It's implementation is a major goal, however this needs HUGE changes. As this implementation needs architectural planning and it's implementation is not easy, this won't be solved in the very near future. 

> But it does not happen in Files/Android app

The files android app has a completely different codebase, so it can't be compared to the talk app.

> Several times I have raised this issue but without giving any proper answer you are closing it as completed. If seriously this issue has been completed why I am going to raise this issue ?

It is not completed. We are not closing it at as completed, we are closing it as a duplicate feature request of https://github.com/nextcloud/talk-android/issues/217 . If you have any more question regarding offline support, just ask there..

Thanks for your interest to improve the talk app :+1: :+1:  If you would like to improve it with coding, it would make sense to start with other issues (just let us know if you need help there). 

Kind regards, Marcel
