### ISSUE TITLE
Cannot login with app token

### ISSUE THREAD

**Issue by oparoz** [nextcloud/talk-android#24]
Tested on our cloud.
Got message that app was not installed on the server
Had to start from scratch, the app did not remember my token.

**Comment by mario** [comment]
Of course not. How is this a bug? If the server doesn't support Talk, why would I keep the account?

**Comment by oparoz** [comment]
The server supports Talk

**Comment by oparoz** [comment]
But I agree, if the app detects that the server doesn't support it, then there is no point keeping the account's data.

**Comment by mario** [comment]
Not the right version, otherwise this would most definitely work? Glad we agree though :P

**Comment by oparoz** [comment]
> Not the right version, otherwise this would most definitely work? 

What do you mean? We're on 13, using Talk for 13.

**Comment by mario** [comment]
@oparoz I mean that I just triple checked with our cloud and it works.

**Comment by oparoz** [comment]
Just tried again and it worked 👍 . Could have been a typo in the token. Would be good to have more granularity in the error messages if possible :)

**Comment by mario** [comment]
You login with your password and the app generates a token for you :)
