### ISSUE TITLE
Talk app does not honor Do Not Disturb mode

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#240]
I’m pretty much in Do Not Disturb the whole time. All apps honor this, but when I get an incoming call in the Talk app, it rings including sound.

This is also the case when I’m only on vibrate. In which case it’s also with sound, but never vibrates.

cc @mario

**Comment by mario** [comment]
This is also not a bug, but something similar was reported in https://github.com/nextcloud/talk-android/issues/238 so I'll definitely take a look eventually.

**Comment by jancborchardt** [comment]
Closing in favor of https://github.com/nextcloud/talk-android/issues/238 then and marking as high because we should absolutely honor do not disturb.
