### ISSUE TITLE
Themed icon

### ISSUE THREAD

**Issue by neunzehnachtneun** [nextcloud/talk-android#2407]
**Is your feature request related to a problem? Please describe.**
Android 13 was released a few weeks ago. Icons should follow Material You since then.

**Describe the solution you'd like**
Support material icon, see: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive
The nextcloud apps notes and deck already support this feature I think it would be great if talk would support it too.

**Comment by tobiasKaminsky** [comment]
For branding I would simply disable it, until someone wants to have it.

**Comment by AndyScherzinger** [comment]
Good idea, it is probably hard to implement for complex-colored launcher icons 👍
