### ISSUE TITLE
When sending message, directly animate message to show in list

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#241]
When you send a message there’s some strange seconds between hitting "Send" and seeing the message in the list. There’s no feedback what happened to the message and if it’s a longer one you are worried if it’s really getting sent or saved.

Instead it should directly be animated (like in Viber) or just show directly in the list (like in Signal).

**Comment by mario** [comment]
This is because the message is shown in the list only when server receives it. Anyway, the behaviour will be changed once we support database storage etc etc.

**Comment by jancborchardt** [comment]
> This is because the message is shown in the list only when server receives it.


Yes, that’s what I thought. However we don’t need to have the UI mirror the server 1-by-1, we need to "fake" certain things to improve the user experience. And this is one of them.

**Comment by ardevd** [comment]
I agree with this one.

One of the main usability issues I have with the android app is the fact that sent messages are not shown until they've seemingly been synced with the server. The end user experience becomes a bit slow and sluggish compared to other messaging apps. 

I would recommend showing sent messages immediately and have some sort of visual indicator on the state of the message (sending/sent/error, etc).

**Comment by mario** [comment]
Fixed in v9.0 if you're running Nc 19.
