### ISSUE TITLE
Server not supported

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2418]
### Steps to reproduce

1. login at server with app 

### Expected behaviour

app starts, conversations loaded

### Actual behaviour
happens very unregulary:

error in UI: "Unsupported Server (The server version is too old.....)"

i debugged and saw that the capabilities of the user are `null` when checking for `hasSpreedFeatureCapability`:

```
hasSpreedFeatureCapability:56, CapabilitiesUtilNew (com.nextcloud.talk.utils.database.user)
isServerEOL:42, CapabilitiesUtilNew (com.nextcloud.talk.utils.database.user)
onAttach:266, ConversationsListController (com.nextcloud.talk.controllers)
```

maybe this is somehow related to https://github.com/nextcloud/talk-android/issues/2322 (although i wonder why no "Unsupported Server" error is shown there..)

### Device brand and model

Pixel XL

### Android version

13

### Nextcloud Talk app version

15.1.0 Alpha 02

### Nextcloud server version

25.0.0 beta 7 (sermo)

**Comment by migulen** [comment]
Hi @mahibi , same happened to me on v15.0.0-RC1, 5 or 6 times when i was connected to a special Wifi net (extremelly firewalled and with low bandwith) and I was trying to new logon 2 accounts of my nextcloud servers.

After trying several times with the prior scenario,  I changed to me mobile net connection, 4G, and the problems gone... So I thought the problem was from "bandwith" or "the hard firewall" of that Wifi net. But I'm not sure. I'm going to try another time at the same Wifi net to see if it happens like before.  

I'll tell you something.

------------------------------------------

**Device brand and model**

Xiaomi Mi 9

**Android version**

12

**Nextcloud Talk app version**

15.0.0-RC1

**Nextcloud server version**

23.0.8

**Talk version**

13.0.8

**Custom Signaling server configured**

No response

**Custom TURN server configured**

Yes

**Custom STUN server configured**

Yes

**Android logs**

No response

**Server log**

No response

**Additional information**

No response

**Comment by mahibi** [comment]
thanks for testing and reporting @migulen 

i guess there is something failing in UserManager (maybe depending on the quality of the internet connection).
Maybe @AndyScherzinger / @AlvaroBrey have any ideas here?

**Comment by AndyScherzinger** [comment]
No clues unfortunately. In case of capabilities being null we could still say we default to "supported version" assuming the best case instead of the worst case.

**Comment by mahibi** [comment]
but with capabilities being null it would crash everywhere. Or do you somehow hope they are set after the `isServerEOL` check?

It would be possible to change every method in `CapabilitiesUtilNew` to return true as default in case no capabilities are found. But even then there would be many crashes where some features are not supported by servers and it would get more complicated to identify why something failed.

So if we don't find the root cause yet i guess it makes sense to check on app start (before checking isServerEOL) if capabilities are set and otherwise show this as an error dialog (because we have no log reporting yet) to get an overview of how many users are affected?

**Comment by AlvaroBrey** [comment]
After some debugging, the normal flow of the login should look like this:

1. `AccountVerificationController` stores the user profile with `capabilities=null` [here](https://github.com/nextcloud/talk-android/blob/57fe34c14ab6e77818c939a36b3ede146c945dc9/app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt#L251-L251)
2. Immediately afterwards, or after the push registration, the same controller [fetches and stores the capabilities](https://github.com/nextcloud/talk-android/blob/57fe34c14ab6e77818c939a36b3ede146c945dc9/app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt#L284-L284). The worker that does the fetching [checks the capabilities are not `null`](https://github.com/nextcloud/talk-android/blob/57fe34c14ab6e77818c939a36b3ede146c945dc9/app/src/main/java/com/nextcloud/talk/jobs/CapabilitiesWorker.java#L80-L80)
3. The verification process only continues [if the capabilities are fetched and stored correctly](https://github.com/nextcloud/talk-android/blob/57fe34c14ab6e77818c939a36b3ede146c945dc9/app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt#L396-L396)

So in theory, there doesn't seem to be a way for a user with `capabilities == null` to reach  `ConversationsListController`. So unless we find a way to reproduce this, I am stuck.

**Comment by mahibi** [comment]
i give up for today.
Studied the code and debugged a lot with lower bandwidth (via Throttly) but can't reproduce it...

maybe there are scenarios where the `ConversationsListController` is opened without that a `CapabilitiesWorker` was executed beforehand?! But don't know how this could happen.

**Comment by mahibi** [comment]
@migulen this should be fixed with 15.0.1 which is already available. If the issue still appears sometimes, please let us know

**Comment by migulen** [comment]
Hi @mahibi, I've seen one situation were shows "Server not supported". But I think it's normal... but confusing. When a user isn't on a group that has been enabled (on the spreed admin options) to use "Spreed app", it shows "Server not supported". Could not be better indicating something like: "Server not supported, or your user/group is not allowed to use Spreed in this server". That phrase if you can't difference between a no supported version, of not allowed user to use spreed. 

The above first time (https://github.com/nextcloud/talk-android/issues/2418#issuecomment-1273675117) it happened to me,  this was not the case ;-).

**Comment by mahibi** [comment]
Currently the info is "Nextcloud Talk app not installed on the server, aborting" right @migulen ?

There is no possibility to differentiate between "not installed" and "not allowed", so yes, the info must be given in the same text..
What about "Nextcloud Talk app not available (not installed or restricted by admin)"

**Comment by migulen** [comment]
@mahibi . Nice it's working in QA (https://github.com/nextcloud/talk-android/pull/2581) :-)

![imagen](https://user-images.githubusercontent.com/60242624/203181840-ff242845-5e27-4bd1-b27e-438b4ad725cc.png)
