### ISSUE TITLE
Set Ringtown & notification sounds  to phones defaults 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-android#2422]
Hi All,

What do you think about having the apps notifications and calls default to the phones sounds by default and the if anyone  wants to change it they can currently if you select the ringtown it plays the notification sound but not the actual ringtone of the phone or even if you change it ot only allows you to pick from notifications sounds. Let me know if this makes sense. I know on the ios iPhone it playes the default iPhone sounds.

**Comment by mahibi** [comment]
makes sense to me

**Comment by AndyXheli** [comment]
Hey @mahibi has this been implemented I though I sewn it under my app

**Comment by mahibi** [comment]
No this is not implemented.
Maybe the behaviour can be different depending on OS and manufacturer.
I remember i had a related problem https://github.com/nextcloud/talk-android/issues/2948#issuecomment-1630613446 where i didn't find a solution back then.

**Comment by AndyXheli** [comment]
Yea because on my samsung it selected my samsung default unless and did it a while back 😅  haha
