### ISSUE TITLE
Reactions are not shown

### ISSUE THREAD

**Issue by neunzehnachtneun** [nextcloud/talk-android#2432]
### Steps to reproduce

1. Update from 14.2.0 to 15.0.0 RC2
2. In any chat react to a message
3. See, that the reaction is not shown.

### Expected behaviour

Reactions to messages should be visible below the message.

### Actual behaviour

Reactions aren't shown. Via webclient they are visible, while they aren't in talk. 

This issue affects both sent and received messages as well as sent and received reactions.

### Device brand and model

Pixel 6a

### Android version

13

### Nextcloud Talk app version

15.0.0 RC2

**Comment by mahibi** [comment]
thanks for the report @neunzehnachtneun !
indeed this is broken somehow, we will have a look!
