### ISSUE TITLE
15.0.0 RC2 and RC3: direct video does not work (only on calyxOS?)

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#2447]
### Steps to reproduce

camara does not show up
nothing happens after I gave the permission

### Expected behaviour

camara popps up

### Actual behaviour

see above

### Device brand and model

Pixel 4a

### Android version

12

### Nextcloud Talk app version

15.0.0-rc.1

**Comment by mahibi** [comment]
does this only not work initially after granting the permission? (There should be a toast with the hint to open it another time)

So if you granted the permission and select another time to record a video directly, does it work or not?

**Comment by jakobroehrl** [comment]
On the first try the permission toast comes up, I gave all permissions on the talk app
But if I click on Video nothing happens

**Comment by mahibi** [comment]
can you try out the version from https://github.com/nextcloud/talk-android/pull/2450#issuecomment-1263398938 and see if there is a toast error message now with "sorry something went wrong"?

**Comment by mahibi** [comment]
but i guess you have some camera app installed actually, right? (if this was not the case the option to record a video should be hidden anyway. so no spontaneous idea what's going wrong, will have a look in the next days)

**Comment by mahibi** [comment]
and are you using some alternative android OS @jakobroehrl ?

**Comment by jakobroehrl** [comment]
I use calyxOS, sorry not mention it

**Comment by mahibi** [comment]
> I use calyxOS, sorry not mention it

ok, no idea what's going wrong but using calyxOS sounds suspicious to me to cause this.
maybe you could try any other app that should open the system camera with an intent and check if this also fails.

If this only happens on calyxOS i might not find time to have a closer look. As a workaround you could check to install other camera apps and see if they are opened by the intent?

**Comment by jakobroehrl** [comment]
Sorry, my fault. ;(
I had no standard cam app assigned. 
Now it works.

**Comment by mahibi** [comment]
glad it works for you now :+1:

**Comment by jakobroehrl** [comment]
It works not completely. 
The photo app starts, I can create the video but after I tip the stop button the video is not uploaded.
On other smartphones, it's working. Maybe it's only a calyxos problem

**Comment by mahibi** [comment]
ok thanks for the info. 
as mentioned i might not find the time to check whats going wrong on calyxOS..
once you reproduce this with any other OS please feel free to reopen!
