### ISSUE TITLE
AGP 7.3.0 not supported by IntelliJ 2022.2

### ISSUE THREAD

**Issue by jld3103** [nextcloud/talk-android#2454]
### Steps to reproduce

1. Open app code with IntelliJ 2022.2
2. `The project is using an incompatible version (AGP 7.3.0) of the Android Gradle plugin. Latest supported version is AGP 7.2.0` appears in the gradle logs

### Expected behaviour

The app should have a supported AGP version

### Actual behaviour

AGP 7.3.0 breaks building, 7.2.2 works

### Device brand and model

-

### Android version

-

### Nextcloud Talk app version

git master

### Additional information

https://github.com/nextcloud/talk-android/pull/2371 introduced this @AndyScherzinger @AlvaroBrey. I'm not sure why this happens because IntelliJ is always more up-to-date (2022.2 is the latest one, all plugins are up-to-date) than Android studio and nobody else complained about this yet, so this might be a weird case, but still worth fixing.

**Comment by AndyScherzinger** [comment]
New AGP releases are bound to Android Studio releases, which also ship a compatible and targeting JDK version, so I would expect that this is more than just the pair of IntelliJ and AGP, so there are no reports because I would expect most people to just run Android Studio as published by Google.

**Comment by AlvaroBrey** [comment]
This looks like it should be opened in some sort of IntelliJ or Google tracker; AGP compatibility with IntelliJ is not an issue of the Talk app. The current AGP version is the correct one for the current Android Studio version.
