### ISSUE TITLE
participant list design is compressed

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2457]
### Steps to reproduce

?

### Expected behaviour

list is fully expanded and scrollable

### Actual behaviour

![grafik](https://user-images.githubusercontent.com/2932790/193542327-483f25cc-14db-4d25-ada8-e986df3ff2be.png)

### Device brand and model

?

### Android version

?

### Nextcloud Talk app version

?

**Comment by mahibi** [comment]
similar or same issue is https://github.com/nextcloud/talk-android/issues/2325

**Comment by tobiasKaminsky** [comment]
It is at c.nc.c and I think it might be related to being moderator or not.
As then above option settings is larger/smaller and thus reduces available/remaining space for participant list.

**Comment by tobiasKaminsky** [comment]
Solution might be to have minimum height of this list view.

**Comment by mahibi** [comment]
i remember i fixed this but don't know the PR right now
