### ISSUE TITLE
Volume of external speaker

### ISSUE THREAD

**Issue by Akrakadil** [nextcloud/talk-android#246]
Low volume of external speaker in video call. Also there's need of a filter to reduce an Echo in video call.

**Comment by mario** [comment]
Volume should be as you set it.

**Comment by Akrakadil** [comment]
When I make it louder echo appears

**Comment by mario** [comment]
I'm not very sure this can be avoided.

**Comment by mario** [comment]
You can increase this using volume up/volume down. Not much I can do I'm afraid.
