### ISSUE TITLE
hide "unread mention" bubble in search mode

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2464]
### Steps to reproduce

prepare:
- join multiple conversations just to fill the conversation list (e.g. "test1" - "test12"). All the conversations on display should be marked as favourite so scrolling is necessary to see all of them, otherwise create more conversations or choose device with smaller screen.
  - mark these conversations as favourite via: long press on conversation - "Add to favourites". This needs to be done to assure conversations with mentions are not moved to the top of the list.
- be mentioned by another person in another conversation (e.g. "test13"). Do NOT mark this conversation as favourite, so it's listed below the favourite conversations.
- with this being done, there should be a "unread mentions" bubble when scrolling to the top. Clicking this bubble will scroll to the conversation with the unread mention.

reproduce bug:
- while the "unread mentions" bubble is shown, tap into the search field to search for conversations/messages.

## Expected behaviour
bubble is hidden as long as the search is active. When leaving the search mode, the bubble should be shown again.

## Actual behaviour
bubble is still shown.

![grafik](https://user-images.githubusercontent.com/2932790/194034635-b77eb2bd-5d4e-40ba-8a33-353cb96d20df.png)

**Comment by Smarshal21** [comment]
@mahibi could you please post an appropriate Screenshot 
![unread_bubb;e](https://github.com/nextcloud/talk-android/assets/99678760/37709ab7-1606-4fa5-a110-1d0ab0b54fda)
Are you speaking about the unread bubble below the Text "2 Day ago".

**Comment by Smarshal21** [comment]
okay
