### ISSUE TITLE
Notification does not Wake the screen

### ISSUE THREAD

**Issue by Akrakadil** [nextcloud/talk-android#247]
When the phone is sleeping while calling, the screen does not Wake up

**Comment by mario** [comment]
Yes it does. What version of the app are you using?

**Comment by Akrakadil** [comment]
I'm trying 2.1.1

**Comment by mario** [comment]
Yup, the screen most definitely wakes up :-/ What phone do you have?

**Comment by Akrakadil** [comment]
three different, Nubia, LeEco, Mi A1

**Comment by Akrakadil** [comment]
I made right setting there

**Comment by Akrakadil** [comment]
I'm not familia only can read the code

**Comment by mario** [comment]
It will be really hard for me to debug this since I don't have the phones :(

**Comment by Akrakadil** [comment]
Well, I'll try to do something because I like your App

**Comment by mario** [comment]
Try looking into MagicFirebaseMessagingService first because that's where the push should arrive.

If you put this line in onMessageReceived method, this will help:

        Log.d("DEBUG", "I GOT A MESSAGE");

**Comment by Akrakadil** [comment]
Ok. I'll install Android Studio now

**Comment by mario** [comment]
Make sure you build the gplay flavour.

**Comment by mario** [comment]
@Akrakadil any news?

**Comment by mario** [comment]
Closing with no information.
