### ISSUE TITLE
No missed call message

### ISSUE THREAD

**Issue by Akrakadil** [nextcloud/talk-android#248]
May be add to chat "You have a missed call..."&Time or "You have a missed videocall"&Time, if they were?

**Comment by mario** [comment]
This has to be done in https://github.com/nextcloud/spreed, sorry :(

**Comment by jakobroehrl** [comment]
@mario 
There is a missed call notification in the server (https://github.com/nextcloud/spreed/issues/2232)
Is it possible to show this in the android app as notification?

If the user only works with the phone I would never get this message.

**Comment by mario** [comment]
I don't understand? All the notifications you get already, but like mentioned by @nickvergessen it's just not in the chat - can you clarify what the issue is?

**Comment by jakobroehrl** [comment]
Sorry. 
If I miss a call I get a server notification. But this notification is only shown on the Web:
![grafik](https://user-images.githubusercontent.com/24530680/72742072-461c6800-3ba9-11ea-945c-3aadae3744cc.png)

So, if I only work with the android app I don't get this missed call notification. Do you understand the problem?

**Comment by jakobroehrl** [comment]
Tested it on iOS, there is a missed call notification.
Sure, it's a server issue, if iOS can handle it already?

**Comment by nickvergessen** [comment]
Part 1 boils down to implement the 2 new system messages from:
https://github.com/nextcloud/spreed/pull/5985/files#diff-0a3568aeb99986c5e603cdd0d00019232adfefbc419dbd69ae6e0551ff64334dR274-R275


See sample of https://github.com/nextcloud/talk-android/pull/1224

Can you do that @timkrueger

**Comment by timkrueger** [comment]
> Can you do that @timkrueger

I'll do my very best :-)

**Comment by mahibi** [comment]
@nickvergessen as far as i understand you expect the following for the android talk app right?:

![grafik](https://user-images.githubusercontent.com/2932790/125631179-2946b3e2-98cc-4a1f-a739-522eaf716d02.png)

this is already working without modifications (Anyway it will be better to turn this explicitly into a system message).

**Comment by mahibi** [comment]
so with the modifcations from @timkrueger who added the 2 system message types in https://github.com/nextcloud/talk-android/tree/feature/248%2Fno-missed-call-message

it looks like this:

![grafik](https://user-images.githubusercontent.com/2932790/125640645-f81d7790-8946-4f27-a8bb-98641d9f2557.png)

**Comment by timkrueger** [comment]
@mahibi Thanks for help and testing
