### ISSUE TITLE
Call Session issues on RC 4

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#2486]
### Steps to reproduce

The original issue started with https://github.com/nextcloud/talk-android/issues/2445 a fix was applied  https://github.com/nextcloud/talk-android/pull/2477 Now the session joins but after a bit the remote users video turns off you can still hear them if they leave and rejoin the video comes back. So while i was on the call on Android Talk i joined it via web and i seen multiple sessions of myself as soon as i joined via web the Android Talk crashed and then it kicked me out of the web i had to rejoin and it was still displaying multiple session after 30 secs or so it cleared all the other sessions

### Expected behaviour

Should no happen

### Actual behaviour

Please see above 

### Device brand and model

SM-G996U1 

### Android version

12

### Nextcloud Talk app version

15.0.0 RC4

### Nextcloud server version

24.0.6

### Talk version

14.0.5

### Custom Signaling server configured

No

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

**Comment by migulen** [comment]
**Device brand and model**

Xiaomi mi 9 (v15.0.0-RC4 like caller/receiver), Samsung A52s (v15.0.0-RC4 like caller/receiver), Xiaomi Poco 3 (v14.2.0 like caller/receiver, for testing  if happens with other versions when communicate with v15.0.0-RC4 )

**Android version**

12

**Nextcloud Talk app version**

15.0.0 RC4

**Nextcloud server version**

23.0.8

**Talk version**

13.0.8

**Custom Signaling server configured**

No

**Custom TURN server configured**

Yes

**Custom STUN server configured**

Yes

**Android logs**

No response

**Server log**

No response

**Additional information**

No response

-----------------

@timkrueger I can confirm every word from @andyxheli . I've test between clients:

Case 1:
v14.2.0 <> v15.0.0-RC4 (being both of them initial callers or receivers of the call): In this case only the user with client v15.0.0-RC4 lost the video from sended by the v14.2.0 client after few seconds. The v14.2.0 client see perfectly the video send by the v15.0.0-RC4 all the time.

Case 2:
v15.0.0-RC4 <> v15.0.0-RC4 (being both of them initial callers or receivers of the call): In this case both sides could lost video signal after few seconds, and it's possible that it don't start receiving video signal at all. Sometimes the caller don't lost the video signal... but the receiver of the call (for me test) always lost the video signal.

The voice works perfectly on both cases.

It happens with caller and receiver on the same (wifi) localnet, or being on differents nets (NATed each one).

**Comment by timkrueger** [comment]
This is fixed with 
- https://github.com/nextcloud/talk-android/pull/2484

**Comment by migulen** [comment]
> This is fixed with
> 
>     * [Fix computing new sessions in call #2484](https://github.com/nextcloud/talk-android/pull/2484)
> 
> 
> Will build an new RC later today.

@timkrueger, @andyxheli, **video and sound worked correctly for me with on a 10 minutes conversation.** Info:

-  Nextcloud-talk android app  v15.0.0-RC5. (I removed all cache and user data from app v15.0.0-RC4, and after the app itself) 
- Nextcloud server v23.0.10
- Talk (Spreed)  v13.0.9

Thanks for all.
