### ISSUE TITLE
 🎨 Support Server theme

### ISSUE THREAD

**Issue by ghost** [nextcloud/talk-android#250]
As a company owner I would like to have the theme configured at the server visible in the mobile app.

Maybe related to #207

**Comment by mario** [comment]
Since you're a company owner, you can either purchase branding service with support or get support + professional services contract to get this implemented.

Otherwise, we''ll probably come to this but I'm not sure how soon.

**Comment by nr458h** [comment]
Our company is to little (7 persons) to give this a high priority but its still a nice to have - thanks for the hint to the professional service.

Other question would a bounty have the same effect?

**Comment by mario** [comment]
Possibly, if somebody decides to pick up the bounty? :)

**Comment by timkrueger** [comment]
Preconditions
- [ ] Get rid of Lovely Dialogs
- [ ] Introduce screenshot tests
