### ISSUE TITLE
Show conversation search results first

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/talk-android#2504]
### Steps to reproduce

1. Search for a conversation

### Expected behaviour

Most of the time I search for an existing conversation so I'd expect those to be listed first in the search results

### Actual behaviour

However the conversation list loads but then shortly after the message search results get added on top of that, so that it always requires you to scroll down.

I feel like searching for a conversation is the more common use case.

cc @nextcloud/designers 

### Device brand and model

Pixel 3a

### Android version

12

### Nextcloud Talk app version

15.1.0 Alpha 05

### Nextcloud server version

25.0.0 RC 5

### Talk version

15.0.0 RC 5

**Comment by LeopoldVInfinite** [comment]
probably happened here? 
e4a480ac2a28bfb9d0b56c468c446d9d37da6562

**Comment by jancborchardt** [comment]
Yes, absolutely agree, also always find that confusing and leads to misclicks.

**Comment by jancborchardt** [comment]
@mahibi seems like a small fix, so should it still get on the board?

**Comment by AndyScherzinger** [comment]
PR is https://github.com/nextcloud/talk-android/pull/2589
