### ISSUE TITLE
Every Text ist replaced with "Benötigt keine Übersetzung, Hier wird nur die formelle Übersetzung verwendet (de_DE)."

### ISSUE THREAD

**Issue by LeopoldVInfinite** [nextcloud/talk-android#2507]
### Steps to reproduce

1. Set System Language to "Deutsch (Österreich)", "German(Austria)"
2. Start App
3. Every Text ist replaced with "Benötigt keine Übersetzung, Hier wird nur die formelle Übersetzung verwendet (de_DE)."

If Language is changed to English or German(Germany) every text is displayed as expected.
![screenshot](https://user-images.githubusercontent.com/57572802/196264684-ea5bda14-152b-49d3-8cec-0157d101715c.jpg)

probably happened here?
e4a480ac2a28bfb9d0b56c468c446d9d37da6562

### Expected behaviour

display text

### Actual behaviour

Text "Benötigt keine Übersetzung, Hier wird nur die formelle Übersetzung verwendet (de_DE)". is displayd for every text

### Device brand and model

Samsung Galaxy A53 5G, Samsung Galaxy Tab S7 FE

### Android version

12

### Nextcloud Talk app version

15.0.0

### Nextcloud server version

24.0.6

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

**Comment by Dj-Redix** [comment]
Same Here.

**Comment by manuelkamp** [comment]
this makes the app unusable, please make hotfix

**Comment by timkrueger** [comment]
Fixed with https://github.com/nextcloud/docker-ci/pull/451

**Comment by Dj-Redix** [comment]
Fixed Here. THX.

**Comment by Neuroplant** [comment]
Hello,
Problem is back with todays update

**Comment by Tingil79** [comment]
Same in the desktop app.

![image](https://user-images.githubusercontent.com/68645159/213634972-3c9a79e7-f622-4dad-addf-dd9dc265b83f.png)

**Comment by Neuroplant** [comment]
> Hello, Problem is back with todays update this time for de-DE

sotrry its the other client (desktop)

**Comment by meltymon** [comment]
i have the same problem running on debian 11 on proxmox server
with android/macosx and ios

**Comment by AndyScherzinger** [comment]
I think the issue came with desktop 3.6.5 and has been fixed with 3.6.6

**Comment by Dj-Redix** [comment]
Same here

**Comment by FelixBuehler** [comment]
Can confirm, is fixed with the newest update. To manually trigger it (since you can't read what is what):

- Right click on Nextcloud in Sys-Tray 
- Open Settings (it's the 3rd button from top/below)
- Go to settings (you can recognize it from the gear symbol)
- Click the bottom right button, the one without dropdown arrow.

**Comment by meltymon** [comment]
i got a update ,it fixed the problem thanks

**Comment by Dj-Redix** [comment]
Update works!

**Comment by SCS13591** [comment]
Problem is back with 3.7

**Comment by schubertma** [comment]
Same here using Windows 11. Before I had the bug that I could not see every folder and the explorer crashed several times. Now this issue...

**Comment by SCS13591** [comment]
> Same here using Windows 11. Before I had the bug that I could not see every folder and the explorer crashed several times. Now this issue...

Explorer an everything else is working fine. It's that the ""Benötigt keine Übersetzung, Hier wird nur die formelle Übersetzung verwendet (de_DE)."" translation

**Comment by SCS13591** [comment]
> Problem is back with 3.7 (german translation)

FIX in 3.7.3

**Comment by schubertma** [comment]
> > Same here using Windows 11. Before I had the bug that I could not see every folder and the explorer crashed several times. Now this issue...
> 
> Explorer an everything else is working fine. It's that the ""Benötigt keine Übersetzung, Hier wird nur die formelle Übersetzung verwendet (de_DE)."" translation

Sorry, comma was missing. Just wanted to tell that I got one bug after another.

Release 3.7.3 Latest
What changed:

Revert "Fix(l10n): 🔠 Update translations from Transifex"
Revert "Fix(l10n): 🔠 Update translations from Transifex"
Revert "Fix(l10n): 🔠 Update translations from Transifex"

https://github.com/nextcloud/desktop/releases/tag/v3.7.3

**Comment by mahibi** [comment]
if there is a problem with the desktop app, please discuss in https://github.com/nextcloud/desktop/issues/5348 or create a new issue at https://github.com/nextcloud/desktop/issues
