### ISSUE TITLE
add Status Icon to users Avatar in chatview header

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-android#2515]
### Steps to reproduce

Open Talk 
Open chat of the users
Under the main screen the your status shows
After doing into the chat the status dose not show under the pictire icon.

@mahibi this is not effected by this 
https://github.com/nextcloud/talk-android/issues/2478 i tested with the settings on or off same results I also tested on cloud.nextcloud.com and same results 

### Expected behaviour

Should should users status 

### Actual behaviour

Dose not

### Device brand and model

SM-G996U1 

### Android version

12

### Nextcloud Talk app version

15.0.0

### Nextcloud server version

24.0.6

### Talk version

14.0.5

### Custom Signaling server configured

No

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

**Comment by mahibi** [comment]
i'm not sure if i understand correctly where the status is missing. 
Do you mean that in group conversations the users should have a status icon for inside chat view?
Can you post a screenshot and mark where you expect the status should be shown?

**Comment by andyxheli** [comment]
Here you go :) 
![image](https://user-images.githubusercontent.com/59488153/196992041-a7fc3ffd-129a-4a07-bbe1-b6f0f051cc9b.png)

**Comment by mahibi** [comment]
ah ok. yes i also thought about to add it there! it's just not implemented so it's not a bug.
i see iOS also doesn't have it.
@nickvergessen can decide how important it is and if/when it should be done to align andoid&iOS ;)

**Comment by andyxheli** [comment]
Thank you very much :)

**Comment by nickvergessen** [comment]
Sounds useful. I myself always workaround by going into the participants list from there.

**Comment by AndyXheli** [comment]
Hello! Just wanted to see if there's any updates on this looks like the ios app has implemented this

**Comment by AndyScherzinger** [comment]
No, else there would be a PR linked to it.

**Comment by AndyXheli** [comment]
> No, else there would be a PR linked to it. 

Thank you! So for the bother.

**Comment by AndyXheli** [comment]
Still an issue.

**Comment by AndyXheli** [comment]
Still an issue.

**Comment by AndyScherzinger** [comment]
Implemented for 1on1 conversations via #3217

**Comment by AndyXheli** [comment]
> Implemented for 1on1 conversations via #3217

Thank you for all your hard work 🙂
