### ISSUE TITLE
Mention gone when tiping the next char

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#2528]
### Steps to reproduce

add a mention
tip a sign for example a ? the mention then is gone

### Expected behaviour

mention stays

### Actual behaviour

the mention then is gone

### Device brand and model

Pixel 4a (5G)

### Android version

13

### Nextcloud Talk app version

15.0.1

**Comment by timkrueger** [comment]
<table>
  <tr>
    <th>Before next char</th>
    <th>After next char</th>
  </tr>
  <tr>
    <td><img width="300" src=https://user-images.githubusercontent.com/606665/199004824-298f4f04-b2f0-4d1f-b018-691dba395e1f.png /></td>
    <td><img width="300" src="https://user-images.githubusercontent.com/606665/199004817-36053772-bb35-4a33-8c2d-6be5cb7b54d1.png" /></td>
  </tr>
<table>

**Comment by mahibi** [comment]
that the expected behaviour from my pov. and it's the same in web.

you can click on the suggested users once they appear. then the bubble is added right inside the edit field.
or you can just add a whitespace. then there will only be a bubble in the sent message if it's a valid username.
but typing a random char without a whitespace means it won't be possible to find the user because the name does not exist..

**Comment by jakobroehrl** [comment]
Web:
type @ and click on a name
Then type only ?
Result: Mention bubble with ? followed

Android:
type @ and tip on a name
Then type only ?
Result: Name of the user without bubble with ? followed

But I noticed it is working with the @all mention but not with the @user mention

**Comment by timkrueger** [comment]
I understood the issue wrong. In my opinion @mahibi is right. It works as expected:

[device-2022-11-11-145134.webm](https://user-images.githubusercontent.com/606665/201354359-fa60f4c5-17c3-4929-afca-cdd9646e700b.webm)

**Comment by jakobroehrl** [comment]
yes, the bubble goes away.
I will try to do a video

**Comment by mahibi** [comment]
is there a different behaviour on different phones (but with same servers) @jakobroehrl ?

**Comment by jakobroehrl** [comment]
Sorry, you are right. 
On my other phones it's working correctly.

**Comment by mahibi** [comment]
@jakobroehrl maybe it's OS related? 
was it the alternate OS where it's failing? you used OxygenOS if i remember correctly?

**Comment by jakobroehrl** [comment]
This could be true.
Its calyx
