### ISSUE TITLE
Show unread messages

### ISSUE THREAD

**Issue by Bolli84** [nextcloud/talk-android#253]
In the webbased version, you can see number of chat messages you have open for a specific chat (One on one or group chat).
In the mobile phone version, this is not visible (at leat I cannot find it).
Is this feature available and can be found somewhere, or is not not (yet) implemented?

**Comment by Bolli84** [comment]
Is this implemented in the fix? On the overall-screen with all conversations and rooms, which I opened I cannot the the current numbers of unread messages
Preference: It should be next to the Conversation name.

**Comment by mario** [comment]
It's indeed implemented.

**Comment by Bolli84** [comment]
It is not visible in v3.0.0beta3 and beta4. At least not in my view Android 8.0.0 Sony Xperia

**Comment by mario** [comment]
I think you need Nc14 and new Spreed. Can't remember atm.

**Comment by Bolli84** [comment]
Is NC14 already a stable /productive Release?

**Comment by mario** [comment]
No. Beta.

**Comment by Bolli84** [comment]
It is good to hear that it is implemented, however it is prefered on a productive release. Is it possible for NC13?

**Comment by mario** [comment]
No, sorry.
