### ISSUE TITLE
Too hard to react with already given reactions

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#2537]
### Steps to reproduce

1. See a message with many different reactions
![Screenshot_2022-11-04-11-52-10-006_com nextcloud talk2](https://user-images.githubusercontent.com/213943/199957917-6f74c83b-46da-45a1-bc08-aba8e95e4817.jpg)

2. Try to react with them

### Expected behaviour

It should be easily possible to react with already available reactions

### Actual behaviour

You can only react with a default list of reactions or you need to know the name of the emoji and use the search
![Screenshot_2022-11-04-11-53-37-879_com nextcloud talk2](https://user-images.githubusercontent.com/213943/199957778-60dde8e2-4311-490f-b8be-d2cc8d4d2a27.jpg)

### Device brand and model

Xiaomi RedMi Note 8

### Android version

11

### Nextcloud Talk app version

Beta

### Nextcloud server version

25.0.1

### Talk version

15.0.1

**Comment by mahibi** [comment]
just as an overview how other messengers do this:
whatsapp - not possible
signal - show emojis that are already used for this message when going to more emojis with the 3dot menu
telegram - just tip on the emoji that is shown right inside the message

**Comment by nickvergessen** [comment]
In talk iOS it's possible to just tab the emoji and it's reacting with it as well (so like telegram)

**Comment by mahibi** [comment]
**before:**
single click on emoji inside message -> open the given-reactions overview 
longclick on emoji inside message -> open the message context menu


**proposed change:**
single click on emoji inside message -> react with +1 if not yet clicked on it. delete reaction if already clicked on it
longclick on emoji inside message -> open the given-reactions overview 

this solution will also need that we change the three dot menu for reactions. right now if there are many reactions, all of them can only be shown by opening the  given-reactions overview.
however if it should be possible to react to +1 for already given emojis, they should better be all shown by a horizontal scroll inside the message (that how it's done in the iOS app).

**Comment by nimishavijay** [comment]
Agreed with @mahibi, there should be similar functionality between web and mobile actions :)
