### ISSUE TITLE
Nextcloud Talk app does not show or bring up notifications.

### ISSUE THREAD

**Issue by InAUGral** [nextcloud/talk-android#2538]
## Steps to reproduce
1.  Install version from either play store/aurora store or F-Droid. Apple iOS app has same problem 
2. Open the app and configure then leave Nextcloud talk app open in background or even when open no notifications come in.

### Expected behaviour
App providing notifications of messages and calls coming in.

### Actual behaviour
No notifications at all despite being enabled in android notification settings.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Android 12 or iOS

**Browser name:** N/A

**Browser version:** N/A

### Browser log

N/A

</details>

## Talk app

**Talk app version:** 14.0.5

**Custom TURN server configured:** no

**Custom STUN server configured:** yes

## Server configuration

**Operating system**: Ubuntu Nextcloud Snap package installation

**Web server:** Apache

**Database:** MySQL

**PHP version:** version 8.1.2

**Nextcloud Version:** 24.0.6

Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - calendar: 3.5.1
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.2
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notes: 4.5.1
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.5
  - support: 1.7.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - twofactor_backupcodes: 1.13.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Rest of info doesnt seem relevant to an app issue.
<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by timkrueger** [comment]
I have a few questions and notes:
- You're using version 15.0.1 of Nextcloud Talk for Android?
- The version from F-Droid is not supporting notifications. 
- Please note that new major versions for Nextcloud and Talk are available.
- Please have a look into our [notifications guide](https://github.com/nextcloud/talk-android/blob/master/docs/notifications.md).

**Comment by farvardin** [comment]
@InAUGral I had the same problem, on the 15.0.1 google play version, and it seems for getting the notifications from NC Talk, you have to install the NC Files! (yes, that's quite odd behavior...)

as said on the notifications guide: 

> Only talk notifications will be delivered by the Talk app, for all other notifications install the Nextcloud Files app from Google PlayStore.

**Comment by Saneckg** [comment]
Nextcloud files установлен, но всё равно уведомлений нет

**Comment by InAUGral** [comment]
> @InAUGral I had the same problem, on the 15.0.1 google play version, and it seems for getting the notifications from NC Talk, you have to install the NC Files! (yes, that's quite odd behavior...)
> 
> as said on the notifications guide:
> 
> > Only talk notifications will be delivered by the Talk app, for all other notifications install the Nextcloud Files app from Google PlayStore.

Thanks for the reply everyone. I have already tried the Nextcloud client app and Nextcloud talk installed from the play store.

You're using version 15.0.1 of Nextcloud Talk for Android? Yes, 15.0.1 is the version installed from the play store
    The version from F-Droid is not supporting notifications.
Play store versions also do not work. Same with iOS version
    Please note that new major versions for Nextcloud and Talk are available.
24.0.6snap1 is the latest Nextcloud server version and the play store provides 15.0.1 for Talk and Nextcloud files/client app is version 3.22.3 which all seem to be the latest available. The guide was not helpful in resolving this.
    Please have a look into our [notifications guide](https://github.com/nextcloud/talk-android/blob/master/docs/notifications.md).

**Comment by pawlosck** [comment]
Could you check if problem is connected with lockscreen? In my case, when I restart phone and after few minutes after restart I will try to call from web app to android Talk, notification is not visible (visible is field to enter passwword).
When I disable any method to lock screen, notification from Talk is visible. I checked few times and with disabled lockscreen, notification is visible. When Password is used to lock screen(I didn't check other method to lock screen - PIN, symbol etc), notification from Talk is visible, but not always and I don't know, where is problem. After restart, before first unlocking, notification is not visible.

**Comment by vdbhb59** [comment]
This still does not work. Irrespective of the PS or FD. Not sure how to solve it at all. ☹

**Comment by chai-rel** [comment]
I have the same issue, tried numerous things, nothing worked for me nor other users I talked to.

Had similar issue on Desktop, but @drlight17 released a desktop client which completely fixed notifications.
I don't know if he has plans to release Android version, or it's even possible to fix.
If you're reading this **drlight17**, any comments on this?

**Comment by vdbhb59** [comment]
Good I guess. But cannot see the code in his repo. Only change details, but not the actual code.

**Comment by drlight17** [comment]
> I have the same issue, tried numerous things, nothing worked for me nor other users I talked to.
> 
> Had similar issue on Desktop, but @drlight17 released a desktop client which completely fixed notifications.
> I don't know if he has plans to release Android version, or it's even possible to fix.
> If you're reading this **drlight17**, any comments on this?
> 

Hello. No, Android version is not in my plan. Notifications in NC Talk Electron are using server-side spreed code for now. So their behavior is almost the same as if you open Nextcloud conversations menu in your system browser.

**Comment by drlight17** [comment]
> Good I guess. But cannot see the code in his repo. Only change details, but not the actual code.

That is strange if I understand you right. Code is not hidden or private of some kind.

**Comment by chai-rel** [comment]
> Hello. No, Android version is not in my plan. Notifications in NC Talk Electron are using server-side spreed code for now. So their behavior is almost the same as if you open Nextcloud conversations menu in your system browser.

That is a shame, but I completely understand.
Thank you for the quick reply, and your continued work on the desktop app, it's absolutely fantastic 👍

**Comment by drlight17** [comment]
> > Hello. No, Android version is not in my plan. Notifications in NC Talk Electron are using server-side spreed code for now. So their behavior is almost the same as if you open Nextcloud conversations menu in your system browser.
> 
> That is a shame, but I completely understand. Thank you for the quick reply, and your continued work on the desktop app, it's absolutely fantastic 👍

Don't get me wrong - I just have no experience in mobile development =) Thanks for your mark.
