### ISSUE TITLE
Add acoustic feedback for a call actions

### ISSUE THREAD

**Issue by alexara** [nextcloud/talk-android#254]
It would be great to have the following acoustic feedback :)

* Play a ringing sound when a call is initiated until the call receiver picks ups or joins the call
* When a user hangs up or a call ends, play an appropriate sound

**Comment by mario** [comment]
There are several issues here:

a) This is not like a phone and we don't know when it really starts "ringing"
b) We don't know when a user hangs up

There was already an issue that I closed.

**Comment by alexara** [comment]
> There was already an issue that I closed.

Sorry, I searched for similar topics but did not find the one you closed.

Could it not be solved by sending "special" messages, when it starts ringing at another's phone or when the user hangs up?

I think of kind of invisible messages like, "hey I receive a call from you" or "hey, I hang up", which triggers an appropriate action at the other end.

**Comment by mario** [comment]
That would need to be done in @nextcloud/talk.

**Comment by jakobroehrl** [comment]
@mario Is this already implemented?
Tested yesterday with the latest version and I can see "Calling..." but can not hear a tone.
Thanks!

**Comment by mario** [comment]
@jakobroehrl it is, but I disabled it. Will fix soon-ish. Thanks for letting me know.

**Comment by jakobroehrl** [comment]
@mario It's working with the latest beta, thanks a lot!

**Comment by benbenik** [comment]
Could this also be added to the iOS version? Or are the apps too different to easily reuse the code? Ref: https://github.com/nextcloud/talk-ios/issues/333
