### ISSUE TITLE
Incoming call screen with only a reject button

### ISSUE THREAD

**Issue by alexara** [nextcloud/talk-android#255]
Last times I called a friend, his incoming call screen often looked like this:

![a9124b4c-5f6d-4a9a-a9ec-edaac5a19b65](https://user-images.githubusercontent.com/13819719/43049907-34cd1a34-8e00-11e8-8cf0-ccd8a9a1f81d.jpg)

There was no way to accept the call. That's a frustrating UX. :-(

# Setup
Receiver: Samsung Galaxy S4, LineageOS 14.1 (Jun 18), NC Talk 2.1.2 PlayStore Version
Caller: Samsung Galaxy S4 Mini, LineageOS 14.1 (Jun 18), NC Talk 2.1.2 F-Droid Version
Sever: NC 13.0.4, NC Talk 3.2.4, TURN+STUN Server

Let me know if you need more information in order to debug this issue.

Kind Regards

**Comment by mario** [comment]
Super strange. I do have an S4 so I'll investigate.

**Comment by mario** [comment]
AAAAH! Lineage! Can you tell me what version of the Play Services do you have installed?

**Comment by mario** [comment]
Btw. this would happen if the app cannot find the user/group that initiated the call.

**Comment by mario** [comment]
(or if it's slow to get the needed info)

**Comment by mario** [comment]
OK, the one without GApps won't even have notifications.

As for your other question... how? :D I can't fix how fast your server reacts :( 

But let me look into this a bit more, maybe I missed something.

**Comment by alexara** [comment]
> As for your other question... how? :D I can't fix how fast your server reacts :(

So you would advise me to upgrade my tiny VPS with LEMP? :-)

> But let me look into this a bit more, maybe I missed something.

Thanks!! :)

**Comment by mario** [comment]
LEMP is good.

**Comment by mario** [comment]
I think this is fixed in master, but I guess we'll see. @alexara can you confirm that you have multiple accounts configured in your app?

**Comment by alexara** [comment]
> can you confirm that you have multiple accounts configured in your app?

Nope, only one is configured.

**Comment by mario** [comment]
Okay, I guess we'll see with 3.0beta1 if this works or not :P
