### ISSUE TITLE
🖼️ Conversation avatars

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#2555]
See meta ticket at https://github.com/nextcloud/spreed/issues/927

- [x] Allow moderators to set an avatar for a conversation
- [x] Allow moderators to delete an avatar from a conversation
- [x] Use new avatar route as conversation icon in all code paths

**Comment by timkrueger** [comment]
@nickvergessen Sorry forgot to mention that I can't hold the ETA. 21.12. should be possible.
