### ISSUE TITLE
Various accounts

### ISSUE THREAD

**Issue by fraengii** [nextcloud/talk-android#256]
_V2.1.2 from F-Droid on a 5.1.1 Android phone._

Setting up first account: All nice.
Second account: App sticks in turning blue circle (at least up to 10 min). After restart there is the option to switch between accounts but it leads to a blank page.

Same with import from Nextcloud app.

**Comment by mario** [comment]
Version of the Talk app please, and if F-Droid or Gplay :)

**Comment by fraengii** [comment]
V2.1.2 from F-Droid on a 5.1.1 Android phone.

I tested the GPlay version via Yalp Store and it crashes when I tryed to import an account from Nextcloud and when I want to add an account (after I created the first one via server address).

**Comment by mario** [comment]
Thanks for the reply. The only reason why it'd crash is if you had a Talk app from GPlay and Nextcloud app from F-Droid. Is that correct?

**Comment by fraengii** [comment]
Yes, correct!

**Comment by fraengii** [comment]
I use the Yalp Store less and just tryed it for to see if there is a difference. Usually I install all my apps from F-Droid! 8-)

**Comment by mario** [comment]
The F-Droid version doesn't support call and messages notifications.

**Comment by fraengii** [comment]
Will it anytime?

**Comment by mario** [comment]
Yes, once Google open sources the Firebase libs and people who run MicroG/Google Play Services.

**Comment by fraengii** [comment]
Sounds like "Never". Do you recommend the GPl-verson so?

**Comment by mario** [comment]
At the moment, yes. But Google plans to release Firebase libraries, and you'd be surprised how many people already have MicroG (FOSS alternative to Play Services) or Play Services on their phone.

**Comment by fraengii** [comment]
Thanks. I will have a look at MicroG.

**Comment by mario** [comment]
I've fixed the issue with crashing on import in a way that import account doesn't show if we can't import accounts. I'll look into the other issue mentioned here too.
