### ISSUE TITLE
import account from files app: username is cleared when typing password

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2569]
### Steps to reproduce

1. choose import account from files app (sidenote: import from files app doesn't work in debug mode!)
2. username is prefilled
3. type password

### Expected behaviour

username remains

### Actual behaviour

username is cleared

**Comment by mahibi** [comment]
might has to be moved to server repo..

**Comment by migulen** [comment]
@mahibi .... excuse me, but could it be exactly the same that jakobroehrl describes in https://github.com/nextcloud/talk-android/issues/743 ?

https://github.com/nextcloud/talk-android/issues/743#issuecomment-751285585

![imagen](https://user-images.githubusercontent.com/60242624/202005163-aa75b3cd-149a-4ee3-b4c4-747ee2438dc4.png)

but it's not full explained in the first post: https://github.com/nextcloud/talk-android/issues/743#issue-573804510

![imagen](https://user-images.githubusercontent.com/60242624/202005809-b869feee-7223-4bf9-b384-14f6eed1c90d.png)

:-)

**Comment by mahibi** [comment]
yeah it should be the same cause so i'm fine with closing this issue and add infos to 743
