### ISSUE TITLE
Shared screen not shown

### ISSUE THREAD

**Issue by schiessle** [nextcloud/talk-android#2571]
### Steps to reproduce

1. Start a group call with multiple participants (I tried to join our weekly company call)
2. Join with the Android app, I tried both: joining voice only and joining with video)
3. Someone in the call shares their screen

### Expected behaviour

I can see the shared screen on my Android device

### Actual behaviour

I only see the participant list but not the shared screen

### Device brand and model

Samsung S21FE

### Android version

12

### Nextcloud Talk app version

15.0.1

### Nextcloud server version

25.0.1.1

### Talk version

15.0.1

**Comment by mahibi** [comment]
fixed with https://github.com/nextcloud/talk-android/pull/2503 in the next bugfix release so i will close this issue.

however, it still needs to be improved. for this, https://github.com/nextcloud/talk-android/issues/1397 exists
