### ISSUE TITLE
Translation sync is broken

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#2577]
### Steps to reproduce

> nextcloud.android-talk - upload of resource 'o:nextcloud:p:nextcloud:r:android-talk' failed - parse_error: Duplicate `tag_name` (string) for `name` (nc_nextcloud_talk_app_not_installed) specify a product to differentiate

This means that the string `nc_nextcloud_talk_app_not_installed` has different source strings in master and all the synced stable branches. Please unify.

**Comment by AndyScherzinger** [comment]
Backport bot failed on #2574

**Comment by nickvergessen** [comment]
Worked, no more error tonight
