### ISSUE TITLE
Ghost call screen when a call starts

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/talk-android#258]
Lately on groups calls, when the call starts I have blank ghost screens like that.
I showed it to @jancborchardt and it happens every time :)

![screenshot_20180704-162041](https://user-images.githubusercontent.com/14975046/43186381-c85e2564-8fee-11e8-92ff-607859cc14ee.png)

@mario

**Comment by mario** [comment]
@skjnldsv does it changes? This is how it is UNTIL it gets all the info which it needs, which is a split second.

**Comment by skjnldsv** [comment]
@mario no, it stays like that forever :(
With screen on too :)

**Comment by mario** [comment]
Only on group calls?

**Comment by skjnldsv** [comment]
I did not test it on single calls :)

**Comment by alexara** [comment]
Looks like what I just reported: https://github.com/nextcloud/talk-android/issues/255. However in my case it happened at a 1:1 call. :-)

**Comment by skjnldsv** [comment]
@alexara exactly :)

**Comment by mario** [comment]
I think this is fixed in master, but I guess we'll see. @skjnldsv  can you confirm that you have multiple accounts configured in your app?

**Comment by skjnldsv** [comment]
@mario Nope, only one account :)

**Comment by mario** [comment]
@skjnldsv thanks.

**Comment by skjnldsv** [comment]
Happened again today with only one account :)
I did not update to latest though

**Comment by mario** [comment]
Right, I assumed you didn't compile from master yourself :) Let's wait for 3.0 beta 1 before testing this ;)
