### ISSUE TITLE
Contact selection small improvements 

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/talk-android#259]
Two suggestions:
- [x] - The contacts should have a loading circle before rendering (even if the data is fetched)
- [X] - The red/green buttons seems out of place @jancborchardt 

| Needs loader | Buttons |
|:--:|:--:|
|![screenshot_20180725-093940](https://user-images.githubusercontent.com/14975046/43186543-39785968-8fef-11e8-8edb-01446c60ada7.png)|![screenshot_20180725-094033](https://user-images.githubusercontent.com/14975046/43186645-96be57c6-8fef-11e8-870a-71bdb9fb3799.png)|

**Comment by mario** [comment]
The second issue was already addressed.

**Comment by jancborchardt** [comment]
Could we also cache the data once it’s loaded? Because currently it _always_ seems to request the server, whereas your contact list probably does not change so often. It could show cached data and then silently make the changes once update is fetched.

**Comment by mario** [comment]
This is a whole other issue which you've mentioned somewhere else @jancborchardt. It will be done, but not now.

(Also, even if it pokes the server, we do cache the data in a way, just not across application runs which is sane considering that Talk runs all the time pretty much)
