### ISSUE TITLE
server url should respect url format

### ISSUE THREAD

**Issue by rullzer** [nextcloud/talk-android#26]
When entering the url: cloud.<domain> the input apparenrly doesn't tell my keyboard it is an url. So the `.` after cloud also gets a space.

This works in the Nextcloud app.

**Comment by mario** [comment]
Easy to fix, will be done.

**Comment by pierrecdlc** [comment]
What's the server url ? Because I enter : http://account.gamacloud.com/gamacloud/index.php/apps/spreed

But it don't work... How can i do ?

**Comment by mario** [comment]
@pierrecdlc answered in a separate ticket: https://github.com/nextcloud/talk-android/issues/28

**Comment by pierrecdlc** [comment]
The URL http://account.gamacloud.com/gamacloud don't work, i receive "only works on nextcloud server"

**Comment by mario** [comment]
You have changed the product name from Nextcloud to Gamacloud. Currently talk only works with Nextcloud as a product, for anything else I'd suggest you contact our Nextcloud sales department, or change & compile the app yourself.

**Comment by pierrecdlc** [comment]
Thanks for all, Pierre.

**Comment by mario** [comment]
@pierrecdlc like I commented in another ticket, will be fixed in 0.1.1 - thanks for the patience!
