### ISSUE TITLE
Show full contact book instead of just Nextclouds 

### ISSUE THREAD

**Issue by enoch85** [nextcloud/talk-android#260]
It would be nice to be able to show the full contact book instead of just Nextclouds to be able to use Talk not only for Nextcloud users, but for anyone.

This would make it easier to share links to anyone, instead of manually copying the link and then send it manually.

I hope you get the point. :)

**Comment by mario** [comment]
Full contacts book? You mean from your address book? But that would mean we'd need to support SMS too?

Please clarify.

**Comment by enoch85** [comment]
Yes, support sending SMS from inside the app.

**Comment by kaffeeringe** [comment]
Turn Talk into a real messenger. See #675

**Comment by nickvergessen** [comment]
> Yes, support sending SMS from inside the app.

This is out of scope. 

It more sounds like the real issue is:
> This would make it easier to share links to anyone, instead of manually copying the link and then send it manually.

So basically after creating a new conversation it should be immediately asked to share the link?
