### ISSUE TITLE
chatrooms open with 30 seconds delay only on mobile data after update to 15.0.2

### ISSUE THREAD

**Issue by Burtdoe** [nextcloud/talk-android#2618]
### Steps to reproduce

switch from wifi to mobile data

### Expected behaviour

chatrooms open immediately (2-3 seconds)

### Actual behaviour

on wifi everything works fine. chatrooms open immediately.
when I open the app on mobile data it takes almost exactly 30 seconds until I can see the chatrooms.
when I open a VPN on mobile data to Hongkong for example, the chatrooms also open immedately.

I tried it also with different providers (Telekom and Vodafone)

My first thought was bruteforce protection about the 30 sec. delay, but SQL was clean.

Everything worked fine before the update.

### Device brand and model

Samsung Galaxy S21+5G

### Android version

12

### Nextcloud Talk app version

15.0.2

### Nextcloud server version

24.0.7

### Talk version

14.0.7

### Custom Signaling server configured

Yes (specify version in Additional Information)

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

### Additional information

I have my own TURN, STUN and the official spreed signaling server.

**Comment by andyxheli** [comment]
Yes, the app seems to have a delay.

**Comment by Burtdoe** [comment]
Looks like the delay had something to do with IPv6. 
My server was only rechable on IPv4. Since I configured it that the server is rechable on IPv4 and IPv6 the delay is gone.
There was also a delay in the video calls who are gone now.
Is there something like a fallback after 30 seconds ?
