### ISSUE TITLE
Application closes if a user tags a channel with @nameofthechannel

### ISSUE THREAD

**Issue by TBI-NS** [nextcloud/talk-android#2623]
### Steps to reproduce

1 => open a channel
2 => @ the channel

### Expected behaviour

1 => open a channel
2 => @ the channel
3=> The tag appears in the chat and users receive a notification

### Actual behaviour

1 => open a channel
2 => @ the channel
3=> the application closes instantly

### Device brand and model

Samsung / xiaomi / oppo / huawei

### Android version

10 / 11

### Nextcloud Talk app version

Last version

### Nextcloud server version

Last version

### Talk version

Last version

### Custom Signaling server configured

Yes (specify version in Additional Information)

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

**Comment by mahibi** [comment]
@TBI-NS does this happen for all channels? always?

**Comment by mahibi** [comment]
@jancborchardt i remember you once told me about this bug, right? Does this still happen for you?

**Comment by TBI-NS** [comment]
Hello, apparently the bug has disappeared since the last update on Android, I keep an eye open on this bug in case

**Comment by mahibi** [comment]
glad it's fixed somehow!

with "last update on Android" you mean the android os version? With which version were the problems and with which version it is solved now?

**Comment by TBI-NS** [comment]
I'm talking about the latest production version of nextcloud talk ios (when I filed the bug of course!)

Now everything works with the latest version of talk on android 10 / 11.

I don't really know when this bug disappeared, but I had about 15 users who had the problem when I posted.

We can therefore pass this bug as solved even if we don't really know why..

Thanks !

**Comment by jancborchardt** [comment]
> @jancborchardt i remember you once told me about this bug, right? Does this still happen for you?

@mahibi it did happen I think last week or a few weeks ago – with a regular @-mention though I thought. Or maybe this happens if the @-nameofchannel is focused / first result, not just if it’s actually used?

**Comment by TBI-NS** [comment]
This bug solved for me ..
