### ISSUE TITLE
App doesn't start with arabic

### ISSUE THREAD

**Issue by mario** [nextcloud/talk-android#263]

**Comment by mario** [comment]
Can somebody test this? I set the language of my phone to a non-standard language and it seems to work ok :(

**Comment by mario** [comment]
@AndyScherzinger ?

**Comment by AndyScherzinger** [comment]
Haven't had a chance yet to test it :/

**Comment by mario** [comment]
All good, was just poking you to tell me when you do :D

**Comment by mario** [comment]
Closing since I can't reproduce. :(
