### ISSUE TITLE
Smart notifications

### ISSUE THREAD

**Issue by mario** [nextcloud/talk-android#265]

**Comment by mario** [comment]
@Ivansss @nickvergessen this is basically:

- first notification in a conversation: show
- following notifications if first one is not dismissed: on second one, show "You have more new messages" or so. Ignore third and following notification in the conversation until dismissed.

**Comment by mario** [comment]
Will be configurable and disabled by default for one-to-one conversations. (which is the only type where this makes sense until group/public calls get notifications on every message)

**Comment by nickvergessen** [comment]
I would always do this, without configuration

**Comment by mario** [comment]
We can do that too :)

**Comment by pwFoo** [comment]
With webpush api / browser it's possible to group notifications together. So with 2+ notifications just one is shown. Not possible with the app?

**Comment by mario** [comment]
Will group and show messages that way instead.
