### ISSUE TITLE
Include sender's avatar in notification preview 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-android#2673]
Would this be possible simmular to [ Include sender's avatar in notification preview ](https://github.com/nextcloud/talk-ios/issues/780)

**Comment by andyxheli** [comment]
So it looks like the avatar is there only when expanding the notification

**Comment by Smarshal21** [comment]
![WhatsApp Image 2023-09-04 at 1 39 16 PM](https://github.com/nextcloud/talk-android/assets/99678760/844f3277-f6db-49c0-b513-3b61329ddfbe)
Is this what you are talking about @AndyXheli ???
