### ISSUE TITLE
Assume https

### ISSUE THREAD

**Issue by rullzer** [nextcloud/talk-android#27]
We build secure software. We should assume that any url entered in the main screen if there is no protocol provided we first try https.

If https fails. Show a big warning and offer to fall back to http

**Comment by mario** [comment]
Or fallback to http automatically like we do on the Nc app?

**Comment by rullzer** [comment]
I would show a warning (actually we should also do that in the NC app I'll open an issue there as well). So usersknow they are communication over an insecure connections.

@jancborchardt any ideas how to show this in a nice way?

**Comment by mario** [comment]
We do show that its insecure in the Android app but then it quickly
proceeds to webview, so not sure users see this.

**Comment by rullzer** [comment]
k, well just the same behaviour as in the app should be fine. Maybe we can show it in a bar on top of the webview or something ? But lets fix it later :)

**Comment by jancborchardt** [comment]
Yes, the behavior in the Android app is for a reason and covers all concerns mentioned. It should be done exactly the same here. :)
