### ISSUE TITLE
Can not share a conversation to another one or copy the link

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#2702]
Just now I tried to guide someone from the community chat to the designer chat.
The problem is there is no way to post a link to the other conversation. I tried switching over but was also unable to find a "copy link" there.
I ended up logging in on firefox navigating with the painful mobile web view to the chat to copy the link.

I think we could help on multiple levels there:

* Have a copy link in the conversation settings (basic)
* Have it in the long press menu of the conversation list (level 2)
* Have a conversation picking option in the share menu (very advanced)

**Comment by mahibi** [comment]
@sowjanyakch pointed out that https://github.com/nextcloud/talk-android/issues/847 is a followup issue that makes sense to solve after this one..
