### ISSUE TITLE
Click on "Wave" sends "Hello ????"

### ISSUE THREAD

**Issue by alexara** [nextcloud/talk-android#271]
Talk Version: 3.0.0beta1 PlayStore
Phone: Galaxy S7 (Android 8)

When I click on the wave it says "Hello ????" with four question marks.

**Comment by mario** [comment]
This is a database issue.

Your database should be created like following:

CREATE DATABASE nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

Or switch to that charset and collation.

**Comment by alexara** [comment]
Thanks, I am going to do fix it.

**Comment by edes** [comment]
I have the same problem here. Altering the database to that charset and collation didn't change anything for me.
