### ISSUE TITLE
Show user role (Administrator)

### ISSUE THREAD

**Issue by alexara** [nextcloud/talk-android#272]
I have two accounts set up, a standard user account and an admin account. This admin account belongs to all user groups as contact.

Since both accounts belong to me they have the same names (first name last name). It would be convenient to differentiate both contacts by naming it's role, eg. in brackets behind the name or under the name: `John Doe (Administrator).`

**Comment by mario** [comment]
Unlikely to happen as this is a VERY specific use case. But I do understand you need a way to differentiate between them. Maybe you could set the name/surname of one of them a bit differently?

**Comment by Ivansss** [comment]
@alexara You could also change the display name of that admin user to `John Doe (Administrator).` in NC settings :)

**Comment by alexara** [comment]
> Unlikely to happen as this is a VERY specific use case.

In the browser the tag `moderator` is already displayed next to the user name. I had hoped you could do the same on NC Talk and additionally display special user roles, like `administrator`. :)

> You could also change the display name of that admin user to John Doe (Administrator). in NC settings :)

Since everyone could do that, I consider that a bad workaround for a setup with a lot of users. However, at my small setup I will consider it. ;-)
