### ISSUE TITLE
Thumbnails previews not show under share from Nextcloud server 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#2729]
### Steps to reproduce

1. Open Chat
2. select Attach Icon
3. Select Share From "Nextcloud Server"
4. Select the file that you want to share
5.

### Expected behaviour

Should show thumbnail preview of the photos\files 

### Actual behaviour

![Screenshot_20230130_125750_Talk](https://user-images.githubusercontent.com/59488153/215569861-b2879dab-7b11-4b9a-89a1-ac5bd75fa2cf.jpg)

### Device brand and model

S22 Ultra 5G

### Android version

13

### Nextcloud Talk app version

3.24.0 RC2

### Nextcloud server version

25.0.3

### Talk version

15.0.3

### Custom Signaling server configured

No

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

### Android logs

N/A

### Server log

```bash
N/A
```

### Additional information

N/A

**Comment by AndyScherzinger** [comment]
@mahibi you might have an idea, I would expect this to be related to the `coil` migration
