### ISSUE TITLE
Avatar not shown in conversation list

### ISSUE THREAD

**Issue by alexara** [nextcloud/talk-android#273]
Talk version: 3.0.0beta1
Phone: Galaxy S7 (Android 8)

The contact list shows all avatars.
However, in case no avatar was set, the conversation list only shows the letter avatars and for all other contacts a gray pictogram of a stylized person.

**Edit:** As I just found out, this issue only effects duplicates of conversations. Eg I have two conversations open with the same user, i.e. the username appears twice in the conversations list - which is already confusing. So this is probably a different issue overall...

**Comment by mario** [comment]
Two conversations with the same user? That sounds VERY strange and is probably a setup issue.
What version of Spreed app on the server do you have?

**Comment by mario** [comment]
@nickvergessen have you ever seen an issue with two conversations existing for the same user? (one2one)

**Comment by alexara** [comment]
> What version of Spreed app on the server do you have?
The current one, 3.2.5 on NC 13.0.5

I will observe it and in case it will happen again, I will report back. For the setup I followed completely the installation guide. ;-)

**Comment by Ivansss** [comment]
That could be the result of making a one2one conversation public and then private again.
The result is a group conversation with that user only. The conversation name will still be the display name of the other user but the avatar will be a group conversation icon since that's the current conversation type.

**Comment by mario** [comment]
Probably true @Ivansss .
