### ISSUE TITLE
App shows responsive web layout if a different login flow is used

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/talk-android#274]
On https://nextcloud-live.com the login screen of the NC offers both SAML and Direct Login.

This causes the Talk app to behave like a responsive web app rather than showing the Talk widgets. After logging in, this is what I see in the Talk app:

I had a similar issue with the NC Files app which has meanwhile been fixed and seems to be related to the login flow on the server being different than the standard.

![screenshot_20180806-065522](https://user-images.githubusercontent.com/295122/43697763-91a0f9c8-9946-11e8-9136-d7963d25916f.png)

**Comment by mario** [comment]
HI @mathiasconradt.

1) Test account please
2) Afaik, only OUR login flow provisions app token which is needed for Talk to receive notifications, so even if we make this work push notifications won't work making Talk pretty useless AFAIK :)

**Comment by mathiasconradt** [comment]
I'm using the direct login (username / password of local user), it's just that this NC instance offers two login mechanism for a user to choose before the actual login page.

**Comment by mario** [comment]
This is an issue with the link leading to a regular Nextcloud login instead of a flow login, therefore closing as there's not much (anything?) we can do about it.
