### ISSUE TITLE
No notification at all on latest F-Droid version

### ISSUE THREAD

**Issue by Almtesh** [nextcloud/talk-android#2782]
### Steps to reproduce

1. Install the latest version from the F-Droid repository
2. Connect it to the latest Nextcloud talk in the latest stable Nextcloud
3. Create a chatroom with guests
4. Close all connected browsers and connect to chatroom as guest
5. Send a message as guest

### Expected behaviour

As no other client see the new messages, the app should produce some notifications for the new messages from guest.

### Actual behaviour

The app does not produce any notification (vibration, sound, like in the notification area).

### Device brand and model

Fairphone 3

### Android version

11

### Nextcloud Talk app version

15.1.1

### Nextcloud server version

23.0.12

### Talk version

13.0.11

### Custom Signaling server configured

No

### Custom TURN server configured

Yes

### Custom STUN server configured

No

### Additional information

To try to solve myself the problem, I tried to allow all notification from the app, disable every battery optimization option for the app and the system. The behavior has been tried with phone on charger and screen on.

**Comment by mahibi** [comment]
Dear @Almtesh ,
unfortunately notifications are not supported for the fdroid version atm. 
See https://github.com/nextcloud/talk-android/blob/master/docs/notifications.md
Please install from gplay to get notification support.
