### ISSUE TITLE
send raise hand signaling messages

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2783]
in https://github.com/nextcloud/talk-android/pull/2715 the UI for raise hand and request assistance for breakout rooms was introduced.
However, the signaling messages for raise hands are not yet sent. 
This still needs to be implemented, see:

https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/activities/CallActivity.java#L425

https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java#L193

**Comment by nickvergessen** [comment]
Duplicate of #1056
