### ISSUE TITLE
Problem with connexion

### ISSUE THREAD

**Issue by pierrecdlc** [nextcloud/talk-android#28]

**Comment by pierrecdlc** [comment]
What's the server url ? Because I enter : http://account.gamacloud.com/gamacloud/index.php/apps/spreed

But it don't work... How can i do ?

**Comment by pierrecdlc** [comment]
Unexpected character "<" (code 60)): expected a valid value (number, String, array, object, true, false 'or' null) at [Source: buffer (buffer (okio .Gzipsource @ ef2f94f))) input Stream0; line: 1, column: 2]

**Comment by mario** [comment]
The url would be just http://account.gamacloud.com/gamacloud.

**Comment by mario** [comment]
I will do a new release soon so it'll work with Gamacloud.
