### ISSUE TITLE
Not receiving calls in background or foreground

### ISSUE THREAD

**Issue by developerfromjokela** [nextcloud/talk-android#281]
When my collegue calls me, and I am not in app, I don't receive popup or notification about incoming call.
When I am in the app, and he calls me again, I can see incoming call screen.

**Comment by mario** [comment]
What version of the app, what phone, what Android version?

**Comment by developerfromjokela** [comment]
App Version v2.1.2 Phone Moto G5 Plus, android 8.1 (using Custom Rom)

**Comment by mario** [comment]
Can you try the beta version pls?

**Comment by developerfromjokela** [comment]
Ok I will try, where I download it?

su 12. elok. 2018 klo 22.14 Mario Đanić <notifications@github.com>
kirjoitti:

**Comment by mario** [comment]
https://play.google.com/apps/testing/com.nextcloud.talk2

**Comment by mario** [comment]
@developerfromjokela any news?

**Comment by developerfromjokela** [comment]
So, Now When I receive call, activity shows up for 1 second as white then
it exits.

ti 14. elok. 2018 klo 21.26 Mario Đanić (notifications@github.com)
kirjoitti:

**Comment by mario** [comment]
@developerfromjokela I will have beta5 out soon.

**Comment by developerfromjokela** [comment]
Ok, I will check when it's released and keep you up to date.

**Comment by mario** [comment]
Beta6 is out. Please try @developerfromjokela .

**Comment by developerfromjokela** [comment]
Ok, I will try it.

**Comment by developerfromjokela** [comment]
It works now fine

**Comment by developerfromjokela** [comment]
When I close app and someone calls me it opens Activity

**Comment by mario** [comment]
Thanks.

**Comment by simo97** [comment]
Hi actually i have the same problem.. but mine is working perfectly on the Play store's version... but the code on the repo is not working the same way. How can i do please ?

**Comment by developerfromjokela** [comment]
Hello!
I will be back at afternoon (GMT+2.00 Finland Time).

Regards,
@developerfromjokela

**Comment by mario** [comment]
@simo97 you need to create your own Firebase project and update the references to this.

**Comment by simo97** [comment]
the references... let me check... i made a reverse of the play store version and i saw it within the manifest file... and a lot of permissions

**Comment by mario** [comment]
all the permissions that are in the Gplay are also in this repository.

**Comment by simo97** [comment]
The two manifest files are differents.. from what i saw.

**Comment by mario** [comment]
You can see both in the repository via builds.

**Comment by simo97** [comment]
Oh i see... it is here : https://github.com/nextcloud/talk-android/tree/master/app/src/gplay
So i will have to merge them and add the firebase services  to get it working or is there a compilation rules command i should use ?

**Comment by mario** [comment]
It's a separate build type so just use Android Studio or gradlew to build a gplay build.

**Comment by simo97** [comment]
> It's a separate build type so just use Android Studio or gradlew to build a gplay build.

yep.. i just saw it. I am building for a new test

**Comment by simo97** [comment]
i did it.. put nothing !!! is there anything i need to add on the server itself ?

**Comment by mario** [comment]
You need to create a Firebase project and change the references in the setup.xml to the project.

**Comment by simo97** [comment]
i did it already. But when receiving calls (for eg) i just see the small ```@user join the call``` but nothing else. In setup.xml i've saw :
 ```<string name="nc_push_server_url" translatable="false">https://push-notifications.nextcloud.com</string>```

Is there anything to do with that ?

**Comment by mario** [comment]
Nop, that's the one to use. And for further debugging I'd have to dig into your changes which is not something I can really do, sorry about that :-/

**Comment by simo97** [comment]
hummmm do i need to touch anything in AndroidManifest.xml ? like specific stuff related to firebase integration ?

**Comment by simo97** [comment]
Still nothing even when i test the actual version in this repo with gplay build type.. without changing nothing
