### ISSUE TITLE
Guest names not shown, says "{actor}"

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#282]
See this:

![](https://i.imgur.com/LAP21R1.png)

Instead the guest name should be shown, or in absence of a name, simply "Guest joined the call".

**Comment by mario** [comment]
I would appreciate if you wrote a version of the app. Right now I know it's beta4, just by luck :)

**Comment by jancborchardt** [comment]
Right, sorry – will include the version in the future.
