### ISSUE TITLE
Feature Request Screen Sharing

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/talk-android#2842]
It would be nice if the screen of an IOS Device can be shared.
For example from an Ipad,
If external screens are connected the screen should be chooseable.

**Comment by mahibi** [comment]
duplicate of https://github.com/nextcloud/talk-android/issues/1530

for iOS please have a look at https://github.com/nextcloud/talk-ios

**Comment by MrLoverLoverMMMM** [comment]
I would really be happy if this feature would not be set to ice.
Goto Webinar, Goto Meeting, Teams,... many more already support screenshare.
I wanna use my phone for presentations in Samsung Dex and with this feature I could replace my presentation pc.
