### ISSUE TITLE
v3.0.0beta5 "Settings" tab provokes error

### ISSUE THREAD

**Issue by mikelupe** [nextcloud/talk-android#285]
- v3.0.0beta5
- LineageOS 7.x
- APK download and install from here.
- no gapps, no micro-g

"Unterhaltung" and "Kontakte" works when switching tabs, "Einstellungen" gives "Nextcloud Talk wurde beendet".

Thanks for your work, Mario.

**Comment by jookk** [comment]
+1 on stock 7.1.1 moto g5s plus

**Comment by ArtJames** [comment]
+1 on stock 5.1 (Wiko Pulp, Odys Neo6) - Google Playstore
I tried a clean reinstall. (Data & cache cleaned) Get 'cypherSuite TLS_DHE_RSA...' error message when asked for server to connect to. Let’s Encrypt certificates up to date and working. 
Old 2.x version still works without any problems.

**Comment by mario** [comment]
Thanks folks.

@ArtJames this sounds VERY strange. There were no changes in regards to cipher suites.

**Comment by jookk** [comment]
And with notifications?

**Comment by mario** [comment]
@jookk what's happening with notifications?

**Comment by mario** [comment]
Fixed in beta6. Thanks for testing folks!

@ArtJames pls let me know if you still have issues with ciphers afterwards.

**Comment by fraengii** [comment]
I'm sorry but where can I get the APK?
:-[

Am 16. August 2018 16:52:33 MESZ schrieb mikelupe <notifications@github.com>:
>- v3.0.0beta5
>- LineageOS 7.x
>- APK download and install from here.
>
>"Unterhaltung" and "Kontakte" works when switching tabs,
>"Einstellungen" gives "Nextcloud Talk wurde beendet".
>
>Thanks for your work, Mario.

**Comment by mikelupe** [comment]
Thanks - settings working :)

**Comment by ArtJames** [comment]
After further unsuccessful tests with beta 6 I went back to 2.1.0.

**Comment by mario** [comment]
Fair enough @ArtJames - can you get me a test account at mario@nextcloud.com?

**Comment by mario** [comment]
@fraengii is Google Play beta channel good enough or you want a direct link to APK?

https://play.google.com/apps/testing/com.nextcloud.talk2

**Comment by jookk** [comment]
On Android 5.1 still crashing

**Comment by fraengii** [comment]
If there is a chance to have a direct link I would prefer this.
Thank you!

Am 17. August 2018 06:52:12 MESZ schrieb "Mario Đanić" <notifications@github.com>:
>@fraengii is Google Play beta channel good enough or you want a direct
>link to APK?
>
>https://play.google.com/apps/testing/com.nextcloud.talk2

**Comment by mikelupe** [comment]
@fraengii 
- https://github.com/nextcloud/talk-android/releases
- or even more direct: 
https://github.com/nextcloud/talk-android/releases/download/v3.0.0beta6/nextcloud-talk.apk

**Comment by fraengii** [comment]
@mikelupe, many thanks!!!

Am 17. August 2018 12:39:43 MESZ schrieb mikelupe <notifications@github.com>:
>@fraengii 
>- https://github.com/nextcloud/talk-android/releases
>- or even more direct: 
>https://github.com/nextcloud/talk-android/releases/download/v3.0.0beta6/nextcloud-talk.apk
