### ISSUE TITLE
No notification sound

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#286]
NC Talk v3.0b6
Notifications workiing, but without sound. Vibrations working if enabled.
No sound notifications in new call and messages.

**Comment by mario** [comment]
Sound turned on, and you're not in Do Not Disturb mode?

**Comment by jookk** [comment]
Sound tunned on and dnd off

**Comment by jookk** [comment]
B7 
New call notifications - working with sound
New msg notif - no sound, only vibration, if enabled.

**Comment by jookk** [comment]
After app reinstall the same as before
