### ISSUE TITLE
Navigation pannel missing

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#287]
NCTalk v3.0b6
![screenshot_20180817-072639](https://user-images.githubusercontent.com/11217085/44249503-73b0f500-a1f0-11e8-83e2-11da04925c83.png)

Ocurred by navigating from Settings.

**Comment by mario** [comment]
Phone & Android version pls.

**Comment by jookk** [comment]
Moto g5s plus android 7.1.1 stock
Sfter click to hw back button, app goes to calls screen and pannel is ok now

**Comment by mario** [comment]
Strange. Please try to give me reproduction steps so I can try to fix it.

**Comment by jookk** [comment]
I cant reproduce. Tried but I cant

**Comment by mario** [comment]
OK, please re-open the issue if you find a way :)
