### ISSUE TITLE
End for all option

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-android#2874]
Hello now that the Talk via web has an option to end for all it would be nice to have this under the mobile app also

**Comment by Smarshal21** [comment]
Is this still an issue? 
i can see the code for it

**Comment by mahibi** [comment]
there is code that should handle when others hung up the call.

A button to hangup for all in the android app is not yet implemented.
Might be helpful to have a look at the iOS code:
https://github.com/nextcloud/talk-ios/pull/1237/files

**Comment by AndyXheli** [comment]
Hi @Smarshal21 just wanted to see if you may have any progress on this ?

**Comment by Smarshal21** [comment]
> Hi @Smarshal21 just wanted to see if you may have any progress on this ?

i stopped working on this issue. Was busy with other issues
