### ISSUE TITLE
Cant call with app

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#288]
This seems only beta 5, 6 related. (not sure) NC14.b4
Audio, video calls are not established together. Cant see other video, hear other audio and other side cant see, hear me. 
After end call, app returns message that call duration is...
Tried on local net and from my 4G cell.

**Comment by mario** [comment]
@jookk can you please uninstall and then install the app again? I will test the upgrade process in the mean time.

**Comment by mario** [comment]
Found the issue.

**Comment by jookk** [comment]
So:
Removed app data, removed app, restarted device, install from store and the same.

**Comment by mario** [comment]
@jookk did this happen with 2.x too? Because this is an issue with Google Play Services failing to update your supported ciphers.
