### ISSUE TITLE
3.0 beta6 cannot join conversations

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/talk-android#289]
After update to beta6 i cannot join conversations anymore (it may be like this with beta5 but i had that one installed for a little time).
I can set up the app with importing the authentication from the Nextcloud app, user list and conversation list loads. But if i tap one conversation, i get the spinning circle indefinitely (it seems to be the bigger one, not the small one which is shown when updating a list). Sometimes if i press the back button i am taken to the page with the authentication again. But if i press back again i am taken back to the conversation and user list. 
Reinstalled the appa few times, it just doesn't work for me. Notifications work, but if i tap them i am taken to the conversation with the spinning circle again.
NC server is 13.0.5, Talk server app 3.2.5

**Comment by jookk** [comment]
Similar?  https://github.com/nextcloud/talk-android/issues/288

**Comment by gradinaruvasile** [comment]
Maybe, but i cannot even enter the text conversations. Sometimes the top bar loads, but the audio/video buttons do nothing. Once i managed to join via the calling screen, but nothing came from the other side.
BTW i got phantom incoming calls mostly.

**Comment by mario** [comment]
Should be fixed in another beta. If not, test acc pls to my mail (mario@nextcloud.com).

**Comment by mario** [comment]
@gradinaruvasile could you try uninstalling and installing the app again?

**Comment by mario** [comment]
@gradinaruvasile found the issue. Pushing it now.

**Comment by mario** [comment]
Beta8 is out!

**Comment by gradinaruvasile** [comment]
It works now.

**Comment by mario** [comment]
Thanks for the feedback and testing!

I've significantly rewritten the way we do networking, so some problems slipped in it looks like!
