### ISSUE TITLE
Site not recognised as Nextcloud

### ISSUE THREAD

**Issue by vikingredwolf** [nextcloud/talk-android#29]
The android app doesn't recognise my server as a valid Nextcloud site. It accepts my certificate and then it gets stuck.

**Comment by mario** [comment]
Does your status.php show "productname" as "Nextcloud"?

**Comment by vikingredwolf** [comment]
That file is "untouched". It contains this:
'productname'=>$defaults->getName());

**Comment by mario** [comment]
Can you mail me pls with the url? mario@nextcloud.com

**Comment by vikingredwolf** [comment]
Sure!
