### ISSUE TITLE
Idea: Add social function (like Status in whatsapp or Storys in Signal)

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#2924]
In social we have no mobile app. 
But maybe we can use the talk app to post to the social app and read the follower status like the Status feature in whatsapp or Storys in the Signal App.
Just an idea, what do you guys think?

**Comment by mahibi** [comment]
i guess it's out of scope for now but maybe @nickvergessen has an opionion

**Comment by nickvergessen** [comment]
We are not going to implement social in talk clients
