### ISSUE TITLE
scroll to first unread message instead end of chat

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2926]
### Steps to reproduce

1. open chat with many unread messages

### Expected behaviour

scroll to first unread message

### Actual behaviour

scroll to end

### Nextcloud Talk app version

16.0

**Comment by R7JANV1** [comment]
You should automatically scroll to the first unread message as soon as you open the chat and then use the button to scroll to the bottom if you don't want to read all the messages. Imho.

**Comment by mahibi** [comment]
> You should automatically scroll to the first unread message as soon as you open the chat and then use the button to scroll to the bottom if you don't want to read all the messages. Imho.

thats how it works with the fix https://github.com/nextcloud/talk-android/pull/2927
