### ISSUE TITLE
Most methods in source code cannot be resolved

### ISSUE THREAD

**Issue by developerfromjokela** [nextcloud/talk-android#294]
Hello!

I downloaded Source code (latest) and I'm getting errors of most voids in source code .java files.

How can I fix them?

**Comment by developerfromjokela** [comment]
https://i.imgur.com/p3mDsMG.png

**Comment by mario** [comment]
I'll check it out, but it should be fine.

**Comment by developerfromjokela** [comment]
Ok, Thanks!

**Comment by developerfromjokela** [comment]
Any news?

**Comment by mario** [comment]
I compiled this a few times today already, so it definitely works. Do a clean & rebuild pls.
