### ISSUE TITLE
Icon in notification bar is too large

### ISSUE THREAD

**Issue by pschopen** [nextcloud/talk-android#2945]
### Steps to reproduce

1. Receive message from someone

### Expected behaviour

The notification icon should be the same size as the icons of other messenger apps like whatsapp or signal.

### Actual behaviour

The icon is larger than other icons.

### Device brand and model

Nokia X10

### Android version

11

### Nextcloud Talk app version

16.0.0

### Nextcloud server version

25

### Talk version

16.0.0

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by Smarshal21** [comment]
i see it as a normal icon 
and the code seems to set a small icon too

**Comment by mahibi** [comment]
![grafik](https://github.com/nextcloud/talk-android/assets/2932790/5e3509e0-c2bb-4ec1-85cf-0ee3bf0b3137)

![grafik](https://github.com/nextcloud/talk-android/assets/2932790/72a152d6-1e9d-4f32-949f-4418d06bc34c)

This is how it looks on a redmi note 7 (talk is maybe a tiny bit larger than the other icons).
Is it this kind of difference we're talking about or does it look different on your Nokia X10?

**Comment by pschopen** [comment]
This is how it looks on Nokia, too. I guess it's about 10% too large compared to the other icons.

**Comment by Smarshal21** [comment]
I tried fixing this issue here - https://github.com/nextcloud/talk-android/pull/3275
