### ISSUE TITLE
replace deprecated onBackPressed

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2961]
onBackPressed is deprecated with api 33

migration guides:
https://medium.com/tech-takeaways/how-to-migrate-the-deprecated-onbackpressed-function-e66bb29fa2fd
https://www.youtube.com/watch?v=UsPJLG6ztBg

**Comment by ezhil56x** [comment]
I'm interested in fixing this. Is it already done or yet to be done ?

**Comment by ezhil56x** [comment]
Happy to hear this @mahibi, will wait for the invite to join the android nextcloud team

**Comment by ezhil56x** [comment]
@mahibi I have replaced deprecated onBackPressed and pushed it into issue-2961 branch. I am not sure what should I include in the write section in the Create Pull Request. Can you guide me so that I will write and create a pull request

**Comment by AndyScherzinger** [comment]
Hi @ezhil56x - Just open a PR with the template, don't worry too much about the content. @mahibi and I can take care of that 👍 
Having the PR will help with getting it reviewed to provide you with feedback in case changes might be needed. Thanks for having picked up this issue 👍

**Comment by ezhil56x** [comment]
@AndyScherzinger I have opened Pull Request with the default template
