### ISSUE TITLE
Unlock Channel switch is gone and write message field

### ISSUE THREAD

**Issue by wolfshade1** [nextcloud/talk-android#2965]
### Steps to reproduce

1. Lock a channel in Website
2. Open Channel Settings in App - there's no switch to lock or unlock anymore
3. Step back to channel
4. You see the message field which still should be invisible

### Expected behaviour

The switch to unlock or lock the channel should be in settings and the the message field should be invisible

### Actual behaviour

 there's no switch to lock or unlock anymore
You see the message field which still should be invisible when you step back from settings to channel

### Device brand and model

Motorola

### Android version

12

### Nextcloud Talk app version

16.0.1

### Nextcloud server version

24.0.12

### Talk version

14.0.10

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment]
the switch in settings is not yet implemented. feature request is #1028

> 4. You see the message field which still should be invisible

this doesn't happen for me on master, so should be fixed with latest remodelings.


i will close this issue and mention on #1028 to double check that message field is invisible when conversation is locked.
