### ISSUE TITLE
Send postings in locked Channels for Channel-Creator and Moderators

### ISSUE THREAD

**Issue by wolfshade1** [nextcloud/talk-android#2966]
**Is your feature request related to a problem? Please describe.**
I use an "Announcement" Channel where only information is shared and no discussion should happen. Therefore I need to unlock the channel, sent the info and lock the channel before someone posts anything.

**Describe the solution you'd like**
If the creator, admin or moderator could post something even the channel is locked would solve my problem.

**Describe alternatives you've considered**
Unlock and lock the channel for announcement. Mostly it works but sometimes I have to delete posts of the members.

**Comment by mahibi** [comment]
you can do this by modifying the permissions of a conversation (currently only possible from web). Please have a look at restricted and advanced permissions.

![grafik](https://user-images.githubusercontent.com/2932790/234217753-43ea55cf-a6af-439a-9b79-8c7537b70eaa.png)

**Comment by wolfshade1** [comment]
Hey,
doesn't work. I can't take the right away to post a message. That's the reason why I asked for the feature, that admin or moderator can post a message in an locked channel.

Maybe wrong in Android, true. I would write it into the Web-App enhancements

**Comment by mahibi** [comment]
okay, please open an issue at https://github.com/nextcloud/spreed/issues
Sounds like something with the permissions has to be fixed instead to be able to post to "locked" conversations
