### ISSUE TITLE
Suggestion : continuous calls of StringBuilder.append

### ISSUE THREAD

**Issue by o0lwj0o** [nextcloud/talk-android#297]
Hi,
    I have found some continuous calls about StringBuilder.append(..) in some files. For example, there are several continuous calls from line 1549 to 1558 in the file https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/controllers/CallController.java

        // Set all we need
        ncSignalingMessage.setPayload(ncMessagePayload);
        ncMessageWrapper.setSignalingMessage(ncSignalingMessage);

        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("{");
        stringBuilder.append("\"fn\":\"");
        stringBuilder.append(StringEscapeUtils.escapeJson(LoganSquare.serialize(ncMessageWrapper
                .getSignalingMessage()))).append("\"");
        stringBuilder.append(",");
        stringBuilder.append("\"sessionId\":");
        stringBuilder.append("\"").append(StringEscapeUtils.escapeJson(callSession)).append("\"");
        stringBuilder.append(",");
        stringBuilder.append("\"ev\":\"message\"");
        stringBuilder.append("}");

    If it was achieved like StringBuilder.append(..).append(..)append(..), it will promote its performance.

**Comment by mario** [comment]
Why don't you submit a PR? :)
