### ISSUE TITLE
F-Droid - webrtc should be either built from source or pulled from maven

### ISSUE THREAD

**Issue by licaon-kter** [nextcloud/talk-android#2972]
ref: https://f-droid.org/docs/Inclusion_Policy/

Since: https://github.com/nextcloud/talk-android/tree/v14.0.0 ref: https://github.com/nextcloud/talk-android/commit/bad5b5f9bccae7f88eb533cf900094956487849f#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R260

ref: https://github.com/nextcloud/talk-android/blob/v16.0.1/buildSrc/src/main/groovy/com/nextcloud/talk/gradle/DownloadWebRtcTask.groovy#L48

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4159622028#L957

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/d06a8ede972819102f2ec2d5e329f2f7d150aba3

**Comment by licaon-kter** [comment]
ref: https://gitlab.com/fdroid/fdroiddata/-/issues/2064

**Comment by AndyScherzinger** [comment]
Not a bug but rather a feature request since f-droid created the requirement to compile binary dependencies themselves.

So contributions are welcome, we currently build and ship WebRTC ourselves, for reasons also mentioned in the referenced discussions, since they are published to maven anymore by the original authors, so "pulling from maven" is no option any longer afaik.

Would you be willing to work on a contribution for the f-droid build variant here @licaon-kter ? For the building see https://github.com/nextcloud-releases/talk-clients-webrtc

**Comment by licaon-kter** [comment]
We've asked Conversations devs (and fork Snikket) to host in maven.

That's the best-est solution for now unfortunately.

Yes, still not built by F-Droid, but...

ref: https://f-droid.org/2022/07/22/maven-central.html

**Comment by licaon-kter** [comment]
> Would you be willing to work on a contribution for the f-droid build variant here

I've already banged my head, see https://gitlab.com/fdroid/fdroiddata/-/issues/2064

If someone else, some dev of sorts :), can make it built without using 20Gb of Google downloaded binaries, we'll gladly take that recipe

**Comment by AndyScherzinger** [comment]
> We've asked Conversations devs (and fork Snikket) to host in maven.

Do you have a direct link, to have all referecing aspects right?

**Comment by licaon-kter** [comment]
https://github.com/snikket-im/webrtc-android

https://codeberg.org/iNPUTmice/webrtc-android

No references on the "how to upload to maven central" unfortunately, but I guess it's "common Internet knowledge" or so I heard :)

**Comment by licaon-kter** [comment]
I've seen this issue while fixing past failed builds, but did not notice that it got in the current cycle already.

So 16.0.1 was built, https://monitor.f-droid.org/builds/log/com.nextcloud.talk2/160000190#site-footer , will be published, and in the next cycle, disabled with the rest.

**Comment by licaon-kter** [comment]
As the links above show... I agree :) :(

**Comment by AndyScherzinger** [comment]
I'll be pushing a fix this week for the next stable releases 👍

**Comment by AndyScherzinger** [comment]
Well, fix is there #2977 so the upcoming releases will respect the f-droid requirement.

**Comment by licaon-kter** [comment]
Thanks https://gitlab.com/fdroid/fdroiddata/-/commit/744f2b8f991b27c3a53cff456d3c9384868ed38c

**Comment by AndyScherzinger** [comment]
Nice and thanks @licaon-kter

Looking forward to see it published 👍
