### ISSUE TITLE
Suggestion : continuous calls of StringBuilder.append

### ISSUE THREAD

**Issue by o0lwj0o** [nextcloud/talk-android#298]
Hi,
    I have found some continuous calls about StringBuilder.append(..) in some files. For example, there are several continuous calls from line 168 to 173 , 180-182  in the file https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/webrtc/MagicProximitySensor.java

private void logProximitySensorInfo() {
        if (proximitySensor == null) {
            return;
        }
        StringBuilder info = new StringBuilder("Proximity sensor: ");
        info.append("name=").append(proximitySensor.getName());
        info.append(", vendor: ").append(proximitySensor.getVendor());
        info.append(", power: ").append(proximitySensor.getPower());
        info.append(", resolution: ").append(proximitySensor.getResolution());
        info.append(", max range: ").append(proximitySensor.getMaximumRange());
        info.append(", min delay: ").append(proximitySensor.getMinDelay());
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT_WATCH) {
            // Added in API level 20.
            info.append(", type: ").append(proximitySensor.getStringType());
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            // Added in API level 21.
            info.append(", max delay: ").append(proximitySensor.getMaxDelay());
            info.append(", reporting mode: ").append(proximitySensor.getReportingMode());
            info.append(", isWakeUpSensor: ").append(proximitySensor.isWakeUpSensor());
        }
        Log.d(TAG, info.toString());
}

    If it was achieved like StringBuilder.append(..).append(..)append(..), it will promote its performance.

**Comment by mario** [comment]
Why don't you submit a PR? :)

**Comment by o0lwj0o** [comment]
Thank you for your advice. It's worth a try.

**Comment by o0lwj0o** [comment]
Thank you for your advice. It's worth a try.
