### ISSUE TITLE
Translations not available

### ISSUE THREAD

**Issue by benhartwich** [nextcloud/talk-android#299]
Hi,

I´m beta tester of Nextcloud Talk and have installed your great app on a Huawei 20 Pro yesterday (Android 8.1). After I`m logged in I see "Benötigt keine Übersetzung" at every button: 
![screenshot_20180826-090703](https://user-images.githubusercontent.com/4061954/44625699-dbadbc80-a90f-11e8-9d9f-b426627a112c.jpg)

**Comment by mario** [comment]
Thank you for your report. Can you please tell me what locale are you using so I can try to reproduce and hopefully fix the issue?

Thanks, Mario!

**Comment by benhartwich** [comment]
Thanks! I´ve set German (Austria) at my language settings.

**Comment by mario** [comment]
Version of Android please?

**Comment by benhartwich** [comment]
Android: 8.1.0, Kernel Version 4.4.103+

**Comment by mario** [comment]
Could you translate it to de_AT pls? 

https://www.transifex.com/nextcloud/nextcloud/android-talk/

**Comment by mario** [comment]
(Never seen this error btw, must be something with Android 8.1)

**Comment by benhartwich** [comment]
Thanks! No problem.

**Comment by mario** [comment]
Fixed. Will be in next beta.

**Comment by MorrisJobke** [comment]
Yes - was fixed with an updated transifex sync. :/
