### ISSUE TITLE
Upgrade chat text colors

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-android#2993]
What do you all think about making the text color more colorfull like adding a blue for the send and gray\white for the resived 

![Screenshot_20230501_195327_Teams.jpg](https://user-images.githubusercontent.com/59488153/235556929-3459396c-63d4-492c-a497-50e59efda978.jpg)

**Comment by mahibi** [comment]
You mean the bubble color right?
As only the android talk app use bubbles it might be possible to do, but opinions regarding the colors are quite different i guess. Maybe @AndyScherzinger has an opinion?

**Comment by AndyXheli** [comment]
Yes correct the chat color like you see in the above picture or like in google messages but not give the option to choose our own dose that make sence

**Comment by AndyScherzinger** [comment]
The bubbles are colored actually in a shade of blue based on the material 3 palette but not the "primary" color which is very vibrant to put it nicely. So we explicitly decided to go with the container-colors instead. Just i.e. change your server's color to red or green to see the subtile change.
Using the container color ensures we have a proper contrast with the text for accessibility reasons. SO in a way I expect Google to also adapt their colors at some point (i.e. the messages app).

**Comment by AndyScherzinger** [comment]
See https://github.com/nextcloud/talk-android/pull/2084 for the screenshots showing when we moved away from the primary color.
