### ISSUE TITLE
Text input is cleared when switching app

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#2999]
### Steps to reproduce

1. Start typing a message
2. Go to another app to copy text or a link or anything
3. Go back to talk to add it to your message

### Expected behaviour

You see your previously typed message and continue with pasting the information, etc.

### Actual behaviour

Chat input is cleared and your message is gone

### Device brand and model

-

### Android version

-

### Nextcloud Talk app version

-

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

### Additional information

I assume this is from the conductor framework restructuring

**Comment by mahibi** [comment]
related code parts for this are:

in manifest:
        <activity
            android:name=".chat.ChatActivity"
            android:launchMode="singleInstance"
            android:noHistory="true"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme" />

--> see commit ae9e9924

and in ChatActivity:
 binding?.messageInputView?.inputEditText?.setText(sharedText)
