### ISSUE TITLE
Granting permissions

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#30]
![2017-12-15-150545](https://user-images.githubusercontent.com/5836855/34045527-8afc9f3c-e1a9-11e7-9315-6b187be7e65f.png)

Instead of letting the user enable permissions on settings, it should directly ask for the permission, like on nextcloud app:
![2017-12-15-150732](https://user-images.githubusercontent.com/5836855/34045552-b0ffeb9e-e1a9-11e7-80ef-3a4a19f2c318.png)

Code reference: https://github.com/nextcloud/android/blob/61cbe88bd056ec1ec2f3933a8175cdc6a4252c6c/src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsBackupFragment.java#L346-L376

**Comment by mario** [comment]
This should already work. I'll investigate.
