### ISSUE TITLE
App showing duplicate text

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-android#3012]
### Steps to reproduce

Send a message or get a message. 

If i close the app and reopen it the duplicate messages go away 

### Expected behaviour

Should not see the text more then once

### Actual behaviour

See more then onvce

### Device brand and model

Samsung S22 Ultra

### Android version

13

### Nextcloud Talk app version

17.0.0 RC2

### Nextcloud server version

26.0.1

### Talk version

16.0.3

### Custom Signaling server configured

No

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

**Comment by mahibi** [comment]
can not reproduce this yet.
does this happen all the time for you or only sometimes?

**Comment by AndyXheli** [comment]
right now its not doing it. but yesterday all day a ios user was sending me messages and i was going doubles and when i was seding i was seeing doubles other users had no issues

**Comment by AndyXheli** [comment]
Issue back again. Seem to be more related when i get a text from a user other user is using an IOS device not sure if it has anything to do with it
