### ISSUE TITLE
Quotes are not "shortened"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#3026]
### Steps to reproduce

1. Write a long message
2. Reply to it

### Expected behaviour

Like in the web only a limited amount of content is in the quote, web is 250 chars:
https://github.com/nextcloud/spreed/blob/1ffd8e58910e048a07fabc123834cb1d5b7ed075/src/components/Quote.vue#L221-L230

### Actual behaviour

Full text is shown

### Device brand and model

Xiaomi RedMi Note 8

### Android version

11

### Nextcloud Talk app version

17.8.0 alpha 2

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by AndyScherzinger** [comment]
@rapterjet2004 I think @mahibi created a text-shortening-ellipsizing function with the typing indicator PR - you can make use of :)

**Comment by mahibi** [comment]
i don't think it's necessary to use it.

```
        <androidx.emoji2.widget.EmojiTextView
            android:id="@+id/quotedMessage"
            ....
            android:maxLines="4"
            android:ellipsize="end"
```

in item_message_quote.xml
should just be fine..

**Comment by AndyScherzinger** [comment]
@mahibi that would shorten it to 4 lines max.
The amount of text it then dynamic since you have way more space in landscape mode than portrait. So I would go with the fixed 250 to have the same experience than web. Can't tell if or what iOS is doing though.

**Comment by nickvergessen** [comment]
cc @Ivansss for iOS knowledge

**Comment by AndyScherzinger** [comment]
Max 4 lines and max 250 sounds like a good idea 👍
