### ISSUE TITLE
get rid of StoreBox

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#3043]
[StoreBox](https://github.com/martino2k6/StoreBox) is used to store [SharedPreferences](https://developer.android.com/training/data-storage/shared-preferences). StoreBox is outdated as well as usage of SharedPreferences is not recommended anymore.

StoreBox also causes Lint warnings when using @KeyByResource annotation: "Resource IDs will be non-final by default in Android Gradle Plugin version 8.0, avoid using them as annotation attributes" 

We should replace StoreBox with modern solutions like datasore:
https://developer.android.com/topic/libraries/architecture/datastore

**Comment by mahibi** [comment]
https://www.youtube.com/watch?v=mdQjuZbLv9Y

**Comment by Smarshal21** [comment]
is this issue open?

**Comment by rapterjet2004** [comment]
@Smarshal21 Yes, but I'm assigned to it. You can see whose assigned to an issue by checking the "Assignees" section on sidebar. I put it on hold as I'm working on the remind-me-later feature, which is more important.

**Comment by Smarshal21** [comment]
yeah sure 
Thank you @rapterjet2004
