### ISSUE TITLE
"Share with ..." function (Android)

### ISSUE THREAD

**Issue by R4U5CH1337** [nextcloud/talk-android#308]
Hi
I was wondering why I can't find Nextcloud Talk in my list when I try to share sth. like in my Brave Browser (LOS 15.1)? Did I miss something or this right?
I would be really happy if there'll be this feature to simply share links directly with my contacts.
Thanks a lot!

**Comment by mario** [comment]
Good idea. I'll add it eventually!

**Comment by mario** [comment]
https://github.com/nextcloud/talk-android/issues/312#issuecomment-433984317

**Comment by szaimen** [comment]
Any update on this?

**Comment by szaimen** [comment]
This feature could probably be implemented before  https://github.com/nextcloud/talk-android/issues/435 and could work like that:
1. Open a website in the browser
2. Click on "share"
3. Select nectcloud-talk from the sharing list
4a. Press short to select one chat that you want to share the link with
4b. Press long to select get into batch-mode to select one or more chats that you want to share the link with and press afterwards okay
5. Press okay or cancel in the popup

**Comment by jakobroehrl** [comment]
Maybe it helps to see how the deck app has implemented it: https://github.com/stefan-niedermann/nextcloud-deck/commit/fc711d851a294e273436dad8dc0267857fcfb3fa

**Comment by Spartachetto** [comment]
I confirm that when I share something e.g. from my browser I have in the list of the available apps:
 - Nextcloud app
 - Nextcloud Notes app
 - Nextcloud Deck app
 - Nextcloud Bookmarks app

yet no Nextcloud Talk app, which seems so strange....

**Comment by daffydock** [comment]
Hello.

Is this an item that is still being actively looked into?

**Comment by dan0xii** [comment]
I am working on it and have a basic implementation for text but not images.

**Comment by mnlipp** [comment]
What's the relationship between this issue and #435? Are these duplicate efforts? Maybe it would speed things up if there was only one joined approach. (As mentioned many times, not having the talk app in the list of apps for sharing images, links etc. makes the app absolutely useless for daily usage.)

**Comment by tobiasKaminsky** [comment]
@mnlipp I think it is the same. But as only @dan0xii is working on this feature, it does not duplicate any efforts…

**Comment by mat-l** [comment]
Sharing files in the browser is working fine. Therefore the backend should be ready right? https://github.com/nextcloud/spreed/pull/2891

Any updates here about the mobile apps for daily use?

**Comment by nickvergessen** [comment]
Mobile apps can now upload items in the chat view, the share dialog to share items form other apps will follow later this year

**Comment by stefan-niedermann** [comment]
@mahibi awesome! Can you tell me in which version this feature will be published? :slightly_smiling_face:

**Comment by mahibi** [comment]
i guess this will be published with v12.

and thanks to @dan0xii ! your branch gave to inspirations how things could be implemented.. 👍

**Comment by stefan-niedermann** [comment]
I roughly scanned the code and i am wondering whether also sharing plain text (for example when selecting a word) into the Talk app is supported by #1252 ?

I have the impression that this is only about files, but i am not sure.
Shall i open a separate issue or is this feature already included?

**Comment by nickvergessen** [comment]
Sharing text works.

But on the share dialog I can not change the current active account.

**Comment by mahibi** [comment]
> But on the share dialog I can not change the current active account.

yes that's true indeed and could be a follow up PR!
