### ISSUE TITLE
F-droid version is 2 years old

### ISSUE THREAD

**Issue by JOduMonT** [nextcloud/talk-android#3084]
### Steps to reproduce

Install f-droid
Update f-droid repo
Search for nextcloud talk

### Expected behaviour

Since you promote the apps being available via f-droid(thanks for that)
I was expecting a more recent version 

### Actual behaviour

Install version 13.0.0 which has been added in 2021-12-05.

### Device brand and model

Samsung

### Android version

11

### Nextcloud Talk app version

13.0.0

### Nextcloud server version

26.0.2

### Talk version

16.0.4

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by AndyScherzinger** [comment]
Is already fixed and will recieve 17.0.0 when released.

D-Droid decided to remove many versions from the past years which didn't fullfil their latest, newly defined requirements... 🙄

So expect the new release by the end of next week or the week after.

**Comment by sudwhiwdh** [comment]
@AndyScherzinger Does my server then need to be updated to Nextcloud 27 to also make use of Android Talk in version 17 from F-Droid?

**Comment by AndyScherzinger** [comment]
@sudwhiwdh you should be save with an older

**Comment by sudwhiwdh** [comment]
@AndyScherzinger How does the Talk app behave if the server version is older? Do I then see, for example, functions in the user interface that I can click on, but which do not work because I would need the latest server version for it to work?

**Comment by AndyScherzinger** [comment]
The client checks the server's features via its capability matrix und if present shows the UI elements else they are hidden.
