### ISSUE TITLE
Cannot talk with Nextcloud Talk

### ISSUE THREAD

**Issue by 9662** [nextcloud/talk-android#309]
**Version:** v3.0.0
**Installation source:** F-Droid
**Android version:** 7.x (both phones)

With both parties having the application open, a conversation is initiated by one of them by clicking on the other user's icon in the contacts list.

The receiving user does not get any notification that there is an incoming call / conversation.

The receiving user (being notified [out-of-band](https://github.com/siacs/Conversations)) goes to the ‘Conversations’ tab and sees the incoming call there. The user enters the conversation.

Initiating and receiving users are able to exchange text messages on the Talk application.

Either user tapping on the ‘phone call’ icon results in a black screen with microphone, phone, and loudspeaker icons. The first time this is done, the application requests and is granted microphone permissions.

Nothing else happens and no voice communications ever occur.

There are no visual or auditory indications at any point that a conversation has been initiated, or that the either user is attempting to reach the other via text or voice call or anything. (#257)

**Comment by mario** [comment]
1) F-Droid doesn't support notifications as mentioned in many issues so far
2) Do you have Turn server installed? Might help with the actual connection between the two participants.

**Comment by 9662** [comment]
> F-Droid doesn't support notifications as mentioned in many issues so far

You mean the Talk version on F-Droid. I know that, in fact I linked to the corresponding issue above.

> Do you have Turn server installed? Might help with the actual connection between the two participants.

Turn server (coturn) [is installed](https://help.nextcloud.com/t/howto-setup-nextcloud-talk-with-turn-server/) and running well (though all things considered, the app should come with its own TURN service bundled in). Nevertheless, the connection is hit and miss even on the same LAN, and all but impossible if the users are on different networks.

Honestly, I do not know how many people may be using this successfully in a fully open source environment but my experience after giving it a couple of my best tries has been truly disappointing. I do not think this application should be billed as “production use”; in terms of UX and in terms of simply working at all this is far below the usual standard for official Nextcloud apps.
