### ISSUE TITLE
Crash when loading conversations after updating to 17.0.0

### ISSUE THREAD

**Issue by Verequies** [nextcloud/talk-android#3099]
### Steps to reproduce

Everyone on my team had their phones automatically updated to Talk 17.0.0 and subsequently could not use the app anymore.

Updated to Nextcloud 27 and Talk 17.0.0 for Android
Opened Talk for Android and select a conversation.
See that app crashes.

### Expected behaviour

Able to view conversations without crashing.

### Actual behaviour

Talk for Android crashes consistently.
Downgrading to 16.0.1 works fine.

### Device brand and model

LG V30+

### Android version

10

### Nextcloud Talk app version

17.0.0

### Nextcloud server version

27.0.0

### Talk version

17.0.0

### Custom Signaling server configured

No

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment]
Thanks for the report @Verequies !
This sounds like some config on this server cannot be handled.
Does it happen for every conversation or for specific ones?

Would you be willing to create a test account for me this server? If yes, please send the credentials to 
marcel dot hibbe at nextcloud dot com

**Comment by Verequies** [comment]
No problem. It happens for every conversation including "Talk updates".
Sure I've created a test account and sent through the details.

**Comment by marcelklehr** [comment]
@Verequies Could you post a list of installed apps on your Nextcloud server?

**Comment by Verequies** [comment]
After talking with @mahibi and narrowing it down to a translation support issue. I have determined that the OpenAI Integration is actually causing every single translation (even unsupported) to be returned in the capabilities endpoint.
I had not even had the translation app installed. Not exactly sure what about the OpenAI Integration is causing the issue but it is just enabled, not setup or connected to their API. Very strange

**Comment by Verequies** [comment]
Perhaps to avoid this issue in future a check could be added to the Android app (if possible)?

**Comment by mahibi** [comment]
thanks @Verequies well done :+1:  @SystemKeeper also found out it's the OpenAI app :smile: 

OpenAI is also filling the same translation config that the translate app is using. For now as a workaround it's also possible to continue to use OpenAI and just disabling it's translation feature:

![grafik](https://github.com/nextcloud/talk-android/assets/2932790/545d5b01-62d0-4cff-896b-2929cf7375ea)

So it seems i will have to find other ways how the Android Talk app can handle this amount of data..

**Comment by SystemKeeper** [comment]
For reference, it's done here: 

https://github.com/nextcloud/integration_openai/blob/615e1f6446789fce8104f4d3e9df525263fa6b5c/lib/AppInfo/Application.php#L61-L63

**Comment by delorean02** [comment]
Exact same errors on my ZFold4, downgrading to 16.0.1 produces the error, "Display name couldn't be fetched, aborting."
Turning off the translation setting in the OpenAI settings does resolve the issue in the 17.0.0 app.  Thanks for posting!

**Comment by marcelklehr** [comment]
cc @julien-nc

**Comment by marcelklehr** [comment]
> should OpenAI set the same capabilitiy translation attributes as the nextcloud translate app?

Yes, as it is a translation provider (not sure why it doesn't work, that should probably be a bug report on integration_openai repo)

> so is it okay that the capabilities answer is so huge?

Yes.

**Comment by nickvergessen** [comment]
> should OpenAI set the same capabilitiy translation attributes as the nextcloud translate app?

Yes it should. But maybe it could only populate options it can really translate (is it known?)

> so is it okay that the capabilities answer is so huge?

Capabilities are checked not too regularly IIRC, but it shouldn't be too big never the less.
This was also one of my fear points back then where I wondered whether we should put them into capabilities or whether we read them from the API instead.

We could remove the capability and replace it with a boolean and then you read the list from https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-translation-api.html#get-available-translation-options

How big is the list with openai? MBs?

**Comment by mahibi** [comment]
> How big is the list with openai? MBs?

no it's still "only" 26KB with OpenAI translations, vs 3 KB without. So regardless of whether the translation options are outsourced or not i will have a closer look how to avoid the crashes because of "bigger" bundles or if anything else is wrong..

**Comment by ETLin** [comment]
got same issue. It's would work fine after closed openai service.

**Comment by muchachagrande** [comment]
Just for the record. I've got this issue today and I can confirm that it is also happening with the Libre Translate plugin installed because Libre Translate offers many languages as source and destination the possible combinations list is huge.
