### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#31]
The input field is a little darker, which in my opinion, does not look very good.
In general it looks very empty, maybe add also some infos, like on nc app?
Maybe also remove "talk" in "nextcloud talk server" as it can lead to the impression that there is a special talk server instead of the regular nextcloud server (of course with talk app enabled)
@jancborchardt 

![2017-12-15-151350](https://user-images.githubusercontent.com/5836855/34045744-90f1e842-e1aa-11e7-98f6-a69d90e99f9e.png) ![2017-12-15-151426](https://user-images.githubusercontent.com/5836855/34045773-b091d932-e1aa-11e7-80e9-9a27cc59b1dd.png)

**Comment by mario** [comment]
a) I need to check what's up with the logo
b) title was already changed to "Nextcloud server address"
c) There will be a proceed button under this all
d) IHMO, the input box looks nice - it's TextField Box according to Material guidelines

**Comment by jancborchardt** [comment]
Fully agree with @tobiasKaminsky’s points, as I also noted via email @mario ;)

- The dark background of the input box is unnecessary, the white line already is enough.
- The arrow is good as a confirm button. Either way we do it, it should be consistent across both apps please.
- We can put the same notice we have in the Files app there too. @jospoortvliet maybe a filter on the providers page as to which provider has the Talk app enabled?


Also – it would be really nice if we would not have this issue at all and just Take server address & credentials from main Nextcloud app #14 ;)

**Comment by mario** [comment]
Like I mentioned, I don't necessarily agree, but one cannot win all the fights so ... :)

**Comment by jancborchardt** [comment]
As said, we designed the Files app view for a reason like that and I'm not fond of going through the same design discussion process again when we already know how to do it. ;)
