### ISSUE TITLE
Longer multi-paragraph messages are not sent with no feedback

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/talk-android#310]
There is a message size limit that is not obvious neither in the Android app nor the web version.
You can type/paste lots of characters into the input field, but if the limit (what is it exactly?) is reached you cannot send the message.
- On the Android client when you press "send" the message dissapears from the input field and nothing else happens, leaving the user wondering about what just happened
- On the web interface the message "Cannot send the message" is shown, but with no additional information.

This case should be handled better - the server side already does this to an extent, but it is still not enough.
Probably something like: 
- prevent the user entering more characters than it is actually allowed to show a consistency between what you enter into the field and what is actually sent/will be sent.
- if the limit is reached (either by typing or pasting from clipboard) there should be a visible error message somewhere - a message with red characters near the input field should be instantly recognized by most users on server side and maybe a toast on mobile.

**Comment by mario** [comment]
I really appreciate you testing the app so much and putting in the effort to submit a bug report.

In order for me to understand the issue better:
- the input field is limited to 1000 chars and shouldn't allow you to input more. Can you confirm it actually allows you to do that? o.O
