### ISSUE TITLE
crash on contact tab and new conversation click

### ISSUE THREAD

**Issue by sysmoh** [nextcloud/talk-android#311]
The app crashes when I try to open the contact tab or try to create a new conversation.

I use nextcloud 14 beta with the **user_sql** app which provides an additionnal user provider based on another database, this is probably the issue, there are no problems when using the web interface of nextcloud talk.

**Comment by mario** [comment]
Woot. I'll investigate, but I'm not aware at what urgency as this is the first report of the kind that I've gotten.

**Comment by mario** [comment]
Thanks for the report!

**Comment by mario** [comment]
Can you send me a test account to mario@nextcloud pls?

**Comment by mario** [comment]
Closing since I can't really tst. Let me know if you get the time to send me a test account.
