### ISSUE TITLE
Crash when loading conversations on Android 10

### ISSUE THREAD

**Issue by Xitee1** [nextcloud/talk-android#3117]
### Steps to reproduce

1. Install and setup Nextcloud Talk on an Samsung Galaxy S9+ running Android 10
2. Try to open a conversation
3. Chat is loading
4. After 1-2 secs of loading, the app crashes and restarts into the conversation overview (Before 17.0.0 it crashed the App completely if I remember correctly)

### Expected behaviour

Chat loads and I can read the messages

### Actual behaviour

I'm back in the conversation overview and unable to open a conversation

### Device brand and model

Samsung Galaxy S9+

### Android version

10

### Nextcloud Talk app version

17.0.0

### Nextcloud server version

Nextcloud Hub 3 (25.0.3)

### Talk version

15.0.6

### Custom Signaling server configured

No

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

### Android logs

[talk_crash_log.log](https://github.com/nextcloud/talk-android/files/11848009/talk_crash_log.log)

### Additional information

My phone is rooted with Magisk if that matters.

My nextcloud is running in an docker container with a slightly modified official image.
coTurn is also running in an docker container.

All other things and calls do work fine if someone calls me. I also managed to create a call in the conversation by clicking really fast on the call icon before the chat loads.

I don't think it is related to #3099 because I also have this issue in previous versions. In version 13.x (or even 14.x?) it works as expected (however of course is outdated).

It works on all other phones I have tested. Only my Galaxy S9+ is affected. Maybe an issue with Android 10? The other phones are running Android 12+.

**Comment by Xitee1** [comment]
I build the project and found out it is working in 17.10.0 Alpha 08.
Still weird that it works on other Android 10 phones (Found one and tested it there) but now it works on my main phone too.

If someone has the same issue, I'll attach the APK so you don't have to build the App or wait for the next release.

--
Had to upload the file to google drive because of Github's 25MB limit: https://drive.google.com/file/d/1Vg66x8Xcshp1SatWx5-bSMn8Shq9IXra/view?usp=sharing

**Comment by mahibi** [comment]
it's most probably https://github.com/nextcloud/talk-android/issues/3099

**Comment by Xitee1** [comment]
Ok, maybe it has fixed my issue too.
But it's not the same cause because I don't have the OpenAI app, I've had the issue with 15.x and 16.x (not only after 17.0.0) too and the issue occured only on 1 of 6 phones I've tested.

But whatever it was, it is fixed now :smile:

**Comment by mahibi** [comment]
the problem might be that too much data is passed via intents, so this could lead to crashed depending on server configs (defines how much data is passed) and android versions/devices (how much data can be handled.

I'm not aware that other configs other than OpenAI create so "big" data, but who knows.
A solution will be https://github.com/nextcloud/talk-android/pull/3122 which will avoid passing too much data via intents
