### ISSUE TITLE
Option to open files or photos in nextcloud

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-android#3118]
I just noticed that when you click or hold on the file or photo under the Talk Ios is gives you an option to open file in nextcloud and redirects me to the Nextcloud app and opens the file or photo. Can this be done on this as well?

**Comment by mahibi** [comment]
seems this is only a fallback atm if it cannot be displayed.
com.nextcloud.talk.adapters.messages.PreviewMessageViewHolder#onMessageViewLongClick
