### ISSUE TITLE
Add file attach feature

### ISSUE THREAD

**Issue by asgardius** [nextcloud/talk-android#312]
could be great if file attach feature present in web version were also on mobile app. I have a nextcloud server and i can also test beta builds of this mobile app for reporting bugs

**Comment by fsxadmin** [comment]
i agree!

**Comment by mario** [comment]
It'll appear in the future, I just don't know when.

**Comment by mdesign83** [comment]
Please make nextcloud talk visible as an application to share something with:
![screenshot_20181029-173956_firefox nightly](https://user-images.githubusercontent.com/181026/47665644-d7b54980-dba1-11e8-9973-db02e5721ad5.jpg)

**Comment by flemmome** [comment]
Mario, is it possible to tell us a release date for this function? The app really works great, but I miss this feature to share pictures, further it would even be great to share videos and sound files in the chat directly, but pictures is the most important I think.

**Comment by mario** [comment]
I'm afraid not @flemmome.

**Comment by Pedulla** [comment]
with the immanent demise of gho this IS the killer app
How do I/we encourage its development?

**Comment by timo12357** [comment]
Any news on this? Sharing pics or any type of file is a key function.

**Comment by mario** [comment]
@timo12357 @Pedulla soon :)

**Comment by Pedulla** [comment]
I see file sharing!  sweet!
