### ISSUE TITLE
The messages  should be copyable partially

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/talk-android#313]
Currently the messages in the message list can be copied only in full (via long press).
This is problematic if one needs only a part of the message because it is needed to paste it somewhere.

It would be really helpful if the messages are copyable partially too 
- on long press the message contents should be selected with the standard Android text selection with the options to expand/reduce and then have the options to copy when the selection sizing is done. This is the standard in Android for browsers etc and it is also easy to use and understand.

**Comment by mario** [comment]
Right. Will look into it eventually.
