### ISSUE TITLE
duplicated accounts in account list

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#3131]
### Steps to reproduce

add multiple accounts

### Expected behaviour

no duplicated accounts

### Actual behaviour

some accounts might be duplicated but there were only added once by user

### Nextcloud Talk app version

17.0.0

**Comment by mahibi** [comment]
i can imagine it's related to https://github.com/nextcloud/talk-android/issues/3103

**Comment by mahibi** [comment]
i can't reproduce this (anymore).
i can imagine it's a race condition...

**Comment by XueSheng-GIT** [comment]
I'm on Talk-Android 19.0.1 (freshly installed on a new device) and each account I add is shown twice.
It says there are 4 registered users but actually it's only two I added.

**Debug information:**

### Meta-Information

**Erzeugung des Systemberichts**

12.07.2024 17:40:24

### Telefon

**Gerät**

HUAWEI TGR-W09

**Android-Version**

31

**Google Play-Dienste**

Google Play-Dienste sind verfügbar

### App

**App-Name**

Nextcloud Talk

**App-Version**

v19.0.1

**Build flavor**

gplay

**Batterie-Einstellungen**

Batterieoptimierung wird ignoriert, alles in Ordnung

**Anrufbenachrichtigungskanal aktiviert?**

Ja

**Nachrichtenbenachrichtigungskanal aktiviert?**

Ja

**Firebase-Push-Token**

cFTaU...

**Neueste Firebase-Push-Token-Generation**

09.07.2024 16:55:22

**Neuester Firebase-Push-Token-Abruf**

12.07.2024 17:40:05

**Registrierte Benutzer**

4

### Aktuelles Konto

**Server**

https://cloud.mydomain.de

**Benutzer**

Username

**Benutzerstatus aktiviert?**

Ja

**Server-Benachrichtigungs-App installiert?**

Ja

**Aktuelle Push-Registrierung am Server**

12.07.2024 17:40:06

**Aktuelle Push-Registrierung beim Push-Proxy**

12.07.2024 17:40:07

**Serverversion**

29.0.3

**Serverversion von Talk**

19.0.6

**Signalisierungsmodus**

Extern

**Comment by mahibi** [comment]
i will close this one in favor of duplicate https://github.com/nextcloud/talk-android/issues/4499
