### ISSUE TITLE
Notifications not showing up in Fairphone 4

### ISSUE THREAD

**Issue by YoannPa** [nextcloud/talk-android#3143]
### Steps to reproduce

Once the app connection to the server is configured, and all conversations are loaded correctly, there is no notification about a new message in a conversation.
However when I open the app manually, I can see on each conversation listed if there is a new message or not, and if so how many.

### Expected behaviour

Notification should show up when I receive a new message in a conversation.

### Actual behaviour

No notification pop up on the screen of my phone when the app is closed.

### Device brand and model

Fairphone 4

### Android version

12

### Nextcloud Talk app version

17.0.0

### Nextcloud server version

26.0.2

### Talk version

16.0.4

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by AndyScherzinger** [comment]
@YoannPa are you using the Google Play or f-droid version of the app? Just asking since f-droid doesn't support push notifications.

**Comment by YoannPa** [comment]
@AndyScherzinger I installed it from the Google Play store.

**Comment by mahibi** [comment]
Please check the settings documented in https://github.com/nextcloud/talk-android/blob/master/docs/notifications.md

**Comment by YoannPa** [comment]
> Please check the settings documented in https://github.com/nextcloud/talk-android/blob/master/docs/notifications.md

@mahibi Everything is setup correctly on the Fairphone 4 from the documentation you shared.
On the server side, since there are other users, and for most of them the notifications work fine, I suppose the issue is really coming from the Fairphone 4.

Before that, I was using a Fairphone 2. And I remember for the first 6 months using the app Nextcloud Talk on this smartphone, I had the same issue.
Then, following a software update (Android update I presume), Nextcloud Talk started to show notifications.
My guess is that what is happening on the Fairphone 4 is somehow similar : maybe it is a software incompatibility.

**Comment by mahibi** [comment]
@YoannPa good to know. So it's original Android? Asking because it's important that Google play services are available..

**Comment by mahibi** [comment]
> What do you mean by "original Android" ? 
just to make sure youhave no alternative OS installed, like grapheneOS or lineage etc. which would come without googple play services.
So if Google Play Store is avialbale for you everything should be fine from this side. 
But not sure what goes wrong..
Would be interesting if other users with FP4 report the same issue..

**Comment by YoannPa** [comment]
Fery few people are using the FP4.
Do you think I should open an issue of the Fairphone forum ?

**Comment by mahibi** [comment]
> Fery few people are using the FP4. Do you think I should open an issue of the Fairphone forum ?

sure that could be worth a try

**Comment by YoannPa** [comment]
@mahibi I created an issue on Fairphone support forum here: https://forum.fairphone.com/t/fairphone-4-nextcloud-talk-android-app-notifications-not-showing-up/97616

Let's see how it goes and if it provides any answer.

**Comment by YoannPa** [comment]
@mahibi Actually I forgot to mention the obvious: notifications work perfectly well for all the other apps installed on my Fairphone 4.

**Comment by testman42** [comment]
Can confirm, notifications are not working on LineageOS (without gapps), despite conversation being set to "Always notify".

**Comment by manu-p** [comment]
Notifications are not working on a FP3+ running LineageOS + MicroG 20 (android 13) and android NC Talk 17.0.2 from Google Play Services via Aurora Store.
Notifications are going fine with other chat apps such as Signal and/or Telegram.

**Comment by cue108** [comment]
I just installed the Google Playstore version of Talk via APK-Mirror on my Fairfone 4 which I completely ungoogled by installing iode´ on it. It uses microG Services Core version 0.2.28.231657-28.

Everything works just fine with Nextcloud Talk 17.0.2 here!
Just saying...

**Comment by YoannPa** [comment]
> Checking on the server side with:
> $ php occ notification:test-push --talk userName
> Trying to push to 1 devices
> .
> .
> 

Since I am using the snap version of nextcloud server I used a slightly different command to test what you recommend.
From the server side I did:
`sudo nextcloud.occ notification:test-push --talk username`

Which printed:
```
Trying to push to 2 devices

Language is set to fr
Private user key size: 1704
Public user key size: 451
Identified 1 Talk devices and 1 others.

Device token:64
```
Following this I received a test notification on the PC web browser interface of the user account.
But no notification at all on my Fairphone 4 from the Android Nextcloud talk app.
As far as I am concerned, the issue remains on Nextcloud Talk v17.0.2.

> Remains my question to what degree this is a privacy concern? I simply don't know enough to reasonably estimate it.

@cue108 Could you elaborate ? I don't understand what you mean.

**Comment by cue108** [comment]
@YoannPa The NC server side command is useful to see whether a device is known to push notifications to on the standard server side notification implementation. 
However, I am also using UnifiedPush provider on the server side to manage notification myself in conjunction with the Adndroid Next-Push app.
https://github.com/UP-NextPush/android

That way I get at least all notifications pushed to the Nextcloud Android App under the menu item Notifications..
Unfortunately Nextcloud-Talk notification will not be handled by this solution and the FOSS Version of Talk is silent on chat messages and calls.

Having Talk installed as a FOSS version and NOT using Google's PubSub message broker infrastructure makes Talk rather useless at the moment. So I felt forced to use the Google Playsore Version of Talk to receive notification messages about chat messages on my Android phone.

Now, Google Cloud Messaging (GCM) and its successor Firebase Cloud Messaging (FCM) in which Google's cloud infrastructure acts as the message broker. It receives messages from publishers and distributes them to all subscribers who have subscribed to the corresponding topics would serve as an ideal point to harvest profiling meta data on Google's side.

I would love to simply bypass Googles services all together especially when I do host my own cloud solution already in order to be un-googled to begin with.

**Comment by Mer0me** [comment]
Using Fairphone 3+ under e/os, Talk notifications are working well if I use the "official" play store APK.

**Comment by YoannPa** [comment]
Now using:

- Android version 13
- Nextcloud Talk Android v18.0.0
- Nextcloud Server 27.1.3
- Talk app on Nextcloud 17.1.3

I am finally receiving notifications on my Fairphone 4!
Will confirm in the coming days before closing the issue if everything works fine.

**Comment by YoannPa** [comment]
Notifications are showing up correctly now.
I close the issue.
