### ISSUE TITLE
Loading indefinitely on OnePlus 7T Pro

### ISSUE THREAD

**Issue by YoannPa** [nextcloud/talk-android#3144]
### Steps to reproduce

1. Install Nextcloud Talk from Google Play store.
2. Log into account on nextcloud server.
3. Conversations are loading indefinitely, without showing up.

### Expected behaviour

After login, the conversations should load smoothly.
Sometimes, it doesn't load at all, for few days. And then one day it works again.

### Actual behaviour

Sometimes, at step 3 the app keeps loading indefinitely the conversations, without displaying them at all. This can be the case for few days. And then, one day, it just works again.

Here is a screen capture of the problem:
![WhatsApp Image 2023-07-05 at 13 01 57](https://github.com/nextcloud/talk-android/assets/12813932/165756f8-df17-4022-87c5-4b71b4029236)

### Device brand and model

OnePlus 7T Pro

### Android version

12

### Nextcloud Talk app version

17.0.0

### Nextcloud server version

26.0.2

### Talk version

16.0.4

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

### Additional information

The App was installed from the Google Play store. Not from F-droid.

**Comment by mahibi** [comment]
Does it happen for other phones as well or only for your OnePlus 7T Pro?
Does it happen only when connected via specific internet connections?
Access via Webbrowser works fine while this occurs on your phone?

**Comment by mahibi** [comment]
Does any dialog appear which says that there was a problem to load the conversations?

**Comment by YoannPa** [comment]
> Does it happen for other phones as well or only for your OnePlus 7T Pro? Does it happen only when connected via specific internet connections? Access via Webbrowser works fine while this occurs on your phone?

On the nextcloud server I administrate, not that I know.
Some user had a similar issue, but in any other case, that could be explained by a low rate internet connection. Basically the loading takes just a lot of time, and sometimes the user with a low rate internet connection has to wait 1 or 2 minutes instead of few seconds. 

In this specific case, the user has a really good internet connection both in 4G or in WiFi. And despite waiting for few minutes, the app still does not load any conversation. And this was the situation for few days... before resolving on its own.
That's why I decided to report it: it does not seem to be an "bad internet connection" related issue.

The user was still able to use every other app, and to web browse smoothly on his while this issue was happening.



> Does any dialog appear which says that there was a problem to load the conversations?

No dialog appear regarding the loading issue. It justs loads no conversation, as shown on the screen capture.

**Comment by mahibi** [comment]
a similar behaviour just happend to me when trying to load a conversation. So maybe it's the same reason...

```
2023-07-13 14:50:42.558 17228-17398 okhttp.OkHttpClient     com.nextcloud.talk2                  I  <-- HTTP FAILED: java.net.SocketTimeoutException: timeout
2023-07-13 14:50:42.562 17228-17228 ChatViewModel           com.nextcloud.talk2                  E  Error when fetching room
```

**Comment by YoannPa** [comment]
> @YoannPa did you have multiple accounts set up inside nextcloud android talk app? or only one?

I here confirm the user is using only 1 registered account within its Nextcloud Talk app on Android.

**Comment by Mer0me** [comment]
With Fairphone 3+ under e/os, sometimes the conversations are loading indefinitely. When it happens, the server isn't overloaded. I cannot figure out why this is happening. Restarting the app, even clearing the cache is not always sufficient to solve the problem. It can work a few minutes later without doing anything...

**Comment by Fuseteam** [comment]
I seem to run into this with both the playstore and fdroid version, but i get a pop up "There was a problem loading your chats"

It seems limited to the chat list however
![Screenshot_20240808_112339_Talk](https://github.com/user-attachments/assets/a19427ff-d752-4624-95ff-11641ff72740)

if i dismiss and try to open a chat with a college that i already have one i can access that fine

```
### Meta information

**Generation of system report**

8 Aug 2024 11:25:49

### Phone

**Device**

samsung SM-T220

**Android version**

34

**Google Play services**

Google Play services are available

### App

**App name**

Nextcloud Talk

**App version**

v19.0.1

**Build flavor**

gplay

**Battery settings**

Battery optimization is not ignored. This should be changed!

**Notification permissions**

Notifications are granted

**Calls notification channel enabled?**

Yes

**Messages notification channel enabled?**

Yes

**Firebase push token**

dmwpv...

**Latest firebase push token generation**

8 Aug 2024 11:19:43

**Latest firebase push token fetch**

8 Aug 2024 11:21:16

**Registered users**

1

### Current account

**Server**

[Redacted]

**User**

[Redacted]

**User status enabled?**

Yes

**Server notification app installed?**

Yes

**Latest push registration at server**

8 Aug 2024 11:21:17

**Latest push registration at push proxy**

8 Aug 2024 11:21:17

**Server version**

29.0.4

**Server Talk version**

19.0.7

**Signaling Mode**

External
```

**Comment by mahibi** [comment]
Is it the same behavior with v20.0.1?

**Comment by Fuseteam** [comment]
is that the app version or the server version?

**Comment by Fuseteam** [comment]
i found the update on fdroid, it indeed seems to work normally now. Loading the chats even seems a tad faster

**Comment by mahibi** [comment]
yes i meant the app version. 
I plan to implement more improvements for offline support soon which will make sure this does not happen at all

**Comment by YoannPa** [comment]
> Is it the same behavior with v20.0.1?

Problem also solved on my side. I think you can close the issue.
