### ISSUE TITLE
No notifications for 'open' conversations

### ISSUE THREAD

**Issue by robertfromont** [nextcloud/talk-android#315]
It seems that if you don't leave a conversation, but hit the home button or turn the screen off, you don't receive any more notifications for text messages in the conversation. So if someone doesn't respond to a chat message right away and I pocket my phone, I won't get a notification when they finally answer.

Steps to reproduce:
1. Person A sends message to Person B (there's a notification on phone B, yay!)
2. Person B opens the conversation.
3. Person B hits the home button (without leaving the coversation).
4. Person A sends another message, there's no notification on phone B

It doesn't matter whether Person A is using the web interface or the phone app.

If, between step 2 and 3, Person B hits the back button to leave the conversation, notifications work fine.

*App version:* v3.0.0 (6/9/2018 on Play Store)
*Server version:* 14
*Device:* Pixel (1)
*Android version:* 9 build PPR2.180905.006

**Comment by mario** [comment]
Yup, know, will be fixed.

Thanks for reporting this.
