### ISSUE TITLE
AndroidX Media3 migration

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#3152]
#3148 is the last release of the standalone exoplayer we use for video playing

This project is now deprecated. All users should migrate to `androidx.media3` (which contains the same ExoPlayer code). See [the migration guide](https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide) for more details, including a script to help with the migration.

**Comment by parneet-guraya** [comment]
#3254
