### ISSUE TITLE
Missing notification forwarding to Samsung Gear S3

### ISSUE THREAD

**Issue by MarkusP** [nextcloud/talk-android#316]
Hi all,
I use Nextcloud in version 14.0.1 on my own server, "Talk" app in version 4.0.0 is installed and enabled.
Also I use Nextcloud Talk app on Android 8 on Samsung S8, S7 and A5 (2017).
Doing chats and voice and video calls, even with notification, works good.
What is not working is, even the Android Nextcloud Talk app is enabled to do so, sending notifications to my Samsung S3 Clock/Wearable Display if new messages or calls arrive - this works wonderful with phonecall app, messages app, calendar app, even with 3rd party (not samsung) apps like banking app, garbage collection app and so on... Within the Samsung Galaxy Wearable app (https://play.google.com/store/apps/details?id=com.samsung.android.app.watchmanager) this is explicitely allowed. 
Any idea why this is not working? Do I have to do some special settings? Would be great to find a solution, as my phone is allways (!) muted and I let all incoming notifications/calls/etc... to be send to my Galaxy S3 clock.

Thanks in advance for any tip or hint or best: solution :-)

Kind regards
Markus

**Comment by mario** [comment]
Hey, thanks for reporting this. Unfortunately no idea as I don't have an Android Wear device :(

But maybe I'll get it in the future and I can test it.

**Comment by mario** [comment]
Will be fixed in 3.1beta3.
