### ISSUE TITLE
Ability to detect ongoing call

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#317]
I started call with nc android talk to another android nc talk app. On that mobile was ongoing call and app ringed...  So expected behavior is if user talking, app will not ring and (if possible) give feedback to other side (busy tone or text?)

**Comment by mario** [comment]
Thank you for the report, I'll definitely look into this.

**Comment by mario** [comment]
What would you do here @nickvergessen? Most existing apps out there actually cancel your call (Viber for example) if there's an incoming REAL call.

**Comment by mario** [comment]
This is a different use case than @jookk mentioned, but it's still important.

**Comment by mario** [comment]
@jookk your particular request is implemented via https://github.com/nextcloud/talk-android/issues/663
