### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#3176]
* Overview ticket: https://github.com/nextcloud/spreed/issues/1027
* API discussion: https://github.com/nextcloud/spreed/issues/9950

We plan to role out the following support for markdown:

# non-optional
- [x] bold
- [x] italic

# optional
Optional means it is just shown with the markdown syntax

- [x] strike-through
- [x] list
- [x] todo list with checkboxes
- [x] code block using 3 `
- [x] inline code using `
- [x] quote
- [x] headlines
- [x] dividers `---`

**Comment by nickvergessen** [comment]
I'm aware of https://github.com/nextcloud/talk-android/issues/3154 just created a new ticket for tracking until we know whether we want to have an option for markdown on/off

**Comment by AndyScherzinger** [comment]
@nickvergessen I checked the formatting list and ticket all boxes since the Android implementation supports all of them. Also adding an option to disable this completely should be very easy to do, only disabling parts is unlikely to work given the nature of the library in use.
