### ISSUE TITLE
Message send multiple times

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/talk-android#318]
Sometimes a single message is send multiple times.
Experienced this in a conversation with @mathiasconradt 
![img_7650](https://user-images.githubusercontent.com/4638605/46275890-b63f4e80-c55e-11e8-9881-e88ba950c0b0.jpg)

**Comment by mario** [comment]
Version of Nextcloud and version of the app?

**Comment by Ivansss** [comment]
Nextcloud 14.0.1 and Talk 4.0.
@mathiasconradt could you provide android app info?

**Comment by mathiasconradt** [comment]
@mario I'm always on the latest version since I have auto-update enabled on Android. I have no more details other than I only sent a message once, however Ivan got it twice. No idea why.

**Comment by mario** [comment]
@mathiasconradt when you enter the same conversation again, do you see the same message multiple times? (e.g. twice or three times?)

**Comment by jookk** [comment]
![screenshot_20190118-204025_1](https://user-images.githubusercontent.com/11217085/51425408-29d39d00-1bdc-11e9-9f50-cc1b7d24a5b1.png)

**Comment by physikerwelt** [comment]
I see that too. Is this a regression?

**Comment by mario** [comment]
This should be fixed already. What version do you have?
