### ISSUE TITLE
Typing status indicator not showing

### ISSUE THREAD

**Issue by ASerbinski** [nextcloud/talk-android#3189]
### Steps to reproduce

No steps required, the indicator is supposed to be visible near the bottom of the screen while the other party to the conversation is typing. It is not.

### Expected behaviour

Typing indicator should show when the other party is typing.

### Actual behaviour

Typing indicator does NOT show EVER.

### Device brand and model

Pixel 6 Pro

### Android version

GrapheneOS 13

### Nextcloud Talk app version

17.0.1

### Nextcloud server version

27.0.0

### Talk version

17.0.1

### Custom Signaling server configured

Yes (specify version in Additional Information)

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

### Additional information

nextcloud-spreed-signaling v1.1.2
notify_push v0.6.3

In talk-android settings, "Typing status" is greyed out and faint text below shows "Typing status is only available when using a high performance backend (HPB)"

It isn't clear if it is referring to the talk or files high performance backend, but this installation is using both as indicated above. The "test_client" for notify_push is able to connect successfully and receive messages.

**Comment by ASerbinski** [comment]
Invalid.
Turns out that there was an issue with the Nextcloud configuration. Table oc_appconfig contained a row with appid="spreed", configkey="signaling_mode", configvalue="internal" that would NOT clear with the settings UI. After clearing the key manually, signaling works correctly and the typing notification shows.

**Comment by JRGonz** [comment]
I'm running into this after installing and configuring the HPB. Can you be more specific on how you fixed it? I am not getting typing notifications at all anywhere but everything else seems fine. Talk seems to be able to connect to the HPB.
