### ISSUE TITLE
Height of conversations in list should all be the same

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#320]
Currently in the conversation list there are 2 different kinds of height:
- Conversations with 1 row of text as message preview
- Conversations with 2 rows of text as message preview

This looks strange when scrolling when the avatars on the left are differently spaced. We should adjust it so the height is the same for all rows.

**Comment by mario** [comment]
Also @AndyScherzinger, wanna do this? :)

**Comment by AndyScherzinger** [comment]
Absolutely! :)

**Comment by AndyScherzinger** [comment]
PR is #331
