### ISSUE TITLE
Force round app icon

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#321]
Our other apps like Files and Notes use the round app icon whenever possible. Here in Android 6.0.1:
![](https://cloud.jancborchardt.net/s/EMpkZC8mYa9WTLK/preview)

We should do the same for Talk.

**Comment by mario** [comment]
*shrug* @AndyScherzinger wanna do this?

**Comment by AndyScherzinger** [comment]
Sure thing, but probably won't be able to do this before mid of October if that is fine with you

**Comment by AndyScherzinger** [comment]
PR is #330
