### ISSUE TITLE
Thumbnail in chat not showing image or document preview. On android mobile app and web portal.

### ISSUE THREAD

**Issue by tinashegufu** [nextcloud/talk-android#3213]
### Steps to reproduce

1. Sending an image or document to any of my contacts
2. Receiving an image or document from any of my contacts

### Expected behaviour

The user expects to see a preview of the image or document whilst in chat without fully opening it. Instead of seeind a dummy thumbnail preview but a thumbnail preview of the actual image. 

### Actual behaviour

When an image is sent or received the user cannot see the preview of it in the thumbnail, however they see the default thumbnail icon instead. As well as documents which also adopt the same be haviour.

Even after downloading the image and viewing it, a thumbnail preview of the image in chat remains the same dummy icon as shown in the images attached from both mobile and browser.

![Mobile App Screen Shot](https://github.com/nextcloud/talk-android/assets/49593281/25b7b887-8c86-4040-86c7-96bbba159751)

![Webbrowser screenshot](https://github.com/nextcloud/talk-android/assets/49593281/aa9c064b-fa0e-4a19-a0aa-73922891d861)

### Device brand and model

Tecno Camon 17 Pro

### Android version

11

### Nextcloud Talk app version

17.0.2

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by AndyScherzinger** [comment]
You need to configure the preview-providers within the server, that also provides them to the clients then. So this is very likely a server-configuration issue.

Closing it for now, feel free to re-open in case it isn't.
