### ISSUE TITLE
Delete messages

### ISSUE THREAD

**Issue by nr458h** [nextcloud/talk-android#322]
It would be great to be able to delete messages (with multiselection)

**Comment by mario** [comment]
As soon as the server supports it :)

**Comment by jookk** [comment]
You can del whole conversation and create new one.

**Comment by gradinaruvasile** [comment]
> You can del whole conversation and create new one.

That is most definitely not the goal here.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/issues/774

**Comment by nickvergessen** [comment]
With issue https://github.com/nextcloud/spreed/pull/774 and PR https://github.com/nextcloud/spreed/pull/4861 chat messages will be deletable on the server. They will be replaced by dummy messages to keep quoting system functional and a hidden follow up message will be posted in the chat to allow clients to be notified about the delete so they can remove it from their local cache/database.
