### ISSUE TITLE
Notify me later about this message

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#3221]
- Overview ticket at https://github.com/nextcloud/spreed/issues/10075

---

The message menu should have an option:
* "Set reminder" > Submenu opens with following options
![grafik](https://github.com/nextcloud/spreed/assets/213943/ab511846-72ca-49f9-b56b-e7da92abf3b4)

## Required aka. MVP
- [ ] Later today => 6pm
- [ ] Tomorrow => 8am
- [ ] This weekend => 8am Saturday
- [ ] Next week => 8am Monday

## Optional

- [ ] Custom date+time picker

**Comment by AndyScherzinger** [comment]
@nickvergessen afaik there is no notification API via ReST or do you offer a Talk specific one?

**Comment by AndyScherzinger** [comment]
Nevermind, found the ticket 👍
