### ISSUE TITLE
Notifications not showing up in Redmi Note 10S

### ISSUE THREAD

**Issue by YoannPa** [nextcloud/talk-android#3238]
### Steps to reproduce

No notification are displayed on the main screen after installing and configuring the app.
The user checked all settings as listed here: https://github.com/nextcloud/talk-android/blob/master/docs/notifications.md
Nextcloud Talk app wasn't installed using F-droid but using Google Play.

### Expected behaviour

Notification should show up on the main screen when a new message is received for example.

### Actual behaviour

No notification displayed at all, when a new message is received.

### Device brand and model

Redmi Note 10S

### Android version

11

### Nextcloud Talk app version

17.0.1

### Nextcloud server version

26.0.3

### Talk version

16.0.5

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment]
Thanks for the detailed description, it should work indeed.
Does it still fail? Hoping it was just some server hiccup.. (i was on vacation for 3 weeks)

**Comment by YoannPa** [comment]
The problem seems to be fixed :) .
So I am closing the issue.
