### ISSUE TITLE
Status bar notifications android

### ISSUE THREAD

**Issue by leihergo** [nextcloud/talk-android#324]
Steps to reproduce
Receive a message in nextcloud talk
Go to the bar notifications
There is nothing there
Expected behaviour
Get the notification, not just a vibration of the terminal

Actual behaviour
The mobile just vibrates, if you don't feel it, you don't know you have messages

**Comment by mario** [comment]
Considering the phone vibrates, push message is received.

What phone do you have, what Android version?

**Comment by mario** [comment]
Could you  guys try 3.1beta1 please? @jimmy5670 and @leihergo

**Comment by mr-bolle** [comment]
With Samsung Note 9 and Stock Android 8.1.0. I only get a notification for a incoming call. With new chat messages i get nothing.

Nextcloud Server 13.0.7 and 14.0.3
Android 3.1.0 beta 1 (with all previous versions the same)

**Comment by jimmy5670** [comment]
Same situation on Android 3.1.0 beta3,
but I noticed in the talk conversation screen list message sender,
the under message sender's last activity time is not up to date,
after I tap the sender and enter the message chat screen, the last message shows immediately,
but still no notification shows up,
does message not received instantly in background?
My hypothesis is the message real received when I enter message chat screen, not anytime in background.

**Comment by mario** [comment]
The conversation list needs to be updated manually. We only pull for chat messages when you are inside chat view @jimmy5670.

Push is something different.

**Comment by mario** [comment]
@mr-bolle can you send me a test account please? I just tried this and it works like a charm :(

same for @leihergo

**Comment by mario** [comment]
Tested this with the user and it works as expected, therefore closing.

**Comment by mr-bolle** [comment]
Thanks Mario 

**Test results:**
- Nextcloud Server 13.x - notification only if user mention
- Nextcloud Server 14.0.3 - notification with other android app chats works, or with the desktop browser login
- public connection as guests - currently no notification (Mario wrote it should be fixed with Nextcloud Servers 15)

**Comment by mario** [comment]
Sorry, maybe we misunderstood each other - currently in public calls you need to be mentioned in order to be notified.

But guests cannot be notified since they don't have a user account.
