### ISSUE TITLE
Login-Error “The account is scheduled for deletion, and cannot be changed”

### ISSUE THREAD

**Issue by Shen** [nextcloud/talk-android#3243]
### Steps to reproduce

Installed Talk on Android
Added path to Nextcloud-Instance

### Expected behaviour

Login-Process

### Actual behaviour

Error: The account is scheduled for deletion, and cannot be changed

![1024-2219](https://github.com/nextcloud/talk-android/assets/81589/229e3d1b-d31d-4ef9-84b7-14aff57b3e35)

### Device brand and model

Samsung Galaxy S23 (SM-911B/DS)

### Android version

13

### Nextcloud Talk app version

17.0.2

### Nextcloud server version

26.0.4.2

### Talk version

16.0.5

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

### Additional information
Web-Login with the same username is working. The account is not scheduled for deletion.
Some other users do have the same problem: [https://help.nextcloud.com/t/nc-talk-das-konto-wird-geloscht/165766](https://help.nextcloud.com/t/nc-talk-das-konto-wird-geloscht/165766)

**Comment by jhenkins** [comment]
Also seeing this error. Software versions on my server and device:

Talk for Android: 17.0.2
Nextcloud Hub: 27.0.2
Talk app: 17.0.3

**Comment by TBI-NS** [comment]
Same today with an android 13 Samsung

**Comment by mahibi** [comment]
If that's okay for anyone, it would be helpful for me to get server-url and credentials of the user that is not able to login to debug what goes wrong.
Just send it to marcel dot hibbe at nextcloud dot com
I can of course understand if this is not desired since they are probably not test users.
If someone can reproduce this with test users it would be great of course!

**Comment by mahibi** [comment]
Although i cannot reproduce the issue i had a closer look and can think of one scenario why this happens, see the fix in https://github.com/nextcloud/talk-android/pull/3261

Anyway there are still some questions:

- Did you try to remove the account beforehand? (The "The account is scheduled for deletion" info means it's only removed inside the app. The account itself is not deleted from nextcloud)
- Does this happen again when the app is restarted?
- Are there other accounts set up in the app?
- Did you try to remove the other accounts before the issues arised?

**Comment by mahibi** [comment]
i keep the issue open for now as i'm not sure if the fix is enough. 
Please let me know if the issue happens once v17.1.0 is out (or any upcoming beta/alpha version)

**Comment by H3cJP** [comment]
Removing the app data (Settings -> Apps -> Talk -> Clear all data) worked for me, now i can login, without that error.

**Comment by TBI-NS** [comment]
From my end, the user didn't have to clear the cache. I created a new account on NextCloud and they were able to connect without any issues.

So, without making any assumptions, I would say the issue is not on the Android app side but likely on the Spreed side.

**Comment by nickvergessen** [comment]
> So, without making any assumptions, I would say the issue is not on the Android app side but likely on the Spreed side.

Server side is not tracking anything. This is definetly a bug in the Android app and mostlikely that is why a new user worked, because a unique identifier consisting of user-id + server-url did not match anymore.

**Comment by nickvergessen** [comment]
I would say instead of erroring in https://github.com/nextcloud/talk-android/blob/51ecd6d9d7086f9a2f50ac15e22737340df929ee/app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt#L328-L336
We should proceed the deletion (remove all related account information) and then continue creating the user again

**Comment by hegGK** [comment]
Had the same issue. I had one account from a different Nextcloud-Instance connected with talk and intended to connect to a different instance when I reproducable got that error.
Tried to delete all application accounts in my nextcloud account named with the name of my smartphone. Did not solve the problem. Could NOT delete the Nextcloud-Account.

Problem solved by deleting the application data on the smartphone (not only the cache). Had to reconnect to both Nextcloud instances which worked without any problems.

So for me it seems to be a problem at the talk app.
May be, I dont remember, I once marked my app account in Nextcloud as "To be deleted" and I could not revoke that.
