### ISSUE TITLE
User mentions in replies not shown correctly

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/talk-android#3259]
### Steps to reproduce

1. Open a chat with a mentioned user in a reply
2. See placeholder instead of user badge

### Expected behaviour

See user badge also in reply message

### Actual behaviour

Placeholder shown

![Screenshot_2023-08-21-17-16-47-27_8632fad113e22989b917ea89c335fe0d](https://github.com/nextcloud/talk-android/assets/16020496/52cd3842-92f6-4d9f-981e-1165fa9dabde)

Happens on c.nc.c and also on my own instance with latest server (27.0.2) and spreed (17.0.3)

### Device brand and model

Oneplus Nord 3 5G

### Android version

13

### Nextcloud Talk app version

17.10 Alpha 14

### Nextcloud server version

27.0.2 / version on c.nc.c

### Talk version

17.0.3 / version on c.nc.c

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by Chartman123** [comment]
> Fixed, please check latest Alpha build. 14 had the issue but got fixed later. Please reopen if still present (shouldn't since I fixed it IMHO) 

Thank you. Is there a problem with the distribution of the alpha versions on Google Play? I didn't get any updates since alpha 14...

**Comment by Chartman123** [comment]
And yes, with the latest alpha 17 I can't reproduce the problem 👍🏻

**Comment by AndyScherzinger** [comment]
> Is there a problem with the distribution of the alpha versions on Google Play? I didn't get any updates since alpha 14

No idea, @mahibi might know best

**Comment by mahibi** [comment]
> > Fixed, please check latest Alpha build. 14 had the issue but got fixed later. Please reopen if still present (shouldn't since I fixed it IMHO)
> 
> Thank you. Is there a problem with the distribution of the alpha versions on Google Play? I didn't get any updates since alpha 14...

It's finally fixed

**Comment by Chartman123** [comment]
Yes I got the new version yesterday in the evening. Thank you very much
