### ISSUE TITLE
Send photos from the nextcloud talk app

### ISSUE THREAD

**Issue by ddi98** [nextcloud/talk-android#326]
Hi, the app is done well but it would be useful to send files and photos directly from the app, you can do it?
I use the latest version of nextcloud stable

**Comment by mario** [comment]
Already planned, see #312 :)

**Comment by mario** [comment]
Thanks for being awesome!

**Comment by Pedulla** [comment]
Not seeing it.
Did I miss it?

With the immanent demise of gho this is the killer app for me.

**Comment by Hanskes** [comment]
Is it possible to add a photo directly from the nextcloud talk app, whereby the photo is also added immediately in nextcloud itself? Now you need two apps to add a photo, first the nextcloud app to upload the photo to the server, then the talk app to add the photo to a conversation. If you still have to take the photo with your phone, you even need three apps. It would be great if you could take a photo with the talk app which is added to a conversation and uploaded to nextcloud.

**Comment by Hanskes** [comment]
when you want to add a photo from the android talk app, you only see the name of the photo and not the photo itself, this makes it difficult to add the correct photo.

**Comment by MBadberg** [comment]
Can't share photos from an external storage.
Nextcloud 19.0.3
I have my NAS as external storage, where i automatically upload Videos and Pictures from phone. That works fine.
I can select the picture i want to share, but nothing happens. Files from nextclouds internal storage are working fine.
Nextcloud Talk Android 8.0.9
