### ISSUE TITLE
show accept call button in chat

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#3260]
Currently when being in a chat and a call is started, only a message "xy started a call" is shown. To join it, the icons in the upper right have to be clicked.

There should also a button right inside the chat to join a call. 
Maybe 2 buttons for audio/video, or maybe one button with a popup to choose between audio/video.

**Comment by rapterjet2004** [comment]
So It's something like this with an additional button for audio?

![image](https://github.com/nextcloud/talk-android/assets/69230048/62232216-09fc-4c4a-9bcc-754832d4f242)

**Comment by mahibi** [comment]
> So It's something like this with an additional button for audio? 

yes. As far as i see it's the same on iOS. So we should coordinate with @nickvergessen  @Ivansss @SystemKeeper 

Maybe we should just show the icon depending on which type of call it is. So if it's a videocall, we also only show the videocall button, otherwise only audio. 

Also related to this: https://github.com/nextcloud/talk-android/issues/1762 but that's a bigger task i guess.

**Comment by Ivansss** [comment]
> Maybe we should just show the icon depending on which type of call it is. So if it's a videocall, we also only show the videocall button, otherwise only audio.

I would go with adding both options (audio-only and video) always.
Calls started from web clients will always be video calls but a user might still want to join in voice-only mode.
