### ISSUE TITLE
media/photo share function - add to long-press menu

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/talk-android#3276]
**Summary**

Currently when viewing a photograph that was shared in a Talk conversation - i.e. clicking on the photograph to view full screen - there is a `Share` option under the 3-dot menu.

![image](https://github.com/nextcloud/talk-android/assets/7018928/fe422f2b-0b4e-48ec-a07f-9366c92e534d)

Currently when long-pressing a photograph that was shared in a Talk conversation, the resulting menu _does not_ contain the `Share` function.

![Screenshot_20230825-182309_Talk_1](https://github.com/nextcloud/talk-android/assets/7018928/356e06f0-d08f-45d3-be95-c0967fc2b9cb)

**Describe the solution you'd like**
Would be great to implement the same `Share` function in the long-press menu.
This would offer a simpler workflow: no need to expand a photograph full-screen just to share it.
There is also arguably plenty of screen real-estate to accommodate another function in the long-press menu.

**Comment by Smarshal21** [comment]
i am working on this

**Comment by Smarshal21** [comment]
i implemented this here - https://github.com/nextcloud/talk-android/pull/3284
