### ISSUE TITLE
feature - Emoji - typed inline emoji auto-complete

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/talk-android#3277]
**Is your feature request related to a problem? Please describe.**
Problem: When typing an emoji via keyboard into the text field - i.e. `:fire` or `:tada` as is possible in Talk, no emoji auto-complete function appears. One *must* insert emoji using the emoji selector (or other method).

https://github.com/nextcloud/talk-android/assets/7018928/fa9ba2e9-70a2-411e-9df3-da81be50e28d

**Describe the solution you'd like**
Recommend adding: typed emoji presents an auto-complete and selection behaviour, similar to Talk:
![Peek 2023-08-25 19-05](https://github.com/nextcloud/talk-android/assets/7018928/a50d128f-704e-4de4-a05d-bbef534bbb46)

**Comment by mahibi** [comment]
i didn't have a closer look so not sure if it's possible at all as it most likely depends on if the used libs provide this information. 
is it possible/planned for iOS? @Ivansss @SystemKeeper ?

**Comment by SystemKeeper** [comment]
No, not supported and not planned from the talk-ios side. iOS itself allows for emoji search from the keyboard, so not sure if we would even wanna try to implement something on our own.

**Comment by mahibi** [comment]
i will close this issue as out of scope for now.
the issue may be reassessed if 
https://github.com/nextcloud/talk-android/issues/2735
has been introduced and perhaps happens to include an interface for this feature, but I do not think this will happen.
