### ISSUE TITLE
No call notification when I´m on 4G

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/talk-android#329]
Hello mario and the other devs 😉 
It was a long time and I was oberserving it. It´s great work anyway and I don´t want to miss it anymore.

Now comes the time, that I really want to install it. I followed MichaIng tutorial to install a TURN server on my PI:
https://help.nextcloud.com/t/howto-setup-nextcloud-talk-with-turn-server/30794

I think I´ve done all alright, because in the first time I reached with my mobile device on 4G my Laptop on LAN. So I think my TURN Server is working. But I receive only in the WLAN call notifications. On 4G I need to enter the conservation manually. Is it exspected behavior? So I don´t know it acutally, because I was long time AFK on Github, because I started a new Job. 🍌 

I have Version 3.0.1 with Nexcloud 14.0.3 and my device is the all time loved HUAWEI Y6 2017 😬 😁 😉

**Comment by mario** [comment]
Welcome back @xXSTrikeXx! :)

Congrats on the new job.

Let me investigate this and we'll see! :)

**Comment by mario** [comment]
Could you try 3.1beta1, just in case?

**Comment by crifalo** [comment]
hello, I have the same things.
Best regards
Laurent

**Comment by mario** [comment]
@xXSTrikeXx I just tried this with latest beta and it works. Can you please try? Same for @crifalo.

**Comment by mario** [comment]
Closing until I get more info.
