### ISSUE TITLE
Can't create new account on android NC Talk

### ISSUE THREAD

**Issue by manu-p** [nextcloud/talk-android#3295]
### Steps to reproduce

Hi, I'm using NC Talk 17.0.2 from google play store (via aurora store) on a LineageOS + MicroG v20.

I already get an account on it connected to a NC server under NC 26.0.4, and **it works fine** apart no notification appears on the phone (which is another problem).

I need to create a new account on the same android NC Talk to connect another server account on another server running NC 27.0.2.

Every time I try to create this new connection, while I'm sure of the URL / user / password, after quite a long time with a black screen showing a rotating circle, the display gets back to the page asking for the URL. And the account does not exist on NC talk on my phone.

No way to get this new account created on android NC Talk! :-(

### Expected behaviour

A new account is created on android NC Talk

### Actual behaviour

Creation process fails.

### Device brand and model

Fairphone 3+

### Android version

13

### Nextcloud Talk app version

17.0.2

### Nextcloud server version

27.0.2

### Talk version

17.0.3

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

Yes

### Android logs

Where can I find it on the smartphone?

### Additional information

STUN server: stun.nextcloud.com:443

My IP is in the security white list on the NC server.

**Comment by manu-p** [comment]
Some more information.

To simplify things, let's say that an AAA account exists in android NC Talk, connected to NC server servA and that it works correctly, apart for notifications (which is another subject).
I want to create a BBB account to connect with another NC server, servB.

When I abandoned the procedure after 2 or 3 minutes staring at the spinning circle on the black screen just after entering the URL / id / password, the account was not created in android NC Talk.

On the other hand, the BBB account on servB is deactivated every time I launch android NC Talk on my smartphone. Very reproducible.

So I deleted the cache and data from the NC Talk app and went back to the beginning, starting by creating the BBB account on servB and there too, black screen, spinning circle, but I let it run longer before stopping the app.

I restart NC Talk on the smartphone and the account is there. And no problem deactivating the account on the server.

The next step is to re-create AAA connected to servA. And guess what! the account is not created but this time, the account on servA is not deactivated.

I know I've had on a previous smartphone under lineageOs at least 2 different Talk accounts connected to different NC servers and it was working well.

**Comment by mahibi** [comment]
HI @manu-p thanks for the report.
That's strange. By "deactivated" you mean that the user on the server becomes disabled, so you also can't login at server anymore?

Could you create test accounts and verify if it's the same behaviour with them, and then send me the credentials so i could test? You could send them to marcel dot hibbe at nextcloud dot com
