### ISSUE TITLE
"app not found" with http instead of https

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#33]
I accidentally typed in http://cloud.nc.c instead of https://... and login worked without a problem, but then it was shown app not found and then I was logged out.

**Comment by mario** [comment]
This is currently expected since the webview follows redirects, while the http client does not (for a reason) and I use the url the user initially entered. Since my PR to the server has been merged, I'll change the code to use the url the server returns so this will fix it.

Thanks for the report.
