### ISSUE TITLE
call notification without caller/chat name, not possible to decline

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#3315]
from @ShGKme : I had a very strange call notification from Talk Android right now. There was no caller/chat name and I couldn't decline it.

![grafik](https://github.com/nextcloud/talk-android/assets/2932790/de67a1b7-e3aa-4021-ad01-b1cedbe2adc3)

**Comment by ShGKme** [comment]
Guess from @nickvergessen - call was canceled before the screen finished

**Comment by mahibi** [comment]
same happened to me yesterday with 18.0.0 RC3 (so still a bug in 18.0.0)
