### ISSUE TITLE
Android or IOS Apps of Nextcloud Background

### ISSUE THREAD

**Issue by Gowtham-eng** [nextcloud/talk-android#3316]
Hi Guys,

We are using the Nextcloud application in our organization of Nextcloud22.2 Version.

As I am new to Nextcloud I have to know some features whether it is available or not.

1) I need to change my Nextcloud Talk mobile application either in IOS or Android background with some photos or logos while we chat which is similar to what we can able to change in the WhatsApp application.
2) Is there we can open the Nextcloud Talk application for Android or IOS offline like WhatsApp chat.
3) Is there we can migrate every individual Nextcloud Application of Talk, Files, Deck, Calendar, Contact into a single mobile application.
Kindly give me a suggestion for whether the above options are available or if it is not how we can able to achieve this above process.

**Comment by mahibi** [comment]
1. there are no background photos available right now

2. there android talk app has no offline support for now. We are planning to do this but it's a quite huge goal so it still takes some time. iOS talk already has ofline support.

3. no, not every server app is available as single mobile app. Currently there is official support for files, talk and notes. Beside deck, there may be also so more good community developed nextcloud apps.
