### ISSUE TITLE
New lines removed from message

### ISSUE THREAD

**Issue by mrtumnus** [nextcloud/talk-android#3335]
### Steps to reproduce

Write a message with line breaks/new lines by pressing the Return/Enter button on the keyboard and continuing to type. For example:

```
Hello
World
```

### Expected behaviour

Message should display line breaks as provided when written.  In the example provided above:

```
Hello
World
```

### Actual behaviour

Line breaks in text are replaced with spaces. With the example above:

```
Hello World
```

### Device brand and model

Samsung Galaxy S22

### Android version

13

### Nextcloud Talk app version

17.1.0

### Nextcloud server version

27.0.2

### Talk version

17.0.3

### Custom Signaling server configured

No

### Custom TURN server configured

No

### Custom STUN server configured

No

**Comment by mrtumnus** [comment]
It should be noted that the Talk app on the server's web interface shows new lines properly.

**Comment by mrtumnus** [comment]
I think this is a result of Markdown support introduced in 17.1.  I found that if you put two spaces at the end of each line, a line break is inserted.

However, I still think this is an issue for many users.  Is there a way to disable Markdown unless it's invoked or requested somehow?

**Comment by AndyScherzinger** [comment]
Whoops...
