### ISSUE TITLE
Contacts list is empty

### ISSUE THREAD

**Issue by wargreen** [nextcloud/talk-android#338]
On my nexus 7, nextcloud-talk 3.01 from f-droid and NC 14.0.2, the contact list is empty, and no request seem to be done to our server (log level 0). Discussion list is correctly filled.
I havn't succeed to get any log via logcat.

**Comment by wargreen** [comment]
I have never build anything for android, but i will try !

**Comment by wargreen** [comment]
Same issue after installing the 3.1 apk from github's releases.
The first "wait round" is infinite (all the night and today, at least), and the contact list is empty after relaunch.

**Comment by mario** [comment]
What version of android? Http or https?

**Comment by wargreen** [comment]
I run lineageOS 14.1 without gApps.
Same problem when i specify https.
On our server we have an http redirection 80 to 443. (cloud.lebib.org)

**Comment by mario** [comment]
Can you send a test account to Mario@nextcloud.com?

**Comment by wargreen** [comment]
You can freely register on the homepage ;)

**Comment by wargreen** [comment]
I've same issue on another android device.
Maybe i search about a wrong thing ? Is the contact panel should display the contacts who are in the contact's app in my NC server and via carddav sync ?

**Comment by cron0mat** [comment]
There is an option at _Sharing_ on _administrator settings_ called _auto-completion of usernames_ 
(Deutsch : Die Auto-Vervollständigung von Benutzernamen im Teilen-Dialog erlauben...)

This needs to be checked to allow nextcloud-talk android app to discover usernames and fill the contacts list !

**Comment by emersonkfuri** [comment]
> There is an option at _Sharing_ on _administrator settings_ called
> _Allow username autocompletion in share dialog_
> (Deutsch : Die Auto-Vervollständigung von Benutzernamen im Teilen-Dialog erlauben...)
> 
> This needs to be checked to allow nextcloud-talk android app to discover usernames and fill the contacts list !

Considering we don't want to use username autocompletion in share, the contacts interface on android-talk should permit to search for full username/email as web interface permits, right?
