### ISSUE TITLE
Starting a call: more feedback needed

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#34]
I started a call on our company instance and also tried it with a local server.
As soon as I start a call I see myself (front camera), but do not see any recipient. 
Trying to start a call on the web ui also did not succeed.

The question is now, what is happening. Is it really trying to connect? So any feedback is necessary.

(Edit: I used the self compiled version directly out of AndroidStudio on an Samsumng S5 Neo)

**Comment by mase76** [comment]
Similar here. The webif gets a signalling, even from a caller with the android app. But no signalling in the android app at all.

**Comment by mario** [comment]
Good things come to those that wait :P

**Comment by mase76** [comment]
Are Google services needed for this to work?

**Comment by mario** [comment]
Google Play services are needed for the push notifications, not for this particular issue.

**Comment by mase76** [comment]
Since the latest server update, I am able to establish a call. There is no notification when a call arrives, even when the app is open, but basically the conversation works.

**Comment by jobyrlen** [comment]
I'm unable to make it work as well. I wrote about it on the Nextcloud community forum: https://help.nextcloud.com/t/using-nextcloud-talk-in-a-vpn/26015/4

Is there an ability to turn on verbose logging in the app? I don't see much when running adb logcat.

**Comment by mario** [comment]
@jobyrlen will answer you in the forums.
