### ISSUE TITLE
Feature Request: Log in security, code, password and fingerprint

### ISSUE THREAD

**Issue by kekePower** [nextcloud/talk-android#340]
Hi.

I'd love to see the same feature as in the main NC app where I can lock access with a password and use my fingerprint to log in.

TIA.

Cheers,
kekePower

**Comment by mario** [comment]
Can you clarify why? I mean it's just like your dialer / viber / whatsapp / whatever app. If you use locking in any way throughout your system, you cannot open the app without unlocking the system first anyway.

**Comment by kekePower** [comment]
Thanks for getting back to me.

I have safe zones where I don't have to unlock my phone and it's also connected to my smart watch.
Don't want anybody looking at my chats even if I'm around.

And I've also enabled this feature in WhatsApp for this reason alone.

Cheers,
kekePower

**Comment by mario** [comment]
After careful consideration, we're going to implement this eventually. Thanks for your request.

**Comment by mario** [comment]
Will track it as part of 
https://github.com/nextcloud/talk-android/issues/464
