### ISSUE TITLE
Chat disappears on configuration change for the first time.

### ISSUE THREAD

**Issue by parneet-guraya** [nextcloud/talk-android#3407]
### Steps to reproduce

- open any chat
- rotate the device
- see the chats disappeared

This happens only for the first configuration change, rest of the time works fine.

https://github.com/nextcloud/talk-android/assets/111801812/806ecd32-7264-457d-aeb5-ca5ca4d59e9b

### Expected behaviour

- Should show the chat on configuration change.

### Actual behaviour

- Chat disappears on configuration change.

### Device brand and model

OnePlus 9RT

### Android version

13

### Nextcloud Talk app version

v17.20.0 Alpha 10

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment]
can reproduce this
