### ISSUE TITLE
no push notifications if app is closed but conversation was opened before

### ISSUE THREAD

**Issue by torarg** [nextcloud/talk-android#341]
Nextcloud Version: 14.0.3
Android App: 3.1.0beta1

I noticed that there are no push notifications for currently opened conversations. So far this is expected behaviour, but if the app is closed or backgrounded when inside a conversation, the push notifications still keep missing. 

If I reopen the app and explicitly leave the conversation and then close the app, the push notifications will work again.

I hope this is the right place for this, I could not determine if the context checking is done inside the app or server part of talk.

**Comment by mario** [comment]
Partly a server issue. But let me try to workaround it :)

**Comment by mario** [comment]
Hopefully fixed for 3.1beta2, but feel free to re-open the issue once beta is released if it doesn't fix it! :)

**Comment by robertfromont** [comment]
Did this make it into a release yet (v3.1.1 is still seems to have the issue)?

**Comment by mario** [comment]
@robertfromont it did and it should work. Can you tell me how are you testing?

**Comment by robertfromont** [comment]
Same process as here:
[https://github.com/nextcloud/talk-android/issues/315](https://github.com/nextcloud/talk-android/issues/315)
i.e.:

1. Person A sends message to Person B (there's a notification on phone B, yay!)
2. Person B opens the conversation.
3. Person B hits the home button (without leaving the coversation).
4. Person A sends another message, there's no notification on phone B

**Comment by mario** [comment]
Well damn...let me re-test this again. Sorry for the trouble @robertfromont :(

**Comment by mario** [comment]
I can reproduce, sorry about that. The fix will be in 3.1.2. Let me know if it doesn't fix it for you @robertfromont.

**Comment by robertfromont** [comment]
Thanks, I really appreciate the quick response @mario

**Comment by robertfromont** [comment]
Now I get the notification if the app is in the background (yay!).
But I also get a notification if the app is still in the foreground.  For my purposes, that's probably fine, actually, but it might not be what you intended.

**Comment by mario** [comment]
Please do let me know. I appreciate the feedback btw! :)
