### ISSUE TITLE
[Feature Req] Nicer Contacts List

### ISSUE THREAD

**Issue by SteveYoungs** [nextcloud/talk-android#343]
I'd like to suggest a couple of improvements to the contacts list, specifically how groups are listed.  Instead of listing them interspersed with normal contacts, put all of the groups at either the top or bottom of the list.  Having a way to see the members of a group would be really nice too, so maybe group contact entries could be expandable to reveal the members.

**Comment by mario** [comment]
Partly implemented for beta2.
