### ISSUE TITLE
Talk app crashes when there is a guest user present without a specific name given

### ISSUE THREAD

**Issue by v3DJG6GL** [nextcloud/talk-android#3442]
### Steps to reproduce

1. Create a new public conversation and use the public link e.g. on your computer browser where you are not logged in with your nextcloud account. I use my browsers _Incognito_/_Private Window_ feature.
2. Don't rename the guest user.
3. Start a call. It doesn't matter if you initiate the call on your desktop browser or on your _Nextcloud Talk_ mobile app.
4. Shortly after both participants have joined the call, the _Nextcloud Talk_ app will crash.

### Expected behaviour

After starting the call, the app shouldn't crash, no matter if the guest account has still its default _Guest_ name.

### Actual behaviour

As mentioned, the _Nextcloud Talk_ app crashes shortly after both participants joined the call.

**Workaround:**

- Shortly after opening the public link, the guest user has to rename their guest account **before** starting the call. Changing the name afterwards has no effect in the above mentioned crashing behavior of the _Android Talk_ app

### Device brand and model

Fairphone 5

### Android version

12

### Nextcloud Talk app version

v17.1.2

### Nextcloud server version

27.1.3

### Talk version

17.1.2

### Custom Signaling server configured

None

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

### Additional information

- STUN & TURN server: https://github.com/ich777/docker-stun-turn-server

**Comment by mahibi** [comment]
already fixed with https://github.com/nextcloud/talk-android/pull/3427, release will come soon
