### ISSUE TITLE
Delete message / sent photo file in app

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [nextcloud/talk-android#3467]
In the nextcloud talk browser version it is possible to send messages and delete them afterwards.
In the android app not. Especially if its photos which where sent.

Steps to reproduce:

- Send photo
- Try to delete the message / photo from the chat

**Comment by mahibi** [comment]
Just tested for text and photos and works as expected. 
Which version did you use?

Please be aware that deletion is only available within 6 hours after posting. In the app as well as in web.

**Comment by GVLLIFESTYLE** [comment]
I use version 17.1.3 android on samsung
It does not work
Do you have a mail addr or something, that I can send you a video to show you?

**Comment by mahibi** [comment]
ah for photos you're right, it was fixed but was not backported to 17.x. 
see https://github.com/nextcloud/talk-android/pull/3319
The fix will be available with v18.0 soon.

**Comment by GVLLIFESTYLE** [comment]
perfect
