### ISSUE TITLE
app crash after clic on info button on conversation

### ISSUE THREAD

**Issue by EricThi** [nextcloud/talk-android#347]
Hello,

I update now my app to last release beta (3.1.0beta2) and check new and test already feature.

i crash many time my apps ( android rebooted between test)

for sure, see my screenshot for version android
where a touch for crash my app
my  :
https://nextcloud.eric.ovh/s/fNjRDJYgER4ezZF

i don't any log on app (not same for app nextcloud with tab log on expert mode) 

I can help you, don't hesitate to tell me.

Eric.

N.B. : sorry for my bad english

**Comment by mario** [comment]
Should be fixed in beta3

**Comment by mario** [comment]
Thanks for the report btw!

**Comment by EricThi** [comment]
nice, thank a lot for hard work

**Comment by EricThi** [comment]
update and fix it :D

**Comment by mario** [comment]
Thanks for the update.
