### ISSUE TITLE
Iphone compatibility

### ISSUE THREAD

**Issue by felipexpert** [nextcloud/talk-android#348]
I am going to write a app (probably with ionic to be executed on Android and IPhone) that will help my local commerce, making it ease to find everything. My project basically is a organization of stores and a chat, I would like to integrate your chat part with it, but it also has to run on Apple devices, I would like to know if I can do it. Thank you!

**Comment by mario** [comment]
Sure, you can use the same APIs that this app uses to talk to the Spreed app on the server.
