### ISSUE TITLE
Constantly crashing

### ISSUE THREAD

**Issue by mollat** [nextcloud/talk-android#349]
I am using a nightly LineageOS 14.1 (Android 7.1.2) on a Galaxy Note 3.

Unfortunately Talk crashes reliable when I push it into the background (with the home button) from the chat view, or when I push on 'Phone' or 'Cam' in the chat view. It does not crash when I push the home button from the _chat_overview_. However - it does not pull messages though in the background.

I already tried to install microG. Tried versions 3.0.1 and 3.1.0beta4. No app restrictions are set in Android.

Did I miss anything? Or can I get somehow debug logs from the app to see which call crashes?

Regards, Andreas

**Comment by mollat** [comment]
Good hint. Found some log entries:

``11-14 11:40:28.941  3983  3983 E AndroidRuntime: FATAL EXCEPTION: main
11-14 11:40:28.941  3983  3983 E AndroidRuntime: Process: com.nextcloud.talk2, PID: 3983
11-14 11:40:28.941  3983  3983 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.bluelinelabs.conductor.internal.LifecycleHandler.getRouters()' on a null object reference
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at com.bluelinelabs.conductor.ActivityHostedRouter.getSiblingRouters(ActivityHostedRouter.java:120)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.removeAllExceptVisibleAndUnowned(Router.java:861)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.setBackstack(Router.java:408)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.popToTransaction(Router.java:701)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.popToRoot(Router.java:284)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.popToRoot(Router.java:268)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at com.nextcloud.talk.controllers.ChatController$8.onNext(ChatController.java:642)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at com.nextcloud.talk.controllers.ChatController$8.onNext(ChatController.java:633)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
11-14 11:40:28.941  3983  3983 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
11-14 11:40:28.947  2933  2946 W ResourceType: No package identifier when getting value for resource number 0x00000000
11-14 11:40:28.951   786   801 W BroadcastQueue: Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to ProcessRecord{672a161 3174:com.amazon.venezia/u0a80} (pid=3174, uid=10080) requires android.permission.READ_LOGS due to sender android (uid 1000)
11-14 11:40:28.951   786   801 W BroadcastQueue: Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to de.amazon.mShop.android/com.amazon.mcc.crashreporter.android.CrashReportBroadcastReceiver requires android.permission.READ_LOGS due to sender android (uid 1000)

**Comment by mario** [comment]
Thanks. Let me try to reproduce this somehow.

**Comment by mario** [comment]
@mollat would you mind if I reopened the issue and tried to fix it anyway? While I can't reproduce it, and neither can you on your other phone it's probably an issue that arises under certain conditions - and I'd like to avoid it if I can.

**Comment by mollat** [comment]
No problem. I still have the phone here... ;)

**Comment by mario** [comment]
Will release beta5 today so  maybe you can try @mollat :)

**Comment by mario** [comment]
Yes, sorry - beta6 is out.

**Comment by mollat** [comment]
No crashes anymore with 3.1.0. Thanks!

**Comment by mollat** [comment]
Thanks for fixing so rapidly... ;)
