### ISSUE TITLE
Won't login after change to DNS (server move)

### ISSUE THREAD

**Issue by tkintenn** [nextcloud/talk-android#350]
Opened Per Mario feedback via google play
Actual behaviour

I copied my NC files and DB to a new VM (moved it from 1and1 hosting). Then upgraded from 13 to 14. Talk app would not login, just said "Redirecting" and logs shows an invalid login for my user. Web interface worked fine. The Nextcloud app worked just fine.
The background was intentionally made different so i could tell when DNS switch had started working. Both Android NextCloud Talk and the Next Cloud app showed the new background image.
Expected behaviour

It would login.
Steps to reproduce

    Move to a new IP for your NC instance
    Try to login with Talk
    Fail

How I fixed it

Cleared the data and cache on the Talk App. It appeared (after watching network attempts via packet capture) that it had cached the IP of the URL. Once I cleared it's data, it correctly used the new IP.

Seems it should resolve the url to IP on each open.
Environment data

Android version: 8

Device model: LG V20

Stock or customized system: Stock

Nextcloud app version: Talk 3.1.0beta4

Nextcloud server version: 14.0.3

**Comment by hoerup** [comment]
I had a simliar experience although the entrypoint was different. After changing my nextcloud password, i just couldn't get Nextcloud Talk app working again. Tried removing and re-adding accounts - removing and re-installing app didn't help either. But after clearing both data and cache on app i was able to login once again.

**Comment by mario** [comment]
Since you seem quite adept at using networks, can you verify if you've had a 503 response with the old IP before you cleared cache/data?

**Comment by nickvergessen** [comment]
Hello there,

we are currently cleaning up old/stray github issues. Can you please retry with the current version and report back if the problem still persists for you?

cheers
