### ISSUE TITLE
No notifications with microg

### ISSUE THREAD

**Issue by pgera** [nextcloud/talk-android#351]
I think this used to work earlier, but I'm not getting notifications for texts or calls although the app registers with microg gcm successfully. The microg settings just says no messages received so far. Has something changed recently ? Any way to debug ? Server and client are at latest stable versions. Tried the beta for the app too but didn't help.

Edit: I see a bunch of these messages on the server log: GuzzleHttp\Exception\ServerException: Server error: `POST https://push-notifications.nextcloud.com/notifications` resulted in a `503 Service Unavailable` response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>503 Service Unavailable</title> </head><body> <h1 (truncated...)

**Comment by mario** [comment]
Let me check if something is wrong with the push infrastructure.

**Comment by mario** [comment]
@pgera should work now - feel free to reopen the ticket if it does not. 

Thanks for raising this issue and sorry for the troubles this caused you, we've had a slight hiccup with the infrastructure.

**Comment by pgera** [comment]
Thanks. Works.

**Comment by pgera** [comment]
Btw, are there any plans to make the push server code open and/or included within the main server ? Would it work if I use my own google api keys for accessing google apis ?

**Comment by mario** [comment]
@pgera it's not a PHP component so it cannot be included with the main server.

If you use your own Google API keys it might still work, yes (with some work), but it'll use our infrastructure.
