### ISSUE TITLE
Pixel 2 instant crash

### ISSUE THREAD

**Issue by xf-** [nextcloud/talk-android#354]
Last beta update of Nextcloiud Talk App (22. Nov via Google-Play 3.1.0beta5) crashes instant on Google Pixel 2 while opining the app.

**Comment by mario** [comment]
I know, sorry about that - beta6 is already out.

**Comment by xf-** [comment]
Thx for quick update :) Wasn't able to find any newer update. Maybe stuck in review process. I will test it again after the update is available.
