### ISSUE TITLE
Accounts disappear and from there they cannot be created anymore

### ISSUE THREAD

**Issue by aluaces** [nextcloud/talk-android#3544]
### Steps to reproduce

I don't really know how this is triggered, but it happens to me having two different accounts, and from time to time one of them disappears.

It might be related to a temporary connection issue.

### Expected behaviour

No configured account should be missing unless explicitly deleted by the user.

### Actual behaviour

After that, I cannot add the missing account again, since after the *grant permissions* screen the app gets back to the main screen, without any message.

The deleted account can be different each time, it's not a server specific problem.

I have tested this with f-droid and with the googleplay version.

### Device brand and model

xiaomi and realme

### Android version

8 and 11

### Nextcloud Talk app version

18.0.0, but previous as well (at least 17)

### Nextcloud server version

25, 26, 27, 28

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by TwizzyDizzy** [comment]
Possible duplicate of #2446 (have just commented there, since it's still an issue.

**Comment by aluaces** [comment]
Yes, you are right, thanks.  I'm closing this and continuing there.

**Comment by migulen** [comment]
> Yes, you are right, thanks. I'm closing this and continuing there.

@aluaces  If you delete the visible account, the invisible account reappears. ;-)
