### ISSUE TITLE
Note to self icon does not display

### ISSUE THREAD

**Issue by louim-lbs** [nextcloud/talk-android#3547]
### Steps to reproduce

Open Talk

### Expected behaviour

Note to self icon

### Actual behaviour

Black hole

![SmartSelect_20231225_130322_Talk](https://github.com/nextcloud/talk-android/assets/82395416/9b470c93-57ff-489b-8fff-0751ebdb8801)

### Device brand and model

Samsung S20 FE

### Android version

13

### Nextcloud Talk app version

18.0.1

### Nextcloud server version

28.0.1

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by louim-lbs** [comment]
Still happening in 18.1.0

**Comment by mahibi** [comment]
Is it shown on web?
I don't have any ideas off the top of my head, except possibly to clear the cache for the app (requires new login)

**Comment by louim-lbs** [comment]
Hello,
No problem on web. Clearing the cache does nothing...
BTW, here is a screenshot.
![img](https://github.com/nextcloud/talk-android/assets/82395416/9d8257bc-39d6-4d63-abe4-28f69e417ec1)

**Comment by mahibi** [comment]
Found out this fails as there is a hardcoded check if the string is "note to self" which fails for translations.
Will change this check!
Workaround for now would be to use english
