### ISSUE TITLE
Move the hang up button to a different place?

### ISSUE THREAD

**Issue by kendy** [nextcloud/talk-android#357]
I was wondering if it was possible to move the hang up button (in the videoconference screen) to some other place; like eg. the top (be it middle, left or right), so that it is hard to touch it by mistake when muting / unmuting? I can even imagine the hang up button in the middle of the screen - the buttons appear after tapping anyway.

I know that ~all the videoconferencing apps have the buttons at the bottom, in the 'mute, hang up, camera on/off' order, but with the hang up button next to the mute, it happens to me too often that I hang up instead of unmuting.  Would be awesome if the Nextcloud Talk was the first app that has done it right :-)

[PS: Hi Mario!  You suggested to file this - so I'm doing so :-)]

**Comment by mario** [comment]
Thanks for this. It will be fixed in the next stable release.

**Comment by mario** [comment]
Fixed. This is how it looks now:

![screen shot 2018-11-29 at 14 36 57](https://user-images.githubusercontent.com/5810/49225397-40335880-f3e4-11e8-8c21-072986dc9008.png)

**Comment by kendy** [comment]
Awesome, thanks so much! :-)
