### ISSUE TITLE
Error when edit personal informations

### ISSUE THREAD

**Issue by wargreen** [nextcloud/talk-android#3570]
### Steps to reproduce

1. Go to Parameters > Click on Profile picture
2. Edit the profile, add or edit informations
3. Save & see error

### Expected behaviour

We can edit the own profile.

### Actual behaviour

Error "Failed to save *EDITED FIELD*"

No edit done.

### Device brand and model

Sony z3c

### Android version

11, LineageOS 18.1

### Nextcloud Talk app version

17.1.3

### Nextcloud server version

28.0.1.1

### Talk version

18.0.1

### Custom Signaling server configured

No

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

### Android logs

01-11 01:46:58.212 16796 16796 E ProfileController: Failed to saved:  as PHONE
01-11 01:46:58.212 16796 16796 E ProfileController: retrofit2.adapter.rxjava2.HttpException: HTTP 403 
01-11 01:46:58.212 16796 16796 E ProfileController: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
01-11 01:46:58.212 16796 16796 E ProfileController: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
01-11 01:46:58.212 16796 16796 E ProfileController: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
01-11 01:46:58.212 16796 16796 E ProfileController: 	at io.reactivex.Observable.subscribe(Observable.java:12284)
01-11 01:46:58.212 16796 16796 E ProfileController: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
01-11 01:46:58.212 16796 16796 E ProfileController: 	at io.reactivex.Observable.subscribe(Observable.java:12284)
01-11 01:46:58.212 16796 16796 E ProfileController: 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
01-11 01:46:58.212 16796 16796 E ProfileController: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
01-11 01:46:58.212 16796 16796 E ProfileController: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
01-11 01:46:58.212 16796 16796 E ProfileController: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
01-11 01:46:58.212 16796 16796 E ProfileController: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-11 01:46:58.212 16796 16796 E ProfileController: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
01-11 01:46:58.212 16796 16796 E ProfileController: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-11 01:46:58.212 16796 16796 E ProfileController: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-11 01:46:58.212 16796 16796 E ProfileController: 	at java.lang.Thread.run(Thread.java:923)

### Server log

```bash
10.13.255.208 - wargreen [11/Jan/2024:01:03:49 +0000] "PUT /ocs/v2.php/cloud/users/wargreen HTTP/1.1" 403 110 "-" "Mozilla/5.0 (Android) Nextcloud-Talk v17.1.3"
10.13.255.208 - wargreen [11/Jan/2024:01:03:49 +0000] "PUT /ocs/v2.php/cloud/users/wargreen HTTP/1.1" 403 110 "-" "Mozilla/5.0 (Android) Nextcloud-Talk v17.1.3"
10.13.255.208 - wargreen [11/Jan/2024:01:03:50 +0000] "PUT /ocs/v2.php/cloud/users/wargreen HTTP/1.1" 403 110 "-" "Mozilla/5.0 (Android) Nextcloud-Talk v17.1.3"
10.13.255.208 - wargreen [11/Jan/2024:01:03:50 +0000] "PUT /ocs/v2.php/cloud/users/wargreen HTTP/1.1" 403 110 "-" "Mozilla/5.0 (Android) Nextcloud-Talk v17.1.3"
10.13.255.208 - wargreen [11/Jan/2024:01:03:50 +0000] "GET /ocs/v2.php/apps/spreed/api/v4/room/bnm4uiiz/participants?includeStatus=true HTTP/1.1" 200 529 "-" "Mozilla/5.0 (Linux) Nextcloud-Talk v0.20.0"
```

### Additional information

From browser :
`[11/Jan/2024:01:18:35 +0000] "PUT /ocs/v2.php/cloud/users/wargreen HTTP/1.1" 200 81 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"`

**Comment by wargreen** [comment]
Seem resolved after uninstall // reinstall NC Talk. But i wonder why...

**Comment by mahibi** [comment]
no idea yet. I will close for now but feel free to reopen if this happens again
