### ISSUE TITLE
18.0.1:  conversation popup: flip from horizontal to vertical kills app

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#3572]
1. open a conversation
2. take a picture
3. tip send
4. the add to conversation popup appears:
![image](https://github.com/nextcloud/talk-android/assets/24530680/8875ad2c-afee-4c23-874d-155e9d4651ea)
7. flip from horizontal to vertical or vise versa
8. the app is killed or the conversation and the pic is lost

### Device brand and model

Pixel 4a

### Android version

14

### Nextcloud Talk app version

18.0.1

**Comment by parneet-guraya** [comment]
I can reproduce this issue. picking this up.
