### ISSUE TITLE
i18n: Need context for build flavour

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/talk-android#3576]
https://github.com/nextcloud/talk-android/blob/a3d77f75632941bab325b0a6e87fbc082df15cb6/app/src/main/res/values/strings.xml#L214

Please enlight us (the translators).

Add it to the sources.

**Comment by AndyScherzinger** [comment]
It basically tells you the type of build. F-droid or. Play, debug or. Release, QA-build.

I Would say should be marked as translatable false.

**Comment by AndyScherzinger** [comment]
But leave it to @mahibi to decide

**Comment by AndyScherzinger** [comment]
@rakekniven how can context be provided for Android Strings?

**Comment by mahibi** [comment]
> I Would say should be marked as translatable false.

sure, lets do this https://github.com/nextcloud/talk-android/pull/3579
