### ISSUE TITLE
Talk 3.1.0 typo on start screen

### ISSUE THREAD

**Issue by j-ed** [nextcloud/talk-android#359]
The latest Nextcloud Talk app cfor Android 3.1.0 ontains a typo on the start screen of German devices. If you choose "Unterhaltungen" you can read "`Kliacken` Sie auf Start um ..." instead of "**`Klicken`** ...".

**Comment by mario** [comment]
HI @j-ed,

would you be so kind to contribute here?

https://www.transifex.com/nextcloud/nextcloud/android-talk/  :)

That way the translation will make it in.

**Comment by j-ed** [comment]
@mario [x] done.

**Comment by mario** [comment]
Thanks for the contribution :)
