### ISSUE TITLE
Avatar icon update (status/self)

### ISSUE THREAD

**Issue by bugsyb** [nextcloud/talk-android#3649]
### Steps to reproduce

1. Have Talk connected to NC already.
2. Update avatar to new icon from either Talk, NC directly or an other way.

### Expected behaviour

Avatar should be updated everywhere, i.e. on app restart, including top right avatar icon on the list of conversations.

### Actual behaviour

Old avatar is there, the one initially at the first login to NC.
Tried replacing avatar from both Talk, NC and restarting Talk, restarting phone.

At the same time in conversation the new avatar is visible.

Erasing all app data and re-login to NC brings the new avatar.

### Device brand and model

Samsung

### Android version

13

### Nextcloud Talk app version

18

### Nextcloud server version

27.1.2

### Talk version

18.0.1

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment]
Can confirm that after changing on server, the top right avatar in app remains the old one, while in account settings the new one is shown.
However restarting the app should show the new avatar (restart= Not just bring the app to background but kill the app and open again).
Can you confirm/ try another time?

Changing the top right avatar faster may be improved, but it's not high priority.

**Comment by joshtrichards** [comment]
See #1490
