### ISSUE TITLE
Talk app doesn't open file links with the Nextxloud Files app

### ISSUE THREAD

**Issue by schiessle** [nextcloud/talk-android#3669]
### Steps to reproduce

1. Receive a internal file link with the Talk app (latest beta from the play store)
2. Click on the link

### Expected behaviour

Nextcloud Files app opens the file.

### Actual behaviour

The link opens in the browser

### Device brand and model

samsung

### Android version

14

### Nextcloud Talk app version

18.1.0RC2

### Nextcloud server version

28.0.8.1

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

### Additional information

Tested with c.nc.com

Until recently links where opened with the files app as expected. This was implemented at the last Nextcloud conference by Tobias and Andy.

**Comment by AndyScherzinger** [comment]
I think this is rather Files app issues than a Talk app issue. Right @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Hm. Depends…Talk needs to send it to Files app.
So might be a problem on Talk or Files.

@mahibi can you check this?

**Comment by schiessle** [comment]
from a stupid user perspective: If I click the link on the Talk app and the browser opens, I assume the problem is the Talk app because at this point the Files app was not yet involved. I would expect that the Talk app calls the Files App directly and I thought this is how you implemented it last year in Berlin... But maybe I misunderstood the whole concept.

**Comment by mahibi** [comment]
For me this works fine.

files app 3.28.0
talk app 18.1.0RC2 as well as 19.0.0alpha01

Tested following scenario on sermo and c.n.c:
1) in web: create file and add other person by search for username in "Search for share recipients" and save share
2) copy the internal link and paste to chat
2) have the files app installed with the same user as for talk app
3) click on link in chat
4) files app opens and shows the file

Is your scenario somehow different?

**Comment by schiessle** [comment]
Scenario seems to be correct.

I just did a even simpler test.

1. Copy the internal link of a personal file
2. Send it to me via Talk "note to myself"
3. Open Android Talk App
4. Click on the link
5. Firefox on Android opens instead of the files app :cry: 

My Talk App: 18.1.0 RC2 (only c.nc.com configured)
Files App: 3.28.0 (two accounts configured, c.nc.com and private, talk app is protected with my fingerprint)
Android: 14 (Samsung One UI 6.1)

**Comment by mahibi** [comment]
seems i did not send my answer last week..

I saw that there is a different handling for the link itself and the preview image, which should be unified..
Currently the link will check for the files app, the preview image not. 

Can you confirm you clicked the preview when it not worked, and if clicking the link itself works?

**Comment by schiessle** [comment]
@mahibi no, the behaviour is always the same for me -> the browser opens and not the files app. Although I'm not even sure of the talk app distinguish where I click on the chat message exactly (the preview or the link). From a user perspective it looks like the whole "message bubble" is one click area.

**Comment by jakobroehrl** [comment]
I think generally this works. 
Maybe you must re-install talk and/or the nextcloud app.

**Comment by schiessle** [comment]
> I think generally this works.
> Maybe you must re-install talk and/or the nextcloud app.

You think or you know? Did you tested it. Sorry for asking so directly but I only want to go to the process to configure both apps again (multiple nextcloud, automated file upload,..) if I really know that this fixes it.

Btw, I noticed today that also links to another chat opens the browser and not the Talk room within the Talk app. So not only the cross-app-links seems to be broken but also the app-internal one :(

**Comment by jakobroehrl** [comment]
I tested it some month ago, this fixed it for me.

**Comment by mahibi** [comment]
> @mahibi no, the behaviour is always the same for me -> the browser opens and not the files app. Although I'm not even sure of the talk app distinguish where I click on the chat message exactly (the preview or the link). From a user perspective it looks like the whole "message bubble" is one click area.

Agree that from a user perspective it looks like the whole "message bubble" is one click area. And it will be changed like this!
Just to make sure, for now if you click the link which is marked green here, also the web browser open (that's the link that opens the files app for me)?

![Bildschirmfoto vom 2024-03-26 11-08-14 geaendert](https://github.com/nextcloud/talk-android/assets/2932790/295706bc-728d-4f09-9107-5e2668b887ee)

> Maybe you must re-install talk and/or the nextcloud app.

I can't think of a reason how it should fix this. 
Are both apps installed from the same store? E.g. both playstore or both f-droid? It shouldn't even make a difference if they come from different stores, i only ask because i run out of ideas..

> Btw, I noticed today that also links to another chat opens the browser and not the Talk room within the Talk app. So not only the cross-app-links seems to be broken but also the app-internal one :(

You are talking about https://github.com/nextcloud/talk-android/issues/847 ? This is not yet implemented.

**Comment by mahibi** [comment]
Had another look..
@schiessle can you confirm that the link where it fails contains "/index.php" ? There is a bug that it fails for these links..
