### ISSUE TITLE
Microphone icon does not do PTT

### ISSUE THREAD

**Issue by bonafideb** [nextcloud/talk-android#367]
When first using the app it indicates that actively pushing the microphone icon/button will active a push to talk (PTT) functionality. This feature does not work, rather the button only works in a press and release fashion; muting and unmuting the microphone.

**Comment by mario** [comment]
Hello,

can you please confirm that the following steps do not work:

1) Disable the microphone/audio by clicking on the microphone icon
2) Click and hold the microphone icon

**Comment by mario** [comment]
Tested, works as expected. Feel free to re-open if the issue happens again.
