### ISSUE TITLE
Enhancement: Bazel Build Migration

### ISSUE THREAD

**Issue by AbdhilahiRWabwire** [nextcloud/talk-android#3673]
# Bazel Build

- I would like to migrate this project from Gradle to Bazel Build. 

-  How would the team feel about me implementing this enhancement in my fork?

- Examples: https://github.com/bazelbuild/rules_kotlin/tree/master/examples

**Comment by AndyScherzinger** [comment]
Hi @AbdhilahiRWabwire currently not a focus given the amount of work to migrate all Android projects and before that checking if all features we have in the gradle build chain would actually work out with Bazel plus gradle still being a first citizen in Android Studio.

So for the moment we would not switch away from Gradle but might in the future depending on Bazel's further development and adoption.

**Comment by AbdhilahiRWabwire** [comment]
Let me know if you change your mind in the future and I will be here to implement.
