### ISSUE TITLE
Contact screen does not show anything after finishes loading

### ISSUE THREAD

**Issue by parneet-guraya** [nextcloud/talk-android#3687]
### Steps to reproduce

- Click on Fab (with edit icon) from the main screen.
- Contacts screen will open.

https://github.com/nextcloud/talk-android/assets/111801812/708a61e3-66cc-400c-87f9-17b27479b445

### Expected behaviour

- Show data after loading 

### Actual behaviour

- Loading finishes but  no data shows.

### Device brand and model

OnePlus 9RT

### Android version

14

### Nextcloud Talk app version

v 19.0.0 Alpha 01

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment]
As discussed in public chat this was a misunderstanding an there are no other users on this instance that could be shown?

So closing this issue..
