### ISSUE TITLE
remove flickering background on top app bar of conversations list.

### ISSUE THREAD

**Issue by sowjanyakch** [nextcloud/talk-android#3688]
### Steps to reproduce

1. Open conversations screen.
2. Scroll to the bottom of the conversations.

### Expected behaviour

No flickering background should appear on the top app bar.

### Actual behaviour

The flickering background appears on the top app bar.

### Device brand and model

Samsung Galaxy A52

### Android version

11

### Nextcloud Talk app version

19.0.0

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment]
This is about the flickering background of the top bar when scrolling.

If it turns out to be difficult to find the cause, it could makes sense to use `git bisect` to find out when this bug occured.

**Comment by mahibi** [comment]
in case it helps:
it only flickers when "flipping" the list.
it won't appear when scrolling while holding finger onto the screen...
