### ISSUE TITLE
Notification shows own name in 3rd row

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#369]
Here I got a message from @mario saying "Hi Jan-C. Borchardt" (a mention). The 3rd row seems to be my own name, as it is also in other 1-on-1 messages:
![talk app notification shows username in 3rd row](https://user-images.githubusercontent.com/925062/49451921-7d328d00-f7e0-11e8-9a86-c9f02a6a1114.png)

I assume this is the room name, which by default is my own name? This we shouldn’t show as it’s not relevant for 1-on-1 calls unless the name changed from the default (other person) to a specific name.

**Comment by jancborchardt** [comment]
Could you show a screenshot of how it looks on newer Android? :) If it’s only an issue with older versions (that screenshot is from 5.1) it should be fine.

**Comment by mario** [comment]
![screenshot 2019-01-02 at 23 50 49](https://user-images.githubusercontent.com/5810/50616618-83a04b80-0ee9-11e9-9578-36ddef9147e3.png)

cc @jancborchardt 

I unfortunately do not have 5.x to test :( @tobiasKaminsky maybe?

**Comment by tobiasKaminsky** [comment]
> I unfortunately do not have 5.x to test :( @tobiasKaminsky maybe?

I only have 4.4.x, 4.0.x and 6.x as hardware devices.
But I guess that an emulator will work, at least while testing for files app, I can receive push notifications on an emulator.

**Comment by jancborchardt** [comment]
@mario on your screenshot it indeed looks way better!

- What’s "lily" in this case though? I assume the recipient / owner of the account? Do we need to display that?
- I guess you don’t have a display name set, but it would show the display name instead of the username? :)
- Still no possibility to show avatars? Is this just not done on Android messengers?

**Comment by mario** [comment]
@jancborchardt yes we do, otherwise you have no idea what account it relates to (and I have bunch of accounts).

- sure, it would be display name.

- there's an issue for avatars in notifications in the follow-up stable release  (3.3)

**Comment by jancborchardt** [comment]
>> What’s "lily" in this case though? I assume the recipient / owner of the account? Do we need to display that?
>
> otherwise you have no idea what account it relates to (and I have bunch of accounts).

2 issues here:

- In the screenshot of the notification I showed above, I only had one account configured. In this case you don’t need to have your own name shown.
- It’s very likely that your own name / username is the same on your instances. It won’t help distinguishing the message. If we want to make it distinguishable, showing the domain would be the factor to show.

**Comment by mario** [comment]
At least for me it definitely helps. But I can understand your first complain so I'll fix this if you only have one account.

**Comment by mario** [comment]
(it's unlikely the domain would fit btw in lots of cases)

**Comment by jancborchardt** [comment]
> (it's unlikely the domain would fit btw in lots of cases)

Yeah, you’re right. But even if we, say, only display the top level domain, it would already be more informative than the username. For me it would be the difference between "jan"/"jan" and "jancborchardt.net"/"nextcloud.com". :wink:

**Comment by mario** [comment]
OK, let's try that. It's an abuse of the expected text in there, but yea ... :P
