### ISSUE TITLE
Clicking on notification does nothing

### ISSUE THREAD

**Issue by mario** [nextcloud/talk-android#370]
Investigate when and why this happens.

To reproduce:
1) Have a user send you two messages
2) Only one notification will have action attached to it

**Comment by tobiasKaminsky** [comment]
If this is what we discussed, then only the latest notification works, but not the previous ones.
It also seems not matter if one dismiss the older one.

**Comment by mario** [comment]
Yup, that's it.

**Comment by pwFoo** [comment]
Push notifications should be grouped? Works with browser / push webapi.

**Comment by mario** [comment]
Sure, but that's a different matter. It's part of the #265 issue.

**Comment by mario** [comment]
This will be fixed once we move to inbox/messaging style notifications.
