### ISSUE TITLE
Thumbnail in chat not showing image or document preview. On android mobile app TALK (F-Droid)

### ISSUE THREAD

**Issue by KapriQ** [nextcloud/talk-android#3700]
### Steps to reproduce

    Sending an image or document to any of my contacts
    Receiving an image or document from any of my contacts

### Expected behaviour

The user expects to see a preview of the image or document whilst in chat without fully opening it. Instead of seeind a dummy thumbnail preview but a thumbnail preview of the actual image.

### Actual behaviour

When an image is sent or received the user cannot see the preview of it in the thumbnail, however they see the default thumbnail icon instead. As well as documents which also adopt the same be haviour.

Even after downloading the image and viewing it, a thumbnail preview of the image in chat remains the same dummy icon as shown in the images attached from both mobile and browser.

My config.php file:

`.............
'enable_previews' => true,
  'instanceid' => '
![photo_2024-03-07_18-04-43](https://github.com/nextcloud/talk-android/assets/31235411/77c8b57c-1d04-497e-9a97-d9c2edc83c35)
',
  'default_language' => 'sk',
  'maintenance' => false,
  'preview_max_x' => 1200,
  'preview_max_y' => 1200,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Movie',
    1 => 'OC\\Preview\\PNG',
    2 => 'OC\\Preview\\JPEG',
    3 => 'OC\\Preview\\GIF',
    4 => 'OC\\Preview\\BMP',
    5 => 'OC\\Preview\\XBitmap',
    6 => 'OC\\Preview\\MP3',
    7 => 'OC\\Preview\\MP4',
    8 => 'OC\\Preview\\TXT',
    9 => 'OC\\Preview\\MarkDown',
    10 => 'OC\\Preview\\PDF',
    11 => 'OC\\Preview\\JPG',
    12 => 'OC\\Preview\\Image',
  ),
.................
`

### Device brand and model

Poco F5

### Android version

13

### Nextcloud Talk app version

18.0.1 (Fdroid)

### Nextcloud server version

26.0.0

### Talk version

16.0.11

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

### Additional information

Thumbnails in Nextcloud app are working fine, also under TALK in web interface i can see thumbnails.

 But TALK apk (F-DROID) is not generating any of the thumbnails. 
 
 
![photo_2024-03-07_18-04-43](https://github.com/nextcloud/talk-android/assets/31235411/ab150c8a-8089-4dbf-9d06-4ab2a65231ac)

**Comment by Dtrieb** [comment]
Additional information

If I send a PDF file, I see the file preview in dark mode.
But without contrast, so that you can hardly see it.

**Comment by mahibi** [comment]
Can you check if previews are set up on server:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#previews

Default icons will be replaced with v19.0.0 which should also resolve the contrast issue.

**Comment by mahibi** [comment]
Do you see the previews in webUI ?

Default icons will be replaced with v19.0.0 which should also resolve the contrast issue.

**Comment by Dtrieb** [comment]
> Do you see the previews in webUI ?
> 
> Default icons will be replaced with v19.0.0 which should also resolve the contrast issue.

On my mobile in dark mode I didn't see it , too.
Look the screenshot.
![Screenshot_20240411-115633](https://github.com/nextcloud/talk-android/assets/3650284/24ebd0b5-4705-425d-b53e-fc6522a8acf5)

If I tap one time on the file I get this square around it.
![Screenshot_20240411-115432](https://github.com/nextcloud/talk-android/assets/3650284/5c2076f7-ec3a-4439-99d9-eec3304f112e)

**Comment by mahibi** [comment]
@Dtrieb Ah seems i misunderstood your comment. 
For dark preview images, please open an issue at https://github.com/nextcloud/spreed/issues

The current issue should just be about the missing previews as shown in the screenshot from @KapriQ

**Comment by mahibi** [comment]
Is this still an issue with talk app 19.0.0?
