### ISSUE TITLE
"X edited a message" system message is displayed (wrongly)

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#3732]
The message should be hidden similarly to the "X deleted a message"
If not hidden it should at least be styled like a system message.

Also the original message in the chat is not updated with the new content
![Screenshot_20240319-102841](https://github.com/nextcloud/talk-android/assets/213943/737832b2-e96a-4394-8275-3c3221f13c0c)

**Comment by mahibi** [comment]
which app version was this?
need to fix alpha builds as well as release RC1 today..
so that might explain it..

**Comment by nickvergessen** [comment]
Latest from GPlay reported as 19 alpha2 in the Talk app UI

**Comment by nickvergessen** [comment]
Update is here and it works now 👍
