### ISSUE TITLE
Username autocomplete doesn't work properly

### ISSUE THREAD

**Issue by Spartachetto** [nextcloud/talk-android#376]
I have a problem with username autocomplete.

Let us suppose that in the server that I use there is a user with a username = "mario".

If I start writing "@mar", the app correctly visualizes a tooltip with the text "@mario". I can touch the tooltip and in the text I get "@mario ". 
I then push the spacebar and I get back the text "@mar ".
  
I tried also using other characters instead of the spacebar. Same result.

App version 3.1.1 but I had this problem also with the previous versions

**Comment by mario** [comment]
Hello @Spartachetto.

I'm sorry that you're having less than perfect experience of using the Talk app. I am aware of several smaller issues with autocomplete but none like you mentioned - I did try to reproduce on a few phones.

In order to help me solve this problem for you, would you mind sharing your phone vendor and your OS version?

That would help me a lot!

Thanks,
Mario

**Comment by Spartachetto** [comment]
I have a Samsung with android 8.0.0

Is this enough information?

Thank you for your prompt reply!

**Comment by mario** [comment]
Do you use some 3rd party keyboard or something maybe?

**Comment by Spartachetto** [comment]
I use the stock Samsung keyboard. Version 3.0.23.

I do not think I have other conflicting apps. Do you have suggestions on which apps to look at?

**Comment by mario** [comment]
Not really - my issue is I have no way of reproducing this atm :( But I'm still hopeful!

**Comment by mario** [comment]
Hello @Spartachetto. v3.2.2 should be out in beta today, so if you're a beta user could you please test it?

**Comment by Spartachetto** [comment]
@mario I am a bit confused.

I was not a beta user so I thought that I could become one to give you feedback. 

I accessed the Play Store and I discovered that I had not yet updated to 3.2.1 
I thought that I could
- update to 3.2.1
- test that version
- switch to beta and update again
- test 3.2.2
- provide feedback 

I updated to 3.2.1 and tested. No problem with autocomplete ...

I double checked the setting section of the Nextcloud Talk app. It says that I am using version 3.2.3

I checked in the Play Store. It says that I am using version 3.2.3 and that I am _not_ using a beta version.

Thank you very much for solving the problem anyway and tell me if you need any more information

**Comment by mario** [comment]
@Spartachetto thank you for your patience and testing. And yes, I quickly moved the app from beta to stable after getting several confirmations it all works.

Keep using the app and give feedback when you have time - it is very valuable and appreciated.

**Comment by Spartachetto** [comment]
@mario thank __you__ !!!
