### ISSUE TITLE
Failed to fetch pending invitations

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#3771]
### Steps to reproduce

1. start app
2. see snackbar with: Failed to fetch pending invitations

### Expected behaviour

Do not really know what this is about, so probably only show it when user knows about it?

### Actual behaviour

See above

### Device brand and model

Oneplus 6t

### Android version

14

### Nextcloud Talk app version

c.nc.c

### Nextcloud server version

c.nc.c

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by vasyugan** [comment]
I'm still seeing this and I'm on version 19.0.1 of the android app.
