### ISSUE TITLE
Allow voice messages to be played at different speeds

### ISSUE THREAD

**Issue by rapterjet2004** [nextcloud/talk-android#3786]
- Related https://github.com/nextcloud/talk-android/pull/3704#issuecomment-1999927317

See [MediaPlayer Docs](https://developer.android.com/reference/android/media/MediaPlayer.html#setPlaybackParams(android.media.PlaybackParams)) and [PlaybackParams Docs](https://developer.android.com/reference/android/media/PlaybackParams#setSpeed(float)) for more info

###  See WhatsApp as an example
![image](https://github.com/nextcloud/talk-android/assets/69230048/e2c53562-f4e5-45c8-90f7-c8f3082bc8c3)

**Comment by arkascha** [comment]
I opened a PR with am implementation of this feature request: 
https://github.com/nextcloud/talk-android/pull/4482

There are a few questions to be answered in that PR, feedback is welcome!

**Comment by AndyScherzinger** [comment]
implemented thank to and by @arkascha via #4482

**Comment by machocam** [comment]
Is there an equivalent for iOS?

**Comment by mahibi** [comment]
> Is there an equivalent for iOS?

@Ivansss @SystemKeeper

**Comment by SystemKeeper** [comment]
* Not yet, theres' a feature request about that at https://github.com/nextcloud/talk-ios/issues/1261

**Comment by machocam** [comment]
upvoted! thank you
