### ISSUE TITLE
Grant for permission directly

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#380]
- install app
- start a call
- see ![2018-12-10-181434](https://user-images.githubusercontent.com/5836855/49749028-85d70780-fca7-11e8-8fbd-6ea6880f597c.png)

It should be directly asked for:
![2018-12-10-181731](https://user-images.githubusercontent.com/5836855/49749170-e5351780-fca7-11e8-9b67-11fbdd48ed4d.png)

Either on first start after installation or on first call…
(Same for camera)

**Comment by mario** [comment]
Hm, I'm just testing this and this is indeed how it works? It only shows you the settings thing if you previously said "Do not ask me again".

**Comment by tobiasKaminsky** [comment]
Tested it again with Android 9 emulator.
(initial report was discovered on a OnePlus 3, with Android 8/9).

**Comment by tobiasKaminsky** [comment]
Working.
