### ISSUE TITLE
Can't login on 15 RC3

### ISSUE THREAD

**Issue by oparoz** [nextcloud/talk-android#382]
## Steps to reproduce

1. Get your session killed
2. Try to log in using a token

### Expected behaviour

I should be logged in

### Actual behaviour

Nothing happens. I can press as many times as I want on the Grant access button. Nothing happens.

**Comment by mario** [comment]
Probably a server issue since token login didn't work for a while :)

**Comment by mario** [comment]
Fixed via 3.1.2. Sorry for the trouble. Keep in mind token login only works on Nc15+.
