### ISSUE TITLE
Consequent notifications don't produce a sound

### ISSUE THREAD

**Issue by RTechSn** [nextcloud/talk-android#3869]
### Steps to reproduce

1. Send a message from another account to your phone. Notification will produce a sound.
2. Send another message. New notification will be appended to the old one and no sound will be produced.

### Expected behaviour

New messages should trigger notification sound. This is how it's handled by every other messenger. 

### Actual behaviour

No matter how hard you try, you can't reach a person, if they missed the first notification.

### Device brand and model

Google Pixel 6a

### Android version

14

### Nextcloud Talk app version

18.0.1

### Nextcloud server version

28.0.4

### Talk version

18.0.7

### Custom Signaling server configured

No

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

### Additional information

Client push app is installed

**Comment by RTechSn** [comment]
Duplicate of #3353

**Comment by msjing-intro** [comment]
I have the same issue in my phone, my phone model is Oppo A18.
