### ISSUE TITLE
Add participant / share link in 1:1 call

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#387]
- create 1:1 call with user A
- go into conversation/room(?)
- try to add another user
or
- share link

**Comment by mario** [comment]
Sharing is already possible via conversation menu (long click on conversation), and conversations management is part of #79 :)

**Comment by tobiasKaminsky** [comment]
> Sharing is already possible via conversation menu (long click on conversation)

ah :-)
I assumed I could do this within a conversation, so you have to leave current room.

On long clicking: is there a reason why link sharing is "hidden" behind "make public"? This seems not to be necessary on web ui?

At least for me it is a bit confusing, when same behaviour is called different.
