### ISSUE TITLE
different links: open file app vs browser

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#3882]
### Steps to reproduce

An internal link is shared, now the user has 2 options:
![grafik](https://github.com/nextcloud/talk-android/assets/24530680/8bdc7dec-690f-46e2-972b-10c6aa58dcc5)
first red area leads to the browser
second red area leads to the nextcloud file app.

Would it make more sense to always use the nextcloud file app for showing the file content?

### Device brand and model

Pixel 6a

### Android version

12

### Nextcloud Talk app version

19.0.0

**Comment by mahibi** [comment]
Yes this has to be changed.
Also mentioned this behavior in https://github.com/nextcloud/talk-android/issues/3669#issuecomment-2020050553
