### ISSUE TITLE
Unsended text inside the "write text windows" is overwriten by clipboard text, when a 30seconds of time pass

### ISSUE THREAD

**Issue by migulen** [nextcloud/talk-android#3897]
### Steps to reproduce

1.- Share some text to App Nextcloud Talk via the "share to" feature
2.- Enter on a room or personal conversation.
3.- Write some text on the text windows.... AND DON'T SEND IT
4.- Wait some seconds (or a minute).... and...

### Expected behaviour

The text on the text windows doesn't dissapear, being overwriting by the clipboard text.

### Actual behaviour

The text on the text window doesn't change (not get ovewritten by the clipboard text).

### Device brand and model

Xiaomi mi Note 10 (and Samsung s24)

### Android version

14

### Nextcloud Talk app version

19.0.0

### Nextcloud server version

28.0.5

### Talk version

19.0.0

### Custom Signaling server configured

No

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

**Comment by mahibi** [comment]
Not sure if i get it and can't reproduce..
Could you share a video of this behavior?

**Comment by migulen** [comment]
@mahibi @rapterjet2004

**Comment by mahibi** [comment]
> @mahibi @rapterjet2004
> 
> This error is very annoying when someone try to write a medium or large message and gets his message deleted. I've seen that there is a patch for it on v19.0.1 of Talk.
> 
> Is there any release date to the v19.0.1 version of Talk ?

today or n the next days
