### ISSUE TITLE
share text to app: own text is overritten

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#3911]
### Steps to reproduce

1. Share text or a url from any app to a nextcloud talk conversation
2. send the message
3. type some text but not send it and wait for 1-2 mins
4. the typed text is removed and the shared text is shown up

### Device brand and model

Pixel 6a

### Android version

14

### Nextcloud Talk app version

19

**Comment by mahibi** [comment]
thanks for reporting! Closing as duplicate of https://github.com/nextcloud/talk-android/issues/3897
