### ISSUE TITLE
Can't talk to guests

### ISSUE THREAD

**Issue by ghost** [nextcloud/talk-android#392]
Devices: Samsung Galaxy Tab A (2016) - Android 8.1, Honor 9 - Android 8.0 

When I start a public call (with or without video), I am disconnected the very moment a guest who has been invited via link joins the call. However I can talk to other users when they use their own account.

**Comment by mario** [comment]
Hello @lobler. I apologize that the app did not meet your expecations. Can you please let me know what version of Nc and what version of the Spreed app are you using so I can help you better?

Thanks!
