### ISSUE TITLE
Camera switch

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#394]
Viber app switches to rear / main camera with one click to camera picture. 
will be glad if you add it in talk :)

**Comment by mario** [comment]
This is already how it works? There is an icon though...

**Comment by mario** [comment]
Let me know if that works for you @jookk :)

**Comment by jookk** [comment]
Yes, working.

**Comment by mario** [comment]
@jancborchardt do you think that the tap on the Camera preview should also toggle camera switch action?

**Comment by jookk** [comment]
Yes 👍🌝

Dňa 10. januára 2019 12:51:58 používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by jancborchardt** [comment]
Yeah, it sounds like it’s more accessible when the whole camera image is tappable. @Ivansss is that also possible on iOS? We should still show the "camera switch" icon though so people know they can tap.
