### ISSUE TITLE
Control conflict between app and web interface

### ISSUE THREAD

**Issue by Pillaknuff** [nextcloud/talk-android#396]
To reproduce:
1) sign in to the nextcloud Talk Webinterface
2) sign in with the nextcloud android app (iOs has the same problem as well)
3) start a call via web interface to another web interface
4) leave call using the smartphone control
=> now joining can only be done using the smartphone, the join conversation button in the web interface does nothing. If joining or calling via the app, video and voice are still taken from the open web interface instead of the phone.

Versions: Server App 4.0.1, Nextcloud version 14.0.3
Android app version: 3.1.2

**Comment by mario** [comment]
Since you mentioned the iOS has the problem as well, maybe it's a server problem @nickvergessen ?

**Comment by mario** [comment]
Ok, so this is expected. Understood! :)
