### ISSUE TITLE
Creating public conversation user interaction

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/talk-android#3992]
### Steps to reproduce

1. Set up an account
2. Click the pencil icon at the bottom right
3. Click *+ New public converstation*

### Expected behaviour

I am taken to the next step where I pick a name for the conversation

### Actual behaviour

The element *+ New public conversation* changes to *Public conversations let you invite people from outside through a special crafted link.*.
As a user it is not clear what I have to do next. The app still lists users I could pick. Apparently I need to click *Done* at the top right.

The interaction is generally very different to the web app.

### Device brand and model

Google Pixel

### Android version

14

### Nextcloud Talk app version

v19.0.1

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment]
duplicate of 
https://github.com/nextcloud/talk-android/issues/3794
https://github.com/nextcloud/talk-android/issues/1463
will be fixed with https://github.com/nextcloud/talk-android/pull/4064
