### ISSUE TITLE
Calling and Videoconference have "dark/dissabled"  icons on a conversation on Dark Theme

### ISSUE THREAD

**Issue by migulen** [nextcloud/talk-android#4012]
### Steps to reproduce

1. Open talk
2. Open a Conversation
3. See the upper bar. You can see phone and videoconferece icons dark

### Expected behaviour

These icons have to be shown like "active/white".

### Actual behaviour

These icons seems "disabled".

### Device brand and model

All

### Android version

13

### Nextcloud Talk app version

19.1.0-RC1

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by AndyScherzinger** [comment]
@migulen do oyu have a screenshot of it? Looks good to me on latest master/stable version. I case you don't have the permission within a room to start a call of any kind I would expect them to be "dark".

**Comment by migulen** [comment]
Hi @AndyScherzinger. The screenshot:

![Dark_disabled_icons_call_videocall](https://github.com/user-attachments/assets/af39b54e-d143-4f39-b0d4-56df189bf3d7)

On previous  version I think it was white.

I've corrects permissions to call and videocalling, and i can DO call and videocall. 

I test talk 19.1.0-RC1 with:   

1. NextCloud Server 28.0.4 / Talk (Spreed): 18.0.7
2. Nextcloud Server 25.0.12 / Talk (Spreed): 15.0.8

Hope it helps.

**Comment by mahibi** [comment]
seems it's broken for dark/light mode differently. For me it is like this (i'm able to do calls and all buttons are enabled):

![grafik](https://github.com/user-attachments/assets/60fcb055-ee5e-428d-9823-fb4feb617702)
all buttons look like disabled.

![grafik](https://github.com/user-attachments/assets/6fea2061-fdfe-4193-95c6-c893967a2344)
three-dot-button looks like disabled.

It seems the first broken release with this was [19.0.0rc1](https://github.com/nextcloud/talk-android/releases/tag/v19.0.0rc1). 
I will have a closer look.
