### ISSUE TITLE
Allow DnD exceptions (priority contacts)

### ISSUE THREAD

**Issue by mario** [nextcloud/talk-android#402]

**Comment by mario** [comment]
Should this be separate to favorite? (cc @jancborchardt @nickvergessen)

**Comment by nickvergessen** [comment]
Favorites is pinning to the top of the list. It should not influence dnd

**Comment by mario** [comment]
@jancborchardt afaik, this has been removed in Android 9. But even if it weren't, our "users" are not regular contacts with phone numbers and we cannot add them as system-wide favorites, so it is indeed inside the app.

I see the two of you (@nickvergessen and @jancborchardt) have different opinions - happy to talk it through on Monday in our regular Talk meeting at 10:00.

**Comment by jancborchardt** [comment]
Ok, sounds good @nickvergessen. It also seems similar to the 3-dot menu in server where you can pick between the mention/notification level. Breaking DnD would be one level on top of that.
