### ISSUE TITLE
Allow search for contacts even if no contacts are in list

### ISSUE THREAD

**Issue by alx-tuilmenau** [nextcloud/talk-android#404]
It would be great to not hide the search icon within the contacts tab if no users are displayed. For privacy reasons I don't want to allow everyone to list all users (~5k), but search (with a limited number of results) is possible. This works on the talk web app, but the android app hides the search icon if the user list is empty.

**Comment by mario** [comment]
Thanks for the report. I'll take a look and see if this is possible.

**Comment by mario** [comment]
This will be released in a few minutes, thanks for your patience @alx-tuilmenau.
