### ISSUE TITLE
Notifications not showing up in Redmi Note 9 (M2003J15SG)

### ISSUE THREAD

**Issue by YoannPa** [nextcloud/talk-android#4044]
### Steps to reproduce

No notification are displayed on the smartphone main screen after installing and configuring the app.
In Nextcloud Talk parameters **no red message is displayed**.
Notifications for **all message are enabled** in conversations.
Nextcloud Talk app wasn't installed using F-droid but **using Google Play**.

### Expected behaviour

Notification should show up on the main screen when a new message is received.

### Actual behaviour

No notification displayed at all, when a new message is received.

### Device brand and model

Redmi Note 9 (M2003J15SG)

### Android version

10 QP1A.190711.020

### Nextcloud Talk app version

19.0.1

### Nextcloud server version

27.1.8

### Talk version

17.1.8

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment]
Hello, sorry for the late answer.

Did you check if notifications work fine on server? 
https://github.com/nextcloud/talk-android/blob/master/docs/notifications.md#-check-server-settings

And did you make sure no other tabs are opened with this user on any webrowser?

Does it still happen with app version 20.0.1?

**Comment by YoannPa** [comment]
Apparently the bug is not related to the app, but related to the phone itself: when someone has too many push notification, Talk notifications are not showing up. That's what the user reported at least.

**Comment by mahibi** [comment]
So other apps are also affected?
maybe https://dontkillmyapp.com/ also has some infos on this.

**Comment by YoannPa** [comment]
From what the user explained it sounded more like a user problem than an app problem. I think the user is just receiving too many push notifications at once for too many different apps, and the notification system just crash at some point bcause it cannot handle that relentless stream of notifications adding up too fast.

As far as I am concerned I think you can close this issue. I am sure that if someone else is having trouble with his Redmi Note 9, this someone will just reopen it.
