### ISSUE TITLE
improve incoming call screen

### ISSUE THREAD

**Issue by schiessle** [nextcloud/talk-android#406]
yesterday I received a call on my mobile phone, the incoming call screen looks like this:

![image](https://user-images.githubusercontent.com/1589737/50890734-0dc14600-13fb-11e9-8618-b1be639a54bc.png)

I was really confused how to pick up the call. Just looking at the buttons, it looks like the call is already running and I could use the two blue buttons to mute audio/video while what they actually do is to pick up the call in audio-only or audio/video mode.

I think making the buttons green would make it more obvious, and maybe change the microphone icon to a phone icon. A quick search lead to this two examples which I think look nice and would it way more obvious what to do:

![image](https://user-images.githubusercontent.com/1589737/50891570-dc497a00-13fc-11e9-8276-ddf6a9471611.png)

![image](https://user-images.githubusercontent.com/1589737/50891585-e3708800-13fc-11e9-9dbb-50148b681a4d.png)

**Comment by mario** [comment]
@jancborchardt thoughts? I'd be more than happy to do this. Just give me the exact hex of the green color we should use.

**Comment by mario** [comment]
Actually, we already use #006400 so might try that :)

**Comment by jancborchardt** [comment]
Sounds good @mario! :)

@schiessle also thanks for the issue! Next time when researching please use more current screenshots of comparable apps though please. ;) We don’t want to make mistakes others did in the past.
