### ISSUE TITLE
Here’s how you might ask about enabling reactions separately

### ISSUE THREAD

**Issue by serhiipetrenko2024** [nextcloud/talk-android#4065]
Hi,

Is it possible to enable reactions to messages separately? For example, if a user in a chat has read-only access, it would be convenient if they could still add reactions.

**Comment by SystemKeeper** [comment]
This needs to be handled in the server part of talk: https://github.com/nextcloud/spreed/issues/11329

**Comment by mahibi** [comment]
i will close as there is the server issue where it belongs to
