### ISSUE TITLE
Translation string concatenation creates wrong string

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#413]
The translations from:
https://github.com/nextcloud/talk-android/blob/7bb0c79b8922e104dd07064c04408d800790aa0f/app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java#L196-L212

are used as they are and appended to the name of the participant.
In a one to one conversation it's either you or someone else.

`<You> <sent an image.>` and `<Mario> <sent an image.>` are both correct.

However this does not work in german:
`<Sie> <haben ein Bild gesendet.>` vs. `Mario <hat ein Bild gesendet.>`

even worse, the current String `Sie hat ein Bild gesendet.` is like `She sent an image.` opposed to `You sent an image.` which is actually what it should say.

So bad news, you need to use 2 different strings. I would also vote to make the name part of the placeholder and then let them translate 2 strings:
1. `You sent an image.`
2. `%s sent an image.`

**Comment by mario** [comment]
That is fine, but how do you solve the fact that it needs to be: "You: whateverMessage" ?

**Comment by mario** [comment]
Found a way :)
