### ISSUE TITLE
Use account from Nextcloud app

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#42]
To have a great UX it would be nice to have the accounts of NC app automatically shown on startup if available:
- use current state and fetch all accounts by name. Drawback: password needs to be entered again
- use https://github.com/nextcloud/ownCloud-Account-Importer/issues/3 so it can work directly

(not now, but maybe for version 1?)

**Comment by mario** [comment]
Already reported/suggested here, so closing as duplicate of #14.
