### ISSUE TITLE
cant call with app

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#421]
NcTalk Beta5, android 8.1
Nc15.0.2
After voice call start, only connecting is shown.
Then its not possible to pick down the call (end call) with buttons. App freezes probably and only possible way is force closing via task manager

**Comment by jookk** [comment]
I dont know if this is related, but may be, because I wanted to call in that time from nc andrid talk app... 
from nextcloud log
![error](https://user-images.githubusercontent.com/11217085/51414618-5d2e1180-1b73-11e9-98c8-328e008da364.jpg)

**Comment by mario** [comment]
@nickvergessen knows issues with push proxy today?

Thanks @jookk .

**Comment by jookk** [comment]
![screenshot_20190119-111427_1](https://user-images.githubusercontent.com/11217085/51425396-f133c380-1bdb-11e9-9ec4-fe58f243ac1f.png)

**Comment by nickvergessen** [comment]
Push proxy still works, so not sure

**Comment by jookk** [comment]
Yes, Ill try and give feedback

Dňa 21. januára 2019 10:29:17 používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by jookk** [comment]
Now it worked
Call success

Dňa 21. januára 2019 10:29:17 používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by mario** [comment]
Sorry about the issue - this is probably https://github.com/nextcloud/talk-android/issues/386. Will try to fix soon.

**Comment by mario** [comment]
Closing this for the time being, but there's another issue where I'm tracking this.
