### ISSUE TITLE
[alpha] Create a new conversation button is not actionable. 

### ISSUE THREAD

**Issue by wjbeckett** [nextcloud/talk-android#4215]
### Steps to reproduce

1. Install the alpha version
2. Tap the FAB to start a new chat
3. Attempt to tap on "Create a new conversation"

### Expected behaviour

Should be able to start a new conversation .

### Actual behaviour

The button is not able to be pressed. The button is visible, but tapping the button does nothing and there is no visual feedback that a button has been pressed. 

### Device brand and model

Google Pixel 7 Pro

### Android version

15

### Nextcloud Talk app version

20.1.0 alpha 02

### Nextcloud server version

30.0.0

### Talk version

20.0.0

### Custom Signaling server configured

Yes (specify version in Additional Information)

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

**Comment by mahibi** [comment]
problem is that the alpha build fails, that's why alpha is currently older than the released v20.0.0. (in 20.0.0 this bug is fixed).
We are having a look to fix the build process...

**Comment by mahibi** [comment]
Alpha build system was just fixed (reason was that the bot had not enough permissions for the repository) and a fresh alpha 03 is available.
