### ISSUE TITLE
Android Client V 20.0.0 Chats are not shown

### ISSUE THREAD

**Issue by WolfDieterKattnig** [nextcloud/talk-android#4222]
### Steps to reproduce

1. Open Client
2. Message: Join a chat or start a new one (translated from german)

### Expected behaviour

List of public and private chats and useres

### Actual behaviour

Blank Screen with NC Logo and aforementioned message

### Device brand and model

Samsung Galaxy A53

### Android version

14

### Nextcloud Talk app version

15.0.8

### Nextcloud server version

25.0.9

### Talk version

20.0.0.

### Custom Signaling server configured

No

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

**Comment by mahibi** [comment]
hopefully fixed with https://github.com/nextcloud/talk-android/pull/4223

**Comment by alexhjelmnf** [comment]
Same here. New android version is broken
iPhone version works fine in 20.0.0 but not Android.

Its not possible to make new conversations but you can get notifications and you can answer them on the small popup.

**Comment by migulen** [comment]
I had the same problem. I closed it yesterday because I upgraded the servers. 

https://github.com/nextcloud/talk-android/issues/4198

I thought that it was "EoS".

**Comment by WolfDieterKattnig** [comment]
Which NC Version do you use? Mit freundlichen Grüßen, Wolf-Dieter KATTNIG____________________________________________Baiernstraße 10/4, 8020 GrazT +43 (699) ***@***.*** www.kattnig.com Die Information in dieser E-Mail-Nachricht ist vertraulich und/oder rechtlich geschützt. Wenn Sie nicht der Empfänger dieser Nachricht, einer seiner Mitarbeiter oder sein Empfangsbevollmächtigter sind,werden Sie hiermit in Kenntnis gesetzt, dass Sie deren Inhalt nicht verwenden, weitergeben oder reproduzieren dürfen.The information contained in this e-mail message is confidential and/or privileged information. If you are not the intended recipient, one of his employees or an agent entitled to hand it over to the intendedrecipient, please be informed that you may not use, disclose or reproduce the contents thereof.Am 17.09.2024 um 09:20 schrieb migulen ***@***.***>:﻿
I had the same problem. I closed it yesterday because I upgraded the servers.
#4198
I thought that it was "EoS".

**Comment by mahibi** [comment]
@WolfDieterKattnig @alexhjelmnf can you temporarily please install the version from here and let me know if this fixes your issue:

https://github.com/nextcloud/talk-android/pull/4223#issuecomment-2353406405

**Comment by alexhjelmnf** [comment]
> @WolfDieterKattnig @alexhjelmnf can you temporarily please install the version from here and let me know if this fixes your issue:
> 
> [#4223 (comment)](https://github.com/nextcloud/talk-android/pull/4223#issuecomment-2353406405)

yes, it works fine with your apk.

**Comment by migulen** [comment]
@WolfDieterKattnig  " Which NC Version do you use?" 

It's indicated on the comments of my issue.  Actually I updated my servers to Nextcloud Server v28.0.10/Talk v18.0.11. 

The problem for me was with Nextcloud Server v25.0.10/Talk v15.0.8, but after updating all the problems about this dissapeared. 

I was not sure if it was a bug or and End of Support. 

 Well, I'm happy it's working correctly now with the @mahibi fix.

**Comment by alexhjelmnf** [comment]
> @WolfDieterKattnig @alexhjelmnf can you temporarily please install the version from here and let me know if this fixes your issue:
> 
> [#4223 (comment)](https://github.com/nextcloud/talk-android/pull/4223#issuecomment-2353406405)

When do you think we can see this fix live?

**Comment by mahibi** [comment]
Version 20.0.1 with the fix is available in playstore. 
Please everyone let me know if it's fixed.

**Comment by WolfDieterKattnig** [comment]
Yeah, it works for me too. Thank‘s a bunch! Mit freundlichen Grüßen, Wolf-Dieter KATTNIG____________________________________________Baiernstraße 10/4, 8020 GrazT +43 (699) ***@***.*** www.kattnig.com Die Information in dieser E-Mail-Nachricht ist vertraulich und/oder rechtlich geschützt. Wenn Sie nicht der Empfänger dieser Nachricht, einer seiner Mitarbeiter oder sein Empfangsbevollmächtigter sind,werden Sie hiermit in Kenntnis gesetzt, dass Sie deren Inhalt nicht verwenden, weitergeben oder reproduzieren dürfen.The information contained in this e-mail message is confidential and/or privileged information. If you are not the intended recipient, one of his employees or an agent entitled to hand it over to the intendedrecipient, please be informed that you may not use, disclose or reproduce the contents thereof.Am 17.09.2024 um 15:34 schrieb alexhjelmnf ***@***.***>:﻿

Version 20.0.1 with the fix is available in playstore. Please everyone let me know if it's fixed.

it works, thanks!
