### ISSUE TITLE
Improve password actions in new conversation screen

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#4235]
When creating a new conversation with password, the password handling should be improved.

In the password dialog it should be possible to see if a password was already set and to change & remove the password.
IIRC the iOS app displays these options. Maybe @SystemKeeper could provide a screenshot.

**Comment by SystemKeeper** [comment]
Guests not allowed:
<img src=https://github.com/user-attachments/assets/312027c0-b6b1-42a9-b146-4e0337569f72 width=350 />

Guests allowed but no password:
<img src=https://github.com/user-attachments/assets/50980d44-b88b-4f1d-a7b7-1fdbf77f338c width=350 />

Guests allowed but password set:
<img src=https://github.com/user-attachments/assets/f00c83c0-5b03-4a96-97bd-66a6b41a28b6 width=350 />
