### ISSUE TITLE
Group Chat shows Text Input Box but I have no permissions to write.

### ISSUE THREAD

**Issue by Dtrieb** [nextcloud/talk-android#4238]
### Steps to reproduce

If I open a group without the right to write, I see in version 2.0.1 the Text Input Box and not the message that I don't allow to write in this group.

![Screenshot_20240918-122754](https://github.com/user-attachments/assets/c947844d-fc9b-4ad3-9812-28740e750776)

### Expected behaviour

Message that I don't allow to write in this group.

### Actual behaviour

I see in version 2.0.1 the Text Input Box.

![Screenshot_20240918-122754](https://github.com/user-attachments/assets/c947844d-fc9b-4ad3-9812-28740e750776)

### Device brand and model

Google Pixel 7 pro

### Android version

14

### Nextcloud Talk app version

20.0.1

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment]
Thanks for reporting! can reproduce it...
