### ISSUE TITLE
Tapping a shared image from a conversation wants to open it in browser

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/talk-android#425]
Tapping a shared image from a conversation wants to open it in browser. This is not really helpful since not many will be logged into a mobile browser to actually see the image. 

Tapping on a shared image should open the image in the nextcloud files app. Is this doable?

**Comment by mario** [comment]
Sure - and planned. But not at the moment :)

**Comment by mario** [comment]
Re-opening so it serves as a reminder, even if it's already planned.

**Comment by jookk** [comment]
I have idea...
Or it should open in nc talk app on fullscreen.

**Comment by DudleyDursley** [comment]
On my tablet it will open the Nextcloud app and highlight the picture in the pictures folder but not open it. The browser is only used if the Nextcloud app isn't installed. I guess this happend with one of the recent updates.

Opening it directly in Talk would be better though.

**Comment by mario** [comment]
Ah, this was indeed implemented. Opening it in Talk will be done later on. :)

Thanks for reminding me @DudleyDursley !

**Comment by gradinaruvasile** [comment]
This happens with version 6.1.2 again. Anyway in previous versions was pretty much useless since Talk crashed when i tapped a shared file...
