### ISSUE TITLE
Position in the conversation list is not expected after it is refreshed.

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#429]
### Scenario 1

1. Go to the conversation list
2. Pull down to reload the list
3. **Expected:** You are at the top of the new list
  **Actually:** You are somewhere in the middle of the list

### Scenario 1

1. Go to the conversation list
2. Go to a conversation somewhere down in the list
3. Write a message and go back out again
3. **Expected:** You are at the top of the list where your room is now (best), or you are at the spot where the conversation was (ok, but not as good)
  **Actually:** You are somewhere in the middle of the list

**Comment by tobiasKaminsky** [comment]
This is happening for me with 6.1.1 (and at least 6.0.x).

**Comment by mario** [comment]
Yup, something got screwed up probably due to some rebase. I'll look into it.

**Comment by mario** [comment]
Should be fixed.
