### ISSUE TITLE
RFE: flip (horizontally) the self image video 

### ISSUE THREAD

**Issue by gdamjan** [nextcloud/talk-android#432]
People are more used to see themselves in a mirror image, than in "real" orientation. 

But currently this app shows your self video in the same orientation that the other side sees you. My suggestion is to flip the self video horizontally, ie. if you wave your left hand, the video of your-self should wave on the left side (as yourself sees it).

Platform: lineage os 15.1 (android 8.1), oneplus 3, nextcloud-talk 3.2.1[installed from fdroid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (but happened in prior versions too).

**Comment by gdamjan** [comment]
now it's reversed on the back camera too

**Comment by mario** [comment]
Yup, will be handled.

**Comment by gdamjan** [comment]
seems fine as of 3.2.7 (f-droid)

**Comment by mario** [comment]
Cool
