### ISSUE TITLE
Make Lock screen more robust

### ISSUE THREAD

**Issue by parneet-guraya** [nextcloud/talk-android#4324]
Right now `Lock` screen is little flaky refer to this [comment](https://github.com/nextcloud/talk-android/pull/4204#issuecomment-2355237070) and also see this #3815. I think we need to make it more robust considering this is sensitive feature.

**Comment by mahibi** [comment]
Thanks for sticking with it @parneet-guraya 
I will close the issue in favor of my comment in https://github.com/nextcloud/talk-android/issues/3815#issuecomment-2401640132
