### ISSUE TITLE
Call rings indefinitely

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/talk-android#4331]
### Steps to reproduce

Received a call today in a Talk room, however I was away from my phone for 45 minutes. 
Upon returning to my phone, it was vibrating (i.e. ringing) with notification "Call started in X room" with time stamp "45 mins ago"
My phone was ringing continuously  for 45 minutes?!

1. phone locked, screen off
2. receive call started notification from a Talk room
3. phone vibrates indefinitely

### Expected behaviour

expecting the phone/call to ring for a minute or so, then silenced.

### Actual behaviour

phone vibrates indefinitely

### Device brand and model

Pixel 7

### Android version

14 (GrapheneOS)

### Nextcloud Talk app version

20.0.2

### Nextcloud server version

30.0.1 RC1

### Talk version

20.0.1

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment]
Are you able to reproduce this?

sounds like something went wrong in  `checkIfCallIsActive`
https://github.com/nextcloud/talk-android/blob/2408d639e42511876a130be99ae9c973c41be931/app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt#L886

**Comment by gerbrent** [comment]
haven't seen this reproduced, but will report if it is.

**Comment by gerbrent** [comment]
this has not occurred in quite some time, so happy to close 👍🏻
