### ISSUE TITLE
[nearly Bug] Autodelete Notifications Status Bar

### ISSUE THREAD

**Issue by sleeplessnight2** [nextcloud/talk-android#434]
Hello,

If you open a unread message (directly in the app or from the status bar), it will not automatically disappear from the status bar. You have to delete this extra.
Is a little annoying...

It would be nice if this would also check other people to exclude my Samsung as a source of error.

**Comment by mario** [comment]
It should. I will check - thanks for the bug! :)

**Comment by Valdnet** [comment]
It is also a bit of a nuisance to me. Especially with more messages.

We are waiting for a quick update :wink:

**Comment by mario** [comment]
Seems to work as expected atm.
