### ISSUE TITLE
[Feature Request] Sharing Files directly

### ISSUE THREAD

**Issue by sleeplessnight2** [nextcloud/talk-android#435]
It would be nice if you can take or select a photo directly and sent this immediately.

I hate comparisons, but as it is done in the well-known Messengers: choose or take a picture without first having to manually upload it.

At the moment it's only possible to send a text-message...

**Comment by mario** [comment]
Planned :) I just don't know when.

**Comment by sleeplessnight2** [comment]
8 Months later and carefully asked: how far is the progress?

**Comment by iTom1192** [comment]
I agree that this would be nice feature to have as I really wanna use Talk to repalce a "Family" Facebook Messenger Chat group. For some reason no one used a group SMS group (understandably), but they all use FB Messenger. This is the one missing feature I think that'll get your average Joe (like my family members) on-board, and to not think I'm some crazy nut Facebook is evil nut (even though FB is). Thank you for the amazing app!

**Comment by sleeplessnight2** [comment]
Mario, what's happening? Why is nothing happened?
I think, more than me would help you, but nothing is a little bit disappointing.
The actually share option is crap - sorry, but that's the truth. I tried one times, and my friend can only view after a login on nextcloud through the Firefox (on click at the picture it opens only a Browser instead of the nextcloud app)... 5 minutes to view a picture... Sorry, this is only useless and annoying.

**Comment by nickvergessen** [comment]
The main issue this this needs some pre work on the Talk server app first.
The rough plan is made, but the actual work is still to be done/in progress:
https://github.com/nextcloud/spreed/issues/1811#issuecomment-505096933

**Comment by pmarini** [comment]
Hi, any update on this feature development? 
Thank you for your hard work!

**Comment by huggymann** [comment]
i agree, that this feature is being asked by many users. 
Is there any plan to implement it soon?

**Comment by nickvergessen** [comment]
Should happen this year.

We are currently implementing file upload on the server side, which is a pre-requirement for this.

**Comment by mikelupe** [comment]
@mario I'm in about this feature. I was finally able to persuade a group of 25y+ family members (mainly females) to use the Talk handy app :) First thing was to moan about not being able to send pictures from the local gallery :-| 

Two things still missing to be the ultimate FB, WA etc killer: Send local files/pics & push-notifications w/o GA. Unfortunatley I'm not a developer, but I could help with testing :)

**Comment by jakobroehrl** [comment]
Push Notifications are working but you have to disable the battery optimization: https://github.com/nextcloud/talk-android/issues/741

battery -> battery optimization -> nextcloud talk -> dont optimize

On Samsung:
Android 6/7/8/
Settings -> Device maintenance -> Battery -> Battery Usage -> More -> Optimize battery usage -> All Apps -> Nextcloud Talk
(http://nine-faq.9folders.com/articles/8698-how-to-turn-off-battery-optimization-on-the-samsung-galaxy-android-6-7-and-8-devices)

Android 9
 1. Apps/Settings/Device care -> 3 Punkte -> Auto optimization -> Off
2. Select “Battery Charging” in “Device Care”. -> 3 Punkte -> settings -> Turn off “Adaptive battery”, “Put unused apps to sleep” and “Auto disable unused apps"

**Comment by mario** [comment]
@jakobroehrl he wants push notifications without Google which won't work though :)

**Comment by mikelupe** [comment]
@mario Dito :)

**Comment by MarcS1975** [comment]
> The main issue this this needs some pre work on the Talk server app first.
> The rough plan is made, but the actual work is still to be done/in progress:
> [nextcloud/spreed#1811 (comment)](https://github.com/nextcloud/spreed/issues/1811#issuecomment-505096933)

Any updates please? NC is awesome and I'd like to replace my current chat app but without the direct upload feature, chat is useless.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/talk-android/issues/435#issuecomment-594470408

**Comment by BlackRose01** [comment]
Hello there,

are there any updates to this issue? Currently I want to use the Talk system as an easy-to-use virtual classroom but the current way to upload a file to the chat is much too complicated.

So could it be possible that this would be implemented? My idea for this problem is that a user choose a file for upload/take a camera shot and choose a folder in nextcloude where the file will be uploaded. After the successfull upload the app share the file for the chat.

Sincerely,
BlackRose01

**Comment by sleeplessnight2** [comment]
> Currently I want to use the Talk system as an easy-to-use virtual classroom but the current way to upload a file to the chat is much too complicated.
> Sincerely,
> BlackRose01
For currently you should uninstall the nextcloud talk app and use any other chat program like telegram or something else. 

If you can wait around end 2022, then it's possible that nextcloud talk would working fine with photosharing. with each other Android update the app have new issues that would be fixed and there is no time for improvements.

**Comment by pmarini** [comment]
Hi,
is the estimate of @sleeplessnight2 accurate? Can this be confirmed by the project maintainers? Thanks!

**Comment by Melon-Bread** [comment]
Pretty sure it was a cruel joke

**Comment by MarcS1975** [comment]
Hopefully. Otherwise nextcloud talk would make nextcloud an irrelevant
application. Noone needs a file sharing platform if there is no sensible
chat/video solution. Without picture upload nobody will use chat.

**Comment by sleeplessnight2** [comment]
I'm just the (frustrated) dude, that opened this Request over a Year ago.

Look the history and there is nothing happend over 1,5 Years. The pre-requirement tasks - nobody knows, if it's done or not.

BTW: I don't use the Talk App anymore. It's a useless app - the only "Plus" called Video Call - works one time well and next time it's failed complete. You can hung ab the call and it's ringing endless by the callee... Bugs, Bugs, Bugs :)

**Comment by szaimen** [comment]
> The pre-requirement tasks - nobody knows, if it's done or not.

This is already done on the server side with Talk 9 which will come with NC19.

**Comment by nickvergessen** [comment]
> Pretty sure it was a cruel joke

Yes

> Look the history and there is nothing happend over 1,5 Years. The pre-requirement tasks - nobody knows, if it's done or not.

Yes it has happened, see this blog post from 2 weeks ago:
https://nextcloud.com/blog/open-sourcing-talk-back-end-rc-of-talk-9-brings-lots-of-improvements/

It's actually the next step on our todo for the mobile clients.

I can ensure you, we know exactly how you feel about it. We use Talk on a day-to-day basis at Nextcloud GmbH for internal communication and therefor also feel the pain of being unable to share stuff directly to Talk.
But it's a matter of priorization as we just can't do everything at once due to the limited amount of working power.
We focus first what our paying customers need, until now this was mainly focused on the call experience, but with Talk 8 and 9 we reached a certain point there, it's just because of the offline support of the mobile clients, that sharing/uploading files got pushed back in the mobile clients one more release.

**Comment by feutl** [comment]
Any update on this, the server is capable of doing this via the web interface. What about implementing it now into the client?

**Comment by nickvergessen** [comment]
It's still on the todo and will come at some point.

**Comment by MarcS1975** [comment]
I agree. Its a pretty key feature since all other chat apps have this.

**Comment by mnlipp** [comment]
I know it was mentioned before, but nevertheless: it's more than a todo, it's a blocker. I'd like to move my family and friends to NextCloud, but without this feature, I cannot even suggest this seriously. (Leaving me with the necessity to have an app on my phone that I'd like to get rid off as soon as possible.)

I'm not sure how many users will consider this particular move, but the termination of Hangouts at the end of this year looks a bit like a "windows of opportunity" to position NextCloud talk as an alternative. Even if it might only be an opportunity to get some attention for the NextCloud alternative.

**Comment by Keboose** [comment]
I am in the same boat. I used the Talk app for a little while with one
friend (who is going just as hard on self hosted/FOSS as many of us,) and
we eventually switched back to another chat app, for precisely this reason.
We send a lot of project pictures and documentation back and forth, so the
double hassle of having to upload files on one end (rather than drag & drop
into chat) and manually manage the files on the other (getting shared filed
dumped unsorted into a single folder) was a big problem.

**Comment by theoneandonly-vector** [comment]
I think it's more important than all the other issues listed..  but maybe it depends on them beeing solved first? also there will be someone working on this dedicated from december

**Comment by morvael** [comment]
This the most important issue for many people, myself included. It's Talk's to be or not to be.

**Comment by nickvergessen** [comment]
I'm locking the issue now. We know about the importance of the issue. Every comment adds no new information and just distracts all developers involved with another useless notification. If someone wants to start working on the issue feel free to create a PR or comment somewhere else.

Feel free to upvote the first post if you feel like it and subscribe for updates, further comments are not needed.

**Comment by szaimen** [comment]
🎉

**Comment by mahibi** [comment]
A first basic version of file sharing can be tested via the google play alpha channel. 
So Alpha testers are welcome: https://github.com/nextcloud/talk-android#testing

Improvements that need to be done for this can be found in #987
