### ISSUE TITLE
Support Single-Sign On

### ISSUE THREAD

**Issue by mw80** [nextcloud/talk-android#440]
Support Nextcloud Single Sign On, like the nextcloud android app for news.
https://github.com/nextcloud/Android-SingleSignOn

**Comment by tobiasKaminsky** [comment]
We enhanced the library so that multi-account is working fine.
Maybe you want to give it a try?

**Comment by mw80** [comment]
There is a import of nextcloud app. But I need to login again?!

**Comment by mario** [comment]
@mw80 yes because you need a new app token.

**Comment by mw80** [comment]
I expected the same behavior like nextcloud news app. Without app token.

**Comment by mario** [comment]
News app doesn't rely on push notifications which needs a new app token per application/account.

**Comment by mw80** [comment]
Ok, got it :) Thank you!

**Comment by szaimen** [comment]
@mario I just installed the app and wanted to use it without having to login again. 
Is there no way around? 
Maybe if changing the nextcloud push-api?
