### ISSUE TITLE
Talk is utter trash again

### ISSUE THREAD

**Issue by Byter3** [nextcloud/talk-android#4403]
### Steps to reproduce

The bluetooth not usable. I can select my earbuds as the mic and speaker, but there's no audio in it and eventually it disconnects. IT1s a lovely time using talk in public on speaker...
The UI glitches out all the time, when I sse my messages 6 times in a row and sometimes even the contact page got overlayed on top of my messages.
Honestly I would pay for these apps, not to have such a bad user experience.

### Expected behaviour

Not to be a barely usable garbage.

### Actual behaviour

It's a garbage.

### Device brand and model

Samsung Galaxy S21 Ultra

### Android version

14

### Nextcloud Talk app version

20.0.2

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by SystemKeeper** [comment]
While we appreciate the honesty and are glad for any helpful bug report, this is not the way to communicate the issues your having. Feel free to open issues with reproducible steps, but please refrain from posting in the way you did here.
