### ISSUE TITLE
Better indicator whether a call is happening or not

### ISSUE THREAD

**Issue by schiessle** [nextcloud/talk-android#4404]
If I enter a room it is really hard to impossible to say whether a call is currently running or not. I think the start audio/video call buttons should indicate somehow if I join a running call if I click them or if I start a new call.

There is a message in the chat area but it has two issues:

1. If you are not that familiar with Talk you don't know if it disappears after the call ended or not. So you don't know if the call still runs or not
2. if people chat a lot, the notification in the chat areas is no longer visible

**Comment by rapterjet2004** [comment]
Fair point, will implement a collapsable pin instead
