### ISSUE TITLE
Android apps behave different than web interface if chat list is filiteres to "unread" messages

### ISSUE THREAD

**Issue by schiessle** [nextcloud/talk-android#4405]
### Steps to reproduce

1. apply the filter to show only rooms with unread messages in the message list
2. use the search and type the name of a user where you don't have unread messages at the moment

### Expected behaviour

The web interface will find the user anyway and this is what I also would expect on Android

### Actual behaviour

On Android no results are shown because the user is not in the filtered list.

### Device brand and model

Samsung Galaxy S24

### Android version

16

### Nextcloud Talk app version

20.0.2

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment]
Without to have a look at the code, sounds like we have 2 options to solve it:

solution A: remove all filters whenever search field is being clicked. When returning from search, filters would have to be set again.

solution B (better & same as on web): When search field is being clicked, store the filters but do not apply them. When returning from search, apply them again.

Something for you, @rapterjet2004 ?
