### ISSUE TITLE
No smiley display

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#444]
In the sent messages as well as in the conversation history you can not see the smilies being sent.

Nextcloud Talk v3.2.3 - Google Play
Android 6 and Android 7 and Android 6.1

**Comment by mario** [comment]
This is due to wrong DB configuration - https://docs.nextcloud.com/server/15/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by Valdnet** [comment]
Thanks. Already done. Now it is great.
