### ISSUE TITLE
No sound of message arriving in the conference

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#445]
During conversations in the conference, there is no sound or vibration when a new message arrives.

Sounds and vibration in settings enabled.

During conversations with a single user, it works correctly.

Nextcloud Talk v3.2.3 - Google Play
Android 6 and Android 7 and Android 6.1

**Comment by mario** [comment]
This I can take a look at - thanks for the bug report.

**Comment by vix95** [comment]
Hi, good job. I found this bug also.

**Comment by mario** [comment]
Works as expected. If it's not working, you probably disabled the sound somewhere in the phone settings or lowered it :)
