### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#447]
There are no translations in the application:

```
<string name="nc_settings_vibrate_desc">Your phone will vibrate unless it\'s silenced</string>
<string name="nc_conversation_menu_conversation_info">Conversation info</string>
<string name="nc_notification_settings">Notification settings</string>
<string name="nc_notify_me_always">Always notify</string>
<string name="nc_mute_calls">Mute calls</string>
<string name="nc_mute_calls_description">You will not receive any notification for calls</string>
```
And I would check these:

```
<!-- Notification channels -->
    <string name="nc_notification_channel">%1$s on %2$s notification channel</string>
    <string name="nc_notification_channel_calls">Calls notification channel</string>
    <string name="nc_notification_channel_messages">Messages notification channel</string>
    <string name="nc_notification_channel_calls_description">Shows incoming calls</string>
    <string name="nc_notify_me_mention">Notify when mentioned</string>
    <string name="nc_notify_me_never">Never notify</string>
```

In transifex the words are translated quite a long time ago.

In addition, it is missing for translation in transifex:

```
You created the conversation
You added
You
```

**Comment by mario** [comment]
I'll take a look.

**Comment by Valdnet** [comment]
I'll take a look.
OK.

> You created the conversation
> You added
> You

I already know that.

**Comment by mario** [comment]
It seems the translation are in the repository? I'm not sure what you're referring to?

**Comment by Valdnet** [comment]
@mario I thought that these words for translation belong to Nextcloud Talk for android.

PS: I have already done a translation for spreed :wink:

**Comment by mario** [comment]
Cool.

**Comment by Valdnet** [comment]
@mario  in Nextcloud Talk v3.2.7 there is no new translation in the Polish version :wink: 
`<string name="nc_settings_vibrate_desc">Phone will vibrate unless it\'s silenced</string>`

**Comment by mario** [comment]
It will be there in 3.3.

**Comment by Valdnet** [comment]
OK. So we wait patiently :wink:

**Comment by mario** [comment]
Thank you for the translations!

**Comment by Valdnet** [comment]
> Thank you for the translations!

No problem 😉 
I corrected the translations and approved them. I think it's good.
There is only one translation of the function: `Instructs keyboard to disable personalized learning (without guarantees)`
Can you describe this function?

**Comment by mario** [comment]
@Valdnet it basically asks the keyboard not to remember/send to 3rd-party the things you type.

**Comment by Valdnet** [comment]
@mario Ok, I thought so :wink: 
It's hard to translate to the Polish word: **Instructs** keyboard.
Can you type more familiar word?

**Comment by mario** [comment]
@Valdnet well, feel free to use something else, like "Tells keyboards" or "Tries to disabled keyboard personalised learning (without guarantees). The translation doesn't have to be a word-by-word translation if it's hard :)

**Comment by Valdnet** [comment]
@mario Thank you for your response 😉 
> The translation doesn't have to be a word-by-word translation if it's hard :)

That's right.
Only that this word "Instructs" is very important :grin:
I do not want to write stupid 😉
