### ISSUE TITLE
[Question] Sending pictures

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#448]
How can you send pictures ?

I have not found this option anywhere.

**Comment by EricThi** [comment]
Hello, it's only possubke via talk web. (for this moment ???)

**Comment by mario** [comment]
We'll add support for this later on. First step will be attaching images/files you already have in your Nextcloud. So I'll close since there's another issue for this, but we're working on it! :)

**Comment by Valdnet** [comment]
Cool. For sure, this feature will be very useful for all users.
