### ISSUE TITLE
Allow dismissing the `Notifications are not setup correctly` warning

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/talk-android#4501]
**Is your feature request related to a problem? Please describe.**
Since the last update, this message is shown on top.
The notifications ARE setup correctly, I disabled them on purpose.

**Describe the solution you'd like**
Signal do show a tiny popup from time to time. But they respect the user decision and just suggest enabling them.

**Describe alternatives you've considered**
NA

**Additional context**
I would add that the phrasing is misleading and the orange background make it looks like something is wrong.
Disabling notifications is a feature of Android after all :)
![Image](https://github.com/user-attachments/assets/ba22ac69-c33d-4b8b-94cb-2bab51316dd9)

**Comment by mahibi** [comment]
I expected this complaint ;)

Please click on the warning and uncheck "Show notification warning".

So after users complaining that the warning was not prominent enough in the past or that notifications don't work, now i will have to deal with users complaining that the setting to hide the warning is not prominent enough 😆🤷🏽‍♂️
I'm open for suggestions on this!

**Comment by skjnldsv** [comment]
> I'm open for suggestions on this!

The signal way is more pleasant I think.
At least make it clear you can click/dismiss the warning.

Still, I'll like to add that an orange warning make it seem like something is wrong.
While in reality, a user would have to manually deny the app permissions to show notifications. :)

**Comment by skjnldsv** [comment]
![Image](https://github.com/user-attachments/assets/1060a27a-e88f-47be-9353-931d9ec3d5a4)

**Comment by mahibi** [comment]
i agree on the color and that there should be an option like "Not now".

This also means that the "Show notification warning" switch might be changed to "Regulary show notification warning". 
So when it's off there will never be a warning and when it's on there will be warnings from time to time.

**Comment by nigelharpur** [comment]
Not sure if this should be a new issue but here is my 10p worth of info - I'm using Talk on a de-googled phone with CalyxOS and MicroG running - I **do** get the Talk notifications just fine but also get the orange warning? Can dismiss (I see from this) but it would be good if the 'show warning' criteria allowed for people using MicroG rather than G services. The app is great by the way, thanks so much for the fab work.

**Comment by mahibi** [comment]
> Not sure if this should be a new issue but here is my 10p worth of info - I'm using Talk on a de-googled phone with CalyxOS and MicroG running - I **do** get the Talk notifications just fine but also get the orange warning? Can dismiss (I see from this) but it would be good if the 'show warning' criteria allowed for people using MicroG rather than G services. The app is great by the way, thanks so much for the fab work.

The notification warning is working when using gplay services (or microG, but no guarantee). The app does not provide other notification services, so when not using gplay the notification warning is not shown but a hint that notifications will just not work.
