### ISSUE TITLE
Group in contacts

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#452]
When moving contacts in the list, the `Group` name is static. Do not move when scrolling contacts.

Nextcloud Talk v3.2.3 - Google Play
Android 6

**Comment by mario** [comment]
Not sure I understand?

**Comment by Valdnet** [comment]
![obraz](https://user-images.githubusercontent.com/47037905/52480101-1009f200-2bab-11e9-87e8-e7891eb2c3cd.png)

The `Group` description does not scroll with contacts.

![obraz](https://user-images.githubusercontent.com/47037905/52480136-21eb9500-2bab-11e9-9d32-ec04c27bb17c.png)

Procedure:
1. View contacts.
2. Scroll down contacts.
3. `Group` **description remains in place**.

**Comment by mario** [comment]
This is expected. Scroll a bit further and it will disappear.

**Comment by Valdnet** [comment]
Okay. With three groups and three users it's hard to notice.

This is the second issue. If you follow these steps:
1. You start contacts (description disappears when scrolling).
2. Turn the screen into a transverse position.
3. Scroll through contacts.
4. The names of the titles behave differently. **They immediately follow the list of groups and users**.

Such a small detail.
