### ISSUE TITLE
Can't hear either side no video from other side

### ISSUE THREAD

**Issue by nickyg666** [nextcloud/talk-android#4526]
### Steps to reproduce

Reproduce: install talk 20.1 on server
Install talk 20.1 apk from play store on android 14
Install talk 20.1 apk from play store on android 13
Make audio or video call

### Expected behaviour

Show other side video, hear audio from other side and have normal call audio or video

### Actual behaviour

Call connects but neither side can hear each other even after ensuring microphone access on both sides. Cannot see other participants video. Does not work from web to android either

### Device brand and model

Samsung a15

### Android version

14

### Nextcloud Talk app version

20.1

### Nextcloud server version

30.0.2

### Talk version

20.1

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

### Meta information

**Generation of system report**

Dec 9, 2024 12:42:08 PM

### Phone

**Device**

samsung SM-S156V

**Android version**

34

**Google Play services**

Google Play services are available

### App

**App name**

Nextcloud Talk

**App version**

v20.1.0

**Build flavor**

gplay

**Battery settings**

Battery optimization is ignored, all fine

**Notification permissions**

Notifications are granted

**Calls notification channel enabled?**

Yes

**Messages notification channel enabled?**

Yes

**Firebase push token**

c7cr_...

**Latest firebase push token generation**

Dec 7, 2024 11:22:53 AM

**Latest firebase push token fetch**

Dec 9, 2024 1:26:37 AM

**Registered users**

1

### Current account

**Server**

https://cloud.a1e.lol

**User**

nick

**User status enabled?**

Yes

**Server notification app installed?**

Yes

**Latest push registration at server**

Dec 9, 2024 1:26:40 AM

**Latest push registration at push proxy**

Dec 9, 2024 1:26:41 AM

**Server version**

30.0.2

**Server Talk version**

20.1.0

**Signaling Mode**

External

### Server log

```bash

```

### Additional information

I can't find any info on how to solve anywhere. Do I need a special port opened for talk?

**Comment by mahibi** [comment]
Thanks for the report!
Hopefully this will also by solved by the fix coming for https://github.com/nextcloud/talk-android/issues/3358
Maybe @danxuliu can judge if the problems might be related?

**Comment by nickyg666** [comment]
Most of the time, if it will connect it either sends the android device to
the web page to answer the call or when making outgoing calls I get sorry
something went wrong

**Comment by nickyg666** [comment]
I did remedy this with logging in and out of the talk app for android, with forwarding the necessary port 3478.
you can close this.

**Comment by danxuliu** [comment]
Thanks for the information. Based on the port number it seems that the clients had to establish the WebRTC connections (to send audio and video) through the TURN server; as port 3478 was closed/blocked no media could be transmitted, and therefore no audio and video was heard/seen.

Note that whether the TURN server is needed or not depends on your setup/infrastructure. For more information please check [our documentation](https://nextcloud-talk.readthedocs.io/en/latest/TURN/).
