### ISSUE TITLE
Duplicate call termination message

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#453]
After the call is completed, the call ending message is duplicated.
![obraz](https://user-images.githubusercontent.com/47037905/52520320-8de00300-2c68-11e9-96f2-f973840fc317.png)

**Comment by mario** [comment]
Pretty sure this is server related at this point. cc @nickvergessen

**Comment by Valdnet** [comment]
There is only one message on the server in the messenger window. However, in the Nextcloud Talk application the message is double.

Are you sure that the error lies on the server side?

**Comment by mario** [comment]
OK, let me re-open.

**Comment by Valdnet** [comment]
Okay.  I tested it again and find out that the server is also duplicated information. I also report the @nickvergessen problem. You can close again. Sorry for the confusion.
![obraz](https://user-images.githubusercontent.com/47037905/52578981-929de600-2e25-11e9-917d-01a90b08e336.png)
