### ISSUE TITLE
Automatic hiding the keyboard

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#455]
Procedure:
1. Create a new connection with the user.
2. Write a message to the user.
![obraz](https://user-images.githubusercontent.com/47037905/52638716-da2e7b80-2ed2-11e9-81b6-90175da065f4.png)

3. Return to the list of users via the arrow in the Nexctcloud Talk application menu.
![obraz](https://user-images.githubusercontent.com/47037905/52635936-89675480-2ecb-11e9-9d06-7f0e31dbc505.png)

4. **The klawaitura is not automatically hidden**.

![obraz](https://user-images.githubusercontent.com/47037905/52636151-15797c00-2ecc-11e9-92f7-661d10eb2e3a.png)

The keyboard covers the list of users who are at the bottom of the list. To display them, press return from the android system menu.

Nexctcloud Talk v3.2.3 - Github
Android 6

**Comment by mario** [comment]
Fixed, will be in the next minor release.
