### ISSUE TITLE
[Suggestion] Change of sound selection descriptions

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#456]
I suggest changing the descriptions of sound selection. The current descriptions are confusing for the user of the application.

I suggest such descriptions:
![obraz](https://user-images.githubusercontent.com/47037905/52694017-b4ec4c80-2f68-11e9-838b-12550b74d163.png)

**Comment by mario** [comment]
I'm not sure what would you like to change these to?

**Comment by Valdnet** [comment]
So, I requested a merge for this one, number #458. Please check it and let mi know that everything is clear.

**Comment by mario** [comment]
Fixed by merging your PR :) Thanks!
