### ISSUE TITLE
Blocked emoticons after locking the smartphone

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#457]
Procedure:
1. Create a new connection with the user.
2. Write a message to the user.
3. Switch to emoticons.
![obraz](https://user-images.githubusercontent.com/47037905/52705304-e245f400-2f82-11e9-9b70-ce526812bb3f.png)

4. Wait for the smartphone to lock or block yourself.
5. Unlock your smartphone.
6. Try disabling the emoticons on the keyboard - **no reaction**.
7. Re-switching only changes the activity status of the icon.
![obraz](https://user-images.githubusercontent.com/47037905/52706008-a0b64880-2f84-11e9-8e14-698058832a63.png)

**A similar error:**
Procedure:
1. Create a new connection with the user.
2. Write a message to the user.
3. Switch to emoticons.
4. Scroll to a different selection of emotes.
![obraz](https://user-images.githubusercontent.com/47037905/52706315-67caa380-2f85-11e9-852a-a37bca50a7fa.png)

5. Wait for the smartphone to lock or block yourself.
6. Unlock your smartphone.
7. Try disabling the emoticons on the keyboard - **only emoticons are changed**.
![obraz](https://user-images.githubusercontent.com/47037905/52707023-03104880-2f87-11e9-85fe-3f9f41b392a1.png)

8. Next switching off emoticons.
![obraz](https://user-images.githubusercontent.com/47037905/52706789-81b8b600-2f86-11e9-9bda-a8c94bbcbd4a.png)

Nexctcloud Talk v3.2.3 - Github
Android 6

**Comment by mario** [comment]
Uh, I'm not sure I understand what's happening? :-/ But I'll check it out.

**Comment by vix95** [comment]
Hi @mario , I think that @Valdnet tried talk to you like this.
When you open emoticons window and block the phone and next unblock the phone during conversation then keyboard can't to show. The emoticons window is still open. In case if you are trying to close emoticons window you can't to close.

**Comment by mario** [comment]
@vix95 thanks for the clarification, that makes sense. I've done a lot of changes to the Emoji Keyboard handling, so I'll take at this as well.

**Comment by vix95** [comment]
@mario , great, you're welcome!
