### ISSUE TITLE
Send photos from gallery and the camera

### ISSUE THREAD

**Issue by vix95** [nextcloud/talk-android#459]
Hi, I know that is already open post like this but other post are including send files only from Nextcloud. The best feature for me will be send photos and short movies by gallery and the camera. It's very helpful and familiar feature if you'd like to fast send any photo for example. I'd like to fast share, I won't to first upload on the Nextcloud. Please think about this. For me it's the must have feature! Good job and thanks for your plugin which is fabulous 😄

**Comment by Valdnet** [comment]
I have already discussed this topic in thread #448. I also think that this is a necessary option that would increase the popularity of the application.

**Comment by mario** [comment]
Closing because we have https://github.com/nextcloud/talk-android/issues/435, but thanks for keeping us on our toes! :)
