### ISSUE TITLE
The icon looks VERY bad

### ISSUE THREAD

**Issue by mario** [nextcloud/talk-android#47]
Using S7, which is a relatively recent phone:

- forced round icon looks awful since it's surrounded by a semi-rounded square (due to the way Samsung shows icons), so I vote for going back to squared icon in most cases (e.g. letting the phone/OS/manufacturer decide what's best)
- the dots on the background are completely INVISIBLE, so I vote for removing them completely

cc @AndyScherzinger 

cc @jancborchardt  @tobiasKaminsky -  I know of your opinion and how "dull"/"boring" simple background is, but simplicity always wins, both on mobile and the desktop. Also, I am a mobile developer and I've done this more than once - I want the best experience, and the current state of icons that we ship is such that it's really really bad.

**Comment by jancborchardt** [comment]
I thought we came to an agreement now through the latest icon discussion in the main app repo?

- where manufacturers decide the shape, we let them
- the dots are very large and at 30% opacity now, so super visible

**Comment by jancborchardt** [comment]
Maybe best post a screenshot to illustrate.

**Comment by mario** [comment]
Have you seen the icon on a phone? I need to use a magnifying glass in order to see the dots. 

The screenshot is useless since it needs to be seen on a phone to see what's happening.

**Comment by mario** [comment]
As for "where manufacturers decide a shape" is not as simple as you imagine, and can't really be done properly before Android 8, so it looks very ugly. (e.g. Android 7.0 now has a round icon surrounded by semi-rounded grey square imposed by Samsung)

**Comment by mario** [comment]
I have now updated the icon to use square where needed, round icon on API 25, and for Android 8 adaptive which means the os/manufacturer/whatever decides. As for the dots, they're still there, but I wish I could show you how this looks :(

**Comment by tobiasKaminsky** [comment]
I could only test the nextcloud (files) app with a Samsung S5 with android 6.0.1 and there the icon is round and the dots are big enough to see and distinguish them without any problems, not blurry.
I liked the icon in its very first state, but now it looks even better, @AndyScherzinger 🎉

**Comment by mario** [comment]
*shrug*

Will leave it as-is and hope the next version of logo will have plain
background :p

**Comment by AndyScherzinger** [comment]
I am not an expert and so I can't say what is right or wrong, maybe a matter of taste when it comes to the dots but I agree with Mario. To me the dots are distinguishable now due to the raised contrast but to me it makes the background rather noisy where I would prefer a minimal gradient to give it a slight 3D effect as mentioned by the material guidelines.
It did the icon changes for the files app according to the requirements stated since the launcher icon is not worth a fight in my personal opinion.
