### ISSUE TITLE
Video call does not work with TURN server

### ISSUE THREAD

**Issue by jcastang** [nextcloud/talk-android#470]
Hello,

Here is the scenario:
(1) Calling from Android phone using app to a client (Chrome on PC) that is not on the same network show black screen on both (Chrome on PC and App on phone).
(2) Calling from Android phone using Chrome to a client (Chrome on PC)  that is not on the same network works.

So TURN setup seems to be correct.

When in scenario (1), TURN server seems unable to authenticate Android App Client:
293: session 000000000000000005: realm <XXXXXXXXXX> user <>: incoming packet message processed, error 401: Unauthorized

Whereas in scenario (2) TURN autentication seems OK:
309: session 001000000000000009: realm <XXXXXXXXX> user <1550324812:7WRwiin+hckZz2ba>: incoming packet CREATE_PERMISSION processed, success

Do you have any information/tip on this case ?

Thanks !

**Comment by mario** [comment]
Hi, this sounds VERY strange. What version of the app?

**Comment by jcastang** [comment]
Last version (3.2.6).
It seemed to be TURN server related.
I used talk.sh script from NextcloudVM setup and then it worked.
