### ISSUE TITLE
The keyboard is not hiding

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#471]
Step to step:
1. Create a conversation.
2. Turn on the keyboard.
3. Go to:  `:` ->`Conversation info`.

**The keyboard is not automatically hidden.**

![obraz](https://user-images.githubusercontent.com/47037905/52862142-c2563200-3134-11e9-912e-d98d2a93624a.png)

Nextcloud Talk v3.2.5
Android 6

**Comment by mario** [comment]
Tested this, definitely works as expected.
