### ISSUE TITLE
 v3.2.5 crashes when starting call.

### ISSUE THREAD

**Issue by resoli** [nextcloud/talk-android#472]
Just tried on two different devices: OP3T with lineage 15.1 and nexus 7 2012 tablet with lineage 14.

**Comment by Valdnet** [comment]
Step to step:
1. Create a conversation.
2. Make a call or video call.

**The application turns off.**

Nextcloud Talk v3.2.5
Android 6

**Comment by mario** [comment]
Thanks. Will be fixed shortly.

**Comment by mario** [comment]
Please confirm it's fine now?

**Comment by Valdnet** [comment]
@mario the 3.2.6 application works very well. Good job :wink:

**Comment by resoli** [comment]
Fixed.
