### ISSUE TITLE
Locked LDAP Accounts after Password Change

### ISSUE THREAD

**Issue by tobilra** [nextcloud/talk-android#475]
First Thanks for your greate App!
Our Nextcloud Login is configured with Active Directory logon. If I change the password for an account it seems that the Nextcloud Talk App does not get any information about this state and try to login with the old Password. After N tries the Account gets locked. Currently I have to logout in the App before I change the password in our Active Directory. It would be nice if you can integrate a login test.

**Comment by mario** [comment]
This will be fixed via a different ticket, so closing.
