### ISSUE TITLE
[Feature request] Separating sounds in the selection list

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#476]
It would be more legible to separate the system sounds from my sounds on the selection list.
![obraz](https://user-images.githubusercontent.com/47037905/53170202-d17b2b00-35df-11e9-93a3-ec8b1a3efa9f.png)
Option for: `One-to-one calls` and `Other`.

**Comment by mario** [comment]
Is that even possible? Which app has it this way?

**Comment by Valdnet** [comment]
> Is that even possible?

I do not know that 😉 

> Which app has it this way?

In system settings of sounds and notifications in android, e.g. 6.
But in fact I did not meet in other applications :grinning:

**Comment by Valdnet** [comment]
The selection of sounds has been changed. I close.
