### ISSUE TITLE
Emoji won't send

### ISSUE THREAD

**Issue by avuton** [nextcloud/talk-android#481]
Using the Nextcloud Talk 3.2.7 from F-Droid, with Nextcloud Talk App 5.0.2, Nextcloud Server 15.0.4. I cannot send emoji. I click any emoji, click send, and it goes away but never sends.

The only helpful thing I've found is in the logcat the following shows:
```LatinIME: Starting input. Cursor position = 3,3```

The '3,3' doubles for each one on the line. Sorry if that's not helpful, please let me know what I can do to be more helpful.

**Comment by avuton** [comment]
I'm going to close this, just tried on the web and I get an error there too. I'll reopen if I confirm this is a talk-android issue.

**Comment by mario** [comment]
Hi. This is an issue with your setup I'm afraid - please see:
https://docs.nextcloud.com/server/15/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by avuton** [comment]
Thank you, I'm kinda surprised this kind of thing isn't detected and reported in the server issues, but that's a different story. I'll fix this tomorrow.

**Comment by danuamirudin** [comment]
Hay for whim doen'y not have fixed this issue ihave some suggest that solved in my case.
1. change your my.cnf / 50-server.cnf to 
character-set-server  = utf8mb4
collation-server      = utf8mb4_general_ci

2. Use version Nextcloud-18.0.1
Althought this version is unsopprted again & I try with Nextcloud 22 the emoji won't work unlike This Version.
thats the link for Nextcloud-18.0.1, if you don't found in nextcloud official web / github
https://www77.zippyshare.com/v/Qk52mGW3/file.html
