### ISSUE TITLE
no notifications for chat messages

### ISSUE THREAD

**Issue by rhonda** [nextcloud/talk-android#482]
I'm currently trying out the nextcloud talk app, and I noticed that I don't receive any notification, which feels very weird. I installed it from frdoid, version 3.2.3, if that's of any relevance.  When I open up the app again I see that there are new messages, but there wasn't any notification in between.

**Comment by mario** [comment]
Hi. The F-Droid build does not support notifications unfortunately.

See https://github.com/nextcloud/talk-android/issues/257 for more details.
