### ISSUE TITLE
"bypass" account import

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#486]
Coming from https://github.com/nextcloud/notifications/issues/82

- click "add a new account"
- select any account
- wait for webflow login
- click back

Video: https://github.com/nextcloud/notifications/issues/82

On two devices: you are logged in, without typing password and then Push does not work anylonger
On another device: you are not logged in, everything remains working

Both misbehaving devices are Android 8+.
One of it is an emulator, so it should be easy to test.

**Comment by tobiasKaminsky** [comment]
This then leads to having two accounts with the same push token and thus the later one (Talk) is receiving all push notifications.

**Comment by mario** [comment]
Fun :D
