### ISSUE TITLE
[Feature request] A beep when ringing

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#488]
I am asking for a function so that the person calling the user will hear the call signal as in the telephone earpiece (tiiiiiiit, tiiiiiiit, tiiiiiiit ...) 😁 Something similar to Skype.

☎️
Currently, when calling from the Nextcloud Talk application for Android from the phone placed to your ear, you can not see if a call is being made and you can not hear when you are rejecting the call.

**Comment by mario** [comment]
Already requested in 
https://github.com/nextcloud/talk-android/issues/454.

**Comment by Valdnet** [comment]
Sorry. I forgot quite.
This is missing in the application.
