### ISSUE TITLE
Message privacy?

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/talk-android#497]
The notifications are sent through the nextcloud push server (push-notifications.nextcloud.com) and through the google FCM. 
What data is actually sent? In the logs the whole message is seen but i'm not sure it is transmitted to google.
If the whole message is sent, the mobile talk app should have an option of sending only metadata in the message (user id and room id), not the actual text.

**Comment by mario** [comment]
Room token mostly, and notification ID. But they are end-to-end encrypted so only your phone can actually decrypt this. 

:)
