### ISSUE TITLE
Highlight of your name when others mention you

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#499]
Currently when other people mention you, your name is displayed in some sort of bronze color:
![Talk Android mention is bronze](https://user-images.githubusercontent.com/925062/54127488-2ef9df00-440a-11e9-968a-00cb7144c334.png)

We don’t use that color anywhere else, and should instead use the primary color (Nextcloud blue by default). :)

As discussed @mario

**Comment by mario** [comment]
Can't do Nextcloud blue as the outgoing bubble default colour is Nextcloud blue - so this wouldn't work :) But I think I have an idea - once I implement, will show you.

**Comment by jancborchardt** [comment]
> Can't do Nextcloud blue as the outgoing bubble default colour is Nextcloud blue

But your own name is never in the outgoing bubble, cause that’s what you say. :) Actually it would be perfect because blue would always refer to "you".

> But I think I have an idea - once I implement, will show you.

Since it’s closed, what did it end up being?

**Comment by jancborchardt** [comment]
Saw https://github.com/nextcloud/talk-android/pull/519#issuecomment-483789586 and answered there :)
