### ISSUE TITLE
Add support for Xiaomi to Effortless permissions

### ISSUE THREAD

**Issue by mario** [nextcloud/talk-android#50]

**Comment by Scoub29** [comment]
Hello,
On huawei P8 (android 7), i need to set permissions (mic, camera, storage) and disable battery optimization manually.
Best regards,

**Comment by mario** [comment]
I'll investigate, thanks for letting me know.

**Comment by SlavikCA** [comment]
On my Nexus 6P (Android 8.1) I needed to manually add permissions, too

**Comment by mario** [comment]
@SlavikCA this is a bug that I'll fix. Xiaomi has a strange permission system, and I heard Huawei has something similar (but that I have to investigate).

For Nexus, it's "just" a bug :)

**Comment by mario** [comment]
@SlavikCA @Scoub29 1.0.10 is out which should fix your particular problems.
As for battery optimizations, I don't see the need to disable it?

**Comment by mario** [comment]
Probably not needed.
