### ISSUE TITLE
Not possible to open conversations in right-to-left languages

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#501]
In any right-to-left language (e.g. Hebrew, Arabic, etc) the app is impossible to use because you can not open a conversation. Instead, the scroll helper is triggered:
![Talk interface right to left](https://user-images.githubusercontent.com/925062/54127876-15a56280-440b-11e9-8a7e-65d9b97fef55.png)

(Another issue is the name of the conversation not right-aligning.)

**Comment by jancborchardt** [comment]
cc @schiessle this is atm the only breaking bug for RTL.

**Comment by nickvergessen** [comment]
Closing in favor of  #405
