### ISSUE TITLE
Confusing "reauthorize" and "client certificate" settings

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#502]
Currently the first settings you see are "Reauthorize" and "Set up client certificate", which are quite technical. (And is "Reauthorize" necessary?):
![Talk settings certificate etc](https://user-images.githubusercontent.com/925062/54128461-68334e80-440c-11e9-86b3-c2df0b1d84b3.png)

We could condense it to this using a "more" menu:
![Talk settings condensed](https://user-images.githubusercontent.com/925062/54128460-68334e80-440c-11e9-94d6-15b2fb809dad.png)

**Comment by mario** [comment]
Reauthorize will disappear eventually when the app is ready for that. I do agree the cert is a bit technical though, but three dots (especially in the place you put it at) also looks strange. 

Got another suggestion?

**Comment by jancborchardt** [comment]
Why do the 3 dots look strange? It’s a standard Android element, and it’s right of the account it relates to.

Maybe the "Add a new account" entry should be a button instead, centered below? Then it looks less strage.

(And we usually omit the protocol part (https://) from the server, which simplifies the view more.)

**Comment by Valdnet** [comment]
In my opinion the @jancborchardt proposal is good. At once, the application settings are more orderly.

**Comment by Valdnet** [comment]
@mario Isn't it worth thinking about it? This would shorten the settings menu a bit 😉.

**Comment by mario** [comment]
Will be in v9.0.

**Comment by CSchaefer70** [comment]
Hello! I'm looking for some guidance to install a certificate on the TalkApp Androidv11.1.1. Where do I place the CertFile?  How?  When I attempt to install [setup a client certificate] the folder is empty.  My NextCloud is installed on a VPS server Ubuntu24.0.1 and the talk app does work as expected within FireFox browser so my SSL is working on the thru the server.  When using the Android App I can only text but the rest does not connect when using the Android Talk app... I thinking I need security like CertCA?

I’m generally ignorant on SSL.  Within the Android Talk App I did try to put the "defaultSSL’ in the “Talk” folder on the server, thinking it might look there when using the settings from the phone to "Setup Cert"?

Is there anywhere that provides a stepxstep for dummies like me?

Thanking for any help!
