### ISSUE TITLE
Push notifications fail sometimes

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/talk-android#504]
It seems the nextcloud google push notification server is not reliable. I occasionally see un-delivered messages (to the Android clients) with the following errors in the logs:

`{"reqId":"joKt2WlHfWqQZFW118Ek","level":3,"time":"2019-03-12T03:25:55+00:00","remoteAddr":"192.168.1.1","user":"username","app":"notifications","method":"POST","url":"\/nextcloud\/ocs\/v2.php\/apps\/spreed\/api\/v1\/chat\/aemah2ch","message":{"Exception":"GuzzleHttp\\Exception\\ConnectException","Message":"cURL error 7: Failed to connect to push-notifications.nextcloud.com port 443: Connection timed out (see http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html)"`

Also sometimes the error is "400 Bad Request" instead of connection timeout.
Internally (between desktop web clients) the messages are delivered with no delays.
This makes the Android app unreliable since if you don't periodically open it and check manually you cannot be sure if you have undelivered chats. 
Note that sometimes the push notifications work so this is a sporadic issue.

Edit:
Server is at 15.0.5
Notifications app at 2.3.0 (this app appears in the logs)

**Comment by mario** [comment]
Not related to Android I'm afraid but to the push proxy. We're working on its reliability. Sorry about the issues :(
