### ISSUE TITLE
Remove old compatibility workarounds

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#510]
The required minimum for the Android app can/should be Talk 4, you can pick Talk 3 to prevent too many bad reviews.

Rule of thumb is supported Nextcloud version (which is always 2.5 releases) +1 against bad reviews.

**Comment by tobiasKaminsky** [comment]
> Rule of thumb is supported Nextcloud version (which is always 2.5 releases) +1 against bad reviews.

On Android Files app we decided to use latest supported version - 2, so for now: NC14 - 2 = NC12.

**Comment by nickvergessen** [comment]
Since Talk is still new and changing heavily, this is just creating too much overhead, specially if your server is not supported anyway.

**Comment by mario** [comment]
New version will support v4.0 and up.
