### ISSUE TITLE
Can not open with Nextcloud 16-Beta

### ISSUE THREAD

**Issue by ralfi** [nextcloud/talk-android#513]

**Comment by ralfi** [comment]
My first entry... Today i am update NC to 16-Beta docker image and Talk cannot login after this.

**Comment by ralfi** [comment]
Error querying skills - Show the screen

**Comment by ralfi** [comment]
Error only on Galaxy Tab S2 (lineageos), works find with S9

**Comment by mario** [comment]
Is the Talk app installed and enabled?

**Comment by mario** [comment]
As I suspected, there's no Talk release compatible with 16 just yet. Please be patient :)

**Comment by ralfi** [comment]
Hi Mario, thanks for reply but please let me have a deeper look at the logfiles and aunderstand the relationship between the components.
