### ISSUE TITLE
Second account import never finishes

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#514]
- Have NC files app with two account from two different servers
- freshly install talk app
- open talk app and import one account -> works
- do the same for second one -> spins endlessly after granting access
- go back
- see in settings "switch account", but no other account is listed there (empty list)
- delete the account that is visible, suddenly see second account

tested with latest stable)

**Comment by tobiasKaminsky** [comment]
Now this happens on a fresh 6.0.3 installation also on the very first account.

**Comment by tobiasKaminsky** [comment]
Tested with Android 9 emulator, there it works.
On my OnePlus 3 with Android 9 not…

**Comment by mario** [comment]
Closing, if the issue really existed, will be fixed via https://github.com/nextcloud/talk-android/issues/710
