### ISSUE TITLE
Upload stops when screen is locked

### ISSUE THREAD

**Issue by rahra** [nextcloud/talk-android#515]
When uploading files the and the screen is locked, the upload is paused. This is not very useful, specifically when uploading many files.
Is there a way to disable this?

**Comment by mario** [comment]
Sorry, but can you clarify this? :) Because Nextcloud Talk doesn't allow uploading files for the moment :)

**Comment by rahra** [comment]
Hi! Very sorry for this, just delete it, accidently posted to the wrong repo.

**Comment by mario** [comment]
All good :)
