### ISSUE TITLE
[notifications] Fatal: error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/talk-android#516]
[notifications] Fatal: error:0906D06C:PEM routines:PEM_read_bio:no start line
POST /ocs/v2.php/apps/spreed/api/v1/chat/ii32kaau

Nextcloud 14.0.8.2
ubuntu 18.04.1
postgresql 10.6
apache 2.4.29
php 7.2.15
Talk 5.0.2
Nextcloud Talk (android 9) 3.2.7
notifications 2.2.1
openssl 1.1.0g-2ubuntu4.3

I get an error in the logs when I add an account in the nextcloud-talk 3.2.7 (android 9) or send a message to chat or call.

nextcloud.log:
"Error	notifications	error:0906D06C:PEM routines:PEM_read_bio:no start line"
or
"error:0E06D06C:configuration file routines:NCONF_get_string:no value"
or
"error:0406D06E:rsa routines:RSA_padding_add_PKCS1_type_2:data too large for key size"

**Comment by mario** [comment]
Sounds like a setup issue on the server side?

**Comment by lvarnava** [comment]
can you tell me where to look?

**Comment by mario** [comment]
I'd assume something is wrong with the SSL certificate you use, but I can't debug it like this obviously :)

I'll close the issue as it doesn't seem to be Talk Android-specific, but let me know if you manage to solve this for yourself eventually.

**Comment by lvarnava** [comment]
ok

**Comment by lvarnava** [comment]
by the way the certificate fro domain is received through letsencrypt.
