### ISSUE TITLE
Cannot create new public conversation

### ISSUE THREAD

**Issue by Bubu** [nextcloud/talk-android#526]
Whenever I want to create a new public conversation I just get an error bar at the bottom which says:

"Sorry, something went wrong. [OK]"

There's nothing in the logcat output.

Nextcloud Talk version: 3.2.7 (F-Droid)
Nextcloud Version: 16 RC1
Speerd/Talk app version: 6.0.0-rc.2

**Comment by Bubu** [comment]
So, I'd guess the new beta versions fix that and I should just add them to F-Droid?

**Comment by mario** [comment]
Or wait for stable in two weeks :)

**Comment by Bubu** [comment]
Stable software is so boooring :-p

(I added the beta3 to f-droid now, hopefull it'll be available in 1-2 days)

**Comment by mario** [comment]
You mean in time I release beta4 xD

**Comment by mario** [comment]
Closing since this is working :)

**Comment by Bubu** [comment]
It's available now, I see no beta4 ;-).

And the beta indeed fixes the reported problem. :tada:
