### ISSUE TITLE
Disabling the application when displaying png

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#533]
When you receive the png file and try to display it in the conversation, the Nextcloud Talk application automatically turns off.

App:
Nextcloud Talk v6.0.2
Android 6

**Comment by mario** [comment]
You mean via sharing?

**Comment by Valdnet** [comment]
> You mean via sharing?

Yes.

When sharing a jpg file, the situation is the same.

**Comment by mario** [comment]
Works here, but maybe it's something with Android 6. Will check.

**Comment by mario** [comment]
Do you have a space in your username?

**Comment by Valdnet** [comment]
> Do you have a space in your username?

No.
I have spaces in the password.  If it matters.

**Comment by mario** [comment]
This should be fixed with 6.0 3

**Comment by Valdnet** [comment]
In version 6.0.3 it is also the same.
I would like to add that when sending from me for another user the image is displayed correctly.

**Comment by mario** [comment]
No idea. Can you send me a test accou T with such a conversation?
Mario@nextcloud.com

**Comment by Valdnet** [comment]
Ok. I send.

**Comment by mario** [comment]
Fixed, will be in the next release.
