### ISSUE TITLE
F-Droid build fails with unknown maven repo https://dl.bintray.com/mdjanic/maven

### ISSUE THREAD

**Issue by Bubu** [nextcloud/talk-android#534]
F-Droid doesn't like your custom maven repo.

Using jitpack like for your other forks doesn't work here?
Do you see any possible way to get rid of this maven repo?

If not, how could I recreate that repo prior to the f-droid build?

**Comment by mario** [comment]
I tried using Jitpack but it didn't work out due to complicated nature of Fresco building :( 

I can take a look at it again eventually. What's the issue with maven btw?

**Comment by Bubu** [comment]
There's no guarantee that the artifacts published in a maven repo correspond to any published sources.

That is of course the same for any maven repo, but things like `maven.google.com` or `jcenter` have much more eyes on them that could detect anything malicious going on.

In short, it's a current policy of F-Droid to only allow a whitelist of known-good maven repositories. That's far from ideal but we don't have anything better for the moment.

(Ideally we would never rely on binaries built by the developers but could get them from an independently trusted source like Debian or compile them ourself)

**Comment by gerroon** [comment]
Hi

Any plans on when we can get the F-droid builds?

**Comment by mario** [comment]
@gerroon no idea, sorry :(

**Comment by mario** [comment]
This will be fixed for the next stable. Sorry for the delay.

**Comment by Bubu** [comment]
@mario can you share what will be the solution?

**Comment by mario** [comment]
@Bubu Jitpack managed to build my repository :)
