### ISSUE TITLE
Notifications do not vanish, even if I visit the conversation

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/talk-android#537]
If I open the conversation that triggered a notification I would expect the notification to be removed. In the latest Android Talk client it's not.

**Comment by nickvergessen** [comment]
This will be fixed via https://github.com/nextcloud/notifications/pull/318 for 17

**Comment by mario** [comment]
@nickvergessen no, this has nothing to do with this, at least not if he's referring to visiting a conversation on the android phone locally.

But yea, I do need to implement delete push messages.
