### ISSUE TITLE
Logo in new icon is too small

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#54]
The main round form in the logo is significantly smaller than in the previous Talk app.

I'm a bit confused why since in the source file I only modified the background size and opacity.

**Comment by mario** [comment]
It is 80% of the original size, as mandated by the Material design.

**Comment by jancborchardt** [comment]
I am not talking about the blue background, but the white app logo.

As you can see from this screenshot, the logo circle is much too small:
https://cloud.jancborchardt.net/s/k21ARdN9u8bwUfY

**Comment by mario** [comment]
I know what you're referring to. The icons were generated using the generator inside the Android Studio with size set to 80%, so it should be good.

@AndyScherzinger can tell you more once he's back :)

**Comment by mario** [comment]
Will re-open for now, at least until @AndyScherzinger comes back ^_^

**Comment by AndyScherzinger** [comment]
I can have a look next week if the logo can be larger while staying within the safe zone, when I am back at a laptop

**Comment by AndyScherzinger** [comment]
PR is #67
