### ISSUE TITLE
Cannot get debug infos

### ISSUE THREAD

**Issue by ralfi** [nextcloud/talk-android#541]
Hi talkis,

i have a local network test install with 6.0.3 / nextcloud 16. Text chat and file transfer works well between android devices but video chat do not work. App rights are okay and now i try to get any debug infos but i find no way to do this.  How can i get it and / or what could be wrong?

Thanks in advance.

**Comment by mario** [comment]
You could do it via ADB. But really, this is probably the issue with non-existing TURN like I mentioned - if the two devices can't communicate directly (you can try with two PCs) then ... it's time to setup TURN.

**Comment by ralfi** [comment]
Yeah mario, its really time to setup TURN... No more need to tell at this momemt. Perfect!

**Comment by mario** [comment]
:)
