### ISSUE TITLE
Accepting calls does not work with the MCU

### ISSUE THREAD

**Issue by fancycode** [nextcloud/talk-android#547]
There is a problem when accepting a incoming call when the MCU is being used. I can reproduce this by calling a user on Android from my (Chrome) browser.

## What happens:
- The Android app shows the "ringing" screen and I can accept the video call.
- The user in the app sees the browser streams.
- The browser user doesn't see the streams from the app but shows "Waiting for XXX ..."

## What should happen instead:
- The browser user should see the mobile streams.

From my initial investigation, it looks like the Android app is connecting twice to the signaling server and performs two 'hello` handshakes. The second session only joins the room on the signaling server, but the call is joined with the first session. This results in the browser trying to subscribe the stream of the first session - which is not in the room on the signaling server.

Here is some debug output from the signaling server.

Call got accepted on mobile, see the two connections and the two `Register user XXX logs`:
```
May 23 15:37:29 XXX nextcloud-spreed-signaling[24932]: 2019/05/23 15:37:29.289705 hub.go:1359: New incoming connection from 127.0.0.1:36876
May 23 15:37:29 XXX nextcloud-spreed-signaling[24932]: 2019/05/23 15:37:29.297829 hub.go:1359: New incoming connection from 127.0.0.1:36878
May 23 15:37:29 XXX nextcloud-spreed-signaling[24932]: 2019/05/23 15:37:29.360703 hub.go:537: Register user YYYYY xiHNr4HEPVy2EJjZEtmnPBffExDe3ZHuA2y3hZztZZp8ZUVXWG9saWhGTWdKUXBLSTBSSks3aHZWT1V2NThOWjh4SzZFbzlBZlppSjNaTDZ5S3Rfakd4Y1ZBSU5sOTFOVk53NnRoenBlclhzM0RBMEpTYk1VeGQ2MU05WTl4Zmk5NXRBN2JCTWw4OXJlaFJzM0xVcl9BMkNHNDNONTVIV2JyMXpDWTF2V2daTDl8OTQ2ODE2ODU1MQ== (private=MTU1ODYxODY0OXxVLW54S05IdFVuY3BWSXR1bmJtRFBkYjgyVlM1UmhtN1hmZlZwOXNmTjc5RFpSLU5LNTNNQkZxWGt3WkZhSjgxdzBzdlAyYWtoclpleE5DVzU5N2NxcFdrZC03Tl9oV1RUeHA5RFhERTRmWDFVdUg0LUtjZHc3RmRWNXBTZVlvN3NpYW10NEdQanlNeHyVKJttg-1f3UssGmsQ8JFaT57bVF3Vja3Wo85vT5pdMw==)
May 23 15:37:29 XXX nextcloud-spreed-signaling[24932]: 2019/05/23 15:37:29.405236 hub.go:537: Register user YYYYY ZbW0FutbHfPOSXIUbRj7c3IzHF2ZnRc_2BBp4DPNx4V8c08yejhQallFUThOZ09oeGxpS0FVcHJQRFp2QkpacDkxcmZ6Vk1CYmllOF81bUh0WkgzTDRIY2lMYUJmQXZqeG9VWERodUs2clBVek9jeC1CcUltX0stYWliY2NucFdYZjA2R24xSTFsOGhrdUtkTGpSMnM2RE5kb0lXTnpLdWlnLXFEY2swal9DTUx8OTQ2ODE2ODU1MQ== (private=MTU1ODYxODY0OXxuOGhyRDVVRjUwZXdOSmdydmtzSHRZaHllSDFQZUFUMTZqMDNTQWsxd01hNlFHY1BZdUxJa1FJRFNpSWpOZlZKM0dNcTJyanJlN3dpS1h5dnV2NHRaaEh0cmpKRC13cXVGRUlERWUzaVF0akhURmJWVmZyb0pGT3Q1YTFjOURWUTNlNTJmSjFTU2lhdnxt6xLMcbt_bRCXYj1gIy2Re6gIExOtEJWr13j6lJEHpw==)
```

The second connection joins the room (using a "room session"):
```
May 23 15:37:29 XXX nextcloud-spreed-signaling[24932]: 2019/05/23 15:37:29.503852 session.go:288: Session ZbW0FutbHfPOSXIUbRj7c3IzHF2ZnRc_2BBp4DPNx4V8c08yejhQallFUThOZ09oeGxpS0FVcHJQRFp2QkpacDkxcmZ6Vk1CYmllOF81bUh0WkgzTDRIY2lMYUJmQXZqeG9VWERodUs2clBVek9jeC1CcUltX0stYWliY2NucFdYZjA2R24xSTFsOGhrdUtkTGpSMnM2RE5kb0lXTnpLdWlnLXFEY2swal9DTUx8OTQ2ODE2ODU1MQ== joined room thf8up9f with room session id PvU8EuheLwWTzrUZmX7Fu6CMctycVJEgAyrwytczEQlylP/7pJ553wT5FryN4psQuNCzd8Zff0K5nJKcbqTLGhSfJcWJO6P3v8EEoLtgsd+yLuv+XsBA11IvQtQeUr6xVwfWh5vZH/heTCt0saFtck5bCjq59ueobK1YuvX6bUfqTm3xf8TdJkBbEK3bliS5x6QQUAlrsPjW6NORjjgehZGZWdqXzV/DX/zCF2cRb0CFcCWbV8xhX/cmQ/8OJmh
```

A different "room session" is being looked up which is unknown to the server. This is most likely the room session of the first connection:
```
May 23 15:37:30 XXX nextcloud-spreed-signaling[24932]: 2019/05/23 15:37:30.683468 backend_server.go:259: Could not lookup by room session YudHqNBH3BKwmqjdI4SmYDSvN6g7Bx6ycMGWhdjIy/no/ku1KC7Uzp4T+/i+DR0m1RY0xApEda/uo/WsYxdP1IV1Dqb1nbiHdTmZwnvwMfwN9qH/pUWfS7M0wNHZ6W1dvLCwdmXmWDd/ouJ/M2Zfh9SK0b2mn8H3RQm89zBXJjn5WEKLqw2hbUkN05xcsOLLETaC02BOO7jWcLbWuh8xAEzgraGwopb4H94kW/CMDU5Rjmeg+La+FrkaIVuT6Lo: nats: timeout
May 23 15:37:31 XXX nextcloud-spreed-signaling[24932]: 2019/05/23 15:37:31.683958 backend_server.go:259: Could not lookup by room session YudHqNBH3BKwmqjdI4SmYDSvN6g7Bx6ycMGWhdjIy/no/ku1KC7Uzp4T+/i+DR0m1RY0xApEda/uo/WsYxdP1IV1Dqb1nbiHdTmZwnvwMfwN9qH/pUWfS7M0wNHZ6W1dvLCwdmXmWDd/ouJ/M2Zfh9SK0b2mn8H3RQm89zBXJjn5WEKLqw2hbUkN05xcsOLLETaC02BOO7jWcLbWuh8xAEzgraGwopb4H94kW/CMDU5Rjmeg+La+FrkaIVuT6Lo: nats: timeout
```

The solution imho would be to only connect once to the signaling server and perform all actions using that session.

@Ivansss I think this is the same problem we saw when calling from iOS to Android.

**Comment by fancycode** [comment]
@Ivansss and I traced it down further and I think I have a reproducible test case for you now:
1. Kill the mobile app so you start with a clean environment.
2. Open the app which connects to the signaling server internally.
3. Call the app from the browser. The app shows the ringing screen and both sides see/hear each other when accepting the call.
4. Hangup the call.
5. Now (while keeping the app running) interrupt the network connectivity to the signaling server. This can happen for example if you switch from wifi to mobile or vice versa, or if the server gets updated and restarts.
6.  Call the app from the browser. The app shows the ringing screen but now the browser doesn't see the mobile side when the call is accepted in the app.
7. When checking the logs of the signaling server, I see the two connections as described above and the sessions being used by the app are mixed up.
8. The app stays broken until you kill and restart it (this triggers the initial WebSocket connection to the signaling server).

Looks like the error handling for WebSocket connection interruptions is missing / not working correctly. In any case the app should only create a single connection to the signaling server and use that for joining the rooms.

**Comment by mario** [comment]
@fancycode sometimes, when using resumeid to reconnect, I see this which pretty much breaks it all:

2019-05-27 17:05:56.632 23353-23666/com.nextcloud.talk2.debug D/MagicWebSocketInstance: Receiving : {"type":"error","error":{"code":"internal_error","message":"No url passed to perform JSON request \u0026{Type:room Auth:\u003cnil\u003e Room:0xc42049e730 Ping:\u003cnil\u003e}"}}

Ideas?

**Comment by fancycode** [comment]
Yes, you need to update your signaling server to version 0.0.6 which contains a fix for this. @Ivansss already reported this quite a while ago.

**Comment by mario** [comment]
I did some work on this today. We can test together tomorrow (cc @schiessle)

**Comment by mario** [comment]
@fancycode please do another round of testing once you're around.

**Comment by fancycode** [comment]
:+1: I can no longer reproduce the error with the latest (beta) version of the app.

**Comment by mario** [comment]
Awesome, thanks @fancycode !
