### ISSUE TITLE
Selection window after writing @

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#548]
After entering @ for group conversations and returning to the list of all conversations, the users selection window does not hide.

Steps:
1. Create a group conversation.
2. Go to the conversation and enter @.
3. Go back to the conversation list (main application window).
Error: the user selection dialog for the group conversation remains.

Additionally, the application is crashing when the user is selected from the group conversation user selection window.

App:
Android 6
Nextcloud Talk 6.0.3

**Comment by mario** [comment]
It'll be fixed in the next release. Could you upload a screenshot of the mention window pls?

**Comment by Valdnet** [comment]
Step 2:

> Go to the conversation and enter @.

![obraz](https://user-images.githubusercontent.com/47037905/58687499-11417380-8382-11e9-96fb-395f2b3fc8e7.png)

Return through:

![obraz](https://user-images.githubusercontent.com/47037905/58687909-48fceb00-8383-11e9-91e4-be611182e993.png)

The window remains:

![obraz](https://user-images.githubusercontent.com/47037905/58687714-b3615b80-8382-11e9-8d23-733de19f995d.png)

Go back again through:

![obraz](https://user-images.githubusercontent.com/47037905/58687909-48fceb00-8383-11e9-91e4-be611182e993.png)

The user selection window remains:

![obraz](https://user-images.githubusercontent.com/47037905/58688415-a0e82180-8384-11e9-929e-a5a534c427a8.png)

**Comment by mario** [comment]
Thanks, as I suspected you have other issues too? So in the autocomplete dialog there are NO names, or did you just remove them for the sake of uploading?

**Comment by Valdnet** [comment]
> So in the autocomplete dialog there are NO names, or did you just remove them for the sake of uploading?

There are no names.

It surprised me too 😉
