### ISSUE TITLE
Notifiactions not worked on Samsung S8, S8 plus

### ISSUE THREAD

**Issue by antonixus** [nextcloud/talk-android#549]
Hello, 
We testing Nextcloud Talk on a few devices and only Samsung S8 Plus and S8 has no notifications worked.  There are no errors in the server's system log.

#### Server:
Ubuntu 18.04.2
PHP 7.2.17
nginx/1.14.0
Coturn 4.5.0.7
Nextcloud 16.0.1 from snap package

#### Client device:
Samsung S8 Plus
model SM-G955F
Android 9
Core ver. 4.4.111-15838602

I can provide additional information if required

**Comment by mario** [comment]
Do you  have a notifications app installed on the server?

**Comment by antonixus** [comment]
Problem solved after resetting phone.
