### ISSUE TITLE
Video controls layout

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#55]
Currently the video controls (hang up, video, mute, switch camera) are in that order, very small, on the top of the view. They stay for a long 10 seconds, no matter if something was touched, and then fade out slowly.

Instead of that:

- they should be on the bottom
- have more padding for better tappability (I guess the icon size itself is standard? Maybe a bit small)
- they should be sorted: Hang up, mute, video, camera switch (so video and camera switch is next to each other)
- mute and video should be at .7 opacity when muted / video off for better feedback
- hang up should have slightly more whitespace to the others so accidental tapping is minimized
- fade out should be quicker with 5 seconds, and the fadeout animation should also be quicker, e.g. 300ms. But whenever you touch the display, the timer should reset

**Comment by mario** [comment]
I agree with almost everything except putting them on the bottom. Do you have a reasoning for that?

The bottom is occupied by the small own-video view in the right, and I'd like to keep the UI clutter-less, and putting the controls on the top achieves that.

**Comment by tobiasKaminsky** [comment]
Yesterday I used Skype on my mobile phone. There they have the control buttons on bottom, as also known from VLC and other media players, The small own-video is on top right and is also draggable so it can snap to other corners.
Putting the own-video on top has also the advantage that if you are looking at your own video you look nearly directly in the front camera (as on most devices it is at top).

**Comment by jancborchardt** [comment]
I'm late, but:

> I agree with almost everything except putting them on the bottom. Do you have a reasoning for that?

Yes. Your thumb is on the bottom.

**Comment by mario** [comment]
They are already on the bottom, so you're late, yes :P
