### ISSUE TITLE
No old conversation removed

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#552]
When you delete a conversation and create a new conversation with the same user, the old chat entries remain.

Steps:
1. Create a conversation with the X user.
2. Lead a conversation.
3. Delete the conversation.
4. Create a new conversation with the X user.

ERROR: Old conversation remains.

App:
Android 6
Nextcloud Talk 6.0.5

**Comment by mario** [comment]
Expected. You shouldn't be able to delete logs from the other user :)
