### ISSUE TITLE
Remove push notification if read on other device

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#556]
- have one mobile set up
- receive a push notification about a new chat
- open this chat in browser on e.g. desktop
- notification on top right of web ui vanishes
- push notification on mobile remains

These messages can pile up easily to more than 20…

**Comment by mario** [comment]
You mean https://github.com/nextcloud/talk-android/issues/556? :)

**Comment by tobiasKaminsky** [comment]
Self referring will result in an endless loop ;-)

**Comment by mario** [comment]
@tobiasKaminsky ah, damn - I meant #551 ?

**Comment by tobiasKaminsky** [comment]
Not sure if this is the same, as there is too little info.
If you think it is the same you can close it.

When would you use "delete all"? 
Delete all notifications per conversation should be enough, or?

**Comment by mario** [comment]
I will use delete all when all the notifications on the server are cleared, of course.

But it's not the same, you're right - if you want the functionality requested in this ticket we need (probably) a new endpoint on the server where I'd say - "Read notification with ID" or "Read all  notifications for a conversation RoomToken"

**Comment by tobiasKaminsky** [comment]
Yeah, a new endpoint to mark all notifications for a conversation. 
And then a silent push notification to get this info to all other clients.



> "Read notification with ID"

is not needed in my opinion, or when can it happen that a user reads only one out of 5 remaining messages in a conversation?

**Comment by mario** [comment]
K, yea - might not need that.

**Comment by mario** [comment]
Ok, so the #551 was indeed the same :)
