### ISSUE TITLE
single-sign on with Android files app

### ISSUE THREAD

**Issue by schiessle** [nextcloud/talk-android#559]
I just installed the Nextcloud News app for Android and discovered a really nice feature, I never saw on any other Nextcloud Android app: https://f-droid.org/packages/de.luhmer.owncloudnewsreader/

I can enter the credentials of my Nextcloud server or chose "single-sign on with Nextcloud app". If I chose single-sign-on I can chose an account which is already configured in the files app and I'm directly authenticated and can use the news app. Without having to enter any password, generate a app password, etc.

The talk app also has a option to chose a "Nextcloud app account" but it seems like we just use it to fetch the URL and the user name, I still get redirected to the Nextcloud and have to login in order to finish the app password creation.

Maybe we can look into how the News app does it and make this process even easier?

**Comment by mario** [comment]
Already requested here https://github.com/nextcloud/talk-android/issues/440 - explanation on WHY NOT is also there :)
