### ISSUE TITLE
Signaling Server

### ISSUE THREAD

**Issue by Luticus** [nextcloud/talk-android#560]
I'm not sure where it's appropriate to ask this question so I figured I'd put it here.  In the talk app settings there's a warning: "An external signaling server should optionally be used for larger installations. Leave empty to use the internal signaling server. Please note that calls with more than 4 participants without external signaling server, participants can experience connectivity issues and cause high load on participating devices."  Now I've tried to google this a bit and basically got the run around.  Some places made it look like I needed to code my own, others pointed me to stuff that looked outdated.  I was hoping someone could clarify what the recommended stand alone signaling server to use with this would be?  What are people using for this?  I have a turn/stun setup from the debian repos but can't crack the signaling and I'm really hoping that adding signaling will help with some reliability issues I'm facing.  (call drops)

Thanks!

**Comment by mario** [comment]
Hi,

it's basically the HPB (high performance backend) which is more than just a signaling server and is included as part of a subscription.

Hope that clarifies it, but if not I'm you can always mail me at mario@nextcloud.com :)

Cheers!
