### ISSUE TITLE
Emoticons do not work in chats

### ISSUE THREAD

**Issue by maxlinux2000** [nextcloud/talk-android#561]
To reproduce the error is simple:
Open a nextcloud talk, click on an emoticons and send.
In the box where the message is written the emoticons are seen correctly, but once it is sent, the message appears "????"

look this screenshot:

![photo5776165576836755934](https://user-images.githubusercontent.com/5683921/59555575-f5121900-8fb4-11e9-9eb2-cc354f63185c.jpg)

my phone is: Android 8.1 stock - Motorola G4plus - Spanish language

**Comment by jordanbancino** [comment]
This is not an issue with the app, but rather, your server. You must enable emoji support for your database backend. You can see instructions for that [here](https://docs.nextcloud.com/server/15/admin_manual/configuration_database/mysql_4byte_support.html).

**Comment by maxlinux2000** [comment]
You are rigth!

**Comment by Niemand112233** [comment]
Hi,
I have the same problem. I did everything written here: https://docs.nextcloud.com/server/15/admin_manual/configuration_database/mysql_4byte_support.html
with my MariaDB 10.1 and everything is enabled. But still get the ???? when sending emojis. Any hints?

**Comment by jordanbancino** [comment]
@Niemand112233 That's odd, I'm not sure. Did you try restarting your server? Both the SQL server and the web server?

**Comment by Niemand112233** [comment]
I restartet the whole server. Nothing. Plus the new update of the android app crashes a lot

**Comment by jordanbancino** [comment]
@Niemand112233 Hmm, that's very interesting. I will admit, the last time I did this was quite a while ago. And yes, I've noticed that v7.0.2 does crash a lot. I use v7.0.0beta5 because that is the latest one that is actually semi-stable. 

It is indeed possible to send emojis on the web GUI! On windows you can pull up the emoji picker by pressing Window key + . (Period) I think. And of course phones have emoji keyboards.

**Comment by mario** [comment]
Did you also alter the existing tables or just set the defaults? Because AFAIK the only reason why this didn't work in the past is that people didn't configure their DB correctly.

**Comment by Niemand112233** [comment]
> 
> 
> Did you also alter the existing tables or just set the defaults? Because AFAIK the only reason why this didn't work in the past is that people didn't configure their DB correctly.

I thin I did. How can I check this?

**Comment by mario** [comment]
@skjnldsv I hear you know something more about this? :)

**Comment by skjnldsv** [comment]
@mario so I? Who said that?

**Comment by Niemand112233** [comment]
`MariaDB [nextcloud]> show variables like 'innodb_file_format';
+--------------------+-----------+
| Variable_name      | Value     |
+--------------------+-----------+
| innodb_file_format | Barracuda |
+--------------------+-----------+
1 row in set (0.01 sec)`

`MariaDB [nextcloud]> show variables like 'innodb_file_per_table';
+-----------------------+-------+
| Variable_name         | Value |
+-----------------------+-------+
| innodb_file_per_table | ON    |
+-----------------------+-------+
1 row in set (0.01 sec)`

`MariaDB [nextcloud]> show variables like 'innodb_large_prefix';
+---------------------+-------+
| Variable_name       | Value |
+---------------------+-------+
| innodb_large_prefix | ON    |
+---------------------+-------+
1 row in set (0.00 sec)
`
Server version: 10.1.41-MariaDB-0+deb9u1 Debian 9.9

OS: Unknown 9.11 stretch
Kernel: x86_64 Linux 5.0.21-2-pve

Anything else? I think everything is set as it should be. But still getting "????"

**Comment by mario** [comment]
SELECT NAME, SPACE, FILE_FORMAT FROM INFORMATION_SCHEMA.INNODB_SYS_TABLES WHERE NAME like "nextcloud%";

Output of this pls? :)

**Comment by Niemand112233** [comment]
MariaDB [(none)]> SELECT NAME, SPACE, FILE_FORMAT FROM INFORMATION_SCHEMA.INNODB_SYS_TABLES WHERE NAME like "nextcloud%";
+-----------------------------------------------------+-------+-------------+
| NAME                                                | SPACE | FILE_FORMAT |
+-----------------------------------------------------+-------+-------------+
| nextcloud/oc_accounts                               | 42885 | Barracuda   |
| nextcloud/oc_activity                               | 42886 | Barracuda   |
| nextcloud/oc_activity_mq                            | 42887 | Barracuda   |
| nextcloud/oc_addressbookchanges                     | 42888 | Barracuda   |
| nextcloud/oc_addressbooks                           | 42889 | Barracuda   |
| nextcloud/oc_appconfig                              | 42890 | Barracuda   |
| nextcloud/oc_audioplayer_albums                     | 42891 | Barracuda   |
| nextcloud/oc_audioplayer_artists                    | 42892 | Barracuda   |
| nextcloud/oc_audioplayer_genre                      | 42893 | Barracuda   |
| nextcloud/oc_audioplayer_playlist_tracks            | 42894 | Barracuda   |
| nextcloud/oc_audioplayer_playlists                  | 42895 | Barracuda   |
| nextcloud/oc_audioplayer_stats                      | 42896 | Barracuda   |
| nextcloud/oc_audioplayer_streams                    | 42897 | Barracuda   |
| nextcloud/oc_audioplayer_tracks                     | 42898 | Barracuda   |
| nextcloud/oc_authtoken                              | 42899 | Barracuda   |
| nextcloud/oc_bookmarks                              | 42900 | Barracuda   |
| nextcloud/oc_bookmarks_folders                      | 42901 | Barracuda   |
| nextcloud/oc_bookmarks_folders_bookmarks            | 42902 | Barracuda   |
| nextcloud/oc_bookmarks_tags                         | 42903 | Barracuda   |
| nextcloud/oc_bruteforce_attempts                    | 42904 | Barracuda   |
| nextcloud/oc_calendar_invitations                   | 42905 | Barracuda   |
| nextcloud/oc_calendar_resources                     | 42906 | Barracuda   |
| nextcloud/oc_calendar_rooms                         | 42907 | Barracuda   |
| nextcloud/oc_calendarchanges                        | 42908 | Barracuda   |
| nextcloud/oc_calendarobjects                        | 42909 | Barracuda   |
| nextcloud/oc_calendarobjects_props                  | 42910 | Barracuda   |
| nextcloud/oc_calendars                              | 42911 | Barracuda   |
| nextcloud/oc_calendarsubscriptions                  | 42912 | Barracuda   |
| nextcloud/oc_cards                                  | 42913 | Barracuda   |
| nextcloud/oc_cards_properties                       | 42914 | Barracuda   |
| nextcloud/oc_carnet_metadata                        | 42915 | Barracuda   |
| nextcloud/oc_circles_circles                        | 42916 | Barracuda   |
| nextcloud/oc_circles_clouds                         | 42917 | Barracuda   |
| nextcloud/oc_circles_groups                         | 42918 | Barracuda   |
| nextcloud/oc_circles_links                          | 42919 | Barracuda   |
| nextcloud/oc_circles_members                        | 42920 | Barracuda   |
| nextcloud/oc_circles_shares                         | 42921 | Barracuda   |
| nextcloud/oc_cms_pico_websites                      | 42922 | Barracuda   |
| nextcloud/oc_collres_accesscache                    | 42923 | Barracuda   |
| nextcloud/oc_collres_collections                    | 42924 | Barracuda   |
| nextcloud/oc_collres_resources                      | 42925 | Barracuda   |
| nextcloud/oc_comments                               | 42926 | Barracuda   |
| nextcloud/oc_comments_read_markers                  | 42927 | Barracuda   |
| nextcloud/oc_cookbook_keywords                      | 42928 | Barracuda   |
| nextcloud/oc_cookbook_names                         | 42929 | Barracuda   |
| nextcloud/oc_cospend_bill_owers                     | 42930 | Barracuda   |
| nextcloud/oc_cospend_bills                          | 42931 | Barracuda   |
| nextcloud/oc_cospend_ext_projects                   | 42932 | Barracuda   |
| nextcloud/oc_cospend_members                        | 42933 | Barracuda   |
| nextcloud/oc_cospend_projects                       | 42934 | Barracuda   |
| nextcloud/oc_cospend_shares                         | 42935 | Barracuda   |
| nextcloud/oc_credentials                            | 42936 | Barracuda   |
| nextcloud/oc_dashboard_events                       | 42937 | Barracuda   |
| nextcloud/oc_dashboard_settings                     | 42938 | Barracuda   |
| nextcloud/oc_dav_shares                             | 42939 | Barracuda   |
| nextcloud/oc_deck_assigned_labels                   | 42940 | Barracuda   |
| nextcloud/oc_deck_assigned_users                    | 42941 | Barracuda   |
| nextcloud/oc_deck_attachment                        | 42942 | Barracuda   |
| nextcloud/oc_deck_board_acl                         | 42943 | Barracuda   |
| nextcloud/oc_deck_boards                            | 42944 | Barracuda   |
| nextcloud/oc_deck_cards                             | 42945 | Barracuda   |
| nextcloud/oc_deck_labels                            | 42946 | Barracuda   |
| nextcloud/oc_deck_stacks                            | 42947 | Barracuda   |
| nextcloud/oc_directlink                             | 42948 | Barracuda   |
| nextcloud/oc_e2e_encryption_lock                    | 42949 | Barracuda   |
| nextcloud/oc_federated_reshares                     | 42950 | Barracuda   |
| nextcloud/oc_file_locks                             | 42951 | Barracuda   |
| nextcloud/oc_filecache                              | 42952 | Barracuda   |
| nextcloud/oc_files_antivirus                        | 42953 | Barracuda   |
| nextcloud/oc_files_avir_status                      | 42954 | Barracuda   |
| nextcloud/oc_files_trash                            | 42955 | Barracuda   |
| nextcloud/oc_flow_checks                            | 42956 | Barracuda   |
| nextcloud/oc_flow_operations                        | 42957 | Barracuda   |
| nextcloud/oc_fulltextsearch_indexes                 | 42958 | Barracuda   |
| nextcloud/oc_fulltextsearch_ticks                   | 42959 | Barracuda   |
| nextcloud/oc_gpxedit_options                        | 42960 | Barracuda   |
| nextcloud/oc_gpxedit_tile_servers                   | 42961 | Barracuda   |
| nextcloud/oc_gpxmotion_options                      | 42962 | Barracuda   |
| nextcloud/oc_gpxmotion_tile_server                  | 42963 | Barracuda   |
| nextcloud/oc_gpxpod_directories                     | 42964 | Barracuda   |
| nextcloud/oc_gpxpod_options_values                  | 42965 | Barracuda   |
| nextcloud/oc_gpxpod_pictures                        | 42966 | Barracuda   |
| nextcloud/oc_gpxpod_tile_servers                    | 42967 | Barracuda   |
| nextcloud/oc_gpxpod_tracks                          | 42968 | Barracuda   |
| nextcloud/oc_group_admin                            | 42969 | Barracuda   |
| nextcloud/oc_group_folders                          | 42970 | Barracuda   |
| nextcloud/oc_group_folders_acl                      | 42971 | Barracuda   |
| nextcloud/oc_group_folders_groups                   | 42972 | Barracuda   |
| nextcloud/oc_group_folders_manage                   | 42973 | Barracuda   |
| nextcloud/oc_group_folders_trash                    | 42974 | Barracuda   |
| nextcloud/oc_group_user                             | 42975 | Barracuda   |
| nextcloud/oc_groups                                 | 42976 | Barracuda   |
| nextcloud/oc_jobs                                   | 42977 | Barracuda   |
| nextcloud/oc_login_flow_v2                          | 42978 | Barracuda   |
| nextcloud/oc_mail_accounts                          | 42979 | Barracuda   |
| nextcloud/oc_mail_aliases                           | 42980 | Barracuda   |
| nextcloud/oc_mail_attachments                       | 42981 | Barracuda   |
| nextcloud/oc_mail_coll_addresses                    | 42982 | Barracuda   |
| nextcloud/oc_mail_mailboxes                         | 42983 | Barracuda   |
| nextcloud/oc_maps_address_geo                       | 42984 | Barracuda   |
| nextcloud/oc_maps_apikeys                           | 42985 | Barracuda   |
| nextcloud/oc_maps_device_points                     | 42986 | Barracuda   |
| nextcloud/oc_maps_devices                           | 42987 | Barracuda   |
| nextcloud/oc_maps_favorites                         | 42988 | Barracuda   |
| nextcloud/oc_maps_photos                            | 42989 | Barracuda   |
| nextcloud/oc_maps_tracks                            | 42990 | Barracuda   |
| nextcloud/oc_migrations                             | 42991 | Barracuda   |
| nextcloud/oc_mimetypes                              | 42992 | Barracuda   |
| nextcloud/oc_mindmaps                               | 42993 | Barracuda   |
| nextcloud/oc_mindmaps_acl                           | 42994 | Barracuda   |
| nextcloud/oc_mindmaps_nodes                         | 42995 | Barracuda   |
| nextcloud/oc_mounts                                 | 42996 | Barracuda   |
| nextcloud/oc_music_albums                           | 42997 | Barracuda   |
| nextcloud/oc_music_ampache_sessions                 | 42998 | Barracuda   |
| nextcloud/oc_music_ampache_users                    | 42999 | Barracuda   |
| nextcloud/oc_music_artists                          | 43000 | Barracuda   |
| nextcloud/oc_music_cache                            | 43001 | Barracuda   |
| nextcloud/oc_music_playlists                        | 43002 | Barracuda   |
| nextcloud/oc_music_tracks                           | 43003 | Barracuda   |
| nextcloud/oc_notes_meta                             | 43004 | Barracuda   |
| nextcloud/oc_notifications                          | 43005 | Barracuda   |
| nextcloud/oc_notifications_pushtokens               | 43006 | Barracuda   |
| nextcloud/oc_oauth2_access_tokens                   | 43007 | Barracuda   |
| nextcloud/oc_oauth2_clients                         | 43008 | Barracuda   |
| nextcloud/oc_ocdownloader_adminsettings             | 43009 | Barracuda   |
| nextcloud/oc_ocdownloader_personalsettings          | 43010 | Barracuda   |
| nextcloud/oc_ocdownloader_queue                     | 43011 | Barracuda   |
| nextcloud/oc_ocsms_config                           | 43012 | Barracuda   |
| nextcloud/oc_ocsms_conversation_read_states         | 43013 | Barracuda   |
| nextcloud/oc_ocsms_sendmessage_queue                | 43014 | Barracuda   |
| nextcloud/oc_ocsms_smsdatas                         | 43015 | Barracuda   |
| nextcloud/oc_ocsms_user_datas                       | 43016 | Barracuda   |
| nextcloud/oc_passman_credentials                    | 43017 | Barracuda   |
| nextcloud/oc_passman_delete_vault_request           | 43018 | Barracuda   |
| nextcloud/oc_passman_files                          | 43019 | Barracuda   |
| nextcloud/oc_passman_revisions                      | 43020 | Barracuda   |
| nextcloud/oc_passman_share_request                  | 43021 | Barracuda   |
| nextcloud/oc_passman_sharing_acl                    | 43022 | Barracuda   |
| nextcloud/oc_passman_vaults                         | 43023 | Barracuda   |
| nextcloud/oc_passwords_entity_challenge             | 43024 | Barracuda   |
| nextcloud/oc_passwords_entity_folder                | 43025 | Barracuda   |
| nextcloud/oc_passwords_entity_folder_revision       | 43026 | Barracuda   |
| nextcloud/oc_passwords_entity_keychain              | 43027 | Barracuda   |
| nextcloud/oc_passwords_entity_password              | 43028 | Barracuda   |
| nextcloud/oc_passwords_entity_password_revision     | 43029 | Barracuda   |
| nextcloud/oc_passwords_entity_session               | 43030 | Barracuda   |
| nextcloud/oc_passwords_entity_share                 | 43031 | Barracuda   |
| nextcloud/oc_passwords_entity_tag                   | 43032 | Barracuda   |
| nextcloud/oc_passwords_entity_tag_revision          | 43033 | Barracuda   |
| nextcloud/oc_passwords_relation_password_tag        | 43034 | Barracuda   |
| nextcloud/oc_phonetrack_devices                     | 43035 | Barracuda   |
| nextcloud/oc_phonetrack_filtersb                    | 43036 | Barracuda   |
| nextcloud/oc_phonetrack_geofences                   | 43037 | Barracuda   |
| nextcloud/oc_phonetrack_options                     | 43038 | Barracuda   |
| nextcloud/oc_phonetrack_points                      | 43039 | Barracuda   |
| nextcloud/oc_phonetrack_proxims                     | 43040 | Barracuda   |
| nextcloud/oc_phonetrack_pubshares                   | 43041 | Barracuda   |
| nextcloud/oc_phonetrack_sessions                    | 43042 | Barracuda   |
| nextcloud/oc_phonetrack_shares                      | 43043 | Barracuda   |
| nextcloud/oc_phonetrack_tileserver                  | 43044 | Barracuda   |
| nextcloud/oc_polls_comments                         | 43045 | Barracuda   |
| nextcloud/oc_polls_events                           | 43046 | Barracuda   |
| nextcloud/oc_polls_notif                            | 43047 | Barracuda   |
| nextcloud/oc_polls_options                          | 43048 | Barracuda   |
| nextcloud/oc_polls_votes                            | 43049 | Barracuda   |
| nextcloud/oc_preferences                            | 43050 | Barracuda   |
| nextcloud/oc_preview_generation                     | 43051 | Barracuda   |
| nextcloud/oc_privacy_admins                         | 43052 | Barracuda   |
| nextcloud/oc_properties                             | 43053 | Barracuda   |
| nextcloud/oc_quicknotes_colors                      | 43054 | Barracuda   |
| nextcloud/oc_quicknotes_notes                       | 43055 | Barracuda   |
| nextcloud/oc_quicknotes_shares                      | 43056 | Barracuda   |
| nextcloud/oc_quicknotes_tasks                       | 43057 | Barracuda   |
| nextcloud/oc_radio_stations                         | 43058 | Barracuda   |
| nextcloud/oc_ransomware_detection                   | 43059 | Barracuda   |
| nextcloud/oc_richdocuments_assets                   | 43060 | Barracuda   |
| nextcloud/oc_richdocuments_direct                   | 43061 | Barracuda   |
| nextcloud/oc_richdocuments_member                   | 43062 | Barracuda   |
| nextcloud/oc_richdocuments_wopi                     | 43063 | Barracuda   |
| nextcloud/oc_schedulingobjects                      | 43064 | Barracuda   |
| nextcloud/oc_sensorlogger_data_types                | 43065 | Barracuda   |
| nextcloud/oc_sensorlogger_device_data_types         | 43066 | Barracuda   |
| nextcloud/oc_sensorlogger_device_groups             | 43067 | Barracuda   |
| nextcloud/oc_sensorlogger_device_types              | 43068 | Barracuda   |
| nextcloud/oc_sensorlogger_devices                   | 43069 | Barracuda   |
| nextcloud/oc_sensorlogger_logs                      | 43070 | Barracuda   |
| nextcloud/oc_share                                  | 43071 | Barracuda   |
| nextcloud/oc_share_external                         | 43072 | Barracuda   |
| nextcloud/oc_storages                               | 43073 | Barracuda   |
| nextcloud/oc_systemtag                              | 43074 | Barracuda   |
| nextcloud/oc_systemtag_group                        | 43075 | Barracuda   |
| nextcloud/oc_systemtag_object_mapping               | 43076 | Barracuda   |
| nextcloud/oc_talk_commands                          | 43077 | Barracuda   |
| nextcloud/oc_talk_guests                            | 43078 | Barracuda   |
| nextcloud/oc_talk_participants                      | 43079 | Barracuda   |
| nextcloud/oc_talk_rooms                             | 43080 | Barracuda   |
| nextcloud/oc_talk_signaling                         | 43081 | Barracuda   |
| nextcloud/oc_text_documents                         | 43082 | Barracuda   |
| nextcloud/oc_text_sessions                          | 43083 | Barracuda   |
| nextcloud/oc_text_steps                             | 43084 | Barracuda   |
| nextcloud/oc_timetracker_client                     | 43085 | Barracuda   |
| nextcloud/oc_timetracker_locked_project_allowed_tag | 43086 | Barracuda   |
| nextcloud/oc_timetracker_project                    | 43087 | Barracuda   |
| nextcloud/oc_timetracker_tag                        | 43088 | Barracuda   |
| nextcloud/oc_timetracker_timeline                   | 43089 | Barracuda   |
| nextcloud/oc_timetracker_timeline_entry             | 43090 | Barracuda   |
| nextcloud/oc_timetracker_user_to_client             | 43091 | Barracuda   |
| nextcloud/oc_timetracker_user_to_project            | 43092 | Barracuda   |
| nextcloud/oc_timetracker_work_interval              | 43093 | Barracuda   |
| nextcloud/oc_timetracker_workinterval_to_tag        | 43094 | Barracuda   |
| nextcloud/oc_trusted_servers                        | 43095 | Barracuda   |
| nextcloud/oc_twofactor_backupcodes                  | 43096 | Barracuda   |
| nextcloud/oc_twofactor_providers                    | 43097 | Barracuda   |
| nextcloud/oc_users                                  | 43098 | Barracuda   |
| nextcloud/oc_users_external                         | 43099 | Barracuda   |
| nextcloud/oc_vcategory                              | 43100 | Barracuda   |
| nextcloud/oc_vcategory_to_object                    | 43101 | Barracuda   |
| nextcloud/oc_weather_city                           | 43102 | Barracuda   |
| nextcloud/oc_weather_config                         | 43103 | Barracuda   |
| nextcloud/oc_whats_new                              | 43104 | Barracuda   |
+-----------------------------------------------------+-------+-------------+
220 rows in set (0.01 sec)

**Comment by mario** [comment]
Did you run this:

ALTER DATABASE nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
sudo -u www-data php occ config:system:set mysql.utf8mb4 --type boolean --value="true"
sudo -u www-data php occ maintenance:repair

**Comment by Niemand112233** [comment]
yes

**Comment by mario** [comment]
Very strange :( Can you share a test account to mario@nextcloud.com pls?

**Comment by Niemand112233** [comment]
I did everything you wrote, but still getting "????"

**Comment by JedMeister** [comment]
Hey @Niemand112233 - Did you ever resolve this? I have come across a similar issue and I'm stumped...

**Comment by nickvergessen** [comment]
Well, check https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html and if that doesn't work, ask for help in the forum:
https://help.nextcloud.com/

**Comment by Niemand112233** [comment]
Problem still here..
