### ISSUE TITLE
Conversation list stuck in loading state

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/talk-android#562]
- Have some conversations
- Start the app
- List is stuck in loading 
- Close the app
- Open again
- Conversation list is shown as expected

This problem occurs quite often for me.

![talk_conversation_list](https://user-images.githubusercontent.com/1426823/59562304-f67a2a80-9022-11e9-9120-6f2e5ae00cb0.jpg)

**Comment by mario** [comment]
Hi @ezaquarii did you maybe try to debug what's happening?

**Comment by ezaquarii** [comment]
I did not have time to check the source code *yet*, but if I disable the network, I can reproduce it 100%.
I suspect it requires a response from backend before displaying the list.

**Comment by ezaquarii** [comment]
@mario I did not have time to check the source code *yet*, but if I disable the network, I can reproduce it 100%.

I suspect it requires a response from backend before displaying the list.

**Comment by mario** [comment]
@ezaquarii ah yup, that's it. We do plan to work on full offline support in the future, but atm the focus is on connection stability/reconnections.

In the mean time, maybe we could extend the current state to show an error or something when it fails to get backend response or there's an error.

**Comment by ezaquarii** [comment]
@mario Since I noticed this issue under poor network conditions, maybe a better retry mechanism could improve it?

**Comment by mario** [comment]
@ezaquarii that's also possible and should be trivial given that we use rxjava(2).

https://github.com/nextcloud/talk-android/blob/c02f820304bb09abaff5256c789305dcbd9d61f9/app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java#L312

**Comment by ezaquarii** [comment]
@mario Trivial solution would be to simply re-try on error, but I'm worried that it will misbehave on persistent network error (private net, airplane mode, list GSM signal, etc), contunously trying to retry fast-failing task.

Also, I'm not sure if it will handle network re-connection well.

This is a stateful behavior with possible edge cases - I'm not sure how to model it using rx. Suggestions?

**Comment by mario** [comment]
I've began working on some magic that involves reconnections, but there are still some edge cases that I didn't quite catch, but if you look here you'll see there are events for connect/disconnect being sent: https://github.com/nextcloud/talk-android/blob/c90ff879c27f39341a030a03f13133674d990974/app/src/main/java/com/nextcloud/talk/utils/singletons/MerlinTheWizard.java, in addition to the isConnectedToInternet method which returns you immediate result if you need to check.

Merlin also uses an endpoint to check if we're behind the captive portal.

So I'd say: retryWhen: isConnectedToInternet() && retryCount < 3 && http error code is not unathorized? And if we're offline, show the offline state (for now) and invoke fetchData when we go back online via NetworkEvent.NetworkConnectionEvent.NETWORK_CONNECTED eventbus message?

That being said

**Comment by mario** [comment]
Opinions and comments welcome, of course.

**Comment by ezaquarii** [comment]
> I've began working on some magic that involves reconnections, but there are still some edge cases that I didn't quite catch

Those are very cleanly handled by state machines, as FSMs can lift arbitrary level of complexity. If you are struggling with covering all cases, https://github.com/oxo42/stateless4j could help.

**Comment by mario** [comment]
@ezaquarii I'll definitely take a look at that, thank you. But the problem at hand is a bit more down-to-earth atm that I'd like to fix before I move to stateless4j for state magic.

https://github.com/novoda/merlin/issues/193

See here for details. Strangely, it works in their demo :-/

**Comment by ezaquarii** [comment]
@mario Can you point me to your code? I'll take a look.

**Comment by mario** [comment]
@ezaquarii pretty much all is here - https://github.com/nextcloud/talk-android/blob/c90ff879c27f39341a030a03f13133674d990974/app/src/main/java/com/nextcloud/talk/utils/singletons/MerlinTheWizard.java

And then you can use "Find usages" to see where each of the methods are used. Let me know if you have any questions.
