### ISSUE TITLE
nextcloud talk blocked and without calls

### ISSUE THREAD

**Issue by maxlinux2000** [nextcloud/talk-android#573]
I have a problem with nextcloud talk.
Yesterday, I could make call and video calls correctly.
On my mobile phones I have the nextcloudTalk from google installed and the notifications worked.
Today in "Talk" (in the browser of the computer) from the menu of the users (the 3 dots) I have disabled the notifications, and then reactivated.

![Screenshot_2019-06-26_14-52-22](https://user-images.githubusercontent.com/5683921/60204353-f3671180-984e-11e9-9d31-a66a745f4076.png)

From this moment, mobile notifications do not work (they still work in the browser).
Calls and video calls do not work either. Mobiles do not activate when a user makes a call.
My installation is the last stable, 16.0.1, the Notification plugin is active, I have not touched anything in the configuration of the stun server (stun.nextcloud.com:443)
this nextcloud server answers the ping.

any ideas?

**Comment by maxlinux2000** [comment]
Ok, I think I found the problem. The tun server (stun.nextcloud.com:443) was down, so the push messsge and calls doesn't works.
My workaround was setup a tun server using the same vps of my nextcloud installstion.
For the moment seem works. I will update this bug next week

**Comment by mario** [comment]
@nickvergessen could this really be the issue?

**Comment by nickvergessen** [comment]
No, STUN is only used in webrtc to determinate the public IP of the participants.
But that is waaaay after the notification has been sent already.

**Comment by maxlinux2000** [comment]
I have rebuild de nextcloud installation from zero, setup the coturn server in the same vps, and installad in the phones the google version of nextcloud talk.

Now seem works, but sometimes the phone don't receive the push message from the other one. This occurs especially after some hours from the las message or call.

first device have LineageOS 14.1 (android 7.1 like) with openGapps. All other apps like whatsapp, telegram, bank app, youtube... works just fine

Second device use Android 8.1 stock. The nextcloud talk app is not optimized in the settings battery.

Others things that can I do?

**Comment by maxlinux2000** [comment]
Ok, with the las update the problem is gone. Closed!
