### ISSUE TITLE
The screen stays on after finishing the call

### ISSUE THREAD

**Issue by alirasol** [nextcloud/talk-android#574]
After a finished call I noticed the phone's screen stays on and my phone does not go to sleep mode after the set time of 30 seconds, even after closing the app. And when I turn my screen off, and get a notification or a message. the screen stays on and drains the battery. I am forced to restart my phone after every call with Nextcloud Talk to go around this problem.

**Comment by mario** [comment]
Will look into this, thank you.

**Comment by alirasol** [comment]
Just wanted to thank you for fixing the issue

**Comment by mario** [comment]
:) You are more than welcome - thank you for following up @alirasol.
