### ISSUE TITLE
Bug: About the dectector of the push messages (again)

### ISSUE THREAD

**Issue by maxlinux2000** [nextcloud/talk-android#575]
There is a problem with push notifications (in the google version).
When I start a conversation with another user using chat, the first time the push warning message arrives several seconds late (up to 30 seconds), then the chat and any calls or video calls run without problems.

But if I let pass a time where meanwhile the screens of the mobiles have been turned off, and I want to make a call to another user, this will not receive any notification, until the screen is started again.
It seems that the program that works in background at low level, has no ability to check if there are calls if the screen is off.

A similar problem occurs if we are going to use an AppKiller. After killing all active apps, Talk will not receive any notification, neither text nor audio, until the user launches the app again.

I think you have to review the program that detects notifications. 
See how Telegram works, for example.

**Comment by mario** [comment]
There's not much we can do about this. You can disable battery optimizations, and depending on your phone, do other things like enable app auto-launch.

If you'd like anything different and feel like you have a technical solution, please open a PR. 

Thanks!
