### ISSUE TITLE
App crashes after photo share

### ISSUE THREAD

**Issue by celocore** [nextcloud/talk-android#580]
Hello there,

after sharing a photo from the album of my mobile phone in talk, the app for the chat with the photo crashes on all devices. All other chats still work. I think the reason is the size of 2.8 MB.

All devices are Android 9 and Nextcloud talk version is 6.0.7

Greetings
Michael

**Comment by mario** [comment]
There's no option to share a file from your device just yet. How did you do this?

**Comment by celocore** [comment]
Sorry for the inaccurate description.
I shared the photo from my device with NextCloud client and then added it in the chat with the + button in front of the input field.

**Comment by mario** [comment]
Thanks, I'll investigate though size here is really irrelevant and the functionality should work.

**Comment by mario** [comment]
Works in master, so it'll the fixed with the next release :) Please reopen if that's not true!
