### ISSUE TITLE
written explanation URL chat public error

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/talk-android#581]
the problem of bad centering of the explanation of the URL to activate public chat takes place on Nexus 6 with android 7.0 perhaps for display?  
the explanation is well centered on Samsung s8 and 2xl pixels.  but from the photo you notice the bug of the writing that not of law.  Italian language

![Screenshot_20190713-213948](https://user-images.githubusercontent.com/35575744/61175895-7f9b6780-a5b7-11e9-83bb-7e607b419cc3.png)

**Comment by nickvergessen** [comment]
Moving to android repo

**Comment by mario** [comment]
Should be fixed in the next release. Let me know if not.
