### ISSUE TITLE
Troubles adding account to android talk app

### ISSUE THREAD

**Issue by adymorz** [nextcloud/talk-android#582]
Versions:
Nextcloud: 16.0.3 
Talk: 6.0.2
Android-App: 6.0.7

# White page after authentication by token:
* "Konto hinzufügen" ("Add account")
* Add URL
* Button "Alternative Anmeldung via App-Taken" ("alternative authentication using app token")
* Add Username / App-Token
* Button "Zugriff gewähren" ("Grant access")

Expected result:
Accounts get added.

Current result:
A white page gets shown, no error message in android client or on server (log).

# Error message after authentication by username / passwort and TOTP token:
* "Konto hinzufügen" ("Add account")
* Add URL
* Button "Anmelden" ("Authenticate")
* Add Username / password
* Button "Anmelden" ("Authenticate")
* Add TOTP Code
* Button "Übermitteln" ("Submit")
* Button "Zugriff gewähren" ("Grant access")

Expected result:
Accounts get added.

Current result:
An error message gets shown:
> Fehler:
> Access Forbidden
> Invalid request

**Comment by mario** [comment]
There is 99,999% chance this is a setup issue on the server side, so please look into that.

**Comment by adymorz** [comment]
Thanks for your fast answer. You are right.

`'overwriteprotocol' => 'https'` has been missing in the configuration.

**Comment by mario** [comment]
:) Glad it works now.
