### ISSUE TITLE
Dispay error while opening conversation

### ISSUE THREAD

**Issue by johnripper1** [nextcloud/talk-android#583]
Device: Galaxy S10+
Android App Version: 6.0.7
Server: 15.0.5.3
Talk App Version: 5.0.4

If i want to start a conversation the FERTIG Button in the upper right side is missing, even if all Informationen are provided properly.
See the missing button here:
![20190721_123232](https://user-images.githubusercontent.com/10068353/61590086-a65b2e80-abb3-11e9-943f-976532fa1cba.jpg)

Furthere more display issues as you add more users:
![20190721_121709](https://user-images.githubusercontent.com/10068353/61590020-95f68400-abb2-11e9-9c38-58d5503281d0.jpg)

Without changing anything within the app, turing the screen into wide screen brings the button:
![20190721_122722](https://user-images.githubusercontent.com/10068353/61590042-feddfc00-abb2-11e9-8a56-dfcf68533d00.jpg)

And it keeps it when you return from wide screen to upside mode:
![20190721_122736](https://user-images.githubusercontent.com/10068353/61590047-07363700-abb3-11e9-88e6-2e39b7881de7.jpg)

Please note: I'll just report this issue as is. If your unable troubleshoot with the information given, please close this issue, as I have no time to provide more information. Sorry and thank you for your cooperation.

I also want to thank all contributors for this entire project. Nextcloud and all the addtional universe is really a base to host your own platform for sharing addtional purpose.

**Comment by mario** [comment]
Should be fixed in master when it comes to the done button. The display issue is outlined here: https://github.com/nextcloud/talk-android/issues/581
