### ISSUE TITLE
microphone not working

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#586]
Model: SM-J510FN
Android 7.1.1
Talk android 6.1.1

In voice call other side cant hear me. I remember that behaviour in previous versions too.

**Comment by jookk** [comment]
Video call afected too. Mic not working

**Comment by mario** [comment]
Thanks, I'll investigate.

**Comment by mario** [comment]
Hi,

I just tried this - works like a charm :-/ Can you please make sure the other side has turned on volume or give me some more information to debug?

Cheers,
Mario

**Comment by jookk** [comment]
It's wired. Other samsung working fine. (Other model).
Samsung have some sort of privacy protection. It notifies user if app uses 
microphone in background.
I tried to search in phone, but couldn't find it.
(I thought, if (my sister) blocked it accidentally.

Dňa 25. júla 2019 18:56:49 používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by mario** [comment]
Once you find me a way to reproduce, please re-open the issue - I'll happily look into it again. As it stands right now I can't reproduce :(

**Comment by jookk** [comment]
So, I requested device reboot and ... mic working. Thx
