### ISSUE TITLE
App Lock geature: the app does not prompt for unlocking if it was not used for longer periods

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/talk-android#589]
The app has the lock feature implemented, but it does not use it correctly.
If i leave the app for long periods (maybe the app is terminated in the background?), i can open it again without having to provide authentication (fingerprint, etc) even if i set the timeout to the lowest possible 30 sec.
This really defeats the purpose of this feature.

**Comment by mario** [comment]
What version of the app, what phone, what Android version?

**Comment by gradinaruvasile** [comment]
Nokia 5, Android 9, Talk 6.1.2

**Comment by mario** [comment]
I think I know why this is. Because the app relies on the system setup, if you say go away from your phone, it'll lock itself - so when you unlock it, you basically unlocked the app as well. Does that make sense?

**Comment by gradinaruvasile** [comment]
By this token separate app locks should have no use.

**Comment by mario** [comment]
Almost :) Which is why I didn't implement this for so long.

**Comment by gradinaruvasile** [comment]
The nextcloud files app does this much better, for us paranoids it is perfect, it locks when in background.

**Comment by mario** [comment]
This can be workarounded by clearing cache/data of the app :) So I honestly see very little point :-/

**Comment by mario** [comment]
@nickvergessen thoughts on this?

**Comment by nickvergessen** [comment]
Hmm?

**Comment by DavidMndz** [comment]
This also happened to me, but lately since the last Talk update it seems to work perfectly.

I use a Note 10+ with Android 10, Nextcloud Talk v8.0.8.

**Comment by nickvergessen** [comment]
So closing for now

**Comment by DavidMndz** [comment]
Sorry, after my last comment I reviewed deeper the behaviour and although some times the lock of Talk works as expected, some other times does not require the fingerprint or the credentials.

As mentioned above, it is not working fine 100% times as the Nextcloud Android app does.
