### ISSUE TITLE
Text messages

### ISSUE THREAD

**Issue by fredscud** [nextcloud/talk-android#59]
Hi,
do you plan to implement text chat to talk-android ?
Thanks,
Fred.

**Comment by mario** [comment]
Yes, but not very soon because the API doesn't support it yet.

**Comment by mario** [comment]
My apologies, the API is there, but not documented. So eventually :)

**Comment by c0fe** [comment]
@mario what exactly would be the issue in activating this capability if the API supports it? I am a bit confused.

**Comment by mario** [comment]
Well, there are several reasons why I'm postponing this :)

a) Currently focusing on the core experience and calling
b) Chat API exists, but is not very good / not meant for mobile
c) It takes time :P

**Comment by c0fe** [comment]
@mario just a bit of clarification, you say core, are you referring to Nextcloud overall or the core for Nextcloud Talk specifically?

**Comment by mario** [comment]
@c0fe core experience of the Nextcloud Talk on Android and Nextcloud Talk in general :)

**Comment by c0fe** [comment]
@mario any timeline/ETA on when you anticipate having text messages available? XMPP is ancient, MatterMost is more geared towards team chat, Nextcloud Talk would be perfect.

**Comment by mario** [comment]
@c0fe no :( I'm hoping 2.0 will mean chat, but as for time ... I don't know when that is. This year? :D

**Comment by cpatscheider** [comment]
If nextcloud/talk-android would be available at bountysource i would support this feature!

**Comment by danger89** [comment]
Will you also support end 2 end message encryption?

**Comment by mario** [comment]
No, not for now.

**Comment by jebos** [comment]
Any ETA for this feature?

**Comment by c0fe** [comment]
@mario how to sign up?

**Comment by mario** [comment]
https://play.google.com/apps/testing/com.nextcloud.talk2

**Comment by lesykm** [comment]
Thank you for implementing this feature.
Having an issue though - installed 1.2 beta, but see no text functionality in the client :(
Also, message sent from server to account with android client does not appear in android client.
Could you please help, how to turn this feature on?
Versions:
Android client: 1.2 beta
Server: 13.0.1
Talk app: 3.2.0
Thank you!

**Comment by mario** [comment]
Should be turned on by default. What happens when you click on one of the conversations in the "Conversations" tab?

**Comment by lesykm** [comment]
In my case ordinary call is invoked - I could only play with Mic, Speaker, Camera.
I've Galaxy S8 upgraded to Android Oreo.
Context menu for conversations has following records: ['Make conversation public', 'Leave conversation']

**Comment by lesykm** [comment]
OK, found how to fix it:
1) Go to app manager and invoke force kill
2) Start Talk again and voile - chats are in place.
Looks like after upgrading to beta app was not restarted.

**Comment by mario** [comment]
Super strange. But glad it works now.
