### ISSUE TITLE
Messages are not marked as read

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#590]
- open up app
- see e.g. 3 conversations with unread messages
- go into one and read it
- go back, but still see the unread messages for this conversation

Only way to get them read is doing it via web.

(found with latest 6.1.2 and our server)

**Comment by mario** [comment]
Yup, I fixed this but it appeared again. Good thing it only happens with external signaling at least so not many are affected.

**Comment by tobiasKaminsky** [comment]
Do you mean 6.1.3, as 6.0.3 was released a while ago? ;-)

**Comment by mario** [comment]
Yup, changed :)
