### ISSUE TITLE
Tapping a file preview tries to open in browser if NC app is from F DROID

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/talk-android#591]
If the Talk app is from gplay and the files app is from fdroid, tapping a preview in talk opens tries to open in the bowser instead of the files app. 
If both apps are from gplay it seems it works correctly.

**Comment by mario** [comment]
Do you mean vice-versa? Because then it would make sense as the Talk in F-Droid doesn't support opening Files app due to this issue: https://github.com/nextcloud/talk-android/issues/534

**Comment by gradinaruvasile** [comment]
No.

Talk - gplay
Nextcloud - fdroid

I don't use Talk from fdroid as it is pretty much useless without the message notification features.

**Comment by schiessle** [comment]
I experienced the exact same problem, also Talk from gplay, Nextcloud from fdroid.

**Comment by mario** [comment]
Ah ok, so I know why this is. We check if the account that received the file exists/is configured within the Files app and if it is, we open the Files app.

In this case, we can't find the relevant account because the F-Droid and GPlay apps are signed with different keys so they cannot share accounts.

Long story short ... for now, please use both apps from the same place. Sorry about the inconvenience :-/

**Comment by tobiasKaminsky** [comment]
Talk app can do this
- check if Files app is installed (will be known even with "wrong" signature)
- check for account (will be none/empty with wrong signature)
- in this case Talk app knows that account might be there, but can't be sure, so it still just sends the intent. 

On Files side: if account is not found, I already show a warning.

**Comment by mario** [comment]
I know it can, just unsure if this is something I like from the UX
perspective...

Can SSO be used in this case to find out if an account exists?

**Comment by tobiasKaminsky** [comment]
It would only be for those that have the apps installed from different sources, and it has a proper UX, but not the best one, as it first has to open up Files app.
But e.g. when sharing something to WhatsApp it also checks within Whatsapp if the file is good to send, and not the "sending" app is checking it.



> Can SSO be used in this case to find out if an account exists?

I do not think so. We ask AccountManager to let user choose an account:
https://github.com/nextcloud/Android-SingleSignOn/blob/de69d46ee3c615484c1935b9f50977797af0992a/src/main/java/com/nextcloud/android/sso/AccountImporter.java#L87-L89

This is a hard-coded list prompt by Android, which then returns the chosen acconut.
We do this to prevent that any other app can figure out which accounts exists (without user interaction).

**Comment by mario** [comment]
Yea, but Whatsapp is different. Anyway I can do this even if I don't like it.

**Comment by mario** [comment]
I now check if signatures of the apps match and if they do, do an account check - otherwise I just open the Files app. 

That way I keep the usual UX when both apps share the signature.

**Comment by schiessle** [comment]
Thanks @mario I think this will be good from the UX. As @tobiasKaminsky said, that's the same UX the user have on all other apps as well. Also keep in mind that only a tiny faction will notice:

1. 80% will have both apps from the same appstore
2. 99% of all people who have installed both apps will also have configured the same account on both apps
3. 99% of the people join chats/calls in one of these instances and don't use the (nice!) feature to join a chat/call on a random server

Thanks for solving this @mario! :smile:
