### ISSUE TITLE
Add Samsung Galaxy S4 Mini (serranoltexx) to HW AEC blacklist

### ISSUE THREAD

**Issue by ericschdt** [nextcloud/talk-android#597]
I experience a bad feedback with a high pitch and echos when talking over the speakers as I guess HW AEC is not supported, just like at the S5 and S7.

**Comment by ericschdt** [comment]
Can you also add option in the app's settings, so that the users can (un)blacklist their device theirself?
That would help users who do not use the Stock ROM but a custom ROM, which solely does not support HW AEC.

**Comment by mario** [comment]
This I can take a look at, thanks for letting me know.

**Comment by mario** [comment]
How did you install this app? Since it shouldn't be supported officially? :)

**Comment by mario** [comment]
Ok, so I'm hoping it's this one - GT-I9195L :)

Let me know if not so I can update this for your specific model.

**Comment by ericschdt** [comment]
> How did you install this app?
I have installed via F-Droid.

>  Since it shouldn't be supported officially? :)
Not sure, what you mean. :-)

> Ok, so I'm hoping it's this one - GT-I9195L :)
The "L" stands for latinamerica. I use the general version "GT-I9195".
