### ISSUE TITLE
App to app not working

### ISSUE THREAD

**Issue by Simounet** [nextcloud/talk-android#598]
Hi there,
I've got a strange issue. I can use Talk with the app and the other person using the browser on the phone but I can't connect if both are using the app. I can't see them trying to connect through the TURN server.

**Comment by mario** [comment]
No idea. What app version, what Nextcloud version? :)

**Comment by Simounet** [comment]
Sorry about the lack of precisions.
Nextcloud 16.0.4
App 6.0.0beta3

**Comment by mario** [comment]
Sounds outdated. How did you end up on that version? o.O

Could you try latest stable which is v6.1.6?

**Comment by Simounet** [comment]
I get it from fdroid but I think I also tried with the one on Play Store.

**Comment by mario** [comment]
So it's been a while, sorry about that :( But did the newest versions help with this?

Otherwise it's quite impossible for me to troubleshoot connection problems.

**Comment by mario** [comment]
This slipped through, sorry. Are you still having issues?

**Comment by Simounet** [comment]
Yep. Still encountering the same issue.

**Comment by mario** [comment]
Mind getting me two test accounts and send them to mario@nextcloud.com?

**Comment by Simounet** [comment]
Done.

**Comment by mario** [comment]
Thanks @Simounet, I'll try to look into it tomorrow.

**Comment by mario** [comment]
@Simounet did I ever get back to you on this?

**Comment by Simounet** [comment]
@mario I gave you the access and I'm waiting since.

**Comment by mario** [comment]
@Simounet sorry about that, usually if I don't circle back in a week feel free to poke me again. Can you re-forward the access email pls?

**Comment by Simounet** [comment]
@mario It should be in your mailbox. :)

**Comment by mario** [comment]
Got it, thank you.

**Comment by Simounet** [comment]
Hi there,
Any news about my issue? Can I help you with something else?
Have a nice day and stay safe.

**Comment by mario** [comment]
Did you install any tracker on my computer? :P I was just looking at this issue :P 

So this week I'm heavily booked, but I can look next Monday again :-/ Can you just send me an email so I don't forget?

Thanks!

**Comment by Simounet** [comment]
Ah ah, my platform is tracker free! I promise.
No worries. I added this to my todo list.

**Comment by mario** [comment]
My apologies that this is getting delayed all the time - there are so many requirements and so much work every day and with only me being full time on it, its not very easy :-/

**Comment by Simounet** [comment]
I totally understand. No worries and have a nice day!

**Comment by Simounet** [comment]
Fixed by handling my IPv6 configuration correctly. Thanks to https://github.com/nextcloud/android/issues/7444 .
