### ISSUE TITLE
Add option to HW AEC un/blacklist app by user

### ISSUE THREAD

**Issue by ericschdt** [nextcloud/talk-android#599]
Can you add option in the app's settings, so that the users can (un)blacklist their device theirself?

Currently the list is hardcoded and removing / adding a device, also for testing purposes, requires a new release.

That would also help users who do not use the Stock ROM but a custom ROM, which solely does not support HW AEC.

Follow up question: If it's HW AEC blacklisted, will it fall back to a pure software based AEC solution?

**Comment by mario** [comment]
I will not do this mainly because its a niche solution to an even more niche userbase :(

But I'm happy to entertain a solution where I maintain the blacklist in the repo. Yes, it will fall back to software based AEC. So sorry, but closing this issue now :(

**Comment by ericschdt** [comment]
> I will not do this mainly because its a niche solution to an even more niche userbase :(

Oh, not even in a hidden expert setting? Too bad. ;-) 
Do you have an explanation why certain models don't support HW AEC, while others from the same brand and production line do?
How else can I, as a user, figure out if my device supports it without listening for echos or feedback? :)
