### ISSUE TITLE
Android app only for nextcloud 13 why?

### ISSUE THREAD

**Issue by hurrikan77** [nextcloud/talk-android#60]
Hi

I use the latest stable version nextcloud 12 with an rapsberry pi 3 (NextcloudPi Project).
I tried to install the talk app and it works great.

But if I try to use the android app it say it works only with nextcloud 13.
Is there any possibility to use the app with nextcloud 12 until Nextcloud 13 goes to stable?

Best regards

Hurrikan77

**Comment by mario** [comment]
Unfortunately no. We need features in 13 in order for app to work correctly. You can install Nextcloud 13 beta and test the app that way.

Sorry that I don't have better news!
