### ISSUE TITLE
Some emoji are not displayed correctly

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#601]
Some emoji are not displayed correctly in the message text.
Examples on the screen:

![obraz](https://user-images.githubusercontent.com/47037905/63427494-87032b80-c415-11e9-8ee2-4a73c5c91a14.png)

I don't know if the problem is with Talk, or keyboard or maybe the android version.

Android 6
Nextcloud Talk v6.1.6

**Comment by mario** [comment]
@Valdnet I'll do a beta today so please test this. Please also try to put one of those as the conversation name and post the screenshot of the conversation so I can see if it works when such an emoji is in the toolbar.

**Comment by Valdnet** [comment]
@mario Waiting for the new beta version 😉.

**Comment by Valdnet** [comment]
The error still occurs. Only the color of the envelopes changed.

![obraz](https://user-images.githubusercontent.com/47037905/64112338-66c55c00-cd87-11e9-97f7-c4cfd55df262.png)

**Comment by mario** [comment]
@Valdnet what about the conversation name in the toolbar?

**Comment by Valdnet** [comment]
@mario For the name of the conversation, not all emoji is available that appears on the keyboard for the conversation.
Sample screenshot:
![obraz](https://user-images.githubusercontent.com/47037905/64115270-6df06800-cd8f-11e9-97c7-5ee148e6aefd.png)

The ones I have available are displayed in the name of the conversation:
![obraz](https://user-images.githubusercontent.com/47037905/64115361-b1e36d00-cd8f-11e9-83b4-3c3785a4a9de.png)

**Comment by mario** [comment]
Ah yes. Could you open another issue for the toolbar & conversation name?

**Comment by Valdnet** [comment]
> Could you open another issue for the toolbar & conversation name?

@mario Open issue: #612 😉.
