### ISSUE TITLE
handshake failed

### ISSUE THREAD

**Issue by Waldhonig01** [nextcloud/talk-android#603]
Hello,
I have a similar problem to # 193:
Operating system Android 7 with EMUI 5.0.3
Since I renewed the certificates to RSA **and** ECDSA, I can´t log into the app "nextcloud talk" anymore. When i try, i get the error message "handshake failed". The main Nextcloud app connects and works just fine (i use the apps from the google playstore)

A login with a current Android system as well as Apple iOS 12 is successful (in both apps: Nextcloud and Nextcloud Talk)

In turnserver.conf, I refer to the RSA certificates cert.pem and privatekey.pem.
cipher-list = "ECDHE RSA AES256-GCM SHA512: DHE-RSA-AES256-GCM SHA512: ECDHE RSA AES256-GCM SHA384: DHE-RSA-AES256-GCM SHA384: ECDHE RSA AES256 -SHA384 "
I also tried it with:
cipher-list = "TLS CHACHA20-POLY1305-SHA256: TLS AES256-GCM SHA384: ECDHE-ECDSA CHACHA20-POLY1305: ECDHE RSA CHACHA20-POLY1305: ECDHE RSA AES256-GCM SHA512: DHE -RSA-AES256-GCM SHA512: ECDHE RSA AES256-GCM SHA384: DHE-RSA-AES256-GCM SHA384 "
Does somebody has any idea?

**Comment by mario** [comment]
Can you try deleting and readding an account pls?

**Comment by Waldhonig01** [comment]
First I enter the server address and already here comes the error message

**Comment by jookk** [comment]
I have this hanshake error too on android 7 samsung a3 2016.

**Comment by mario** [comment]
Can any of you provide a test account to mario@nextcloud.com?

**Comment by jookk** [comment]
Sent

**Comment by Waldhonig01** [comment]
also just sent, if still needed

**Comment by mario** [comment]
@Waldhonig01 your site is:

err_ssl_version_or_cipher_mismatch

Which is a server configuration problem.

And @jookk, I can login without any issues? :-/

**Comment by jookk** [comment]
Via Talk android 7? Wired then.

Dňa 25. augusta 2019 23:21:49 používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by jookk** [comment]
Turnserver has nothing to do with your problem.


Dňa 27. augusta 2019 11:54:22 používateľ Waldhonig01 
<notifications@github.com> napísal:

**Comment by Waldhonig01** [comment]
@jookk 
do you have any idea what I'm doing wrong ? I get a A+ from https://www.ssllabs.com when i check my server configuration.
result by Android 7: ok with TLS1.2>h2)

**Comment by jookk** [comment]
Try generate your config with this tool:
https://ssl-config.mozilla.org/

Dňa 27. augusta 2019 12:28:35 používateľ Waldhonig01 
<notifications@github.com> napísal:

**Comment by Waldhonig01** [comment]
I have found the mistake: 
After I had registered prime256v1 on the "ssl_ecdh_curve", i was able to log in successfully

**Comment by mario** [comment]
Awesome! :)
