### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#607]
nc 17b3
android talk v7b

Cant call, after call started only connecting
Messages are not notified on other end. 

On nc 16.04 
android Talk crashing after opening conversation

**Comment by mario** [comment]
What Android version are you using?

**Comment by jookk** [comment]
android 9

Somehow after few minutes it working.
So now: 
Calling working on local network, notifications working.
Messages are delivered, but not notified.

My turnserver worked fine till upgrade to nextcloud 17b3, is there any changes that I have to do in turnserver?

**Comment by mario** [comment]
When are you not notified? One2one or public/group notification?

**Comment by jookk** [comment]
one2one, public/group not tested

**Comment by mario** [comment]
Maybe you changed the config option? Can you send me a test acc?

**Comment by jookk** [comment]
I restarted coturn and now calling is working as before, local - public networks. So coturn working (must be bug on debian buster)

**Comment by jookk** [comment]
you have account, I didnt deleted it.

**Comment by mario** [comment]
Can't reset password - Request failed with status code 500

**Comment by jookk** [comment]
Sorry I cant create new account , no change password. Going to issue bug 
report to server

Dňa 30. augusta 2019 19:24:18 používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by szaimen** [comment]
> nc 16.04
> android Talk crashing after opening conversation
For me the same.

**Comment by jookk** [comment]
Wait a bit, mine working

**Comment by mario** [comment]
Found the issue and fixed. Will be in the next beta - thanks! :)
