### ISSUE TITLE
nextcloud talk does not follow theme color chosen

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/talk-android#608]
I changed color style to my nextcloud and in the nextcloud application it follows the color s elto which does not happen with talk application.  Is it possible to make the talk get back color quickly from the nextcloud application?  I attach example

Color app nextcloud 
![Screenshot_20190831-083913_Nextcloud](https://user-images.githubusercontent.com/35575744/64060327-4355b200-cbcb-11e9-99c2-0e8c70575eec.jpg)

in the talk application, the color remains blue

![Screenshot_20190831-083857_Nextcloud Talk](https://user-images.githubusercontent.com/35575744/64060344-6d0ed900-cbcb-11e9-9cd2-c258e8114e5e.jpg)

**Comment by mario** [comment]
Requested in https://github.com/nextcloud/talk-android/issues/250.
