### ISSUE TITLE
Crashing app v7.0.0b1 on Android 6

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#609]
Crashing the application when creating a new or opening a current conversation with the user.

Android 6
Nextcloud Talk v7.0.0b1

**Comment by mario** [comment]
Nextcloud version.?

**Comment by jivarson** [comment]
Happens here too on b1. Using android 9, nextcloud 16.0.4 and latest stable Talk backend. Sent feedback / logs through Google play. Happens in both dark and light app theme.

**Comment by Valdnet** [comment]
> Nextcloud version.?

Sorry.

Nextcloud 16.0.4
Talk 6.0.4
