### ISSUE TITLE
Use own avatar as icon for »Settings«

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#61]
Currently it’s a bland settings icon, but since it’s all about your own settings, having your own avatar there would be nice. This also show you how you appear to others, and will be good feedback for when we support multiple accounts.

cc @mario what do you think?

**Comment by mario** [comment]
Well, it's also global settings, but I agree ;)

We also support multiple accounts on Android :P

**Comment by AndyScherzinger** [comment]
Still can't compile the app anymore but my guess would be that something like this added to the `` could maybe work...

in `onAttach` add
```
if(menuSize > 0) {
                loadAvatarImage(menu.getItem(menuSize - 1));
            }
```
with 
```
private void loadAvatarImage(MenuItem item) {
        UserEntity userEntity = userUtils.getCurrentUser();
        String avatarId;
        if (!TextUtils.isEmpty(userEntity.getUserId())) {
            avatarId = userEntity.getUserId();
        } else {
            avatarId = userEntity.getUsername();
        }

        GlideUrl glideUrl = new GlideUrl(ApiUtils.getUrlForAvatarWithName(userEntity.getBaseUrl(),
                avatarId, true), new LazyHeaders.Builder()
                .setHeader("Accept", "image/*")
                .setHeader("User-Agent", ApiUtils.getUserAgent())
                .build());

        Target target = new SimpleTarget<Bitmap>(100,100) {
            @Override
            public void onResourceReady(Bitmap resource, Transition<? super Bitmap> transition) {
                item.setIcon(new BitmapDrawable(getResources(), resource));
            }
        };

        GlideApp.with(NextcloudTalkApplication.getSharedApplication().getApplicationContext())
                .load(glideUrl)
                .centerInside()
                .apply(RequestOptions.bitmapTransform(new CircleCrop()))
                .circleCrop()
                .into(target);
    }
```

while this is missing a dp to px conversion of course.

Since I can't compile, no idea if this might even work or just crash.

**Comment by AndyScherzinger** [comment]
@mario true that I also where I put the code so let's see if I get it to compile with your fix :)

**Comment by AndyScherzinger** [comment]
@mario I'll where to put it. Due to objects I need access to I guess it'll have to be `BottomNavigationController`.

**Comment by mario** [comment]
@AndyScherzinger if that's needed, fine.
