### ISSUE TITLE
Incomplete keyboard emoji for conversation name

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#612]
For the name of the conversation, not all emoji is available that appears on the keyboard for the conversation.
Sample screenshot:
![obraz](https://user-images.githubusercontent.com/47037905/64115270-6df06800-cd8f-11e9-97c7-5ee148e6aefd.png)

App:
Android 6
Talk Android 7.0.0b2
Nextcloud 16.0.4
Talk 6.0.4

**Comment by Valdnet** [comment]
@mario I didn't notice any change in version 7.0.0b3 on Android 6. Has something been changed?

**Comment by mario** [comment]
There should be an emoji field next to the name field?

**Comment by Valdnet** [comment]
Ok. Now I just noticed.

No emoji display.

![obraz](https://user-images.githubusercontent.com/47037905/64165856-2973d380-ce46-11e9-9c48-4becbd8fc8f6.png)

![obraz](https://user-images.githubusercontent.com/47037905/64165754-f4678100-ce45-11e9-9a12-40afc41cd5b7.png)

The correct display of emoji only in the conversation list.

![obraz](https://user-images.githubusercontent.com/47037905/64165891-3abce000-ce46-11e9-986d-1dbe376d9a2e.png)
