### ISSUE TITLE
cant delete conversation

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#615]
Android talk 7b3
After long click, menu appears, click delete conversation - confirmation and click to delete.
Nothing is done. Conversation is still there.

**Comment by mario** [comment]
What type of call? One2One, group, public?

What Nc version? :)

**Comment by jookk** [comment]
Nc 17b3
One2one

It was there in b2 at least
Dňa 3. septembra 2019 1:57:36 odpoludnia používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by mario** [comment]
Why did you close this? o.o

**Comment by jookk** [comment]
Issue occured two times. Yesterday and today to me. But now looking to 
conversation list and one to delete is now disappeared. So I closed.

Dňa 3. septembra 2019 15:44:17 používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by mario** [comment]
I see the issue :)

**Comment by mario** [comment]
(Btw. in Nc16 & 17 you can only leave one2one conversations, not delete - but yea, there's still a bug)
