### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by jrobinson52** [nextcloud/talk-android#616]
Should be fixed in v7.0.0beta2, so please test and re-open if that's not the case. Should be out in a few hours.

_Originally posted by @mario in https://github.com/nextcloud/talk-android/issues/604#issuecomment-527106472_

I have updated to v7.0.0beta2 and notifications are still non-functional. Is there anything I can do to provide you with more information?

**Comment by mario** [comment]
Can you look into Nextcloud logs and post parts that show that notifications are indeed sent?

**Comment by jrobinson52** [comment]
Do you mean the server logs or the app logs?

**Comment by mario** [comment]
Server logs.

**Comment by jrobinson52** [comment]
I do not know where to look for those. Also as a side note, I switched to another nextcloud instance hosted by someone else and notifications work there.

**Comment by mario** [comment]
Well, that might depend on how you configured your Nextcloud. Sorry but I can't be of any help if I don't have the logs.

**Comment by Ivansss** [comment]
@jrobinson52 Do you have the [notifications](https://github.com/nextcloud/notifications/) app enabled in your Nextcloud server?
You need that app to receive notifications in Nextcloud and push notification in mobile apps.

**Comment by jrobinson52** [comment]
@mario @Ivansss I am still working on getting this information. This is my company's Nextcloud instance that is giving me trouble. As a side note, the other employees attached to this Nextcloud instance receive notifications with the same beta version (although they're on Android 9).

**Comment by nickvergessen** [comment]
> I am still working on getting this information. This is my company's Nextcloud instance that is giving me trouble. 

Then please tell your sysadmins to take care of this. You proxying the information is not really useful. In case your sysadmin has questions they can open a support ticket in our customer support tool.

**Comment by jrobinson52** [comment]
We were not able to find any logs but it turns out logging into the app with an app key vs my username and password fixed notifications
