### ISSUE TITLE
Message not visible in one2one conversation

### ISSUE THREAD

**Issue by GLLM** [nextcloud/talk-android#618]
Hello !
I'm not sure this has been reported already or even fixed in the upcoming v7.

I'm using 
* NC 16.04 on Ubuntu 18.04 LTS + the app Talk 6.0.4 (setup w/ Coturn)
* Nextcloud Talk 6.1.6 on a Galaxy S8+ with Android 9.0

I've noticed that when I chat in one-to-one conversation :
* sometime the messages I _send_ to no appear in the conversation. When I get back to the list of conversation and correctly see the last one I send in the overview. If I get back in the conversation, those previously missing messages are now visible.
* when I _receive_ a message and Talk is not open, I do get the notification so I know what to expect. Then when I click on the notification, the correct conversation opens but I lack the msg I just received.
* sometime the messages I _receive_ do not appear in the conversation. I do get the notification, so I know what to expect ... but they are not visible. When I get back to the list of conversation and correctly see the last one I send in the overview. If I get back in the conversation, those previously missing messages are now visible.

In the end, if I quit the conversation and reopen it, I always end up getting all the expected messages, but it required additional steps ! Seems more like a GUI/refresh issue than a network/technical one I'd say :)

Not sure how I can provide more details or logs ...

Have you been reported such an issue ?

Thanks for the amazing work anyway !

GLLM

**Comment by Valdnet** [comment]
> sometime the messages I send to no appear in the conversation. When I get back to the list of conversation and correctly see the last one I send in the overview. If I get back in the conversation, those previously missing messages are now visible.

This problem sometimes also occurs with me.

**Comment by mario** [comment]
Could you check with 7.0 beta if it's not an issue @GLLM ?

**Comment by GLLM** [comment]
@mario 
I tested with beta3 of 7 :
#1 : sent message now appear properly (though it take ~2s) ✔️ 
#2 : when I receive a message and Talk is not open, I do get the notification so I know what to expect. Then when I click on the notification, Talk open and closes within the same second 🔴 
#3 : the few messages I managed to receive seemed OK ... TBC with more tests but looks OK 

thanks

**Comment by mario** [comment]
So closing this since it was fixed. I'll look into the crash if there's one in the play store.

**Comment by GLLM** [comment]
OK, thanks @mario  ! :)
