### ISSUE TITLE
Show Talk icon left of the »Nextcloud Talk« title in header, left-align text with content text

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#62]
Currently the header text is all the way to the left and there is no icon. We should display the Talk icon on the left next to the »Nextcloud Talk« header. :)

**Comment by mario** [comment]
Unsure. This hasn't been like that on Android since like ... forever? :)

**Comment by jancborchardt** [comment]
When apps have a sidebar. When they don’t, it looks strange to have the text unaligned. Signal for example has their logo there.

**Comment by mario** [comment]
Gimme a few days to think about it, and I'll come back to you.

**Comment by AndyScherzinger** [comment]
I'd also say don't add the logo.

While Signal is doing that and it is technically possible API wise (well, Signal is doing it...) it is something I haven't seen in any app except for signal (running >100 apps on my phone).

**Comment by tobiasKaminsky** [comment]
Imdb has it ;-)
But I also think that is not neccessary 🙃 

![screenshot_20180119-143050](https://user-images.githubusercontent.com/5836855/35153096-65e48c2c-fd25-11e7-8711-f62b02dc5adc.png)

**Comment by jancborchardt** [comment]
Hm :/ design-wise it looks very bland and text-heavy with only text and not the app-logo there. Also the header text is not properly aligned with the content text. Guidelines or not, this just looks very sloppy.

Of course I can't win a voting against 3 people as the only designer. ;) Maybe @nextcloud/designers have more input?

**Comment by mario** [comment]
Sorry, but this would go against everything I know in creating a good UI on Android, and especially against guidelines :(

**Comment by AndyScherzinger** [comment]
Well, I'd say aligning header and context shouldn't be an issue and is easy to fix and yes I also like alignment of UI elements but I still don't think adding a logo to the bar is the way to go.

**Comment by mario** [comment]
Well, the title actually IS aligned to the beginning of the content. 24dp, as is standard ;)

**Comment by mario** [comment]
![screen shot 2018-01-30 at 23 59 35](https://user-images.githubusercontent.com/5810/35596295-a93a467c-0619-11e8-8c77-0255704cb254.png)

**Comment by AndyScherzinger** [comment]
Just checked, yes fine by me. Is the whole icon area including whitespace 72dp then?

**Comment by AndyScherzinger** [comment]
Just asking since the left and right whitespace of the icon differ which indeed looks a bit off.

**Comment by mario** [comment]
Left whitespace - 24dp, icon 40dp, right 8dp.

**Comment by mario** [comment]
So yup, 72 :)

**Comment by mario** [comment]
And yes, it might be 24-24-24, but then the icons would maybe be too small.

**Comment by pixelipo** [comment]
AFFAIRS, in material design, left edge of the header is reserved for hamburger/Back icon, depending on context.

The only few apps on my phone that have a logo in header are those that are not religious about Material.

If there's a plan to add a sidebar in the future, then it's header is a good location for the icon
