### ISSUE TITLE
V7.0.0 Beta4 clicking on chats scrolls from the top down

### ISSUE THREAD

**Issue by szaimen** [nextcloud/talk-android#620]
V7.0.0 Beta4 clicking on chats scrolls from the top down. (You can see the fetching of the chat)
You have to wait until everything has loaded. Then you can write something.

**Comment by szaimen** [comment]
BTW: caching the chats would be much better! Also for using the app offline!

**Comment by mario** [comment]
Will be fixed in beta5, thanks for reporting.

**Comment by Valdnet** [comment]
@mario I thought it should be this way :smile:. It's a bit annoying  :grin:.
