### ISSUE TITLE
No information about the end of the incoming call

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#621]
There is no information about the end of an incoming call from another user.

![obraz](https://user-images.githubusercontent.com/47037905/64432471-e96a5600-d0bc-11e9-9e24-30ee13c8fdd7.png)

App:
Android 6
Talk Android 7.0.0b4
Talk 6.0.4
Nextcloud 16.0.4

**Comment by mario** [comment]
Not sure I understand the issue?

**Comment by Valdnet** [comment]
@mario Information about the end of a call does not always appear.

![obraz](https://user-images.githubusercontent.com/47037905/64476884-c1e6bc80-d194-11e9-8af4-2d4e2721224c.png)
