### ISSUE TITLE
Call screen shown even if the call has ended when switching airplane mode off

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/talk-android#625]
Steps to reproduce: 
* Switch airplane mode on;
* Make somebody call you and hang up;
* Toggle airplane mode off and unlock the phone.

Expected behavior: 
You see a missed call notification.

Actual behavior: 
the call screen pops up for an instant and then disappears. 

Phone: Huawei p20 pro, stock OS 
version 7.0.0 Beta 4

**Comment by mario** [comment]
@Ivansss to check the same on iOS.

**Comment by mario** [comment]
Happens only with one2one calls because we automatically show the call screen. Needs a server-side solution probably.

**Comment by nickvergessen** [comment]
I guess this should be fixed by the "is someone still in the call check"?

Is it still happening @ma12-co
