### ISSUE TITLE
Emoji in push notifications

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#627]
Incorrect emoji display in push notifications.

1.

![obraz](https://user-images.githubusercontent.com/47037905/64866521-df57d280-d63b-11e9-96fb-6d94c2e60c7f.png)
Examples:
![obraz](https://user-images.githubusercontent.com/47037905/64866819-77ee5280-d63c-11e9-91f3-8a14d50f28b6.png)

2.

![obraz](https://user-images.githubusercontent.com/47037905/64866576-f8f91a00-d63b-11e9-8b55-27d887cbd611.png)
Examples:
![obraz](https://user-images.githubusercontent.com/47037905/64866847-876d9b80-d63c-11e9-8cc0-eae3a856784d.png)

App:
Android 6
Talk Android 7.0.0b4
Nextcloud 16.0.4
Talk 6.0.4

**Comment by mario** [comment]
Check with beta5 pls.

**Comment by Valdnet** [comment]
The issue still exists

**Comment by mario** [comment]
https://github.com/android/user-interface-samples/issues/80

Sorry about that :(
