### ISSUE TITLE
Profile picture

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#628]
Would be great to have ability to change profile picture via Talk android. 
![Screenshot_20190913-212310-picsay](https://user-images.githubusercontent.com/11217085/64889705-2fe82380-d66e-11e9-86be-35dee153e0db.png)

**Comment by mario** [comment]
Not supported by the API. Please file a server issue.

**Comment by markus2330** [comment]
My girlfriend ran into this, it was disappointing for her that she could not change the profile picture.

@jookk did you already create a server issue?

If not: Should it be done on https://github.com/nextcloud/spreed or somewhere else?

**Comment by mario** [comment]
@markus2330 probably here: https://github.com/nextcloud/server

**Comment by markus2330** [comment]
Does https://github.com/nextcloud/server/issues/7744 cover everything you would need?

**Comment by mario** [comment]
That ticket mentions only administrators. One should be able to update their own profile pic as well.

**Comment by jookk** [comment]
No, I didnt. Beautiful feature 👍✨
