### ISSUE TITLE
Dark mode / beta: wrong background color on chat

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#629]
![image](https://user-images.githubusercontent.com/5836855/64919000-e4389580-d7a5-11e9-82d2-023898aca814.png)

To read this properly on mobile screen I had to manually switch to dark mode.

**Comment by mario** [comment]
Do you have a system-wide dark mode?

**Comment by tobiasKaminsky** [comment]
Indeed, I was not aware of. 
When I set it manually to "light" then it is ok, but setting it to "dark" I get above situation.
There is also an automatic mode, which will then lead to the same problem in upcoming night, I guess.
