### ISSUE TITLE
Use link-icon instead of world globe for public calls

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#63]
To be symmetric to the icons we use on the server and iOS, we should use the link icon instead of the globe:
![screenshot from 2018-01-12 22-27-50](https://user-images.githubusercontent.com/925062/34895889-e9e9cb92-f7e7-11e7-97a6-491fa74a63d8.png)
https://material.io/icons/#ic_link

**Comment by mario** [comment]
Absolutely.
