### ISSUE TITLE
Icon on dark mode is scraggy

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#630]
![image](https://user-images.githubusercontent.com/5836855/64920133-ed306380-d7b3-11e9-8308-78f520d1382a.png)

- choose dark mode
- have a conversation without icon / with default icon

**Comment by mario** [comment]
Do you see this issue in the newest version, and if so, where exactly?

**Comment by tobiasKaminsky** [comment]
With 7.0.5 it is now looking good.
It was on conversation overview.
