### ISSUE TITLE
Click on push notification lead to null

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#631]
![image](https://user-images.githubusercontent.com/5836855/64920152-308ad200-d7b4-11e9-8b79-10a490285102.png)

Happened 2x with latest beta (7.0.0 beta5).
- receive a push notification
- click on it

**Comment by jookk** [comment]
If you mind receiving new message notification, mine working fine. 
Click to notification opens conversation.

**Comment by tobiasKaminsky** [comment]
Normally push nofification were working, but now I have it from time to time that it shows these "null".

**Comment by mario** [comment]
Should be fixed in stable once its out.
