### ISSUE TITLE
Crash app when conversation to 2 users

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#632]
Steps I:
1. Open a conversation with 2 users.
2. Go to conversation info.
3. **Crash app**.

Steps II:
1. Open a conversation with 2 users.
2. Enter with conversation.
3. **Crash app**.

App:
Android 6
Talk Android 7.0.0b5
Nextcloud 16.0.4
Talk 6.0.4

**Comment by Valdnet** [comment]
This only happens when an old unnamed conversation is created.

**Comment by mario** [comment]
Not sure I understand?

**Comment by Valdnet** [comment]
@mario If you have ever created a conversation on an older version of Talka that does not have the **"Conversation name"**, then after opening and closing the conversation or "Conversation Information" the app crashes.

**Comment by mario** [comment]
Should be fixed, if not let me know!
