### ISSUE TITLE
Unread messages counter appears when it shouldn't

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#633]
**Sometimes**, after writing a message, your message does not appear.

Steps:
1. Create a conversation.
2. Write a message.
3. **Sometimes** your message does not appear.
4. Exit the conversation.
5. Information on the unread message is displayed.

App:
Android 6
Talk Android 7.0.0b5
Nextcloud 16.0.4
Talk 6.0.4

**Comment by jookk** [comment]
I have it too.
Talk b5

**Comment by mario** [comment]
This should be fixed in stable 7.0, if not (should be released today) please send me two test accounts at mario@nextcloud.com. Thanks!

**Comment by Valdnet** [comment]
In version 7.0.4 my messages also appear as unread.

![obraz](https://user-images.githubusercontent.com/47037905/65879932-34604c00-e391-11e9-8df2-87efc5ce79fd.png)

**Comment by mario** [comment]
Can you try 7.0.5?

**Comment by Valdnet** [comment]
After receiving a new message from the user and sending his message, information about the new message from the user appears, which is really my message.

Steps:

1. Receive a message from the user.
2. Reply to the message.
3. Information about **unread messages** appears.

![obraz](https://user-images.githubusercontent.com/47037905/65891996-d12ce480-e3a5-11e9-95bf-67381e097e67.png)

App:
Android 6
Talk Android 7.0.4 and 7.0.5
