### ISSUE TITLE
Hide "PROCEED"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#635]
I suggest to hide "PROCEED" when it is not entered:

1. Conversation name:

![obraz](https://user-images.githubusercontent.com/47037905/65223333-44d71380-dac1-11e9-8519-05dafd1cec58.png)

2. Link conversation:

![obraz](https://user-images.githubusercontent.com/47037905/65223386-620be200-dac1-11e9-92fb-1e0264e8e85f.png)

Just as it is when choosing a conversation user. "DONE" appears only when the user is selected.

App:
Android 6
Talk Android 7.0.0b5

**Comment by mario** [comment]
@jenniferpiperek thoughts on this?

**Comment by mario** [comment]
The UI for creating a conversation will change, while I'm unsure if we should hide buttons as this would cause bottom sheet to resize as we re-enable it, so closing for now.

**Comment by Valdnet** [comment]
I suggest the gray color "PROCEED" if no name or link is provided.
