### ISSUE TITLE
Crashing app - push notifications

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#641]
When reading messages from push notifications, the application crashes.

Steps:

1. Receiving a push notification with a message.
2. Tap on the push notification to read the message.
3. **Crash app**.

App:
Android 6
Talk Android 7.0.0

**Comment by hobesman** [comment]
I'm on 7.0.5 and experiencing this problem. When I open a conversation that has a new message, the android app crashes. I can then reopen it and read the message, but the first time opening a conversation after a new message, it crashes the app. Is this something different, or is this problem resurfacing, or not yet fixed, or...?

Thanks for any info.
