### ISSUE TITLE
Description change "Manual" and adding description for "Lobby"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#645]
I suggest changing the description in "Webinar" - "Start time" from "Manual" to another which would inform about the lack of date and time setting, e.g .:
- Unknown
- Not set
- None

![obraz](https://user-images.githubusercontent.com/47037905/65760998-52724600-e11e-11e9-859a-e2fca92d699d.png)

The current description only informs about the possibility of setting the time and time manually.
Additionally, you should add a description of the "Lobby" function, as it is for: "Important conversation" and "Mute calls", e.g .:

- Sets the date and time of the start of the webinar

![obraz](https://user-images.githubusercontent.com/47037905/65761218-ab41de80-e11e-11e9-9410-95d5aeb3d23f.png)

**Comment by mario** [comment]
@Ivansss @nickvergessen as we probably want to coordinate this across the platforms?

**Comment by nickvergessen** [comment]
Well we just show the empty input with the placeholder "Start time" in the web

**Comment by mario** [comment]
"Manual" changed to "Not set"

**Comment by Valdnet** [comment]
@mario And what about the function description "Lobby"?

**Comment by mario** [comment]
I don't know what to put there :(

**Comment by Valdnet** [comment]
Maybe:
- The lobby for webinar will be enabled

**Comment by Valdnet** [comment]
@mario In version 8.0.0 b1 there are no visible changes to the descriptions:

- Not set
- Calls and message notifications will be shown even while in Do not disturb mode (follows system "Allow priority interruptions only" configuration)
- description of the "Lobby" option

Is this a mistake or should we wait for newer versions?

**Comment by mario** [comment]
@Valdnet it was postponed for 9.0.
