### ISSUE TITLE
No translation for "All" when choosing mention

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#646]
There is no Transifex translation of the word "All" that appears when choosing mention.

![obraz](https://user-images.githubusercontent.com/47037905/65762254-e80ed500-e120-11e9-97c3-81efb75233f7.png)

**Comment by mario** [comment]
As far as I know, this won't be translated but dunno. @nickvergessen ?

**Comment by nickvergessen** [comment]
yeah, it's `all` and autocomplete works with `all` and `<room name>`
