### ISSUE TITLE
Notification settings

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#649]
Notification settings for a conversation with a user are not working properly.

- Setting "Important conversation" to enabled does not send "Do Not Disturb" notification.
- Setting "Mute calls" to enabled does not mute.

App:
Android 6
Talk Android 7.0.2

**Comment by Valdnet** [comment]
> Notifications in this conversation will override
>         Do Not Disturb settings

In my opinion, this description of the function is hardly understood by the user.

**Comment by mario** [comment]
@nickvergessen and @nextcloud/designers for thoughts.

**Comment by skjnldsv** [comment]
It should be discussed with iOS and server team. So we have the same settings across all the apps/web :)

**Comment by nickvergessen** [comment]
First thought: remove the important conversation setting form the UI until we handle that topic across all platforms

After looking at the screen, I would expect the following situation for a group conversation:

## Default
Normal text: No notification
Mention: Notification
Call: Notification

### Mute calls
Normal text: No notification
Mention: Notification
Call: No notification

## DND
Normal text: No notification
Mention: Notification without sound/vibrate
Call: Notification without sound/vibrate

### DND + Mute calls
Normal text: No notification
Mention: Notification without sound/vibrate
Call: No notification

## Important
Normal text: No notification
Mention: Notification
Call: Notification

### Mute calls
Normal text: No notification
Mention: Notification without sound/vibrate
Call: No notification

**Comment by nickvergessen** [comment]
Basically Important makes a conversation to behave like your phone is not in DND

**Comment by mario** [comment]
@nickvergessen while I'd usually agree on the account of feature parity the issue is that neither iOS or Web *can* have this particular feature as they either don't have the technical means (iOS) or don't have DnD (iOS).

As for "Mute calls" - why would it impact texts and mentions?

That being said, I can change mute calls to completely not show notifications instead of silencing them.

**Comment by Valdnet** [comment]
In my opinion, the "Important conversation" function is unnecessary and confuses the user.
As for DnD, I agree with @mario. Not all systems have this function. Most users probably don't really know what's going on.

As for muting, I would separate the options "Mute calls" and "Mute conversations". The user can choose what to mute. If the user wants to completely mute the phone, can the computer do it from the system level.

**Comment by jancborchardt** [comment]
I’d also agree with @nickvergessen here:

> First thought: remove the important conversation setting form the UI until we handle that topic across all platforms

If we can’t have it in e.g. iOS cause the tech isn’t there yet, let’s focus on things where we can have feature parity.

(iOS also has this concept of "VIP" at least in Mail, but not sure if they use it anywhere else. If anything, it could be expected that favorited conversations are important, but yet another setting is too complex to understand.)
