### ISSUE TITLE
Push-to-talk

### ISSUE THREAD

**Issue by HammyHavoc** [nextcloud/talk-android#65]
Hey all,

Would love to see push-to-talk support come to Talk; really promising. :- )

**Comment by mario** [comment]
Would this not be just a gimmick? :) What's the practical idea behind it?:)

**Comment by HammyHavoc** [comment]
Not in any way... for one thing, it's a great way of eliminating noise and feedback, and on group calls it's a complete no-brainer, especially if any of your employees are working in the field and are outside or in a generally noisy environment. This is a standard with most enterprise VoIP systems. Push-to-talk is a cornerstone of enterprise voice communication. This is why you need to hold a button to use a walkie-talkie even though plenty are digital and duplexed now.

In my particular workplace, we tend to keep VoIP calls open between a group and with the press of a key, people can chime in with an issue, a question, or a status report.

This is something that would be the difference between us being able to consider Nextcloud and going with a competing product.

You should really take a look at what's already on offer out there to get an idea of must-have features like talker priority and rejoining a call if it disconnects:

- http://www.verizonenterprise.com/products/mobility/workforce-productivity/push-to-talk-plus/
- https://getsonica.com/enterprise
- https://business.bell.ca/shop/enterprise/push-to-talk-service

**Comment by mario** [comment]
@HammyHavoc 

- ability to mute others should be in the apps eventually, I think web interface already has this
- rejoining call if it disconnects - on the agenda

I'm interested in implementing this, but I'd like to know your take where would you put it in the interface? (the big TALK button). Would it be a config option? Something else?

**Comment by HammyHavoc** [comment]
@mario 

I'm not sure if muting others is quite what I have in mind when talking about PTT; your implementation of muting implies I don't want to hear the other party, that's not the case. PTT is similar to everybody having their own mic muted by default, they then unmute it with the depression of a key or holding their finger on a certain virtual button on the screen, it then goes back to muting their mic after releasing their finger on the button.

Ideally, there would be the ability to map this button to a keystroke, so a user could use a hardware button or a hardware keyboard.

Awesome! :- )

PTT would be disabled by default on a server-level (keep the UX clean out of the box, it makes Nextcloud look simple and pretty), but for those who need it, it's there.

In terms of UX and where to put it, when on a video call, touching your own video feed should unmute you and ideally give a visual indication that audio is indeed sending (glow around the video box or avatar ala Skype?). On a non-video call, anywhere towards the bottom would be great (within thumb reach, people are going to be pressing it a lot every day).

**Comment by bryandesrosiers** [comment]
Although aimed for Gamers, Discord does Push To Talk pretty darn well. Even on their mobile platforms, PTT is able to be utilized. Only thing lacking is a potential floating PTT button for when out side of app, similar to Facebook's Messenger app.

Personally, I use PTT religiously. So much that a prospecting software WILL lose my interest if no PTT function exists.

End of the day, the way I look at it is, if there is a function that allows you to block annoying ambient noises from constantly being in a Voice Discussion, it's just that - annoying.

**Comment by mario** [comment]
@HammyHavoc let's first implement this on Android, and if it works like you want it to, then we can poke @nextcloud/talk and @nextcloud/talk-ios. Sounds good? :)

**Comment by mario** [comment]
cc @nickvergessen @Ivansss

**Comment by HammyHavoc** [comment]
@mario Awesome! :- )

**Comment by nickvergessen** [comment]
Push to Talk sounds nice to me, if it's easy enough I'd do it in the mobile apps.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers to bring up a nice UX for this.

**Comment by mario** [comment]
My thoughts:

- functionality would be enabled per-room (in a menu)
- you'd still have the option to have microphone ON all the time in a call, disabling microphone shows PTT button again
- this is based on clients, so someone could STILL be in the call with its microphone on, as said above
- button would be rounded and with mic inside located at bottom right, emiting glow when sending audio

Let me know if this works, and if it does, you'll have it in 1.2.

**Comment by HammyHavoc** [comment]
@mario This sounds fantastic. I'm impressed by how fast you guys move. :- ) 👍

**Comment by MorrisJobke** [comment]
> My thoughts:
> 
> functionality would be enabled per-room (in a menu)
> you'd still have the option to have microphone ON all the time in a call, disabling microphone shows PTT button again
> this is based on clients, so someone could STILL be in the call with its microphone on, as said above
> button would be rounded and with mic inside located at bottom right, emiting glow when sending audio
> Let me know if this works, and if it does, you'll have it in 1.2.

Could we get some feedback from @nextcloud/designers here to have the same feature set on all devices/platforms.

**Comment by mario** [comment]
New thoughts: add a PTT button next to microphone if disabled. Keeps UI consistent, and there's no room setting so makes it simpler.

**Comment by mario** [comment]
Or even better! Long press and hold on the muted microphone initiates PPT!

This gets better by the second!

**Comment by HammyHavoc** [comment]
Love the elegance and simplicity of that. Intuitive. :- ) 👍

**Comment by mario** [comment]
Thanks to the awesome feedback from you all, this will be in 1.1 which means in say 3-4 weeks rather than in 1.2 :) Thanks folks!

**Comment by mario** [comment]
Majority of this has now been implemented, some details remain in order to improve animations and stuff.

**Comment by HammyHavoc** [comment]
@mario This might be the fastest feature implementation I've seen for a few years! Thank you! Will be looking forward to trying this on launch... now we have a far more compelling argument to roll out Nextcloud. :- )

**Comment by mario** [comment]
@HammyHavoc :)

Sorry that it won't be released sooner - some things just need to go in 1.1, so don't want to rush it.

**Comment by tobiasKaminsky** [comment]
> Long press and hold on the muted microphone initiates PPT!

Is this somehow shown to the user? Maybe as text like we have on initial FAB on nextcloud files? Otherwise I would never expect that long pressing this button allows me to speak.

**Comment by mario** [comment]
@tobiasKaminsky to me it's quite intuitive and judging by the @HammyHavoc comment he likes it too. Saying that, there will eventually be an animated introduction into this feature :)

**Comment by mario** [comment]
(I will however consider putting PTT text underneath the icon, let me just think about it)

**Comment by mario** [comment]
@HammyHavoc can you mail me please? mario AT nextcloud DOT com

**Comment by MorrisJobke** [comment]
@mario could you open a ticket in the talk repo to implement it there too

**Comment by mario** [comment]
@MorrisJobke absolutely.

**Comment by mario** [comment]
@MorrisJobke:

https://github.com/nextcloud/spreed/issues/603
https://github.com/nextcloud/talk-ios/issues/42

**Comment by mario** [comment]
@HammyHavoc can you mail me please? mario AT nextcloud DOT com :) In case you haven't seen my original request.
