### ISSUE TITLE
no sounds/notification if installed from f-droid

### ISSUE THREAD

**Issue by markus2330** [nextcloud/talk-android#650]
I use talk-android from f-droid and generally I am very happy: video calls work with good quality.

What is, however, not so satisfactory is that I do not get any notification if someone writes me a message or calls me. I know that there are some limitations because of the missing "google push notifications" but I would like to have at least a sound (or whatever the settings say, see #649) whenever talk-android receives a message/call.

**Comment by markus2330** [comment]
To clarify: unlike #257 here it is only about playing sounds whenever the message arrives (which might be with an arbitrary delay).

**Comment by mario** [comment]
It's pretty much the same request - no "push", no notification of any kind, including the sound :)

Sorry about that!

**Comment by markus2330** [comment]
Ohh, what a pity.

Is it maybe possible to automatically accept audio/video chats if I already have an open chat with that person? That would also more or less solve my problem.

**Comment by mario** [comment]
Oh. You mean when you have a chat open? I can definitely get you sound then
on each new message but I am not sure how useful that is since you already
ahve it open and actively using it?

**Comment by markus2330** [comment]
Yes, when I have the chat open. I imagine it to be useful: e.g. if I charge the phone, the chat could be open permanently and the other person might call after an hour or so. Then I do not need to poll if the person calls, I will simply hear someone speaking. Even better would be if it also works with the screen lock on.

But in any case it is more of a temporary solution. A proper push solution is better. So do not put too much effort into this if you already know how to do proper notification.
