### ISSUE TITLE
post image in chat

### ISSUE THREAD

**Issue by markus2330** [nextcloud/talk-android#651]
From the web-client one can easily post an image (available within Nextcloud as file) into the chat. Can you also support this in talk-android?

Different to #306 my use-case is that the picture is already uploaded to Nextcloud.

**Comment by mario** [comment]
It's there already. Which version of the app are you using?

**Comment by markus2330** [comment]
The latest of f-droid: v6.0.0beta3 (5 month old)

**Comment by mario** [comment]
Support for this was added in stable v6.0. Anyway, F-Droid should soon be building 7.0 so this issue will be resolved :)

**Comment by markus2330** [comment]
Thank you!
