### ISSUE TITLE
importing account from NC app fails

### ISSUE THREAD

**Issue by DudleyDursley** [nextcloud/talk-android#652]
I tried to import my account from the NC files app but it failed. After choosing 'import account' and selecting my account, there was a spinning blue circle on a dark gray background, then a login button for maybe one second and finally the normal login page asking for a username and a password.

Nextcloud 17 (Docker) + Talk 7.0.0
Nextcloud (Playstore) 3.8.0
Talk (Playstore) 7.0.2
Android 8.1.0

This might be related to #545.

**Comment by mario** [comment]
Actually this is normal behaviour. Since the password cannot be imported from the NC Files app (due to reasons of working push) you're expected to re-enter your password.

Sorry about the inconvenience.
