### ISSUE TITLE
Switching between Wifi and Mobile network

### ISSUE THREAD

**Issue by alirasol** [nextcloud/talk-android#653]
The call stops when switching from Wifi to 4G network and vice versa. One caller has to end the call and join again to get it working again.

**Comment by jookk** [comment]
I think, handover? is not possible.
Your network is changed (ip)

**Comment by alirasol** [comment]
I am no developer or expert, but all other services that I use are working when switching between networks. It says "reconnecting" and voilà.

**Comment by mario** [comment]
This should work actually. I'll take a look.

**Comment by mario** [comment]
Duplicate of https://github.com/nextcloud/talk-android/issues/135
