### ISSUE TITLE
Call Notification keeps playing after answering the call

### ISSUE THREAD

**Issue by alirasol** [nextcloud/talk-android#654]
After changing the notifications sound for the incoming call, and answering, the app keeps playing the old sound for about one or two seconds after taking the call.

**Comment by mario** [comment]
Hi,

thanks for the report. The "default" incoming call sound is actually also used as a ringing sound which is why you experience this. Until I find a better properly licenced "ringing"/"calling" sound this is how it is :(

Sorry about the inconvenience!

Cheers,
Mario

**Comment by alirasol** [comment]
I can live with it. I shouldn't really complain because you are doing a great work

**Comment by mario** [comment]
@alirasol it's not a complaint - feedback like yours help us shape the software better to suit people like you! Maybe you'd like to help me out by finding a nice ringing/calling sound under a good enough licence? :)

**Comment by alirasol** [comment]
Of course

**Comment by nextra06** [comment]
"Until I find a better properly licenced "ringing"/"calling" sound" - I don't understand this statement. Maybe I am missing something but aren't there loads of royalty free sounds which can be used?

Sorry for being dumb

**Comment by mario** [comment]
Find me one? :)

**Comment by nextra06** [comment]
On it, Sir.

**Comment by nextra06** [comment]
www(dot)zapsplat(dot)com/sound-effect-category/ambient/

www(dot)pacdv(dot)com/sounds/domestic_sounds-2(dot)html - Has 3 different ringers

if these don't work (do not fit the licensing) maybe I can make a custom ringer and send that to you.
I am pretty bad at audio effects though but can manage a ringer.
