### ISSUE TITLE
switch between cameras broken

### ISSUE THREAD

**Issue by username72764274** [nextcloud/talk-android#655]
In previous versions it was possible to toggle a camera switch by clicking on the camera preview. This doesn't work for me with nextcloud talk android v7.0.5 
Any reasons why this functionality has been removed? Is there any other way to trigger a camera switch?

**Comment by mario** [comment]
I will take a look, thanks for letting me know. It should work!

**Comment by dadosch** [comment]
Can confirm that it is Broken in the latest Version.

**Comment by tigernero79** [comment]
ok i'll wait for bug resolution

**Comment by b3** [comment]
Is there a compiled version I can get somewhere with this bug fixed?

**Comment by gerroon** [comment]
LIneage OS 14.1 Samsung , Talk 7.0.8 no back camera I can confirm
