### ISSUE TITLE
Not necessary to show sender names in conversation list for 1on1 conversations

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#658]
The conversation list shows a nice preview of the last message in a conversation.

For group conversations it’s good to see the "Sender:" prepended for context. For a 1on1 conversation it’s not really needed, and often takes away a lot of space from the message preview. :)

@mario if you describe where this would need to be changed, this could make a nice "good first issue". Thanks!

**Comment by mario** [comment]
But then it's not entirely obvious if my message is thhe last one or from
the other person?

**Comment by jancborchardt** [comment]
Right, so how others do it:
- WhatsApp, Instagram and Viber: show the name only for messages in groups, not for 1on1
- Facebook Messenger and Twitter: show the name for group messages, and for 1on1 they show only "You: " prepended if the last message was from you, and nothing if the message was from the other person.
- Signal: don’t show anything, not even in groups (assume they will add it for groups at least though)

The solution Facebook Messenger and Twitter use seems to be a great balance. What do you think?

**Comment by mario** [comment]
Yup, can do.
