### ISSUE TITLE
App name too long on Android 10

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/talk-android#659]
![Screenshot_20191019-081545](https://user-images.githubusercontent.com/3404133/67147547-30d82a80-f296-11e9-9399-bbb6b6884e48.png)

The app name is too long to be fully shown on Android 10 running on a Pixel 3a. As I didn't have this issue on my old device I guess it is kind of vendor/version dependent. However I think we should align with the other nextcloud related apps and maybe just call it "Talk".

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Yep, at least for the home screen / app list icons, "Talk" is enough.

**Comment by mario** [comment]
@nickvergessen thoughts?

**Comment by ma12-co** [comment]
> In the stores it should of course still be called "Nextcloud Talk".

IMO there's no need for this as you can see the author right underneath. I think it's just cleaner if we omit it.

![Screenshot_20191021_095526_com android vending](https://user-images.githubusercontent.com/26852655/67186863-3a25dc00-f3e9-11e9-9521-4974bd3a00ff.jpg)

**Comment by nickvergessen** [comment]
Apps with similar problems on my phone (Android 9):
* Messag… (Messages - default SMS app)
* Play Bo…
* Play Mu…
* Play Mo…
* Play Ga…
* Play Sto…
* Prime V…
* PS Mes…

**Comment by ma12-co** [comment]
> Omitting is a problem, as the description/author field is not considered on search.

We could use search tags both on android and iOS, but we should confirm that the search results are not affected. 
Anyway the real issue the home screen, this one is no biggie :)

**Comment by juliushaertl** [comment]
@ma12-co The app store description seems to be independent from the home screen icon, so that should not be an issue:

![image](https://user-images.githubusercontent.com/3404133/67191403-d2c05a00-f3f1-11e9-91b3-2f20cdbece20.png) 
![image](https://user-images.githubusercontent.com/3404133/67191423-dce25880-f3f1-11e9-8ca3-4b56fd9862c8.png)

**Comment by ma12-co** [comment]
True for android, but apparently they don't allow this in iOS. cc @Ivansss

**Comment by Ivansss** [comment]
It looks like that's also possible on iOS.

This is what Apple says:
`App names in iTunes Connect and as displayed on a device should be similar, so as not to cause confusion`

So I guess showing "Nextcloud Talk" in the App Store and "Talk" as app display name should be fine.

@karlitschek

**Comment by karlitschek** [comment]
Hmm. 'Talk' is way less recognizable than 'Nextcloud Talk'. But I guess if we run out of space then we have to do it. So let's try if Apple accepts 'Talk' below the app and 'Nextcloud Talk' in the AppStore then we should do it. Let's try

**Comment by mario** [comment]
@Ivansss let me know of the outcome once you get to this - thx.

**Comment by jancborchardt** [comment]
@mario as it's a problem on both Android and iOS, and we know it's possible to fix on Android for sure, it would be good to do at least that. No reason to have iOS uncertainty blocking that. :)

**Comment by nickvergessen** [comment]
No, as per https://github.com/nextcloud/talk-android/issues/659#issuecomment-544498198 we only do it for both or none

**Comment by jancborchardt** [comment]
@nickvergessen I think @karlitschek was only referring to how we do it for iOS there? Frank, I doubt you think this looks good (how it is on Android):
> ![Screenshot_20191019-081545](https://user-images.githubusercontent.com/3404133/67147547-30d82a80-f296-11e9-9399-bbb6b6884e48.png)

**Comment by nickvergessen** [comment]
![Screenshot_20191026-161416~2](https://user-images.githubusercontent.com/213943/67620859-c2521a00-f80b-11e9-9df7-ec592c2b95d3.png)

Well there seem to be reasons for that. Im at least in favore of having both clients im Sync. Having two different app names is way to confusing

**Comment by stefan-niedermann** [comment]
Well, "Play" is way shorter than "Nextcloud". This allows one to read 2-3 letters of the actual app name. If we do this with Nextcloud each apps label will just say "Nextcloud..." without any additional letters.

So it is way harder to distinguish between them as it is with the Play apps.

**Comment by jancborchardt** [comment]
Just talked about it with @karlitschek and we said:
If possible, we should use "Nextcloud Talk" because that is better branding, like for the app store listing.
But if it’s cut off, e.g. to "Nextcloud …" then it of course does not make sense and we should only use "Talk", like for below the icon.

Android is not blocked by what we can do on iOS here.

**Comment by nickvergessen** [comment]
Let's hope the unexperienced users will still find it in their app list when it's all of a sudden at T for Talk instead of N dor Nextcloud .... But okay.

So let's o @mario @ivansss

**Comment by Bugsbane** [comment]
nTalk?... nDeck? nNews? nNotes?  (Yes, I'm kidding. Please don't take this seriously!)
