### ISSUE TITLE
Connexion initialized : no sound no video only with app

### ISSUE THREAD

**Issue by ernesst** [nextcloud/talk-android#66]
First of all thanks for the app and talk.

I'm running right now on nextcloud 13 rc1 with talk updated to the latest and also the latest nextcloud talk app on the app store. 

I've installed the app on a phone and a tablet for tests. I've noticed with different accounts :  

1) tablet + app (outside of the local network) calling the phone + app (in the local network of the server), when the call is initiated on each device, the connexion doesn't bring sound neither video. 

2) tablet + browser logged on the webinterface (outside of the local network) calling the phone + app (in the local network of the server), when the call is initiated on each device, the connexion brings sound and video. 

3) tablet + app (outside of the local network) calling the phone + laptop browser (in the local network of the server), when the call is initiated on each device, the connexion doesn't bring sound neither video. 

4) tablet + browser logged on the webinterface (outside of the local network) + laptop browser (in the local network of the server), when the call is initiated on each device, the connexion brings sound and video. 

A coturn server is set it up to welcome video call from outside the network, for a year now.

Coturn log when fails : https://paste.ubuntu.com/26402418/

**Comment by mario** [comment]
Hello @ernesst!

Thanks for setting the up. I'm not an expert, but:

> 219222: session 001000000000000141: realm <nextcloud13rc1.org> user <1516252609>: incoming packet CREATE_PERMISSION processed, error 403: Forbidden IP
219222: session 001000000000000141: realm <nextcloud13rc1.org> user <1516252609>: incoming packet message processed, error 403: Forbidden IP

And also:

> incoming packet message processed, error 401: Unauthorized

These log lines look fishy to me.

For revelant code that checks if IP is OK in coturn take a look here:
https://github.com/svn2github/coturn/blob/master/src/server/ns_turn_server.c#L253

And of course, your coturn configuration maybe?

There might be of course a problem in the app, but once you check this all and confirm it should be working, maybe you can mail me test credentials (two accounts) to mario AT nextcloud DOT com and I can take a look :)

**Comment by freddresken** [comment]
Hi @ernest @Mario,

Same situation as Ernest described I have here but with the difference that I don't have stun/turn on my system. So it's not a stun/turn issue.

Going to test with coturn later today.

**Comment by ernesst** [comment]
@freddresken 
Yes I think you need a turn server.
Try also from the web interface only.

@mario 
I was in doubt that was a problem with my coturn server as the call through the web interface from Internet was good.
I figured out that was my system adblocker, blokada. As soon i deactivate it, the call and video work. 
FYI : with DNS66 works fine.

Thanks

**Comment by mario** [comment]
@freddresken by default you have Nextcloud's STUN configured, but in lots of cases, you need TURN to get a connection. :)

@ernesst glad it works! :)
