### ISSUE TITLE
Making a call let's ring caller's phone, but not the called one's

### ISSUE THREAD

**Issue by ericschdt** [nextcloud/talk-android#661]
If I call a friend, until he/she picks up, my own phone rings as if I were called. 
I would expect a "tooot tooot tooot" sound like from a standard phone.

On the other side, the called one's phone does not ring at all and there's no notification displayed.
However, there's a message in the chat "eric has started a call".

# Setup 

NC 17.0.0
Talk 7.0.0
Galaxy S7, S10e: NC Talk 7.0.5 PlayStore

**Comment by ericschdt** [comment]
My friend can only accept the call by calling back while I am calling and then has the calling sound as well...

**Comment by samweisgamdschie** [comment]
Same issue/behaviour like ericschdt.

NC 16.0.4, PHP 7.2.24, debian
NC Talk app 6.0.4
Android Talk app 7.0.5 from f-droid store

Coturn and NC is configured like https://decatec.de/home-server/nextcloud-talk-mit-eigenem-turn-server-coturn/ and I tried it with 2 android apps and 1 android app and 1 webclient/browser with both the same behaviour.

**Comment by mario** [comment]
Talk from F-Droid doesn't have push notifications.

As for the original poster here -> the "calling" sound is as-is now and until I find a better one that's how it is :(

**Comment by ericschdt** [comment]
> Talk from F-Droid doesn't have push notifications.
> 
You mean this issue: https://github.com/nextcloud/talk-android/issues/257 ?

> As for the original poster here -> the "calling" sound is as-is now and until I find a better one that's how it is :(

Which one does the iOS app use? Could this one be used (to also be consistent)?
Are you looking for dial sounds, which are public domain? Maybe you can ask the community to create a good one for you. :)

**Comment by mario** [comment]
Yes, issue #257. i

iOS is special because it can use the "default" calling view from the system. On Android, something like that is still in its infancy - Android 10 is the first to have a somewhat usable system for that, but not quite. I'm looking into it :) Also, Android 10 will be on 50%+ phones in 10-15 years anyway.

Dial sounds in public domain or any acceptable licence would be good, yes. Either find one or create it. Community, pretty please with a cherry on top? :D

**Comment by nextra06** [comment]
Same here as well. iOS as told before does not have this issue. Waiting for the same in Android as well.
