### ISSUE TITLE
mute notifications when I'm in a normal phone call

### ISSUE THREAD

**Issue by schiessle** [nextcloud/talk-android#663]
It happens to me already multiple times. I'm in a normal phone call and there is some active chatting going on in a Talk room. That means that I get a notification every few seconds which every time interrupts my call for a second which means that I can hardly understand what the other person says.

@Ivansss told me that the iOS app detect ongoing calls and suppress notification sounds during this time. Is something similar possible on Android?

**Comment by mario** [comment]
I'll look into it. Would you expect only sound to be muted or should it not vibrate as well?

**Comment by mario** [comment]
Ok, should be just the sound. Let me do this.
