### ISSUE TITLE
Remember (keyboard) language for each conversation

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/talk-android#666]
Inspired by a nice change log issue from Signal on iOS:
> a keyboard that returns to the last language you used in each conversation so עơų ƈąŋ ʝųʂɬ ʂɬąƦɬ ɬע℘ıŋɠ.

As I converse with different people in different languages I find this very useful! Not sure if Android can do it...

**Comment by mario** [comment]
There's no real way to do this I'm afraid - on Android keyboard is a completely different application so while you can change locale this doesn't guarantee anything.

Sorry :(
