### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by tamis-laan** [nextcloud/talk-android#667]
After installing the app:
1. I enter my server address
2. I login with my credentials, this sends me to a internal browser version of nextcloud.

And that's it, I'm just logged into nextcloud and not into the app itself. 

This also happends with the official app,  after a while it will say's login failed reverting back to old login method and then I sign in again and the app works. However this is not the case with the talk app I'm just stuck in my account.

What is going on here?

**Comment by mario** [comment]
This is more than likely a server setup issue that I can't really help with.
