### ISSUE TITLE
No push notification 

### ISSUE THREAD

**Issue by sanek8686** [nextcloud/talk-android#668]
After last update I don't get any notifications on my phone. All my friends don't get any notifications to. No call or message notifications.

Nextcloud Talk 7.0.8

Redmi 4x
Android 8.1
LineageOS 15.1.20190726

**Comment by nickvergessen** [comment]
Works fine here. We had 15-20 Minutes downtime this morning due to an upgrade on the server. But we just tested it now and it worked greatly
