### ISSUE TITLE
No push notifications when used aplications token - TOTP Authentificathion

### ISSUE THREAD

**Issue by sanek8686** [nextcloud/talk-android#669]
No push notifications when used aplications token. TOTP Authentificathion applications enabled and used aplications token in Talk.
When I create new test_user without TOTP Authentificathion all good work. When I enable this options for test_user and create token for Talk first time all ok. When another user with TOTP Authentificathion calls to test_user it works. When test_user call another user with TOTP Authentificathion it doesn't work. After this any calls from another user with TOTP Authentificathion  to test_user don't work. 

Error in Log:
{"reqId":"*******","level":4,"time":"2019-11-09T23:56:18+03:00","remoteAddr":"192.168.1.1","user":"*******","app":"notifications","method":"POST","url":"/ocs/v2.php/apps/spreed/api/v1/chat/baurgsfd","message":"error:0909006C:PEM routines:get_name:no start line","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v7.0.8","version":"16.0.6.1","id":"*******"}

**Comment by mario** [comment]
I have no idea why this should happen (and if it does it's a server issue I guess), but you really should login with your username and password, not an app token you created.

What version of Nextcloud and Nextcloud Talk/Spreed on the server do you have?

**Comment by sanek8686** [comment]
> 
> 
> I have no idea why this should happen (and if it does it's a server issue I guess), but you really should login with your username and password, not an app token you created.
> 
> What version of Nextcloud and Nextcloud Talk/Spreed on the server do you have?

Nextcloud 17.0.1
Talk 7.0.2
I used local STUN and TURN (coturn) server and turned off this options, but it's not work.

**Comment by mario** [comment]
Did you try with regular username and pass?

**Comment by sanek8686** [comment]
Yes. I turned off TOTP, but push notifications not works.

**Comment by mario** [comment]
No, this is not about TOTP. You can still use it with regular username and
password.

**Comment by sanek8686** [comment]
Ok. Now I use it with regular username and password. But push notifications not works for existing users

**Comment by X-Raph-X** [comment]
Hi,
i have the same problem. My server is a debian 9, the nextcloud server is in version 17 and the mobile app is up to date from F-Droid. The smartphone is a Xiaomi Redmi 6. Other users of Talk are well notified (Xiaomi Redmi S2 and Iphone 6). I have tweaked all the settings about battery and background running. I never used the TOTP authentification (may be to have a try but i am not sure). I don't understand why i isn't working and i don't known what to do but i would help to solve this issue.

**Comment by sanek8686** [comment]
> 
> 
> Hi,
> i have the same problem. My server is a debian 9, the nextcloud server is in version 17 and the mobile app is up to date from F-Droid. The smartphone is a Xiaomi Redmi 6. Other users of Talk are well notified (Xiaomi Redmi S2 and Iphone 6). I have tweaked all the settings about battery and background running. I never used the TOTP authentification (may be to have a try but i am not sure). I don't understand why i isn't working and i don't known what to do but i would help to solve this issue.

Hi! Some month ago I have the same as yours problem.
If you use FDroid build on Android without special libraries it's not work. Install apps from google play and enjoy!

**Comment by X-Raph-X** [comment]
Arrrrrrrg! You're right ! I have just re installed the app from the google play store, notification works now ! Thank you very much. Do you advise to not use the F-DRoid market for the Nextcloud ecosystem products ?

**Comment by sanek8686** [comment]
> 
> 
> Arrrrrrrg! You're right ! I have just re installed the app from the google play store, notification works now ! Thank you very much. Do you advise to not use the F-DRoid market for the Nextcloud ecosystem products ?

I use:
From GPlay: Nextcloud, Nextcloud Talk, TOTP
From FDroid: DAVx, Etar, Nextcloud Notes, Nextcloud Bookmarks, Nextcloud SMS, Tasks

**Comment by mario** [comment]
Closing as I fail to see the issue really :(
