### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by rugk** [nextcloud/talk-android#671]
Android 9

* import from Nextcloud app -> get grant access screen -> ends in user login sceen in Nextcloud
* manual login -> enter username+password, authenticate (2FA) works -> loading -> ends in web interface (files view) in Nextcloud. (so inside of the app Nextcloud talk I can then browser my files lol, but no Nextcloud talk login possible.

**Comment by KawaiDesu** [comment]
I'm affected too.
- Android 9 (LineageOS 16)
- Nextcloud Talk 7.0.8

If I try to use app token it claims "Wrong username or password".
If I try to use usual login with my password as for web - it just spins "Logging in" forever.
The interesting thing - I can see newly created session by this app in the web (Settings -> Security).

I also experinced "Forever logging in" with main Nextcloud app, but after some time it suggests to fallback to old login method and it works. Talk does not suggest it :(

**Comment by rugk** [comment]
Do you also have 2FA activated?

**Comment by KawaiDesu** [comment]
No, I haven't activated it yet. I'm playing around with nextcloud, testing features.

**Comment by rami-dabain** [comment]
Same issue here.

> If I try to use app token it claims "Wrong username or password".
If I try to use usual login with my password as for web - it just spins "Logging in" forever.
The interesting thing - I can see newly created session by this app in the web (Settings -> Security).

I had 2FA / OTP and disabled them, but still have the issue

**Comment by mario** [comment]
Hi.

@rugk your issue number 1 is normal - you need to reauthenticate - we basically import the url and the username. For various reasons, importing the token from the Files app won't work.

As for your other issue: Did you check the nextcloud logs? This really sounds like a redirect doesn't happen on the server side so is PROBABLY a server configuration issue.

@KawaiDesu old login method is not recommended and would cripple lots of functionalities for Talk, so we therefore do not implement it.

**Comment by rami-dabain** [comment]
Of you are using https and a proxy, check this out: https://github.com/nextcloud/server/issues/18155 I had same issues as i said before, and this is how i solved it

**Comment by mario** [comment]
Closing as there's no reply.
