### ISSUE TITLE
Account switching too complicated

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#673]
Being in the app and want to switch to another account takes too many step:
- click on top right avatar
- click on "switch between accounts"
- choose correct account
- press back to get to contact list

@jancborchardt do you have an idea how to get this a bit faster?

On Android Files we have to open drawer and can then directly click on another account.

**Comment by jancborchardt** [comment]
@ivansss can you post screenshots here of how you do the settings area (especially account list and switching) in the iOS app? That seemed a very good blueprint. :)

(Of course I’m not suggesting to use iOS design, merely looking at that information architecture.)

**Comment by Ivansss** [comment]
This is how it has been implemented on iOS https://github.com/nextcloud/talk-ios/pull/264

**Comment by tobiasKaminsky** [comment]
In initial steps the last step was missing:
- after selecting account you are in settings view, and thus have to press back to get to contact list

**Comment by jancborchardt** [comment]
Yep, so how it should be is of course:
1. Tap avatar to go to settings which has the account list on top
2. Tap other account you want to switch to → automatically switches to conversation list

**Comment by githubkoma** [comment]
I really like how rocket chat handles this, in all mobile Clients:
![20200420_120759](https://user-images.githubusercontent.com/5107805/79740302-bdc07700-82ff-11ea-929a-51875beb0256.jpg)

When you tap on (1) it opens (2), where you habe the choice of Multiple Servers and to add another..

**Comment by mario** [comment]
Will be in v9.0.
