### ISSUE TITLE
Show warning if server us unreachable / no internet

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#674]
Same like we have on Files App, show a warning if either 
- no server connection
- no internet connection
- wlan is behind paywall

**Comment by mario** [comment]
The question is - is this a good design pattern? Do we need this? None of the messenger platforms I've seen has the functionality because they provide offline storage and actions (which is our intention too).

@nickvergessen for comments.

**Comment by tobiasKaminsky** [comment]
True, this is just how we do it on files currently, as there is no offline functionality.
How long will it take to have a full working offline functionality in place? It this takes too long, then this might be a short win?
E.g. enabling airplane mode and opening up talk currently shows only a spinner.

**Comment by nickvergessen** [comment]
Sure offline support will help.
But I guess you should be notified in some way when fetching messages etc doesn't work even with offline support. So not sure it replaces it completely, but it removes the priority of the issue.

> How long will it take to have a full working offline functionality in place?

Hopefully most of it comes with the Talk 8 release. But yeah I would say lets keep this in mind and for the future to fix the corner cases after we got offline support.

**Comment by mahibi** [comment]
still an issue.
as offline support is not implemented in the near future, what is the priority of this? @nickvergessen ?

**Comment by nickvergessen** [comment]
How much effort is it?
If it's just up to an hour or two, I think we could show a message in the meantime to raise awareness. Especially in the german landscape it's good to know when there is no connection atm while you try to open a chat or refresh the conversation list. So a little toast at top/bottom or something is fine

**Comment by mahibi** [comment]
solved with https://github.com/nextcloud/talk-android/pull/2453
