### ISSUE TITLE
Chat Login for users outside Nextcloud instance

### ISSUE THREAD

**Issue by oppenheimer-** [nextcloud/talk-android#677]
I experienced problems during an onboarding scenario. I didn't find any information about getting users from outside my nextcloud instance into a chat. I'd love to get my family into the chat because i keep advocating against whatsapp etc. and pro nextcloud.

Steps taken:
1. created a contact with valid e-mail adress in nextcloud instance as super user
2. put that contact in trusted circle
3. added a new chat
4. added that contact as chat member
5. set password
6. installed Talk Android app (deleted previous session to test)
7. set URL to the nextcloud instance
8. entered e-mail adress from contact

error -> chat password / user is invalid

How is it possible to invite people easily?
Prerequisite is, that chat is locked by a password.

**Comment by jookk** [comment]
All is possible in Android Nextcloud Talk. 
In chat click to + and New public conversation

**Comment by oppenheimer-** [comment]
Thanks for the hint @jookk, but in the _freshly installed app_ there is no option for that, yet. As illustrated before, the new member has to connect to my nextcloud server. 

I expect that the user enters the e-mail and chat password to get access to the chat room. But this does not work and is an frustrating experience tbh.

I'd be happy about advice how to verify devices without "real" nextcloud user credentials.

**Comment by jookk** [comment]
No, guest user logins via special link and password, if you set password.

Dňa 7. decembra 2019 11:05:16 používateľ oppenheimer- 
<notifications@github.com> napísal:

**Comment by jookk** [comment]
![1](https://user-images.githubusercontent.com/11217085/70372825-4a840e80-18e4-11ea-8953-58b7d3f7a565.png)
![2](https://user-images.githubusercontent.com/11217085/70372828-51128600-18e4-11ea-88a3-ca92ed4524b0.png)
![3](https://user-images.githubusercontent.com/11217085/70372830-566fd080-18e4-11ea-920d-bb55b5ba0d3b.png)
![4](https://user-images.githubusercontent.com/11217085/70372833-5a9bee00-18e4-11ea-80d9-71e25d06d0e0.png)

**Comment by oppenheimer-** [comment]
> No, guest user logins via special link and password, if you set password. Dňa 7. decembra 2019 11:05:16 používateľ oppenheimer- <notifications@github.com> napísal:
> […](#)
> Thanks for the hint @jookk, but in the freshly installed app there is no option for that, yet. As illustrated before, the new member has to connect to my nextcloud server. I expect that the user enters the e-mail and chat password to get access to the chat room. But this does not work and is an frustrating experience tbh. I'd be happy about advice how to verify devices without "real" nextcloud user credentials. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

I know that this functions exists. But it is unusable with a freshly installed app.

**Comment by mario** [comment]
Yes, you currently need an account to use the Nc Android app. This will be fixed via this issue: https://github.com/nextcloud/talk-android/issues/261
