### ISSUE TITLE
is it no longer possible to use the rear camera?

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/talk-android#679]
I tested the video call with an s10 plus samsung one Nexus 6 and a 2xl pixel and on both I didn't find the way to change video from front to back camera.  can no longer be done?

**Comment by username72764274** [comment]
Hi, I already reported this bug some time ago: https://github.com/nextcloud/talk-android/issues/655

**Comment by tigernero79** [comment]
ok i'll wait for bug resolution

**Comment by mario** [comment]
I'll close this one as it's a duplicate :)
