### ISSUE TITLE
Status bar color

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#682]
Currently the status bar color is slightly darker than the header bar of the app. This makes it look a tad dated.

Easy fix: The status bar color should simply be the same as the header bar. :) See e.g. Signal or our own Android files app.

-----

@mario if you mention where in the code this can be adjusted, this would make for a very cool "good first issue". :)

**Comment by mario** [comment]
The color for the status bar is currently taken automatically via colorPrimaryDark as per the Android guidelines/the way OS is designed. However, this can be overridden of course.

I guess changing/adding android:statusBarColor to the styles.xml would work and setting it to the primary color.
