### ISSUE TITLE
Compile error fresh checkout,

### ISSUE THREAD

**Issue by geekz-reno** [nextcloud/talk-android#683]
Hi, got error on fresh clone master,

`error: cannot find symbol
public class ClosedInterfaceImpl implements ClosedInterface, ProviderInstallListener {
                                                             ^
  symbol: class ProviderInstallListener`

any help will appreciate, thanks team

**Comment by mario** [comment]
Hi.

What flavour are you trying to build?

**Comment by geekz-reno** [comment]
hi @mario , sorry for late replay, i think i got an error when running build command, then i copy paste depedencies from gplay.gradle to app/gradle and success.

**Comment by mario** [comment]
Cool.
