### ISSUE TITLE
Incoming and posted messages appear twice on the chat list

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/talk-android#684]
Server: https://nextcloud.kaminsky.me
Client: v7.0.8 from Google Play

![nextcloud-talk-duplicated-messages](https://user-images.githubusercontent.com/1426823/71259952-9184f180-2331-11ea-886e-78e7757fa37c.jpg)

**Comment by mario** [comment]
I did have reports of this in group conversations from a few people, but was never able to reproduce :( I guess there's a race condition somewhere.

**Comment by StillLoading** [comment]
I can confirm this is an issue in group chats. If you however return to the chat overview and re-enter the conversation again the duplicates disappear.
And it doesn't seem to be an Android only issue since we have at least one iOS device user how reported the same thing.

**Comment by AlexP05** [comment]
We have the same issue with Nextcloud 17.0.2 and the up-to-date Nextcloud Talk Android client with a group chat. Some of us have all messages twice, some don't. Those who have the issue get every incoming message twice (sometimes the second one will come after a different message) and also every sent message appears twice. But some of us don't have this issue. The duplicate messages have the same timestamp and they don't disappear if your return to the chat overview and re enter the group chat.

**Comment by vonAlenberg** [comment]
Same problem. NC18 + Android app.

**Comment by Art4** [comment]
A user has the same problem.
- device: Motorola Moto G7 Plus (Android 10), 
- Nextcloud Talk for Android 8.0.3
- Nextcloud Talk App on Server 8.0.5
- Nextcloud Server 18.0.1

Are there any dumps or logs I can provide for investigating and fixing this issue?

**Comment by mario** [comment]
Thanks for your patience, making a release with the fix now.

**Comment by kadarpik** [comment]
I see the same problem with NC 18 and 15, there is even another issue, in my group chats I see all message lists 4 times in the chat room.  There is message 1 2 3 4 and then again 1 2 3 4 and so on. All messages have same timestamps and API returns correct chat room message list. My current version is 8.0.6. from android store. All looks perfect from browser

**Comment by andyxheli** [comment]
Still happens to be once in a while running leatest version on talk 14.2.0
