### ISSUE TITLE
Url case-sensitive not support...

### ISSUE THREAD

**Issue by Deltafox79** [nextcloud/talk-android#69]
Hi, i have compiled latest Android build v1.0.11 Build 22 of today and login access work fine but the url displayed does not support uppercase letters **xxxxx.yyy/Nextcloud** but the app not recognize the case-sensitive N and display url xxxx.zzz/**n**extcloud and not see any user contact after login..

ios app instead work fine...

Regards

**Comment by mario** [comment]
Thanks for the report @Deltafox79. Could you send me test credentials to mario AT nextcloud DOT com so I can test and fix? :)

**Comment by Deltafox79** [comment]
https://www.pensierando.it/Nextcloud
Username=mario
psw=nextcloud

the bug for android is : 
1) After login I not see any contact but whit ios app all work fine.. 
For iOs
2) Is possible like android to login whit many account?

Regards

**Comment by mario** [comment]
@Deltafox79 I will test in a bit. For iOS, we don't yet support multi-account.

**Comment by tigernero79** [comment]
I also have the same problem, I have the cartel anextcloud with the N in upper case (Nextcloud) app nextcloud talk makes me log in but then the account entry digs me www.xxxx.it/nextcloud and does not show me the users only white screen. and in setting me

https://tigernero.no-ip.org/nextcloud instead of the final Nextcloud

**Comment by mario** [comment]
Thanks folks, you can delete the test account @Deltafox79 now :) Please look into your admin settings where you'll see you miss TTF-something, so avatars aren't properly generated.

As for the problem you're having with uppercase, it's fixed, and you'll have a new version tomorrow.

**Comment by mario** [comment]
cc @tigernero79 too ^_^

**Comment by tigernero79** [comment]
after having compiled your version with uppercase fix I see only users that when I make a call alert it exits from android to ios to accept call but from android to android or iOS to android warning that someone is calling you does not exit. coincidence or general bug? warning comes out only from android to ios

**Comment by mario** [comment]
@tigernero79 this is normal. Once you install an update 1.0.12 from Play Store, it'll work :)
