### ISSUE TITLE
Android 10 - Talk app gives no notification at all.

### ISSUE THREAD

**Issue by nextra06** [nextcloud/talk-android#696]
Hello All,

Nextcloud Server 16.0.5
Webserver Apache
PHP-FPM
HTTPS & HTTP/2
Self hosted TURN & STUN server
Hardware - Raspberry Pi 4 4B - 4GB Ram - 2TB SSD - 64GB Card

Android 10 (OnePlus 6 - No Root - Stock)
Nextcloud Talk 7.0.8

Expected behaviour - Talk app should ring on incoming call & should make notification sound when a new message is received.

Noted behaviour - No notifications at all.

Error logs - None - No errors at Webserver or Nextcloud Server.

Detailed description - Notifications only work when the app is kept in foreground. As soon as the app goes background the notifications stop. Battery optimization has been disabled for the app, the app has unrestricted data allowance. App has been installed and reinstalled several times however the same issue remains.

On previous Android versions (7, 8 both rooted with stock rom - Sony Z5 & 9 no root stock OnePlus 6) there was proper ring for an incoming call and sometimes new message made a sound as well (although the message notification were never instant and sometimes there was no notification, incoming call ring were fine though).

On iOS the notification seems to be working perfectly for both calls and messages (tested iOS 13,3).

What am I doing wrong? Help is needed and appreciated.

**Comment by mario** [comment]
So in general, there's one way to receive a notification - if the phone can show it, it will. Some vendors have certain settings that make it more likely to see the notifications, but even that won't help. 

If you can send me a test account to mario@nextcloud.com I can check if notifications are sent, but that's pretty much all I can do - the rest is up to your phone unfortunately.

**Comment by nextra06** [comment]
Will send you a test account.

**Comment by nextra06** [comment]
Well after sorting out the Push notification problem in Nextcloud client (Android), Talk app still has problems only on OnePlus 6 (Android 10).
I guess a vendor specific problem to be looked at.

**Comment by GitJamz** [comment]
I have the same issue.. No notifications at all, on 2 different phones.
However, I dont have pushnotifications on my android because I use microG instead of google Gapps package, and have not turned on push notifications on my phone - because then it requires more google services.

But, everything else I use has notifications. If I get a email, calender alerts, sms and signal messages etc etc.. So the question is, why does Nextcloud Talk have to rely on push for their notifications? There are many people doing what I do nowdays becaue they want a "google-free" android phone as much as possible at least.

**Comment by mario** [comment]
@GitJamz expected and not a bug, like you figured out at the end :)

As for @nextra06, yes - probably a vendor specific issue that is hard/impossible to fix. But anyway, since you're a company if you need Talk (or Nextcloud in general) support please send an email to mario@nextcloud.com.
