### ISSUE TITLE
iOS 13.3 - Talk app does not respect group settings

### ISSUE THREAD

**Issue by nextra06** [nextcloud/talk-android#697]
Talk app for iOS displays all contacts in contact list when the server is set to allow only members of Talk group to use Talk app.
On the other hand Android app displays only the first contact and nothing else.

**Comment by mario** [comment]
Hi and thank you for your report.

If there's an issue with the iOS app you should probably file a bug there (https://github.com/nextcloud/talk-ios/) - @Ivansss do you use the share or the autocomplete API to get the list of contacts?

As for why the Android app would show only one contact - unsure why only 1, but with Android (and it really should be the same with iOS) it only fetches a portion of your contacts and for further results you're supposed to search.

Let me know if searching brings more results.

**Comment by nextra06** [comment]
Sorry for mixing up iOS and Android.

Yes, the search works as expected but I thought the app would list all the contacts who are allowed in the group to use Talk.

**Comment by mario** [comment]
Yea, I'll improve the UI to make that more obvious.
