### ISSUE TITLE
Notifications call Incoming missing on Android 

### ISSUE THREAD

**Issue by Deltafox79** [nextcloud/talk-android#70]
When try to call a user whit Android to other Android no Notification Incoming call appare.. In background or foreground... Test whit latest v1.0.22 build 23...

**Comment by mario** [comment]
Like I mentioned in another issue, you need to use a build from Play Store or download an APK from here to have notifications: https://github.com/nextcloud/talk-android/releases

Cheers! :)

**Comment by Deltafox79** [comment]
I understand I signed whit my Signatures.. Right.. On play store is present always 1.0.11 i Wait new version whit case sensitive fix
