### ISSUE TITLE
Talk v8.0.0beta1 crashes on pressing "send button" 

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/talk-android#702]
Hello,

i updated from v7 to v8.0.0beta1 on Motorola G5/Android 8. Fine. 

After the start all dialogs are loaded and it looks good. If you call up a previous chat and then press the send arrow, the app will crash. 

Please check if there are other users with the same problem.

**Comment by jookk** [comment]
Android 9
Reproduced, after you type msg, then send button - fc.

**Comment by Akrobs** [comment]
Confirmed! Xiaomi Mi5, Android 7.0, Talk v8.0.0beta1

**Comment by mario** [comment]
Got it, will take a look - thanks.

**Comment by Valdnet** [comment]
Same. Application crashes when sending a message.

App:
Android 6
Talk 8.0.0 b1
Nextcloud Talk 7.0.2
Nextcloud 17.0.2

**Comment by jookk** [comment]
B2 fixed it

**Comment by Valdnet** [comment]
On Android 6 version 8.0.0b2 also works correctly. Thanks.

**Comment by Akrobs** [comment]
Good work, Mario! Thanks!!!
