### ISSUE TITLE
Calling with app

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#71]
I have problem with app to app calling.
Using androids.
Call is not working, no sound, no video on both sides.
Tried in my local network and tried in mobile network both sides.
Calling via webui working fine in one local network and mobile to mobile networks. 
Using own turnserver and own stun 2ip adresses.

I have not checked calling via web ui to mobile talk app.

**Comment by mario** [comment]
Can I get two test accounts please: mario AT nextcloud DOT com. Also what
version of the app and what phones and Android?

**Comment by jookk** [comment]
Your account is created, hoope, email was sent to you... 
app version 1.0.12 on all of them.
Xiaomi Redmi note 4 global android 7
Lg optimus android 5.1 
Lenovo tab android 6
Asus tab android 6
all permissions granted for app

**Comment by mario** [comment]
@jookk thanks, let me check.

**Comment by mario** [comment]
Just tried webUI <-> Android works. Will try Android <-> Android tonight. Thanks for the accounts!

**Comment by mario** [comment]
I tried it. I got it to work, but it does not always work which is strange. Wil try to look into it!
Please keep the accounts! :)

**Comment by jookk** [comment]
I tried calling with other side on other network with app on both sides (androids)
First call: no call success. So I ended call and started new call and it succeed. 
(sometime I receiving late notifications about call in progress (someone call me notify).

**Comment by mario** [comment]
I cannot impact how fast the notifications appear, but we've set priority to high.

As for the connectivity, I'll check - just please keep my accounts! :)

**Comment by mario** [comment]
Fixed, will be in the next minor release. You can now delete the accounts :)
