### ISSUE TITLE
No incoming call signaled under android 10 / android Q

### ISSUE THREAD

**Issue by chrissi55** [nextcloud/talk-android#713]
Since update from android P to 10 (Q) my nextcloud talk app (8.0.0) under nextcloud server 17.0.2.1 is no longer ringing loud when an incoming call should be signaled.

Instead of that the recipient get a short message in chat that xy has started a call. 
If you have a look to the unlocked android device that moment and if you have opened the app on top then you are able to join the call.

Other messages like emoji or text-messages are signaled in info area and on the locked screen either.

I know that google has damaged a lot with android 10 - but is there a chance that this behaviour could be healed with a update of nextcloud talk? Or are there any settings i could modify?

I already set battery savings to none for all nextcloud apps (files and talk)
I allowed all notifications for nextcloud apps.

**Comment by bgbearcatfan** [comment]
I also have this same issue.  Also updated Nextcloud server to 18 and issue still exists.

**Comment by chrissi55** [comment]
i suggest it is an compatibility problem between nextcloud 8.x and android 10.

Many others have problems since android 10 with notifications etc.
one needed dependencies seems to be the popup function in android 10 must be supported by apps.
Not sure if nextcloud talk is already full compatible with the requisites of android 10.

Never the less, not clear why other messages like text, pictures etc. come through as expected and are well signaled and voice / video calls are not. 
I disabled for testing the ability to use audio / video / data and re-enabled it without success.
I switched between FDroid Version to Google Version without effect - maybe because there is no difference between both versions.

I entered the beta program in hope of (early) solution

**Comment by mario** [comment]
Hi, thank you for bringing this to my attention. I was aware of the upcoming changes, but sadly, because I do not have a Q phone myself completely forgot about it.

The fix will be out in the world today.

**Comment by yostral** [comment]
Hi.

I'm in the same situation. I had no problem to receive calls notifications until I upgrade Android Talk to 8.0.0. I upgraded few minutes ago to 8.0.1, on Play Store version, and it is still the same, no incoming calls notifications. I'm on Android Q, on Nextcloud 17.0.2 and Talk 7.0.2. The only difference with when it worked is the Android Talk version.

Thanks a lot for your work Mario !

**Comment by bgbearcatfan** [comment]
Can confirm that the problem still exists after upgraded to 8.0.1 as well.  Testing done with android 10 on Pixel 4XL's.

**Comment by chrissi55** [comment]
Yes can confirm too, and have cleared app cache and data and re-enabled it to avoid retention data of old 8.0.0 install.

And thanks for your investigations and help mario

**Comment by mario** [comment]
Gimme a few days to try and figure it out - thanks for your continued
patience and help people!

**Comment by jakobroehrl** [comment]
Hi, have the same problem with a OnePlus 7T. The 8.0.1 doesn't fix the problem. 
@mario: Thanks for your work!

**Comment by nursoda** [comment]
Same* here, OnePlus 6/T/7/T, all Android 10. Can I assist you in debugging on my device?

* I do not get ANY notification upon ring call (except when app is active, in the chat and device is on), text is notified just fine, even when app is closed.

**Comment by mario** [comment]
Fixing this is untrivial as emulator seems to misbehave, and I don't yet have a real Android 10 device. Anyway ... I think I have a workaround for now - there will be a release later today. Please test!

**Comment by yostral** [comment]
Thanks Mario. But it still doesn't work for me with the 8.0.2  :( .

**Comment by chrissi55** [comment]
...i'm not sure if it's out now?
https://play.google.com/store/apps/details?id=com.nextcloud.talk2&hl=de

I'm still on 8.0.1 and no Updates are offered by google for me :-)

**Comment by jakobroehrl** [comment]
It's not working with the 802, sorry

**Comment by yostral** [comment]
@chrissi55 : https://github.com/nextcloud/talk-android/releases

**Comment by chrissi55** [comment]
Thx i get the latest (8.0.2 now) from Play Store this morning.

But the problem still exist. Maybe it's slightly different from 8.0.0 because i get notice when i opened NC Talk and then go back to the Homescreen but do not lock my device. Then the incoming call is signaled. But the app is not in foreground this moment. That moment i lock my device and wait for e.g. 4-5 seconds then no calls were signaled anymore.

Maybe a phenomenon of the moment or a lucky second - don't know.

But all around the problem is not solved yet.  But many thanks for your engage mario!!

**Comment by mario** [comment]
@chrissi55 do you get notifications for messages and group/public calls?

**Comment by chrissi55** [comment]
I get notice for messages in all states: foreground, hidden and locked screen

I got 1:1 call notice in following states: foreground, shortly hidden (means tipped on homescreen and awaited incomming calls = ringring came up)  no notices after locked screen or (not yet testet) after waiting a longer while after switching to homescreen without locking the device.

So, never the less i have to watch my phone to get informed about incoming calls.

**Comment by mikweb2017** [comment]
i dont work for me  on Mate 20 Lite  with Emui 10  talk 8.02  und Nextcloud 18

**Comment by mario** [comment]
I found a way to fix this. new release will be out this week.

**Comment by nursoda** [comment]
8.0.4 does not work for me on Android 10 (OnePlus 6/7).

**Comment by yostral** [comment]
There's no 8.0.4 Android Talk app : https://github.com/nextcloud/talk-android/issues/713#issuecomment-582620269

You are talking about the Nextcloud app, on the server, the web interface.

**Comment by nursoda** [comment]
Yell, yes, sorry. I'm on the latest released Google Play App 8.0.2. Registering for Google Play Beta now.

**Comment by mario** [comment]
Should be fixed today - please reopen if it's not.

**Comment by mikweb2017** [comment]
thanks now work fine

**Comment by jakobroehrl** [comment]
Thanks a lot!
Very good Job

**Comment by nursoda** [comment]
Hmmm, not working for me. As it's working for others, I will investigate further. But how?

**Comment by mario** [comment]
Do the regular chat notifications work for you?

**Comment by nursoda** [comment]
Yes!

**Comment by mario** [comment]
@nursoda then it's really strange. Are you sure you're on 8.0.3?

**Comment by nursoda** [comment]
Sorry, no, wasn't 8.0.3. It DOES work with 8.0.3, at least if both phones use that version. Sorry. I face other issues, will eventually report them, but this issue can remain closed. Thanks a lot @mario!

**Comment by mario** [comment]
Awesome @nursoda ^_^
