### ISSUE TITLE
Allow to swipe a message to reply

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#714]
### Steps
1. Open a conversation
2. See a message you want to reply to
3. Swipe it to reply

Works like that in: Signal, Telegram, Threema, Viber and Whatsapp

**Comment by mario** [comment]
How can you call a bug something that was never there in the first place? xD

**Comment by nickvergessen** [comment]
Well call it an enhancement if you like, but it just makes the feature non-discoverable for most people.

**Comment by mario** [comment]
Implemented in master.
