### ISSUE TITLE
Do not stop ringing after 45 seconds

### ISSUE THREAD

**Issue by markus2330** [nextcloud/talk-android#718]
For me this is a misfeature: What was the idea behind stopping to ring someone after 45 seconds of not picking up? Especially with notifications not working, this feature is very disturbing.

Could you please remove the feature and again ring endlessly.

Furthermore, there is a bug related to the misfeature: After the 45 seconds expired, trying to exit the call sometimes hang forever.

**Comment by mario** [comment]
Even a normal phone call stops ringing in 45 seconds, so I'm afraid this won't change. I'm happy to help you on other things - why do notifications not work for you? Did you check the Nc log?

**Comment by markus2330** [comment]
Thank you for your answer!

> Even a normal phone call stops ringing in 45 seconds

This is not true for me. My provider was able to make endless ringing for my "normal" phone. And even if all providers in the world would have this restriction, this would still not be a good reason.

> why do notifications not work for you? Did you check the Nc log?

I have Nextcloud Talk 8.0.0 installed from F-Droid. Do notification now work without Google Play?

**Comment by mario** [comment]
Ah, F-Droid - no, there are indeed no notifications without Google Play Services/MicroG.
