### ISSUE TITLE
Weblogin: user agent with unneeded prefix

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#72]
"Mozilla/5.0" should be removed, I think. 

![screenshot_20180119-121924](https://user-images.githubusercontent.com/5836855/35152824-42e88ff8-fd24-11e7-940a-d211f1b27878.png)

**Comment by mario** [comment]
This was discussed with @Ivansss and @nickvergessen before we decided to do this, so closing. They can chime in to complain :P

**Comment by mario** [comment]
The Nextcloud app does the same btw :)

 <string name="user_agent">Mozilla/5.0 (Android) ownCloud-android/%1$s</string>

**Comment by tobiasKaminsky** [comment]
![2018-01-19-143230](https://user-images.githubusercontent.com/5836855/35153148-9388b1bc-fd25-11e7-9fb3-c8a2371772d2.png)

I am only talking about the "mozilla" part.
But I am currently also unsure where this gets removed as indeed our useragent also have "mozilla".

**Comment by mario** [comment]
@tobiasKaminsky this is probably the server side magic :)

**Comment by tobiasKaminsky** [comment]
Then this should be also done on server side talk app, or? @nickvergessen

**Comment by nickvergessen** [comment]
Well, not entirely sure how this is done in the other app, but the files app shows "Huawei ALE-L21" for me, not anything user agent related at all...

**Comment by mario** [comment]
@nickvergessen probably related to the login flow :) I do exactly the same as we do on the Files app.

**Comment by nickvergessen** [comment]
Yeah but I tried to find the code, but it does not use the user agent constants anywhere.

**Comment by mario** [comment]
@nickvergessen @tobiasKaminsky found the issue. Android app uses:

    private static String getWebLoginUserAgent() {
        return Build.MANUFACTURER.substring(0, 1).toUpperCase(Locale.getDefault()) +
                Build.MANUFACTURER.substring(1).toLowerCase(Locale.getDefault()) + " " + Build.MODEL;
    }

**Comment by mario** [comment]
@tobiasKaminsky and @nickvergessen - thanks for debugging with me! :)
