### ISSUE TITLE
Caller notification in smartwatches

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#720]
some suggestions from using Talk 👍 
1. If Im on call (calling with others) and Talk app goes to background, calling is stopped. Cant be on status bar some notification, that Im calling and call can continue when app is in background?
2. that notification can solve 2nd feature suggestion: Getting call and messages notifications on watches (smart tracker, watches...)?

Thank You very much, Talk app working fine, we are using it daily :)

**Comment by mario** [comment]
Hi,

I'll eventually add the notification, but the call should already continue when the app is in background - what android version and what app version?

The second should already work as well?

**Comment by jookk** [comment]
I had today call and 2nd part goes to SMS app for info and call was interrupted.

**Comment by jookk** [comment]
No, I havent received a notification to watch.

**Comment by jookk** [comment]
Messages goes to watch, but not call notification. 
Msg -> notification in watch
Call -> not notified in watch

**Comment by mario** [comment]
Will be fixed soon ;)

**Comment by mario** [comment]
Release should be out today.
