### ISSUE TITLE
No avatars for @mention

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#721]
There are no avatars for @mention. They are visible only after the next message has been sent.

![obraz](https://user-images.githubusercontent.com/47037905/73533220-95229280-441e-11ea-8d19-02a2ef3ac03e.png)

App:
Android 6
Talk Android 8.0.1
Talk 8.0.1
Nextcloud 18.0.0

**Comment by mario** [comment]
When did this start happening? :-/

**Comment by Valdnet** [comment]
After upgrading Nextcloud to 18 and Talk 8.0.1.

**Comment by mario** [comment]
Removed chips for now, so closing.
