### ISSUE TITLE
Missing UI elements

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/talk-android#722]
1. check out master
2. compile and install

Problem:
Toolbar is not displayed - only white space is visible.
Login window is missing some UI elements.

![Screenshot_20200209-092755](https://user-images.githubusercontent.com/1426823/74100122-1bc42780-4b23-11ea-8e00-9e39c847c440.jpg)
![Screenshot_20200209-093956](https://user-images.githubusercontent.com/1426823/74100123-1ebf1800-4b23-11ea-8bbb-4f1aa4513c75.jpg)

**Comment by mario** [comment]
On the first screen there should be no toolbar at all. But you're right, this is a bug.
