### ISSUE TITLE
Settimg for muting the ring sound when calling

### ISSUE THREAD

**Issue by StyXman** [nextcloud/talk-android#723]
It's 23.30, my kids are sleeping, I'm trying to test video calls between two users, and even when I disabled all notifications and all volume settings are in 0 (granted, 'only' according to the volume app in f-droid), I get a loud sound when calling someone else.

**Comment by mario** [comment]
Thanks for your request. Let me think about this.

**Comment by nickvergessen** [comment]
Hu? Any calling app plays a ringing for you while you start a call?

**Comment by nickvergessen** [comment]
Okay, for outgoing video calls the sound is played via the speaker by default. that's of course a bit disturbing but also the same as all others handle it.

**Comment by nickvergessen** [comment]
Duplicate of #772 which has more info
