### ISSUE TITLE
8.0.3 report

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#728]
I see notification on phone, but not in watch.
Mario, I have sometimes (probably old) problem, that smartphone vibrate after call received or missed or ended. To resolve vibration, I must restart phone.
It occurred 2 times, one on android 9 and 1 on Android 8.1 . Moto g5s plus and g6 plus.

Thanks for your time, 👍😃

**Comment by mario** [comment]
The watch notification should work now - I don't know why it doesn't, but I don't have a watch to test. Vibration thing I can't help atm. Let's see what happens with 9.0 :)

**Comment by jookk** [comment]
Wau - 9.0! Will be there beta near?

Dňa 13. februára 2020 9:16:23 používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by mario** [comment]
Who knows :)
