### ISSUE TITLE
Cannot end call -> app hangs

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#73]
I only have this one call ("Du" = "you").
If I click on it, I can see myself, flip camera, but on ending call (red button) or clicking back, the whole app freezes.
I have to hard kill it and restart it to get back to the call list.

![screenshot_20180119-142132](https://user-images.githubusercontent.com/5836855/35152884-7ed62444-fd24-11e7-8f09-3063136592ce.png)

**Comment by jookk** [comment]
A cant sometimes end call too. One click and no call control buttons are visible.

**Comment by mario** [comment]
What version @tobiasKaminsky ?

**Comment by mario** [comment]
@jookk your particular bug will be fixed in the next minor release :)

**Comment by tobiasKaminsky** [comment]
Latest App yesterday 1.0.12

**Comment by mario** [comment]
Please try 1.0.14 :D

**Comment by tobiasKaminsky** [comment]
Same.
On Monday I'll try to get a logcat, if possible.

**Comment by mario** [comment]
Thanks

**Comment by tobiasKaminsky** [comment]
This is all I get.
After clicking back / red button, the video stops and I can toggle the overlay icons, but I can never get back to the "start/calling screen".
I have to manually force close it.

```
0:59.650 12501-12501/com.nextcloud.talk2 I/org.webrtc.Logging: EglRenderer: pip_video_viewReleasing done.
01-22 08:00:59.650 12501-12609/com.nextcloud.talk2 I/org.webrtc.Logging: EglRenderer: pip_video_viewQuitting render thread.
01-22 08:00:59.651 12501-12501/com.nextcloud.talk2 D/MagicAudioManager: stop
01-22 08:00:59.655 12501-12501/com.nextcloud.talk2 D/MagicBluetoothManager: stop: BT state=HEADSET_UNAVAILABLE
01-22 08:00:59.656 12501-12501/com.nextcloud.talk2 D/MagicBluetoothManager: stopScoAudio: BT state=HEADSET_UNAVAILABLE, SCO is on: false
01-22 08:00:59.657 12501-12501/com.nextcloud.talk2 D/MagicBluetoothManager: cancelTimer
01-22 08:00:59.657 12501-12501/com.nextcloud.talk2 D/MagicBluetoothManager: stop done: BT state=UNINITIALIZED
01-22 08:00:59.727 12501-12501/com.nextcloud.talk2 D/MagicAudioManager: Abandoned audio focus for VOICE_CALL streams
01-22 08:00:59.729 12501-12501/com.nextcloud.talk2 D/MagicAudioManager: AudioManager stopped
01-22 08:00:59.861 12501-12607/com.nextcloud.talk2 I/org.webrtc.Logging: Camera2Session: Stop done
01-22 08:00:59.862 12501-12607/com.nextcloud.talk2 I/org.webrtc.Logging: Camera2Session: Camera device closed.
01-22 08:00:59.862 12501-12514/com.nextcloud.talk2 W/art: Long monitor contention with owner VideoCapturerThread (12607) at boolean android.os.BinderProxy.transactNative(int, android.os.Parcel, android.os.Parcel, int)(Binder.java:-2) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 201ms
```

**Comment by tobiasKaminsky** [comment]
It seems to happen only if I am the only one (or maybe the last one?) in the call.

**Comment by mario** [comment]
@nickvergessen @Ivansss hey folks! @tobiasKaminsky has this talk called "You" which keeps reappearing. Since the Android app never creates such a talk, I was wondering if you've got any idea what's going on?

On the WebUI this call doesn't have the right detail side.

**Comment by tobiasKaminsky** [comment]
Server is NC13.0.0 RC2
Spreed/talk sever app is: 3.0.1
Android app is: 1.0.14

**Comment by Ivansss** [comment]
This "You" call was probably created by clicking on "New public call" in the web UI.
It is just a public call where you are the only participant.
You should be able to rename it or add more participants.

> On the WebUI this call doesn't have the right detail side.

If you click on that call, the right side bar doesn't show up?

**Comment by tobiasKaminsky** [comment]
This is "you" / "Du": https://nextcloud.kaminsky.me/index.php/s/7P8sYfE7yMxJZZR
this is "call": https://nextcloud.kaminsky.me/index.php/s/bcf6oRA96nQbDmP

Clicking on "you" does not open the detail/right view.

**Comment by tobiasKaminsky** [comment]
![screenshot_20180122_101543](https://user-images.githubusercontent.com/5836855/35213471-089f86c6-ff5e-11e7-8355-f3d1ed718682.png)

Debugged with @Ivansss and it appears that there were null rooms. I removed them and now the app is working as expected.
But maybe these rooms should be somehow avoided / auto cleaned?

**Comment by mario** [comment]
I can NOT show them. Dunno why they would appear.

**Comment by nickvergessen** [comment]
Server/update issue => https://github.com/nextcloud/spreed/pull/606
