### ISSUE TITLE
Don't receive any notifications

### ISSUE THREAD

**Issue by Sim59121** [nextcloud/talk-android#731]
Hello,

I have nextcloud Talk for android on my phone and i have a problem ! 
i don't receive any notifications...

I have download the app with F-Droid and i have allowed notifications for the app but i don't see new call, chat etc...

For see them, i must open frequently the application for check my messages because i don't receive notifications for new chat, incoming calls etc...

I have a samsung J5 2016 (SM-J510FN) with android 7.1.1

Regard,

**Comment by mario** [comment]
F-Droid  does not support notifications.

https://github.com/nextcloud/talk-android/issues/257
