### ISSUE TITLE
Not possible to reply in android client

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/talk-android#733]
Not possible to reply to messages in Nextcloud Talk Android client, additionally, it is not possible to mark respondents using @.

**Comment by mario** [comment]
I transferred the issue to the proper repository. 

a) To reply long click on a message.
b) Why is it not possible to use @?

**Comment by ostasevych** [comment]
> I transferred the issue to the proper repository.
> 
> a) To reply long click on a message.
Long click leads to appearing copy function.
> b) Why is it not possible to use @?
Ah, I got! It's necessary to add @ manually, I thought, you may click on icon of the user and select one. Thanks!

**Comment by ostasevych** [comment]
Plus, it is good to have Forward and Delete functions.

**Comment by ostasevych** [comment]
> I transferred the issue to the proper repository.
> 
> a) To reply long click on a message.

With long click I'm getting only Copy.

> b) Why is it not possible to use @?

Ah,I see. I thought, I may point at a user's icon to add him/her instead of manually entered @eppfel 

Please, add Forward and Delete functions as well - to manage with a post.

**Comment by mario** [comment]
You need Nextcloud 18 to get a reply function. 

As for other functions, we're considering it.
