### ISSUE TITLE
Allow to swipe away call notifications

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#736]
### Steps
1. Colleges have a call in a group conversation
1. Phone vibrates for 45s and there is no way to stop it
1. Notification can not be swiped to dismiss it and stop the vibrating
1. After vibration stops, it's still not possible to swipe away the notification, so it looks like you are always in a phone call
![Screenshot_2020-02-18-11-22-25-147_com miui home](https://user-images.githubusercontent.com/213943/74727469-7e16d980-5241-11ea-8600-88c465935ed8.jpg)
![Screenshot_2020-02-18-11-26-56-952_com google android apps photos](https://user-images.githubusercontent.com/213943/74727676-d2ba5480-5241-11ea-80a9-1e13df9a634f.jpg)

**Comment by nickvergessen** [comment]
So after further testing when tabbing the notification, an actual call screen shows up.

**Comment by mario** [comment]
Swiping the notification will not be possible, but I can add a "Reject call" action if you want.

**Comment by nickvergessen** [comment]
I need something to stop my phone from vibrating 45s and draining my battery by 1% when I'm busy, yes please

**Comment by mario** [comment]
This is a lot more complicated to rewrite that I initially thought, so will be out in v9.0.0beta.
