### ISSUE TITLE
Pressing on the text of a message triggers the built-in Text-menu that cannot get dismissed until you press back or select one of the options

### ISSUE THREAD

**Issue by szaimen** [nextcloud/talk-android#739]
As the title says.

I am currently on 8.0.3
Android 10

Better would be if I could press anywhere on the screen to dismiss the built-in text menu. (Or maybe don't show it at all?

Look at this screenshot:
![Screenshot_20200226-235824_Nextcloud Talk](https://user-images.githubusercontent.com/42591237/75396243-5a642b00-58f4-11ea-8712-bb0265c5e1ae.png)

**Comment by mario** [comment]
Hm thanks for the report, I thought I disabled the text menu. Will check.

**Comment by mario** [comment]
This is disabled in v9.0, so "fixed" :)
