### ISSUE TITLE
Translation change

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#744]
Use "Du: " instead of "Sie: "
![Screenshot_20200228-183440](https://user-images.githubusercontent.com/24530680/75664483-d4890c80-5c72-11ea-84ad-34071204eb70.jpg)

If "Du" is selected in the settings -> language
![grafik](https://user-images.githubusercontent.com/24530680/75664637-11ed9a00-5c73-11ea-837a-fe2fbb2364e3.png)

In the current version "Sie: " is always set.

**Comment by mario** [comment]
I really don't think Android supports this - we've had this issue before. @nickvergessen maybe you remember what was the verdict?

**Comment by nickvergessen** [comment]
Well I stand with the same. Im not sure how you decide the language. But if I set my Nextcloud profile to Du I would expect Du in the apps aswell.

**Comment by mario** [comment]
It doesn't look like this is possible on Android (through existing localization methods) so I'll close the issue. If someone finds a way to prove me wrong, I'll happily make it happen.
