### ISSUE TITLE
Nextcloud talk app continues call after server is shutdown

### ISSUE THREAD

**Issue by Gregory92** [nextcloud/talk-android#749]
Hello,

This isnt really an issue, more so a technical question on how nextcloud talk on android connects calls. After making a call and connecting with another user, we determined to reboot the server to fix some connectivity issues we were having. However, after the virtual machine was shut down AND the host computer shutdown, the call was still connected and audio was still passing through. I was under the assumption that all calls were encrypted through the server,  but since the server was shut down, I am just curious how the call was still connected and active and seemingly working? After the initial call is made and members are connected, is the call still secure and routed through the server, or is there something else going on? My client was just concerned that since the server was shutdown that information/contents of the call were being routed elsewhere unencrypted. 

Keep up the great work! Other than this head scratcher, the apps seems to be working well 90% of the time and we are very pleased!

Thank you, 

Gregory Boga

**Comment by mario** [comment]
There is no host computer really. What happens is that the server (and STUN/TURN) act as a mediator between all relevant parties to establish fully encrypted peer-to-peer connection.
