### ISSUE TITLE
Don't show a calling screen for group calls

### ISSUE THREAD

**Issue by schiessle** [nextcloud/talk-android#751]
I noticed that since some time, can't name the exact version when it started, the Android app opens a normal calling screen (like for 1:1 calls) when a group call started. Interestingly this only happens when the phone is locked while the call started. When the phone is unlocked I get a notification, as it should be. But also the notification behaves strange because my phone still rings/vibrates and doesn't play the normal notification sound, that's probably the same as @nickvergessen already noticed https://github.com/nextcloud/talk-android/issues/736 but I think the calling screen on a locked phone wasn't reported yet.

**Comment by mario** [comment]
Yea, I'll fix this.

**Comment by nickvergessen** [comment]
Well the call screen is fine. The vibrating is the real problem and that is being dealt with in #736 So this could also be closed.

**Comment by Ivansss** [comment]
> Well the call screen is fine.

We never showed a full incoming call screen for group calls and I think that should not be the case.

We should just show a normal notification when receiving a group call (That's how it is on iOS since the beginning).

**Comment by schiessle** [comment]
> We never showed a full incoming call screen for group calls and I think that should not be the case.

I agree with Ivan that a full call screen which interrupt you from whatever you do at the moment is way to intrusive for a group call. Older versions only showed the notification and I think that was the right behavior.

**Comment by mario** [comment]
The question is: should it ring/vibrate then like a phone call? Or only notify you like a message notification?

**Comment by mario** [comment]
Making it act like a normal notification for now, like it was earlier.

**Comment by mario** [comment]
Not entirely happy about it, but meh.

**Comment by mario** [comment]
Also keep in mind that this means group/public calls (like messages) are not very likely to wake up your phone.

**Comment by mario** [comment]
Was not trivial, but I got it done. Will be in 9.0.

**Comment by schiessle** [comment]
> Making it act like a normal notification for now, like it was earlier.

I just realized that my phone still rings when a new group call started. Wasn't it supposed to be fixed in one of the last minor release or did you only fixed the vibration-thing for now and the rest will come in v9.0?

**Comment by mario** [comment]
@schiessle like I said in my latest reply to this ticket, the rest will come in v9.0. The code is already there, but it's involved and given my lack of time and workload, backporting this is not an option.

**Comment by schiessle** [comment]
Thanks, I was just confused if it should be fixed already or not... :smile:
