### ISSUE TITLE
No notifications on Huawei EMUI 9.1.0.241

### ISSUE THREAD

**Issue by RIS2000** [nextcloud/talk-android#752]
Hello!
Trying to get notified when message or call occurs, but to no avail.
All energy savers disabled.
On Xiaomi MIUI notifications working well.

**Comment by mario** [comment]
I have the same phone and it seems to work.

Two things to try:
a) reboot the phone
b) delete the account and add it again in the app

**Comment by mario** [comment]
Closing - but please let me know if above doesn't help you.

**Comment by RIS2000** [comment]
Things helped. Thank you.
But there is other issues, where notifications become registered for app every time call occurs.
I will open another issue.
