### ISSUE TITLE
Change mic input level

### ISSUE THREAD

**Issue by doitux** [nextcloud/talk-android#755]
It would be great to have an option to change the mic input level on the device. Especially when try to play music through nc-talk the android mic level seems to be to high and cuts of to zero when the input is to loud.

**Comment by mario** [comment]
I'm pretty sure this is not available on Android. Are you aware of any API that would allow me to do so?

**Comment by doitux** [comment]
Unfortunately not. I'm not familar with android development.

**Comment by mario** [comment]
Not possible as far as I know :( Sorry.
