### ISSUE TITLE
Double push notification sound

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#756]
At the first push notification, the sound is played twice. The sound is played correctly the next notifications.

Steps:
1. Receipt of one push notification **(sound played twice)**.
2. Receipt of the second notification (playback sound correctly).

App:
Android 10
Talk Android 8.0.3
Talk Nextcloud 8.0.5
Nextcloud 18.0.1

**Comment by mario** [comment]
Sounds strange. But let me postpone this bug until 9.0 is out so we'll see if its fixed then.

**Comment by jmhammond** [comment]
Sorry to comment on an closed issue, but this is happening on Android 10 on my device as well, exactly as described by @Valdnet.

**Comment by Valdnet** [comment]
Issue reopened. I think this should be reviewed and improved in version 8.

**Comment by mahibi** [comment]
thanks for reopening @Valdnet

**Comment by jakobroehrl** [comment]
I can confirm this problem, too.

**Comment by 0ranki** [comment]
I commented on another issue about this, didn't notice this one first.

[Link](https://github.com/nextcloud/talk-android/issues/892#issuecomment-827425622)

**Comment by Valdnet** [comment]
@mahibi Can you take a look at this problem?

**Comment by mahibi** [comment]
@Valdnet sorry not in the near future i guess, lots of other stuff to do atm

**Comment by Valdnet** [comment]
@mahibi and @AndyScherzinger While testing Apha 16 version 12.0.0, I noticed the following event:

1. Receive the message (there is a double beep).
2. Read it in Talk in the Nextcloud instance.
3. Exit Talk in the Nextcloud instance.
4. Receive the next message (there is one beep even though the previous message has been read in the Talk of the Nextcloud instance).

The message notification sound is now correct (only beep once) until you have not read the message by Android Talk.

It can be concluded that as long as the PUSH notification is active on the smartphone, the sound is played correctly (once). The error is not related directly to the received unread message.

**Comment by starypatyk** [comment]
This seems to be caused by the fact that since Android 8 (Oreo) notification sounds are handled by the system - as described in this article: [Create and Manage Notification Channels](https://developer.android.com/training/notify-user/channels).

@mahibi - if nobody is working on this, I should be able to devote some time over the next few weeks to try to make some improvements this area.

**Comment by mahibi** [comment]
> @mahibi - if nobody is working on this, I should be able to devote some time over the next few weeks to try to make some improvements this area.

sorry for the late answer @starypatyk , was on sick leave for a while. Thank you for working on this! :+1:
