### ISSUE TITLE
Disable proximity sensor for video calls

### ISSUE THREAD

**Issue by chaptergy** [nextcloud/talk-android#758]
Please disable the proximity sensor or at least add the option to do so for video calls. I can't think of a use case, where I would hold the phone to my ear while my video is active. But I have the issue, as soon as I get too close to my phone (~20cm), It turns the screen off and routes the audio through the earpiece, and sometimes it does not turn back, before I manually trigger the proximity sensor and remove my hand again.

**Comment by mario** [comment]
Not turning it back (might) be a bug, but this is how it for most messengers as far as I know. In addition, switching from a video to audio communication is easier this way.

So it's a "no" for now, but not definite - it more people express concern with the way things are now, we might change it.
