### ISSUE TITLE
possible to make video calls to three or more users?

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/talk-android#76]
And in anticipation of opportunities to make video calls to three or more by applying nextcloud talk from mobile as already happens by browser? allow you to add more users to a video call. from mobile I mean.

**Comment by mario** [comment]
You can create a call with more users on the web, and then join the call on the mobile. Mobile will get the opportunity to create group/public calls a bit later.

**Comment by mario** [comment]
See #74.
