### ISSUE TITLE
conversations won't load last messages

### ISSUE THREAD

**Issue by guzzisti** [nextcloud/talk-android#761]
Applied the latest beta update from Google Play Store yesterday which was meant to fix double messages.
Opening a conversations from the converation list won't load the conversation anymore. When entering the conversation the loading indicator is shown and won't go away.

This happens on both of my instances.

Nextcloud: 18.0.2
Talk-Version: 8.0.5
App-Version: 8.0.5
OS: Android 8.0 (Samsung Stock ROM)

**Comment by mario** [comment]
Hi, thanks for the report.

Can you try v8.0.7 and send me a test account to mario@nextcloud.com? Thanks!

**Comment by jookk** [comment]
V.8.0.7 too

**Comment by mario** [comment]
Okay I can reproduce. Let me try to fix this.

**Comment by jookk** [comment]
Fixed, very thans ✅

**Comment by mario** [comment]
Thanks for the patience!
