### ISSUE TITLE
Nextcloud Talk stucks loading conversations

### ISSUE THREAD

**Issue by TheNablaOperator** [nextcloud/talk-android#763]
### Expected behaviour
- Showing conversations properly.

### Actual behaviour
- Conversations get stuck in loading (using WIFI and LTE)
- I get Notifications, and also see the last message partly in the conversation overview list.

### Environment data
Android version:
10
Device model: 
Sony Xperia XZ2 Compact
Stock or customized system:
Stock
Nextcloud app version:
NC: 3.10.1 / Talk: 8.0.8

**Comment by mario** [comment]
This should have been fixed with 8.0.8 and it did for most people I know. Can you please reinstall the app?

**Comment by TheNablaOperator** [comment]
I already reinstalled it yesterday...
But let's try again.
I just closed the app, cleared the cache and de-installed it. -> restarted my phone -> Installed it again.
Same Behaviour. :(

**Comment by mario** [comment]
Can you send me a test account to mario@nextcloud.com? Then I can check it out.

**Comment by TheNablaOperator** [comment]
Sorry a test account is not possible, I'm not the admin. The Nextcloud service is provided by our university.
I know from a colleague, she is using the iOS app, that the service works on her iPhone properly.

**Comment by mario** [comment]
Not much I can do then since I unfortunately can't debug. :-/

**Comment by TheNablaOperator** [comment]
I can check with the local admin.

**Comment by TheNablaOperator** [comment]
Hey Mario.
I just tried something else.
I deleted the phone from the scurity tab in the cloud. Then reinstalled the app.
Now it's working :)

In case someone has the same problem at the beginning:
shut down the app, delete its cache, remove the phone from the security tab in the cloud and restart the whole thing. Worked for me!

**Comment by mario** [comment]
This was something with your app token then. But glad it's working now :)

Cheers! :)

**Comment by dvergeylen** [comment]
Had the same issue. Upgrading to 8.0.8 solved the issue. Thanks! 🙂 👍
