### ISSUE TITLE
Notifications become registered for app every time call occurs.

### ISSUE THREAD

**Issue by RIS2000** [nextcloud/talk-android#764]
![изображение](https://user-images.githubusercontent.com/30177105/77454115-29025080-6e09-11ea-80e8-eb4692dc5599.png)

And that's added every time the call occurs.

**Comment by mario** [comment]
I'll check it out. Should not happen.

**Comment by RIS2000** [comment]
This is on EMUI 9.1.0

**Comment by mario** [comment]
Found it. Will be fixed - thanks for reporting.

**Comment by RIS2000** [comment]
Fast reaction!
Thank you

**Comment by mario** [comment]
Seems fixed, let me know if it happens once v9.0 is out.
