### ISSUE TITLE
cannot dial-in as first attendee, only into existing call

### ISSUE THREAD

**Issue by fajabird** [nextcloud/talk-android#765]
Server-side I'm running Nextcloud on a Server with a public IP - no NAT. All updated to lastest version available in Archlinux repos (Nextcloud 18.0.3, Talk-plugin/app 8.0.5). I'm using the Two-Factor TOTP Provider plugin for authentication. 

Client is a Android-10 mobile device with Nextcloud-Talk app from F-Droid (8.0.6). I managed to authenticate via App-Token (there seem to be a bug - the app jumps in less than a second to plain username/password login, but after few tries I managed to hit the "login via app-token" button). 
All chats are visible inside the app and text-messages just work fine. But when I hit the Audiocall/Videocall button the app rings until hits the 45 seconds timeout. When I start the call from within e.g. a browser session on my PC (also tested when PC is on completely different network), I than can also dial-in from the app into that existing call.

**Comment by mario** [comment]
I don't know if this is related, but you should definitely use username/password login and not app-token login as the app then generates the token itself.

**Comment by mario** [comment]
Thanks for the report btw :)

**Comment by mario** [comment]
Could you try this between the two phone devices?

Also, do you have a TURN server in place?

**Comment by fajabird** [comment]
Hi, yes I installed coturn right away - seem to work as I can do calls but only "join" from the android app to an already ongoing call. 

I reinstalled the app and followed your instructions to login. BTW. when I enter the server URL manually instead of importing from nextcloud-app then I can login normally and am prompted to enter the OTP-token as well. This did not work when importing from nextcloud-app - but thats  a different story.

Still same issue - cannot initiate call. How can I test if TURN server works correctly other than establishing a call? BTW. Server is in a Datacenter - so definetly in a different network than all clients - to my understanding this only works if TURN server is working - right?

**Comment by mario** [comment]
Funnily enough it seems I can reproduce the problem - but I've never seen it so far. Let me do some more testing and I'll get back to you.

As for importing - sounds strange, but I'm going to rewrite the import process in the future anyway so we'll see.

What I asked above is can you confirm that you see the same issue if you try to call from one android phone to another? What I'm trying to see if this is a Web UI problem somehow as in my testing two android (or an android and an iOS phone) connect just fine.

**Comment by fajabird** [comment]
Sure - but how can I call a phone? Do mean  -> "+" -> Username ?

**Comment by mario** [comment]
Yes. You basically need another user.

**Comment by fajabird** [comment]
OK installed the android-talk app on another mobile device with different user. Calling the other user did also not work - text-messages do work though. 

Question: as I always installed from f-droid I guess the app will not register any push-service. Therefor even Text-Messages are not signaled on  the other device when the app is not in foreground - right? Can this also impact audio/video calls for the test?

**Comment by mario** [comment]
Nah, lack of notifications shouldn't interfere with your ability to call.

**Comment by fajabird** [comment]
BTW. if I shutdown the TURN-Server I experience the same result with the difference that of course without TURN I will not get the other members video/audio. But joining-wise the same problem.

**Comment by mario** [comment]
@danxuliu this seems to be the problem lately, and nothing regarding calling changed on the Android app :-/

**Comment by nickvergessen** [comment]
Hello there,

we are currently cleaning up old/stray github issues. Can you please retry with the current version and report back if the problem still persists for you?

cheers
