### ISSUE TITLE
Android/iOS Talk App could not connect to STUN/TURN Server

### ISSUE THREAD

**Issue by michi8c** [nextcloud/talk-android#767]
Hi,

not quiet sure if this is the right place for this - so if not, sorry! :)

I've setup a NC 18.0.2 with application Talk and a STUN/TURN service on same machine. 
It is all running fine in the browser (desktops and mobiles) - but the Talk App (Android and IOS) can't connect video/sound stream.
More see my entry in NC community: https://help.nextcloud.com/t/android-ios-talk-app-could-not-connect-to-stun-turn-server/74389

Best regards
Michael

**Comment by mario** [comment]
STUN and TURN need to be on the  public internet, not behind NAT.

Sorry :)

**Comment by jedwabny** [comment]
Hi Mario,
I'm sorry for the question but are you sure for the STUN/TURN behind the NAT?:(

In /etc/turnserver.conf of coturn we can find the external_ip option.
Isn't it working solution? 

> # For Amazon EC2 users:
> #
> # TURN Server public/private address mapping, if the server is behind NAT.
> # In that situation, if a -X is used in form "-X <ip>" then that ip will be reported
> # as relay IP address of all allocations. This scenario works only in a simple case
> # when one single relay address is be used, and no RFC5780 functionality is required.
> # That single relay address must be mapped by NAT to the 'external' IP.
> # The "external-ip" value, if not empty, is returned in XOR-RELAYED-ADDRESS field.
> # For that 'external' IP, NAT must forward ports directly (relayed port 12345
> # must be always mapped to the same 'external' port 12345).

> #
> # In more complex case when more than one IP address is involved,
> # that option must be used several times, each entry must
> # have form "-X <public-ip/private-ip>", to map all involved addresses.
> # RFC5780 NAT discovery STUN functionality will work correctly,
> # if the addresses are mapped properly, even when the TURN server itself 
> # is behind A NAT.
> #
> # By default, this value is empty, and no address mapping is used.
> #
> #external-ip=60.70.80.91
> #
> #OR:
> #
> #external-ip=60.70.80.91/172.17.19.101
> #external-ip=60.70.80.92/172.17.19.102

**Comment by mario** [comment]
No, but that's pretty much how I've used it so far and I don't have any other information. 

If you can configure it otherwise/make it work otherwise, I'm more than happy to change my stand and "fix" the documentation.

**Comment by jedwabny** [comment]
Unfortunately, I'm not able to make it working that way. I just hoped that I do some mistake.

**Comment by michi8c** [comment]
> STUN and TURN need to be on the public internet, not behind NAT.
> 
> Sorry :)

Hi mario,

just for my understandig - why does STUN and TURN need to bo on public internet?
I've configured external_ip like jedwabny commented - otherwiles the whole NC talk wouldn't work.. 
My question is, why is the mobile app acting in an other way than the webbrowser? -> In browser all is working fine with TURN/STUN - my server behind NAT is available from outside.
Just the app seem not to connect on the default ports like configured in NC Talk config:
![image](https://user-images.githubusercontent.com/28434601/77651529-37697d00-6f6d-11ea-8c16-d4803bae49ec.png)

**Comment by michi8c** [comment]
Hi @mario ,

i found the problem for me - it was no app problem :) (see for details here: https://help.nextcloud.com/t/android-ios-talk-app-could-not-connect-to-stun-turn-server/74389/6 )

So i've a working NC Talk App over NAT.
Maybe interesting for others here my coturn configuration:

```
external-ip=<myexternalip>/<myinternalip>       # e.g. 10.10.10.10/10.20.20.20
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=<myturnsecret>
realm=cloud.<mydomain>.de
total-quota=100
bps-capacity=0
stale-nonce
cert=/etc/pki/tls/certs/<mycert>.cer
pkey=/etc/pki/tls/private/<myprivate>.key
cipher-list="ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384"
log-file=/var/log/coturn/turnserver.log
simple-log
no-multicast-peers
```

Best regards
Michael

**Comment by mario** [comment]
Awesome, thanks for sharing
