### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by renatobellotti** [nextcloud/talk-android#768]
I cannot login to my fresh nextcloud installation. I am using the configuration from the [examples page](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm).

What happens:

- I select to use the account from my Android Nextcloud app (which is working).
- I have to enter my password. If the password is incorrect, I get an error message saying that it is correct. If it is correct, however, I get an endless "Signing in" message.

I am running my nextcloud at a non-standard port. Might this be a problem? The main app and the web interface work without problems.

I am looking forward to hear your suggestions.

**Comment by maxxberg** [comment]
I have the same issue with Talk and the Nextcloud Docker image. 
Nextcloud version is 18.0.3 with apache.
When I try to login the button has an endless spinning circle with "Signing in". After some time the server log says the password would be incorrect. I checked it several times.
It doesn't matter if using password or app token.

**Comment by mario** [comment]
This is a server setup issue. Maybe 'overwritehost' => '', configuration option can help as it did for other.

**Comment by renatobellotti** [comment]
I don't think this is a server issue. I can still login and have calls in the web interface.

**Comment by Ivan-Roger** [comment]
@mario This issue still seems to be happening to me, the server considers the login attempt as a bruteforce attack. Do you have any recommendation on how to fix this ? The `overwritehost` option didn't seem to help.

**Comment by isdnfan** [comment]
take a look at this forum discussion: (https://help.nextcloud.com/t/caldav-calendar-certificate-issue-in-local-network/89269/5)
