### ISSUE TITLE
Notifications for google version no longer working

### ISSUE THREAD

**Issue by 05nelsonm** [nextcloud/talk-android#769]
Push notifications for GCM no longer seem to be working since about 2 weeks ago.

Tried re-flashing my phone and the app won't even register with MicroG's GCM service. Every other app register's just fine.

My Nextcloud instance app v8.0.5
Android App version 8.0.8

**Comment by 05nelsonm** [comment]
After uninstalling both the Nextcloud App (Google Version which was registered for GCM), and Nextcloud Talk (Google Version which was NOT registering for GCM), then installing Nextcloud Talk (Google Version), it registered.

I just installed the F-Droid version of the Nextcloud App to avoid any conflicts, but something's definitely up there.

**Comment by mario** [comment]
No idea. It's possible it's due to a newer version of fcm client libs.

**Comment by hashworks** [comment]
Same here, no notifications at all in the Nextcloud or Nextcloud Talk apps (both from Google Play). Reinstallations don't seem to fix the issue.

**Comment by 05nelsonm** [comment]
> Same here, no notifications at all in the Nextcloud or Nextcloud Talk apps (both from Google Play). Reinstallations don't seem to fix the issue.

Yeah, I noticed while testing that sending a message via talk would proc the Nextcloud App's GCM event but not display a notification.

That's why I installed the FDroid version of the Nextcloud App and the GPlay version of NC Talk.

**Comment by mario** [comment]
So I don't really know how to test this. @tobiasKaminsky do you still have a Lineage with MicroG installed? Do notifications work for you?

**Comment by tobiasKaminsky** [comment]
Yes and yes.
According to MicroG, NC Talk received 5min ago a push notification.

**Comment by mario** [comment]
*shrug* So something phone specific.

**Comment by ubuntiger** [comment]
I can confirm that "Push notifications for GCM do not seem to work" for me either.
The app won't register with MicroG's GCM service on my phone either.
I cannot tell if they ever worked, because I installed for the first time.
Telegram from Playstore and "Push Notification Tester" by Bernd Bindreiter
from PlayStore both do register and Push Notification Tester reports
"Your phone can receive push notifications without any problems."

I observe that the NC Talk App get's stuck when registering the account.
It keeps circling the progress bar endlessly.
But if I terminate the app and restart it, the account is available in talk.

My setup:
Xiaomi Mi8 with LineageOS for MicroG:
https://download.lineage.microg.org/dipper/
lineage-16.0-20200324-microG-dipper.zip
MicroG Selftest all checks OK = hooks set
Nextcloud Talk Android App 8.0.8 from PlayStore
Nextcloud 18.0.3 on Fedora 31 5.5.15-200.fc31.x86_64
All devices in local WLAN.

I can provide additional information / do testing on the Mi8 if it helps.

**Comment by ubuntiger** [comment]
> Yes and yes.
> According to MicroG, NC Talk received 5min ago a push notification.

May I ask which Version of NC Talk you used?

**Comment by tobiasKaminsky** [comment]
> I observe that the NC Talk App get's stuck when registering the account.
> It keeps circling the progress bar endlessly.
> But if I terminate the app and restart it, the account is available in talk.

Adding account and registering for push are two tasks. So if account adding is working and it hangs on registering for push then it makes sense that you have a working talk without push.



> @tobiasKaminsky May I ask which Version of NC Talk you used?

Latest one, yesterday 8.0.8 and now 8.0.9.

**Comment by ubuntiger** [comment]
> Adding account and registering for push are two tasks. So if account adding is working and it hangs on registering for push then it makes sense that you have a working talk without push.

Indeed I have a working Talk 8.0.9 from PlayStore on all my three phones now, all LineageOS, but on the two phones with MicroG push does not work, I do not get notifications, neither text nor sound. On the third phone with OpenGapps "stock" push does work, I get notifications incl. sound. So @mario  I suppose it is rather the combination of Talk with MicroG than
> something phone specific.

@tobiasKaminsky Do you think I can help, with debugging, e.g. providing logs, or testing?

**Comment by hashworks** [comment]
I don't have MicroG installed, just normal Google Play Services on a stock Motorola Z2 Play. Nextcloud is installed over FDroid and Nextcloud Talk over the Google Play Store.

Can you recommend ways to debug this?

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky Do you think I can help, with debugging, e.g. providing logs, or testing?

> Can you recommend ways to debug this?

I am only aware of the usual push testing: install push notification tester and see if this works.
But if this works, and Files or Talk does not work, I am really out of clue :/

**Comment by mario** [comment]
Issue is in the version of the firebase messaging lib. We need to revert to
some older version but I need to find which one :p

**Comment by tobiasKaminsky** [comment]
Files used 17.3.0 from 09/18 till 03/20 and suddenly the error occurred.
Switching to latest 20.1.3 did not helped.

https://github.com/nextcloud/android/issues/4675 here we can see that this happened on both version…

**Comment by mario** [comment]
@tobiasKaminsky according to one user 17.3.4 has no issues so I'll switch to that.

**Comment by tobiasKaminsky** [comment]
Nice. 
I will wait a bit, if this is indeed working and then also switch.

**Comment by tobiasKaminsky** [comment]
Hey,
Android files app has this porblem for some users/devices. Can you confirm that this fcm version fixed it?

**Comment by mario** [comment]
Yes, it seems to work so far @tobiasKaminsky

**Comment by DDArn** [comment]
On our three family mobiles with talk 8.0.9 two have text and tone notification an the huawei Mate 8 has not. Chat ist no problem if the talk window is open. If I close the phone I do not get any notification. The trhree phones have Android 7, 8, and 10
