### ISSUE TITLE
No notification on LineageOS 14.1

### ISSUE THREAD

**Issue by kafisc** [nextcloud/talk-android#77]
Hello,

i'm on a Moto Z Play LineageOS 14.1 and i do not get notifications for incoming calls (I do not use gapps).
Does the notifications depend on the gapps framework?

I do not have another LineageOS 14.1 phone so i can't cross check.

Thank you in advance
kafisc

**Comment by mario** [comment]
You need either gapps or microg. I just learned today there is a Lineage with MicroG already installed.

https://lineage.microg.org/

**Comment by krodelabestiole** [comment]
hi @mario , and thanks for your great work.

I think people who use nextcloud often want to avoid google services as much as possible.
and we often install lineageos for the exact same reason.

therefore I think an alternative to Gapps (whether "open" or not) would be much appreciated.

I already use linphone and xabber without gapps at all, and I guess they keep it on using their own services. 

I think it would be great if talk-android was behaving the same !

**Comment by mario** [comment]
You avoid Google services via MicroG 99,99%. The only thing is that messages are still sent via FCM, but they're encrypted and don't contain any useful content. 

Starting next release, we'll have a version on F-Droid that runs without Google, but also without push notifications.

**Comment by krodelabestiole** [comment]
ok I didn't knew about MicroG. I doubled checked and you convinced me ;)

I've just upgraded 3 devices to LineageOS for microG (using the [migration zip](https://download.lineage.microg.org/extra/) then flashing the rom) and it worked fine. I had to activate everything about MicroG, reboot, and reinstall Nextcloud Talk.

thanks for the tip :)
