### ISSUE TITLE
openssl_sign(): supplied key param cannot be coerced into a private key

### ISSUE THREAD

**Issue by tdm4** [nextcloud/talk-android#773]
Hi,
   In my nextcloud log file, whenever an Android Nextcloud Talk client logs in, my nextcloud log files are cluttered with:

```
{"reqId":"mhYp8gXuHrYu1Co06k4I","level":3,"time":"2020-04-01T11:07:41+01:00","remoteAddr":"192.168.1.7","user":"someone","app":"PHP","method":"POST","url":"/ocs/v2.php/apps/notifications/api/v2/push?proxyServer=https%3A%2F%2Fpush-notifications.nextcloud.com&devicePublicKey=<PUBLIC KEY CONTENTS HERE>%20PUBLIC%20KEY-----%0A&pushTokenHash=ca4022f2ef1358fca35ab47dbc0ae46c69e80e83c14ee1a579d865dd5647c4c1255654fc2741aa27cc0766a6f8b42b5b3ef549206bc4e0ff287082d91e8579b4&format=json","message":"openssl_sign(): supplied key param cannot be coerced into a private key at /nextcloud/apps/notifications/lib/Controller/PushController.php#121","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v8.0.8","version":"18.0.1.3"}
```

Any ideas on how to fix this?

**Comment by mario** [comment]
Sounds bad? What version of the client, what server version, php version,etc?

**Comment by tdm4** [comment]
Hi @mario ,

  PHP 7.3.16
  NextCloud Server 18.0.1
  NextCloud Talk 8.0.5

  Deleting rows in `oc_notifications` and `oc_notifications_pushtokens` clears it but it comes back. Have seen this also with someone connecting in with web client to Talk.

  Does Nextcloud Talk use the pushtokens to notify people there's a call, and whether other people join them? The person who had this problem with the web browser was attempting to connect to a call and they never connected.

**Comment by tdm4** [comment]
Also:


OpenSSL support | enabled
OpenSSL Library Version | LibreSSL 3.1.0
OpenSSL Header Version | LibreSSL 3.1.0
Openssl default config | /etc/ssl/openssl.cnf

openssl.cafile  and openssl.capath don't appear to have a value.
I'm running NextCloud in OpenBSD in /var/www chroot, and yes I have copied cacert.pem and openssl.cnf to the `/etc/ssl` directory relative to that chroot.

So I'm not sure what else it could be.

**Comment by mario** [comment]
I wonnder if this could have anything to do with OpenBSD :(  @nickvergessen ideas?

**Comment by tdm4** [comment]
@mario @nickvergessen - This is in the pkg-readme for PHP 7.3:
```
PHP's OpenSSL functions
=======================
The chroot jail commonly used with PHP on OpenBSD means that only files
inside /var/www can be used. Functions for making TLS connections usually
need access to CA certificates, and key generation functions may need
access to configuration files.

To use these, copy the relevant files into the /var/www jail:

    # mkdir -p /var/www/etc/ssl
    # install -m 444 -o root -g bin /etc/ssl/cert.pem /etc/ssl/openssl.cnf \
          /var/www/etc/ssl/

As these files are updated from time to time, you might like to add
the above "install" line to /etc/rc.local.
```

I do have `/etc/ssl/cert.pem` and `/etc/ssl/openssl.cnf` copied into the chroot, so the openssl functions should be OK. I wonder if the hash function is what's causing the problem?

```
 openssl_sign($deviceIdentifier, $signature, $key->getPrivate(), OPENSSL_ALGO_SHA512);
```

Maybe LibreSSL doesn't like it? I'm not sure. Would I be able to test this in some way?

**Comment by tdm4** [comment]
Does Nextcloud need a private key generated for these pushtokens?
I searched through the nextcloud web root and couldn't find any pem or key files.

**Comment by tdm4** [comment]
Hmm.. if I run `occ security:certificates`, am I supposed to see any certificates?
```
# doas -u www /usr/local/bin/php-7.3 -f ./occ security:certificates      
+-----------+-------------+--------------+-------------+-----------+
| File Name | Common Name | Organization | Valid Until | Issued By |
+-----------+-------------+--------------+-------------+-----------+
```

**Comment by nickvergessen** [comment]
thats something else.

In your data directory, do you see a key (private + public) in `appdata_SOMERANDOMCHARS/identityproof/user-someone`
And are they valid?
Sizes should be about 3.6kb (private) and 451 bytes (public)

**Comment by tdm4** [comment]
> thats something else.
> 
> In your data directory, do you see a key (private + public) in `appdata_SOMERANDOMCHARS/identityproof/user-someone`
> And are they valid?
> Sizes should be about 3.6kb (private) and 451 bytes (public)

Ahh! Well.. the public file is 0 bytes.
The private fie just looks like 178 characters all on one line.

Both are from March 2018. Should they be removed and regenerated somehow?

**Comment by nickvergessen** [comment]
You also need to delete the traces in the `oc_filecache` table for `appdata_SOMERANDOMCHARS/identityproof/user-someone`, `appdata_SOMERANDOMCHARS/identityproof/user-someone/private` and `appdata_SOMERANDOMCHARS/identityproof/user-someone/public`  (but only those 3 entries ❗️  ) and then delete the complete folder for the user.

If that doesn't work, ask for help in the forums please: https://help.nextcloud.com/

I'm closing this as it is not a but in Talk or the Talk Android app

**Comment by tdm4** [comment]
@nickvergessen @mario - Can confirm 100% this fixed all the issues where some people were trying to connect to an ongoing nextcloud talk call and couldn't. So yes, while this was a greater 'nextcloud' problem not particularly limited to Nextcloud Talk itself, it still affected it (and probably affected other parts of the Nextcloud ecosystem that use pushtokens/push notifications)
