### ISSUE TITLE
Microphone changes input level if headphone is connected

### ISSUE THREAD

**Issue by username72764274** [nextcloud/talk-android#774]
Without a connected headphone the volume of the microphone is loud enough for the other participant. As soon as a headphone is connected (via audio jack), the input level of the microphone changes. This results in a low volume audio received by the other participant. This makes it difficult to do video calls this way, as the volume is often to low. 
As soon as the headphone is disconnected, the input level of the microphone is increased again.

I would expect that the input level of the microphone stays the same regardless whether a headphone is connected or not.

**Comment by username72764274** [comment]
After doing some tests with different devices and applications, it turned out, that this issue only appears on my smartphone and occurs with different applications. This issue has nothing to do with nextcloud talk itself.

**Comment by mario** [comment]
Thanks for testing this and following up, really appreciate it.
