### ISSUE TITLE
History doesn't appear to be cached.

### ISSUE THREAD

**Issue by mackenzie-1k4** [nextcloud/talk-android#780]
On v8.0.8, when switching between conversations, or switching back to the app after a while, the entire conversation history scrolls by. This has been happening since the last release.

**Comment by mario** [comment]
I'm not sure I understand? It shouldn't fetch the whole history (just a part of it), but we indeed don't cache anything in v8.0.8.

**Comment by mackenzie-1k4** [comment]
To clarify, when I switch between conversations, or switch back to the app after a while, quite a bit of conversation history scrolls by, which takes around 10-15 seconds. Previously, with older versions, the most recent history seemed to be immediately displayed.

**Comment by mario** [comment]
I can't reproduce, but since I'm rewriting this part let's assume it'll be fixed with 9.0 :)

**Comment by mackenzie-1k4** [comment]
Great! :-) Keep up the good work.
