### ISSUE TITLE
Android Talk app crash after select shared Folder

### ISSUE THREAD

**Issue by Maggi68** [nextcloud/talk-android#783]
### Steps to reproduce
1. Admin create users and invite them to a group
2. share folders to group of users and save files in the folders and outside (toplevel)
3. Admin can attach the shared files at top level and shared folder to users at Desktop Version, Android App and iOS App. 
4. iOS user can recieve the message with attached files  and can select a file from inside the shared folders and toplevel to integrate it to a conversation.
5.Android App User can recieve the message with attached files and can select files at toplevel but can not select the files inside the shared folders
6. Android App crahes everytime after click to the icon of the shared folder.

### Expected behaviour
- Tell us what should happen
Navigate to shared folders and select files in it to attach this to a conversation

### Actual behaviour
- Tell us what happens
Android App crash only possible to resart or send a feedback to google with systemprotocols.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum
No I can not use it as admin and create new user.

### Environment data
Android version:
different smartphones tested (Android 7, 8 and 9)
Device model: 
Sony Xperia Z5, Sony Xperia XZ1, and Samsung Galaxy S7, IPhone 5
Stock or customized system:
customized system
Nextcloud app version:
8.0.8
Nextcloud server version:
18.0.3
#### Web server error log
```no log at nextcloud
Insert your webserver log here
```no log at nextcloud
#### Nextcloud log (data/nextcloud.log)
``` no log at nextcloud
Insert your Nextcloud log here
```no log at nextcloud
Android System message (Feedback):
Absturz, Name der Ausnahmeklasse = java.lang.NullPointerException, Quelldatei: ReadFilesystemOperation.java, Quellklasse: com.nextcloud.talk.components.filebrowser.webdav.ReadFilesystemOperation; Quellmethode: readRemotePath; Zeilennummer: 90 .....
and more, I cannot save the ccomplete feedback message that will be sent to google.....
sry.
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
@Maggi68 I've done it, thanks for the report.

**Comment by mario** [comment]
@Maggi68 works for me :-/ Can you send me a test account that has shared folder so I can test this? Thanks! :)

**Comment by Maggi68** [comment]
I sent you a private message...
THX

**Comment by mario** [comment]
Hm, where? You can send it to my mail: mario@nextcloud.com @Maggi68

**Comment by Maggi68** [comment]
at the gmyil.com

**Comment by guentir** [comment]
Same issue here...
NC 17.0.5 / Android 6 Samsung A5 2016/2015

**Comment by Maggi68** [comment]
you mean you can reproduce it...?

**Comment by guentir** [comment]
Yes, all my devices are affected (Android).

**Comment by mario** [comment]
This was not related to shared folders, but to the fact that your usernames had spaces in them :)

I fixed it so it will be in v9.0.

Thanks all!
@Maggi68 please delete my test account.

**Comment by Maggi68** [comment]
Oh, tanks for Information and many thanks to solve it in futurre version.....

**Comment by guentir** [comment]
@mario 
You are my livesaver! Many Thanks!
