### ISSUE TITLE
Video preview 

### ISSUE THREAD

**Issue by pmarini** [nextcloud/talk-android#784]
If I receive or send a video to a friend in the Nextcloud Talk chat, I have to open it in an external application (typically Nextcloud App or browser).

Is this the expected default behavior, or I'm missing something? If so, are there any plans to allow users to directly play the videos in the chat?
Thanks!

**Comment by mario** [comment]
It's expected for now - we'll improve this in the future but we're short-staffed atm. Any contributions are more than welcome :)

**Comment by pmarini** [comment]
Hi Mario, 

Thank you for the quick reply.

Can you give an overview of the work to be done to get this feature implemented? Are there any tasks that must be completed before starting with this one?

**Comment by mario** [comment]
At this point there are no pre-requirements to be done before work on this starts.

https://github.com/nextcloud/talk-android/blob/master/app/src/main/res/layout/rv_chat_item.xml
If it's a video, add a play button overlay on previewImage.

https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/newarch/features/chat/ChatView.kt
Extend onElementClick to handle video click in a chat message.

Add new "feature" videoPlayer in https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/newarch/features based on MVVM, ideally based on some variant of Exoplayer. I'd like to avoid external libraries if possible in favor of closer integration.

Further integration possible would be to have that videoview directly inside the chat view.

**Comment by pmarini** [comment]
Ok, thanks. I lack any previous experience with Android development so let's see if someone more skilled can dedicate some time to this.

I have recently convinced my family (10 users) to switch to Nextcloud Talk and I really think that this feature along with #435 would give huge improvements to the app.

**Comment by rodzilla2** [comment]
Would actually love to see this feature.

**Comment by stefan-niedermann** [comment]
@rodzilla2 please use [GitHub Reactions](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 👍  to signal that you are also interested in a feature. This helps to keep the issue history clean and understandable 🙂

**Comment by nickvergessen** [comment]
Should be fixed now
