### ISSUE TITLE
Fix avatar caching (also in notifications)

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#785]
This user has an avatar image but it is not shown up:
![grafik](https://user-images.githubusercontent.com/24530680/79252972-c5f16000-7e82-11ea-990b-5025781400d7.png)

**Comment by mario** [comment]
This should already work. Does that user have avatar set?

**Comment by jakobroehrl** [comment]
Yes, the user has an avatar image. 
And I have the latest beta version of the talk app

**Comment by mario** [comment]
Sounds very strange because the avatar you see comes from the API. :-/ 

I'll investigate. What Nc version?

**Comment by jakobroehrl** [comment]
OK, thanks. 
Latest 18.0.3

**Comment by jakobroehrl** [comment]
Tested again, now it is working, strange! 
8.0.9 Version

**Comment by mario** [comment]
Yup, nothing changed - I did find a bug in v9.0 (master) thanks to you though - so I'll leave the issue open :)

**Comment by jakobroehrl** [comment]
The problem occurs again, it's sporadically.
I will test with the v9.0 again.

**Comment by jakobroehrl** [comment]
This is fixed, I think.
