### ISSUE TITLE
Support "Note to self"

### ISSUE THREAD

**Issue by mario** [nextcloud/talk-android#786]
- Overview at https://github.com/nextcloud/spreed/issues/2196

Similar implementation to the changelog room.

"bot" and "notes" are the magical words.

Avatar is based on the same background as the app logo +notes icon for the foreground: https://material.io/resources/icons/?search=notes&icon=notes&style=baseline logo.

**Comment by nickvergessen** [comment]
Server PR: https://github.com/nextcloud/spreed/pull/3320

**Comment by nickvergessen** [comment]
The following restrictions apply to the newly added conversation type, so make sure that the UI options are hidden:

- [ ] Can not add participants to the room
- [ ] Can not allow guests
- [ ] Can not make read-only
- [ ] Can not make listable
- [ ] Can not change permissions
- [ ] Can not set lobby
- [ ] Can not enable SIP
- [ ] Can not configure breakout rooms
- [ ] Can not call
