### ISSUE TITLE
create new profile avatar image with camera

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#788]
Since my users using talk for cummunication the ask a lot how to change the profile picture. 
It would be nice, if this could be possible in the talk app on the settings page. 
Tip on the avatar image there could show up the possibility to shot a picture with the camara or upload one.

**Comment by jookk** [comment]
I requested this long ago, but wasnt possible because on server isnt api available.

**Comment by jakobroehrl** [comment]
@nickvergessen How hard is it to implement this API?
If it's easy could you assist me?

**Comment by mario** [comment]
@jakobroehrl there's ongoing work on this already on the server side.

**Comment by nickvergessen** [comment]
Feel free to join in at https://github.com/nextcloud/server/pull/20072

**Comment by nickvergessen** [comment]
Upload is now possible, but there is no camera option as of yet.
