### ISSUE TITLE
Binary XML file line #40: Error inflating class <unknown>

### ISSUE THREAD

**Issue by Terrox** [nextcloud/talk-android#791]
I get this error when entering new server address
 Binary XML file line #40: Error inflating class <unknown>

Sometimes it says class android.webkit.WebView instead of <unknown>

It wont connect and crashes on exit.

I have Google Play and have tried with and without installed Android System WebView

Android 5.1.1

**Comment by mario** [comment]
I'll take a look, thanks - I unfortunately rarely test on 5.x :-/

**Comment by mario** [comment]
Will be fixed in v9, thanks for reporting!
