### ISSUE TITLE
Show talks from different instances in one list

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/talk-android#794]
Hi all,

i just added a second instance into my talk-app. I can change between instances via settings, but as it is a talk/chat-app, it would be nice to have the chats of both instances inside one list, for not always to have to change the selected instance in settings.
- Still the chats may be sorted under headings per instance or somehow marked to which instance the chat belongs.
- Maybe this feature could just be an option to be chosen by user in settings.

Greets´:)
Jonas

**Comment by mario** [comment]
Unlikely. I think it was decided this is not the way to go.

@nickvergessen decision if he wants to close the issue or keep it.

**Comment by jotoeri** [comment]
Hm, not even as optional setting?
It's a pitty, it makes the app by far not as usable, that i personally would recommend people to use it for chat on mobile... :( (people from different settings/clubs, working on different instances...)
