### ISSUE TITLE
Loading & Error screens

### ISSUE THREAD

**Issue by mario** [nextcloud/talk-android#8]

**Comment by jancborchardt** [comment]
Yup, currently it's quite confusing to have just the black screen instead of the emptycontent screen.

**Comment by jancborchardt** [comment]
@mario any progress here? This is one of the most confusing parts in the UX. :) Just simply showing the other person's avatar (or the group icon) and below "Waiting for <person name> to join …" would go a long way.

**Comment by bugzy** [comment]
@mario any progress on this?
