### ISSUE TITLE
Receiving call screen

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#80]
You can now receive call by:
Phone ringing, display is off, 
You have to unock phone, swipe down to Nextcloud Talk notification > answered by tap, or dismissed by swiping.

New users (not advanced android users) are in state (what to do? )
Is is possible to implement:
Nextcloud talk ringing -> display on > Calling screen with Two choices (Pick Up or Dismiss buttons)?

So, user know how to answer receiving call :)

**Comment by mario** [comment]
Will be in 1.2 I hope.

**Comment by jookk** [comment]
Wau! Looking forward for new beta :)

Dňa 20. júna 2018 7:42:57 PM používateľ Mario Đanić 
<notifications@github.com> napísal:
