### ISSUE TITLE
Beta 9 doesn't start

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#800]
Oneplus 7t
Android 10

**Comment by mario** [comment]
Ok, I see the crash this time - thanks. It crashes in native webrtc code o.O

**Comment by Chartman123** [comment]
I just installed beta2 from Github releases and it also force closes again... As I installed it manually it doesn't allow me to report the crash

**Comment by mario** [comment]
:-/ 

  #01  pc 00000000001f39e8  /data/app/com.nextcloud.talk2-RgVBNGf8YjIjI5-BYdgIAw==/lib/arm64/libjingle_peerconnection_so.so

Dunno. Let me get the crashes from someone and we'll see :(

**Comment by Chartman123** [comment]
Here's a logcat, hope that helps, too
[logcat_05-03-2020_19-48-15.txt](https://github.com/nextcloud/talk-android/files/4571194/logcat_05-03-2020_19-48-15.txt)

**Comment by mario** [comment]
@Chartman123 thanks.

**Comment by simonspa** [comment]
For me beta2 doesn't start but hangs at a gray screen, no crash. (Oneplus X, Android 7.1)

**Comment by jakobroehrl** [comment]
Beta2: App is not starting, same as beta1

**Comment by guzzisti** [comment]
Beta2 is crashing immediately after startup, crash report has been submitted.

**Comment by tylerstyle** [comment]
Same Issue, Oneplus 8 Pro, Android 10. Bug Reports submitted.

**Comment by digititus** [comment]
I will chime in too so I can follow. Both betas crashing. Uninstall and reinstall doesn't help

**Comment by c0urier** [comment]
Same issue here, instantly crashes after launch.
OP7 Pro - Android: 10

**Comment by mario** [comment]
Should be fixed soon-ish.
