### ISSUE TITLE
beta3: Icons too big?

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#802]
Great for pics, maybe a little bit too big for files etc

![grafik](https://user-images.githubusercontent.com/24530680/80995235-3cf49580-8e3e-11ea-9c03-1ef644e1f0ed.png)

**Comment by mario** [comment]
Yup, I'll file it under v9.0, but unsure if I'll get to it. Contributions welcome! :)

**Comment by jakobroehrl** [comment]
I am closing issue. The error only occurred for version 9.
