### ISSUE TITLE
dark mode: chat information text color

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#804]
Enter a chat in the dark mode, tip on the 3 dots menu, maybe the text could look a litte bit better?

![grafik](https://user-images.githubusercontent.com/24530680/80996287-d53f4a00-8e3f-11ea-8200-d284828ec42d.png)

**Comment by mario** [comment]
PRs welcome? :P

**Comment by nickvergessen** [comment]
Also the color of the android status info is wrong: time, battery and icons of other apps are very close to not be readable:
Dark | White
---|---
![Screenshot_2020-05-05-07-57-06-622_com nextcloud talk2](https://user-images.githubusercontent.com/213943/81039064-49153d00-8ea8-11ea-84d3-60291a30fe1d.jpg) | ![Screenshot_2020-05-05-07-57-03-195_com nextcloud talk2](https://user-images.githubusercontent.com/213943/81039068-4a466a00-8ea8-11ea-990b-305f0b687c93.jpg)

**Comment by mario** [comment]
Status bar is fixed, the other thing is waiting for @jakobroehrl :)
