### ISSUE TITLE
own messages don't show up in chat history after sending

### ISSUE THREAD

**Issue by guzzisti** [nextcloud/talk-android#805]
Version: 9.0.0beta3
Android: 8.1
Nextcloud: 18.0.4
Nextcloud Talk-App: 8.0.8

I've send a message in a 1to1 chat which seems to be delivered correctly.
On the chat overview, the last message shown is my message, but in the chat history may message does not appear, even after leaving and re-entering the 1to1 chat.
After scrolling around a bit in the history of this specific chat a "unread message" button appeared which redirected me to my own message.

**Comment by mario** [comment]
Uhm. Right. Was it simply at the bottom?

**Comment by guzzisti** [comment]
Nope, i've tried scrolling to the bottom but the message was not just "out of display scope", it seems like that chat history has not been refreshed after sending.

**Comment by mario** [comment]
Ok, what Nextcloud version?

**Comment by guzzisti** [comment]
> Ok, what Nextcloud version?
18.0.4, added to the opening post.

**Comment by mario** [comment]
Thank you.

**Comment by simonspa** [comment]
Same here, NC 18.0.4, Talk 8.0.8, Android 7.1, Talk Android 9Beta3

**Comment by guzzisti** [comment]
chat history in general seems to be a mess even with 9.0.0beta4.

In a group chat, there a messages from other participants from 2 days ago which are still missing in the chat history. I can't find a way to trigger a reload, even if i send a message to the group chat by myself these won't show up in the history.

**Comment by nickvergessen** [comment]
Hello there,

we are currently cleaning up old/stray github issues. Can you please retry with the current version and report back if the problem still persists for you? I also remember that we fixed something related.

cheers

**Comment by guzzisti** [comment]
Current version does not show this behaviour

**Comment by EricKerby** [comment]
I have been seeing this issue frequently today on Nextcloud Talk Android 15.0.2 / Nextcloud server 25.0.1 / Talk app 15.0.2. Is this actually resolved?
