### ISSUE TITLE
beta: notifications are not working on migration

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#806]
notifications are only shown when I remove and install the app

**Comment by guzzisti** [comment]
I can confirm that although the app required a new login on the nextcloud instance after updating notifications do not work.

App version: 9.0.0beta4
Android version: 8.1 and 10
Nextcloud Version: 18.0.4
Nextcloud Talk App: 8.0.8

**Comment by Valdnet** [comment]
I also confirm. Push notifications do not work.

App:
Android 10
Talk Nextcloud 9.0.0beta4

**Comment by mario** [comment]
Should be fine in the newest beta that I'll release soon, pls re-open if not.

**Comment by Valdnet** [comment]
@mario Notifications still do not work in version 9.0.0beta5.

**Comment by mario** [comment]
Reinstall the app and try again.

**Comment by Valdnet** [comment]
Notifications appear only after uninstalling the old version and installing a new one.
