### ISSUE TITLE
Chat layout comparison

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#807]
Comparing some of the screenshots of a lorem ipsum:

 Talk 9 | Whatsapp | Telegram | Threema | Signal | Line
---|---|---|---|---|---
![Screenshot_2020-05-04-22-29-08-792_com nextcloud talk2](https://user-images.githubusercontent.com/213943/81040347-7adbd300-8eab-11ea-8c4d-c01de561d13c.jpg) | ![Screenshot_2020-05-05-08-15-25-881_com whatsapp](https://user-images.githubusercontent.com/213943/81039576-bd041500-8ea9-11ea-82b3-4598abacf645.jpg) | ![Screenshot_2020-05-05-08-15-46-079_org telegram messenger](https://user-images.githubusercontent.com/213943/81039578-becdd880-8ea9-11ea-83f4-3c89d66998e3.jpg) | ![Screenshot_2020-05-05-08-17-02-507_ch threema app](https://user-images.githubusercontent.com/213943/81039579-c0979c00-8ea9-11ea-98e7-56302598ec52.jpg) | ![Screenshot_2020-05-05-08-17-50-620_org thoughtcrime securesms](https://user-images.githubusercontent.com/213943/81039581-c2f9f600-8ea9-11ea-8bed-93c20937d56a.jpg) | ![Screenshot_2020-05-05-08-17-21-107_jp naver line android](https://user-images.githubusercontent.com/213943/81039586-c4c3b980-8ea9-11ea-8907-e3cb47434ab0.jpg)

Couldn't take lorem ipsum one due to #803 

 Feature | Talk 9 | Whatsapp | Telegram | Threema | Signal | Line
---|---|---|---|---|---|---
Messages in Bubbles | :heavy_multiplication_x: (was the case in Talk 8) | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark: 
Single emojis in Bubbles | --- | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark: 
Single emojis bigger | :heavy_check_mark: | :heavy_check_mark:  | :heavy_multiplication_x: (unless you pick a sticker from it  | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_multiplication_x: 
Messages trimmed at some point | :heavy_multiplication_x: | :heavy_check_mark:  | :heavy_multiplication_x:  | :heavy_multiplication_x:  | :heavy_check_mark:  | :heavy_multiplication_x: 
Shows icon in header | :heavy_multiplication_x:  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_multiplication_x:
Pixel height from bottom of g to top of f | 32px | 48px | 48px | 52px | 48px | 48px

**Comment by mario** [comment]
What does "bottom of g to top of f" means?

**Comment by mario** [comment]
Also, what's wrong with the font size?

**Comment by nickvergessen** [comment]
### Todo for Talk 9.0.0
- [ ] Adjust font size to a similar size
- [ ] Bring back the bubbles if possible

### Others
I think not showing the "default group icon" is fine, but for one-to-one and later when we have conversation icons I think it would be nice to also show them in the header. All apps that show this, then don't show a user icon on the mesages anymore, as the icon is in the top and the messages are seperated by color and side in their bubbles

**Comment by nickvergessen** [comment]
> What does "bottom of g to top of f" means?

The font size, I messured basically this:
![fontsize](https://user-images.githubusercontent.com/213943/81041244-a8298080-8ead-11ea-8cba-f4d0d43b46fd.jpg)


> Also, what's wrong with the font size?

It's way too small
