### ISSUE TITLE
Login flow is broken

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#808]
* Install Talk 9 beta newly
* Enter server address (c.nc.c)
* See Login flow screen
* Fill login form
* Fill 2FA
* Press to grant access
* Get redirected to step 2

**Comment by mario** [comment]
But that's just the webview?

**Comment by mario** [comment]
I'll check it out.

**Comment by nickvergessen** [comment]
Also happens with my private instance NC 18.0.4
