### ISSUE TITLE
Conversation list comparison

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#809]
Talk 9 | Whatsapp | Telegram
---|---|---
![Screenshot_2020-05-05-09-08-33-743_com nextcloud talk2](https://user-images.githubusercontent.com/213943/81043262-3bfd4b80-8eb2-11ea-8cca-bded74e6023b.jpg) | ![Screenshot_2020-05-05-08-57-56-203_com whatsapp](https://user-images.githubusercontent.com/213943/81043252-37389780-8eb2-11ea-94cf-31dd12e21c46.jpg) | ![Screenshot_2020-05-05-09-22-04-063_org telegram messenger](https://user-images.githubusercontent.com/213943/81043267-3d2e7880-8eb2-11ea-8755-c350a586f952.jpg) 
Line | Signal | Threema
![Screenshot_2020-05-05-08-58-36-633_jp naver line android](https://user-images.githubusercontent.com/213943/81043253-3869c480-8eb2-11ea-951a-0d22a782c8cf.jpg) | ![Screenshot_2020-05-05-08-59-43-201_org thoughtcrime securesms](https://user-images.githubusercontent.com/213943/81043255-399af180-8eb2-11ea-8c64-39367a8f7aed.jpg) | ![Screenshot_2020-05-05-09-04-27-969_ch threema app](https://user-images.githubusercontent.com/213943/81043259-3acc1e80-8eb2-11ea-9094-247b8ea75149.jpg)

Feature | Talk 9 | Whatsapp | Telegram | Line | Signal | Threema
---|---|---|---|---|---|---
Sticky icon | On image | On right | On right | On image | :heavy_multiplication_x: | On right
Unread counter position | On right | On right | On right | On right | On image | On right
Unread counter "alertness" | Small and grey | medium and color | medium and grey | Big and color | Big and color | Big and color
Mute icon | Not visible | On right | After name | After name | Before name | Before name

**Comment by nickvergessen** [comment]
I think we should increase the unread counter font size, so it is more easily readable.

From the rest I only think the missing mute icon could change in the future, but that should then be done for all our UIs, so something to dicuss

**Comment by simonspa** [comment]
Since this ticket is about the UX/UI: I found it odd to not have the app name or any primary color styled elements on the home screen. The primary color only appear (quite boldly) when entering a conversation.

Maybe the Search field could be expanded only when clicking on it and use the title bar for the app title in primary color instead?
This is how all apart messengers from Line do it in your overview @nickvergessen

**Comment by mario** [comment]
This is a new design language that will be implemented across the Nextcloud apps and is in line with the Material guidelines and new development on the Android scene.
