### ISSUE TITLE
Camera not working (black) Huawei MediaPad 10 Android 7.0

### ISSUE THREAD

**Issue by elpraga** [nextcloud/talk-android#81]
It does work correctly when I use the Talk app via the web interface on the same tablet.

app version 1.0.14

**Comment by mario** [comment]
Could you go into settings and tell me what it says for the model name? Thanks! :)

**Comment by mario** [comment]
(Also, did you enable it? Call controls are in the bottom of the call screen)

**Comment by elpraga** [comment]
I can give you __Device name:__ HUAWEI MediaPad T3 10 or __Model number:__ AGS-W09

Yes, I did enable it, but it just shows a black square, it does work when I use the web interface though (as I mentioned before). Switching cams does nothing either.

What more can I help you with?

**Comment by jookk** [comment]
Have you enabled app permissions for camera, mic?

**Comment by elpraga** [comment]
@jookk Yes I did (I double checked that) @mario stock ROM and Android 7.0 (as I wrote in the description) 
@jookk which Android version is T3 8.0 running? My Phone is also Huawei running Android 6.0, and it also works fine.  I thought it might be Android 7.0 issue. Is it working fine on other Android 7.0 devices?

**Comment by jookk** [comment]
Yes, working on nougat xiaomi redmi note 4.
My brother have t3 8.0 on Android 7 and talk worked well (as my memory 
telling me)
I ll recheck at thursday.


Dňa 28. januára 2018 1:04:32 PM používateľ elpraga 
<notifications@github.com> napísal:

**Comment by mario** [comment]
@elpraga I'll build a separate APK for you to try soon :)

**Comment by mario** [comment]
@elpraga http://172.104.243.61/nextcloud/index.php/s/S7YtxX37msFLZGA

**Comment by elpraga** [comment]
Ok, I can confirm. The camera is working correctly now on my device. 

Thank you! Great you were able to find the problem so quickly! What was it?

I'm experiencing some more issues, I will  give it more testing, and I'll report them if needed!

Thank you!

**Comment by mario** [comment]
@elpraga thanks for letting me know, the fix will be in the next release. Some devices, unfortunately, don't support video hardware acceleration, and when something like this happens, there's no video.

By disabling hardware acceleration, it starts working (even if a bit slower than it should!).

Report all the issues, and I'll be happy to help! :)
