### ISSUE TITLE
paper clip icon in instaed of + icon

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#811]
![grafik](https://user-images.githubusercontent.com/24530680/81140470-bf2da880-8f69-11ea-8e5b-b4554b5cc4f0.png)

What do you think @mario

**Comment by mario** [comment]
Unsure. Because there will be other things in there, and for example adding a location isn't suitable for a paper clip button. @Ivansss and @jancborchardt, thoughts?

**Comment by Ivansss** [comment]
The WebUI moved to use the clip icon when the upload feature was introduced IIRC.
Maybe it's time for the mobile clients to use the clip-icon as well.

**Comment by jakobroehrl** [comment]
Server is using the clip too, so I thought we should adapt the app.
![grafik](https://user-images.githubusercontent.com/24530680/81150731-94028380-8f80-11ea-80be-20f6021769fb.png)

**Comment by nickvergessen** [comment]
Yeah because currently we only have file upload/share.

I checked others:
📎 Whatsapp, Threema, Telegram
➕ Signal, Line
*** Viber has a full row for some times and the rest is in `…`

So paperclip seems to be "more what people expect", but + is also used already. So if possible I would say "stay in line" for now and use the paperclip

**Comment by mario** [comment]
Ok, but since we're moving on the server-side to the default material icons, which one do you want:

https://material.io/resources/icons/?search=clip&icon=attach_file&style=baseline

or

https://material.io/resources/icons/?search=clip&icon=attachment&style=baseline

**Comment by Ivansss** [comment]
I guess we can use https://github.com/nextcloud/spreed/blob/master/img/clip-add-file.svg, so we don't have to change the one in the web UI.

**Comment by mario** [comment]
But that's the thing - if the web is moving to native/original material icons, we'll have to do it anyway in the future @Ivansss - @ma12-co where did you get this icon from?

**Comment by nickvergessen** [comment]
Yeah whenever that future is.

I would say go with the spreed icon, or use https://material.io/resources/icons/?search=clip&icon=attachment&style=baseline as we "attach anything" and not just files in the future.

**Comment by jancborchardt** [comment]
> Yeah whenever that future is.
> 
> I would say go with the spreed icon, or use https://material.io/resources/icons/?search=clip&icon=attachment&style=baseline as we "attach anything" and not just files in the future.

Agreed. Let’s just go for consistency at the moment, and the move to Material icons on the server is still far out.

**Comment by ma12-co** [comment]
I think that as discussed today @jancborchardt , we should start the migration to material immediately where we can, and without worrying too much about consistency (which for now we don't have anyway)
Consistency will come the closer we are to material icons everywhere.
