### ISSUE TITLE
beta4: Invisible navigation

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#813]
After entering the file attachment, the navigation "Undo" and "Refresh" is hardly visible.

![obraz](https://user-images.githubusercontent.com/47037905/81195381-02196b80-8fbe-11ea-8dae-a7fe93e60926.png)

![obraz](https://user-images.githubusercontent.com/47037905/81196345-35a8c580-8fbf-11ea-82e6-0a393bd674d1.png)

App:
Android 10
Talk Android 9.0.0beta4

**Comment by AndyScherzinger** [comment]
Fixed on master
