### ISSUE TITLE
beta4: Return to entering the server address

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#814]
Steps:

1. Enter settings.
2. Add a new account.
3. Enter the server address.
4. Try connecting to the server.
5. Return to editing the server address entered.

The window does not return to editing the server address, but displays the loading again.

![obraz](https://user-images.githubusercontent.com/47037905/81196736-b49dfe00-8fbf-11ea-904d-0f9ee5105a1b.png)

App:
Android 10
Talk Android 9.0.0beta4

**Comment by mario** [comment]
Are you using a custom port?

**Comment by Valdnet** [comment]
No.

**Comment by Valdnet** [comment]
I am closing issue. The error only occurred for version 9.
