### ISSUE TITLE
beta4: White background when connecting to the server

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#815]
Steps:

1. Enter settings.
2. Add a new account.
3. Enter the server address without **http://** or **https://**.
4. Try connecting to the server.

**Only a white background appears.**

App:
Android 10
Talk Android 9.0.0beta4

**Comment by Liakoni** [comment]
I have the same problem, white background when connecting to server.

Android 10
Talk Android 9.0.0beta4

**Comment by mario** [comment]
I can't reproduce. Did you check the server logs?

**Comment by Liakoni** [comment]
> I can't reproduce. Did you check the server logs?

In the server logs doesn't provide any information about this.

**Comment by Valdnet** [comment]
I am closing issue. The error only occurred for version 9.
