### ISSUE TITLE
Changing the description "Privacy"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#817]
I suggest changing the "Privacy" description in the "About" app to a different one, e.g. "Privacy and Legal Policy"

In my opinion, the same names in two different options is confusing to the user.

![obraz](https://user-images.githubusercontent.com/47037905/81199212-a8677000-8fc2-11ea-9ff4-53f73cdc52e4.png)

**Comment by mario** [comment]
Will be in beta5.
