### ISSUE TITLE
beta4 microphone info is almost not readable

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#818]
![grafik](https://user-images.githubusercontent.com/24530680/81258665-7b54a500-9036-11ea-93ca-aca4e6dacbcc.png)

**Comment by nickvergessen** [comment]
Hello there,

we are currently cleaning up old/stray github issues. Can you please retry with the current version and report back if the problem still persists for you? I can not reproduce this.

cheers

**Comment by jakobroehrl** [comment]
Hi, issue still exist.

**Comment by nickvergessen** [comment]
Can you then please open a new issue and fill out all the required information?
