### ISSUE TITLE
beta4 crashes on call leave

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#819]
start a audio or a video call an leave it
Android 10

**Comment by Valdnet** [comment]
Steps:

1. Create a conversation with the user.
2. Try to connect to the user via call.
3. End connection.
4. The Talk app turns off automatically.

App:
Android 10
Talk Nextcloud 9.0.0beta4

**Comment by dkadioglu** [comment]
For me the same happens with beta4 on Android 10.

**Comment by mario** [comment]
Fixed in beta5 (soon)
