### ISSUE TITLE
SSO

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#822]
Why is it impossible to create a user account through Single Sign-On in version 9.0.0 in Talk? Is it consciously omitted?

**Comment by mario** [comment]
We do not support SSO at all, and never have in the Talk app.

**Comment by Valdnet** [comment]
I mean the option: "Import accounts from the Nextcloud app".

![obraz](https://user-images.githubusercontent.com/47037905/81337046-a8429f80-90aa-11ea-9a76-0070328515ef.png)

**Comment by mario** [comment]
Known:  https://github.com/nextcloud/talk-android/issues/710
