### ISSUE TITLE
Unnecessary values when confirming the certificate

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#824]
Unnecessary values when confirming the certificate to create a new account by SSO.

![obraz](https://user-images.githubusercontent.com/47037905/81299885-3a30b500-9077-11ea-9f2c-0f1dc104f0fe.png)

https://github.com/nextcloud/talk-android/blob/e50a9ed9f3419807b5a41aee1db896cb78908cdd/app/src/main/res/values-b%2Ben%2B001/strings.xml#L50

App:
Android 10
Talk Nextcloud 8.0.9

**Comment by mario** [comment]
What SSO? Talk doesn't support SSO. Also yes, they are needed so you can make an educated decision.

**Comment by Valdnet** [comment]
@mario OK.
I correct: When choosing an option "Import accounts from the Nextcloud app" in my opinion there are unnecessary values like: "CN" and "[2]".

**Comment by mario** [comment]
Pretty sure that comes from the certificate somewhere.
