### ISSUE TITLE
Chat scrolls to the top when returning from information

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#826]
1. Enter a conversation
2. Go to "Conversation information"
3. Go back
4. See chat scrolls all to the top.

**Comment by ctilluma** [comment]
Might want to move this back to high. I was reproducing the issue, and the third time got an app crash.

I think all we need to do is maintain the state of where we are in the conversation, so when it calls the instance state on drawing the information activity, we can adjust the view model to hold the current activity state.

**Comment by ctilluma** [comment]
This is tied to #880 as we need to hold where we are in the view as well as any unfinished tasks in instancestate.
