### ISSUE TITLE
Mentions are no longer highlighted

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#827]
![IMG-20200507-WA0002](https://user-images.githubusercontent.com/213943/81391133-df519900-911c-11ea-8152-be4c5da802c6.jpg)

**Comment by nickvergessen** [comment]
The full mention chip stuff was removed?
No avatars shown, no highlight of your own mentions

**Comment by mario** [comment]
Chips was removed from the messages because they don't behave the way I want them to and to make them behave that way I'd have to write the whole component myself for which I don't have the time. They currently remain only while you're writing the message.

**Comment by jancborchardt** [comment]
They did look nice though the way they were before? Now it’s very difficult to see where people have been mentioned, let alone yourself.

**Comment by mario** [comment]
Except avatars didn't load for a bunch of people :)

**Comment by jancborchardt** [comment]
Right, for that case we can have a fallback "user" icon. Of course it’s not good if avatars are not loaded, but it’s worse when you can’t quickly scan a chat for mentions of yourself. :)

**Comment by nickvergessen** [comment]
This is only in broken-master, so I close this.
