### ISSUE TITLE
9.0.0beta5: keeps crashing on Android 5.1

### ISSUE THREAD

**Issue by gajdipajti** [nextcloud/talk-android#833]
Hi, the Android Talk app instantly crashes after launch and keeps crashing in the background (I had this problem with all the 9.0.0beta* releases, might be similar to #799, #800, #801). I've reported the crashes, do you need any more info?

Android 5.1 (SDK version 22)
Asus_Z00VD (Zenphone Go ZC500TG)

(Btw, is my old Android version still supported, or should I downgrade to the 8.0.* branch?)

**Comment by mario** [comment]
It should be supported - I'll take a look.

**Comment by nickvergessen** [comment]
Hello there,

we are currently cleaning up old/stray github issues. Can you please retry with the current version and report back if the problem still persists for you?

cheers

**Comment by gajdipajti** [comment]
Hi,
It can be marked as fixed. (Just updated to version 11.1.0).
Sorry for not following up with this issue.
