### ISSUE TITLE
beta5: Text color for own messages has too little contrast in the light theme

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#834]
The background of the sent message is too dark.

![obraz](https://user-images.githubusercontent.com/47037905/81668162-88153680-9444-11ea-8085-80d9b8f49d61.png)

![obraz](https://user-images.githubusercontent.com/47037905/81668211-a418d800-9444-11ea-922f-f04866680a8e.png)

App:
Android 10
Nextcloud Talk 9.0.0beta5

**Comment by simonspa** [comment]
I think it uses the primary (non-themed) color - for me that makes text (especially links) completely illegible:

![image](https://user-images.githubusercontent.com/1677436/81689841-f1a03f80-945a-11ea-8963-570cabcfe48f.png)

**Comment by jancborchardt** [comment]
The issue is not necessarily the background color being too dark, but that on this background color, the text color should be white. :)

**Comment by simonspa** [comment]
Also a possibility. :) But I am with @Valdnet here that the color seems very strong for being a background color...

**Comment by Valdnet** [comment]
@jancborchardt In my opinion the problem is the background because it is darker than the color of the app theme.

**Comment by mario** [comment]
> @jancborchardt In my opinion the problem is the background because it is darker than the color of the app theme.

No it's not - it's the same color. You're seeing it as different because the app background is dark.

**Comment by alexanderdd** [comment]
IMHO text and links should be white as it is the case in 8.0.9 
Background should stay the standard blue, no need to change. 

(In the long term maybe adopt the theming color, as in the Deck Android app. But that is a separate issue.)

**Comment by dan0xii** [comment]
How does this suit everyone. The date for `Sent` now looks like it needs to be lighter to me.

![screenshot-2020-09-23_13 10 37 697](https://user-images.githubusercontent.com/1926270/94010857-663aa180-fd9e-11ea-9e14-6d29df355b53.png)

![screenshot-2020-09-23_13 12 45 326](https://user-images.githubusercontent.com/1926270/94010956-89655100-fd9e-11ea-81ef-2da8a6a880a0.png)

**Comment by jancborchardt** [comment]
@dan0xii good stuff! :) Only design feedback on this specific text contrast topic:
- In light theme, the date text for own messages should also be light, not dark
