### ISSUE TITLE
Add "Skip" button

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#835]
I suggest adding the "Skip" button in the window to enter the server address, because after installing the new version of the app on the old version it is not possible to skip registration.
This only allows you to turn the app off and on again.

![obraz](https://user-images.githubusercontent.com/47037905/81670129-74b79a80-9447-11ea-83df-3f857e43afaa.png)

**Comment by mario** [comment]
Well, did you have accounts previously?

**Comment by Valdnet** [comment]
Yes. I had accounts before 😉.

**Comment by nickvergessen** [comment]
Hello there,

we are currently cleaning up old/stray github issues. Can you please retry with the current version and report back if the problem still persists for you? If so please also add some more steps to reproduce.

cheers

**Comment by Valdnet** [comment]
@nickvergessen I think the issue can be closed. When installing a new version, e.g.: 11 or 12 Alpha, the problem did not repeat.

Cheers :beer:
