### ISSUE TITLE
Share link shows outdated icon

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#840]
- create a public conversation
- share link via Whatsapp
- see old icon
- server is NC18

![image](https://user-images.githubusercontent.com/5836855/81822821-dfde9b00-9533-11ea-8b3b-1e0dd95a877c.png)

**Comment by mario** [comment]
I'm not sure this is at all related to Talk. ``

**Comment by tobiasKaminsky** [comment]
Just silently closing…?

**Comment by mario** [comment]
No, I wrote a comment that I'm unsure how is this related to Talk?

**Comment by tobiasKaminsky** [comment]
I share the link from Talk to WhatsApp. So I assumed that icon comes from the app?
