### ISSUE TITLE
Bad qualitiy on 1:1 Smartphone Calls

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#841]
Tested 1:1 Calls with different people a lot because I tried substitute telefon calls with talk calls. 
We only used smartphones (is this the right repo?)
And it's impossible to reproduce
Problems are: 
 - connection creation takes a long time
 - connection tears off after about 10 mins
 - connection sometimes stucks

Can I test/debug these problems better?

**Comment by mario** [comment]
I don't know what to do here. If it connects, it's fine - all connection issues are then between the two phones as its peer2peer?

**Comment by jakobroehrl** [comment]
Is there a cache for the to trace this calls?

**Comment by jakobroehrl** [comment]
Tested on another server, there it works great, so I close this.
