### ISSUE TITLE
Connection Handshake failed 

### ISSUE THREAD

**Issue by githubber-spec2** [nextcloud/talk-android#842]
Connection Handshake failed 

Just like here: https://github.com/nextcloud/talk-android/issues/193

My Nextcloud App work fine. Note and Deck App also works without this issue.

Using LineageOS recently upgraded. Android 9 (Pie)
Nextcloud Talk App: 8.0.9 from f-droid (latest)
My Server uses TLS 1.3 Only (Debian 10 Buster)
TLS_AES_128_GCM_SHA256, 128bt keys (info from browser)
if you need more details please let me know where i can take them from

> support for the newer TLS cipher suites is lacking 
`i guess`

**Comment by ctilluma** [comment]
I thought Android 10 (Q) is supposed to be where TLS 1.3 is supposed to be implemented, but the cipher you are using isn't a newer suite.

Is Talk the only nextcloud app you have loaded? Are you having 'Connection Handshake' issues with other apps connecting to the same server?

**Comment by nickvergessen** [comment]
Hello there,

we are currently cleaning up old/stray github issues. Can you please retry with the current version and report back if the problem still persists for you?

cheers
