### ISSUE TITLE
Beta 5 calling not working. No call notifications

### ISSUE THREAD

**Issue by digititus** [nextcloud/talk-android#843]
When calling from Android Beta 5 to another phone with Beta 5, it is impossible to establish a call. There are no notifications of an incoming call. Both phones running Android 9. Notifications permissions are set. No battery saver enabled.

Normal text messages do show notifications between devices. Only call notifications are not displayed 

Calling from Beta 5 to NextCloud Talk web can establish a call and vice versa. The problem as far as I can tell only happens between the android clients.

I have tested on Wifi and 4G. Turn server is working.

**Comment by digititus** [comment]
Resolved by downgrading each device to v8.0.9

**Comment by nickvergessen** [comment]
This should not happen anymore as the broken master was removed from the code base
