### ISSUE TITLE
Screen kept on for chat

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#844]
When you are just in a text chat, the screen stays on all the time. This drained my battery once just having it lying on the table and not noticing.

The only case where the screen needs to be kept on is in video chat (and maybe maybe voice chat). But when you are anywhere else in the app, the screen should time out just as per system settings.

**Comment by ctilluma** [comment]
I'd like to understand this from a usability perspective. If you leave the app, you would get standard timeout settings, but when in the app, it should only keep the screen on for Video and Audio? An active chat should still timeout, but only if you're receiving texts, and not if you've recently interacted?

Once the screen timeouts then, should active incoming chats be moved to notifications instead (based on conversation settings).

**Comment by jancborchardt** [comment]
> it should only keep the screen on for Video and Audio

The screen should only be kept for Video actually, as audio doesn’t need the screen to be on all the time. Even when it’s an "active chat" receiving texts, the standard timeouts should apply. This is how other chat apps do it as well.

> Once the screen timeouts then, should active incoming chats be moved to notifications instead (based on conversation settings).

Yep, exactly! :)

**Comment by ServError** [comment]
This is still draining the batteries of users everywhere who are accustomed to the behavior of their normal chat apps. At least for my usage, video is so much less common than text that I'd rather see this issue flipped and have the sleep timeout apply to video and make that the To-Do.
