### ISSUE TITLE
beta5: "+" button during conversation

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#846]
Steps:

1. Put your smartphone to sleep.
2. Receive a message from the user.
3. Wake up your smartphone.
4. Tap the notification on the smartphone screensaver.

The "+" button from the list of conversations remains in the conversation window.

![obraz](https://user-images.githubusercontent.com/47037905/82322390-b9f34380-99d6-11ea-882a-626fb3c076f6.png)

App:
Android 10
Talk Nextcloud 9.0.0beta5

**Comment by mahibi** [comment]
@Valdnet i guess this can be closed?

**Comment by Valdnet** [comment]
@mahibi Of course 😉.
