### ISSUE TITLE
On orientation change, chat views scroll to top

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#848]
When you are scrolled further down in the list of conversations and then rotate your phone from portrait to landscape or vice versa, the list jumps to the top.
Same happens when you are in a chat – this is especially annoying since the chat by default is of course scrolled to the bottom as that's where new messages appear.

Instead, any scroll position should be kept on change of orientation.

**Comment by mario** [comment]
Hey @jancborchardt, thanks for testing the app.

This issue is the same one as https://github.com/nextcloud/talk-android/issues/826, so I'll close this one as #826 is older.

**Comment by jancborchardt** [comment]
It’s not really the same though? This is about it scrolling to the top when you **turn your phone** from landscape to portrait, or from portrait to landscape. The other one is about switching views inside the app.

**Comment by mario** [comment]
It's the same :) I ffix one, I fixed the other as well
