### ISSUE TITLE
[WARN] Subscriber is using the legacy 'listener' ptype

### ISSUE THREAD

**Issue by acsfer** [nextcloud/talk-android#849]
While using the signaling server (HPB), each time a client connects using the app, this is logged.

`[WARN] Subscriber is using the legacy 'listener' ptype`

Nothing is logged while using web app (`spreed 8.0.9`).

**Comment by ctilluma** [comment]
I've seen that as well, and am wondering if it may be a cause of call setup problems with Android. I don't see the message from the web client, nor the iOS client, and both of those clients have significantly higher success rates when initiating a call than i'm seeing on Android.

Are you aware of any other changes that were made in the iOS or web client in relation to HPB or Janus, other than listening for the new data channel?

**Comment by ctilluma** [comment]
This isn't unique to Android. Here are my Janus logs from a call between two web clients.

Creating new handle in session 703438797225619: 4246614428565800; 0x55f5100e5ba0 0x55f510138fa0
[4246614428565800] Creating ICE agent (ICE Full mode, controlled)
[WARN] [4246614428565800]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [4246614428565800]     Missing valid SRTP session (packet arrived too early?), skipping...
[4246614428565800] The DTLS handshake has been completed
[janus.plugin.videoroom-0x55f510101b00] WebRTC media is now available
Creating new handle in session 703438797225619: 6226219876027852; 0x55f5100e5ba0 0x55f5102442c0
[6226219876027852] Creating ICE agent (ICE Full mode, controlled)
[WARN] [6226219876027852]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [6226219876027852]     Missing valid SRTP session (packet arrived too early?), skipping...
[6226219876027852] The DTLS handshake has been completed
[janus.plugin.videoroom-0x55f5101047c0] WebRTC media is now available
Creating new handle in session 703438797225619: 4337888591244126; 0x55f5100e5ba0 0x55f510197420
[WARN] Subscriber is using the legacy 'listener' ptype
[4337888591244126] Creating ICE agent (ICE Full mode, controlling)
Creating new handle in session 703438797225619: 1624143671142912; 0x55f5100e5ba0 0x55f5101978c0
[WARN] Subscriber is using the legacy 'listener' ptype
[1624143671142912] Creating ICE agent (ICE Full mode, controlling)
[WARN] [1624143671142912]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [1624143671142912]     Missing valid SRTP session (packet arrived too early?), skipping...
[1624143671142912] The DTLS handshake has been completed
[janus.plugin.videoroom-0x55f510197a00] WebRTC media is now available
[WARN] [4337888591244126]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [4337888591244126]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [4337888591244126]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [4337888591244126]     Missing valid SRTP session (packet arrived too early?), skipping...
[4337888591244126] The DTLS handshake has been completed
[janus.plugin.videoroom-0x55f510198340] WebRTC media is now available

**Comment by kleener** [comment]
Hello,
I also still have the message in the log, are there any hints or ideas here?

**Comment by kleener** [comment]
Hi,
I think with this merge you can close the issue: https://github.com/strukturag/nextcloud-spreed-signaling/commit/43f0b1d598a006f43621b26b3b70b4bd16a2d7c3
