### ISSUE TITLE
Incoming calls don't vibrate when phone is locked

### ISSUE THREAD

**Issue by siccovansas** [nextcloud/talk-android#850]
My Sony Xperia XZ2 Compact doesn't vibrate when I receive a Nextcloud Talk call. This is the case when I have my ringtone volume on, but also when it is off and I use the vibration only mode (which thus results in unnecessary missed calls).

I use the exact same Nextcloud Talk settings as a Samsung Galaxy S10 (both in the app, the app specific notification channel settings and system wide settings as far as they are similar) and that phone does vibrate. Normal calls and Signal calls also make the Sony vibrate, so it seems to be a combination of Nextcloud Talk and this Sony phone that causes it not to vibrate.

Is there any extra info I can add to help debug this problem?

**Comment by mario** [comment]
What app version are you using?

**Comment by siccovansas** [comment]
Right I should've mentioned that 🙃. The latest version of Talk for the Android app and also for the server app: 8.0.9. Also with the latest version of Nextcloud Hub: 18.0.4.

**Comment by mario** [comment]
Try 9.0 beta pls

**Comment by siccovansas** [comment]
Thanks for the advice. I installed the beta, but now I can't even establish a phone call, so I can't test if the vibration works. I also installed the beta on the Samsung, but still couldn't establish any calls (the calling phone just rings and the receiving phone doesn't show that a call is incoming). Do I do anything wrong with the beta? Does the server also need to be the beta version (I couldn't quickly figure out how to install the beta of the server Talk app)?

**Comment by nickvergessen** [comment]
Hello there,

we are currently cleaning up old/stray github issues. Can you please retry with the current version and report back if the problem still persists for you?

cheers

**Comment by siccovansas** [comment]
Hi @nickvergessen,

Thanks for reaching out. The problem still persists. I tried calling both phones using Nextcloud Talk Android 11.1.0 (and Talk on the server with version 11.2.1 on Nextcloud 21.0.2). 

- When the phone is locked and on 'vibrate only' the incoming call is shown on screen, but the phone doesn't vibrate
- When the phone is NOT locked and on 'vibrate only' the incoming call is shown on screen and the phone DOES vibrate

- When the phone is locked and 'ringing/sound is on' the incoming call is shown on screen and the phone's ringtone plays, but the phone doesn't vibrate
- When the phone is NOT locked and 'ringing/sound is on' the incoming call is shown on screen, the phone's ringtone plays and the phone DOES vibrate

The above results are the same for both phones (I tried calling them both). Both phones do vibrate when they are locked when they receive normal or Signal calls.

**Comment by siccovansas** [comment]
@mahibi I just checked if this issue still exists with the latest versions and I can confirm that the problems as described in my previous comment are still exactly the same.

Nextcloud 22.1.0
Nextcloud Talk 12.0.1
Nextcloud Talk Android 12.1.2

**Comment by siccovansas** [comment]
@mahibi @AndyScherzinger I just checked again using the newest versions of Nextcloud and Talk. The issue still exists.

I'm not sure if this is specific to my devices or a general issue for everybody. This issue prevents me from using Talk (though I would love to actively use it) as it doesn't make sense to try and call people if they aren't notified and thus miss the call.

Nextcloud 23.0.2
Nextcloud Talk 13.0.3
Nextcloud Talk Android 13.0.0

**Comment by siccovansas** [comment]
I checked the issue using the current versions of Nextcloud (Talk) and it still exists. In a [previous comment](https://github.com/nextcloud/talk-android/issues/850#issuecomment-848315264)  I stated that vibration DOES work when the phone has 'ringing/sound' on, but that doesn't seem to be the case (anymore). So the problem is as follows:

Results when the phone is on 'vibrate only':

- When the phone is locked the incoming call is shown on screen, but the phone doesn't vibrate (this is incorrect; expected behaviour: phone should vibrate)
- When the phone is NOT locked and on 'vibrate only' the incoming call is shown on screen and the phone DOES vibrate (this is correct)

Results when the phone has 'ringing/sound' on:

- When the phone is locked the incoming call is shown on screen and the phone's ringtone plays, but the phone doesn't vibrate (this is incorrect; expected behaviour: phone should ring and vibrate)
- When the phone is NOT locked the incoming call is shown on screen, the phone's ringtone plays and the phone doesn't vibrate
 (this is incorrect; expected behaviour: phone should ring and vibrate)

Nextcloud 24.0.5
Nextcloud Talk 14.0.5
Nextcloud Talk Android 14.2.0

I guess people (are expected to) only use Talk as a Google Meet alternative and not as a Signal/phone alternative as this bug is longstanding and make Talk unusable as a Signal/phone alternative? Fixing this small(?) bug would make Talk a more widely usable app ❤.

**Comment by nickvergessen** [comment]
> I guess people (are expected to) only use Talk as a Google Meet alternative

Not expected at all.

Is it this quirk?
https://github.com/nextcloud/talk-android/blob/fcf20e3362dfa391a10716d6ecc26e2c62eeb8ac/app/src/main/java/com/nextcloud/talk/utils/DoNotDisturbUtils.kt#L69-L86

**Comment by siccovansas** [comment]
Good to know that normal calls are a supported use case for Talk :)! I'm wondering though how many people use Talk for normal calls as this bug makes it quite unusable. Or is this bug not universal? It would be nice to know if @nickvergessen or anyone else can you reproduce it (see the steps in https://github.com/nextcloud/talk-android/issues/850#issuecomment-1255145648)?

@nickvergessen thanks for seeking out the related code. I'm not familiar enough with the codebase to check if it contains the bug though. Do you? Or would someone else know?

**Comment by mahibi** [comment]
@siccovansas are you aware that sound and vibration is handled by android for each app since Android 8.0 (API level 26)?

**Comment by siccovansas** [comment]
@mahibi Thanks for your reply :pray:! I'm using:
Samsung Galaxy S10: Android 12
Sony Xperia XZ2 Compact: Android 10

Good to know that some work is being done on vibrations :fireworks:. I won't be able to test the PR though.

I double checked the app specific notification settings of Talk again and 'vibrate' is allowed on both phones.

I tried all the steps I detailed in https://github.com/nextcloud/talk-android/issues/850#issuecomment-1255145648 again and the results are still the same. In short: incoming Talk calls don't make the phone vibrate when the phone is locked (both in on 'vibrate only' and with 'ringing/sound on').

Can you (or anyone else) please test this? I would really like to know if getting called with a locked screen results in vibrations for some people or if this issue affects everyone :smiley:.

I tested using the latest versions:
Nextcloud 25.0.1
Nextcloud Talk 15.0.1
Nextcloud Talk Android 15.0.1

**Comment by pawlosck** [comment]
I have the same problem. I have disabled sounds on phone and vibration is on when text messages are received, but no vibration, when someone call me. Maybe problem is connected with older version of Android or modification from manufacturer?

Server: 25.0.1
Web Talk: 15.0.1
Android Talk: 15.0.1

OS: Android: 9
Phone: Samsung Galaxy S8

**Comment by siccovansas** [comment]
Amazing, the just released version 15.1.0 has fixes this issue :fireworks::100:! I checked all scenarios from https://github.com/nextcloud/talk-android/issues/850#issuecomment-1255145648 again with both phones and they now both vibrate in the 3 scenarios where they erroneously didn't vibrate before. I guess https://github.com/nextcloud/talk-android/pull/2566 has fixed it @mahibi like you suggested above! I'm really happy that I'm (finally :wink:) able to use Nextcloud Talk as a complete and better phone alternative :pray:.

**Comment by pawlosck** [comment]
It's not fixed. I checked now and currently I hear only one vibration and that's all. Screen is on for few seconds and nothing more.

**Comment by siccovansas** [comment]
That's too bad @pawlosck! Could you open a new issue detailing exactly which steps you took and which device(s) you used with all their software versions?
