### ISSUE TITLE
Support for High-performance backend clustering

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#851]
With https://github.com/nextcloud/spreed/pull/3292 we introduced what we call "Conversation based clustering" for Talk 9.
It means an admin can set up multiple HPB and a "random" (or fixed one when the admin sets a HPB for a given conversation token) HPB will be used per conversation. This is only persistent until the last participant left the conversation. So each call/chat session can happen on a different HPB.

The API endpoint `/ocs/v2.php/apps/spreed/api/v1/signaling/settings?token=aBcDeFgH` was extended with the token parameter.
See doc changes in: https://github.com/nextcloud/spreed/pull/3662

So now you get the signaling settings for the first conversation, if the setting is `conversation_cluster` you need to get new settings, disconnect from the old one and reconnect to the new HPB in case the url changed.

**Comment by ctilluma** [comment]
Does this affect call setup in a non clustered HPB configuration?

**Comment by nickvergessen** [comment]
No

**Comment by nickvergessen** [comment]
Feature is deprecated
