### ISSUE TITLE
Obey force mute signaling message

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#853]
In Talk 9 moderators have an option to turn of the microphone of participants (see `force-mute` capability).

So if you receive a signaling message with:
```js
	if (message.type === 'control') {
		if (message.payload.action === 'forceMute') {
			if (message.payload.peerId === self.connection.getSessionId()) {
```

Mute the microphone.

**Comment by mario** [comment]
Should already be done via https://github.com/nextcloud/talk-android/issues/742.

**Comment by mario** [comment]
If there are any bugs with the implementation please open an issue.
