### ISSUE TITLE
Nextcloud Talk app installed via F-Droid does not raise notifications

### ISSUE THREAD

**Issue by dirdi** [nextcloud/talk-android#854]
## Steps to reproduce
1. Install the "Nextcloud Talk" app from the **F-Droid** store
2. Login to a Nextcloud instance with default Talk server settings:
![2020-05-31-201032_1518x514_scrot](https://user-images.githubusercontent.com/7914030/83359509-ed40b580-a37a-11ea-9985-6c283601fca6.png)
3. Start a conversation with another user or join a group chat
4. Make sure you have set the *...* > *Conversation info* > *Messages* option to *Always notify*
5. Switch to another app or completely close the Nextcloud Talk app
6. Wait for smb. to send a message

### Expected behaviour
The Nextcloud Talk app should raise a notification as soon as smb. else sends a message.

### Actual behaviour
Nothing happens: No sound. No vibration. No notification badge.

I stumbled upon a thread stating that the Nextcloud Talk app leverages some Google push services. In the past I already learned that apps installed from 3-rd party app stores do not play well together with Google services. Therefore, I removed the Nextcloud Talk app and re-installed it via the Google's Play store. Now everything works fine. So I suspect this is somehow related to the way how one installs the app.

## Talk app

**Talk app version:** 8.0.9

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration
**Web server:** Apache

**Database:** MySQL/MariaDB

**PHP version:** 7.3.18

**Nextcloud Version:** 18.0.4

### Server log (data/nextcloud.log)
Does not contain anything related to this bug.

**Comment by dirdi** [comment]
You [advertise this app](https://nextcloud.com/hub/) as a fully-fledged replacement of WhatsApp, Threema, Telegram etc:
![2020-06-01-022416_1150x297_scrot](https://user-images.githubusercontent.com/7914030/83366384-05322c80-a3af-11ea-8dbb-25dc1f452a67.png)
You are aware that one of its core functionality (i.e. delivery and notification of new messages) is utterly broken if installed via F-Droid. After @nickvergessen's response I double checked the app's description. Yes, after one clicks on the "MORE" button and scrolls down half a page, there is a section called "Nextcloud Talk supports:" (sic!) with the following hint in the middle of a twelve item long list:

> * ...
> * Mobile call & chat push notifications (only if installed from Google Play)
> * ...

Even if I had read this before I installed the app (and I admit I did not, like I expect most users will not), I would have expected that there was a fall back, like polling for new messages or something.

It is like selling smb. a broken car and when he comes back complaining, you state that on the 5-th page of the sales agreement under section IX. 5. A) there is a tiny note that the car does not run properly if you do not buy it from another dealer.

IMHO there should be a warning - not in the middle, but at the very beginning of the app description, in big, bold, red letters, like: "This version of the app is broken! Head over to the Google Play Store to get a fully functional app!"

Please do not get me wrong. This is not meant as a rant. I am more than grateful for all the work you developers put into Nextcloud and its apps. Yet, I can not understand that this bug report was closed.

**Comment by tsr8** [comment]
Why every application I use have notifications without G-Play but Nextcloud Talk not? It is still actual now. Why?

**Comment by KapriQ** [comment]
Is there anything new? Is there any way how to sopve notification without google services? Need that in for my usage. Thanks...
