### ISSUE TITLE
Call/Message Notifications not working

### ISSUE THREAD

**Issue by some-git-user** [nextcloud/talk-android#856]
I tried the F-Droid release and the latest apk from this git release.
In both versions notifications not working when calling or sending messages.
We use Android 10 devices without Gapps.

Any solution to this problem? Other Apps like Signal or Telegram works fine.

**Comment by ericschdt** [comment]
Duplicate: https://github.com/nextcloud/talk-android/issues/257

**Comment by some-git-user** [comment]
So basically this app is deprecated?
This "bug" exists since  Jul 24, 2018 with no solution for users without Gapps?

Maybe anyone reading this, could point me to some alternative App or complete self hosted WebRTC solution.

**Comment by nickvergessen** [comment]
Close as duplicate per above

> So basically this app is deprecated?

No, but the issue is hard to solve as you can read in the other issue.
