### ISSUE TITLE
No incoming call after last update to Talk 9.0.1

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/talk-android#858]
## Steps to reproduce
1. Create a conversation in web, invite a user 
2. No inbound call on android device

### Expected behaviour
The inbound call should ring at the android device, pop-up window appears.

### Actual behaviour
After update to Talk 9.0.1 at the server side the inbound call is missing on android device (Talk app 9.0.0beta5).

At the same time the notifications about text messages in the chat are coming to the Android device.

**Comment by ctilluma** [comment]
@ostasevych Couple questions - Is it only a problem if one side (web / android) initiates the call, and not the other? Are you using the HPB (High Performance Backend) or standard signalling?

**Comment by ostasevych** [comment]
Only web. Standard signaling. What should happen ideally, meanwhile?

**Comment by ctilluma** [comment]
Ideally, when you make a call, the requested party is notified on any devices connected to that account, and upon accepting the call, an audio or video call is successfully set up and maintained.

I'm seeing a lot of differences in call success, based on whether the initiator is using web, iOS, or android. I sense a bit of this is a function of some differences between 8 and 9, as when iOS got to 9, it resolved some issues. 

Call success in general I found to be better with standard signaling in the version differences. I'm going to spin up a kvm to use standard signalling, and see if I can replicate this problem.

**Comment by ostasevych** [comment]
> Ideally, when you make a call, the requested party is notified on any devices connected to that account, and upon accepting the call, an audio or video call is successfully set up and maintained.
> 
> I'm seeing a lot of differences in call success, based on whether the initiator is using web, iOS, or android. I sense a bit of this is a function of some differences between 8 and 9, as when iOS got to 9, it resolved some issues.
> 
> Call success in general I found to be better with standard signaling in the version differences. I'm going to spin up a kvm to use standard signalling, and see if I can replicate this problem.

Thank you for explanations. I may testify that I do not have an incoming voice/sound when a call is to be received through web. This function is missing. What may be obtained is a pop-up window at the level of OS (provided chrome notifications are allowed).  I hope that the desktop client may provide this functionality with the ringtone and pop-up window, plus, when you have open window with NC you may obtain a pop-up window and hear the incoming ringtone (eg JSXC provides this option).

**Comment by arnowelzel** [comment]
Just for the record - it's the same here. The app never notifies about anything at all. Only when I have the app opened and running in foreground I can at least see that there is something going on.

**Comment by Hanskes** [comment]
I have similar problems with version 11.1. Sometimes the phone starts to ring, other times it doesn't. There will then be a notification at the top of the screen, but the phone does not start to ring and you will not get a call screen with the option to answer the call.

**Comment by mahibi** [comment]
I'm aware of these problems with the notifications, i hope to find the time to have a closer look soon

**Comment by nickvergessen** [comment]
Hello there,

we are currently cleaning up old/stray github issues. Can you please retry with the current version and report back if the problem still persists for you?

cheers

**Comment by arnowelzel** [comment]
Seems to be solved for me.
