### ISSUE TITLE
9.0.0beta5 : external gif preview no longer working

### ISSUE THREAD

**Issue by jcastang** [nextcloud/talk-android#859]
Hello, 

On 8.0.x gif link from Tenor or Giphy were changed from link to direct preview.

On 9 beta 5 only link is shown, no more preview.

**Comment by nickvergessen** [comment]
Just for the record, for now this is the expected behaviour. We might even remove all direct viewing in the future as it violates users privacy by default.

**Comment by valon0388** [comment]
I'd like to add my support to this issue. I'd love to see gif preview working again. It's the one thing keeping me from adopting Nextcloud Talk. Even if it's optional with a disclaimer or something. I'd use it.

**Comment by AndyScherzinger** [comment]
Decission now has been: drop preview for links: so no more preview rendering.
