### ISSUE TITLE
Status bar and navigation bar color

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#860]
It’s details but makes the app appear more disheveled than it needs to be:
- [ ] The status bar is always colored according to the theme. This is fine in the conversation list, but inside conversations or the settings though it should be the same color as the header bar. (Currently that is blue, we can also think about adjusting that to conform with the Android Files app.)
- [ ] The bottom navigation bar is always black. Would be much nicer if it’s colored like the theme, so it fits with the background. We need to make sure that the icons are also properly contrasting.

List | Chat
-|-
![Screenshot_20200612-141610_Nextcloud_Talk](https://user-images.githubusercontent.com/925062/84526271-56122100-acdd-11ea-9f7d-3646a50461b1.png) | ![Screenshot_20200612-141629_Nextcloud_Talk](https://user-images.githubusercontent.com/925062/84526269-55798a80-acdd-11ea-872a-a0fc1b0b8a0e.png)

**Comment by dan0xii** [comment]
Implementing this is a bit messy because the conversation list view has a light header and the conversation view headers themselves have the primary colour set. Are there plans to migrate the look of the app inline with the screen above on the left? That would seem like the long-term solution.

Thanks,


Daniel

**Comment by tobiasKaminsky** [comment]
>     * we can also think about adjusting that to conform with the Android Files app.

This should be the goal, which then also answers @dan0xii question, I think.

![2020-08-31-083509](https://user-images.githubusercontent.com/5836855/91689701-f0f3fc00-eb64-11ea-9a68-e58823540323.png) ![2020-08-31-083513](https://user-images.githubusercontent.com/5836855/91689702-f18c9280-eb64-11ea-93c5-a22528a46cca.png)

**Comment by dan0xii** [comment]
Thanks for pointing that out Tobias, I obviously didn't spot it ;)

I'll see what's involved to move the UI to look like that of the Files app and see if I can put it together.

**Comment by dan0xii** [comment]
Progress so far. It still has that panelled look on some of the views--do I need to try and flatten those? I don't want to butcher it too much.

![screenshot-2020-09-08_20 01 17 183](https://user-images.githubusercontent.com/1926270/92517801-32dd0c00-f20f-11ea-80be-d03f5cfa59f6.png)
![screenshot-2020-09-08_20 01 29 079](https://user-images.githubusercontent.com/1926270/92517808-340e3900-f20f-11ea-86a8-7d3fafd831b1.png)
![screenshot-2020-09-08_20 01 33 488](https://user-images.githubusercontent.com/1926270/92517810-34a6cf80-f20f-11ea-88e9-eb34bb96ef8f.png)
![screenshot-2020-09-08_20 01 40 084](https://user-images.githubusercontent.com/1926270/92517812-353f6600-f20f-11ea-9f44-6653e0439b94.png)
![screenshot-2020-09-08_20 01 43 453](https://user-images.githubusercontent.com/1926270/92517815-35d7fc80-f20f-11ea-9667-92153db99f90.png)
![screenshot-2020-09-08_20 01 46 813](https://user-images.githubusercontent.com/1926270/92517818-36709300-f20f-11ea-9a81-a8887cf89ed5.png)
![screenshot-2020-09-08_20 01 50 806](https://user-images.githubusercontent.com/1926270/92517821-37092980-f20f-11ea-84d7-4177647a1abb.png)
![screenshot-2020-09-08_20 02 07 072](https://user-images.githubusercontent.com/1926270/92517823-383a5680-f20f-11ea-9900-e27e107576dd.png)

**Comment by tobiasKaminsky** [comment]
I would say, the smaller the PR the better, but can you change the background color of the chat dialog, as this looks strange this way? :blue_heart:

**Comment by jancborchardt** [comment]
Yeah, good stuff! And agree with Tobi, the chat background should be the same as the conversation list and header background, meaning white in light mode and that grey in dark mode. 👍
