### ISSUE TITLE
end to end encryption

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/talk-android#861]
Hi !
https://restoreprivacy.com/nextcloud/ 
writes
**Once end-to-end encryption is fully deployed**

either this is not true or the statement on
https://nextcloud.com/talk/
**Encrypted, peer-to-peer audio/video calls**
is not precise.

excuse me to post this question here.

**Comment by kesselb** [comment]
Please use https://help.nextcloud.com for questions.
