### ISSUE TITLE
Can't accept call when App is connected with 2 accounts

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#862]
1. Connect 2 accounts (User A and User B) of 1 server to Nextcloud Talk
2. Switch to User A
3. Call User B from another device, you will see this:

![Screenshot_20200611_104253_com nextcloud talk2](https://user-images.githubusercontent.com/24530680/84622965-8a086480-aede-11ea-800c-a0ec13cdf183.jpg)

**Comment by ctilluma** [comment]
Replicated it. I'll look into it in a moment. It would be nice to have multiple accounts working properly.

**Comment by nickvergessen** [comment]
Hello there,

we are currently cleaning up old/stray github issues. Can you please retry with the current version and report back if the problem still persists for you?

cheers

**Comment by jakobroehrl** [comment]
Should be fixed, could reproduce it
