### ISSUE TITLE
Quoted font colour on reply is white, background colour too

### ISSUE THREAD

**Issue by smirkybg** [nextcloud/talk-android#864]
When replying on a message, the quoted text is using a white colour font. The background colour is not exactly white, but it's too close and it makes text hard to read.

**Comment by stefan-niedermann** [comment]
@smirkybg Please post at least the version of the app you are using and, if possible, a screenshot.

**Comment by smirkybg** [comment]
Nextcloud 19.0.0
Nextcloud Talk for Android - 8.0.9

It appears that this happens only when you reply with an emoji rather than text.
If you reply with writing text, the background is blue.

**Comment by smirkybg** [comment]
It appears that 9.0.0 Beta5 has this resolved by the redesign.
