### ISSUE TITLE
What's needed to get Talk 9.0 for Android released?

### ISSUE THREAD

**Issue by guzzisti** [nextcloud/talk-android#865]
Hi there,

i wonder what is currently going on with the android app.
Nextcloud 19 has been released a few days ago, but the release of the corresponding talk app for android is lacking behind with the latest 9.0.0beta5 in a barely usable state (atleast from my experience, so i switched back to 8.0.9).

There have been no (visible) commits to the repo for more than a month.

I hope everybody is fine, especially @mario

**Comment by stefan-niedermann** [comment]
Hey @guzzisti you can have a look at this project / kanban board: https://github.com/nextcloud/talk-android/projects/2

We are currently organizing all the stuff that needs to be done for a proper Talk 9 Android release (and there are quiet a few issues left as you can see) :slightly_smiling_face: You're welcome to grab an issue and join! :rocket:

**Comment by Valdnet** [comment]
I am also starting to worry about @mario.
@stefan-niedermann I don't think the project was abandoned.

**Comment by stefan-niedermann** [comment]
> I don't think the project was abandoned?

It is definitely not :wink:

**Comment by nickvergessen** [comment]
> I don't think the project was abandoned?

as per Stefan the project was not abandoned.

> I am also starting to worry about mario.

Mario is fine, but we need help from the community at the moment to get the next release out of the door.

**Comment by edo0** [comment]
> I am also starting to worry about @mario.
> @stefan-niedermann I don't think the project was abandoned?

Mario is ok, though he left Nextcloud to initiate a personal project. 
https://help.nextcloud.com/t/a-new-major-talk-release-for-our-mobile-clients-bringins-offline-support-and-more-cool-features/83485/14

Unfortunately, it seems that in the past 2 months Nextcloud GmbH hasn't found yet someone to take his place and pick up development

**Comment by nerrixDE** [comment]
Can't wait for Talk 9... Really sad that this project is so undermaintained.

**Comment by ctilluma** [comment]
Can't wait either. So we're making this happen! I look forward to the next release!

**Comment by Valdnet** [comment]
I can see nothing has changed in the Talk Android project.
No new commits since May. There are no new volunteers to run the project. It's a pity such a good app, come unfinished in version 9.0.

Well, there was only an appeal:
### **We want @mario back !!!**
### **We want @mario back !!!**
### **We want @mario back !!!**

**Comment by ctilluma** [comment]
I'm becoming familiar with the code over the last couple days. I'll be making more commits and pull requests as I locate areas that correspond to issues.
I want Android Talk 9 to work, and since there hasn't been much progress toward that, i'm going to be doing what I can to get this version out.

**Comment by himpierre** [comment]
Any news on this? Are you getting somewhere @ctilluma? Appreciate you do something by the way. :-)

**Comment by dan0xii** [comment]
There was a commit to master in the last few days for some UI changes (#860) and there's an open PR for another of the prioritised issues. If you are able to test either of those branches it will help move things along since I'm limited on device types and setup variations.

**Comment by himpierre** [comment]
@dan0xii Would it be enough to subscribe to the google beta channel or do I need to create an apk from master myself (if possible)?

**Comment by dan0xii** [comment]
It will be - using the beta channel will give you the dev version from the master branch and therefore you should see the updated UI.

**Comment by Thovi98** [comment]
Waouh thanks for that @dan0xii !! As soon as it’s available on Google Play beta channel, I will test it ! Thanks for your hard work !

**Comment by tobiasKaminsky** [comment]
> It will be - using the beta channel will give you the dev version from the master branch and therefore you should see the updated UI.

I am not aware that there is such an automated master branch -> dev version -> gplay beta channel mechanism.

**Comment by himpierre** [comment]
gplay beta still offers 9.0-beta5, yeah.

**Comment by dan0xii** [comment]
> I am not aware that there is such an automated master branch -> dev version -> gplay beta channel mechanism.

@tobiasKaminsky I was relaying the info from the talk dev chat. Is it possible for me to create a branch that will be fed into the beta channel or is it a manual process to upload?

**Comment by tobiasKaminsky** [comment]
It is a manual process.
Do you think it is ready for a new beta6?

cc @dasbiswajit

**Comment by mahibi** [comment]
hi @stappersg 
next week there will be some information for the further roadmap for the talk app

**Comment by stefan-niedermann** [comment]
Closing since the actual development continued and [Talk Android 11.0](https://github.com/nextcloud/talk-android/releases/tag/v11.0.0) has been released yesterday. Kudos to @mahibi and @tobiasKaminsky - looking forward to the new release :slightly_smiling_face:
