### ISSUE TITLE
No notification for new messages! (Android 10)

### ISSUE THREAD

**Issue by Akrobs** [nextcloud/talk-android#870]
Hi, Mario!
I have a new phone, Samsung S10e, with Android 10. Im testing Talk v8.0.9 and 9.0.5b. Both version have no notification. All permissions are set.

**Comment by jakobroehrl** [comment]
Did you disable the battery optimization?
-> https://dontkillmyapp.com/?app=Nextcloud%20Talk

**Comment by Akrobs** [comment]
> 
> 
> Did you disable the battery optimization?
> -> https://dontkillmyapp.com/?app=Nextcloud%20Talk

Thaks for you reply! Yep, I'm disable all optimization, add Talk app to exclude on sleep, but nothing...

**Comment by guzzisti** [comment]
duplicate of #866

**Comment by Akrobs** [comment]
Yep, but on Samsung A6 Android 10, it works very well!

**Comment by Akrobs** [comment]
It works on 8.0.10!!!!! Thanks!
