### ISSUE TITLE
All messages repeat 4 times in the android app chat room !!!

### ISSUE THREAD

**Issue by kadarpik** [nextcloud/talk-android#872]
This all happens in group chats where we have 4 members, I have posted some images also to NC forum [https://help.nextcloud.com/t/nextcloud-talk-has-bug-in-android-app-repeats-messages-for-each-group-member/87372](url)  . all data is correct at the server, tested via REST API. Current version is 8 and nextcloud 15 is in use.

There seems to be direct correlation between number of users in the group chat and number of repetitions.

**Comment by ctilluma** [comment]
Is this with standard signaling, or the HPB. 

Are you able to verify the correlation you are seeing of the number of users and the repetition? ie., do you see 3 with three members, and 5 with five members as well?

**Comment by kadarpik** [comment]
Mostly I see 4 copies with fout members at Android, everything ok at
desktop anf database level I have checked via API

E, 10. august 2020 17:16 ctilluma <notifications@github.com> kirjutas:

**Comment by kadarpik** [comment]
just tested today with my own wordpress API client talking to NC talk and
with three members I see
two messages. Two members are ordinary users and one is group admin.

*Toomas Kadarpik*



*Board member+372 55514009Skype: kadarpik*

*3KGroup OÜ*

*Ruckus Networks value added distributor*

*Pärnu mnt 139c kolmas korrus
<https://www.google.fi/maps/place/P%C3%A4rnu+maantee+139c,+11317+Tallinn,+Eesti/@59.4063792,24.7341679,17z/data=!4m7!1m4!3m3!1s0x469294c3c45ab373:0xd01cdf63dfe36c23!2sP%C3%A4rnu+maantee+139c,+11317+Tallinn,+Eesti!3b1!3m1!1s0x469294c3c45ab373:0xd01cdf63dfe36c23?hl=et>*
*Estonia*

**Comment by nickvergessen** [comment]
Hello there,

we are currently cleaning up old/stray github issues. Can you please retry with the current version and report back if the problem still persists for you?

cheers
