### ISSUE TITLE
 No notification redmi note 7

### ISSUE THREAD

**Issue by bladem2003** [nextcloud/talk-android#874]
Hello,
I have a xiaomi note 7 (miui 11 android 9) and I don't get any notifications or ringing (v8.0.9 and 9.0.5b).
I switched off the battery optimization and set all rights.

**Comment by Akrobs** [comment]
In Xiaomi phones permanent problem with notifications...

**Comment by bladem2003** [comment]
it worked very well on my wife's xiaomi (note 5A)

**Comment by smirkybg** [comment]
No notifications on OnePlus 7 Pro with stock OS (OxygenOS 10.0.6 - Android 10)

**Comment by ctilluma** [comment]
Installing through Play Store or F-Droid?

**Comment by smirkybg** [comment]
Turned out to be F-Droid. The Play Store version works.

**Comment by bladem2003** [comment]
It is the play store version.
I delete the user and I create a new one now with a new user I get all notifications.
--
Sent from myMail for Android Τρίτη, 11 Αυγούστου 2020, 01:48μ.μ. +03:00 from smirkybg  notifications@github.com :

**Comment by nickvergessen** [comment]
Hello there,

we are currently cleaning up old/stray github issues. Can you please retry with the current version and report back if the problem still persists for you?

cheers

**Comment by bladem2003** [comment]
Hello.
With the new version no problem.
