### ISSUE TITLE
App doesnt show all users while opening contact list

### ISSUE THREAD

**Issue by tunnelpr0** [nextcloud/talk-android#876]
Hi,
we found out that the Nextcloud Talk App seems to have an limit, which prevents the App from loading all users while opening the contact list (the plus button for creating a new chat).

We are running a setup with about ~100 users and only see ~50 of them. If we explicitely searched for their name, we found them and the app displayed them.

As of my research i have had seen, that the App is running a Request to an autocomplete API of Nextcloud with a limit of 50 users. I guess its this part of source code, which sets that limit.
https://github.com/nextcloud/talk-android/blob/6b1642931164531d1b2a645ac7f7310853d2cd79/app/src/main/java/com/nextcloud/talk/newarch/data/source/remote/ApiService.kt#L98

Is there anybody who can confirm such a behaviour? 
What can we do to fix this problem?

We tested it with the following software versions:
- iOS 13.6 & Nextcloud Talk 9.0.1
- ShiftOS Lite (Android 8) & Nextcloud Talk v8.0.9

**Comment by nickvergessen** [comment]
This is the expected behaviour. we list the first 50 and others can be found be search.
We are aware that this might be an issue for instances which are around the 50 user mark, but otherwise it doesn't scale and we just move the border of the problem to another value.
