### ISSUE TITLE
Fix datachannel support with latest Janus

### ISSUE THREAD

**Issue by fancycode** [nextcloud/talk-android#877]
Adding here for the Android-related fixes to support the datachannel changes in the latest Janus (actually since 0.7).

See https://github.com/nextcloud/spreed/issues/3937 for further information.

**Comment by danxuliu** [comment]
It was fixed in #907. As the _v8.0.x_ branch became the _master_ branch [it is already in master too](https://github.com/nextcloud/talk-android/blob/0bc3be1b6e9a42256a9ff1a65baabbb963e5b61f/app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java#L423).
