### ISSUE TITLE
Deactivate Video via Admin for all or some users

### ISSUE THREAD

**Issue by SLYtiger16** [nextcloud/talk-android#878]
Referencing a similar question [here](https://help.nextcloud.com/t/disable-video-call-justa-allow-chat-feature/64474/14)

I have 400-450 users for a healthcare related company, they currently use Slack to casually communicate about work related items on the go across 6 regions of my state. Video is not necessary, but the "channel-like" setup that Talk has is desirable, very similar to Slack. This in turn could replace our use of Slack and remove one more downloaded app from the list to get work done throughout the day, helping to solidify Nextcloud use.

The problem is our company will not pay for the expensive backend setup offered and Video is frankly not necessary. Other _chat_ options are not user friendly, nor are they useful on a phone. Talk would be perfect for this if we could just disable the video calling feature from administration settings, it is not needed or capable without extensive extra setup or a bunch of cash.

We have the app uninstalled but if we could remove the video option and use the feature rich chat portion instead, this would be perfect. as mentioned in the referenced article above, removing the video buttons is key to not confuse users.

**Comment by ctilluma** [comment]
I like this feature, cross platform. When an admin creates (or within the call preferences) the call, they can disable Video, or Audio and Video for any given chat. Users who come into the call are only presented with a join call button, that then will coordinate with the backend to determine what call parameters are used during the call.

**Comment by SLYtiger16** [comment]
@ctilluma I actually meant it as a complete setting for my whole organization always, not call to call, but both approaches are valuable

**Comment by ctilluma** [comment]
I do see in the code already a check for isVoiceOnlyCall on call setup, so we just need a way to set at both the conversation and organization level, to set the conversation to voice only.

**Comment by SLYtiger16** [comment]
@ctilluma agreed. Where is that in the code? I would also venture to say that an additional setting to limit calling all together, at the organization level, determine that Talk would be 'chat' feature only would be supremely beneficial. Arguably this lacking feature is the only reason my organization won't use Talk.

**Comment by ctilluma** [comment]
Under controllers->callcontroller.kt

At the organization level, i'd think the best place to place the setting configure it would be under settings->talk within the web UI.

**Comment by nickvergessen** [comment]
Yeah this needs to be fixed in the server app, so I'm closing this here
