### ISSUE TITLE
Detect when user is talking and send proper data channel messages.

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/talk-android#88]
- [ ] Send speaking/stoppedSpeaking datachannel messages.

https://github.com/nextcloud/talk-ios/issues/46

**Comment by mario** [comment]
We're moving away from data channels for this afaik.

**Comment by Ivansss** [comment]
At the moment is the only way to promote participants when they are speaking in the WebUI.
But you are right, we'll remove this messages at some point.

**Comment by mario** [comment]
Have to work on this again as it causes other issues :-/
