### ISSUE TITLE
No visual notification when a new call has started

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/talk-android#89]
When a new call has started, the phone just rings, but there is not visual notification.
So, when the phone is locked and the screen asleep, the screen does not get woken up. I need to unlock the screen manually and then pull down the notification menu, in order to join the call. From a UX perspective, these are too many steps.
Better to have a visual notification right on the screen, where you just tap and you're in the call right away.
(Android client v1.0.14 with cloud.nextcloud.com)

**Comment by mario** [comment]
Will investigate if we can bypass this in a simple way.

**Comment by mathiasconradt** [comment]
Related to this: there should also be a way to reject the call. Right now the phone keeps ringing, and if you don't want to answer it, but also want it to stop ringing, there is no real visual indicator how to do it.
Would be good if there would be two buttons: accept / reject, similar to other call apps.
