### ISSUE TITLE
Media files are stored in userdata not cache?

### ISSUE THREAD

**Issue by tacruc** [nextcloud/talk-android#891]
I just noticed that the talk app uses 2.35 gb or user data, but 360kb of cache. I assume Images and media files of conversations are stored as userdata and not in the cache.
This behavior is quite annoying, when you run out of storage.
On the other hand can I annoy everyone on the instance by sending a bunch of big immages and let there phone run out of storage?

**Comment by davidpr78** [comment]
Thanks for bringing this up. Its a big problem!

**Comment by davidpr78** [comment]
What I don't understand: I use the talk app for text messages only. I don't share or receive images or any other data. Nevertheless my userdara is 3,5 gb. Where does this data come from?

**Comment by tobiasKaminsky** [comment]
> Where does this data come from?

I had a quick look in my (rooted) device and found nc_log.txt is 90Mb big, which is 99% of user data.
Can you verify this?

**Comment by syntron** [comment]
I see this too - on my phone it is ~1.5GB of data. It is quite annoying that one has to redo the login to free the data (clear user data instead of only clearing the cache)

Content (from a backup): 264MB in nc_log.txt; I do not know what uses the remaining space ...
