### ISSUE TITLE
Mute notifications in Android, still get a sound

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#892]
- Mute notifications in Android (long press on Talk notification and select silent)
- still receive a sound
- one needs to disable sound additionally in settings of Talk

**Comment by 0ranki** [comment]
I'd like to add a little:

Android 10, (OxygenOS 10.5.11 OnePlus Nord N10)
Talk installed from Play Store, v11.1.0

- If you change notification sound only from the app's own settings, the newly selected notification sound and the default notification sound will play for each notification
- If you change notification sound from both the app's settings and Android's notification settings, you'll get two sounds per notification, I think first the Android one and then the one selected from the app
- If you mute the notification from the app's own settings, you get no notifications at all
- If you mute the sound from Android notif.settings, (but not from the app) the sound plays only once per notification, like expected.

**Comment by mahibi** [comment]
fixed with https://github.com/nextcloud/talk-android/pull/1728
