### ISSUE TITLE
Error in first time project run with vectordrawable-animated 

### ISSUE THREAD

**Issue by msndvlpr** [nextcloud/talk-android#906]
I have downloaded **talk-android-8.0.9** and when I want to run project for the first time, sync fails with the following error:
`Could not find vectordrawable-animated.jar (androidx.vectordrawable:vectordrawable-animated:1.1.0).
Searched in the following locations:
    https://dl.google.com/dl/android/maven2/androidx/vectordrawable/vectordrawable-animated/1.1.0/vectordrawable-animated-1.1.0.jar`
The strange thing is that above link to **vectordrawable-animated-1.1.0.jar** file is in accessible on web!
What is the problem and how can I solve that?

**Comment by tobiasKaminsky** [comment]
Maybe a temporary hiccup?
You can also try to download the file manually and put it in correct gradle cache.
