### ISSUE TITLE
Problems with the notifications

### ISSUE THREAD

**Issue by frpp9512** [nextcloud/talk-android#908]
I'm having big issues with the NextCloud talk Android Application's push notifications. I've tested it with two Samsung J2, with a J7, and with a Huawei, all this phones with android not superior to the 7.0 version, and it doesn't work. To know about the chat messages or calls you have to go to the app and refresh it. In my phone (LG QStylus Alpha, Android 8) works sometimes but when I get the notification, that I tap it to receive the call, it shows me a error screen with debug info that I have to dismiss so I can continue doing the call.

**Comment by tobiasKaminsky** [comment]
>  it shows me a error screen with debug info

Can you post this please?

**Comment by lazyprog** [comment]
The same troubles Redme Note 4 (MIUI Global 11.0.2 / Android 7.0 NRD90M). 
![Screenshot_2020-10-24-14-45-43-577_com android settings](https://user-images.githubusercontent.com/10957682/97081142-181cf600-1609-11eb-8fa3-489ba3049c20.jpg)
![Screenshot_2020-10-24-14-45-31-140_com miui securitycenter](https://user-images.githubusercontent.com/10957682/97081144-19e6b980-1609-11eb-9fcd-385a46970fb2.jpg)
![Screenshot_2020-10-24-14-45-18-454_com miui securitycenter](https://user-images.githubusercontent.com/10957682/97081145-19e6b980-1609-11eb-8876-f65a7984d3dc.jpg)
![Screenshot_2020-10-24-14-45-03-253_com miui securitycenter](https://user-images.githubusercontent.com/10957682/97081146-1a7f5000-1609-11eb-9a16-52eca1a6a9d6.jpg)

**Comment by apady** [comment]
I also can not get any notification from NextCloud Talk App with Huawei P40 Pro or XiaoMi 9 Pro. I installed this app (v8.2.0) with an apk package downloaded directly form nextcloud talk Adriod github release page. When the app loading for the first time, it shows the notification feature is disabled. Is there any solution for this problem?
