### ISSUE TITLE
Audio only calls

### ISSUE THREAD

**Issue by markcs** [nextcloud/talk-android#91]
Hi,

It would be great if there was an option to select 'audio call' or 'video call' before the call is established (much like is now implemented in Google Duo).  An audio call would not then send video.

Is that possible?

**Comment by mario** [comment]
Of course. Will be done in the future.

**Comment by mario** [comment]
After thinking about this, I'll make audio-only calls the default, and you'll be able to turn on the camera. Is that ok?

**Comment by jookk** [comment]
Good idea +1

**Comment by GLLM** [comment]
+1 :-)

**Comment by mario** [comment]
Will happen sooner than I initially thought, so marking it to 1.1 :)
