### ISSUE TITLE
Dark theme enhancements

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#916]
All tested with primary color dark green
- on/off switches not good visible
- in conversation: 
  - cursor hardly visible --> use text color max constrast
  - text constrast in bubble from other people: text color darker?
- header bar: dark grey, but status bar green -> should be the same

For more infos ping @jancborchardt :-)

**Comment by axheli** [comment]
Duplicate of #915

**Comment by tobiasKaminsky** [comment]
No, but both are valid, I fear…(e.g. in the linked issue mention of on/foff switches are missing)

**Comment by axheli** [comment]
> No, but both are valid, I fear…(e.g. in the linked issue mention of on/foff switches are missing)

I removed the duplicate note

**Comment by nickvergessen** [comment]
Should all be fixed already, right? @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Don't know @nickvergessen since I didn't test branding with a dark green primary color as stated in the original issue description.

**Comment by AndyScherzinger** [comment]
Except for the low contrast primary color (branding) which is a trade off until the talk client adapts dynamic theming like the files client
