### ISSUE TITLE
Sort attachment view

### ISSUE THREAD

**Issue by Simounet** [nextcloud/talk-android#919]
Hi there,
It could be great to be able to sort the attachment view. Here is the use case:
- I have a folder containing a very long list of pictures named after the shot's date (my phone photos)
- I want to share the last picture I took
- I don't want to scroll endlessly
- I just want to change the order  (from Z to A) and pick the last picture

Have a good evening and stay safe.

**Comment by tobiasKaminsky** [comment]
:+1: 
From look & feel it should be similar to NC Files app:

![image](https://user-images.githubusercontent.com/5836855/96407231-3afe7300-11e1-11eb-96c8-0f12f06997bd.png)

**Comment by markus2330** [comment]
Imho the usability already would improve a lot if the latest files/pictures are first and not the oldest ones. This should be also much easier to implement. I created an issue for that #1244

**Comment by nickvergessen** [comment]
Copying from #1102 

> open a conversation
> share from Nextcloud
> see that files/folders are first sorted A-Z (uppercase), then a-z (lowercase)
> should be inline (as on server)
> should also have sort options like on Android Files
