### ISSUE TITLE
Sessions not transferring between Android and Web

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#924]
When you're in a meeting via web and open up the talk mobile app the session dose not transfer and vise versa. You either need to leave the meeting and rejoin it via talk app or web.

**Comment by tobiasKaminsky** [comment]
@nickvergessen can you give me some insights what we can do here?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/issues/1587
Currently expected. However we added a soft/force joined option in Talk9/10 and the other session receives a dedicated error when it was removed and the signaling connection is closed, but as far as i know android doesn't listen to signaling 🤷‍♂️

**Comment by axheli** [comment]
So nothing we can do here?

**Comment by nickvergessen** [comment]
Well I just wrote to things that can be done.

**Comment by axheli** [comment]
> Well I just wrote to things that can be done.

Sorry misunderstood it.

**Comment by axheli** [comment]
@tobiasKaminsky any updates on this?

**Comment by mahibi** [comment]
for web only this works now with different browsers.
it's planned to change this behaviour for the mobile apps too the next weeks or months

**Comment by nickvergessen** [comment]
APIv4 support allows double joining, so closing this

**Comment by andyxheli** [comment]
Still don't work. The sessions dose not transfer from web into mobile app so I don't think this should be closed. I just tested it had a meeting via web and opened the talk app on android and session was still active via web and on top of that when I clicked on the video button it just said ringing and never transfer the session.  Currently on IOS as soon as you enter the chat it disconnects the chat from web if this is something that's not support on Android Talk at this time please let me know.  Thank you

**Comment by andyxheli** [comment]
This is still an issue the android app never pickups a dubplate session and the call never gets transfer can someone open this ticket and fix the problem

**Comment by jasonjenssen** [comment]
Issue is still there, Calls dont come through or joining a call fails/calling screen freezes
