### ISSUE TITLE
Picture-in-picture Support

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#925]
@tobiasKaminsky  I was thinking we implement this feature  on the Android Talk app please see below link 

https://www.geeksforgeeks.org/how-to-implement-picture-in-picture-pip-in-android/

**Comment by nickvergessen** [comment]
Hi @axheli sounds like a good and interesting idea.
But please avoid mentioning people. The responsible people monitor the repos themselves, thanks

**Comment by axheli** [comment]
> Hi @axheli sounds like a good and interesting idea.
> But please avoid mentioning people. The responsible people monitor the repos themselves, thanks

Thank you! understood sorry about that.

**Comment by tobiasKaminsky** [comment]
> i wanted some help to point me on the right direction

You already have found a good reference.
My quick idea would be:
When in call and minimize button is pressed do this PIP

Activity is called CallController

**Comment by axheli** [comment]
@tobiasKaminsky Thanks but i have no idea where to even start i never coded before

**Comment by andyxheli** [comment]
#1655

**Comment by andyxheli** [comment]
#1655
