### ISSUE TITLE
Enable multiple user in a group meeting 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#928]
Only able to see and hear  one user in a group meeting. Is available on the IOS

**Comment by tobiasKaminsky** [comment]
What do you mean with "enable user"?
Can you give us a bit more info?

**Comment by axheli** [comment]
> What do you mean with "enable user"?
> Can you give us a bit more info?

Hello, what when for example if you and I and something else was on the talk meeting the user using the android talk app can only see and hear one person.

**Comment by tobiasKaminsky** [comment]
@nickvergessen this then is more related to server talk, or? 
Or might there be a problem on Android's side?

**Comment by nickvergessen** [comment]
We don't limit anything related like this. Could be that a TURN server is missing and therefor people are not connecting to each others.

**Comment by tobiasKaminsky** [comment]
So it seems that this is not Android related.
For server "support" setup, please ask over at help.nextcloud.com

**Comment by axheli** [comment]
> So it seems that this is not Android related.
> For server "support" setup, please ask over at help.nextcloud.com

Turn server is configured and I don't have issues on any other platform then a android so please reopen the ticket

**Comment by axheli** [comment]
@tobiasKaminsky  I don't think this is only and android issue it's also happening in the IOS side . This only happens when using the IOS or android talk app participants cannot see or hear one another but if you're on the web you could see and hear all participants
