### ISSUE TITLE
Nextcloud Talk cannot cope with strange ports

### ISSUE THREAD

**Issue by Maulwurf16** [nextcloud/talk-android#93]
Short story.
I use my Nextcloud behind a DS-Lite (Unitymedia) internet access, and therefore have no public IPv4 address. Thus, I use a Portmapper, which maps my IPv6 Address to something like:

http://some.verystrangeaddress.de:123456/nextcloud

which is public available.

The Nextcloud App (iOS as well as Android) and the desktop sync Clients can cope with this, the chat app however cannot. I assumed, that it was the lack of ssl, but read that you support "normal" http in other issues.

EDIT: My Bad - I'm in the Android Channel. Wanted to post this in the iOS app, as I now did [here](https://github.com/nextcloud/talk-ios/issues/54). Is this issue also active on Android?

**Comment by mario** [comment]
I have no idea. Did you install and configure TURN server? :)

**Comment by Maulwurf16** [comment]
No I don't :(, however I can initate calls via browser, even outside of my home network. So thoug I don't know for sure, I do assume, that I would not need a TURN Server

**Comment by mario** [comment]
You probably do need TURN. Browser is a different thing I guess. But unsure. If you have an Android phone, try this...

**Comment by mario** [comment]
I will close this in the mean time :)

**Comment by Maulwurf16** [comment]
Am ok with closing :) as this issue is not android related.
Just for interest pruposes: I just tried accessing with a TURN Server, which didn't change anything. The (iOS) Nextcoud Talk App still cannot connect with the error message "Nextcloud Talk App not found"

**Comment by mario** [comment]
Ah ok. Would appreciate if you could find the Android device to test with too! :)

**Comment by Maulwurf16** [comment]
will do this evening :)

**Comment by mario** [comment]
@Maulwurf16 thanks ;)

**Comment by Maulwurf16** [comment]
@Mario just tested with the Android Client. Everything works absolutely fine :)
Arbytrary ports and just http is absolutely no problem for the Android app.

It really only is the iOS Client, which cannot cope with pure http connections.
All of this has nothing to do with the port.

Sorry for the false alarm.

**Comment by mario** [comment]
Thanks for testing 👍
