### ISSUE TITLE
Question / Idea: Cordova-App for Mobile?

### ISSUE THREAD

**Issue by theoneandonly-vector** [nextcloud/talk-android#930]
As we can see it's hard to keep up with the latest updates (Nextcloud Talk on Desktop seems to work fine).
Is there the possibility to create a simple cordova app just to adjust GUI to mobile phones and add push-messages? so there won't be such a hassle to keep up?

**Comment by tobiasKaminsky** [comment]
Starting on December we will have a new FTE for Talk.
Cordova is no option for us, as it would mean to propably loose some functionality and also drop all of the previous work.

(of course this can be done by our awesome community, if wanted/needed. But I would suggest to rather help here to focus our power…)
