### ISSUE TITLE
Enable screen_security by default

### ISSUE THREAD

**Issue by eayin2** [nextcloud/talk-android#931]
Set screen security to `@DefaultValue(R.bool.value_true)`
https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferences.java#L224

**Comment by tobiasKaminsky** [comment]
Can you elaborate a bit why you want to have this as a default setting enabled?

This prevents screen recording/capturing, but is also not default enabled on other messengers (if available at all).

**Comment by eayin2** [comment]
I think enabling it by default will prevent screen recording by the majority of users, because most people don't know or bother to change this setting. Forcing other video call participants to enable screen security when one participant enabled it (during the initialization handshake) would be ideal, but this small change (only on Android environments) would be sufficient for my use case.

**Comment by tobiasKaminsky** [comment]
Honestly I still do not get this.
Do you not trust the others app on your device? 
(For bank apps I understand why they prevent showing info in recent app, so that other people shortly using the device cannot see any confidential info, but here…?)

@Ivansss (iOS dev)
@nickvergessen (server)

What do you think?

**Comment by nickvergessen** [comment]
Yeah I would also not do this by default. Taking screenshots is a must-have feature.

**Comment by eayin2** [comment]
> Honestly I still do not get this.
> Do you not trust the others app on your device?
> (For bank apps I understand why they prevent showing info in recent app, so that other people shortly using the device cannot see any confidential info, but here…?)

I don't want the other participant of the video call to be able to make screenshot of me. When I configure the screen security in the options the other video participant only my own device can't make screenshots anymore. Can you implement it like so, that when I enabled screen security as a privacy setting, that the other party can't take screenshots anymore for that specific video call

**Comment by nickvergessen** [comment]
That doesn't work anyway when they join with the web they can take screenshots with their browsers just fine.

**Comment by eayin2** [comment]
Even if you add a feature to not allow web video participants you can record the screen with a rooted device or scrcpy (with adb) - just most Android users don't know or bother. People who really want to take screenshots can just enable it in the settings. Privacy is a thing nowerdays and I think enabling it by default doesn't hurt. Cheers
