### ISSUE TITLE
any message that being sent and received while in a call is shown twice

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#935]
Hello any message that being sent and received via the app is show up twice.

![image](https://user-images.githubusercontent.com/59488153/98839287-fabe9900-240a-11eb-8df2-07df63cfd5fc.png)

**Comment by tobiasKaminsky** [comment]
Is this happening only during call? Or always?

**Comment by axheli** [comment]
@tobiasKaminsky  This happens only during the call.

**Comment by Joe7new** [comment]
Hi ! **_Same problem_**. Happens (only) during call. Sometimes messages are shown three times ! When the call is stopped and I take a look in the chat history then all chat-messages are shown in the right way (one message displayed for one message sent).


p.s. I do _also have the problem when I send a message to my handy in standby-mode_ (no display on). 
(**seems app need to have focus...?**)

(all apps latest version and Nextcloud latest version)

regards, Joe

**Comment by andyxheli** [comment]
Still an issue.

**Comment by andyxheli** [comment]
No longer an issue on Talk App v12.2.1
