### ISSUE TITLE
Talk app mute icon not working

### ISSUE THREAD

**Issue by axheli** [nextcloud/talk-android#940]
So if a user mutes you the mute button dose not change to mute on the android app do you don't know that you're on mute. You'll have to double click on the mute icon to unmute yourself. I don't see this being a server issue this works with no issues in the IOS platform! If a user mutes you the the mic icon changes but not on android.

**Comment by tobiasKaminsky** [comment]
@Ivansss have you implemented this? 
If yes, can you give me/us some info how to do this?

**Comment by Ivansss** [comment]
Hi @tobiasKaminsky :)

This is about the "forceMute" feature https://github.com/nextcloud/talk-ios/pull/290
Moderators can mute other participants from the webUI.
If this happen, the muted participant will receive a "forceMute" signaling message.

I see that there is something already implemented to handle those messages in the android app
https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/controllers/CallController.kt#L1399

Could you check why the button icon is not updated?

**Comment by tobiasKaminsky** [comment]
> I see that there is something already implemented to handle those messages in the android app
> https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/controllers/CallController.kt#L1399
> 
> Could you check why the button icon is not updated?

This is on master only, but stable is currently 8.x.
So let us assume that this works once we are on latest stable again.

@axheli it will be then in one of the next major version.
If not, please re-open.
