### ISSUE TITLE
Group conversation picture

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/talk-android#943]
Add the ability to set a group conversation picture. 
This is the link to the main issue: https://github.com/nextcloud/spreed/issues/927
Let's keep the conversation there so we can make this as consistent as possible across platforms.

**Comment by tobiasKaminsky** [comment]
Although FTE talk dev will start at 1.12, I suspect that this will not be ready until NC21 release.

**Comment by nickvergessen** [comment]
Duplicate of https://github.com/nextcloud/talk-android/issues/2555
