### ISSUE TITLE
App doesn't open on iOS/iPadOS

### ISSUE THREAD

**Issue by gladonias** [nextcloud/talk-android#944]
After the latest update of NextCloud Talk (v10.1.0), the app doesn't open. It doesn't show anything, it just closes itself.
App is installed on an iPhone and an iPad running the latest versions of iOS/iPadOS.

**Comment by gladonias** [comment]
My apologies, opened the issue on the wrong repository.

**Comment by tobiasKaminsky** [comment]
> I'd appreciate if any admin would delete this issue.

There is no need of deleting it.
Mistakes can happen, closing is fine enough :-)
