### ISSUE TITLE
displaying quoted message

### ISSUE THREAD

**Issue by daita** [nextcloud/talk-android#945]
When displaying a quoted message, the author of the new message is not placed at the top, in front of the avatar like on the webclient.

See this message from Arthur, quoting me; viewed from the web client, and from the android client.

It is kind of disturbing, and I think the way the message is displayed on the web client is better.

![talk_displaying_quotes](https://user-images.githubusercontent.com/1038617/101766539-74ad7500-3ad2-11eb-8819-63fc513609fb.png)

**Comment by jancborchardt** [comment]
Jep, agree that the avatar is a bit much. Also the timestamp is unnecessary detail.

Checked Signal as well and they do it without avatar and timestampt too.
