### ISSUE TITLE
Strange output in Error message during initial start/config

### ISSUE THREAD

**Issue by lebochequirit** [nextcloud/talk-android#95]
I had afwall blocking a fresh Nextcloud Talk install and it said
"failed to connect to nc.mydomain.com/217.11.48.191:443"

I presume it should say "failed to connect to $givenserveraddress:443" or even omit the port?

This is meant as a humble contribution, not as a complaint.

L.B.Q.R.

**Comment by mario** [comment]
Ah. You're right - I simply show whatever the library we use returns. Will eventually/hopefully fix improve this!

Thanks for the report!
