### ISSUE TITLE
display issues with non default font sizes

### ISSUE THREAD

**Issue by Minnietheandroid** [nextcloud/talk-android#955]
Hi. I'm wondering if this has slipped under the radar.
When adding an attachment the display looks a bit odd, (the extra cutoff lines are scrolling right to left) 

Phone is a Pixel2 XL
Size | 6.0 inches, 92.6 cm2 (~76.4% screen-to-body ratio)
Resolution | 1440 x 2880 pixels, 18:9 ratio (~538 ppi density)

![Screenshot_20210107-073056_Nextcloud_Talk](https://user-images.githubusercontent.com/3885113/103819006-b9223580-50bd-11eb-83aa-3a257cc238a3.png)
![Screenshot_20210107-073102_Nextcloud_Talk](https://user-images.githubusercontent.com/3885113/103818997-b0c9fa80-50bd-11eb-86a9-a2cccaee87e1.png)

Love the app, thank you:)

**Comment by mahibi** [comment]
Thanks for the bug report. 
Could you add your Android version and the Version of the Nextcloud Talk App?

**Comment by Minnietheandroid** [comment]
Thanks for the reply and apologies for the giant pic.

This is on Android 10, and Nextcloud-Talk 8.2.0.
I got the phone July 2020 and the issue has existed for as long as I can remember.

**Comment by mahibi** [comment]
did you change the system wide font-size to "large" or "largest"? With these font-sizes, i can reproduce your issue (Default font-size works fine).

**Comment by Minnietheandroid** [comment]
Yes you're right. I have the font size set to largest.

**Comment by mahibi** [comment]
fixed by https://github.com/nextcloud/talk-android/pull/1057
