### ISSUE TITLE
[FEATURE REQUEST] Add text chat capabilities

### ISSUE THREAD

**Issue by c0fe** [nextcloud/talk-android#97]
I would like to request that text chat capabilities are added to the Android client for Nextcloud Talk. XMPP is bulky and Nextcloud Talk is good but having only video chat is annoying. Please add text chat capabilities.

**Comment by mario** [comment]
Duplicate of https://github.com/nextcloud/talk-android/issues/59 :)

Will be done, but not soon! :)
