### ISSUE TITLE
new Nextcloud-Talk Android Developer & Roadmap

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#984]
Hi Nextcloud Community,

my name is Marcel and I have the honor to pick up development of the nextcloud android talk app as a new employee at Nextcloud. As you may know, the development of the app was problematic in the past because an employee left the company.
I will do my best to continue the development and gradually make the app more stable. It's a challenge to understand the code base and to learn new technologies at the same time. Unfortunately, the app has very few unit tests, which doesn't make the situation any easier. In any case, I hope to find my way around faster month after month. 

It is very important to me to involve the community more closely. Therefore, in the future there will be pull requests for all code changes and I would like to pay more attention to the github-issues. Another goal is to unify the development between the Talk app and the File app.

Thanks to @tobiasKaminsky there is now an Alpha Channel in which interested parties can obtain the latest version of the talk app from the master branch on a weekly basis. Read more in the [testing](https://github.com/nextcloud/talk-android#testing) chapter of the readme file.

## Roadmap
As you can see, there was never a finished version 9 (#865). This is due to the fact that the developer left the company in the middle of a large code refactoring. In the meantime, new features had to be delivered, which took place on the version 8 branch. This branch is now the current master branch. The old master branch (which should have become version 9) is now called "master-broken" and is to be rebuilt in the long term to become the new master branch one day. All features that do not yet exist on "master-broken" should be ported there. If you want to contribute code before the "master-broken" branch becomes the new master branch, it is recommended to develop on the current master branch and features will be ported afterwards. The following scheme illustrates the history of the branches:

![grafik](https://user-images.githubusercontent.com/2932790/106158760-613e9200-6184-11eb-8f31-a8b193431d1d.png)

Therefore, versions 9 and 10 are skipped to adapt to the [server app's](https://apps.nextcloud.com/apps/spreed) publishing cycle. Until the release of version 11, we would be happy to welcome a few [alpha testers](https://github.com/nextcloud/talk-android#testing). 

I want to thank Nextcloud for the great opportunity to develop this app and I thank the community for their persistent help.

Keep up the good work and stay healthy!

**Comment by maxcco** [comment]
It's great news to see a new dev for this app

Looking forward to the improvement and I will try your newly alpha build this week ;)

**Comment by Valdnet** [comment]
> Thanks to @tobiasKaminsky there is now an Alpha Channel in which interested parties can obtain the latest version of the talk app from the master branch on a weekly basis. Read more in the testing chapter of the readme file.

@mahibi I'd like to test the alpha version, but don't use the google store. It would be good to put the app on Github or https://download.nextcloud.com and download as it is for Nextcloud Android.

PS: I tested previous versions a lot. The detected bugs were quickly fixed by @mario.

**Comment by mahibi** [comment]
@Valdnet you can find the alpha apps on Google Play and on https://download.nextcloud.com/android/nightly/talk/ (i think we will reorganize the folder-structure up there soon so it makes more sense). Sure, i hope i can fix any bugs reported on github. The apk's on the download page are the same as on Google Play, so this doesn't make any difference.

**Comment by mahibi** [comment]
And what i didn't mention until now:
Thanks @mario for everything you have done so far for this app! It's really impressive to see how much work you put in there.

**Comment by Valdnet** [comment]
> i think we will reorganize the folder-structure up there soon so it makes more sense
I think exactly the same 😉.

I see Talk come to life again.

**Comment by pjrobertson** [comment]
Welcome @mahibi ! Excited to see you've joined the Nextcloud and you're picking up work on this really promising app! Looking forward to seeing new things soon! (Full offline caching of all messages! :D )

**Comment by mario** [comment]
Full offline caching of all messages is actually done in what @mahibi calls "master-broken" atm, along with many other improvements, whole new UI, etc -  waiting for a few bug fixes to make it entirely usable @pjrobertson

**Comment by Valdnet** [comment]
@mario How nice to see you :wave:.

@mahibi I have noticed that the Alfa versions have been deleted on the Nextcloud server. Do you know anything about it?

**Comment by mahibi** [comment]
Hi @mario 👋
Yes i especially like the new UI you made, good job 👍
I hope this won't take too long to migrate the features and to fix the bugs.

So @pjrobertson thanks to @mario offline caching is done, but "just" has to be merged with other features so it's not released yet.

@Valdnet alpha version folder has been deleted by an other script for the files app. thanks for the hint. Waiting for an admin to create an own folder for andrid-talk. will inform you when it's done.

**Comment by tobiasKaminsky** [comment]
> @Valdnet alpha version folder has been deleted by an other script for the files app. thanks for the hint. Waiting for an admin to create an own folder for andrid-talk. will inform you when it's done.

New folder is: https://download.nextcloud.com/android/talk-alpha/
@mahibi this needs also to be changed in readme.md, if I am not mistaken.

**Comment by Valdnet** [comment]
@tobiasKaminsky Thanks a lot 👍. Now I will be able to download new versions of Alpha again and test them 😉.

**Comment by dan0xii** [comment]
> The old master branch (which should have become version 9) is now called "master-broken" and is to be rebuilt in the long term to become the new master branch one day. All features that do not yet exist on "master-broken" should be ported there. If you want to contribute code before the "master-broken" branch becomes the new master branch, it is recommended to develop on the current master branch and features will be ported afterwards.

Hello @mahibi. I have (partially) developed a "share with" feature against the old master branch that would allow users to send text or images from other apps as messages in Talk. I've separated it into a plain text only branch (seen here: https://github.com/dan0xii/talk-android/tree/share-with) in the hope it would be easier to get it finalised and then work on image sharing. To clarify from your message above: should I still open a PR against the `master-broken` branch with my changes?

Hope that makes sense and glad to see someone picking up on @mario's great work.

**Comment by mahibi** [comment]
Hi @dan0xii 

thanks for working on the app!
I had a look at your code, it looks promising! 👍

Since you developed on branch "master-broken" it is up to you on which branch you want to finish the feature.
If you stick to master-broken you should be aware that it may take a while for the feature to be released.
If you adapt your code so that it can be used in the master branch, the feature will probably end up in the play store faster. 

Note that basic file sharing from local storage within the chat view is implemented in master for version 11:
https://github.com/nextcloud/talk-android/pull/958
Improvements could be (some of which you are already working on): https://github.com/nextcloud/talk-android/issues/987

**Comment by mjwonderwomam** [comment]
Hi.
Love the app.
A few suggestions (android version):
1. Split screen to type and video chat simultaneously.
2. Add pictures (and videos if not too much to ask) directly as in other chat apps.
3. Search criteria to search for keyword in a conversation.
4. When app is placed in background, video of other chatters doesn't return and I have to restart chat.
5. When a voice call comes on the phone while video chatting and is refused or hung up, the sound reverts back to the phone call speaker, not the speakerphone or Bluetooth, etc. that was used prior to the call coming in.

Thank you for considering my input.

**Comment by mahibi** [comment]
hi @mjwonderwomam , welcome to github! 👋
thanks for your suggestions and bug descriptions! it would be nice if you could create separate issues for your concerns. 
you can add the lables "enhancement" or "bug" for this. 
this way it is easier to keep track of things.
Adding pictures and videos will be available in the next release which will be available tomorrow or in the next days.

**Comment by k3vinb0ss** [comment]
hi @mahibi, How can I check out nextcloud android files + talk merge version ? I was thinking of doing that since last week now i see you guys doing it too

**Comment by mahibi** [comment]
hi @k3vinb0ss 
i'm not sure if i get you right. You want to checkout the Files App and the Talk App right?? So just checkout out to different folders. There is no need to combine anything.

**Comment by k3vinb0ss** [comment]
> hi @k3vinb0ss
> i'm not sure if i get you right. You want to checkout the Files App and the Talk App right?? So just checkout out to different folders. There is no need to combine anything.

"Another goal is to unify the development between the Talk app and the File app." 
I mean this one. Did it  start yet or in future ?  My goal is don't have to open 2 seperated apps (in this case File and Talk)

**Comment by mahibi** [comment]
> > Another goal is to unify the development between the Talk app and the File app.
> 
> I mean this one. Did it start yet or in future ? My goal is don't have to open 2 seperated apps (in this case File and Talk)

Ah ok. Perhaps this was not clearly formulated. The apps will not be merged. This is not intended and won't be possible. What i meant is that the development between the Files App and the Talk App should benefit from each other. So there should be more cooperation between the developers and in the long term the same technologies/libs should be used.

**Comment by ASerbinski** [comment]
I'm very happy to hear that there is going to be some movement on this project.
Of very critical importance, and I sincerely hope that you can respect just how important this is, is to be able to deliver talk push notifications without relying on 3rd party (i.e. google) services.

The beautiful thing about Nextcloud, is that it does just about everything that google does -- file and photo storage, contact management, calendar management, and voice/video/text communications, and does so in a manner that gives people the freedom to maintain control over their own data, however, it is a critical and potentially DANGEROUS oversight that some of these benefits can't be utilized without still depending on that service we are trying desperately to avoid.

There is an issue about it here; https://github.com/nextcloud/talk-android/issues/257

**Comment by g0d-m0nky** [comment]
Hi, the development of this app is really exciting, thank you for all the work you have done on it.

One issue I am having is that whenever I share a photo ok the android app, when I then try and open the photo, it tries to open it in either chrome or the nextcloud app, with either choice then telling me 'the file could not be found'. Is this normal behaviour or do I have something setup wrong?

I am using alpha 06 v12.

**Comment by mjwonderwomam** [comment]
I have the issue where it opens it always in the Nextcloud cloud storage app.

Another issue to address, the picture or video sent doesn't show who sent it. If there's a group of people, I don't know who which person sent it. It only says it if you catch the initial notification pop up as it comes in, after, it's anyone's guess.

Thanks!



Sent from my Galaxy



-------- Original message --------
From: g0d-m0nky ***@***.***>
Date: 4/17/21 09:22 (GMT-05:00)
To: nextcloud/talk-android ***@***.***>
Cc: mjwonderwomam ***@***.***>, Mention ***@***.***>
Subject: Re: [nextcloud/talk-android] new Nextcloud-Talk Android Developer & Roadmap (#984)


Hi, the development of this app is really exciting, thank you for all the work you have done on it.

One issue I am having is that whenever I share a photo ok the android app, when I then try and open the photo, it tries to open it in either chrome or the nextcloud app, with either choice then telling me 'the file could not be found'. Is this normal behaviour or do I have something setup wrong?

I am using alpha 06 v12.

**Comment by mahibi** [comment]
@g0d-m0nky 'the file could not be found' should not happen. Anyway currently it's being worked on that the files open directly inside the app so this will change with the next release. See https://github.com/nextcloud/talk-android/issues/1098 

@mjwonderwomam i guess you mean this happens in group chats? this was fixed with pull request https://github.com/nextcloud/talk-android/pull/1081 (thanks to @starypatyk !!) and it will be out in the next release.

**Comment by mjwonderwomam** [comment]
Awesome 👌 thanks all!



Sent from my Galaxy



-------- Original message --------
From: Marcel Hibbe ***@***.***>
Date: 4/19/21 13:37 (GMT-05:00)
To: nextcloud/talk-android ***@***.***>
Cc: mjwonderwomam ***@***.***>, Mention ***@***.***>
Subject: Re: [nextcloud/talk-android] new Nextcloud-Talk Android Developer & Roadmap (#984)


@g0d-m0nky<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fg0d-m0nky&data=04%7C01%7C%7C017c0b8b20604860437808d90359c812%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637544506402237034%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=29kxqlVcLkJ9fHy5D0a54GYRoCrm%2FFaOdoqI1BtES2M%3D&reserved=0> 'the file could not be found' should not happen. Anyway currently it's being worked on that the files open directly inside the app so this will change with the next release. See #1098<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnextcloud%2Ftalk-android%2Fissues%2F1098&data=04%7C01%7C%7C017c0b8b20604860437808d90359c812%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637544506402246990%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BZRCSZPmoBazDdmy9IfOsxlDztk0ZVoRBwpm5KxBIGs%3D&reserved=0>

@mjwonderwomam<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmjwonderwomam&data=04%7C01%7C%7C017c0b8b20604860437808d90359c812%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637544506402246990%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NXqEx7bw11622RxcUqaDEkBWHHAnxiuaqrPKkkmOemo%3D&reserved=0> i guess you mean this happens in group chats? this was fixed with pull request #1081<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnextcloud%2Ftalk-android%2Fpull%2F1081&data=04%7C01%7C%7C017c0b8b20604860437808d90359c812%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637544506402246990%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=T3h5YDvPoE6VazyEM9YoYOFYQDULXh%2BuUD7KqzxGBGQ%3D&reserved=0> (thanks to @starypatyk<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstarypatyk&data=04%7C01%7C%7C017c0b8b20604860437808d90359c812%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637544506402256949%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=d5zT4zUfIDjiBwoqdmjZeFuBPPBfHSvgDX%2BbCeifG%2Bo%3D&reserved=0> !!) and it will be out in the next release.
