### ISSUE TITLE
improve files upload from local storage

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#987]
enhancements for #435 :
- [x] confirmation screen before sharing file to chat #995 
- [ ] Info when the upload failed in the background thread
  - [ ] retry button
- [ ] video/image compression
  - [ ] optional (via settings)
- [x] show progress as notification
- [ ] placeholder image in chat (including progress)
- [x] Enable the app to process Android's "Share To" command (handle the Intent..)
  - [ ] show additional Screen to select one or multiple chats where the file should be posted

**Comment by Hanskes** [comment]
Might it be possible to take and upload a photo directly from the app?

**Comment by mahibi** [comment]
@Hanskes as far as i know take and upload a photo directly from the app is not planned for the near future and I guess i won't have time to do this on the side

**Comment by jakobroehrl** [comment]
> Installed the alpha version and it is already running smoothly, good job !! Might it be possible to take and upload a photo directly from the app?

Topic is already listed here: https://github.com/nextcloud/talk-android/issues/306

**Comment by Valdnet** [comment]
Has anything moved with the options below?

- show progress as notification
- placeholder image in chat (including progress)

 I will say that it is very much missing from Talk 😬.

**Comment by mahibi** [comment]
> Has anything moved with the options below?
> 
>     * show progress as notification
> 
>     * placeholder image in chat (including progress)
> 
> 
> I will say that it is very much missing from Talk grimacing.

unfortunately this won't make it to 14.0 but hopefully have time for it soon!

**Comment by mahibi** [comment]
closing this as progress bar is done with https://github.com/nextcloud/talk-android/pull/2351 
created https://github.com/nextcloud/talk-android/issues/2375 for the the message preview of uploading messages
