### ISSUE TITLE
"Error inflating class android.webkit.WebView" on server connection screen (Android 5.0.2)

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#989]
Versions: 
Android: 5.0.2
Talk App: master a71e3fcd540c8a4125113b093b629af81c7802c3 (but should not be related to this)

reproduce:
- Enter server address 
- hit connect

Error:
Binary XML file line #40: Error inflating class android.webkit.WebView

may be identical to:
https://github.com/nextcloud/android/issues/4943

**Comment by mahibi** [comment]
tried to checkout older android talk version to verify the error occured in the past.
checked out tag v8.0.9. and get the error:

talk-android/app/build/generated/source/kapt/genericDebug/com/nextcloud/talk/models/json/search/ContactsByNumberOverall$$JsonObjectMapper.java:14: error: cannot find symbol
public final class ContactsByNumberOverall$$JsonObjectMapper extends JsonMapper<ContactsByNumberOverall> {
                                                                                ^
  symbol: class ContactsByNumberOverall


cleaning etc did not help yet.

**Comment by nickvergessen** [comment]
Still an issue?

**Comment by AndyScherzinger** [comment]
@nickvergessen: @mahibi linked to the files client issue. TLDR; there is nothing you can do. GPlay users with Android 5 need to install the Android Web View app which updated the WebView (to a version that works). F-Droid people might need to give Bromite a try. Other than that I'd say close it. The info is here and at some point we might drop Android 5.0.x (oldest release we support atm) and the issue can't even come up again.
