### ISSUE TITLE
Call menu design

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#99]
- Can we place the menu just where the menu icon is instead of at the bottom? The menu shouldn't be in a different plce than where was clicked. Also compare to Files Android app.
- Then we can also drop the irrelevant header "What would you like to do today?"
- "Leave call" should always be the last item in the list, and colored red
- Can we get icons to the left of the items? Rename pencil, Share icon, Delete icon

**Comment by mario** [comment]
In order of your questions :)

- no, because bottom sheet is also standard way of showing a menu + it enables a nicer flow for operations
- we can discuss this - we can either change it or remove completely
- this shouldn't be a problem
- also not a problem, but we probably can't get it for all actions. Unsure.

**Comment by mario** [comment]
@AndyScherzinger please add icons (not the colored versions thought) and put leave call always as last item. Example from iOS:

![screen shot 2018-04-26 at 14 09 00](https://user-images.githubusercontent.com/5810/39305485-90b37b3c-495d-11e8-8906-9b8fa9d36afb.png)
![screen shot 2018-04-26 at 14 09 13](https://user-images.githubusercontent.com/5810/39305486-91baac80-495d-11e8-8bd1-844a02f9508a.png)
![screen shot 2018-04-26 at 14 09 38](https://user-images.githubusercontent.com/5810/39305487-922276c6-495d-11e8-83e8-ed5d72752424.png)

I guess I already have some of the icons, and for those that I don't, they might be in https://github.com/nextcloud/talk-ios or https://github.com/nextcloud/spreed
