### ISSUE TITLE
"Nextcloud Talk App not installed on the server"

### ISSUE THREAD

**Issue by MajaR91** [nextcloud/talk-android#991]
Version: 8.2.0
Android: 10/MIUI Global 12.0.2
Device: Xiaomi Redmi Note 8 Pro

When you try to log in, the above error message appears.  Then you will be redirected to the input of the server address.
Multiple attempts to uninstall and reinstall did not solve the issue.

Edit: German wording: "Nextcloud Talk App nicht auf dem Server installiert"

**Comment by mahibi** [comment]
Hi @MajaR91
On Nextcloud there are "Apps" that indeed need to be installed on the Nextcloud Server. So to use the Talk App on Android, you have to connect to a Nextcloud Instance that has the "Talk" Server App installed.

If you are an admin of the Nextcloud Instance, just install the "Talk" App via the menu:
![grafik](https://user-images.githubusercontent.com/2932790/106599358-3c1d9b00-6559-11eb-9746-184405ec598e.png)

Otherwise you might ask the admin to do so.

After that, you should be able to connect to the Nextcloud Instance with your Android phone.
Let me know if this solves your issue, Marcel

**Comment by MajaR91** [comment]
Hello Marcel,

Thank you for the quick answer!

> On Nextcloud there are "Apps" that indeed need to be installed on the Nextcloud Server. So to use the Talk App on Android, you have to connect to a Nextcloud Instance that has the "Talk" Server App installed.

The problem did only occurr after I uninstalled the app after displaying issues. I am a teacher, the whole school works with Nextcloud and Nextcloud Talk, therefore the app should be installed on the server.
I will forward your solution proposal to the admin!

Maja

**Comment by mahibi** [comment]
Closing this issue. If it turns out Talk was installed on the server, fell free to open this issue again.
And feel free to create an issue about the displaying problem you talked about.

**Comment by MajaR91** [comment]
Hello Marcel,

Talk actually is installed on the server.
After the 50th attempt of uninstalling and reinstalling the app I finally managed to login. I have no Idea how or why but I am so happy!
The displaying issues are gone as well.

Have a nice evening and stay healthy!

**Comment by mahibi** [comment]
Sounds strange and I have no idea what could have gone wrong.
Glad it works for you again.
Thanks for your effort to register at github for this issue, I really appreciate that. For the future, feel free to report any issue or enhancement.
Stay safe, Marcel

**Comment by Torser76** [comment]
Nextcloud 22.0.0 RC2

Je n'arrive pas connecté nextcloud talk à partir de mon téléphone xiaomi poco2 j'ai toujours l'avertissement "application nextcloud talk n'est pas installé sur le serveur, abandon" pourtant ils est bien installé et activé c'est le même problème pour mes autres utilisateurs. Un peu d'aide svp

**Comment by mahibi** [comment]
translation of issue from @Torser76 :
"Nextcloud 22.0.0 RC2
I can not connect nextcloud talk from my xiaomi poco2 phone I still have the warning "nextcloud talk application is not installed on the server, abandon" however they are installed and activated it is the same problem for my other users. A little help please "

**Comment by AndyScherzinger** [comment]
@Torser76 can you update the nextcloud server to the latest stable v22 and also latest Talk version 12 and also the Android client to 12.1.1+ and check if the issue persists?

**Comment by dvergeylen** [comment]
> @Torser76 can you update the nextcloud server to the latest stable v22 and also latest Talk version 12 and also the Android client to 12.1.1+ and check if the issue persists?

En 🇫🇷: @Torser76, pouvez-vous mettre à jour votre serveur NextCloud à la dernière version stable (v22), la dernière version de l'application Talk (12) et également le client Talk Android version 12.1.1+ et tester si le problème persiste?

**Comment by dalins** [comment]
> @Torser76 can you update the nextcloud server to the latest stable v22 and also latest Talk version 12 and also the Android client to 12.1.1+ and check if the issue persists?

I am facing the same issue with the F-Droid version (11.1.2). After switching to the Google version (12.1.1) everything works fine.

On F-Droid this is the actual version at this moment and related to issue #1450 the next release (12.2.2) is planned for the 03.08.2021?

Additional information:
NC version 22.0.0 (docker), Talk app version 12.0.0

**Comment by AndyScherzinger** [comment]
> On F-Droid this is the actual version at this moment and related to issue #1450 the next release (12.1.2) is planned for the 03.08.2021?

Yes while 12.1.0 and 12.1.1 have been tagged already but f-droid builds and releases themselves, so they publish not "us". So there is nothing we can do to improve f-droid releases...

**Comment by Torser76** [comment]
Je vous remercie pour vos réponses, depuis la mise à jour vers la version 22.0 j'arrive à me connecter avec talk mais depuis les smartphone Android les appels visio et audios ne fonctionne pas ! Bizarrement quand on passe un appel audio ou visio depuis un IPhone cela ça marche!

**Comment by AndyScherzinger** [comment]
Best to open an issue about that (in english if possible, I also had to send the last post to a translator, since I don't speak French unfortunately). Did you test in Wifi and cellular?

**Comment by Torser76** [comment]
Le problème c'est que sur Android pas moyen d'accepter les appels! Il y a ni notification ni aperçu d'appel avec Talk et ce n'est pas un soucis de réseau. Mais ça marche bien depuis un IPhone vers un téléphone Android! Curieux!

**Comment by Torser76** [comment]
sorry, i'm not very good in english

**Comment by AndyScherzinger** [comment]
no worries, just copy some auto translated text 👍

**Comment by MrColumbo** [comment]
I am experiencing the same issues - nextcloud is docker version 23 and app on Android and talk app on server latest version.

I get the screen to allow my smartphone to connect .....then enter OTP and allow my smartphone and then get the error and the page where I can add the url

These are the logs on the server



92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /index.php/login/flow HTTP/1.1" 200 8405 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /core/css/login/authpicker.css?v=cbee0c0d-0 HTTP/1.1" 200 691 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /apps/files_rightclick/css/app.css?v=62abc69f-0 HTTP/1.1" 200 745 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /core/css/guest.css?v=cbee0c0d-0 HTTP/1.1" 200 6154 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /index.php/apps/theming/styles?v=0 HTTP/1.1" 200 1476 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /core/js/dist/files_fileinfo.js?v=cbee0c0d-0 HTTP/1.1" 200 10021 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /core/js/dist/files_client.js?v=cbee0c0d-0 HTTP/1.1" 200 43456 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /apps/files_sharing/l10n/de_DE.js?v=cbee0c0d-0 HTTP/1.1" 200 6157 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /apps/files_sharing/js/dist/main.js?v=cbee0c0d-0 HTTP/1.1" 200 1634 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /apps/accessibility/l10n/de_DE.js?v=cbee0c0d-0 HTTP/1.1" 200 1815 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /core/l10n/de_DE.js?v=cbee0c0d-0 HTTP/1.1" 200 22770 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /apps/accessibility/js/accessibilityoca.js?v=cbee0c0d-0 HTTP/1.1" 200 6147 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /apps/files_rightclick/l10n/de_DE.js?v=cbee0c0d-0 HTTP/1.1" 200 1053 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /apps/files_rightclick/js/script.js?v=cbee0c0d-0 HTTP/1.1" 200 3781 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /apps/files_videoplayer/js/files_videoplayer-main.js?v=cbee0c0d-0 HTTP/1.1" 200 20034 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /core/js/login/authpicker.js?v=cbee0c0d-0 HTTP/1.1" 200 728 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /apps/files_rightclick/js/files.js?v=cbee0c0d-0 HTTP/1.1" 200 1832 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /core/img/background.png?v=0 HTTP/1.1" 200 10118 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /apps/theming/l10n/de_DE.js?v=cbee0c0d-0 HTTP/1.1" 200 2151 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /core/img/actions/confirm-white.svg?v=2 HTTP/1.1" 200 904 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /index.php/core/js/oc.js?v=cbee0c0d HTTP/1.1" 200 2483 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /core/js/dist/main.js?v=cbee0c0d-0 HTTP/1.1" 200 487531 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /index.php/js/core/merged-template-prepend.js?v=cbee0c0d-0 HTTP/1.1" 200 3955 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /index.php/apps/accessibility/css/user-a82fd95db10ff25dfad39f07372ebe37 HTTP/1.1" 200 5283 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:47 +0000] "GET /index.php/svg/core/logo/logo?color=ffffff&v=1 HTTP/1.1" 200 1583 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:58 +0000] "GET /index.php/login/flow/grant?clientIdentifier=&stateToken=0vEOdeCmI6Q9XXX...HTTP/1.1" 303 894 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:58 +0000] "GET /index.php/login?redirect_url=/index.php/login/flow/grant?clientIdentifier%3D%26stateToken%3D0vEOdeCmXXXX..... HTTP/1.1" 200 7328 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:58 +0000] "GET /core/js/dist/login.js?v=cbee0c0d-0 HTTP/1.1" 200 271092 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:59 +0000] "GET /core/img/actions/toggle.svg HTTP/1.1" 200 807 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:24:59 +0000] "GET /core/img/loading-dark.gif HTTP/1.1" 200 5180 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:25:09 +0000] "POST /index.php/login HTTP/1.1" 303 1008 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

127.0.0.1 - - [03/Dec/2021:18:25:15 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.51 (Debian) PHP/8.0.13 (internal dummy connection)"

92.116.176.208 - - [03/Dec/2021:18:25:15 +0000] "GET /index.php/login/challenge/totp?redirect_url=/index.php/login/flow/grant?clientIdentifier%3D%26stateToken%3D0vEOdeCmXXXX..... HTTP/1.1" 200 7475 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:25:15 +0000] "GET /custom_apps/twofactor_totp/css/style.css?v=54d09f91-0 HTTP/1.1" 200 666 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:25:15 +0000] "GET /apps/accessibility/l10n/de.js?v=cbee0c0d-0 HTTP/1.1" 200 1810 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:25:15 +0000] "GET /apps/files_rightclick/l10n/de.js?v=cbee0c0d-0 HTTP/1.1" 200 1031 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:25:15 +0000] "GET /apps/theming/l10n/de.js?v=cbee0c0d-0 HTTP/1.1" 200 2137 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:25:15 +0000] "GET /apps/files_sharing/l10n/de.js?v=cbee0c0d-0 HTTP/1.1" 200 6167 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:25:15 +0000] "GET /custom_apps/twofactor_totp/img/app.svg HTTP/1.1" 200 1542 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:25:15 +0000] "GET /core/l10n/de.js?v=cbee0c0d-0 HTTP/1.1" 200 22150 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:25:31 +0000] "POST /index.php/login/challenge/totp?redirect_url=/index.php/login/flow/grant?clientIdentifier%3D%26stateToken%3D0vEOdeCmXXXX..... HTTP/1.1" 303 1209 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:25:31 +0000] "GET /index.php/login/flow/grant?clientIdentifier=&stateToken=0vEOdeCmI6Q9XXX...HTTP/1.1" 200 7342 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:25:31 +0000] "GET /core/js/login/grant.js?v=cbee0c0d-0 HTTP/1.1" 200 819 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"

92.116.176.208 - - [03/Dec/2021:18:25:37 +0000] "POST /index.php/login/flow HTTP/1.1" 303 880 "-" "Oneplus ONEPLUS A6003 (Nextcloud Talk)"
