### ISSUE TITLE
Top bar hides partially under status bar when typing

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/talk-android#992]
In 11.0.0 Alpha 04, I get a strange behaviour. The top bar moves half way up and hides under the status bar when I tap on the input field.

Phone: Oneplus 8
Android: 11
OS: Oxygen OS 11.0.3.3.IN21BA

![Screenshot_20210202-164651_2](https://user-images.githubusercontent.com/16020496/106625196-bf011e80-6576-11eb-924e-e68b57f7d96a.jpg)

**Comment by tobiasKaminsky** [comment]
Do you have a notch on top?

**Comment by Chartman123** [comment]
No, Oneplus 8 has the camera integrated into the screen and rounded corners, but no notch.

**Comment by nickvergessen** [comment]
Still happens for me, but not as much anymore. The font does not underflow the header anymore, but there is also no padding/margin

**Comment by Chartman123** [comment]
12.0.0 alpha 13: still happens to me in the same way as presented in my original screenshot.

**Comment by nickvergessen** [comment]
Before keyboard opens | After
---|---
![Screenshot_2021-05-19-15-20-31-409_com nextcloud talk2](https://user-images.githubusercontent.com/213943/118819806-fdb4ad80-b8b5-11eb-95a1-a8b4b525a6f0.jpg) | ![Screenshot_2021-05-19-15-20-28-114_com nextcloud talk2](https://user-images.githubusercontent.com/213943/118819813-fee5da80-b8b5-11eb-9f94-b360d2a57cca.jpg)

**Comment by Chartman123** [comment]
Before: same as on your screenshot
After: like original post
