### ISSUE TITLE
[11 alpha04] Background of file uploading window

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#994]
Steps:

1. Choose a dark theme.
2. Go to the conversation with the user.
3. Choose to send the file.

The file transfer window background does not turn black for a dark theme.
This makes the font unreadable for the sending function.

![obraz](https://user-images.githubusercontent.com/47037905/106647991-edd7be80-658f-11eb-9769-24a65e22cb05.png)

App:
Android 10
Nextcloud Talk 11.0.0 Alpha 04

**Comment by mahibi** [comment]
might be a similar cause like it is for #915

**Comment by nickvergessen** [comment]
Also we should use similar labels like on web?

* Share from Nextcloud
* Upload new file

**Comment by Valdnet** [comment]
> Upload new file

I don't know if the users will get it right.
I would suggest leaving it as is "Upload local file" or changing it to "Upload file".

**Comment by nickvergessen** [comment]
Yeah my main focus was that the other option should be "Share..." Not "Upload ..." Because its not duplicating kr reuploading the file

**Comment by Valdnet** [comment]
> Yeah my main focus was that the other option should be "Share..." Not "Upload ..."

This should be changed and I am also in favor of it 😉.

**Comment by Valdnet** [comment]
@nickvergessen I released a PR #996 for "Shared" 😉. Now we are waiting to merge via @mahibi.

Additionally, I changed the description of the bug in issue because it is a window background problem and not a font.

**Comment by AndyScherzinger** [comment]
Fix is part of #1111 - https://github.com/nextcloud/talk-android/pull/1111/commits/6e16f428b32e521080ebfef7ec4a2f16209203d3
