### ISSUE TITLE
Add confirmation screen when uploading

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#995]
There should be a in between screen when uploading a file so you can see you didn't misclick on a wrong file.
Bonus points for a cutting tool when it's an Image like in many other messengers.

![Screenshot_2021-02-04-07-46-25-392_jp.naver.line.android.jpg](https://user-images.githubusercontent.com/213943/106855401-288b4500-66bd-11eb-916b-6b2be96f0859.jpg)

But at least a yes/no to make sure the user knows there will not be an editing option
![1612421315858.jpg](https://user-images.githubusercontent.com/213943/106855574-6d16e080-66bd-11eb-866c-f287aa65176c.jpg)

**Comment by mahibi** [comment]
agree. #987
